### ISSUE TITLE
type number will trigger ERROR TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mactanxin** [xtermjs/xterm.js#1011]
I implemented a shell page with Angular 4 + typescript,
every time I type any number "1-0" on the keyboard it'll trigger this error, I went through with debugger, if it's any other character it works, only when it's a number then it'll be undefined :
```
core.es5.js:1020 ERROR TypeError: Cannot read property 'length' of undefined
    at Terminal.innerWrite (xterm.js:4369)
    at xterm.js:4361
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:397)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:165)
    at ZoneTask.invoke (zone.js:460)
    at timer (zone.js:1732)
```
this is my code how I initialized
```
  initializeTerminal() {
    this.xterm = new Terminal({
      'cursorBlink': true,
      'tabStopWidth': 4,
      'cols': 80,
      'rows': 50,
      'focus': true
    });
    this.xterm.open(this.container.nativeElement);
    this.xterm.attach(this.ss);
    this.xterm._initialized = true;
  }
```

## Details
- Browser and browser version:  Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)
- OS version: Mac OS 10.12
- xterm.js version: 2.9.2

### Steps to reproduce

1. type any number will trigger
2.

**Comment by dasukeImaimobile** [comment]
Same issue.

**Comment by dasukeImaimobile** [comment]
I found why it didn't work.

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
