### ISSUE TITLE
Master issue for webpack/loadAddon issues

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1018]
I've seen a bunch of issues recently come in around how loadAddon works and I wonder if we're over complicating things. In today's world of bundlers and source maps, it appears very difficult to get this right in a way that will work across all build systems.

## Goals

- We need an easy way to load addons without forcing the user to download and parse/run the script. The core should be as slim as possible, leaving out optional components.
- It should work with webpack, browserify and vscode's module system (and more?)
- It should work nicely with TypeScript

### Current Situation

- We wrap addons in UMD which allows handling of the addon script in a plan browser environment, CommonJS environment and require.js environment. A problem here is that we needed to reorder the UMD definition as VS Code defines the `define` global, messing with the typical format and introducing issues for people eg. https://github.com/sourcelair/xterm.js/pull/994
- In a CommonJS environment the addon script attempts to load in the `Terminal` object via `require`, this causes issues for webpack https://github.com/sourcelair/xterm.js/issues/927
- `Terminal` inside addons is not typed currently as the definition for `Terminal` lies outside of the addon folder

## Potential Solutions

I'm not attempting to solve the problem right now, here are some ideas though:

- Have `loadAddon` pull in the script addon object and apply it to `Terminal`, as opposed to leaving it up to the addon to load `Terminal` (see https://github.com/sourcelair/xterm.js/issues/927#issuecomment-325210992)

  ```js
  public static loadAddon(addon: string, callback?: Function): boolean | any {
      // TODO: Improve return type and documentation
      if (typeof exports === 'object' && typeof module === 'object') {
        // CommonJS
        return require('./addons/' + addon + '/' + addon)(Terminal);
      } else if (typeof define === 'function') {
  ...
  ```
- Require bundling or concatenation when using addons?

If anyone has more insights into how this sort of dynamic loading at runtime issue is typically handled, I'd love to hear it :smiley: 

CCing people from related issues: @parisk @mofux @ficristo @dgriffen @ebertmi @rdicroce @jclangst @LucaT1 @jan0e @KagamiChan @vincentwoo

**Comment by blink1073** [comment]
This line would cause all of the addons to appear in the Webpack bundle: `return require('./addons/' + addon + '/' + addon)(Terminal);`.  Is it not possible to use another piece of metadata to distinguish a VSCode environment prior to checking for `define`?

**Comment by blink1073** [comment]
Here is the header used by `CodeMirror` for addons, which works quite well for us as a consumer: https://github.com/codemirror/CodeMirror/blob/master/addon/search/search.js#L12, we can `require('codemirror/addons/search/search')`, etc and only get the ones we want in our bundle.

**Comment by Tyriar** [comment]
@blink1073 it is likely possible using the solution put forward here https://github.com/sourcelair/xterm.js/pull/921/files, checking define.amd. I think a lot of problems are occurring because files are being shuffled around and both the addon and `Terminal` needs them to be in a particular spot.

The whole dynamic loading at runtime thing isn't a requirement, we just need the ability to *not* load some code by default. This could be a compile-time decision.

**Comment by ficristo** [comment]
My problem with the UMD check is only with the search addon, which is the only one that involve Typescript and Browserify. Checking for `define` and `define.amd` was the simplest thing I found to solve my issue with it.
Also, as I wrote elsewhere, I cannot use `loadAddon` since it assumes a specific path of the addons which would be wrong in my case. See #881 
```js
define(function (require, exports, module) {
    var Terminal = require("node_modules/xterm/dist/xterm"),

    require([
        "node_modules/xterm/dist/addons/fit/fit",
        "node_modules/xterm/dist/addons/search/search"
    ]);

    var term = new Terminal({});
});
```

**Comment by Tyriar** [comment]
> I cannot use loadAddon since it assumes a specific path of the addons which would be wrong in my case.

@ficristo I think this is the fundamental flaw with the current system, assuming the path can cause pain for consumers.

I kind of want to get it working with just plain file concatenation, the files are compiled separately via TS and then you just include via require/script the additional files, the only way this would work is making `Terminal` available as a global though, even in a CommonJS environment which is not ideal.

Perhaps a setting which lets you define the path to look for addons in, combined with passing `Terminal` into the addon is a good solution?

```js
public static setAddonDir(dir: string): void {
  Terminal.addonDir = dir;
}

public static loadAddon(addon: string): void {
  // if define && define.amd...
  if (typeof exports === 'object' && typeof module === 'object') {
    // CommonJS
    // Require the addon using the path in others and pass Terminal into the addon
    require(Terminal.addonDir)(Terminal);
  }
  // ...
}
```

**Comment by jgillich** [comment]
Why not just get rid of all the various module loader hacks and let the consumer deal with it? Maybe I'm missing something, but for me the easiest solution would be:

addon:

```
export function myAddon(terminal: Terminal) {
    terminal.prototype.doStuff = function() {}
}
```

loadAddon:

```
loadAddon(fn: (terminal: Terminal) => any) {
    return fn(Terminal)
}
```

consumer:

```
import {myAddon} from 'anywhere'
// or
let myAddon = require('anywhere')
// ...

xterm.loadAddon(myAddon)
```

**Comment by mofux** [comment]
@jgillich I think the module loader hacks exist because we cannot assume that keywords like the `export` statement are available in the current environment. As in your example

```javascript
export function myAddon(terminal: Terminal) {
    terminal.prototype.doStuff = function() {}
}
```

This statement will fail when loaded through a script tag directly in a browser 😞

**Comment by jgillich** [comment]
You would of course do usual commonjs/requirejs/global thing for exporting, and pretty much all module loaders will handle that just fine. It's requiring modules dynamically at runtime where issues arise, and you can fix that by not doing it at all.

**Comment by Tyriar** [comment]
@jgillich it's the wrapping in UMD where I get a little hazy, moving responsibility. Your proposal is a good way forward as long as we can get the all environments working. Am I right in the below example:

**CommonJS**

Bundler does everything:

```js
import {Terminal} from 'xterm';
import {searchAddon} from 'xterm/lib/addons/search'

Terminal.loadAddon(searchAddon)
```

**Web**

```html
<script src="./node_modules/xterm/lib/xterm.js"></script>
<!-- This just works as each addon looks for window.Terminal -->
<script src="./node_modules/xterm/lib/addons/search/searchAddon.js"></script>
```

**Require.js**

Anyone?

**Comment by LucaT1** [comment]
I really love your last idea @Tyriar, plus it's the thing I've always voted for!
Just one tough: Is there any method to disable extensions?(No, AFAIK) 
Well IMO it should be included, and in this case providing the name along with addon itself in the `loadAddon` API would be better.

**CommonJS**

Bundler does everything:
```js
import {Terminal} from 'xterm';
import {searchAddon} from 'xterm/lib/addons/search'

Terminal.loadAddon('search', searchAddon)

// Later on in the lifecycle, for whatever reason:
Terminal.removeAddon('search') // disableAddon(?)
```

And plus to support this feature on the web we'd need a more similar API(which is not a bad thing, since will lead to less difference/customer confusion about the usage of xterm)

**Web**
```html
<script src="./node_modules/xterm/lib/xterm.js"></script>
<!--
 This should create a global object referencing
 the addon somewhere like window.Terminal.addons['search'] (just for example)
 -->
<script src="./node_modules/xterm/lib/addons/search/searchAddon.js"></script>

<script>
// Same usage as in the bundler case:
Terminal.loadAddon('search', window.Terminal.addons.search) // This name is way too long tough.
Terminal.removeAddon('search') // disableAddon(?)
</script>
```

**Comment by jgillich** [comment]
requirejs would look like:

```
requirejs(['xterm', ''xterm/lib/addons/search'], function(xterm, search) {
    xterm.Terminal.loadAddon(search)
})
```

**Comment by ficristo** [comment]
I guess whatever decision will be taken here, the fix will not be backported to 2.9. Is it correct?
I'm asking because the whole point of the issues/PR I opened was to fix the search addon in the 2.9 branch.

**Comment by LucaT1** [comment]
As the 3.0 release is very close(about 1 moth) it's pointless to backport it. By the time this issue will be fixed the new release will be out(probably)

**Comment by ficristo** [comment]
I don't think I'll be able to use v3 anytime soon. See: https://github.com/sourcelair/xterm.js/pull/994#issuecomment-333127542

**Comment by jgillich** [comment]
@ficristo Not sure I follow, does v3 not support that version? What changed? I imagine several other CEF based apps don't always use the latest version either.

**Comment by ficristo** [comment]
From what I understood, v3 will support only the most recent version of the browsers.
While it is possible that everything will run on Chrome 49 (I didn't check), I feel it safer to remain on v2.

**Comment by Tyriar** [comment]
@ficristo we're targeting the latest version of major browsers, plus IE11. Because of this diversity, old versions of Chrome will be supported for a long time.

**Comment by ganeshkbhat** [comment]
Currently I am using webpack config from angular cli and am facing the same issue of .map parser. Any work around for issue of parsing maps or addon loader? ES5 code works fine, its an issue with ES6 systemjs

```
WARNING in ./node_modules/xterm/lib/addons/search/search.js.map
Module parse failed: /home/jack/Projects/C290/website/node_modules/source-map-loader/index.js
```

**Comment by jgillich** [comment]
@ganeshkbhat Add `.js` to the loadAddon function (#1013) in `node_modules/xterm/lib/xterm.js` and the error should go away. Or try [this](https://github.com/sourcelair/xterm.js/issues/877#issuecomment-330433211).

**Comment by ganeshkbhat** [comment]
@jgillich Nope did not work. I am still getting an error "You may need an appropriate loader to handle this file type."

**Comment by reem** [comment]
I am seeing source maps fail to parse as well, here is a full example error:

```
WARNING in ./~/xterm/lib/addons/search/SearchHelper.js.map
Module parse failed: /Users/reem/code/udacity/web-terminal-client/node_modules/xterm/lib/addons/search/SearchHelper.js.map Unexpected token (1:10)
You may need an appropriate loader to handle this file type.
| {"version":3,"sources":["../../../src/addons/search/SearchHelper.ts"],"names":[],"mappings":";;AAgBA;IACE,sBAAoB,SAAc,EAAU,4BAAiC;QAAzD,cAAS,GAAT,SAAS,CAAK;QAAU,iCAA4B,GAA5B,4BAA4B,CAAK;IAK7E,CAAC;IAQM,+BAAQ,GAAf,UAAgB,IAAY;QAC1B,EAAE,CAAC,CAAC,CAAC,IAAI,IAAI,IAAI,CAAC,MAAM,KAAK,CAAC,CAAC,CAAC,CAAC;YAC/B,MAAM,CAAC,KAAK,CAAC;QACf,CAAC;QAED,IAAI,MAAqB,CAAC;QAE1B,IAAI,QAAQ,GAAG,IAAI,CAAC,SAAS,CAAC,MAAM,CAAC,KAAK,CAAC;QAC3C,EAAE,CAAC,CAAC,IAAI,CAAC,SAAS,CAAC,gBAAgB,CAAC,YAAY,CAAC,CAAC,CAAC;YAEjD,QAAQ,GAAG,IAAI,CAAC,SAAS,CAAC,gBAAgB,CAAC,YAAY,CAAC,CAAC,CAAC,CAAC;QAC7D,CAAC;QAGD,GAAG,CAAC,CAAC,IAAI,CAAC,GAAG,QAAQ,GAAG,CAAC,EAAE,CAAC,GAAG,IAAI,CAAC,SAAS,CAAC,MAAM,CAAC,KAAK,GAAG,IAAI,CAAC,SAAS,CAAC,IAAI,EAAE,CAAC,EAAE,EAAE,CAAC;YACtF,MAAM,GAAG,IAAI,CAAC,WAAW,CAAC,IAAI,EAAE,CAAC,CAAC,CAAC;YACnC,EAAE,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC;gBACX,KAAK,CAAC;YACR,CAAC;QACH,CAAC;QAGD,EAAE,CAAC,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC;YACZ,GAAG,CAAC,CAAC,IAAI,CAAC,GAAG,CAAC,EAAE,CAAC,GAAG,QAAQ,EAAE,CAAC,EAAE,EAAE,CAAC;gBAClC,MAAM,GAAG,IAAI,CAAC,WAAW,CAAC,IAAI,EAAE,CAAC,CAAC,CAAC;gBACnC,EAAE,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC;oBACX,KAAK,CAAC;gBACR,CAAC;YACH,CAAC;QACH,CAAC;QAGD,MAAM,CAAC,IAAI,CAAC,aAAa,CAAC,MAAM,CAAC,CAAC;IACpC,CAAC;IAQM,mCAAY,GAAnB,UAAoB,IAAY;QAC9B,EAAE,CAAC,CAAC,CAAC,IAAI,IAAI,IAAI,CAAC,MAAM,KAAK,CAAC,CAAC,CAAC,CAAC;YAC/B,MAAM,CAAC,KAAK,CAAC;QACf,CAAC;QAED,IAAI,MAAqB,CAAC;QAE1B,IAAI,QAAQ,GAAG,IAAI,CAAC,SAAS,CAAC,MAAM,CAAC,KAAK,CAAC;QAC3C,EAAE,CAAC,CAAC,IAAI,CAAC,SAAS,CAAC,gBAAgB,CAAC,cAAc,CAAC,CAAC,CAAC;YAEnD,QAAQ,GAAG,IAAI,CAAC,SAAS,CAAC,gBAAgB,CAAC,cAAc,CAAC,CAAC,CAAC,CAAC;QAC/D,CAAC;QAGD,GAAG,CAAC,CAAC,IAAI,CAAC,GAAG,QAAQ,GAAG,CAAC,EAAE,CAAC,IAAI,CAAC,EAAE,CAAC,EAAE,EAAE,CAAC;YACvC,MAAM,GAAG,IAAI,CAAC,WAAW,CAAC,IAAI,EAAE,CAAC,CAAC,CAAC;YACnC,EAAE,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC;gBACX,KAAK,CAAC;YACR,CAAC;QACH,CAAC;QAGD,EAAE,CAAC,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC;YACZ,GAAG,CAAC,CAAC,IAAI,CAAC,GAAG,IAAI,CAAC,SAAS,CAAC,MAAM,CAAC,KAAK,GAAG,IAAI,CAAC,SAAS,CAAC,IAAI,GAAG,CAAC,EAAE,CAAC,GAAG,QAAQ,EAAE,CAAC,EAAE,EAAE,CAAC;gBACtF,MAAM,GAAG,IAAI,CAAC,WAAW,CAAC,IAAI,EAAE,CAAC,CAAC,CAAC;gBACnC,EAAE,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC;oBACX,KAAK,CAAC;gBACR,CAAC;YACH,CAAC;QACH,CAAC;QAGD,MAAM,CAAC,IAAI,CAAC,aAAa,CAAC,MAAM,CAAC,CAAC;IACpC,CAAC;IAQO,kCAAW,GAAnB,UAAoB,IAAY,EAAE,CAAS;QACzC,IAAM,UAAU,GAAG,IAAI,CAAC,SAAS,CAAC,MAAM,CAAC,KAAK,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC;QACtD,IAAM,eAAe,GAAG,IAAI,CAAC,4BAA4B,CAAC,UAAU,EAAE,IAAI,CAAC,CAAC,WAAW,EAAE,CAAC;QAC1F,IAAM,SAAS,GAAG,IAAI,CAAC,WAAW,EAAE,CAAC;QACrC,IAAM,WAAW,GAAG,eAAe,CAAC,OAAO,CAAC,SAAS,CAAC,CAAC;QACvD,EAAE,CAAC,CAAC,WAAW,IAAI,CAAC,CAAC,CAAC,CAAC;YACrB,MAAM,CAAC;gBACL,IAAI,MAAA;gBACJ,GAAG,EAAE,WAAW;gBAChB,GAAG,EAAE,CAAC;aACP,CAAC;QACJ,CAAC;IACH,CAAC;IAOO,oCAAa,GAArB,UAAsB,MAAqB;QACzC,EAAE,CAAC,CAAC,CAAC,MAAM,CAAC,CAAC,CAAC;YACZ,MAAM,CAAC,KAAK,CAAC;QACf,CAAC;QACD,IAAI,CAAC,SAAS,CAAC,gBAAgB,CAAC,YAAY,CAAC,MAAM,CAAC,GAAG,EAAE,MAAM,CAAC,GAAG,EAAE,MAAM,CAAC,IAAI,CAAC,MAAM,CAAC,CAAC;QACzF,IAAI,CAAC,SAAS,CAAC,UAAU,CAAC,MAAM,CAAC,GAAG,GAAG,IAAI,CAAC,SAAS,CAAC,MAAM,CAAC,KAAK,EAAE,KAAK,CAAC,CAAC;QAC3E,MAAM,CAAC,IAAI,CAAC;IACd,CAAC;IACH,mBAAC;AAAD,CA3HA,AA2HC,IAAA;AA3HY,oCAAY","file":"SearchHelper.js","sourceRoot":"."}
 @ ./~/xterm/lib/addons ^\.\/.*$
 @ ./~/xterm/lib/xterm.js
 @ ./src/js/components/terminal/index.js
 @ ./src/js/lib.js
 @ ./examples/web-terminal.js
 @ ./examples/index.jsx
 @ multi webpack-hot-middleware/client?reload=true babel-polyfill ./examples/index.jsx
```

haven't been able to get webpack to parse these files.

**Comment by sabbaka** [comment]
I'm also having problem with require and webpack, though managed to load it through dist, will see how it will work with addon for fit.

**Comment by parisk** [comment]
Started working on this. I made my testbed public here: https://github.com/parisk/xterm-webpack.

Right now I am getting the following error logs, when I am running `npm run build`

```
Hash: ad015a893c459fa739cb
Version: webpack 3.8.1
Time: 3712ms
    Asset     Size  Chunks             Chunk Names
bundle.js  3.08 kB       0  [emitted]  main
   [0] ./src/index.ts 288 bytes {0} [built]
    + 1 hidden module

ERROR in ./node_modules/xterm/src/Terminal.ts
Module parse failed: Unexpected token (51:8)
You may need an appropriate loader to handle this file type.
|
| // Declares required for loadAddon
| declare var exports: any;
| declare var module: any;
| declare var define: any;
 @ ./src/index.ts 3:17-46

npm ERR! Linux 4.4.0-98-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
```

**Comment by sabbaka** [comment]
@parisk I've tried to use 

```
            {
                test: /\.js.map$/,
                loader: 'source-map-loader'
            }
```

And 

```
            {
                test: /\.js.map$/,
                loader: 'ignore-loader'
            }
```

Build went fine ( without same error which is listed above ), but I've got this in browser console: 

```
Uncaught ReferenceError: require is not defined
    at Object.<anonymous> (xterm.js:3)

```

**Comment by Cheprer** [comment]
Just a follow up on https://github.com/xtermjs/xterm.js/issues/877 and post/hack from @KagamiChan to prevent webpack from bundling other addons is good but once you use loadAddon it loads anyway all the addons. Therefore adding this:

```.js
new webpack.ContextReplacementPlugin(/.*xterm\/lib\/addons/, /fit|attach\/fit|attach/)
```
With mentioned line of code: 
```.js
new webpack.IgnorePlugin(/^\.\/.*js.map$/, /.*xterm\/lib\/addons/)
```
Will load only the one you need in my case fit and attach
