### ISSUE TITLE
Provide modifier option for links

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1021]
VS Code only follows links when ctrl is held. Support for this inside xterm.js would be useful, specifically:

- If the modifier is set to ctrl, the link underline will only show up when ctrl is held
- Events are ignored unless ctrl is held

Also consider the following scenario:

1. `tmux`
2. `echo 'http://google.com'`

Ideally no modifier mousedown/click events on the link would be handed by tmux, but ctrl+mousedown/click events would be handled by Linkifier. Currently (after https://github.com/sourcelair/xterm.js/pull/1022) no modifier mousedown/click events on a link will never make it to tmux even when ctrl is required to follow the link.

**Comment by parisk** [comment]
Makes total sense, but I am worried that we might be adding too much logic into the core that does not have to do with the terminal itself.

Maybe we could rethink pulling the linkifier into an add-on and implement all that functionality there? This would require exposing more APIs though, so I am not sure if it's a viable solution.

**Comment by Tyriar** [comment]
Yeah we should think about pulling this out, because links deal with UI (tooltip, underline) it's difficult to get it right without adding a bunch of API.

**Comment by parisk** [comment]
i agree. Does it make sense to bundle this with the Component API?

**Comment by Tyriar** [comment]
Potentially yeah
