### ISSUE TITLE
The paste option is not shown in the context menu in Firefox

### ISSUE THREAD

**Issue by travisobregon** [xtermjs/xterm.js#1039]
In the latest version of Firefox, the option to paste is not there:

![image](https://user-images.githubusercontent.com/12074713/31281859-967c3c9c-aaa8-11e7-859f-acde85b50d77.png)

## Details
- Browser and browser version:  Firefox 56.0 (latest)
- OS version: Windows 7
- xterm.js version: 2.9.1 (v3 branch)

### Steps to reproduce

1. Follow the steps to run the demo app in the README

**Comment by joegaffey** [comment]
I've submitted a pull request to address this issue:
https://github.com/sourcelair/xterm.js/pull/1040 

You can try it here:
https://joegaffey-xtermjs.glitch.me/

**Comment by runner-mei** [comment]
This bug is happen on my firefox57/windows

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/418
