### ISSUE TITLE
fullscreen examples fails to change viewport

### ISSUE THREAD

**Issue by jmwilkinson** [xtermjs/xterm.js#1053]
SSCE: https://jsfiddle.net/zger2wtx/4/

```
var Terminal = require('xterm');

Terminal.loadAddon('fullscreen');  // Load the `fullscreen` addon

var term = new Terminal();

term.open(document.getElementById('terminal-container'));  // Open the terminal in #terminal-container

term.toggleFullscreen();
```

Using the example from the docs, when toggling fullscreen, the xterm viewport fails to change.  This results in the screen being covered by the term element but only the originally allocated space being usable.

The expectation is for toggling fullscreen to actually make the viewport fullscreen.

## Details
- Browser and browser version: Chrome
- OS version: Windows 10
- xterm.js version:  2.9.2

### Steps to reproduce

1. Run the example in the docs.

**Comment by Tyriar** [comment]
@parisk does fit needs to be called after full screening?

**Comment by parisk** [comment]
Yep. The [`fullscreen` addon](https://github.com/sourcelair/xterm.js/blob/v3/src/addons/fullscreen/fullscreen.js) just toggles a CSS class.

Updating the geometry of the terminal should be done separately.

Note to self: maybe it would be a good idea if we made this automatically in the future. Sounds quite intuitive.

**Comment by Tyriar** [comment]
Fullscreen may eventually be able to call into fit itself? 😮 https://github.com/xtermjs/xterm.js/issues/1128#issuecomment-394215111
