### ISSUE TITLE
any chance to make this package compatible with cssModules

### ISSUE THREAD

**Issue by veeramarni** [xtermjs/xterm.js#1074]
inline styling is getting popular and stuff like [`cssModules`](https://github.com/css-modules/css-modules) are recommended. It would be great if we see this taken into consideration. 

Example modules
---
https://github.com/Quramy/typescript-css-modules-demo (browsify way)
https://github.com/css-modules/webpack-demo (using webpack)

**Comment by parisk** [comment]
@veeramarni no plans yet. PRs are always welcome though!

**Comment by Tyriar** [comment]
I'd rather not complicate things further around this to be honest. We don't really have all that much CSS anymore also so effort here would provide minimal benefit. I also recently made this change which should sort of the majority of conflict issues https://github.com/sourcelair/xterm.js/commit/1d76cc921a53f16a0131b99a7a4dd407e343bfbc

**Comment by Tyriar** [comment]
Closing as there are no plans to change this.
