### ISSUE TITLE
Executing a command by javascript when clicking on a link

### ISSUE THREAD

**Issue by majid4466** [xtermjs/xterm.js#1107]
Is there a way to make the following work without having to manually press enter?
I need this to make a small automation tool.
```
<div id="terminal-container"></div>
<div id="commands">
    <a href="javascript:exec('ls -la');">ls -la</a>
    <a href="javascript:exec('sudo su');">sudo su</a>
</div>
<script>
function exec(cmd) {
    term.send(cmd); // needs manual Enter
    term.write(cmd); // also needs manual Enter
    term.writeln(cmd); // although the cursor advances to the next line, the command does not get executed
}
</script>
```

I have searched the issues and the closest thing I found was [this comment](https://github.com/xtermjs/xterm.js/issues/605#issuecomment-286870911) offering this method:

```
process.send({
  event: 'input',
  data: text
});

```
But where is ```process``` exposed? It does not seem to be accessible thorough ```term```.

**Comment by Tyriar** [comment]
@majid4466 `process` is on the nodejs process running https://github.com/Tyriar/node-pty, the demo makes use of node-pty in this file https://github.com/xtermjs/xterm.js/blob/v3/demo/app.js

**Comment by Anirudh16** [comment]
Hi @Tyriar may I how to execute bat files in xterm with node-pty,
Actually tried with term.write("command to be executed")
But it is not executing and we need to manually press enter from keyboard,is there any possibility to programatically use enter when the command is automatically called?

**Comment by Tyriar** [comment]
@Anirudh16 you would want to write to node pty and include a `\n`:

```
pty.write("command to be executed\n")
```

**Comment by Anirudh16** [comment]
> @Anirudh16 you would want to write to node pty and include a `\n`:
> 
> ```
> pty.write("command to be executed\n")
> `

Is it possible from xterm rather than node-pty?

**Comment by Anirudh16** [comment]
> @Anirudh16 you would want to write to node pty and include a `\n`:
> 
> ```
> pty.write("command to be executed\n")
> ```

@Tyriar Actually wanted to execute commands directly without pressing enter manually through keyboard. With writeln or using "\n" it just goes to another line but doesn't execute automatically.Any suggestions on that?

**Comment by Anirudh16** [comment]
> You need to write it to node-pty, not xterm.js. You're trying to simulate an xterm.js onData event which would be forwarded to node-pty, so call whatever you're using in your `onData` event handler.
> 
> Key presses: xterm.js -> node-pty
> Process data: node-pty -> xterm.js

@Tyriar Used pty.write("\r") and was able to execute the commands

**Comment by kopax** [comment]
I have tried with :

```
  sendMessage(event) {
    if (event.data && event.data.command) {
      const cmd = event.data.command + '\r\n'
      this.write(cmd)

      console.log(this.socket.send)
      this.socket.send(JSON.stringify({ method: 'command', command: cmd }))
      // this.socket.emit('data', event.data.command)
    }
  }
```. 


I still dont see the command sent, I can see the text being written in xterm.js, any clue ?

**Comment by jerch** [comment]
@kopax Your snippet lacks alot of context information and is not even valid Javascript/Typescript as you show it, missing the function keyword. Though I assume this is a method copied over, but then it is still unclear, what `this` is, where `socket` comes from and how xterm.js plays into it etc. Plz give a minimal comprehensible example with enough context info if you want ppl to be able to help you.

**Comment by Coffee-Nerd** [comment]
Did anyone ever figure this one out?
