### ISSUE TITLE
Cursor location is improper on window resize

### ISSUE THREAD

**Issue by shrihari-balasubramani** [xtermjs/xterm.js#1120]
## Details
- Browser and browser version: Chrome latest
- OS version: Mac latest
- xterm.js version: SourceLair

On window resize the cursor location is mis-aligned. Even after clicking at the end, cursor fails to position properly.

Initial cursor location:
<img width="1440" alt="screen shot 2017-11-09 at 11 07 24 am" src="https://user-images.githubusercontent.com/4323322/32590130-b33f278a-c53e-11e7-82db-d7bce64e612c.png">

Final cursor location after resizing back:
<img width="1440" alt="screen shot 2017-11-09 at 11 07 35 am" src="https://user-images.githubusercontent.com/4323322/32590140-c3deeef4-c53e-11e7-8430-2d9cafc4dee8.png">

### Steps to reproduce

1. Type a fairly long string in the terminal.
2. Resize the window horizontally until half the string is not seen.
3. Resize it back to full screen mode, observe the cursor position.
4. Try clicking at the end and observe the cursor is still not placed correctly.
5. Type something and the cursor is back to proper position.

Refer attached images.

**Comment by Tyriar** [comment]
This may be an issue in https://github.com/Tyriar/node-pty, not sure.

**Comment by chorgy** [comment]
Since there is no side ways scrolling, truncating rows to new width on resize would fix it.

https://github.com/chorgy/xterm.js/commit/fbd90473b16a876798a4fecea97e72a50464b0ec#diff-2dde2e231611debc03c006fe7eb37211R135

**Comment by Tyriar** [comment]
I think this issue is related to node-pty so closing off. Also if what @chorgy mentioned is part of the problem, that will get done in this issue https://github.com/xtermjs/xterm.js/issues/622
