### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by danieldaeschle** [xtermjs/xterm.js#1124]
Hello,

should i have to make the whole keyboard input by my own? is there no default? how can i create the backspace and all these keyboard shortcuts?

**Comment by Tyriar** [comment]
Can you elaborate a little on the specific issue? Have you tried to run the demo - I/O should work just fine on that.

**Comment by danieldaeschle** [comment]
The demo connects to my windows console. i want to emulate my own console, not connecting to a real...

**Comment by Tyriar** [comment]
@danieldaeschle you will want to use [`Terminal.write(text)`](https://xtermjs.org/docs/api/terminal/#writetext) for when you want to write something to the terminal and [`Terminal.on('data', fn)`](https://xtermjs.org/docs/api/terminal/#data) for handling input coming into the terminal.
