### ISSUE TITLE
copy shortcuts does not work under windows with chrome 

### ISSUE THREAD

**Issue by nzomkxia** [xtermjs/xterm.js#1129]
## Details
- Browser and browser version:  chrome  62.0.03202.94
- OS version:  windows7 
- xterm.js version:  2.9.2 

### Steps to reproduce

I've tried    https://github.com/xtermjs/xterm.js/issues/292 , add term.attachCustomKeyEventHandler  but it does not work, can't copy text from terminal

**Comment by Tyriar** [comment]
`attachCustomKeyEventHandler ` definitely works, you can check out how vscode does it here:

https://github.com/Microsoft/vscode/blob/1f040a1258c13f39938bb39d296b86db5df34152/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L306-L313

As mentioned in https://github.com/xtermjs/xterm.js/issues/292#issuecomment-250189337, you cannot override ctrl+shift+c in Chrome AFAIK as it's a browser shortcut.
