### ISSUE TITLE
Linkifying includes trailing '.'

### ISSUE THREAD

**Issue by rightparen** [xtermjs/xterm.js#1135]
## Details

Linkifying includes a trailing '.' as part of a URL's path.  This can cause problems in the common scenario of a terminal program displaying output that ends a sentence with a URL.

- Browser and browser version: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- OS version:  macOS Sierra Version 10.12.6
- xterm.js version: v2.9.2 and current master

### Steps to reproduce

1. Run the demo.

2. Enter the command:
`  echo "Please see https://github.com/xtermjs/xterm.js/issues."
`

3. Click the echoed link.

Expected:  Link references [https://github.com/xtermjs/xterm.js/issues](https://github.com/xtermjs/xterm.js/issues)
Actual:  Link references [https://github.com/xtermjs/xterm.js/issues.](https://github.com/xtermjs/xterm.js/issues.), which results in 404 Not Found.

**Comment by rightparen** [comment]
To be fair, the current behavior is technically correct, since '.' is a legal URL path character.  It's just less usable this way.

**Comment by egmontkob** [comment]
(See also #583.)

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/583
