### ISSUE TITLE
how to implement in an angular 4 project ?

### ISSUE THREAD

**Issue by shaulnaim** [xtermjs/xterm.js#1141]
i need to create client ssh terminal and want to use xtern.js
but couldn't understand how to install it (npm install --save xterm ? - not worked)  rather implement it in an angular 4 project
can you provide sample code and explanation???

its very important to me .
thanks
Shaul

**Comment by Tyriar** [comment]
Refer to the getting started docs https://github.com/xtermjs/xterm.js#getting-started and npm's docs for how to install modules https://docs.npmjs.com/

**Comment by Tyriar** [comment]
@shaulnaim I don't know anything about angular. xterm.js is just a JavaScript library, the API documentation is available with examples here https://xtermjs.org/
