### ISSUE TITLE
Unexpected underlining at emacs init (support CSI > Ps; Ps m)

### ISSUE THREAD

**Issue by robnagler** [xtermjs/xterm.js#1147]
## Details
- Browser and browser version: Version 62.0.3202.94 (Official Build) (64-bit)
- OS version: Mac OS X 10.12.6 and Windows 10
- xterm.js version: 2.9.2

### Steps to reproduce

1. Visit jupyter.radiasoft.org
2. Login with GitHub
3. Click My Server
4. Click New > select terminal
5. Type: `TERM=xterm emacs --kill`
6. The terminal will now be in underline mode.
7. Workaround: `TERM=ansi`

See also jupyter/terminado#51 and radiasoft/jupyter.radiasoft.org#15

![demo](https://user-images.githubusercontent.com/3825435/32810847-1730cf7c-c95a-11e7-8a2b-751f13a36ab8.png)

**Comment by robnagler** [comment]
I'm a user of Jupyter, not a developer. xterm.js is already bundled. It's quite a bit of work to dive into to bower, etc. to get all the pieces in place.

The demo would need to include ssh to be able to reproduce with xterm.js directly.  Do you have test config like that?

The `term` isn't available from the browser console so I couldn't turn on debug. Is there another global handle?

**Comment by takluyver** [comment]
The demo is a little standalone Javascript application in this repo - you'll need npm installed, but once you've got that, it should be easy to test this out:

https://github.com/xtermjs/xterm.js#demo

**Comment by robnagler** [comment]
It shows up in v3:

![screen shot 2017-12-12 at 2 48 15 pm](https://user-images.githubusercontent.com/5495179/33910322-988b03c4-df4b-11e7-90fb-1c1c0d2d8f7f.png)

**Comment by robnagler** [comment]
The debug log has an `ESC[>4m`, which has something to do with setting alternative numeric keypad modes.  I don't see a `CSI 4m`.

[debug.txt](https://github.com/xtermjs/xterm.js/files/1553427/debug.txt)

**Comment by Tyriar** [comment]
Looks like you're right, I think CSI >4m is being interpreted as enable underline instead of what it's meant to do:

> CSI > Ps; Ps m
          Set or reset resource-values used by xterm to decide whether
          to construct escape sequences holding information about the
          modifiers pressed with a given key.  The first parameter iden-
          tifies the resource to set/reset.  The second parameter is the
          value to assign to the resource.  If the second parameter is
          omitted, the resource is reset to its initial value.
            Ps = 0  -> modifyKeyboard.
            Ps = 1  -> modifyCursorKeys.
            Ps = 2  -> modifyFunctionKeys.
            Ps = 4  -> modifyOtherKeys.
          If no parameters are given, all resources are reset to their
          initial values.

From http://invisible-island.net/xterm/ctlseqs/ctlseqs.html

**Comment by parisk** [comment]
Similar case with tmux: https://github.com/xtermjs/xterm.js/issues/1150

**Comment by brandonccx** [comment]
I've got the similar case with tmux too, but entering  `reset` or `ls` will restore the style.

in xterm.js:

![image](https://user-images.githubusercontent.com/6195470/40043444-0fede510-5857-11e8-924d-649003b4f962.png)

in term client:

![image](https://user-images.githubusercontent.com/6195470/40043581-7c63a9d2-5857-11e8-9cb0-7a10b3d301c6.png)

**Comment by Tyriar** [comment]
I think this is fixed, correct me if I'm wrong.

/cc @jerch
