### ISSUE TITLE
Null pointer exception occurs in InputHandler

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1151]
VS Code issue: https://github.com/Microsoft/vscode/issues/38296

Failing line (`get` returns undefined): 

https://github.com/xtermjs/xterm.js/blob/eeda380b6776320d54bd6d8a34169b66f00acae0/src/InputHandler.ts#L97

**Comment by Tyriar** [comment]
I can't see anything that would cause this error unfortunately. I think we need a reproducible report from a user.

**Comment by AndrienkoAleksandr** [comment]
@Tyriar 

***"Visual Studio Code"***
Steps to reproduce:
On the Linux system(Ubuntu, Fedora doesn't matter): 

1. Open terminal in the VSCode.
2. Type in the terminal something. Content in the terminal should be bigger than one screen. Horizontal scrollbar should APPEARED .
3. Open Midnight Commander type: `mc` . But actually you can open any another program with text user graphic (nano, htop...)
4. Decrease terminal by height!
5. Go back to the normal screen. Ctrl + O for Midnight , or another hotkey depends on program.

![out-2](https://user-images.githubusercontent.com/6873095/34129695-b75af64a-e44d-11e7-9225-47760247f61f.gif)

***The same is always reproducible on the xterm.js demo.***
Expected result: terminal should turn back to the normal sceen and user can type something.
Actual result: user can not type something, terminal client completely dead...

**Comment by Tyriar** [comment]
Great repro steps thanks! 😃

**Comment by AndrienkoAleksandr** [comment]
Hi, @mofux this issue is still relevant in the master. I checked  for latest commit for 21 January  https://github.com/xtermjs/xterm.js/tree/f554f53bdab1eaf4675815e8ae475f1af2fffe9a 

xterm.js:892 Uncaught TypeError: Cannot set property '0' of undefined
    at InputHandler.addChar (xterm.js:892)
    at Parser.parse (xterm.js:2026)
    at Terminal.innerWrite (xterm.js:3629)
    at xterm.js:3614

Recorded video for demo:

![xterm js](https://user-images.githubusercontent.com/6873095/35241761-32c6649e-ffc0-11e7-834c-46b6fc5b986c.gif)

**Comment by mofux** [comment]
@AndrienkoAleksandr Yep you are right, I can reproduce on OSX following the steps in your video. One precondition for this bug seems to be that the primary buffer has all (or at least the amount of rows after resize + 1) filled.

**Comment by mofux** [comment]
Ufff this one is really hard to figure out, my guess is that the normal buffer is not resized properly while being inactive -- the resize code does take care of resizing both buffers, but still we end up with this weird situation. @Tyriar do you have any hints?

**Comment by Tyriar** [comment]
@mofux yeah that's what I would expect is happening. I managed to repro on my macbook with vim so I'll check it out.
