### ISSUE TITLE
Default fonts are vertically offset on some Linux distributions

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1170]
VS Code issue: https://github.com/Microsoft/vscode/issues/36322

![image](https://user-images.githubusercontent.com/2193314/34415401-658ec154-eba3-11e7-8e30-62bc74bd61ee.png)

Getting around this will probably involve drawing a character and checking the pixels to see where it was drawn in the cell and adjusting as necessary. From what I can see this just happens on some fonts which happen to be default on Kali and Debian.

**Comment by rhamilto** [comment]
I'm seeing this in Chrome 64 on Fedora 26 where the default monospace font is DejaVu Sans Mono, but not in Firefox 58 on the same platform using the same font.

**Comment by AndrienkoAleksandr** [comment]
+1  on Fedora 25. This bug do invisible symbol "_"

**Comment by Tyriar** [comment]
@AndrienkoAleksandr the underscore thing is probably happening due to https://github.com/xtermjs/xterm.js/issues/1138

This issue is about some fonts on Linux seems to not be drawing in the right spot.

**Comment by Tyriar** [comment]
This now affects Ubuntu 18.04 as well.

**Comment by Tyriar** [comment]
I believe this has the same root cause as other funny font problems in the DOM on Linux using Chrome 66:

![image](https://user-images.githubusercontent.com/2193314/42105345-d4e83988-7b84-11e8-87bf-aad29dc7ab33.png)

![image](https://user-images.githubusercontent.com/2193314/42105365-e623762c-7b84-11e8-915a-5da8589d2bad.png)

Maybe there's a Chromium bug tracking this?

**Comment by Demon000** [comment]
Seems like even using Roboto Mono still doesn't fix the vertical alligment. A good example is the tmux status bar as shown in this picture.

![image](https://user-images.githubusercontent.com/12939434/42186298-d734d5b6-7e54-11e8-93fd-5af3709f736d.png)

**Comment by scycer** [comment]
Do we have any ideas for a temporary fix? Just running into this issue with Ubuntu and electron.

**Comment by EmpireJones** [comment]
Another workaround: changing the font size from 14 -> 13 fixed the issue for me in vscode.

**Comment by zwhitchcox** [comment]
I'm havingthis problem on linux, but changing the font to 'Ubuntu mono' worked for me

**Comment by Tyriar** [comment]
This issue was closed off as it's fixed in the experimental WebGL renderer addon. It's not ready yet but I'm closing this off so I don't forget about it. See this query for current webgl addon issues https://github.com/xtermjs/xterm.js/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Faddon%2Fwebgl
