### ISSUE TITLE
Viewing demo on 0.0.0.0

### ISSUE THREAD

**Issue by uuf6429** [xtermjs/xterm.js#1173]
I was reading the `README.md` and I noticed a small oddity with the instructions.

The [linux/mac demo section](https://github.com/xtermjs/xterm.js#linux-or-macos) advises one to navigate to `0.0.0.0:3000` from a web browser, but surely that cannot work since `0.0.0.0` is a non-existent IP (generally used as a way to bind to "any IP")?

**Comment by Tyriar** [comment]
Certainly works :smile: 

![image](https://user-images.githubusercontent.com/2193314/34493269-f6601458-ef9f-11e7-81bb-90fbb7a27186.png)

@parisk wanted it to be 0.0.0.0 instead of 127.0.0.1, I think it was related to docker.

**Comment by parisk** [comment]
Yep, it's the preferred way to ensure that works inside of Docker. 

Also seems to be working on the Mac, so I am closing this.
