### ISSUE TITLE
Tabbing autocomplete oddity

### ISSUE THREAD

**Issue by npezza93** [xtermjs/xterm.js#1174]
I noticed in zsh when tab autocompleting text is getting kept around for some reason. This didn't use to happen in xterm so not entirely sure what caused it.

## Details
- Browser and browser version: Latest Chrome
- OS version: High Sierra 
- xterm.js version: Tip of v3 branch

### Steps to reproduce

1. Boot up zsh
2. Type 'cd' and hit tab

![tab](https://user-images.githubusercontent.com/5059927/34471317-101b6c94-ef14-11e7-9126-81f3edbc86fe.gif)

**Comment by npezza93** [comment]
Typing `cd[tab]` yields the following: 
<img width="686" alt="screen shot 2018-01-03 at 6 30 41 pm" src="https://user-images.githubusercontent.com/5059927/34544432-3f9a3e2c-f0b4-11e7-9fa8-59b564fcf27a.png">

The first 9 lines are typing `c` and `d`.

**Comment by npezza93** [comment]
This looks to be resolved now

**Comment by Tyriar** [comment]
I actually repro'd it in an external terminal at some point, so I think it was a problem with zsh.

**Comment by duguying** [comment]
@npezza93 maybe caused by you locale, my remote locale is en_GB but local locale is zh_CN, and it's occurred, i changed the local locale as en_GB, its running well.

**Comment by zakariaboualaid** [comment]
Not sure what was the resolution of this issue? cc @npezza93
