### ISSUE TITLE
alt+backspace does not delete word

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1179]
VS Code report: https://github.com/Microsoft/vscode/issues/40444

alt+backspace is meant to delete a word in bash. Note that it behaves differently to ctrl+w.

**Comment by bforbis** [comment]
Not sure where to ask about this since the linked issue for microsoft/vscode#40444 is locked, but this doesn't seem to solve the problem there for me using the latest version of vscode which should have pulled in this fix. Is there something I have to do to allow for Alt + Backspace to delete a single word? The current version of vscode is using xterm@3.15.0-vscode1

**Comment by Tyriar** [comment]
@bforbis what OS/shell?

**Comment by bforbis** [comment]
I'm using a bash shell on Mac OS.

This issue is most noticeable in file paths, where normally in a terminal ( I generally use iTerm2) , alt + backspace will delete one directory at a time, but in VSCode it will delete the full file path.

**Comment by Tyriar** [comment]
@bforbis I'm seeing the following:

- macOS, iterm: deletes single char
- macOS, terminal.app: deletes single char
- macOS, vscode: deletes whole path
- Linux, gnome terminal: deletes single directory
- Linux, vscode: deletes single directory

**Comment by bforbis** [comment]
An extra clarification from before, I am actually referring to ⌥ + Backspace (option + backspace), not Alt + Backspace. So maybe this is off topic from this issue?

The terminal I am using on Mac is iTerm2. By default, iTerm 2 is configured to send Esc+ for the left ⌥  key. I briefly checked a few other terminals I have installed.

- terminal.app: By default, left option is unescaped. Meaning ⌥ + backspace will delete only a single character. There is a configuration option to have ⌥ act as a Meta key, causing it to delete one word in a directory path as I expect.
- Hyper: By default, this acts the same as iTerm2 and will delete one word in a directory path.

So maybe I just need a way to configure my left ⌥  key to send a meta character in the integrated VSCode terminal to get the functionality I expect?

**Comment by Tyriar** [comment]
@bforbis now I'm confused, this:

```
{
    "key": "alt+backspace",
    "command": "deleteWordPartLeft",
}
```

Is an editor keybinding, not a terminal one...?

FYI for the terminal you can send whatever you want via the keybinding system by following this https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-from-a-keybinding

**Comment by bforbis** [comment]
I can't say I understand it fully either :), the settings in VSCode are pretty complex and I'm not sure if some of them interact poorly with others. From what I understand, the keyBindings in VSCode apply both to the normal editor pane and the integrated terminal, depending on if the keybinding command has a `when` condition or not.

By default, alt+backspace will do `deleteWordPartLeft` in the editor, and `deleteWordLeft` in the integrated terminal. Overriding the bindings to always do `deleteWordPartLeft` with no `when` condition gets me what I was looking for.

Hope that clears it up for you :)

**Comment by Tyriar** [comment]
You're right it does depend on the when clause, but the command you've assigned deletes a word part to the left inside the editor, not the terminal.

For terminal keybindings you may need to whitelist the command such that it's passed to the vscode keybindings system (not eaten by the shell) by adding it to `terminal.integrated.commandsToSkipShell`, then you will need a terminal-specific command. `workbench.action.terminal.sendSequence` I linked to earlier is how you do this in the terminal.

What I suspect happened is the problem fixed itself somehow and your alt+backspace keybinding  isn't actually doing anything because thee command is not whitelisted to skip the shell.

**Comment by bforbis** [comment]
Yeah, I just noticed that that particular override broke `deleteWordPartLeft` functionality for the file explorer sidebar. I used to be able to use alt+backspace to do that action when renaming files, and it broke by overriding the keybindings without a `when` condition.

To fix that, you can apply this keybinding with a `when` condition 
```
  {
    "key": "alt+backspace",
    "command": "deleteWordPartLeft",
    "when": "terminalFocus"
  },
```

**Comment by Tyriar** [comment]
@bforbis that keybinding doesn't do what you think it does. If you have terminal focus and press alt+backspace, that will delete the word part left inside **the editor**. Additionally, it won't do anything unless you have `deleteWordPartLeft` as an entry in the `terminal.integrated.commandsToSkipShell` setting.

**Comment by bforbis** [comment]
@Tyriar I'm not sure what you mean by "the editor". Do you mean the VSCode application as a whole, or do you mean just the editor pane within VSCode? I have not added anything to `terminal.integrated.commandsToSkipShell` and this keybinding seems to work properly within the integrated terminal, so something must be working.

**Comment by Tyriar** [comment]
By editor I mean the editor pane, that keybinding does nothing if you haven't set `terminal.integrated.commandsToSkipShell` and can be removed. You _must have_ fixed the issue you were having some other way.
