### ISSUE TITLE
Utilize web audio API for bell sound

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1181]
Data URIs require a specific content security policy exemption, this may not be needed for the web audio api

- VS Code PR to allow data URIs in CSP https://github.com/Microsoft/vscode/pull/40832
- Web audio api tutorial https://www.html5rocks.com/en/tutorials/webaudio/intro/

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/1200

**Comment by 199621** [comment]
Thank you good job I would have never fixed it
