### ISSUE TITLE
v3: is requirejs still supported?

### ISSUE THREAD

**Issue by ficristo** [xtermjs/xterm.js#1187]
I'm only looking inside the addon folder that inside build and lib folders.
No addons has an umd wrapper.

## Details
- Browser and browser version: -
- OS version: Windows 10
- xterm.js version: v3

### Steps to reproduce

1. Just look at build/addons/fit.js for example

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/pull/1130 for the changes/discussion. @parisk can confirm

**Comment by ficristo** [comment]
I don't see any mention about requirejs... is there?
It seems to me that PR talks only about modules and commonjs way to import files.

**Comment by ficristo** [comment]
It seems to me that also the browser usage for the addons is broken.

**Comment by FGasper** [comment]
Please LMK if there’s anything I can do to help resolve this more quickly, as it’s a direct impediment to adoption of v3 for our team.

**Comment by tsl0922** [comment]
It seems the [zmodem addon demo](https://github.com/xtermjs/xterm.js/tree/master/src/addons/zmodem/demo) is broken with errors like https://github.com/xtermjs/xterm.js/pull/1130#pullrequestreview-78576803.

**Comment by jpmasters** [comment]
We're having the same problem. We're using the control inside an Angular 1.6 component so we include the fit addon from \dist in an html script tag. This no longer works because the UMD header is missing. I've made a temp workaround by creating my own version of the fit addon but obviously it would be great to be able to use the real thing.

**Comment by parisk** [comment]
Just got on top of this. This should be fixed after https://github.com/xtermjs/xterm.js/pull/1199, since add-ons are compiled in UMD format. I think it's a good idea to publish another bugfix release for this.
