### ISSUE TITLE
Initial cursorBlink setting has no effect

### ISSUE THREAD

**Issue by blink1073** [xtermjs/xterm.js#1194]
Passing `cursorBlink: true` to the constructor does not enable cursor blinking.

## Details
- Browser and browser version: Firefox 57
- OS version: macOS 10.13
- xterm.js version: 3.0.1

### Steps to reproduce

1. Run the demo from master
2. Enable cursorBlink
3. Refresh the page
4. Click in the terminal - no blink
5. Disable and enable cursorBlink
6. Click in the terminal - blinking

**Comment by blink1073** [comment]
I am currently working around this by using `setOption('cursorBlink', true)` after the constructor.

**Comment by blink1073** [comment]
Actually, it looks like it has to be set after the canvas has been added to the DOM.

**Comment by mofux** [comment]
Just to verify, creating the terminal like `const xterm = new Terminal({ cursorBlink: true })` does not make the cursor blink, but calling `xterm.setOption('cursorBlink', true)` afterwards does make it blink?

From your repro steps, it looks like you are setting the cursorBlink option and then reload the demo page and expect the cursor to blink. This does not work as the setting is reset once you reload the demo page.

**Comment by blink1073** [comment]
The setting was showing as still on when I refreshed the page, but I didn't check in the console whether it was set.  Either way, in my app I had to manually call `xterm.setOption('cursorBlink', true)` after the the element was added to the DOM.

**Comment by blink1073** [comment]
Looks like it is sticky in the demo:

```
term.getOption('cursorBlink')
true
```

**Comment by Tyriar** [comment]
Pretty sure there is no code to make it sticky, I'm having a bit of trouble reproducing 😕

**Comment by blink1073** [comment]
The following can be used to ensure it is called in the constructor:

```diff
diff --git a/demo/main.js b/demo/main.js
index 95b15a0..5d7f30b 100644
--- a/demo/main.js
+++ b/demo/main.js
@@ -87,7 +87,7 @@ function createTerminal() {
     terminalContainer.removeChild(terminalContainer.children[0]);
   }
   term = new Terminal({
-    cursorBlink: optionElements.cursorBlink.checked,
+    cursorBlink: true,
     scrollback: parseInt(optionElements.scrollback.value, 10),
     tabStopWidth: parseInt(optionElements.tabstopwidth.value, 10)
   });
```

**Comment by Tyriar** [comment]
Oh you mean setting in the ctor doesn't work and it requires a setOption call?

**Comment by blink1073** [comment]
Yes, and more than that, you have to set it *after* the call to `open()`.  Might it make sense to ensure the proper cursor blink behavior on `focus()`?

**Comment by chabou** [comment]
Same issue.

There is a `TODO` here: https://github.com/xtermjs/xterm.js/blob/691f8a7567517b8908012eaaa2e69aac178f3618/src/renderer/CursorRenderLayer.ts#L47

I would suggest to call `this.renderer.onOptionsChanged();` here: https://github.com/xtermjs/xterm.js/blob/691f8a7567517b8908012eaaa2e69aac178f3618/src/Terminal.ts#L305

**Comment by Akryum** [comment]
Still an issue.

**Comment by Tyriar** [comment]
Works fine for me when I hardcode `cursorBlink: true` into the demo's Terminal ctor

**Comment by Akryum** [comment]
Well, I still have to do `xterm.setOption('cursorBlink', true)` after the terminal is created.

**Comment by Tyriar** [comment]
@Akryum created https://github.com/xtermjs/xterm.js/issues/2683 as I found a repro
