### ISSUE TITLE
Allow theme colors to be named colors?

### ISSUE THREAD

**Issue by blink1073** [xtermjs/xterm.js#1195]
Currently named colors are ignored by themes

## Details
- Browser and browser version: Firefox 57
- OS version: macOS 10.13
- xterm.js version: 3.0.1

### Steps to reproduce

1. Apply named colors like `'white'` to a theme
2. Colors are not handled by [_validateColor](https://github.com/xtermjs/xterm.js/blob/57c45712049e4fea67c28f614ec7fa5d6428e593/src/renderer/ColorManager.ts#L111) and fall back to the default

**Comment by blink1073** [comment]
Actually, it looks like [backgroundColor](https://github.com/xtermjs/xterm.js/blob/57c45712049e4fea67c28f614ec7fa5d6428e593/src/renderer/ColorManager.ts#L89) is the only one affected.

**Comment by Tyriar** [comment]
I'm not sure there's a way to do this without either dropping the validation all together or including a huge list of the keywords which will make the results JS quite large

**Comment by blink1073** [comment]
Hmm, fair enough.  My issue was that it failed silently and was not a documented restriction.  Perhaps a note in the `ITheme` [interface](https://github.com/xtermjs/xterm.js/blob/be18507df64d6f79113d216572921ddb912b8196/typings/xterm.d.ts#L93)?

**Comment by Tyriar** [comment]
@blink1073 how about validating all colors just like background but also check if the first char is a-z and assume it's correct if so?

**Comment by blink1073** [comment]
You could use a dummy DOM node and set the value and make sure it reads back the same.

https://stackoverflow.com/a/28440897

**Comment by Tyriar** [comment]
Cool trick 👍
