### ISSUE TITLE
Access to legacy DOM rendering?

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#1202]
I'd like to be able to pull the text output of xterm for archival purposes. Previously, pre-3.0, I would do this by inspecting the DOM at certain points and pull out the <spans> I was interested in, and save them separately.

Is there any way to achieve that now? I noticed screen reader support and thought that might work.

**Comment by Tyriar** [comment]
Weren't you after a getState function to cover this case? The screen reader support will have the plain non-colored text for the current viewport but you should be careful about relying on that as it's not API and you need to enable screen reader mode to turn it on.

**Comment by vincentwoo** [comment]
I wanted getState for a related but not exactly identical case. I can probably make-do by just-in-time creating terminals for display of archival data.

**Comment by Tyriar** [comment]
If you need to archive the entire buffer then scraping just the rows that are rendered wouldn't be enough?

**Comment by vincentwoo** [comment]
Right, but I wanted a way to have the ready-to-go in a format fit for render in a traditional DOM.

**Comment by mofux** [comment]
Although not currently implemented anymore, it shouldn't be too hard to create DOM nodes from the buffer by modifying the code from the old HTML renderer:

https://github.com/xtermjs/xterm.js/blob/2.9.2/src/Renderer.ts#L123-L323

You would basically have to get rid of the `_spanElementObjectPool` references (this was a cache of DOM nodes that we used to re-use DOM nodes). The internal data structure itself hasn't changed much.

**Comment by Tyriar** [comment]
@vincentwoo I'm still not quite understanding the reason you want to do this and why pulling from something like getState wouldn't be sufficient?

**Comment by vincentwoo** [comment]
get/setState allows me to put a terminal element in a particular state. However, trying to manipulate a bunch of canvasses is tricky for a client app. I store the results of code execution as terminal output for later review by customers. Previously, this was achieved by storing the raw input to terminals, and at render-time running them through a hidden xterm, pulling out the HTML, and displaying it. This had some advantages, because I could tweak styling or make output more readable. Now, I'll probably need to render a bunch of xterms on the page directly, which a less granular approach.

**Comment by Tyriar** [comment]
Maybe instead you should record the pty output stream and then playback using that?

**Comment by vincentwoo** [comment]
That's what we already do, but it's problematic. For instance, if you have a terminal with only one real line of output, *how much should be shown* is difficult to know in advance. I'd like to have a flat representation that browsers can scroll by default. We may need to display many of these on the same page at the same time.

**Comment by Tyriar** [comment]
@vincentwoo if you want the full buffer height you could grab `term.buffer._lines.length`, this will potentially create a very large texture though.

**Comment by vincentwoo** [comment]
I'm hacking around it now with:

```js
function lastPresentLine(terminal) {
  let i = terminal.buffer.lines.length - 1
  while (i >= 0) {
    if (_.any(terminal.buffer.lines.get(i), ([attr, char]) => char != ' ')) return i
    i--
  }
  return terminal.buffer.lines.length
}
```

**Comment by Tyriar** [comment]
@vincentwoo If you want where the cursor is you could also use `buffer.ybase + buffer.y`. This is less likely to change than the char data structure as well.

**Comment by vincentwoo** [comment]
Smart, smart.

**Comment by Tyriar** [comment]
I'll close this off in favor of the more targeted https://github.com/xtermjs/xterm.js/issues/1360
