### ISSUE TITLE
Bold and underline in version 3

### ISSUE THREAD

**Issue by scragg0x** [xtermjs/xterm.js#1209]
In version 2 there is xterm-bold, xterm-underline.  I styled them with css and just set a background color for these to mimic another terminal emulator.  I've been trying version 3, is it possible to do something like this?  To give text that were "bold" and "underline" arbitrary css styles.  Forgive me I don't know much about canvas.

**Comment by zolem** [comment]
I am not sure if this is what you need but I just figured out myself how to update the colors on the terminal. The documentation seems a bit out of date. If you look at the TS definition file you will see that there is a Theme object that you can pass as an option to the constructor of Terminal.

```ts
const xterm = require('xterm');
var theme = {
    black: "#000000"
}
var term = new xterm.Terminal({
    cursorHidden: true,
    theme: theme
});
```

The definition file will give you all the available options you can use that don't appear in the documentation.
https://github.com/xtermjs/xterm.js/blob/5888cd7938fa00d3756287dfcfd23f0ea0716d96/typings/xterm.d.ts#L14-L138

**Comment by Tyriar** [comment]
@scragg0x I think you're after `enableBold: false` in the settings which will render all bold text as regular text. You can't disable underline like this though, no one has asked for this, we would want to check whether it's supported in a few terminal emulators before pulling the trigger.

You can no longer manipulate the text using CSS.
