### ISSUE TITLE
Cursor with blink turned on is lagging behind

### ISSUE THREAD

**Issue by albinekb** [xtermjs/xterm.js#1216]
## Details
- Browser and browser version: `Electron 1.7.10` (chrome)
- OS version: macOS `10.13.2 (17C88)`
- xterm.js version: `3.0.2`

### Steps to reproduce

1. Open a new terminal
2. Press enter a couple times
3. Press `CMD+K` (clear) when the cursor appears
4. The cursor will not move into position until after it goes black and comes back again

Demo:

![kapture 2018-01-18 at 13 19 35](https://user-images.githubusercontent.com/5027156/35098223-9ae802b4-fc53-11e7-91ed-e9fd74d8e5f9.gif)

I think that even tough blink is active, the cursor should still move like a non-blinking cursor. Maybe even reset the blink states to "SOLID" when the cursor moves?

**Comment by Tyriar** [comment]
Yeah this is a problem with the cursor I just never got around to, there are times when it needs to hide/refresh but doesn't atm.

**Comment by Tyriar** [comment]
PR out https://github.com/xtermjs/xterm.js/pull/1217

**Comment by albinekb** [comment]
Woah, that was quick @Tyriar, superb! I'll test it out.

**Comment by albinekb** [comment]
Awesome 😍 🎉
