### ISSUE TITLE
Message incomplete display

### ISSUE THREAD

**Issue by GavinSong123** [xtermjs/xterm.js#1242]
Message on viewport incomplete display.

## Details
- Browser and browser version: Chrome Version 63.0.3239.132 (Official Build) (64-bit) 
- OS version: Ubuntu 16.04
- xterm.js version: 3.0.2

### Steps to reproduce
When I execute `ps -ef`, the message which return from server can not be display on the viewport completely. Like line two, the end of the message is `cc-console`.
![image](https://user-images.githubusercontent.com/14323101/35317044-c865cf80-010f-11e8-8085-f871007b8cee.png)

**Comment by Tyriar** [comment]
@GavinSong123 could you test using the master branch? This may be fixed already. If not could you put side-by-side of the output and what you expect?

**Comment by GavinSong123** [comment]
@Tyriar master branch is the same with 3.0.2
![image](https://user-images.githubusercontent.com/14323101/35377127-f2f332ea-01e8-11e8-83fc-b92de1cd1f4e.png)
Look at `/opt/google/chrome/chorme --type=render`, on the right side, after `render` there are many words. But on left side there is nothing.
In fact, if terminal on computer is small, the message can not be displayed completely. The reason of message on right side window can display is that I maximize the window and execute `ps -ef`, then return to the common size. I think terminal should maintain the original features of terminal and enhance it, although I do not know if this need is necessary. I think the message which is too long can be show with break line or add horizontal scroll bar on the view port.
I have an another question. If necessary, I will open a new issue.
I install xterm in my project with npm. And my project is based on angular 5+. When the project run with produciton mode. It has error
![image](https://user-images.githubusercontent.com/14323101/35378062-6584f7c8-01ec-11e8-9576-1b8c8fb96243.png)
ps: English isn't my native language, if I make a spelling error, don't hesitate to let me know it.

**Comment by mofux** [comment]
Could you please try to run the xterm.js demo by checking out the xterm.js master branch, then running `npm install` in that folder and once installed running `npm start`. Then connect to `http://localhost:3000`. To me it looks like either xterm.js or the backing tty has wrong dimensions (rows, columns).

**Comment by Tyriar** [comment]
@GavinSong123 so you're maximizing and then sizing down which is chopping off the content? If so this is tracked in https://github.com/xtermjs/xterm.js/issues/622

With production mode, maybe your bundler is optimizing away some important code? The only place where INVERSE is referenced is on the `FLAGS` enum

https://github.com/xtermjs/xterm.js/blob/8f1a629b48efc54760ba9c5ed4b3b15ef2850082/src/renderer/Types.ts#L9-L16

**Comment by GavinSong123** [comment]
@Tyriar OK, I got it.

About the error above, do you think the use of xterm.js with some other frame like angular is a situation need to consider? If it is not necessary, we can close this issue.

**Comment by Tyriar** [comment]
I would expect it to just work with angular, I'm pretty sure the problem is not on our side and would need more info to be able to investigate further.
