### ISSUE TITLE
cmd+page up/down no longer scrolls git log/diff

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1245]
This works in v3, not in master.

**Comment by Tyriar** [comment]
This was caused by https://github.com/xtermjs/xterm.js/pull/1215 /cc @markus-oberhumer

**Comment by Tyriar** [comment]
Ah I see what's happening. VS Code assigns page up/down to keybindings that call `scrollPages` to scroll the scrollback buffer and before cmd+page up/down would just do the regular page up.down behavior `\x1b[6~`, but now it's sending `\x1b[6;9~`.

**Comment by Tyriar** [comment]
Here's how Terminal.app works:

- page down: Scrolls scrollback
- shift+page down: Scrolls git
- cmd+page down: Navigates marks
- ctrl+page down: Scrolls scrollback (modifier not implemented)
- alt+page down: Scrolls scrollback (modifier not implemented)

iTerm2:

- page down: Scrolls git
- shift+page down: Scrolls scrollback
- cmd+page down: Scrolls scrollback
- ctrl+page down: Scrolls scrollback (modifier not implemented)
- alt+page down: Something different to us (outputs [6~, we output ;3~

Given this, it looks like we behaved closer to the other terminals before so I'm going to revert this change as it will negatively impact the vast majority of users. I'm open to matching iTerm2's behavior for alt in the future though.

**Comment by markus-oberhumer** [comment]
I'm not fully sure what this issue is about (I don't use a Mac), but if you build the current xterm-331 on Linux with `./configure --enable-trace` and then press PageDown, Ctrl+PageDown and Alt+PageDown you will see the following log in the file `Trace-parent.out`.

This would match my original patch.

```
[...]

KeyPress 0x75
Input keysym 0xFF56, 0:'' Mod2 7bit CursorKey EditFkey
xtermStateToParam 0x10
...xtermStateToParam 0
...ModifyOtherKeys(0,0) off
writePtyData 4:\033[6~

[...]

KeyPress 0x75
Input keysym 0xFF56, 0:'' Control Mod2 7bit CursorKey EditFkey
xtermStateToParam 0x14
...xtermStateToParam 5 MOD_CTRL
...ModifyOtherKeys(0,5) off
writePtyData 6:\033[6;5~

[...]

KeyPress 0x75
Input keysym 0xFF56, 0:'' Mod1 Mod2 8bit CursorKey EditFkey
xtermStateToParam 0x18
...xtermStateToParam 3 MOD_ALT
...ModifyOtherKeys(0,3) off
writePtyData 6:\033[6;3~

[...]
```

**Comment by Tyriar** [comment]
@markus-oberhumer the issue is about what terminal emulators that build on top of xterm.js use to navigate scrollback. My main Linux box is off atm but for the 2 mac terminals I used it is assigned to shift+page up/down and just page up/down. Now for the latter case where the terminal emulator overrides page up/down, with your patch there is no way for the user to send standard page up/down keystrokes which means they cannot scroll applications using page up/down.

One of the main related issues to this is that right now xterm.js has no nice way of customizing keystrokes (https://github.com/xtermjs/xterm.js/issues/487), meaning there's no workaround for the above problem. Eventually it would be ideal for consumers to customize what they actually want to do, in the meantime we can just provide good defaults that work for most people.

Also we're not trying to align 100% with xterm but to align with what the standard appears to be based on popular terminals (typically I use xterm/[+this doc](invisible-island.net/xterm/ctlseqs/ctlseqs.html), VTE, Terminal.app and iTerm2 as a basis).

**Comment by markus-oberhumer** [comment]
So you want Cmd+PageUp to send a plain PageUp to the client app because the real PageUp is consumed by some terminal emulator?

Something like the patch below might work (untested), but I have a feeling this problem should be given more thoughts.

```
diff --git a/src/Terminal.ts b/src/Terminal.ts
index 5536cf0..a006d27 100644
--- a/src/Terminal.ts
+++ b/src/Terminal.ts
@@ -1600,7 +1600,7 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
         // page up
         if (ev.shiftKey) {
           result.scrollLines = -(this.rows - 1);
-        } else if (modifiers) {
+        } else if (modifiers && !ev.metaKey) {
           result.key = C0.ESC + '[5;' + (modifiers + 1) + '~';
         } else {
           result.key = C0.ESC + '[5~';
@@ -1610,7 +1610,7 @@ export class Terminal extends EventEmitter implements ITerminal, IInputHandlingT
         // page down
         if (ev.shiftKey) {
           result.scrollLines = this.rows - 1;
-        } else if (modifiers) {
+        } else if (modifiers && !ev.metaKey) {
           result.key = C0.ESC + '[6;' + (modifiers + 1) + '~';
         } else {
           result.key = C0.ESC + '[6~';
```

**Comment by Tyriar** [comment]
But that's for the mac case, on Linux/Windows it's even worse as there is no cmd key. ctrl, shift and alt are all overridden so with that proposal there's no way to send page up/down.
