### ISSUE TITLE
Improve DOM-based integration tests

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1247]
Right now we're on jsdom which has a lot of problems and as a result we don't write that many integration tests. https://github.com/GoogleChrome/puppeteer

**Comment by bgw** [comment]
At `$dayjob`, we use a combination of JSDom and Puppeteer.

Puppeteer is definitely a lot more powerful, but it's also slower, and it's harder to get tests to run reliably. Puppeteer has an async API (it's easy to introduce race conditions) and more stuff that can go wrong. As a result, we've only built tests using Puppeteer for our most important surfaces.

I'd recommend using a combination of both, or just sticking with JSDom.

**Comment by Tyriar** [comment]
@bgw I think your idea of adding node-canvas sounds like the most attractive first step atm
