### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstElementChild' of undefined

### ISSUE THREAD

**Issue by lxlenovostar** [xtermjs/xterm.js#1252]
Error messages: "Uncaught TypeError: Cannot read property 'firstElementChild' of undefined," , when I run "let subjectRow = term.rowContainer.firstElementChild;".

## Details
- Browser and browser version:    Chrome 63.0.3239.132
- OS version:                                  windows 7
- xterm.js version:                          xterm@3.0.2

### Steps to reproduce
the html file is:
```
 <!doctype html>
  <html>
    <head>
      <link rel="stylesheet" href="D:\node_modules\xterm\dist\xterm.css" />
      <script src="D:\node_modules\xterm\dist\xterm.js"></script>
    </head>
    <body>
      <div id="terminal"></div>
      <script>	
		let section = document.createElement('div');
                section.id = 'terminal-0';
                section.className = 'terminal';
		
		let terminal = document.getElementById("terminal");
		
		terminal.appendChild(section);
		
		let term = new Terminal();
                term.open(section);
                term.write('Hello from \033[1;3;31mxterm.js\033[0m $ ')
		
		let subjectRow = term.rowContainer.firstElementChild;
		
      </script>
    </body>
  </html>

```

**Comment by lxlenovostar** [comment]
I‘m a new one in JS. Is this a problem with my usage?

Thank you.

**Comment by AndrienkoAleksandr** [comment]
@lxlenovostar you did not attached element to dom html. Before calling "document.getElementById" element should be attached to html page. Like variant it can be: 
`document.body.appendChild(section)`

And id = 'terminal-0', so: 
`let terminal = document.getElementById("terminal-0");`

**Comment by lxlenovostar** [comment]
@AndrienkoAleksandr   I think `let terminal = document.getElementById("terminal");` should be right, beacuse ` <div id="terminal"></div>` . I want to add a child(terminal-0) to  terminal. 

Thank you.

**Comment by Tyriar** [comment]
There is no row container in v3, you cannot do this anymore.
