### ISSUE TITLE
canvas has static id attribute

### ISSUE THREAD

**Issue by zxdong262** [xtermjs/xterm.js#1255]
the canvas has id such as `xterm-selection-layer`, when run multiple xterm inst in same page, it has a potential problem: can not select it by id, and it has no className. will you consider using class or unique id instead ?

## Details
- Browser and browser version: all
- OS version: all
- xterm.js version: 3.0.1

### Steps to reproduce

just use it.

**Comment by Tyriar** [comment]
I'm not even sure the id's are used, I think it was added to identify them when looking at the DOM.
