### ISSUE TITLE
why the terminado demo in docs not work?

### ISSUE THREAD

**Issue by walunte** [xtermjs/xterm.js#1259]
All script loaded correctly but i still get this error。
Uncaught TypeError: term.terminadoAttach is not a function
    at WebSocket.<anonymous> ((index):19)

I run the terminado's single.py demo,it work very well and it use make_terminal not new Terminal。
Is that because the docs' demo is outdated?

**Comment by mvasilkov** [comment]
You need to run `terminado.apply(Terminal)` first.

See my updated example here: https://github.com/mvasilkov/python-browser-based-terminal/commit/0629e19072e843f1af133b30ecd95f1c6228af5b

**Comment by parisk** [comment]
Nah, I forgot to update the terminado guide after the 3.0 release.

@walunte you have to use the new add-on API we published with xterm.js 3.0: https://xtermjs.org/docs/guides/using-addons/.

Closing in favor of https://github.com/xtermjs/xtermjs.org/issues/37.

**Comment by walunte** [comment]
thank you ~
