### ISSUE TITLE
CSS Web Fonts are no longer supported

### ISSUE THREAD

**Issue by khuongduybui** [xtermjs/xterm.js#1261]
In 2.x version, I can use CSS to set the `font-family` for the terminal to a CSS Web Font declared with `@font-face`.

In 3.x version, I cannot use CSS to set the `font-family` for the terminal but instead have to use the `{fontFamily}` option, which only works with fonts that already exist in the operating system.

## Details
- Browser and browser version: all of them
- OS version: all of them
- xterm.js version: 3.x

### Steps to reproduce

1. Include a CSS Web Font, such as [Fira Code](https://github.com/tonsky/FiraCode/blob/master/distr/fira_code.css)
2. Create a new Terminal with the web font

**Comment by khuongduybui** [comment]
Actually, it kinda works, I just need to make sure the font is fully loaded before the terminal is rendered.

**Comment by Tyriar** [comment]
@khuongduybui 👍 this was brought up in another issue, just make sure you call `Terminal.open` when things are ready.
