### ISSUE TITLE
Support vim cursor key bindings h j k l

### ISSUE THREAD

**Issue by StefanScherer** [xtermjs/xterm.js#1262]
Using vim in Play-with-Docker or eg. the Azure Cloud Shell does not work fluently as the standard vi/vim key binding to move a cursor does not repeat automatically when you press down one of `h`, `j`, `k` and `l` to move the cursor more than just one line or column.

## Details
- Browser and browser version: 
Safari 11.0.3 (what 1103? Remember these C64 games? :-) )
Chrome 63.0.3239.132
- OS version: 
macOS 10.13.3
- xterm.js version: 
built-in in play-with-docker or Azure Cloud Shell.

### Steps to reproduce

1. Open Azure Cloud Shell or play-with-docker
2. `vi .bashrc` # or another file
3. Press `l` for some seconds, it should constantly move the cursor to the right.

vi / vim has key bindings so a developer does not have to move her/his hands to the cursor block
- `h` move cursor to the left
- `j` move cursor down
- `k` move cursor up
- `l` move cursor to the right

**Comment by Tyriar** [comment]
To clarify, this is specifically about holding down keypresses repeating the char on macOS? Like https://github.com/xtermjs/xterm.js/issues/265 ?

**Comment by StefanScherer** [comment]
Oh, yes exactly. 

![azure-vim](https://user-images.githubusercontent.com/207759/35637141-a9afc0ce-06b3-11e8-8b2f-e4ab1d646a19.gif)

Wow, didn't know that VSCode's terminal also has this behaviour.
I found that yesterday in Azure Cloud Shell.

So this is a duplicate issue in favor of #265.
