### ISSUE TITLE
shift + alt + 3 shortcut support

### ISSUE THREAD

**Issue by Yanpas** [xtermjs/xterm.js#1267]
## Details
- OS version: linux|windows 10
- xterm.js version: the one that comes with vs code 1.19.3

run terminal, hit shift + alt + 3
actually alt + 3 passed to terminal
shift + alt + 3 shortcut types # in the start of a line and hits enter.

Actually it is "Alt + #"

Original issue: https://github.com/Microsoft/vscode/issues/42629

**Comment by saamalik** [comment]
This is already fixed in #1231 . The same sequence `shift+alt+#` was actually tested.

**Comment by saamalik** [comment]
Btw here are other standard sequences supported in PR #1231 . Try with in bash:

```
    $ touch p1 p2 p3
    $ echo a b c d
    $ <ctrl+alt+y> # a
    $ <alt+.> # d
    $ ls p<alt+shift+/> #list glob-matching files
    $ ls p<alt+shift+8> # insert glob-matching files as arguments
    $ echo bad command do not run <alt+shift+3> # comment out command
```

**Comment by Tyriar** [comment]
Marked #1231 as fixes this.
