### ISSUE TITLE
Links that wrap to the next line are truncated

### ISSUE THREAD

**Issue by amejia1** [xtermjs/xterm.js#1270]
For any link that wraps to the next line, xterm.js will only capture the first portion of the link on the first line and make it clickable. The wrapped portion on the next line is not made clickable. Furthermore, clicking on the first portion will send you to the truncated first portion of the link.

## Details
- Browser and browser version: Latest Chrome 63.*, Atom 1.23.3
- OS version: Windows 10 and Ubuntu 16.04.3 LTS
- xterm.js version: 3.0.2 and latest master branch

### Steps to reproduce

1. Write a link to the terminal which causes xterm.js to wrap it to the next line.
2. Hover over the link, the first portion gets underlined, the wrapped portion doesn't do anything.
3. Click on the first portion, it will send you to the first portion of the link instead of the entire link.

### Demo

![xterm-truncated-links](https://user-images.githubusercontent.com/86134/35768803-b7919910-08cf-11e8-89a0-a8b1687e5f57.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/24
