### ISSUE TITLE
[Angular 5] Module parse failed: Octal literal in strict mode

### ISSUE THREAD

**Issue by MaximeAnsquer** [xtermjs/xterm.js#1277]
Hello,

I integrated xterm into my Angular 5 project, and everything works fine except the colors. 

``` javascript
let term = new Terminal();
term.write('Hello from \033[1;3;31mxterm.js\033[0m $ ');
```
Be cause of the `\033[`, this produces the following error : 

```
Module parse failed: Octal literal in strict mode
You may need an appropriate loader to handle this file type.
```
Could you help me solve this problem?
Thank you very much!

## Details
- Browser and browser version: Chrome 63.0.3239.132
- OS version: Windows 10
- xterm.js version: 3.0.2

### Steps to reproduce

1. Create a new Angular 5 project with the latest version of angular-cli
2. Integrate xterm.js basic example from the readme as explained there
3. Run npm start

**Comment by Tyriar** [comment]
I don't know much about angular, you will need to look up the error you're seeing as it's related to your module bundler.

**Comment by MaximeAnsquer** [comment]
@johntostring Nope sorry :/

**Comment by MaximeAnsquer** [comment]
@ficristo This solved it, thansk a lot !

**Comment by cnyin** [comment]
answer from @ficristo worked
