### ISSUE TITLE
Text cursor when hovering over scrollbar

### ISSUE THREAD

**Issue by duncanwerner** [xtermjs/xterm.js#1279]
## Details
- Browser and browser version: Electron 1.8.2
- OS version: Windows 10
- xterm.js version: 3.0.2

### Steps to reproduce

1. Hover over scrollbar
2. Text cursor (I-bar) displays instead of default cursor

This is because the last stylesheet rule sets cursor for the toplevel element. My workaround is just adding a canvas selector,

```
.xterm:not(.enable-mouse-events) canvas {
    cursor: text;
}
```

**Comment by Tyriar** [comment]
Fixed in 3.1 https://github.com/xtermjs/xterm.js/issues/1067
