### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of undefined 

### ISSUE THREAD

**Issue by RalphHogenbirk** [xtermjs/xterm.js#1281]
I'm using xterm for the opensource plugin 'Pymakr' in Atom. It's used to connect to the Pycom boards using the micropython REPL. It's working great, but once in a while this error pops up a few times in a row. Multiple users are reporting it and I've seen it a few times as well but it's solved after a reboot and doesn't happen again for a long time.

Now, I don't know if this is a bug in the xterm lib or that I'm doing something wrong when writing data to the terminal. I'm just posting here to be sure.

```
At C:\Users\<USER>\.atom\packages\Pymakr\node_modules\xterm\lib\SelectionManager.js:244

TypeError: Cannot read property '2' of undefined
    at SelectionManager._onSingleClick (/packages/Pymakr/node_modules/xterm/lib/SelectionManager.js:244:17)
    at SelectionManager._onMouseDown (/packages/Pymakr/node_modules/xterm/lib/SelectionManager.js:201:22)
    at /packages/Pymakr/node_modules/xterm/lib/SelectionManager.js:51:90)
```

## Details
- Browser and browser version: Atom (1.23.4) / Pymakr package (1.2.6)
- OS version: Mac OS 10.11.6
- xterm.js version: 2.9.2 

### Steps to reproduce
Unknown

**Comment by Tyriar** [comment]
This is fixed in v3

**Comment by RalphHogenbirk** [comment]
Thanks @Tyriar, will start implementing v3 soon.
