### ISSUE TITLE
Fit addon covers scrollbar

### ISSUE THREAD

**Issue by duncanwerner** [xtermjs/xterm.js#1284]
If you call `fit`, it seems to extend the text area over the scrollbar. The mouse has a text cursor and you can't click the scrollbar. Without `fit`, it seems fine. It looks like fit adds 1 or 2 too many columns. 

In the last release build (3.0.2) it had the text cursor, but clicking the scrollbar worked.

## Details
- Browser and browser version: Electron 1.8.2, Chrome 64.0.3282.140, FFx 58.0.1
- OS version: Windows 10
- xterm.js version: 3.1.0 (npm version) 

### Steps to reproduce

1. Create, open xterm instance
2. Call fit()
3. Mouse over scrollbar: shows text cursor
4. Click scrollbar: nothing
5. Remove fit call, works OK

### Example

```html
<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
<title>Test Page</title>
<style>

  #terminal {
    border: 1px solid gray;
    width: 632px;
    height: 333px;
    margin: auto;
  }

</style>
<link rel="stylesheet" href="../node_modules/xterm/dist/xterm.css">
</head>
<body>

<div id='terminal'>

</div>

<script src="../node_modules/xterm/dist/xterm.js"></script>
<script src="../node_modules/xterm/dist/addons/fit/fit.js"></script>
<script>
  Terminal.applyAddon(fit);

  term = new Terminal({rows: 40, cols: 40});
  term.open(document.querySelector("#terminal"));
  term.focus();

  // fit fits properly, but breaks scrollbar
  term.fit();

  // remove the fit call and scollbar works OK

  for( let i = 0; i< 1000; i++ )
    term.write(`Line ${i}\r\n`);


</script>
</body>
</html>
```

**Comment by dgriffen** [comment]
The problem seems to be fixed by changing the identified line to ``this._terminal.screenElement.style.width = `${this.dimensions.canvasWidth}px\`;``

Even without fit the behavior with that line causes issues because for a small area to the right of the canvas you are able to still select (that area being the width of the scroll bar).
