### ISSUE TITLE
Hello, I am interested in contributing with this work through a Spanish translation, which is my native language.

### ISSUE THREAD

**Issue by LuigiBaute** [xtermjs/xterm.js#1285]

**Comment by Tyriar** [comment]
Hi @LuigiBaute, I don't think we should translate any of the developer documentation as it changes so frequently and therefore any translations would go stale very quickly. As for localizing the actual product, this will be supported once https://github.com/xtermjs/xterm.js/pull/1182 is merged as it introduces the first strings. But we're leaving it up to consumers to localize these https://github.com/xtermjs/xterm.js/pull/1182/files#diff-7033d1b5b24001987e75925ebd825da1R6
