### ISSUE TITLE
Copying a multi line selection will trim the right whitespace on wrapped lines incorrectly

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1286]
![image](https://user-images.githubusercontent.com/2193314/36261569-9fd4f788-1219-11e8-8f42-62019a1aafc4.png)

See https://github.com/Microsoft/vscode/issues/43696

**Comment by jerch** [comment]
@Tyriar I checked this with the landed PR #1775, seems to be fixed now.
