### ISSUE TITLE
.xterm-screen is on top of .xterm-viewport, preventing mouse interaction with scroll bar

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1289]
On master:

![image](https://user-images.githubusercontent.com/2193314/36338340-06113d20-1361-11e8-8f7b-68cdb17e0696.png)

**Comment by mofux** [comment]
Strange... I'm offline this weekend 😟. Will look at it on monday.

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/1284
