### ISSUE TITLE
Can't select text on iOS

### ISSUE THREAD

**Issue by ColdGrub1384** [xtermjs/xterm.js#1291]
I can't select text in terminal on iOS. 
I tried with a Web view on my app and with Firefox with the demo.

## Details
- Browser and browser version: WebKit iOS 11 (all iOS browsers)
- OS version: iOS 11
- xterm.js version: 3.1

### Steps to reproduce

1. Run the demo.
2. Try to select text on mobile device.

**Comment by Tyriar** [comment]
We don't support mobile at the moment, most of xterm.js will work fine but some components won't (eg. IME, selection).

**Comment by rgaufman** [comment]
Is there a solution to this? :)
