### ISSUE TITLE
[Usage/Help] Creating server on Java. What socket events to listen to?

### ISSUE THREAD

**Issue by xxRockOnxx** [xtermjs/xterm.js#1292]
Basically need to use Java instead of node. Although I'm good at js, I'm not really good at node/socket currently.

If I understand it correctly, I just need to create a socket endpoint for the client, but what socket events should I listen for? Anyone point me to the right direction? Not sure what to look at `src`.

**Comment by Tyriar** [comment]
I recommend studying how the demo works, here is the front end that runs in a browser https://github.com/xtermjs/xterm.js/blob/master/demo/main.js

It uses the attach addon: https://github.com/xtermjs/xterm.js/blob/master/demo/main.js#L151

You can look at the attach addon impl here: https://github.com/xtermjs/xterm.js/blob/master/src/addons/attach/attach.ts
