### ISSUE TITLE
Support for column/box selection

### ISSUE THREAD

**Issue by kenorb** [xtermjs/xterm.js#1300]
## Details

- OS version: macOS 10.13.2

### Steps to reproduce

In _Terminal_ app I could press _Alt_ key and make a vertical selection, similar in iTerm. E.g.

<img width="194" alt="screen shot 2018-02-22 at 16 01 22" src="https://user-images.githubusercontent.com/266306/36549109-dbd38b02-17e9-11e8-8129-a22e3c69241d.png">

I expect similar behaviour for _xterm.js_.

Related: zeit/hyper/issues/2697

**Comment by Tyriar** [comment]
Alt on mac currently forces regular selection if an app is in mouse mode intercepting the events. We may need a setting that defines what alt does.

**Comment by Tyriar** [comment]
I looked into how column selection is handled in various terminals and this is what I found.

There are two different types of column selection:

- Start the box from where mouse down happens
  - Windows 10/cmd: alt+click
  - Windows 10/powershell: alt+click
  - Windows 10/cmder: alt+click
  - Linux/gnome-terminal: ctrl+alt+click
  - macOS/Terminal.app: alt+click
  - macOS/iTerm: alt+cmd+click (alt+click is force selection)
- Start the box from the existing cursor (typically alt+shift+click)
  - Windows 10/cmd: alt+shift+click
  - Windows 10/powershell: alt+shift+click
  - Windows 10/cmder: not implemented
  - Linux/gnome-terminal: ctrl+alt+shift+click
  - macOS/Terminal.app: alt+shift+click
  - macOS/iTerm: not implemented

Given this, I think save defaults are as follows:

- Start the box from where mouse down happens
  - Windows & macOS: alt+click
  - Linux: ctrl+alt+click
- Start the box from the existing cursor (typically alt+shift+click)
  - Windows & macOS: alt+shift+click
  - Linux: ctrl+alt+shift+click
- Force selection
  - I think this should be off by default with an opt in setting instead

I think these keybindings also align with how most editors work ([VS Code is missing the alt+click feature](https://github.com/Microsoft/vscode/issues/5402#issuecomment-246321432)).
