### ISSUE TITLE
Have alt+click only move horizontally when in the normal buffer

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1305]
Current alt+click will move the cursor to that position, it was made to work with vim/nano/etc by moving left to the start of the line, moving up/down vertically and then moving right. The problem is that this can lead to weird behavior when in a shell as up moved through history. A nice solution to this is to only move horizontally when in a shell, we need new API such as a setting to define alt behavior for that though.

See https://github.com/Microsoft/vscode/issues/44642

/cc @npezza93

**Comment by mofux** [comment]
Uffff, prompt detection, if we could ever get this to work somewhat reliable that would open the way for tons of cool plugins 😜But to be realistic, as long as the pty does not somehow tag a prompt line for us, this will be really hard to do. For example, how to detect that you are in a `node` prompt, or `mysql` prompt? Maybe a better approach to this problem would be to somehow wait for the echo of the cursor move command and test if it was moving the cursor to the expected direction -  and if it fails we cancel the whole operation 🤔

**Comment by mofux** [comment]
Thinking about it a little more, I guess most editors etc. use the alt buffer to draw, whereas the primary buffer is usually used by the prompt itself. Maybe a quick workaround would be to only allow left <-> right movements when in primary buffer, and full movements when in alt buffer?

**Comment by Tyriar** [comment]
> Maybe a quick workaround would be to only allow left <-> right movements when in primary buffer, and full movements when in alt buffer?

@mofux I like this idea even more than adding API :+1:
