### ISSUE TITLE
vim editor strange display

### ISSUE THREAD

**Issue by frankLife** [xtermjs/xterm.js#1306]
## Details
- Browser and browser version: chrome v64.0.3282.186
- OS version: mac 10.13.2 (17C88)
- xterm.js version: 3.1.0

### Steps to reproduce

when I set the height of container of xterm a such as `160px` . After fit process, the vim editor display the wrong line and I can't edit file correctly. like this:

![image](https://user-images.githubusercontent.com/5081884/36893854-8ee1c780-1e44-11e8-93dc-7497c65d18a0.png)

If I won't set the value of the height. the vim editor display is right and the editor can work correctly.

PS. 
1. The another strange point is  that sometimes it will work well when container has a accurate height value.
2. when edit a file which it's content is more than one page ，the display works well
3. the backend depends on node-pty 

@Tyriar I think you must know what happened ?  😢

**Comment by Tyriar** [comment]
@frankLife all fit does is call `Terminal.resize`, maybe you could check what the bad resize is being called with and try repro it without the fit addon (in the demo you can use the global var `term` in the console).

**Comment by frankLife** [comment]
Thanks for your quick response @Tyriar , I will try to check the effect of fit addon. I have found that the node-pty spawn receive the 125 cols and 11 rows config but when it works incorrectly it shows data like 

![](https://img.alicdn.com/tfs/TB1o9ApbuuSBuNjy1XcXXcYjFXa-974-620.png)

It seems that the output data has beyond the rows of config.

when sometimes works well the data like this :

![](https://img.alicdn.com/tfs/TB1y3yebTtYBeNjy1XdXXXXyVXa-990-306.png)

It looks like match the config .

So , do you think the problem exists the back end side ?

**Comment by frankLife** [comment]
When I get rid of `fit` process and set the node-pty 's and xterm's  cols and rows the same 125 and 11 explicitly.
And the log beyond 11 lines also appear: 

![image](https://user-images.githubusercontent.com/5081884/36911187-bacb1c00-1e7d-11e8-83df-c6c7fe350a92.png)

It may be vim's question in node-pty or some wrong config with node-pty or xterm ?  
@Tyriar

**Comment by frankLife** [comment]
I just reproduce the case in the xterm.js repository's demo:
![image](https://user-images.githubusercontent.com/5081884/36930591-28328a88-1edf-11e8-96df-935d284b9911.png)

when I just change the height of container from `450px` to `164px` 

![image](https://user-images.githubusercontent.com/5081884/36930608-850bfece-1edf-11e8-901d-c980e026edec.png)
 
and set the spawn command `['-c', `docker exec -it b620e7f8261c856c4f690e101316f94fc5c89664c2e55d1cf2cacfa107b1ce68 /bin/sh`]` to attach a docker container 

the case was reproduced.

And I finally found in VSCode ...

![image](https://user-images.githubusercontent.com/5081884/36930627-eae28826-1edf-11e8-9ab5-42878e5ea57c.png)

**Comment by frankLife** [comment]
I found when I resize the term explicitly , the output become right.
But I first need resize a another config and set the origin config back, can we just resize the origin config forcely

**Comment by Tyriar** [comment]
If the problem also occurs in iterm2 then it's likely a docker bug as they're 2 different implementations and iterm's been around for a long time.

**Comment by frankLife** [comment]
Yes, It may be admitted by offcial 

[#moby:36477](https://github.com/moby/moby/issues/36477)
[#moby:35407](https://github.com/moby/moby/issues/35407)

and the official say 
> (you can try if the output works correctly after resizing the Window; if it does, then it's definitely the same issue 😄) by [thaJeztah](https://github.com/thaJeztah)

But 

> But I first have to need resize a another config and set the origin config back, can we just resize the origin config forcedly

Shall we have a forced way to refresh the terminal screen or resize the terminal screen forcedly ? 
@Tyriar

**Comment by Tyriar** [comment]
@frankLife you can force a refresh of the terminal by resizing the terminal panel vertically or the window horizontally. It's not up to VS Code to work around a race condition in docker though.

**Comment by frankLife** [comment]
Ok, I got it. 
Thanks.
