### ISSUE TITLE
Slow scroll within Atom

### ISSUE THREAD

**Issue by twifty** [xtermjs/xterm.js#1311]
I'm experiencing a good 3 second delay between scrolling the mouse wheel and actual scrolling on screen. This did not happen in the 2.9.2 release which was almost instantaneous. I don't know what has changed under the hood, but the content being rendered is about 90 lines of multicolored text. I can provide a gist if required.

Is there any option I need to configure or a possible workaround? 

## Details
- Browser and browser version: Atom 1.24
- OS version: Manjaro Linux
- xterm.js version: 3.1.0

**Comment by Tyriar** [comment]
> content being rendered is about 90 lines of multicolored text

This is probably the problem, especially if it's non-ascii or has background color set. See https://github.com/xtermjs/xterm.js/issues/1294
