### ISSUE TITLE
'Ctrl + Shift + C' combination

### ISSUE THREAD

**Issue by twifty** [xtermjs/xterm.js#1312]
Not sure if #1231 fixes this, but I'm not able to capture the 'Ctrl + Shift + C' combination. The 'key' event is not being triggered at all.

I am displaying an interactive php script for which I want the user to be able to cancel just like they would in a normal terminal. Adding a listener to the parent element also fails.

## Details
- Browser and browser version: Atom 1.24
- OS version: Manjaro Linux
- xterm.js version: 3.1.0

**Comment by Tyriar** [comment]
ctrl+c sends SIGINT normally, not ctrl+shift+c. To do something on ctrl+shift+c I think you need to handle it manually using this API:

https://github.com/xtermjs/xterm.js/blob/6e546c0f30558125c8309f78b0c9e81a49bba81d/typings/xterm.d.ts#L377-L386
