### ISSUE TITLE
Options object is mutated when creating terminal

### ISSUE THREAD

**Issue by LucianBuzzo** [xtermjs/xterm.js#1322]
If I have some code like the following:

```js
const termConfig = {
	cols: 80,
	cursorBlink: false,
	rows: 24,
	theme: {
		background: '#343434',
	},
};
const tty = new Xterm(termConfig);
```

If I try to re-use the value of `termConfig` it will cause problems, as the value has been unexpectedly mutated. For example, the theme value will be `null`.
This could be resolved on this line https://github.com/xtermjs/xterm.js/blob/3.2.0/src/Terminal.ts#L260 by using `Object.assign` or a clone utility (if you have one available).

## Details
- Browser and browser version: whatsmybrowser.org/b/YWN4JTB
- OS version: OSX 10.13.3
- xterm.js version: 3.2.0

### Steps to reproduce

*See code example above*

**Comment by Tyriar** [comment]
👍 open to PRs, we can't use `Object.assign` as we need to retain IE11 support for now.

**Comment by LucianBuzzo** [comment]
Cool! I'll find a solution that will support IE11

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/1326
