### ISSUE TITLE
We're shipping the zmodem demo and it also breaks debugging

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1324]
<img width="408" alt="screen shot 2018-03-11 at 12 03 04 pm" src="https://user-images.githubusercontent.com/2193314/37257255-2bbe9ebc-2524-11e8-9f9b-bbb626d404b9.png">

It should probably live in a sub-directory of demo/ instead.

**Comment by FGasper** [comment]
What is desired here? Just to move the zmodem demo to a subdirectory?

I’m happy to help if the intended work could be given a bit clearer description.

**Comment by Tyriar** [comment]
@FGasper the issue is all js files in lib are run when debugging which causes the debugger to break since document doesn't exist. There is also the issue that we include all js files in the npm module. Moving the zmodem demo somewhere into `<reporoot>/demo` would fix both issues.
