### ISSUE TITLE
Marker API

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1325]
In order for consumers to provide some cool integrations such as activating different link matchers in different parts of the body or jumping to some arbitrary marked line we need a way to track lines in the normal buffer/scrollback.

## Goals

- Provide an API that allows consumers to add "markers" to arbitrary lines that are then tracked within the buffer.
- Don't slow down the terminal; minimize manipulations/GC of adding and maintaining markers.
- Should be an optional feature, it will have minimal O(1) overhead for unless consumers opt in.
- Be well tested.
- Markers will only work in the normal buffer.
- Link matchers will eventually adopt scoping which will use markers, this will allow link matchers to activate only on a subset of the buffer.
- (Future) Allow consumers to define how they visualize markers (or not show them at all) - this will likely involve standardizing a render layer API.

## API

```ts
class Terminal {
    /**
     * Adds a marker on cursor line, allowing it to be tracked.
     * @param cursorOffset The offset from the cursor of the line to be marked.
     */
    addMarker(cursorOffset?: number): Marker;
    
    /**
     * Scrolls to a line within the buffer.
     * @param line The 0-based line index to scroll to.
     */
    scrollToLine(line: number): void;

    /**
     * Selects text in the buffer between 2 lines.
     * @param start The 0-based line index to select from (inclusive).
     * @param end The 0-based line index to select to (inclusive).
     */
    selectLines(start: number, end: number): void;

    /**
     * Gets a list of active markers, generally you should request this every time you need to use
     * this array and not keep a reference as markers are disposed when they reach the end of the
     * scrollback.
     */
    markers: Marker[];
}

interface Marker {
    /**
     * The ID of the marker, this is a unique number generated for each marker and can be used to
     * differentiate markers.
     */
    id: number;

    /**
     * The absolute line of the marker.
     */ 
    line: number;

    /**
     * Whether the marker is disposed.
     */
    isDisposed: boolean;

    /**
     * Disposes the marker.
     */
    dispose(): void;
}
```

## How it works

Trim/splice listeners are setup on the buffer and adjust the position of the marker when a change occurs. Deleting a line will dispose the marker, this can happen through a splice call or from being trimmed off the top of the buffer. Consumers may still have a reference to the marker but it will be marked as `isDisposed` when this happens.

**Comment by mofux** [comment]
I don't quite see the use-case for this. I agree that having a stable line number (or id) is very useful in many cases, but I'm not sure if we really need a marker API on top of that. The only useful scenario I can think of is to mark a certain range, or at least a stable {x,y} coordinate which can be referenced later on. For example, the linkifier could mark an already resolved link with this, or the find addon could mark a match. And then, in a second step, we could add an API to the renderer that allows to render custom decorations for these areas. On top, we could add an API that allows to listen for hover and clicks on these areas. 

Are your thoughts with the marker API going into the same direction?

**Comment by Tyriar** [comment]
@mofux there are two primary use cases in my mind:

- Mark lines in which commands are run so they can easily be navigated and selected between
- Allow link matchers to be scoped between 2 markers, rather than just globally as they are now. This would allow us to linkify the output of `ls` for example as we know that all the words should be directories. Doing this eagerly for all output would be too slow, hit the HDD too much and it would linkify things you don't expect.

**Comment by mofux** [comment]
Oh I see, like the "Mark" feature that was recently added to the OSX Terminal.app that allows you to jump between commands using `cmd+up/down`?

https://apple.stackexchange.com/questions/209635/what-functionality-do-marks-offer-in-the-el-capitan-terminal/209907

**Comment by Tyriar** [comment]
Yeah similar to that
