### ISSUE TITLE
Occasional terminal corruption

### ISSUE THREAD

**Issue by FGasper** [xtermjs/xterm.js#1334]
We’ve found occasional corruption to happen in xterm.js 3.2.0. I’ve reproduced it in xterm.js’s demo.

I’ve seen it in Chrome/Mac 65.0.3325.146 as well as FF/Mac 60.0b3.

The attached video demonstrates the issue. You’ll notice a few “jumps” in the cursor movement: those are cases where I hit a single arrow, letter, or backspace key and got a “jump”, which isn’t what’s supposed to happen in the application.

## Details
- Browser and browser version: Chrome/Mac 65.0.3325.146 as well as FF/Mac 60.0b3
- OS version: macOS High Sierra
- xterm.js version: 3.2.0

### Steps to reproduce

1. It’s a bit finicky to reproduce, but I’ve been able to make it happen after futzing with arrow keys, various letters, space, delete/backspace, and enter/return keys.

[xtermjs_3_2_0_corruption_1333.zip](https://github.com/xtermjs/xterm.js/files/1816868/xtermjs_3_2_0_corruption_1333.zip)

**Comment by Tyriar** [comment]
Not sure what's happening here. Could you repro in the demo and run this in the devtools console to see what's being sent to the terminal?

```
term.setOption('debug', true);
```
