### ISSUE TITLE
Some characters are changed in tmux mode when the output file is compressed using uglifyjs

### ISSUE THREAD

**Issue by ManojkumarV** [xtermjs/xterm.js#1339]
TMUX mode usually displays the least possible dimension of the active sessions. The remaining area is filled with some characters. Those characters are replaced with some random characters when compressed using uglifyjs with options mangle and compress set to true. 

Terminal before compressing JS files:
<img width="1440" alt="screen shot 2018-03-19 at 10 53 29 am" src="https://user-images.githubusercontent.com/10399151/37579487-80362ef6-2b64-11e8-9851-b1255637a171.png">

Terminal after compressing JS files:
<img width="1435" alt="screen shot 2018-03-19 at 10 54 00 am" src="https://user-images.githubusercontent.com/10399151/37579491-8b9767a6-2b64-11e8-9ef6-f18fcece9d89.png">

**Comment by Tyriar** [comment]
What did you run exactly to reproduce this?

**Comment by Tyriar** [comment]
And what platform are you on?

**Comment by ManojkumarV** [comment]
@Tyriar I use xterm in an ember app. Ember app uses uglifyjs to compress the files for production environment. 
`terminalJsFiles = uglifyJs(terminalJsFiles, {options: {mangle: true, compress: true}});`

Those characters are replaced when compressed using the above line. The build runs in linux environment and is reproducible in all the browsers.

**Comment by Openappdev** [comment]
Hi @ManojkumarV, @Tyriar 
Please tell me how to attach/add a TMUX session to Xterm terminal in NodeJs. I really need it.
This will be really appreciated!
Thanks,
Saad.

**Comment by Tyriar** [comment]
@Openappdev responded to your issue, let's keep this one on topic.

**Comment by Tyriar** [comment]
@ManojkumarV oh I see, well I would assume this is a bug with uglify then, or you need to add some setting. I'll close this off for now, but if we just need to represent some character ([here?](https://github.com/xtermjs/xterm.js/blob/master/src/Charsets.ts)) differently inside xterm.js so this doesn't happen we can consider that

**Comment by ManojkumarV** [comment]
Importing the JS file with charset "utf-8" resolved the issue.
