### ISSUE TITLE
Improve Scrolling Experience

### ISSUE THREAD

**Issue by fkorotkov** [xtermjs/xterm.js#1343]
Right now Xterm.js captures all scroll events which leads to an inconvenient user experience in two related cases:

1. When Xterm is small and a user scrolls to the very bottom and is trying to scroll more, nothing will happen. I would expect the whole page to continue scrolling once Xterm reaches the very bottom.

2. When Xterm is large so there is no need for scrolling within Xterm. In this case Xterm captures all scrolling attempts and is stopping the whole page from scrolling. It's especially inconvenient if Xterm occupies most of the screen.

**Comment by Tyriar** [comment]
Seems reasonable, my use case for xterm.js is always a full screen app so there's no nested scrolling. It would be good to validate this won't cause issues if anyone watching this issue is using nested scroll bars.

**Comment by rlamana** [comment]
The PR seems to be closed, what is the state of this? I am using xterm.js to showcase the features of our CLI tool. It is part of a longer page and this is a total blocker to push it to production. Any quick workarounds I can use for this? Thanks!

**Comment by Tyriar** [comment]
@rlamana there was a problem with the PR and it became stale, this is waiting on someone else in the community picking it up.

**Comment by ShahzadUmair** [comment]
@Tyriar Faced a similar issue. I think i have a fix for this, opening a PR soon.
