### ISSUE TITLE
v3.2.0 - Performance regression

### ISSUE THREAD

**Issue by chabou** [xtermjs/xterm.js#1347]
I noticed a performance regression between v3.1.0 and v3.2.0. This is maybe a subtle one, but I am currently using a very old laptop (MBP late-2008) and typing chars is jerky.

I profiled a sequence with some quick and sequential keystrokes. 

v3.1.0
![capture d ecran 2018-03-23 a 11 03 34](https://user-images.githubusercontent.com/4137761/37823952-6351e3a0-2e8b-11e8-963c-8d0ad252c32a.png)

v3.2.0
![capture d ecran 2018-03-23 a 10 46 56](https://user-images.githubusercontent.com/4137761/37823958-6d21d868-2e8b-11e8-8db5-c6ba3fe36628.png)

Are you aware of this? (I didn't find any issue about this)

I can make some complementary tests if needed

## Details
- Browser and browser version: Electron v1.8.2 (Hyper)
- OS version: macOS 10.11.5
- xterm.js version: 3.2.0

**Comment by Tyriar** [comment]
Probably https://github.com/electron/electron/issues/11051 or https://github.com/electron/electron/issues/12042

**Comment by chabou** [comment]
It is not constant and seems to be a snowball effect. Very hard to isolate and to reproduce.
And there isn't any issue with a decent computer.

Let's close this.
Sorry for the noise
