### ISSUE TITLE
Send command via JS API to xterm terminal

### ISSUE THREAD

**Issue by drale2k** [xtermjs/xterm.js#1348]
## Details
- Browser and browser version: Safari 11
- OS version: macOS High Sierra
- xterm.js version: 2.9.2

### Steps to reproduce

I'd like to send a command like "ls" on a button click to the xterm terminal. I could find the methods .write and .writeln but both will only write the command to the terminal but not send it.

Is there  a way to do this? (I am using https://github.com/yudai/gotty with a go-backend connected to xterm)

Thanks

**Comment by Tyriar** [comment]
@drale2k you probably want to send `ls` to gotty, which will evaluate it in your shell and send it back to xterm.js to render.
