### ISSUE TITLE
Suggestion: event indicating _writeInProgress has cleared

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#1351]
It's useful for consumers of xterm to be able to know when xterm has completed rendering its buffer queue. This is because you cannot synchronously count on `.write` having affected the terminal buffer. I've noticed that xterm uses `_writeInProgress` to check when it has cleared its queue depth, and I think it would be useful to emit some event that means "writing is done" so that we don't have to reach into internals.

**Comment by Tyriar** [comment]
@vincentwoo what's the use case? In isolation this sort of API wouldn't make sense as no information about the buffer is currently public.

**Comment by vincentwoo** [comment]
1. It is useful to know when xterm is "done" in that you can display other information to the user. Let's say a user runs a function that spams the terminal too much and we kill the program. We may want to wait until rendering has cleared out before showing them a message about what's happened.

2. I'm using the legacy rendering function, it's useful to me to know when it's okay to go in and try to extract the state of the terminal.

**Comment by Tyriar** [comment]
I think listening to the `data` event and using a timeout period after that would give you a similar effect.
