### ISSUE TITLE
Terminal disables browser refresh

### ISSUE THREAD

**Issue by masonwheeler** [xtermjs/xterm.js#1352]
When I focus the terminal and `attach()` it to a websocket, the `F5` key stops working to refresh the page.  I can understand why this can be desirable, when interfacing with a program for which `F5` has its own significance, but in my case it doesn't, and not being able to refresh with a single keypress slows down the testing cycle.  Is there any way to make xterm.js make an exception for the `F5` key?

**Comment by parisk** [comment]
Hi @masonwheeler, thanks for reporting this. Sounds quite strange.

Can you provide us with some more information;

1. Xterm.js version you are using
2. Browser (and version) you are using
3. Operating System (and version) you are using

**Comment by masonwheeler** [comment]
Hmm, are you saying this isn't expected behavior?

I'm using the latest xterm.js version, (just pulled from NPM,) on Windows7, and I see the same results with Firefox (latest) and Chrome (latest).  There's literally nothing at all making this extra-complicated or weird. This is my HTML page in its entirety:

```
<!DOCTYPE html>
   <html>
   <head>
  <link rel="stylesheet" href="node_modules/xterm/dist/xterm.css" />
  <script language="javascript" type="text/javascript" src="node_modules/xterm/dist/xterm.js"></script>
  <script language="javascript" type="text/javascript" src="node_modules/xterm/dist/addons/attach/attach.js"></script>
   <script language="javascript" type="text/javascript">
   Terminal.applyAddon(attach);
   var wsUri = "ws://localhost:2468/myWS";
   var terminal;
    
   function init()
   {
   terminal = new Terminal({cols: 120, rows: 40});
   terminal.open(document.getElementById("Terminal"));
   var websocket = new WebSocket(wsUri);
   websocket.onopen = function(evt) { terminal.send("init"); terminal.focus(); };
   terminal.attach(websocket);
   }
    
   window.addEventListener("load", init, false);
    
   </script>
    
   </head>
   <body >
    
    
   <div id="Terminal"></div>
    
   </body>
   </html>
```

**Comment by theflyingape** [comment]
If expediency helps, `ctrl-shift-r` works for me using Chrome or Firefox.

**Comment by Tyriar** [comment]
I've never had issues refreshing the demo on any platform even when focused. I tend to use cmd+r/ctrl+r these days though.
