### ISSUE TITLE
allowTransparency = false still allows transparent backgrounds

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1357]
See https://github.com/Microsoft/vscode/issues/46374, setting background to `#0000` will use a transparent background

![image](https://user-images.githubusercontent.com/2193314/38043623-83a685d6-326c-11e8-86e3-d66ab7e6f010.png)

We should ignore the alpha portion or disallow this all together when allowTransparency = false. FYI @bgw, @chabou

**Comment by bgw** [comment]
I can fix this. It should be pretty easy to add this on top of #1346.

**Comment by bgw** [comment]
This was fixed by https://github.com/xtermjs/xterm.js/pull/1346/commits/b66b0aae182d9540ddffb213e83e24ac4dfdd276
