### ISSUE TITLE
ngOnDestroy does not remove child process created in xterm.

### ISSUE THREAD

**Issue by vaibhav-rbs** [xtermjs/xterm.js#1358]
I am using the xterm.js to access the unix shell terminal for a freenas system. I am trouble in getting to kill the unix process on navigation away from webpage or on a reload of xterm web application. is this something expected or am I doing something wrong.

my latest changes are in this branch, https://github.com/freenas/webui/tree/FIX-30225

## Details
- Browser and browser version: Chrome: Version 65.0.3325.181 (Official Build) (64-bit)
- OS version: OSX High Sierra, 10.13.3 (17D102)
- xterm.js version: "vscode-xterm": "^3.0.0-beta8",

### Steps to reproduce

1. please set up a freenas dev environment: using https://github.com/freenas/webui/ 
2. navigate to http://localhost:4200/shell
3. type in top,  hit return key, navigate away, come back to http://localhost:4200/shell
4. repeat step 3 few times.
5. ps aux | grep top shows you quite a few process are open.
```
root       25705   0.0  0.0    7948   3724 65  S+   22:13      0:01.76 top
root       26534   0.0  0.0    7948   3532 71  S+   22:36      0:00.16 top
root       26542   0.0  0.0    7948   3536 72  S+   22:36      0:00.13 top
root       26550   0.0  0.0    7948   3536 73  S+   22:37      0:00.12 top
```

6. I expected that top command would be killed when I navigate away from the webpage.

**Comment by Tyriar** [comment]
Managing the process doesn't have anything to do with xterm.js. It should be the responsibility of the server to clean up the pty when you navigate away.
