### ISSUE TITLE
Xterm overwrites comands on same line if its longer

### ISSUE THREAD

**Issue by fenfenraorao** [xtermjs/xterm.js#1359]
1.var opts = {
            cols: 80,
            rows: 100,
            screenKeys: true,
            cursorBlink: true
          }
          this.term = new Terminal(opts)
 sh-4.2#：
When the input character is more than 28 characters, it starts at the beginning of the line.
eg:'sh-4.2# aaaaaaaaaaaaaaaaaaaa' changed as 'aaaaaaaaaaaaaaaaaaaaaaaaaaaa', It will not wrap,
but When I enter, it shows correctly as 'sh: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: command not found'

￼
![wechatimg12](https://user-images.githubusercontent.com/27481345/38084184-73111d4a-337e-11e8-9437-4f420835c7f5.jpeg)

**Comment by Tyriar** [comment]
What are the dimensions of the backing pty? Where are you running sh?

**Comment by fenfenraorao** [comment]
￼The variable opts defines the dimensions of the backing pty.
The column is 80, the row is 100.
After returning, send the command to the background.

**Comment by Tyriar** [comment]
The shell might be turning wraparoundMode off in which case this is expected.

**Comment by fenfenraorao** [comment]
Is there any solution?

**Comment by Tyriar** [comment]
I don't know what the socket.io plugin is, but this seems like a problem with your backend. Provided wraparoundMode is on (default), when the shell sends characters that would go off screen, it will wrap them.

**Comment by Liaozhenting** [comment]
I reproduced the bug.
For example,If the server terminal (in app.js) set the cols is  80 , but your terminal in browser is more than 80.Xterm will not wrap correctly.It overwrites commands on same line when the commands is too long.
To fix this bug maybe you should set the right width in browser.

**Comment by Liaozhenting** [comment]
Seems we can only set css style of terminal in broswer like this.
```js
function setTerminalSize() {
  var cols = parseInt(colsElement.value, 10);
  var rows = parseInt(rowsElement.value, 10);
  var width = (cols * term.renderer.dimensions.actualCellWidth + term.viewport.scrollBarWidth).toString() + 'px';
  var height = (rows * term.renderer.dimensions.actualCellHeight).toString() + 'px';
  terminalContainer.style.width = width;
  terminalContainer.style.height = height;
  term.fit();
}
```

**Comment by vueCcc** [comment]
> Seems it need correct width strictly and we can only set css style of terminal in broswer like this.
> 
> ```js
> function setTerminalSize() {
>   var cols = parseInt(colsElement.value, 10);
>   var rows = parseInt(rowsElement.value, 10);
>   var width = (cols * term.renderer.dimensions.actualCellWidth + term.viewport.scrollBarWidth).toString() + 'px';
>   var height = (rows * term.renderer.dimensions.actualCellHeight).toString() + 'px';
>   terminalContainer.style.width = width;
>   terminalContainer.style.height = height;
>   term.fit();
> }
> ...
> setTerminalSize();
> ```

你好，我也遇到了这个问题，请问下您这里的term是new Terminal实例吗，我发现实例并没有renderer这个方法，谢谢

**Comment by JasinYip** [comment]
> 你好，我也遇到了这个问题，请问下您这里的term是new Terminal实例吗，我发现实例并没有renderer这个方法，谢谢

```
term._core._renderService
```

**Comment by DasyDong** [comment]
The questions is caused by col  size, when using "term.fit(); " , the termination resize to fit width. 
If col size is larger than 80;  the bash wrap to one lines (I don't know how to resize the termination size to larger)
We can delete  term.fit() to fix the issue .

BTW this is not a good solution

![image](https://user-images.githubusercontent.com/9334289/93163102-d9ae3480-f748-11ea-98eb-5d75dfc8675b.png)

**Comment by Manon103** [comment]
when I delete the 'cols' option can solve this problem, but I really want it to fit screen size, is there any solution?

**Comment by DasyDong** [comment]
Use term.resize to match the pty windows size 
One import things is that do not define cols and rows with new Terminal(cols: cols, rows: rows), not work for me

Auto fit the term size by windows width , the issue is fixed ,  share the codes 
```
        let height = document.body.clientHeight;
        let width = document.body.clientWidth;
        let rows = parseInt(height/18, 10);//18是字体高度,根据需要自己修改
        let cols = parseInt(width/9, 10);
        let term = new Terminal();
        term.open(document.getElementById("terminal"));
        term.write("connecting to pod " + pod + "...")

        conn = new WebSocket(url);
        term.on('data', function (data) {
            msg = {operation: "stdin", data: data}
            conn.send(JSON.stringify(msg))
        });

        term.on('resize', function (size) {
            msg = {operation: "resize", cols: size.cols, rows: size.rows};
            conn.send(JSON.stringify(msg))
        });

        conn.onopen = function (e) {
            term.write("\r");
            msg = {operation: "stdin", data: "export TERM=xterm && clear \r"}
            conn.send(JSON.stringify(msg))
            term.resize(cols, rows) //  The most import code 
        };
```

**Comment by haust-lyb** [comment]
2020-12-13 这个问题虽然关闭了 但是也没有好的解决办法啊 按照DasyDong提供的代码也没有什么效果

**Comment by lesauf** [comment]
I am still having the same issue. I fixed it by running this command in the terminal to set the server terminal size to the fontend terminal like this:

`stty cols 158` // replace 158 with the variable containing the value computed.

> conn.onopen = function (e) {
>             term.write("\r");
>             msg = {operation: "stdin", data: "export TERM=xterm && clear \r"}
>             conn.send(JSON.stringify(msg))
>             term.resize(cols, rows) //  The most import code 
>         };

**Comment by GitHubForWard** [comment]
2021年11月23日（xterm.js4.X版本），new Terminal({})初始化的试试不需要cols，rows，调用fit方法以后，可以直接拿xterm实例中的cols和rows通过websocket给服务端发送cols和rows数据，窗口resize之后同理，切记一定要在窗口resize后调用一下fit方法，也压根不用手动去计算cols和rows

`
      this.xterm = new Terminal(this.xtermOptions)
      this.xterm.loadAddon(this.fitAddon)
      this.xterm.open(document.getElementById(this.terminalId), true)
      this.fitAddon.fit()
      const sendData = JSON.stringify({
        operate: 'resize',
        columns: +this.xterm.cols,
        rows: +this.xterm.rows
      })
      this.websocketSend(sendData)
`
`
  window.addEventListener('resize', () => {
    const columns = this.xterm.cols
    const rows = this.xterm.rows
    const data = JSON.stringify({ operate: 'resize', columns, rows })
    this.websocketSend(data)
    this.fitAddon.fit() // 一定要调用这个
  })
`

**Comment by GitHubForWard** [comment]
> 2020-12-13 这个问题虽然关闭了 但是也没有好的解决办法啊 按照DasyDong提供的代码也没有什么效果

可以试一下我的方案
