### ISSUE TITLE
We're publishing test js files to npm

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1361]
<img width="197" alt="screen shot 2018-03-29 at 11 49 45 am" src="https://user-images.githubusercontent.com/2193314/38107625-5a74dfce-3347-11e8-9d8c-40e26ab50ba4.png">

**Comment by Tyriar** [comment]
I'm not sure the best way to fix this. It's happening even though we have this defined in .npmignore:

```
lib/*.test.js
lib/*.test.js.map
```

Our package.json has a whitelist which matches them though:

```
    "lib/*.js",
    "lib/*.js.map",
```

**Comment by pro-src** [comment]
@Tyriar  I've tested it and it's ready to merged now
