### ISSUE TITLE
trigger a left arrow key in the terminal

### ISSUE THREAD

**Issue by dusadrian** [xtermjs/xterm.js#1378]
Hi,

I am trying to reproduce a bracket matching capability in the terminal. As a very simple example, this is what I do:
```
let bracket = false;

xterm.on('data', (data) => {
  if (data == "(") bracket = true;
  ptyProcess.write(data);
});

ptyProcess.on('data', function (data) {
  xterm.write(data);
  if (bracket) {
    bracket = false;
    ptyProcess.write(")");
  }
});
```
This inserts the matched bracket, and now I need to automatically simulate a left arrow key to position the cursor in between the brackets. I've searched the Internet up and down, and still unable to figure out how to do that.
Any suggestion is highly welcomed, thanks very much in advance.

**Comment by Tyriar** [comment]
This should work:

```
xterm.write('\x1b[D')
```

See https://github.com/xtermjs/xterm.js/blob/master/src/Terminal.ts#L1560

You could also create a KeyboardEvent and use [`dispatchEvent](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) on `xterm.element`.

**Comment by dusadrian** [comment]
Thanks very much.
I was so close, having already tried `'\x1b[1D'` (where I thought the last 1 means move left one position).
Your code did not work as provided, instead this one does: `ptyProcess.write('\x1b[D')`
