### ISSUE TITLE
Crash when you change options before calling open

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#1383]
Attempting to setOption for some options triggers a `renderer.clear`, but if the terminal has not opened yet, this will crash.

[CodePen repro](https://codepen.io/akanet/pen/wmOMoe)

relevant code: https://github.com/xtermjs/xterm.js/blob/master/src/Terminal.ts#L452

**Comment by Tyriar** [comment]
Thanks for the codepen, makes it super easy 😄
