### ISSUE TITLE
How to input Chinese character when used the xterm.js in browser?

### ISSUE THREAD

**Issue by kangbb** [xtermjs/xterm.js#1386]
## Details
- Browser and browser version: chrome,firefox
- OS version:  ubantu
- xterm.js version: 3.2.0

### Steps to reproduce

 I want to do a web tty, and use the xterm.js with npm. But I can't find api to set the character types. So I can't input the Chinese. Can you give me some adivce? Thank you~

**Comment by Tyriar** [comment]
We support IMEs, you will need to configure one in Ubuntu and then enable it.

**Comment by cute-angelia** [comment]
how to enable IMEs with xterm.js?

the demo in https://xtermjs.org/ can't input Chinese character

**Comment by Tyriar** [comment]
IMEs are an OS level feature, look up how to set it up for your operating system.

**Comment by cute-angelia** [comment]
@kangbb  use `on("data", `
