### ISSUE TITLE
Linkifier: underline shift after double width character

### ISSUE THREAD

**Issue by mandel59** [xtermjs/xterm.js#1387]
Linkifier doesn't support East Asian Width (wcwidth) yet

## Details
- Browser and browser version: any
- OS version: any
- xterm.js version: master (da8151b1b51adb415c3c6929d985f91551e34006)

### Steps to reproduce

1. Write any URL after [East Asian Wide or Fullwidth](https://www.unicode.org/reports/tr11/tr11-31.html#Definitions) (a.k.a double width) characters

![image](https://user-images.githubusercontent.com/1079715/38744867-f14b5260-3f7d-11e8-8da4-25d76fc3dcdd.png)

**Comment by Tyriar** [comment]
This will involve making Linkifier.ts aware of wide characters similar to how SelectionManager.ts is. This can make the code a lot more complex:

https://github.com/xtermjs/xterm.js/blob/2cee66909bedd0a0a1e70f677f7470e5f28cd92b/src/SelectionManager.ts#L645

I wonder if there's a nicer, more generic way to deal with converting between character indexes and column numbers.

**Comment by Tyriar** [comment]
Works in master 🎉
