### ISSUE TITLE
In DynamicCharAtlas, don't store empty characters in the texture

### ISSUE THREAD

**Issue by bgw** [xtermjs/xterm.js#1389]
Discussion here: https://github.com/xtermjs/xterm.js/pull/1327#discussion_r179231675

We don't need to save anything to the atlas texture if a glyph is empty, we just need to keep track of the fact that it was empty. This may or may not be worth the added complexity, but we should try and see.

**Comment by Tyriar** [comment]
No plans to implement this for canvas renderer as we'll move towards the webgl addon that was just moved eventually
