### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by varadekd** [xtermjs/xterm.js#1397]
## Details
- Browser and browser version:  Chrome V65
- OS version: macOS High Sierra
- xterm.js version: 3.3.0

I installed xterm in my vuejs application using npm and then followed the Readme file for importing xterm

I imported Xtermjs and xterm Css in my component, As soon as I click the button an div is visible with black background, and when I click on it and error is thrown 

TypeError: Cannot read property 'map' of null

Screenshot is attached for better clarity
![screen shot 2018-04-20 at 12 12 53 pm](https://user-images.githubusercontent.com/10898509/39034509-3f5aa5da-4494-11e8-9b83-9a4269367d36.png)
![screen shot 2018-04-20 at 12 13 05 pm](https://user-images.githubusercontent.com/10898509/39034510-3f958a4c-4494-11e8-84b3-17b88654c076.png)
![screen shot 2018-04-20 at 12 13 13 pm](https://user-images.githubusercontent.com/10898509/39034512-40201f0e-4494-11e8-8fa5-b65c8215da87.png)

Import {Terminal } from 'xterm'
style src="<CSS_PATH>"

html code:
<div v-if="some_condition>
<div id="terminal></div>
</div>

script code:
some_condition = true
var terminal = new Terminal()
terminal.open(document.getElementById('terminal'))

**Comment by Tyriar** [comment]
`getCoords` must be returning null for you:

https://github.com/xtermjs/xterm.js/blob/a3ce881897818d1c61476620e7d037717ca9a68f/src/handlers/AltClickHandler.ts#L31-L41

Opening to PRs.

@varadekd this should only happen when you hold alt and click, did you not press alt?

fyi @npezza93

**Comment by varadekd** [comment]
No @Tyriar

**Comment by caosm** [comment]
I got the same error when I ignore this sentence.

> The parent element should be visible (have dimensions) when open is called as several DOM-based measurements need to be performed when this function is called.

[ref](https://xtermjs.org/docs/api/terminal/#openparent-focus)
