### ISSUE TITLE
Some question in demo. the message input will be Change line

### ISSUE THREAD

**Issue by Jandou6** [xtermjs/xterm.js#1398]
## Details
- Browser and browser version:  Chrome 65
- OS version: 10.11
- xterm.js version: 3.2.0

### Steps to reproduce

1.  add a console.log in term.on 'data'. Look like that
![image](https://user-images.githubusercontent.com/13618778/39044959-3537e6e6-44c4-11e8-95cd-370240754490.png)

2. and start the demo.

3.if paste some command in terminal. You will found the Paste Data will be Change line in console.log.
![image](https://user-images.githubusercontent.com/13618778/39045548-c31ad53a-44c5-11e8-9b92-a966ae590592.png)

**Comment by Tyriar** [comment]
`data` events aren't guaranteed to contain everything. This is working as expected
