### ISSUE TITLE
Implement https://nodejs.org/api/tty.html and/or readline interfaces

### ISSUE THREAD

**Issue by pro-src** [xtermjs/xterm.js#1400]
This would add indirect compatibility for webpack'ed packages that depend on `process.stdout`. If a user provides a browser shim for node's global process with a Terminal instance assigned to global process as stdout then popular packages such as `chalk` and those that only have similar dependencies should theoretically work.

With the proposed interfaces implemented, packages that use process.stdout to display progress information such as `ora` which displays a cli spinner could be made to work.

This isn't meant to detail exactly how to get such packages working but as an example with the proposed changes/additions:

```js
const term = new Terminal();
window.process = { env: {}, stdout: term, stderr: term };
// then deferred dependencies are loaded
```

**Comment by Tyriar** [comment]
@pro-src could you just map the interface expected by chalk/whatever to `xterm.write`? This seems to me like something that would be better off living outside the lib.

**Comment by pro-src** [comment]
chalk doesn't use `xterm.write` or do any logging. It does it's best to detect color support in a cross platform way by checking `process.env`, `process.platform`, and `process.stdout`. The `process.stdout` check simply looks to see if `process.stdout.isTTY === true`.

This is chalk's [test](https://github.com/chalk/chalk/blob/master/test/windows.js#L41) that covers xterm-256color support in Windows (illustrates what chalk does)
```js
// test/windows.js-41-45
test('don\'t replace blue foreground color in xterm based terminals', t => {
     process.env.TERM = 'xterm-256color';
     const m = importFresh('..');
     t.is(m.blue('foo'), '\u001B[34mfoo\u001B[39m');
});
```

Chalk checks `process.stdout.isTTY` [here.](https://github.com/chalk/supports-color/blob/master/index.js#L50)

Yes, I could just shim `process.stdout` with a different `object` besides `xterm` then map `xterm.write` to said `object.write` but it doesn't make much sense to do so given what xterm.js does and it doesn't solve the problem of packages expecting `process.stdout` to be a instance of `Readline`.

```js
process = {
  stdout: { isTTY: true, write: data => xterm.write(data) }
  env: { FORCE_COLOR: '1', TERM: 'xterm-256color' }
}
```

xterm.js is a pseudoTTY, supports color, has a stream-like interface, and has methods similar to the ones in the suggested interfaces already. Implementing the missing properties/methods and/or renaming existing ones to match node's [TTY(https://nodejs.org/api/tty.html)/[Readline](https://nodejs.org/api/readline.html) (aside from full stream Interface) would be trivial and make for a good `process.stdout` replacement in the browser.

**Comment by pro-src** [comment]
Doesn't xterm already have a method for each of these but with different function signatures? 

```js
readline.clearLine(stream, dir)
readline.clearScreenDown(stream)
readline.cursorTo(stream, x, y)
readline.emitKeypressEvents(stream[, interface])
readline.moveCursor(stream, dx, dy)
```

**Comment by Tyriar** [comment]
> Implementing the missing properties/methods and/or renaming existing ones to match node's TTY/Readline (aside from full stream Interface) would be trivial and make for a good process.stdout replacement in the browser.

So something like this?

```ts
// Don't touch process when used in a node context
if (!process && !('process' in window)) {
  window.process = {
    stdout: { isTTY: true, write: data => xterm.write(data) }
    env: { FORCE_COLOR: '1', TERM: 'xterm-256color' }
  }
}
```

How would it work when you have 2 xterm instances? Just use the first one?

> Doesn't xterm already have a method for each of these but with different function signatures?

@pro-src you can accomplish all these via `xterm.write`, except for emit keypress events which would need events to be dispatched on `Terminal.element` atm.

---

Also with chalk, it looks like you can set the color support manually: https://github.com/chalk/chalk/blob/678152cf1952f3afe1e523a306c0413ad57c34b3/index.js#L23

**Comment by pro-src** [comment]
The user would decide whether to use a terminal instance as `process.stdout` or `process.stderr` or not and could switch it out for another instance. I made a [demo](https://github.com/pro-src/xterm.js-chalk-ora).

Notice the boilerplate in main.

All of this could be accomplished without xterm but that's not the point. The idea is to have plug-n-play type compatibility and given the similarities between tty/readline and xterm, I can't come up with a reason for xterm not to accommodate  it. Other users are bound to ask for public APIs similar to readline eventually if they haven't already.

**Comment by Tyriar** [comment]
@pro-src the problem with adding more and more API is that it restricts development, that's more stuff that needs to be supported going forward and more that we cannot break without at least a major version bump.

Since this is so easily accomplishable using the API currently as you mention, and no one has asked for this in the 2 years I've been involved int he project I don't think we should add this to core. In the future once the addon situation is is improved https://github.com/xtermjs/xterm.js/issues/1128, I think there should be a tty-adapter and readline-adapter addon.

**Comment by pro-src** [comment]
Another popular package worth mentioning is [inquirer](https://www.npmjs.com/package/inquirer). I'd have to go read it's source and produce similar boilerplate code to get it working whereas if xterm implemented those interfaces I could just assign my xterm instance as process stdio and voila!
