### ISSUE TITLE
xterm.fit() causes a random error

### ISSUE THREAD

**Issue by denishristov** [xtermjs/xterm.js#1405]
xterm.fit() causes this error and I don't have a clue why: 
![screen shot 2018-04-24 at 1 19 29](https://user-images.githubusercontent.com/22468578/39156156-a6f70e42-475d-11e8-9b4b-c52a44a9a7e9.png)

I'm invoking .fit in didComponentMount in the Terminal component which I've linked below. Without .fit the terminal opens just fine and I don't get this error which is pretty strange and leads me to believe that its not an issue with the websocket. I've also got another error from .fit but I can't recreate it and it was something about invalid state but didnt mention any error with the websocket. Thanks in advance!

## Details
- Browser and browser version: Google Chrome 65.0.3325.181
- OS version: macOS 10.13.2
- xterm.js version: 3.2.0
- the app is build on react + tornado
- the terminal component: [https://github.com/Loosper/sherminal/blob/master/client/src/Terminal.js](url)

**Comment by Tyriar** [comment]
This is happening because the terminado attach is listening to `resize`:

https://github.com/xtermjs/xterm.js/blob/716a8d592676ada264d9b9b7ebec2f1f3277a4c6/src/addons/terminado/terminado.ts#L66

You will need to wait for the socket to connect before calling `fit` (or call it before attaching?).
