### ISSUE TITLE
react import xterm don't load css file ?

### ISSUE THREAD

**Issue by zhangjie2012** [xtermjs/xterm.js#1418]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 3.3.0

### Steps to reproduce

1. npm install xterm --save
2. `new Terminal()` and `term.open(document.getElementById('terminal-container'));`

![image](https://user-images.githubusercontent.com/2450412/39303545-256d17da-4989-11e8-9f5f-3c4faf3288d7.png)

Looks like not load xterm css file ? I use xterm with react.

**Comment by pro-src** [comment]
Hi zhangjie2012,

I don't know that much about react but when you `require('xterm')` or `import 'xterm'` you only get js unless your using some special loader. Webpack has a special loader to handle style/css but you have to point to xterm's css file using the import statement. Refer to your bundler/loader's documentation for loading css.

To be clear. The css and js files are stored separately and usually need multiple import statements to get them both.

**Comment by Tyriar** [comment]
Yes you'll need to include the CSS file as well as in the getting started snippet https://github.com/xtermjs/xterm.js#getting-started

**Comment by monsterooo** [comment]
for scss:

```scss
@import '~xterm/dist/xterm.css';
```

**Comment by nahidacm** [comment]
In react you can do:
```nodejs
import 'xterm/css/xterm.css';
```
