### ISSUE TITLE
Sometimes it takes a while to register an ESC key pressing

### ISSUE THREAD

**Issue by LexSong** [xtermjs/xterm.js#1423]
## Details
- Browser and browser version: Chrome 66.0.3359.117
- OS version: Windows 10 version 1709, build 16299.371
- xterm.js version: latest master branch

### Steps to reproduce

1.  Launch xterm.js demo
2.  Start windows version of vim with `vim`
3.  Type `i` to get into insert mode
4.  Type `test`
5.  Type `<Esc>` to leave insert mode, however this key pressing won't be register
6.  Type `<Esc>` again, this time the key pressing will be recognized, but it takes a while
7.  Type `:q!` to leave vim
8.  At this stage, every esc key pressing will take a while to be recognized by cmd.exe, even we already leave vim. Typing random command into cmd and pressing ESC to clean the command line, to show this issue.

**Comment by Tyriar** [comment]
This is more likely related to https://github.com/Microsoft/vscode/issues/45693 than xterm.js
