### ISSUE TITLE
Demo rendering appears to be broken

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1424]
Loading and then pressing enter looks like it's drawing the text at 50% alpha or something.

<img width="298" alt="screen shot 2018-04-30 at 3 11 50 pm" src="https://user-images.githubusercontent.com/2193314/39452929-e46343ec-4c88-11e8-8bb5-aee7cb1d701d.png">

Reproing on my fork's master branch which is up to date with upstream.

**Comment by bgw** [comment]
I think I might know what's causing this:

- TextRenderLayer doesn't wrap foreground drawChar calls in a save()/restore().
- BaseRenderLayer's drawChar doesn't do a save()/restore() itself (which it probably should).
- drawChar sets the globalAlpha when drawing a dim character.

I can experiment with trying to repro and fix this after work.

**Comment by Tyriar** [comment]
I think this is still happening, just synced with VS Code and I see this again 

![image](https://user-images.githubusercontent.com/2193314/40316642-cff1295a-5cd3-11e8-9ea8-7b6def1e1fd3.png)

allowTransparency = false
background = #ffffff

**Comment by Tyriar** [comment]
It's also using the static cache.

**Comment by Tyriar** [comment]
Can repo on the demo by changing this:

https://github.com/xtermjs/xterm.js/blob/0ad108013399bd1e7a82a82fb9079db7a45107a9/demo/main.js#L113-L119

To:

```
term = new Terminal({});
```

**Comment by Tyriar** [comment]
Disabling any one of these settings (such that there are 4 properties) will cause the repo :confused: 

```ts
  term = new Terminal({
    macOptionIsMeta: optionElements.macOptionIsMeta.enabled,
    cursorBlink: optionElements.cursorBlink.checked,
    scrollback: parseInt(optionElements.scrollback.value, 10),
    tabStopWidth: parseInt(optionElements.tabstopwidth.value, 10),
    screenReaderMode: optionElements.screenReaderMode.checked
  });
```

**Comment by Tyriar** [comment]
The same fix as https://github.com/xtermjs/xterm.js/pull/1442 needs to be applied to the static char atlas. We should do this for 3.4.1
