### ISSUE TITLE
Implement function keys above F12 (F12, F13, ... F24)

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [xtermjs/xterm.js#1426]
I'm coming from a downstream consumer (Hyper terminal, v2.0.0); it looks like xterm.js doesn't handle function keys [above F12](https://github.com/xtermjs/xterm.js/blob/a3ce881897818d1c61476620e7d037717ca9a68f/src/Terminal.ts#L1689-L1773). This is causing Hyper to ignore these keys as well.

I spent about an hour digging through the source, to see if I could add this myself; but I have no idea where `KeyboardEvent.keyCode` is coming from. (I tried to test this in the Inspector in FireFox, but I kept running into unrelated issues. `)=`)

## Details
- Browser and browser version: N/A (Hyper.app 2.0?)
- OS version: macOS 10.13.4
- xterm.js version: [7cb4b8e](https://github.com/zeit/hyper/blob/2.0.0/package.json#L203)

----

I don't know if any of the developers have access to a keyboard that goes higher than F12; I'm happy to test things! For reference, macOS's Terminal.app goes through F19 (and, weirdly, reports F20 as `⌃P`? wtf?):

<img width="179" alt="screen shot 2018-05-01 at 1 06 29 pm" src="https://user-images.githubusercontent.com/200/39492087-10707466-4d54-11e8-90c4-83421737a7bc.png">

**Comment by jerch** [comment]
@ELLIOTTCABLE Here is some info about the keyCode https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode. There is a table for the F keys, as you can see there, it gets tricky with the higher ones, they are kinda system and browser dependent (due to the lack of a proper spec for years).
The place to hook them into xterm.js is `Terminal._evaluateKeyEscapeSequence` in Terminal.ts.

**Comment by ofadieiev** [comment]
In Midnight commander <kbd>Shift+F3</kbd> leads to <kbd>F13</kbd> which is used to column selection. `mintty` works good with these combinations.

**Comment by Tyriar** [comment]
Since this has been open over a year and has no votes I'm going to close as out of scope. Consumers should be able to intercept and handle these keypresses themselves via the `attachCustomKeyEventHandler` API
