### ISSUE TITLE
When scrolling in the terminal, text is also selected.

### ISSUE THREAD

**Issue by travisobregon** [xtermjs/xterm.js#1427]
When scrolling in the terminal, text is also selected.

![image](https://user-images.githubusercontent.com/12074713/39527506-70c1318c-4e19-11e8-8678-63a461e823a3.png)

Is the latest version of Firebox ESR supported? If not, please disregard this issue.

Thanks.

## Details
- Browser and browser version: Firefox ESR 52.7.4 (64-bit)
- OS version: Windows 7 Enterprise
- xterm.js version: ^3.3.0

### Steps to reproduce

1. Run the demo.
2. Type some commands so that the terminal has enough content to scroll.
3. Click the scroll bar and scroll up/down.

**Comment by Tyriar** [comment]
I cannot reproduce on Windows 10 Firefox/Chrome. My guess is it's related to Windows 7 which we don't aim to support.
