### ISSUE TITLE
Font rendering weight heavier than in 2.x

### ISSUE THREAD

**Issue by hatched** [xtermjs/xterm.js#1429]
It looks like the font weight rendering in the 3.x branch is much heavier than in the 2.x branch even with `fontWeight` set to `100`, `normal` or nothing. When setting `fontWeight` to `bold` the text is more bold so it appears that the config value is being respected.

2.x
<img width="410" alt="screen shot 2018-05-03 at 1 27 16 pm" src="https://user-images.githubusercontent.com/532033/39598479-ecbd8ab2-4ed5-11e8-848d-7dc121db3f09.png">
3.3
<img width="378" alt="screen shot 2018-05-03 at 1 39 13 pm" src="https://user-images.githubusercontent.com/532033/39598928-665ab6b4-4ed7-11e8-97b7-f6d2b6c2daf2.png">
3.3 (`fontWeight: 'bold'`)
<img width="379" alt="screen shot 2018-05-03 at 1 46 48 pm" src="https://user-images.githubusercontent.com/532033/39599248-75b05ed8-4ed8-11e8-9656-070c8df42334.png">

```JavaScript
const term = new XTerm({
  fontWeight: '100',
  fontFamily: 'ubuntu mono',
  theme: {
    background: '#111'
  }
});
```
I'm using https://www.npmjs.com/package/xterm-webfont to load the webfont however the weight is consistent without it.

This is also consistent in both the latest Chrome and Firefox.

**Comment by bgw** [comment]
@Tyriar we compute the font size using `terminal.options.fontSize * window.devicePixelRatio`. I can't help but wonder if that somehow results in a bolder looking font than if we were to use `ctx.scale()` and then use `terminal.options.fontSize`.

@hatched, Your 2.x screenshot shows grayscale antialiasing. Your 3.x screenshot shows RGB subpixel antialiasing. I'm wondering if there's a compounding factor there. Can you disable subpixel AA by calling `term.setOption('allowTransparency', true)`? (where `term` is your Terminal object)

**Comment by hatched** [comment]
@bgw Here is 3.3.0 with `term.setOption('allowTransparency', true`. There doesn't appear to be any change with or without it enabled (In both Chrome and Firefox). 

<img width="376" alt="screen shot 2018-05-08 at 10 27 53 pm" src="https://user-images.githubusercontent.com/532033/39795686-1e757d48-530f-11e8-83f7-83a00d6c8a66.png">

**Comment by Tyriar** [comment]
@bgw but that's just the size, which roughly translates to the height of the character. Without that characters would be tiny on retina displays at 100% zoom for example.

**Comment by bgw** [comment]
@Tyriar There's two ways to scale up the text. One is to increase the font size (what we're doing now). The other is to call `CanvasRenderingContext2D.scale()` before drawing the character. I'm wondering if the approach we choose affects how the text is rendered.

It may not, but it's probably worth testing.

**Comment by Tyriar** [comment]
We can try, I remember that `scale` wasn't doing what I expected, maybe I was doing it wrong

**Comment by Tyriar** [comment]
We're moving towards DOM and webgl renderers in favor of the canvas one.
