### ISSUE TITLE
in ubuntu 18.04, terminal text rendering seems not right

### ISSUE THREAD

**Issue by zxdong262** [xtermjs/xterm.js#1430]
in ubuntu 18.04, terminal line-height seems not right(see picture below).
in ubutnu 16.04 is ok.
![ss-ubuntu1804-1](https://user-images.githubusercontent.com/1641949/39617334-e79d6458-4fb1-11e8-9b8d-feb742f6c712.jpg)

## Details
- Browser and browser version: electron 1.8.4
- OS version: Ubuntu 18.04 x64
- xterm.js version: 3.2.0/3.3.0

### Steps to reproduce

1. download and run electerm from https://electerm.html5beta.com

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/1170
