### ISSUE TITLE
What happened to `getState` and `setState`?

### ISSUE THREAD

**Issue by ioquatix** [xtermjs/xterm.js#1431]
There was a PR but it was closed without completion. I'd still like to see this feature. Any idea when it would be implemented?

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/pull/613#issuecomment-386588247

**Comment by ioquatix** [comment]
Is it possible we could implement a minimal `getState` and `setState` by saving and restoring the terminal buffer? That would be my use case.

Can we access the buffer data/text?

**Comment by Tyriar** [comment]
@ioquatix that's most of the request at https://github.com/xtermjs/xterm.js/issues/595
