### ISSUE TITLE
cursor at wrong column position behind last cell

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1434]
I tried to repair some of the escape sequence test files and find the same failure pattern for many of them - the cursor points to `terminal.cols` instead of `terminal.cols - 1`. Note a real VT cant move the cursor outside the screen to the right.

Not sure yet if this can be fixed at individual method level (some already have a fix in place like `HPositionRelative`, maybe from earlier bug reports) or if it has to be global change (guess the latter since I am not able to fix the ICH test with only local changes while a global change does the trick). Affected by this are at least the following terminal primitives:
- BS (backspace)
- ED (erase display)
- EL (erase line)
- ICH (insert character)

Also `top` output is affected by this, xterm places the cursor at the end of the screen (invisible) while xterm.js has the cursor at different places after a refresh in the first column (cursor is not hidden, `CSI ? 25 l` is currently not implemented). The white underlined table header is one cell short in xterm while xterm.js fills all cells to the right. With the global change top output looks identical. Other typical apps seem not to be affected by this (quick tests with ls, vim, emacs, mc, htop).

Whatever the fix will be it has to be tested extensively due to a fundamental change in the cursor handling :disappointed: 

By global I mean that a method of `InputHandler` adjusts the cursor column position to `cols - 1` before returning, thus the global accessible cursor position never contains a value bigger than `cols - 1` between method calls. A local change would allow this faulty intermediate state and fix the position on entering the method (partly implemented now). Not sure if any other code parts beside the autowrap in `addChar` are relying on the `buffer.x >= terminal.cols` condition, those would need to be changed as well for a global fix.

Edit:
Sorry for the messed up bug description, tried to clean it up a bit. :blush:

**Comment by Tyriar** [comment]
That is indeed very ugly 😆 https://github.com/xtermjs/xterm.js/commit/7194f765a73976a4935fd525e97dc64dddb1bd92

I'll look into this a bit more once the parser PR is through, strapped for time atm.

**Comment by PerBothner** [comment]
_thus the global accessible cursor position never contains a value bigger than cols - 1 between method calls_

Actually, in my experience with DomTerm, it works well to have "the global accessible cursor position" be between 0 and the number of columns _inclusive_.  If x==cols it means the next printable character will cause a wrap.  From looking at the code, this seems to be how it currently works.

In other words, I don't think you need any global or fundamental change.  At least based on my experience with DomTerm, which does pretty with with vtttest.  For example here is the DomTerm code:

    DomTerm.prototype.cursorRight = function(count) {
        this.columnSet(this.getCursorColumn()+count);
    };
    DomTerm.prototype.columnSet = function(column) {
        this.cursorSet(this.getCursorLine(), column, false);
    }
    DomTerm.prototype.cursorSet = function(line, column, regionRelative) {
        var rowLimit, colLimit;
        if (regionRelative) {
            line += this._regionTop;
            column += this._regionLeft;
            rowLimit = this._regionBottom;
            colLimit = this._regionRight;
        } else {
            rowLimit = this.numRows;
            colLimit = this.numColumns;
        }
        if (line < 0)
            line = 0;
        else if (line >= rowLimit)
            line = rowLimit-1;
        if (column < 0)
            column = 0;
        else if (column >= colLimit)
            column = colLimit-1;
        this.moveToAbs(line+this.homeLine, column, true);
    };

**Comment by jerch** [comment]
@PerBothner Yes xterm.js does it currently this way too. And it works for most things, but shows those weird behavior described above. Imho there is a bug hidden in the cursor handling, the cursor is clearly off in `top`.

For me vttest compliance is a big issue and I like this getting fixed soon (even my own old emulator is better than xterm.js - lol WTH). On the other hand it seems to cause no issues for ppl, guess apps use only a very reduced set of escape sequences nowadays (a pity if you ask me). My plan is to address this after we finished the buffer redesign and the unicode switch.
Feel free to contribute in this field if you want, you have great knowledge about VTs that would help us alot.

**Comment by PerBothner** [comment]
I wouldn't mind working on fixing vttest failures, but it's low priority unless either (1) someone pays me, or (2) I decide to switch to using xterm.js for DomTerm.  Alas. there are so many things that xterm.js can't handle yet (most obviously embedded graphics and general html) - but I'm looking forward to when that changes.
