### ISSUE TITLE
[bug]browser crash

### ISSUE THREAD

**Issue by kevinwon1985** [xtermjs/xterm.js#1435]
## Details
- Browser and browser version:  chrome 66.0.3359.139
- OS version: mac 10.13.4
- xterm.js version: 3.0, 3.1, 3.2, 3.3, master

### Steps to reproduce

1. use this crash demo commit 
`https://github.com/kevinwon1985/xterm.js/commit/c7dbb0c9808b6899bd6168ae96f4f3fa064eca97`
2. run the demo

**Comment by kevinwon1985** [comment]
here is my pull request https://github.com/xtermjs/xterm.js/pull/1436

**Comment by Tyriar** [comment]
I'd rather not expose API for this as it can very easily be handled on the consumer side. An alternative way to solve the problem is mentioned in https://github.com/xtermjs/xterm.js/issues/1416
