### ISSUE TITLE
how to send and execute remote commands to xterm running inside a container

### ISSUE THREAD

**Issue by saurabh1294** [xtermjs/xterm.js#1439]
xterm.js remote command execution

Hi,

I am running an online compiler. I run xterm.js inside a docker container. 

My problem is, I want to take commands/ esp program from user from browser and send it to xterm.js container and show the output in xterm shell. How can I do that?

I am having a tough time getting this to work. Any help would be appreciated

**Comment by Tyriar** [comment]
You need to do the transport to/from the client/server. The xterm.js demo shows a basic example of this

**Comment by saurabh1294** [comment]
That's fine but which xtrem.js api to use for remote command execution once
I send data from browser to xterm.js server ??

Xterm.writeln doesn't work. I need a rough idea about how to implement this.

**Comment by Tyriar** [comment]
Study the demo like I said, that's a working example of a client/server setup https://github.com/xtermjs/xterm.js/tree/master/demo

**Comment by saurabh1294** [comment]
I am already using this application and deployed it inside docker container
at http://code.golibrary.co. I think this demo doesn't suffice. What I want
is to send code from browser to this server running inside docker and
execute that code interactively inside the terminal on the link shared
above..

receiving data from browser is doable. But I am not clear how to execute
that code inside the terminal. As I said, term.write or writeln doesn't
work on execute commands..

Hope the query is clear to you ??

**Comment by Tyriar** [comment]
The demo uses xterm to display and get input (client) and node-pty runs the process, accepting input and telling xterm what to display. Both have inputs and outputs which you need to hook up.

**Comment by saurabh1294** [comment]
Thanks a lot. I am close to getting what I want !!






[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

**Comment by pro-src** [comment]
Glad to hear it! Please do keep in mind that Github issues isn't typically for Q/A or general help questions. Stackoverflow is though. I'm not saying that you can't ask questions here, just that this particular question is better suited for stackoverflow. If there's something _really_ missing from the demo, now that you've got things figured out, a new issue would be appropriate. This one has been closed for a minute :smile:

**Comment by saurabh1294** [comment]
Yeah sure, thanks :)



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

**Comment by saurabh1294** [comment]
One more question . Does resizing the terminal or changing its position in
the existing demo, result in any errors ?

Using web socket I am sending commands to the terminal and it's failing at
below line from bundle.js


Terminal.prototype._bindKeys = function () {

this.on('refresh', function (data) { return
_this._queueLinkification(data.start, data.end); });

}

The error is "can't read property start of undefined". Why data is
undefined here ? Am I missing something obvious ?

Please elaborate more on this function and when this function is called !




Thanks,
Saurabh


‌
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

On Sun, May 13, 2018 at 10:56 AM, Saurabh Gattani <saurabh.gattani@gmail.com
> wrote:

> Yeah sure, thanks :)
>
>
>
> [image: Mailtrack]
> <https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&> Sender
> notified by
> Mailtrack
> <https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
>

**Comment by saurabh1294** [comment]
This is fixed. Please ignore the previous query. Can you tell me how can I
get xterm instance on the server from terminal PID and then use that
terminal instance
to execute commands on server using term.writeln(<cmd>) ?


Thanks,
Saurabh



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

**Comment by saurabh1294** [comment]
I have fixed this as well. Good to close this thread.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
