### ISSUE TITLE
Let non-xterm keybindings bubble

### ISSUE THREAD

**Issue by evanplaice** [xtermjs/xterm.js#1440]
## Details
- Browser and browser version: Chromium 64.0.3282.140
- OS version: ElementaryOS Loki
- xterm.js version: 3.2.0

### Steps to reproduce

1. Trigger non-xterm custom keybinding that should be captured outside of xterm
2. Nothing happens, keybinding is being captured so it doesn't bubble.

**Comment by Tyriar** [comment]
This API lets you have fine-grained control of key events:

https://github.com/xtermjs/xterm.js/blob/685757b04b695e55380aee19c62d42fb33fed852/typings/xterm.d.ts#L395-L404

**Comment by evanplaice** [comment]
@Tyriar I knew about `attachCustomKeyEventHandler()` already. What I was wondering is, why does `xterm` capture any keybindings other than the ones it uses internally. Is there a technical reason for this.

AFAICT, if there isn't then letting non-captured keybindings continue to bubble would eliminate the need for `attachCustomKeyEventHandler()` altogether.

**Comment by Tyriar** [comment]
xterm sends stuff to the shell it thinks it _could_ handle, whether it handles it or not is up to the shell. There's no mechanism for getting feedback the other way so `attachCustomKeyEventHandler` is the best we can do.

**Comment by evanplaice** [comment]
Makes sense, thanks for the clarification.
