### ISSUE TITLE
Getting "createImageBitmap with ImageData is not implemented" from Safari users

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#1441]
I think the issue is because of generateCharAtlas' check to determine whether it is safe to call createImageBitmap: https://github.com/xtermjs/xterm.js/blob/be32695e168e1cf9b7774ef3d72220017a39b779/src/shared/atlas/CharAtlasGenerator.ts#L101.

It appears to check whether the method is available, and goes ahead if it is. However, on Safari, I think the method is available but that it does not work with every function signature. I can't reliably reproduce this, unfortunately.

**Comment by vincentwoo** [comment]
It might be users on some kind of dev build of Safari. Probably safe to ignore this for now.

**Comment by Tyriar** [comment]
@vincentwoo 👍 thanks for letting us know
