### ISSUE TITLE
[feature] add setSelection api

### ISSUE THREAD

**Issue by futurist** [xtermjs/xterm.js#1443]
Is it possible to add `setSelection` api?

That make sense if want to mark some lines as selection from JS.

**Comment by Tyriar** [comment]
What's the use case? You don't know what's in the buffer with the current API?

**Comment by futurist** [comment]
I want to show/share some terminal info to others, there's so many texts on the screen, and I want to highlight some text to show the specific lines/chars, just like I manually select some text in terminal.

In brief, need the function to generate `.xterm-selection-layer` from JS.

**Comment by futurist** [comment]
The API maybe something like below:

```js
// term.setSelection(row, col, chars)
term.setSelection(3, 1, 10)
```
will select/mark from the point line-3 col-1, to 10 chars after the start point.

**Comment by Tyriar** [comment]
@futurist but how do you know what to select? We don't expose the terminal buffer in the API currently.

**Comment by futurist** [comment]
Yeah, that's really a problem. In case this feature is reasonable, there could be some change in API maybe?

**Comment by Tyriar** [comment]
We may expose the buffer in the future but I don't think it makes sense to expose a selection API until that time.

**Comment by futurist** [comment]
Think of the `live-share` feature in VSCode, how to share my selection in terminal? Similar use case may arise related to

1. multiple user collaboration
2. demo or show remotely
3. want to do some fancy job on xterm

Or can expose some events related to user mouse events to tell the rows/cols info?

any thing helps.

**Comment by wspl** [comment]
This makes sense for implementing a single Terminal multiplexing multiple streams. Back up buffer, selection and cursor position, and restore them when they need to be used in the future.
