### ISSUE TITLE
screenReaderMode support docs available?

### ISSUE THREAD

**Issue by s-a** [xtermjs/xterm.js#1454]
Hi I found [screenReaderMode](https://github.com/xtermjs/xterm.js/blob/master/src/Terminal.ts#L116) in source. Does there exist any example or API docs how to use it?

**Comment by Tyriar** [comment]
I always refer people to the d.ts file for the API as the website becomes stale easily:

https://github.com/xtermjs/xterm.js/blob/435cf91ec73e9ef9e36c38a42a73460db0e04fee/typings/xterm.d.ts#L115-L120
