### ISSUE TITLE
Triple click should select the fully wrapped line if it spans multiple lines

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1456]
VS Code: https://github.com/Microsoft/vscode/issues/49935

**Comment by roryokane** [comment]
Possibly related code:

https://github.com/xtermjs/xterm.js/blob/f4da8af2e948f8f7ae48163153f243152dd3efce/src/browser/services/SelectionService.ts#L552-L563

https://github.com/xtermjs/xterm.js/blob/f4da8af2e948f8f7ae48163153f243152dd3efce/src/browser/services/SelectionService.ts#L999-L1009

Some code that might be related to the similar issue https://github.com/microsoft/vscode/issues/135567:

https://github.com/xtermjs/xterm.js/blob/f4da8af2e948f8f7ae48163153f243152dd3efce/src/browser/services/SelectionService.ts#L601-L610

**Comment by Tyriar** [comment]
Moved to track this edge case in https://github.com/xtermjs/xterm.js/issues/3670 instead of reopening
