### ISSUE TITLE
How to correctly handle C0 control codes without an explicit handler

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1461]
From @jerch in https://github.com/xtermjs/xterm.js/pull/1399

> C0 control codes without an explicit handler - what to do with those? To reassemble the old behavior those should call InputHandler.print. I still think printing those is faulty behavior, but maybe we should do to keep in line with old parser and address it later?

**Comment by jerch** [comment]
Possibly affected: #1204

**Comment by Tyriar** [comment]
Not sure we care about this, @jerch reopen if you disagree.
