### ISSUE TITLE
Is it possible to add a 'current working directory' event to the public API in a reliable way?

### ISSUE THREAD

**Issue by rfgamaral** [xtermjs/xterm.js#1471]
I'm wondering if it would be possible to add an event to the public API (like the `title` event, for instance) so that the current working directory was always passed to that event on every `cd` change.

Is it possible to implement such a feature in a reliable way that it doesn't matter if you're using Bash, Zsh or any other shell?

**Comment by Tyriar** [comment]
Not really, Hyper is probably doing it the best way I'm aware of AFAIK.

**Comment by rfgamaral** [comment]
@Tyriar What do you mean with "Hyper is doing it"? AFAIK, Hyper doesn't provide the current working directory in any fashion, plugins always rely on other means to retrieve that.

**Comment by Tyriar** [comment]
@rfgamaral I mean hypercwd/lsof

**Comment by rfgamaral** [comment]
@Tyriar The problem is that that doesn't work under WSL because `lsof` is running on the context of the OS running Hyper, meaning Windows.

I have a found a workaround to find the cwd when running under WSL which uses `lsof` too but runs with `bash -ic "cmd"` and it's a bit slower. Not mention that the workaround itself is probably around 90% reliable, there might be some edge cases where it fails.

That's why I was looking for a better way, something implemented directly on xterm.js, but I guess that ain't possible.

**Comment by Tyriar** [comment]
@rfgamaral yeah windows/WSL is different, the right place for this request is https://github.com/Microsoft/node-pty but there isn't really any way of doing it there either that I know of.
