### ISSUE TITLE
Add code examples to typings/xterm.d.ts using markdown syntax

### ISSUE THREAD

**Issue by pro-src** [xtermjs/xterm.js#1476]
Markdown syntax is supported in comments along with Jekyll directives if there's a good reason to use those. The [old examples](https://github.com/xtermjs/xtermjs.org/blob/8d2aa15692d59cf87e50c95fbd03892ceb84d4c6/_docs/api/Terminal.md) could be updated and copied over.

**Comment by Tyriar** [comment]
@pro-src do you have a link to the file you used to generate https://github.com/xtermjs/xtermjs.org/blob/8d2aa15692d59cf87e50c95fbd03892ceb84d4c6/_docs/api/Terminal.md? I'm interested in the exact syntax you used.

**Comment by pro-src** [comment]
What I mean about the `@decorator` issue is how typedoc renders it. The `@example` from above would produce the following markdown _without_ backward slashes.

```text
*_example_*: ```js
console.log('test');
 \```
```

Instead of

```text
*_example_*:

```js
console.log('test');
\```
```

**Comment by Tyriar** [comment]
Very cool, we should go with a format something like this then:

```
    /**
     * Resizes the terminal.
     * @param x The number of columns to resize to.
     * @param y The number of rows to resize to.
     * 
     * @example desc...
     * 
     * ```typescript
     * ...
     * ```
     */
```

**Comment by Tyriar** [comment]
> The @example decorator doesn't do anything special as of right now. You could use @anything in place of it except perhaps @param, @returns, etc.

Is there an issue for this in the typedoc repo?

**Comment by pro-src** [comment]
@Tyriar I'm still not happy with the way the typedoc annotations work with inline code blocks. I think typedoc-plugin-markdown is complicating the rendering of those.

Should examples for the terminal be prioritized over add-ons? Just checking with you cause I'll probably get around to it.

**Comment by Tyriar** [comment]
@pro-src we should prioritize examples that currently exist on the site, anything else should be considered new work that should ideally be done after we have the addon doc conversion automated.
