### ISSUE TITLE
can't find required 'xterm.js' script

### ISSUE THREAD

**Issue by grrrwaaa** [xtermjs/xterm.js#1480]
Hi there, I'm getting started with xterm.js, really excited to use it, thanks for making it!

However, I can't locate the script source "xterm.js" as mentioned in the quickstart html code on the xterm.js homepage (reposting the sxample below):

>   <!doctype html>
>  <html>
>     <head>
>       <link rel="stylesheet" href="bower_components/xterm.js/dist/xterm.css" />
**>       <script src="bower_components/xterm.js/dist/xterm.js"></script>**
>     </head>
>     <body>
>       <div id="terminal"></div>
>       <script>
>       	var term = new Terminal();
>         term.open(document.getElementById('#terminal'));
>         term.write('Hello from \033[1;3;31mxterm.js\033[0m $ ')
>       </script>
>     </body>
>   </html>

I've looked in the bower package and within the releases and src of this xterm repository. Can someone point me to where it should be? 

Also, just a note that the xterm.js script is not included in the bower package either, so the above mentioned 'quickstart' html is out of date. 

## Details
- Browser and browser version: Chrome
- OS version: Windows 10
- xterm.js version: 3.4.1?

### Steps to reproduce
Not sure what to write here... its not a bug so much as a missing file issue.

**Comment by Tyriar** [comment]
We recommend using npm, we've stopped shipping to bower. I created https://github.com/xtermjs/xtermjs.org/issues/48 to fix this on the website.

The getting started section on the repo is up to date: https://github.com/xtermjs/xterm.js#getting-started
