### ISSUE TITLE
Why colors of vim changes under xterm.js to colder tone?

### ISSUE THREAD

**Issue by inoyatov** [xtermjs/xterm.js#1481]
Colors in vim output uses colder tone. You can see results of output below:

## Details
- Browser and browser version: I tested it under VSCode IDE and Hyper.is terminal which uses internal xterm.js
- OS version: Ubuntu 16.04 LTS 
- xterm.js version:  Depends on VSCode IDE and Hyper.is

### Steps to reproduce

1. Install latest VSCode IDE, or Hyper.is terminal
2. Install vim theme from [here](https://github.com/morhetz/gruvbox)
3. Open vim using VSCode IDE's built in terminal or Hyper.is terminal and open vim under gnome terminal.
Under Gnome Terminal:
![Under Gnome Terminal](https://user-images.githubusercontent.com/7060390/40832185-d53e255c-65c5-11e8-80d9-177ecf4a7ba2.png)
Under Hyper Terminal:
![Under Hyper Terminal](https://user-images.githubusercontent.com/7060390/40832186-d56bbdf0-65c5-11e8-9be8-f7ea64336185.png)
Under VSCode IDE's built in terminal:
![Under VSCode's built in terminal](https://user-images.githubusercontent.com/7060390/40832187-d596d724-65c5-11e8-8a5f-5d94d273c8e7.png)

**Comment by Tyriar** [comment]
Those colors would be driven by the theme which you can configure depending on the program. See https://github.com/Tyriar/vscode-snazzy/blob/master/snazzy.json for an example of settings in vscode.

**Comment by inoyatov** [comment]
@Tyriar Thank you for clearing that. In terminal this color can be set using shell script. This changes reflects in Gnome Terminal. So is it possible to set this colors? As far as i understand i can only set 16 colors, plus cursor, selection, background and foreground colors.

**Comment by Tyriar** [comment]
@inoyatov ah, I think what you want is support for than sequence. Do you want to create a new issue to add support for `"\033]4;167;rgb:fb/49/34\033\\"`?

**Comment by inoyatov** [comment]
@Tyriar I will add new issue. Thank you.
