### ISSUE TITLE
[Minor] Dirty output build for xterm.js source code without test files.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [xtermjs/xterm.js#1482]
[Minor] Dirty output build for xterm.js source code without test files.
P.S. It's a bit strange that existed tests somehow did clean up "build" output.

## Details
- Browser and browser version: Google Chrome Version 66.0.3359.170 (Official Build) (64-bit)
- OS version: Fedora 28
- xterm.js version: 3.4.0

### Steps to reproduce

1. remove all tests from source code(linux command):

```
find . -name \*.test.ts -print -delete
```

2. Build xterm.js:

```
npm install
```

Build logs is dirty(contains errors):

> xterm@3.4.0 prepublish /tmp/xterm.js
> npm run build

> xterm@3.4.0 build /tmp/xterm.js
> gulp build

[13:11:11] Using gulpfile /tmp/xterm.js/gulpfile.js
[13:11:11] Starting 'tsc'...
src/AccessibilityManager.ts(11,29): error TS2307: Cannot find module 'xterm'.
src/AccessibilityManager.ts(52,40): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(76,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(77,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(78,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(80,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(81,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(82,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(83,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(84,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(88,43): error TS2339: Property 'addDisposableListener' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(89,52): error TS2339: Property 'addDisposableListener' does not exist on type 'IRenderer'.
src/AccessibilityManager.ts(167,73): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/AccessibilityManager.ts(264,40): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(9,38): error TS2307: Cannot find module 'xterm'.
src/Buffer.ts(51,73): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(57,58): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(70,63): error TS2339: Property 'scrollback' does not exist on type 'ITerminalOptions'.
src/Buffer.ts(80,30): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(95,89): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(97,40): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(118,26): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Buffer.ts(129,26): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(130,37): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(149,37): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Buffer.ts(276,31): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Buffer.ts(276,65): error TS2339: Property 'tabStopWidth' does not exist on type 'ITerminalOptions'.
src/Buffer.ts(290,32): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Buffer.ts(290,54): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Buffer.ts(301,50): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Buffer.ts(302,32): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Buffer.ts(302,54): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/CompositionHelper.ts(198,95): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/EventEmitter.ts(7,44): error TS2307: Cannot find module 'xterm'.
src/Linkifier.ts(242,35): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Linkifier.ts(243,50): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Linkifier.ts(244,49): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Linkifier.ts(245,65): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Linkifier.ts(247,27): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/Linkifier.ts(289,51): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(135,33): error TS2339: Property 'on' does not exist on type 'ICircularList<[number, string, number, number][]>'.
src/SelectionManager.ts(136,28): error TS2339: Property 'on' does not exist on type 'IBufferSet'.
src/SelectionManager.ts(292,20): error TS2339: Property 'emit' does not exist on type 'ITerminal'.
src/SelectionManager.ts(300,48): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(302,20): error TS2339: Property 'emit' does not exist on type 'ITerminal'.
src/SelectionManager.ts(321,136): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/SelectionManager.ts(321,163): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(321,184): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/SelectionManager.ts(342,43): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/SelectionManager.ts(342,110): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/SelectionManager.ts(532,54): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(544,52): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(576,52): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(576,116): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/SelectionManager.ts(596,22): error TS2339: Property 'emit' does not exist on type 'ITerminal'.
src/SelectionManager.ts(606,28): error TS2339: Property 'off' does not exist on type 'ICircularList<[number, string, number, number][]>'.
src/SelectionManager.ts(607,26): error TS2339: Property 'on' does not exist on type 'ICircularList<[number, string, number, number][]>'.
src/SelectionManager.ts(647,37): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(748,44): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionManager.ts(807,55): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionModel.ts(72,30): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/SelectionModel.ts(72,81): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/SoundManager.ts(31,112): error TS2339: Property 'bellSound' does not exist on type 'ITerminalOptions'.
src/Terminal.integration.ts(93,30): error TS2345: Argument of type '{ cols: number; rows: number; }' is not assignable to parameter of type 'ITerminalOptions'.
  Object literal may only specify known properties, and 'cols' does not exist in type 'ITerminalOptions'.
src/Terminal.ts(50,67): error TS2307: Cannot find module 'xterm'.
src/Terminal.ts(98,3): error TS2322: Type '{ cols: number; rows: number; convertEol: false; termName: string; cursorBlink: boolean; cursorSt...' is not assignable to type 'ITerminalOptions'.
  Object literal may only specify known properties, and 'cols' does not exist in type 'ITerminalOptions'.
src/Terminal.ts(289,30): error TS2339: Property 'cols' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(290,30): error TS2339: Property 'rows' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(573,87): error TS2339: Property 'rightClickSelectsWord' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(578,85): error TS2339: Property 'rightClickSelectsWord' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(703,53): error TS2339: Property 'theme' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(704,18): error TS2339: Property 'theme' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(717,19): error TS2339: Property 'on' does not exist on type 'IRenderer'.
src/Terminal.ts(738,22): error TS2339: Property 'screenReaderMode' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(804,102): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(830,108): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(1482,41): error TS2339: Property 'macOptionIsMeta' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(1795,57): error TS2339: Property 'macOptionIsMeta' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(2104,22): error TS2339: Property 'disableStdin' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(2177,18): error TS2339: Property 'rows' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(2178,18): error TS2339: Property 'cols' does not exist on type 'ITerminalOptions'.
src/Terminal.ts(2220,25): error TS2339: Property 'bellStyle' does not exist on type 'ITerminalOptions'.
src/Types.ts(6,103): error TS2307: Cannot find module 'xterm'.
src/Viewport.ts(141,57): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/Viewport.ts(165,32): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/handlers/AltClickHandler.ts(35,30): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/handlers/AltClickHandler.ts(36,22): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/handlers/AltClickHandler.ts(37,22): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/handlers/AltClickHandler.ts(157,72): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/handlers/AltClickHandler.ts(223,50): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/handlers/AltClickHandler.ts(234,37): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/handlers/Clipboard.ts(65,10): error TS2339: Property 'textarea' does not exist on type 'ITerminal'.
src/handlers/Clipboard.ts(66,10): error TS2339: Property 'emit' does not exist on type 'ITerminal'.
src/input/MouseZoneManager.ts(56,28): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/input/MouseZoneManager.ts(174,141): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/input/MouseZoneManager.ts(174,168): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/input/MouseZoneManager.ts(174,189): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/BaseRenderLayer.ts(74,46): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/BaseRenderLayer.ts(241,48): error TS2339: Property 'drawBoldTextInBrightColors' does not exist on type 'ITerminalOptions'.
src/renderer/BaseRenderLayer.ts(245,59): error TS2339: Property 'enableBold' does not exist on type 'ITerminalOptions'.
src/renderer/BaseRenderLayer.ts(251,88): error TS2339: Property 'enableBold' does not exist on type 'ITerminalOptions'.
src/renderer/BaseRenderLayer.ts(304,18): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/BaseRenderLayer.ts(315,50): error TS2339: Property 'fontWeightBold' does not exist on type 'ITerminalOptions'.
src/renderer/BaseRenderLayer.ts(315,84): error TS2339: Property 'fontWeight' does not exist on type 'ITerminalOptions'.
src/renderer/BaseRenderLayer.ts(318,59): error TS2339: Property 'fontSize' does not exist on type 'ITerminalOptions'.
src/renderer/BaseRenderLayer.ts(318,116): error TS2339: Property 'fontFamily' does not exist on type 'ITerminalOptions'.
src/renderer/ColorManager.ts(8,24): error TS2307: Cannot find module 'xterm'.
src/renderer/CursorRenderLayer.ts(71,14): error TS2339: Property 'refresh' does not exist on type 'ITerminal'.
src/renderer/CursorRenderLayer.ts(78,16): error TS2339: Property 'refresh' does not exist on type 'ITerminal'.
src/renderer/CursorRenderLayer.ts(83,26): error TS2339: Property 'cursorBlink' does not exist on type 'ITerminalOptions'.
src/renderer/CursorRenderLayer.ts(96,16): error TS2339: Property 'refresh' does not exist on type 'ITerminal'.
src/renderer/CursorRenderLayer.ts(125,76): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/CursorRenderLayer.ts(144,44): error TS2339: Property 'cursorStyle' does not exist on type 'ITerminalOptions'.
src/renderer/CursorRenderLayer.ts(160,50): error TS2339: Property 'cursorStyle' does not exist on type 'ITerminalOptions'.
src/renderer/CursorRenderLayer.ts(168,44): error TS2339: Property 'cursorStyle' does not exist on type 'ITerminalOptions'.
src/renderer/CursorRenderLayer.ts(174,42): error TS2339: Property 'cursorStyle' does not exist on type 'ITerminalOptions'.
src/renderer/LinkRenderLayer.ts(15,24): error TS2339: Property 'on' does not exist on type 'ILinkifier'.
src/renderer/LinkRenderLayer.ts(16,24): error TS2339: Property 'on' does not exist on type 'ILinkifier'.
src/renderer/Renderer.ts(16,24): error TS2307: Cannot find module 'xterm'.
src/renderer/Renderer.ts(32,54): error TS2339: Property 'allowTransparency' does not exist on type 'ITerminalOptions'.
src/renderer/Renderer.ts(77,22): error TS2339: Property 'refresh' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(77,48): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(86,36): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(86,57): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(102,22): error TS2339: Property 'refresh' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(102,48): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(119,22): error TS2339: Property 'refresh' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(119,48): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(133,34): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(133,55): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(153,66): error TS2339: Property 'allowTransparency' does not exist on type 'ITerminalOptions'.
src/renderer/Renderer.ts(189,20): error TS2339: Property 'emit' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(216,109): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/renderer/Renderer.ts(220,60): error TS2339: Property 'lineHeight' does not exist on type 'ITerminalOptions'.
src/renderer/Renderer.ts(223,107): error TS2339: Property 'letterSpacing' does not exist on type 'ITerminalOptions'.
src/renderer/Renderer.ts(227,72): error TS2339: Property 'letterSpacing' does not exist on type 'ITerminalOptions'.
src/renderer/Renderer.ts(231,57): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(232,56): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(248,86): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/Renderer.ts(249,84): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/SelectionRenderLayer.ts(58,68): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/SelectionRenderLayer.ts(61,44): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/SelectionRenderLayer.ts(67,96): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/SelectionRenderLayer.ts(73,60): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/SelectionRenderLayer.ts(78,82): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/TextRenderLayer.ts(43,33): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/TextRenderLayer.ts(43,48): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/renderer/TextRenderLayer.ts(69,36): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/TextRenderLayer.ts(130,27): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/TextRenderLayer.ts(213,43): error TS2339: Property 'cols' does not exist on type 'ITerminal'.
src/renderer/TextRenderLayer.ts(219,53): error TS2339: Property 'allowTransparency' does not exist on type 'ITerminalOptions'.
src/renderer/Types.ts(7,39): error TS2307: Cannot find module 'xterm'.
src/renderer/atlas/CharAtlasCache.ts(76,58): error TS2339: Property 'experimentalCharAtlas' does not exist on type 'ITerminalOptions'.
src/renderer/atlas/CharAtlasUtils.ts(23,28): error TS2339: Property 'experimentalCharAtlas' does not exist on type 'ITerminalOptions'.
src/renderer/atlas/CharAtlasUtils.ts(27,34): error TS2339: Property 'fontFamily' does not exist on type 'ITerminalOptions'.
src/renderer/atlas/CharAtlasUtils.ts(28,32): error TS2339: Property 'fontSize' does not exist on type 'ITerminalOptions'.
src/renderer/atlas/CharAtlasUtils.ts(29,34): error TS2339: Property 'fontWeight' does not exist on type 'ITerminalOptions'.
src/renderer/atlas/CharAtlasUtils.ts(30,38): error TS2339: Property 'fontWeightBold' does not exist on type 'ITerminalOptions'.
src/renderer/atlas/CharAtlasUtils.ts(31,41): error TS2339: Property 'allowTransparency' does not exist on type 'ITerminalOptions'.
src/shared/atlas/CharAtlasGenerator.ts(6,28): error TS2307: Cannot find module 'xterm'.
src/shared/atlas/Types.ts(6,28): error TS2307: Cannot find module 'xterm'.
src/utils/CharMeasure.ts(41,51): error TS2339: Property 'fontFamily' does not exist on type 'ITerminalOptions'.
src/utils/CharMeasure.ts(42,54): error TS2339: Property 'fontSize' does not exist on type 'ITerminalOptions'.
src/utils/Dom.ts(6,29): error TS2307: Cannot find module 'xterm'.
src/utils/RenderDebouncer.ts(2,29): error TS2307: Cannot find module 'xterm'.
src/utils/RenderDebouncer.ts(27,39): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
src/utils/RenderDebouncer.ts(41,58): error TS2339: Property 'rows' does not exist on type 'ITerminal'.
[13:11:19] TypeScript: 167 semantic errors
[13:11:19] TypeScript: emit succeeded (with errors)
[13:11:19] Finished 'tsc' after 8.2 s
[13:11:19] Starting 'browserify'...
[13:11:19] Starting 'browserify-addons'...
[13:11:19] Finished 'browserify-addons' after 212 ms
[13:11:19] Starting 'sorcery-addons'...
[13:11:19] Finished 'sorcery-addons' after 13 ms
[13:11:19] Finished 'browserify' after 499 ms
[13:11:19] Starting 'sorcery'...
[13:11:19] Finished 'sorcery' after 71 ms
[13:11:19] Starting 'build'...
[13:11:19] Finished 'build' after 33 μs
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by pro-src** [comment]
@AndrienkoAleksandr Are you sure that you've deleted all of the test files?

Try: `find src/ \( -name *.test.ts -o -name *.integration.ts \) -print -delete`

**Comment by AndrienkoAleksandr** [comment]
@pro-src +1 for your command, but even with this command output build is dirty. And by the way before Eclipse CQ for xterm.js I removed really all test files manually and build result was the same. Build is not broken, but contains dirty logs. About ```/// <reference path="../typings/xterm.d.ts"/>``` +1, it's works too. But in this case we need change more than one file.

**Comment by pro-src** [comment]
> About /// <reference path="../typings/xterm.d.ts"/> +1, it's works too. But in this case we need change more than one file.

I don't think so... but adding it to all of the files would make more sense than just one.

Not that I have preference on how to resolve this, it's not an issue for me.

**Comment by Tyriar** [comment]
Wow this is weird :confused:

**Comment by Tyriar** [comment]
Still don't totally understand why it works with the test files, but adding the reference to the root file works and makes sense (as it's already imported when the other files are parsed) https://github.com/xtermjs/xterm.js/pull/1484
