### ISSUE TITLE
Cannot use Ctrl+F to search through output in terminal

### ISSUE THREAD

**Issue by zehranaz** [xtermjs/xterm.js#1492]
Find doesn't work in terminal.

## Details
- Browser and browser version: Chromium
- OS version: Windows Version 1709 (OSBuild 16299.431)
- xterm.js version: 2.8.1 (but even latest has the same issue)

### Steps to reproduce

1. Open a terminal 
2. Type Ctrl + F
3. You will see that ^F get's typed.

**Comment by Tyriar** [comment]
Find works but you need to create the UI yourself and call the `search` addons APIs https://github.com/xtermjs/xterm.js/blob/a8964a15ddf8d2e09aca51cf29b0f83440ef5ea2/src/addons/search/search.ts#L16
