### ISSUE TITLE
Add support for setting colors using "Operation System Command" sequence.

### ISSUE THREAD

**Issue by inoyatov** [xtermjs/xterm.js#1493]
In traditional terminals which support 256 color, (Gnome terminal, xterm, iTerm and etc.) colors can be set using [Operation System Command](http://rtfm.etla.org/xterm/ctlseq.html) sequence. In example: `printf "\033]4;18;rgb:ff/00/00\033\\"`. Where `\033` escape character and 4 means color set command, followed by color number 18 and color in RGB with closing `\033\\' escape sequence. However, terminals which built using xterm.js (VC's internal terminal or Hyper terminal) dose not reflect system color change commands.

## Details
- Browser and browser version: I tested it under VSCode IDE and Hyper.is terminal which uses internal xterm.js 
- OS version: Ubuntu 16.04 LTS
- xterm.js version: Depends on VSCode IDE and Hyper.is

### Steps to reproduce

1. Input following `printf "\033]4;18;rgb:ff/00/00\033\\"` in Gnome terminal and Hyper or VC's terminal for comparison.  
2. And then input following `printf "\033[38;5;18mWhat color is it?\033[0m\n"`. It shows "What color is it?"  in RED color on the gnome terminal however on Hyper terminal it shows blue (Images attached). Changes by previous command was not reflected to xterm.js.

So, it would be nice if it will be added to xterm.js since there is many color themes which require custom colors. 
Gnome output:
![gnome-output](https://user-images.githubusercontent.com/7060390/40968636-fcdc72d4-68f0-11e8-80a8-dae01c9ab80a.png)

Hyper output:
![hyper-output](https://user-images.githubusercontent.com/7060390/40968635-fcadd078-68f0-11e8-9e89-18d51de4cff7.png)

**Comment by pro-src** [comment]
This would have to be supported by node-pty? If the command is in a script that is ran by the server, `$ change-colors.sh`, how would xterm.js know that "printf" had been used?

**Comment by jerch** [comment]
This will be possible by hooking a handler in here https://github.com/xtermjs/xterm.js/blob/master/src/InputHandler.ts#L211

@inoyatov Do you some typical examples for this OSC command? I find the description in the xterm docs kinda hard to grasp.

@pro-src  node-pty will simply forward to xterm.js, it does not matter if the bytes were created by printf or any other means.

**Comment by inoyatov** [comment]
@jerch i am using it in order to fix colors for gruvbox theme from (here)[https://github.com/morhetz/gruvbox/wiki/Terminal-specific#a-256-color-gruvbox-palette-shellscript]. Example shell script is located (here)[https://github.com/morhetz/gruvbox/blob/master/gruvbox_256palette.sh]

**Comment by Tyriar** [comment]
Is this defined in http://invisible-island.net/xterm/ctlseqs/ctlseqs.html? That's typically the spec we work from.

**Comment by inoyatov** [comment]
@Tyriar it is defined under [Operation System Commands](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands) in source you specified.

**Comment by jerch** [comment]
@Tyriar If I get it right this seems to change a color in the palette permanently?

**Comment by inoyatov** [comment]
@jerch not permanently it will last until terminal session ends. Which means if you reload xterm colors will reset to original.

**Comment by Tyriar** [comment]
Yeah, we will want to override the terminal's `ColorManager.colors.ansi[x]` and redraw when this happens.

**Comment by egmontkob** [comment]
Some notes:

- In addition to `rgb:ff/00/00`, the more standard format `#ff0000` should also work.

- The feature comes hand in hand with OSC 5 for bold etc. colors, OSC 10 & 11 for the default foreground and background, and a few other special ones up to 19 at this moment. VTE implements most, but not all of these.

- They all have a 100+ counterpart for resetting. 104 with an additional parameter resets that particular entry; 104 without an additional parameter resets all the 256 entries.

- There's also an OSC 106 (formerly known as OSC 6 conflicting with an existing functionality in macOS's Terminal.app and VTE) which is quite a mystery to me, see [VTE 722751 comment 18](https://bugzilla.gnome.org/show_bug.cgi?id=722751#c18).

- At [VTE 705985](https://bugzilla.gnome.org/show_bug.cgi?id=705985), followup fix at [793152](https://bugzilla.gnome.org/show_bug.cgi?id=793152) we figured out that the proper approach is that each palette color has two slots: one for the value set via API (e.g. the Preferences dialog) (I guess it's `ColorManager.colors` here??), and one for the value set via escape sequence (if any). The escape sequence one takes precedence whenever set. If unset (e.g. initially, or after OSC 104, 110 etc.) then the API color is drawn. The former approach of both sources fiddling with the same internal variable had problems, e.g. the API wasn't idempotent, so re-applying the very current settings cancelled the effect of escape sequences.

- It's inconsistent which of these colors are reset on a standard reset operation (OSC 10-19 aren't but OSC 4s are, or the other way around, can't recall). VTE follows xterm's inconsistency, although I'd argue this is a bug (or misdesign) in xterm (and hence in turn in vte).

- The value of `?` queries the actual resolved value (the one currently seen on UI, regardless of whether it's from API or ESC) and places in the keyboard buffer. Useful for fullscreen apps to figure out whether they run on dark-on-light or light-on-dark color scheme, as a better replacement for the braindamaged COLORFGBG (see also [VTE 733423](https://bugzilla.gnome.org/show_bug.cgi?id=733423)).

- Watch out for some confusion between `5;0` and `4;256` etc. when querying the color, see [VTE 722751](https://bugzilla.gnome.org/show_bug.cgi?id=722751) (note that we deliberately slightly deviate from xterm here).

**Comment by maxekman** [comment]
Any update on this? Would be great to have to make a base16-shell confit work in VSCode. They use that escape sequence to reset the ANSI colors and a few more. 

https://github.com/chriskempson/base16-shell

**Comment by jerch** [comment]
@maxekman Nope not yet. We recently changed the way attributes are stored internally and are still in the middle of of repo/codebase refactoring, thus feature enhancements like this have to wait until we are settled with the new and easier to use lib infrastructure.
I think we have all the bits needed to provide this feature in the future (imho only the ColorManager needs some shims where such an OSC handler can operate on).

**Comment by maxekman** [comment]
Sound good, thanks for the update!

**Comment by Tyriar** [comment]
Later on I expect ColorManager will become IColorService and we could have a component that depends on ICoreService and IColorService to hook up the OSC handler and update the colors. Probably a good idea to wait as @jerch suggests.

**Comment by slawekzachcial** [comment]
For information, I've been working on #3163 that, once finished and if merged, would provide support to set colors using OSC 4 sequences.

**Comment by Tyriar** [comment]
This was done in https://github.com/xtermjs/xterm.js/pull/3524
