### ISSUE TITLE
setOption fontSize and fontWeight changes fontFamily

### ISSUE THREAD

**Issue by s-a** [xtermjs/xterm.js#1499]
It seems there is something not working while using `setOption` `fontSize` and `fontWeight` which  changes `fontFamily`

## Details
- Browser and browser version: chrome:"61.0.3163.100" / Electron
- OS version: Windows 10
- xterm.js version: 3.4.1

### Steps to reproduce
Initialize xterm.js using `setOption`
1. `self.xterm.setOption('theme', theme)`
Change font settings
2. `xterm.setOption('fontSize', theme.fontSize || '10px')`
3. `xterm.setOption('fontWeight', theme.fontWeight || 'normal')`

**Comment by Tyriar** [comment]
Looks like this is happening because you're using `'10px'` the `string` for `fontSize`, you should use `10` the `number` as per:

https://github.com/xtermjs/xterm.js/blob/ddc94669169714bdd3b5468c5f3dd69ff5955d13/typings/xterm.d.ts#L623

**Comment by s-a** [comment]
Thank you very much.
