### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isWrapped' of undefined

### ISSUE THREAD

**Issue by ioquatix** [xtermjs/xterm.js#1509]
https://github.com/ioquatix/script-runner/issues/94

Not sure if this is an issue wiht xterm.js or script-runner. Any ideas?

**Comment by Tyriar** [comment]
What version of xterm.js? It's not clear from your package.json if you shipped with 3.3 or 3.4.

**Comment by ioquatix** [comment]
I guess it’s the latest version, because it’s not pinned to a specific version

**Comment by pelmers** [comment]
I have seen reports of this issue in Atom IDE's terminal as well, which recently upgraded from 3.1.0 to 3.4.1. Possibly it could be some race condition in the access to the buffer object or a missing bounds check? I did not dig into it too much yet.

**Comment by ioquatix** [comment]
`script-runner` is a terminal for Atom.

**Comment by Tyriar** [comment]
I'm guessing this happens when the start line of a set of wrapped rows has been trimmed from the top of the buffer and the latter part of the wrapped line is trying to be linkified. Might be wrong though, just adding a null check to prevent it going to `-1` should suffice.

@pelmers 👋

**Comment by npezza93** [comment]
If it helps, I was able to reproduce this by jumping into a tux session cat'ing a large file, scrolling up, and resizing the terminal.
