### ISSUE TITLE
ability to turn off the flash and fade of the size, e.g. "94x22"

### ISSUE THREAD

**Issue by glycerine** [xtermjs/xterm.js#1516]
I have an application where it is distracting to have the "94x22" flash and fade when resizing or initializing the xtermjs. It would be great to have a way to turn off that "display the size upon init/resize" feature.  Screenshot attached, see the lower right corner for what I mean.

![image](https://user-images.githubusercontent.com/445247/41503005-bd4e1c80-718d-11e8-8f64-3defdb488589.png)

**Comment by Tyriar** [comment]
xterm.js and its built in addons don't do that 😕, must be some other code you're running
