### ISSUE TITLE
Predictive Typing

### ISSUE THREAD

**Issue by MisterTea** [xtermjs/xterm.js#1519]
One nice feature of mosh ( https://mosh.org/ ) is predictive typing: as soon as you type, it draws an underlined version of the character.  Then if the next character sent to the terminal matches the prediction, it keeps the character (removing the underline) or if not, it deletes the prediction.

I would like to do something similar when using ssh or et with xterm.js, but for this to work I would need some way to tell xterm that these are predictive characters so xterm can undo them if it turns out that the prediction was not accurate.

**Comment by Tyriar** [comment]
I would expect this to be done either on the shell level or as an [addon](https://github.com/xtermjs/xterm.js/issues/1128) to xterm.js (which isn't really possible yet). Definitely not something we would want in the core as we're trying to keep it slim and only add critical functionality there.
