### ISSUE TITLE
How to prohibit the right button to appear in the menu bar？

### ISSUE THREAD

**Issue by Williamlook** [xtermjs/xterm.js#1533]
I want to prohibit the right click of the menu and define the event by myself.

**Comment by Williamlook** [comment]
@svenstaro @jsmecham @joaomoreno @ioquatix @yuvipanda help me,think you

**Comment by Tyriar** [comment]
You may be able to do it the normal way, otherwise we don't support it.

Also it's probably a good idea not to ping random people.
