### ISSUE TITLE
SelectionRenderLayer renders on top of TextRenderLayer

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#1539]
Excuse me if I am mistaken, but it appears xterm intentional draws the selection layer over the text layer. If you specify a selection theme color that is opaque, it will fully obscure the text beneath it. Non-opaque selections mix their color with the text layers beneath.

I'm not exactly sure what the reference xterm application does, but if you highlight in ITerm2, the selection layer is opaque and drawn behind the text layer. The color of the text layer is overridden to be  a standard color for selections, which works well.

I think this is a better approach than trying to mix the colors of the selection and text layers.

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/720
