### ISSUE TITLE
Linkifier: CSS styling of linkified links

### ISSUE THREAD

**Issue by chubin** [xtermjs/xterm.js#1540]
Would it possible to specify some CSS style for linkified links?
It would be even better if it would be possible to specify different CSS styles basing the links text/content.
By means of this mechanism, we could embed various HTML objects in the terminal output (or better to interpret it as such). But even plain CSS styles would be really great.

(maybe it is already possible, but after going through the documentation and the code I didn't manage to find out how)

**Comment by Tyriar** [comment]
Since v3 we use a canvas to render by default which makes it not possible to do this. if you want to embed something on hover this is possible using the current API by listening to the tooltip and leave callbacks:

https://github.com/xtermjs/xterm.js/blob/1395b0f03cedcce7b8ece0da96ce92c8a66d4fe7/typings/xterm.d.ts#L227-L268

If you need some other capability let us know some more specifics about the use case.

**Comment by chubin** [comment]
@Tyriar But it is impossible to display in some special way? (without hovering)

**Comment by chubin** [comment]
Yes, this too, but it is much more than that.

Currently I use xterm.js in experimental mode:

https://cht.sh/:shell/

You will get a shell here, where the user can ask any programming language questions:

For example, try this:
```
    cht.sh> python create empty file
    ...
    # [ThiefMaster] [so/q/12654772] [cc by-sa 3.0]
    cht.sh>
```

Of course, you can try any question you want, not only this one

The answer may contain links to some external resources (for example here: links to the stackoverflow answer where this information was found, to the author and to the license).

I want to display this links as links.

Of course, you may ask, how xterm.js should now that that are links, and what are the hrefs of these links? This information is known (though not displayed, but it is available to a JS script running on the page). This information looks like a dictionary:

```
{
  "[ThiefMaster]": "https://stackoverflow.com/users/298479/thiefmaster",
  ...
}
```

How should I solve this task?
What would you suggest me?
Should I use xterm.js 2.x for that?
Any other ideas?

**Comment by Tyriar** [comment]
So there's two ways I see this being solved:

- Solve for xterm.js specifically: Create a link handler for a regex matching the format you use (`[x/y/z]`) and then handle the link yourself: https://github.com/Microsoft/vscode/blob/4f870afa5871c688b6dff58a955218100f7c4054/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L112
- Solve for all terminals supporting hyperlink escape: Use the hyperlink escape when it's implemented https://github.com/xtermjs/xterm.js/issues/1134, this lets you create a HTML-style link with a label and URL

**Comment by chubin** [comment]
(by the way, Daniel, maybe you could give me a hint, how could we create a cheat.sh plugin for visual studio, so that people could send the queries directly from, Visual Studio not leaving it? We've already created plugins for Vim, Emacs and currently are working on a sublime plugin.

Is it a good starting point?

https://msdn.microsoft.com/en-us/library/bb166030.aspx?f=255&MSPPError=-2147217396

Please ignore this question if it seems to be irrelevant for you; it is irrelevant indeed; I've just noticed that you are working at the Visual Studio team, that's why I've asked it)

**Comment by chubin** [comment]
Thank you very much for the answer, I think that the both answers are appropriate, but the first one seems to be easier to implement

**Comment by Tyriar** [comment]
> how could we create a cheat.sh plugin for visual studio

I don't know anything about VS extensiblity unfortunately.

> but the first one can be implemented just now, as far as I can judge

Yep, it should work :slightly_smiling_face: 

> And with the second way, even if it will be implemented, it still would not be possible to display links in some fancy way (like a GitHub button or whatever).

We are starting to open up extensibility within xterm.js which you can read about in https://github.com/xtermjs/xterm.js/issues/1128. Once we progress more I this I can see us opening up APIs for the buffer which could potentially enable things like this.
