### ISSUE TITLE
Getting "TypeError: term._core is undefined" 

### ISSUE THREAD

**Issue by kirtangajjar** [xtermjs/xterm.js#1544]
Got them by running demo examples on npm build Likely this problem has been fixed as it runs from the "demo/builds" folder in master branch.

I also see there hasn't been a release since long time and master branch 247 commits ahead since last release.

I think it's high time xterm does a release now. Any reason for delay in release?

**Comment by Tyriar** [comment]
@kirtangajjar try doing `git clean -xfd` and reinstall, I haven't seen this personally.

This is a 2 month release as I did a bunch of travel during the normal release time.
