### ISSUE TITLE
why not exclude `src` from the npm packaging

### ISSUE THREAD

**Issue by veeramarni** [xtermjs/xterm.js#1545]
I was wondering, why it needs the npm package to include to `src` files?
https://github.com/xtermjs/xterm.js/blob/master/.npmignore#L23

Besides it increases the size of the packages to download, we have noticed `ts-loader` sometimes compiles the `src` code and throwing below error (although that was another issue due to `webpack` or `ts-loader`).

```
pr/node_modules/xterm/src/SoundManager.ts(50,5)
      TS2322: Type 'ArrayBuffer | SharedArrayBuffer' is not assignable to type 'ArrayBuffer'.
  Type 'SharedArrayBuffer' is not assignable to type 'ArrayBuffer'.
    Types of property '[Symbol.toStringTag]' are incompatible.
      Type '"SharedArrayBuffer"' is not assignable to type '"ArrayBuffer"'.
```

**Comment by Tyriar** [comment]
The reason is so that source maps are resolved. If size is critical to your application you can remove `**/*.ts` and `**/*.js.map` from your packages app.

**Comment by veeramarni** [comment]
got it. thanks
