### ISSUE TITLE
Feature Request: Allow Sending Raw Data to Terminal

### ISSUE THREAD

**Issue by ilyaigpetrov** [xtermjs/xterm.js#1546]
Sometimes I want to send a raw data to the terminal like `[?1049h[22;0;0t[1;3r(B[m[4l[?7h[H[2JHello World !!![3;1H[?1049l[23;0;0t
[?1l>`
How about exposing `term.send`?

# Why
I [compiled](https://github.com/kripken/emscripten/issues/6766) ncurses library for a browser with emscripten.
Simple ncurses command like `printw("Hello World !!!")` requires to send `[?1049h[22;0;0t[1;3r(B[m[4l[?7h[H[2JHello World !!![3;1H[?1049l[23;0;0t
[?1l>` to xterm.js (I don't know what the char codes means here).

Will it be possible?

Currently:
```js
const term = new Terminal({
  cols: 80,
  rows: 24,
  rendererType: 'dom',
});
term.open(output);
term.send(text.toString()); // TypeError: term.send is not a function
```
__UPD__:
I tried `term._core.send('[?1049h[22;0;0t[1;3r(B[m[4l[?7h[H[2JHello World !!![3;1H[?1049l[23;0;0t
[?1l>')` and it doesn't work. Maybe I do something wrong.
__UPD__
In case you want to test it yourself: https://github.com/ilyaigpetrov/ncurses-for-emscripten

**Comment by Tyriar** [comment]
You can do this by just sending it directly to the process, if you're using node-pty you would use [write](https://github.com/Microsoft/node-pty/blob/2c1c0e78c8f110b4e3da87a3f9b88ebc9e7b33b8/typings/node-pty.d.ts#L70).

**Comment by jerch** [comment]
@ilyaigpetrov I think you are mixing up the master and slave side of the pty terminal setup - `send` will write the data to the master and appear on the slave to be read (as stdin for the slave program). To get something shown in terminal you have to feed the data into the slave side of the pty or directly write it to the terminal. The latter will omit the pty, but that will get into serious trouble with this and that since the pty does some important manipulations to the data (your raw data will miss those changes). You might be able to get away with a lightway fake pty implementation in JS.

**Comment by ilyaigpetrov** [comment]
1. @Tyriar, I don't use any server, just a regular browser page, so node-pty is not an option.
> You can do this by just sending it directly to the process

I believe browser tab has only one process, not sure if sending stuff to it is what you mean.

2. @jerch, I slightly miss something, so let's discuss the whole set:
   1. ncurses is a library to print all kind of stuff to the terminal, drawing characters at terminal coordinates, maybe drawing windows, etc. It is written in C.
   2. Emscripten tool compiles C code to javascript or WASM, so it may be executed in a browser, but because most of the interfaces of browser and of shell are drastically different we need some shims that emulate, e.g., tty in a browser and allows compiled code to work with it.
   3. I thought xterm.js is an emulation of terminal for a browser and if C process wants to interact with a terminal I can glue C/ncurses program compiled to js with xterm.js to draw nice ascii animations and interfaces in a browswer.

Now you say I need to write a tty for a browser, so I guess my notion of xterm.js is wrong.
I have to think about what you said more and come up with a better plan of approaching my goals, thank you for your clarification, any further comments are welcome.

**Comment by jerch** [comment]
> I thought xterm.js is an emulation of terminal for a browser and if C process wants to interact with a terminal I can glue C/ncurses program compiled to js with xterm.js to draw nice ascii animations and interfaces in a browser.

xterm.js is a terminal emulator that can draw/handle typical interactive program output. In combination with a pty you can use it as the controlling terminal for processes (does not matter if written in C or whatever). To act as a controlling terminal for a single process the io channels stdin/stdout/stderr are typically mapped to the slave end of the pty while the emulator itself listens on the master side. This is a typical terminal emulator setup (all emulators work like this) and need the OS level pty in between (in the kernel).

If you want to run a C program compiled with emscripten in the browser this wont work that easy anymore - you dont control the browser process and cant use the std io channels (remember, your program just runs in the JS sandbox of the browser).
