### ISSUE TITLE
Setting to remove anti aliasing

### ISSUE THREAD

**Issue by Khalilw1** [xtermjs/xterm.js#1550]
I wonder if it is possible to add some setting to remove antialiasing from xterm. I prefer antialiased fonts because they look much thiner. I use xterm on VS code so it is running on electron if I understand correctly.

**Comment by Tyriar** [comment]
I don't think it's possible to draw to a canvas without AA https://stackoverflow.com/q/4261090/1156119, https://stackoverflow.com/q/195262/1156119

You can turn of _sub-pixel_ AA by turning `allowTransparency` on though.
