### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by shalvah** [xtermjs/xterm.js#1554]
This is a great tool, as shown by the number of users and companies who trust it. Unfortunately, the documentation is very poor, in my opinion.

Firstly, only a very simple guide is found in the README. What about the other things xterm can do? How do we utilise it effectively?

After lots of searching, I found [this](https://xtermjs.org/docs/api/), but it isn't linked to in the README. The problem with this documentation is it's written by machines. It lists the classes and methods and properties but doesn't tell you how they work together, how to use them, or what to watch out for. I'm personally struggling with a few issues that I haven't been able to find solutions to.

I'd suggest taking out time to write more friendly guides, explaining how you would use xterm in typical scenarios. I understand that this is OSS, and everyone working on it probably has other daily responsibilities, but maybe we can put it on a to-do list somewhere. I'd contribute to the docs, but I haven't been able to get xterm to work, so I'm still lost.

_PS: The [README section on "Addons"](https://github.com/xtermjs/xterm.js#addons) is misleading. It omitted the fact that you might need to add its CSS for an addon to work._

**Comment by shalvah** [comment]
No problem @Tyriar . Hopefully, I can get xterm working and contribute to the documentation when I have some free time.

**Comment by jtviolet** [comment]
@shalvah I have been using xterm.js for the last year now and I have been looking to start contributing in a meaningful way. I am going to work on a revision of the documentation this weekend and push something up. In the meantime, feel free to reach out to me and I can help you with your xterm project as best as I can.

**Comment by shalvah** [comment]
That's nice @jtviolet. I was finally able to figure things out. I guess my biggest challenge with xterm.js came from thinking it provided expected terminal functionality, like handling/displaying input. Didn't realise it was so barebones and you had to implement lots of stuff yourself. But I making progress now.

**Comment by cubiclesoft** [comment]
xterm.js definitely needs better documentation (especially the `Terminal.on()` event listeners).

**Comment by Tyriar** [comment]
Most of this is done, please create more focused issues if we're still lacking.
