### ISSUE TITLE
Box drawing characters with escape sequence Esc ( 0 are broken since 3.5.0

### ISSUE THREAD

**Issue by astefanutti** [xtermjs/xterm.js#1565]
Since Xterm.js version 3.5.0, box drawing characters using the escape sequence `Esc ( 0`, like `\x1b(0\x6A\x1b(B`, do not render correctly, while it was working with previous versions. 

See https://en.wikipedia.org/wiki/Box-drawing_character#Unix,_CP/M,_BBS

## Details
- Browser and browser version: Chrome
- OS version: Mac OS X
- xterm.js version: 3.5.0

### Steps to reproduce

```
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xterm@3.5.0/dist/xterm.css" />
    <script src="https://cdn.jsdelivr.net/npm/xterm@3.5.0/dist/xterm.js"></script>
  </head>
  <body>
    <div id="terminal"></div>
    <script>
      var term = new Terminal();
      term.open(document.getElementById('terminal'));
      term.write('Test \x1b(0\x6A\x1b(B\n')
    </script>
  </body>
</html>
```

**Comment by Tyriar** [comment]
I saw this reported in VS Code a while ago https://github.com/Microsoft/vscode/issues/53769, I can repro in xterm.js' demo but not VS Code.

**Comment by Tyriar** [comment]
Copying and pasting this:

<img width="320" alt="screen shot 2018-07-12 at 8 03 12 am" src="https://user-images.githubusercontent.com/2193314/42641734-1066282e-85aa-11e8-9114-b03d471787a4.png">

Yields:

```
❯ echo -e '\x1b(0\x6A\x1b(B\n'
┘
```

**Comment by Tyriar** [comment]
This only happens with the canvas renderer

**Comment by astefanutti** [comment]
> I saw this reported in VS Code a while ago Microsoft/vscode#53769, I can repro in xterm.js' demo but not VS Code.

I can reproduce the issue in VS Code as well.

**Comment by Tyriar** [comment]
This only happens using the static texture atlas (this is why I couldn't reproduce in VS Code).

@astefanutti 👍

**Comment by Tyriar** [comment]
The glyph is referencing ascii code 106 (`j`)

**Comment by Tyriar** [comment]
The glyph in 3.4:

<img width="482" alt="screen shot 2018-07-12 at 8 17 50 am" src="https://user-images.githubusercontent.com/2193314/42642645-282bc2c8-85ac-11e8-93a0-1d435e9c03bd.png">

**Comment by Tyriar** [comment]
3.4 CharData: `[131840, "┘", 1, 9496]`
3.5 CharData: `[131840, "┘", 1, 106]`

**Comment by Tyriar** [comment]
I think https://github.com/xtermjs/xterm.js/pull/1399 is root cause

**Comment by Tyriar** [comment]
@astefanutti thanks for the report, PR with fix is out.

**Comment by jerch** [comment]
Oh well was wondering about that while doing #1399, guess this means "yes".

@Tyriar Thanks for fixing it. :+1:

**Comment by astefanutti** [comment]
@Tyriar thanks for the very quick reply and fix. I confirm it works!

**Comment by Tyriar** [comment]
@jerch curiously it's only an issue for the static cache though, didn't look in to why (I guess the key is based on the char instead)
