### ISSUE TITLE
Exception when disposing the terminal while parsing

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1567]
Repro:

- Run `yes`
- Kill terminal

VS Code issue: https://github.com/Microsoft/vscode/issues/54132

**Comment by jerch** [comment]
A single parse step should be strictly in sync, so no dumping of the terminal should be possible within an `EscapeSequenceParser.parse` step. Therefore I think this happens between `InputHandler.parse` calls.

Should be fixable by testing for a valid terminal object in `InputHandler.parse` or even better, bubbling the dispose thing to the input handler and the parser as well.
