### ISSUE TITLE
Calling xterm.fit immediately after xterm.open gives incorrect measurements 

### ISSUE THREAD

**Issue by Demon000** [xtermjs/xterm.js#1572]
Calling xterm.fit immediately after xterm.open results in bad measurements, even though the resulting terminal window does fit the whole container.
Calling xterm.fit after a 1 second timeout fixes this issue. 

This seems to happen only on uncached page loads.

## Details
- Browser and browser version: Firefox Developer Edition 62.0b4 (64-bit)
- OS version: Arch Linux, 4.17.3-1-ARCH
- xterm.js version: 3.5.1

### Steps to reproduce

1. Call xterm.open, call xterm.fit
2. Retrieve xterm.rows and xterm.cols

**Comment by Demon000** [comment]
Investigation shows that actualCellWidth and actualCellHeight change from 14 and 17 to 8 and 19 after the terminal container is resized to fit another row/column.

**Comment by Demon000** [comment]
Well, I found the culprit. 14 and 17 are the sizes of the default font when the current one can't be loaded. So if the measuring happens before the desired font is actually loaded, it will use those sizes.

**Comment by Tyriar** [comment]
@Demon000 for web font support try using this: https://www.npmjs.com/package/xterm-webfont
