### ISSUE TITLE
Emoji issue

### ISSUE THREAD

**Issue by jas99** [xtermjs/xterm.js#1575]
`Hyper version 2.0.0`
Left windows is hyper and where issue lies.
Check the emoji rendered as first character.

![screenshot_2018-07-20 05 25 06_bqhisp](https://user-images.githubusercontent.com/1231593/42976367-ce540416-8bde-11e8-8165-e986f494f84e.png)

Thx

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/1059
