### ISSUE TITLE
node-pty terminals jump to bottom when a .NET Core console app requests for a cursor position

### ISSUE THREAD

**Issue by tylerl0706** [xtermjs/xterm.js#1579]
_From @tylerl0706 on July 21, 2018 3:13_

## Environment
- Environment: VSCode and Hyper
- OS version: macOS & Fedora 28

### Details

node-pty terminals jump to the bottom when a .NET Core console app requests for a cursor position. In other terminals (iterm, terminal.app), it does not.

This only happens on unix/linux OS's - Windows works as expected.

This is easily reproducible in PowerShell since it's built on .NET Core.

### Steps to reproduce

1. have [PowerShell on unix](https://github.com/powershell/powershell#get-powershell)
2. hit enter a bunch (until the page starts scrolling)
3. run this
```powershell
while ($true) { $null = [Console]::CursorTop; Start-Sleep 1 }
```
4. scroll up

> Note the use of `[Console]::CursorTop` which is the cursor query. In .NET Core, this emits the report cursor position ansi escape sequence on unix-like platforms

### Actual behavior

The console window jumps down to the prompt

### Expected behavior

The console window does not move

_Copied from original issue: Microsoft/node-pty#211_

**Comment by tylerl0706** [comment]
p.s. @Tyriar is awesome 👍

**Comment by tylerl0706** [comment]
In case it helps, [here's the function that gets called when you call `CursorTop` in corefx](https://github.com/dotnet/corefx/blob/dd8449ded9dda04f50d8394341e2b9a59bee2b0e/src/System.Console/src/System/ConsolePal.Unix.cs#L343).

**Comment by tylerl0706** [comment]
_From @jerch on July 23, 2018 16:14_

@tylerl0706 Imho this can't be fixed in the pty binding, the binding simply routes the byte streams to and from the OS into JS space. This seems more emulator related (if you use xterm.js as emulator - thats the place to address this imho).

**Comment by tylerl0706** [comment]
Ah my bad - that's my lack of knowledge of the stack. I can move this over there if you'd like

**Comment by tylerl0706** [comment]
_From @Tyriar on July 23, 2018 17:45_

This is happening because the text is sent via `Terminal.send`:

https://github.com/xtermjs/xterm.js/blob/8f22d8dda4f282e6c10943576ed5797317ad626f/src/InputHandler.ts#L1717-L1724

https://github.com/xtermjs/xterm.js/blob/8f22d8dda4f282e6c10943576ed5797317ad626f/src/Terminal.ts#L1814-L1817

I'm not totally sure what the right behavior is (I would check other terminals), but it definitely belongs in xterm.js 👍

**Comment by Tyriar** [comment]
We should check what the behavior of other popular linux/mac terminals is when you're in the scrollback and cursor position is requested, if we're doing standard behavior I'm not sure how best to fix this for PS atm.

**Comment by tylerl0706** [comment]
@Tyriar not sure if you over looked it - but in the description I mentioned that this behavior is different from within iTerm2 and Terminal.app (2 non-xtermjs terminals) on macOS. It doesn't scroll back.

**Comment by Tyriar** [comment]
@tylerl0706 oh ok, I thought this was a PS extension within VS Code thing.

**Comment by Tyriar** [comment]
@tylerl0706 can you clone [my fork](https://github.com/Tyriar/xterm.js), checkout `1579_emit_pos_directly` and test if this fixes it by running [the demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo)?

**Comment by tylerl0706** [comment]
@Tyriar sorry for the delay! I was heads down on OneWeek 👍

I can confirm that branch fixes the problem 🎉
