### ISSUE TITLE
Terminal does not clear screen after detaching from `screen`

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1582]
From @rjbruin in https://github.com/Microsoft/vscode/issues/54664

1. Open integrated terminal and switch it to the right hand side of the window
2. Install package `screen`
3. Enter a couple of commands to fill the terminal buffer
4. `screen` to open a new screen
5. Press Ctrl+A then D to detach from the screen. The previous commands in the terminal buffer are now displayed, though the terminal "cursor" is at the top of the terminal.

Expected:

![image](https://user-images.githubusercontent.com/2193314/43144496-22540346-8f12-11e8-8d7e-a9ce2202ad1b.png)

Actual:

![image](https://user-images.githubusercontent.com/2193314/43144516-2d06393a-8f12-11e8-8549-766ede699053.png)

**Comment by jerch** [comment]
@Tyriar Yes very likely. As you might remember I already started digging through those tests, but #1434 kinda got me stuck. :blush:

**Comment by Tyriar** [comment]
Can no longer repro
