### ISSUE TITLE
Adding a rendered event

### ISSUE THREAD

**Issue by faressoft** [xtermjs/xterm.js#1592]
Is it possible to provide a `rendered` event that fires when the texts passed via .write is completely written whatever the length of the text is (when the writeBuffer is flushed).

**Comment by vincentwoo** [comment]
Related to https://github.com/xtermjs/xterm.js/issues/1351

**Comment by Tyriar** [comment]
@faressoft correct me if I'm wrong but I think you're after when a frame is rendered, rather than when the write buffer is flushed? An event immediately after the buffer is flushed would fire before any changes occur in the terminal.

**Comment by faressoft** [comment]
@Tyriar yes your are right.

The event fires when we `.write()` a text whatever the length is and the text is fully rendered on the terminal (Canvas).

**Comment by Tyriar** [comment]
You can actually use the `refresh` event for this, it fires when text changes in the terminal are rendered:

https://github.com/xtermjs/xterm.js/blob/ff63d3eb2380a604e0563b8f8a2952c9cbb672d0/typings/xterm.d.ts#L381-L386

Fired here:

https://github.com/xtermjs/xterm.js/blob/ff63d3eb2380a604e0563b8f8a2952c9cbb672d0/src/renderer/Renderer.ts#L199
