### ISSUE TITLE
Column selection doesn't render correctly when the selection starts above the viewport

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1593]
VS Code issue: https://github.com/Microsoft/vscode/issues/55488

**Comment by mofux** [comment]
This only solves part of the problem for me. It now correctly draws the selection if the mouse is inside the terminal viewport, but while the mouse is moving outside of it the selection is still drawn incorrectly (expanding to the left or right edge), see the capture below

![kapture 2018-08-06 at 15 44 25](https://user-images.githubusercontent.com/2785983/43720107-d8ccddd2-998f-11e8-98fc-8b9e727ff177.gif)
