### ISSUE TITLE
Adding a .one method to the IEventEmitter

### ISSUE THREAD

**Issue by faressoft** [xtermjs/xterm.js#1595]
It would be great if we have the ability to attach an event handler that is fired once instead of storing a reference for the handler and then use `.off` method to remove it.

**Comment by faressoft** [comment]
@Tyriar

**Comment by Tyriar** [comment]
We're planning on removing access to EventEmitter stuff and adding explicit event calls that play nicer with TS, you will still be able to do a `once` like call like this: 

```ts
const disposable = term.onLineFeed(() => {

  // stop listening for consecutive events
  disposable.dispose();

  // ...

});
```

See https://github.com/xtermjs/xterm.js/pull/1569
