### ISSUE TITLE
Kindle browser

### ISSUE THREAD

**Issue by rgruesbeck** [xtermjs/xterm.js#1600]
I would like to use xterm in the kindle browser.
I've checked that it does support websockets, and work with shellinabox.
xterm loads, but does not produce anything visible.

**Comment by Tyriar** [comment]
xterm.js definitely works in Silk as it's based on Chromium. I suggest looking a little deeper as some example implementations such as:

- https://github.com/Microsoft/node-pty/tree/master/examples/electron
- https://github.com/Microsoft/vscode
- https://github.com/zeit/hyper
