### ISSUE TITLE
Slow down from 3.5.1 -> 3.6.0 with dom render type

### ISSUE THREAD

**Issue by scragg0x** [xtermjs/xterm.js#1612]
Slow down from 3.5.1 -> 3.6.0 with dom render type. You notice significant lag.

## Details
- Browser and browser version: Chrome 68
- OS version: Ubuntu 18.04 Gnome
- xterm.js version: 3.6

### Steps to reproduce

1. Launch a shell with dom render type
2. Start typing fast

**Comment by Tyriar** [comment]
There are the only changes to the DOM renderer in 3.6: https://github.com/xtermjs/xterm.js/pull/1588, https://github.com/xtermjs/xterm.js/pull/1590, https://github.com/xtermjs/xterm.js/pull/1594

Perhaps the constant one is slowing things down? :confused:

**Comment by scragg0x** [comment]
@Tyriar n/m with further testing, the chrome devtools being open on the dom was causing the slow down.
