### ISSUE TITLE
Is there a local echo?

### ISSUE THREAD

**Issue by felix0080** [xtermjs/xterm.js#1615]
Because of the network reason, Telnet is very slow, so I want to do local echo on the front end,
does this need to develop by myself?

**Comment by Tyriar** [comment]
You could try to do this yourself, it would be tricky though. I don't think such an optimization would belong in the core lib as it's complex and only applies to a subset if use cases.

**Comment by wavesoft** [comment]
I had a very similar pain with local terminal echo, so I started working on this. It might be helpful : https://github.com/wavesoft/local-echo
