### ISSUE TITLE
Word cannot be found if it is broken in the end of line.

### ISSUE THREAD

**Issue by haoqi0818** [xtermjs/xterm.js#1616]
## Details
- Browser and browser version:  chrome newest
- OS version: mac os
- xterm.js version: 3.5.1

### Steps to reproduce

1. search a word that is broken
![image](https://user-images.githubusercontent.com/6848645/44244663-94387980-a207-11e8-9ef9-66a8623165bc.png)

**Comment by haoqi0818** [comment]
#1617

**Comment by Tyriar** [comment]
Captured in https://github.com/xtermjs/xterm.js/issues/705#issue-235750050
