### ISSUE TITLE
Resizing terminal causes text to be lost.

### ISSUE THREAD

**Issue by hifall** [xtermjs/xterm.js#1618]
When I resize the terminal, some text is lost, instead of wrapped.

## Details
- Browser and browser version: Google Chrome 67.0.3396.99.
- OS version: macOS Sierra 10.12
- xterm.js version: 3.5.1

### Steps to reproduce

1. call term.resize() when the parent is resized;
2. expect long lines in terminal to wrap, but I see the loss of text;

This issue #325 reporting this behavior before has been closed.

**Comment by Tyriar** [comment]
I think you're after reflow https://github.com/xtermjs/xterm.js/issues/622
