### ISSUE TITLE
Hang when opening in hidden iframe

### ISSUE THREAD

**Issue by eoftedal** [xtermjs/xterm.js#1625]
I've been trying to use xterm.js in HTML5 slides, where it would initially be hidden (because it wasn't on the first slide). This makes xterm.js hang, due to:
Infinity is returned here:
https://github.com/xtermjs/xterm.js/blob/master/src/addons/fit/fit.ts#L45
Because ._core.renderer.dimensions.actualCellWidth is 0 (divide by null)
In this case this while loop never terminates:
https://github.com/xtermjs/xterm.js/blob/master/src/Buffer.ts#L126 because newCols = Infinity

## Details
- Browser and browser version: Chrome 68
- OS version: docker/ubuntu
- xterm.js version: 3.0.0

### Steps to reproduce
It doesnt happen all the time, and it's sometimes hard to reproduce it, but it's really annoying when it happens, as the browser tab hangs at 100% cpu:
```
<div style="display: none">
  <iframe src="http://localhost:3000/"></iframe>
</div>
```

**Comment by Tyriar** [comment]
> xterm.js version: 3.0.0

This is a very old version - I think this bug is fixed in the latest.
