### ISSUE TITLE
Wrong width/columns calculation with `fit()`

### ISSUE THREAD

**Issue by alex-saunders** [xtermjs/xterm.js#1631]
I know this issue has been opened before in #1081 , but apparently that was fixed with #1157. However, I'm facing a similar issue so hope you don't mind me opening a new issue.

When calling `term.fit()` within a fixed-width container, it doesn't look like the correct amount of columns/canvas width is being calculated?

Please see screenshot:
<img width="522" alt="screen shot 2018-08-25 at 21 17 20" src="https://user-images.githubusercontent.com/22820481/44622217-4a592e80-a8ac-11e8-897d-34429c03a1dc.png">
The red background shows the `.xterm-viewport` element, with the grey element being the calculated canvas size (and therefore number of columns).

Is there something going wrong or is there perhaps an option passed to `fit()` that I'm missing? (currently I'm just calling `term.fit()` with no options)

## Details
- Browser and browser version:  Chrome 68
- OS version: macOS High Sierra
- xterm.js version: 3.6.0

### Steps to reproduce

1. Place xterm instance within a fixed-width container
2. Call `term.fit()`

**Comment by alex-saunders** [comment]
Following on from this, I've noticed if I call `term.fit()` after a 50ms delay using `setTimeout` (within `componentDidMount` - I'm using React), it appears to correctly calculate the width - is there perhaps a timing issue going on with calling `fit()` directly after `term.open()` (just a guess)?

**Comment by jerch** [comment]
@alex-saunders:
Thats kinda to be expected - `fit` cannot do the job if your container is not hooked into the DOM yet since it gets the geometry from there.

**Comment by alex-saunders** [comment]
@jerch the container should be hooked into the DOM as i'm calling `fit` on `componentDidMount` - i.e. when everything has been mounted into the DOM

**Comment by jerch** [comment]
@alex-saunders Ah sorry misread your comment. Thats weird, it should work correctly, just tested with the demo.
Can you elaborate on how you initialize the terminal? Please also comapre your code with `createTerminal` in demo/main.js

**Comment by alex-saunders** [comment]
No problem @jerch , I've realised where I was going wrong - I was calling `fit()` before updating the theme option (which I imagine was causing some sizes changes to take place).

Closing this now
