### ISSUE TITLE
Search addon broken from buffer refactors

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1647]
Repro:

1. ls 
2. Add something to find next text box
3. Hit enter

![image](https://user-images.githubusercontent.com/2193314/44950827-517dc080-ae07-11e8-9a2e-9c1f67bacff2.png)

![image](https://user-images.githubusercontent.com/2193314/44950829-5773a180-ae07-11e8-98b0-6584976fde96.png)

**Comment by jerch** [comment]
Another `any` dumb type. Have to go through all addons line by line.

**Comment by Tyriar** [comment]
@jerch addons will eventually be typed and rely 100% on API, that's the dream anyway 😄
