### ISSUE TITLE
Search addon: Introduce a new selection type so that multiple ranges can be highlighted at once

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1653]
This would allow showing all matches of a search in the viewport and also not hijacking the regular selection.

Plan issue: https://github.com/xtermjs/xterm.js/issues/705

**Comment by Tyriar** [comment]
This is blocked on https://github.com/xtermjs/xterm.js/issues/1852

**Comment by roguexiaohuihui** [comment]
Are there any immediate plans to address this feature？

**Comment by Tyriar** [comment]
@roguexiaohuihui no, https://github.com/xtermjs/xterm.js/issues/1852 needs to be tackled first as well.

**Comment by dpdpbj** [comment]
Hi @Tyriar , any update for this issue? Seems the #1852 has been closed.

**Comment by Tyriar** [comment]
@dpdpbj it's on the plan for VS Code this month, we're looking at decorations in the scroll bar first though (https://github.com/microsoft/vscode/issues/144595)
