### ISSUE TITLE
Search addon: Support "match whole word" option

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1658]
When true, a search for `"term"` would match `"a term b"` but not `"a terms b"`

Plan issue: #705

**Comment by alexr00** [comment]
It seems like space wouldn't be the only delimiter that signifies the start/end of a word. I'm thinking that anything that isn't a letter or number should be used as a "whole word delimiter". 
Examples where "term" would **not** match:
"a 5term b" 
"a term2 b"
Examples where "term" **would** match:
"a %term b"
"a (term} b"

**Comment by Tyriar** [comment]
@alexr00 👍 I think this is what monaco does as well.
