### ISSUE TITLE
feature request: rewrap autowrapped content upon resize

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#166]
This is one of the most requested feature and actually missing in xterm. People won't lose content anymore upon resizing, a great enhancement of UX imo. `screen` has this feature enabled by default, you can test it with some lengthy output and shrinking/enlarging the terminal window.

Since it is not xterm compatible I suggest to make it switchable via an escape sequence and/or a configuration option.

**Comment by parisk** [comment]
@jerch I am not sure I totally understand this. Could you please describe how this should work and compare it with the current implementation? How do users lose content with the current resizing mode?

**Comment by jerch** [comment]
It works like the autowrapping in a browser, if you resize the text will just flow around the next line and back. xterm cant do that, if you shrink the xterm terminal window the characters at the right border will be lost.

**Comment by akalipetis** [comment]
I believe this is caused by a misconfigured PTY @jerch (sourcelair/xterm.js#171) - could you please try this out at https://www.sourcelair.com where we make sure the PTY rows/cols are in sync with the actual Terminal and let me know if it still fails?

**Comment by jerch** [comment]
Ah misunderstanding - this is no bug, it is actual a missing feature in the original xterm (not xterm.js).

**Comment by parisk** [comment]
@akalipetis is right, if you resize the back-end PTY appropriately no characters should be lost.

Since this could provide a better user experience overall for the end-user, I am marking this as a feature. We can implement this when we believe that it is important.

**Comment by jerch** [comment]
This is the behavior I am talking about:

![rewrap](https://cloud.githubusercontent.com/assets/6193135/16804573/bd72204a-490c-11e6-9a74-d8cf67d2322e.gif)

**Comment by jerch** [comment]
Closing this old issue since there are several follow-ups.
