### ISSUE TITLE
Search addon: Support "find as you type"

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1660]
> It would be nice to have a browser-style “find-as-you-type” logic. I think it would work if a couple functions were added:
> 
> * `findCurrentOrNext(needle)`
> * `findCurrentOrPrevious(needle)`
> 
> These would expand the current selection if the `needle` is present at the 0-index of the current selection; otherwise they’d do a normal `findNext` or `findPrevious`.

Plan issue: #705

**Comment by peacefullatom** [comment]
May I grab this? 😃

**Comment by Tyriar** [comment]
@peacefullatom that would be great! 😃

**Comment by peacefullatom** [comment]
Need to refine some things:
1. The "find as you type" feature should only work for the selected fragment?
2. We taking into account only the visible part of the terminal?

**Comment by Tyriar** [comment]
@peacefullatom sorry about the delay.

1. The primary difference between this and the normal search is that if the term is still matched by expanding the selection to the right, it should just do that, rather than going to the next term.
2. It should still search the whole buffer.

**Comment by peacefullatom** [comment]
Thanks a lot! 😃

**Comment by Tyriar** [comment]
This may just be restarting a matter of starting the search at the current cursor position, rather than the next line (or at the end of the search term). In that case maybe this makes more sense as an option?

https://github.com/xtermjs/xterm.js/blob/005785b84df3b6e88059bee4da43f7a16db54180/src/addons/search/Interfaces.ts#L24-L28

**Comment by peacefullatom** [comment]
Yes, it makes sense.
In case if user hits `enter` we perform regular search, in case if new symbol is readable we are updating the search term and reruning a whole routine.
Now the goals are clear, thank you 😃
