### ISSUE TITLE
Demo does not work on IE11 anymore

### ISSUE THREAD

**Issue by tsl0922** [xtermjs/xterm.js#1665]
The 3.6.0/master version stops to work on IE11.

## Details

- Browser and browser version: Internet Explorer 11.0.9600.17843
- OS version: Windows 7
- xterm.js version: 3.6.0/master

### Steps to reproduce

1. Run the demo from master
2. Open the demo on IE11

### Screenshot

![image](https://user-images.githubusercontent.com/1680515/45211508-0eb75f00-b2c5-11e8-9df3-bf3f28c58aab.png)

**Comment by Tyriar** [comment]
@tsl0922 that error is due to some plugin you have installed, can you try resolve that and check the console? If the demo doesn't work I would expect an error in the console.

**Comment by tsl0922** [comment]
@Tyriar The 3.5.0 version works fine on the same browser, I didn't remember I've installed some IE plugins.

**Comment by Tyriar** [comment]
We'll investigate before the release

**Comment by Tyriar** [comment]
I looked into this, it's related to changes in the demo using template strings and fat arrow functions. I don't think anything has slipped in which regresses IE support. This may get fixed in https://github.com/xtermjs/xterm.js/pull/1648

**Comment by tsl0922** [comment]
F12 Developer Tools works again after I installed [KB3008923](https://answers.microsoft.com/en-us/ie/forum/ie11-windows_7/imposible-use-f12-developer-tools-exception-in/09b4f305-e436-4615-a8a5-705b0bc85bbd), this is not a xterm.js bug.

**Comment by Tyriar** [comment]
@tsl0922 did you double check that the demo works again in IE11 on the master branch? I merged that PR I mentioned which I expect to fix it, just want to double check.

**Comment by Tyriar** [comment]
🎉
