### ISSUE TITLE
Linkifier doesn't handle some unicode strings

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1669]
I was this in VS Code today:

<img width="678" alt="screen shot 2018-09-08 at 12 00 17 pm" src="https://user-images.githubusercontent.com/2193314/45257876-10833000-b362-11e8-9d34-a75f28127438.png">

Failing on 140:

<img width="417" alt="screen shot 2018-09-08 at 12 01 41 pm" src="https://user-images.githubusercontent.com/2193314/45257877-10833000-b362-11e8-902d-ccd140c45e60.png">

https://github.com/xtermjs/xterm.js/blob/bdb6647ae0e83bba07b2c1937c9371a02382bde9/src/Linkifier.ts#L223

I have had reports of some links not working, perhaps this is causing it (by failing on a row before?).

**Comment by jerch** [comment]
Oh thats weird, a char should not be empty, at least I am not aware of any code that initializes a line with no cells defined.
Do have some data to repro it?

**Comment by jerch** [comment]
@Tyriar 
This doesnt work at all: `echo http://💩.la`

**Comment by Tyriar** [comment]
@jerch I was thinking more: `echo '💩 http://something.com'` breaking the text index

**Comment by jerch** [comment]
Yepp thats it - if you insert spaces before the poo in a way that "http..." wraps to the next line the error above appears.

**Comment by Tyriar** [comment]
I merged the PR but let's reopen this to keep tracking it.

**Comment by Tyriar** [comment]
I'm seeing wrapping being broken on macOS/bash when I use 💩:

<img width="854" alt="screen shot 2018-09-09 at 7 03 58 am" src="https://user-images.githubusercontent.com/2193314/45265360-95238c00-b3fe-11e8-87c6-2a82176fa671.png">

**Comment by jerch** [comment]
@Tyriar Could you test if the input problem with the PR #1678 persists?

**Comment by Tyriar** [comment]
@jerch yep it's in my queue 😃 

Also just saw this (not running your change):

<img width="437" alt="screen shot 2018-09-10 at 9 45 39 am" src="https://user-images.githubusercontent.com/2193314/45311571-611f9800-b4de-11e8-89c9-612ff797622d.png">
<img width="246" alt="screen shot 2018-09-10 at 9 45 45 am" src="https://user-images.githubusercontent.com/2193314/45311572-61b82e80-b4de-11e8-9b57-c35d6c31abc4.png">

Test text: `~/playground/jekyll❯ echo './Makefile'`
