### ISSUE TITLE
Render performance degradation from 3.0.2 to 3.7.0

### ISSUE THREAD

**Issue by tsl0922** [xtermjs/xterm.js#1677]
**Update:** This issue should be introduced between 3.3.0 and 3.4.0.

----------------------

Originally reported at: https://github.com/tsl0922/ttyd/issues/126

## Details

- Browser and browser version: Chrome69.0.3497.81
- OS version: macOS High Sierra 10.13.6
- xterm.js version: 3.7.0

### Steps to reproduce

1. Start the 3.7.0 demo.
2. Open the demo with chrome, and turn on the FPS meter.
2. Resize it to a larger size (155 cols / 40 rows).
3. Run: `vtop` (`npm install -g vtop`).
4. Press and hold the down arrow button.
5. Result: 4-14 PFS on 3.7.0 (not stable) and 30-35 FPS on 3.3.0 (stable).

It's much smoother on 3.0.2 (ttyd 1.4.0) than 3.7.0 (ttyd 1.4.1).

**Comment by Tyriar** [comment]
I don't think this is anything to worry about, some history:

- 3.0.0: Only cells that changed are re-rendered.
- Introduced around 3.1.0(?), not yet fixed: the entire line gets re-rendered when a cell in the line changes. I have a WIP to fix this but I suspect this is what you're seeing. This makes rendering a lot slower (but still very fast).
- Related: Introduced 3.5.0, fixed 3.7.0: the entire viewport was getting rendered almost every frame.

Let me know if that doesn't sound right for what you're seeing. A devtools perf profile would help better identify what's going on if not.

**Comment by tsl0922** [comment]
@Tyriar This is still an issue to me, please keep it open, thanks.

I've updated the repro steps.

**Comment by Tyriar** [comment]
@tsl0922 I'm having trouble finding it. Can you provide a chrome perf timeline to show the difference you're seeing?

<img width="495" alt="screen shot 2018-09-10 at 6 27 18 am" src="https://user-images.githubusercontent.com/2193314/45300222-9ddd9600-b4c2-11e8-8b79-9688f02e4312.png">

**Comment by tsl0922** [comment]
@Tyriar Uploaded profile data:

[profile.zip](https://github.com/xtermjs/xterm.js/files/2367375/profile.zip)

**Comment by Tyriar** [comment]
@tsl0922 which OS, browser (including versions) were both of these profiles running on?

**Comment by tsl0922** [comment]
@Tyriar macOS High Sierra 10.13.6/ Chrome 69.0.3497.81

**Comment by Tyriar** [comment]
@tsl0922 and this is xterm 3.0.2 vs 3.7.0? Can you also do the same against 3.4? 3.4 should have the line fix but not the dynamic cache parts.

**Comment by tsl0922** [comment]
@Tyriar yes its xter 3.0.2 vs 3.7.0.

3.4.0 still have this issue as 3.7.0, but 3.3.0 works good, so I've downgraded xterm to 3.3.0 in ttyd now and the reporter confirmed this fixes the issue(https://github.com/tsl0922/ttyd/issues/126#issuecomment-419750128).

[profile-330-340.zip](https://github.com/xtermjs/xterm.js/files/2373062/profile-330-340.zip)

**Comment by Tyriar** [comment]
Hm, well 3.4.0 is when the dynamic cache was introduced which touched a lot of stuff https://github.com/xtermjs/xterm.js/pull/1327

**Comment by Tyriar** [comment]
@tsl0922 yeah I think you're on to something, on my macbook I'm seeing approx the following numbers:

- 3.3.0: ~1.5ms frames
- 3.4.0: ~3ms frames (static cache)
- 3.7.0: ~7ms frames (dynamic cache)

After a look at the code it may just be the additional of the abstractions/functions/GC 🤔

**Comment by jerch** [comment]
The profile shows like >90% of the runtime is spend in `_drawUncachedChars`. Isnt this the static cache fallback?

@tsl0922 Does your input contain lots of different chars that are not in the ASCII range? Tbh both profiles look not so good regarding drawing to total runtime ratio. Could you check chrome://gpu if the browser is using hardware acceleration at all?

**Comment by tsl0922** [comment]
@jerch `chrome://gpu` shows: `Canvas: Hardware accelerated`.

This issue can be reproduced with vim too: just open source file with syntax highlighting and press j to scroll.

**Comment by Tyriar** [comment]
@jerch did you switch to dynamic cache? I'm trying to narrow down what's going on and I'm eyeing these lines atm:

String generated every char draw:

https://github.com/xtermjs/xterm.js/blob/74474da7f32ff7cbfdd120ba6adf04efaed3cb69/src/renderer/atlas/DynamicCharAtlas.ts#L39

Object created every char draw:

https://github.com/xtermjs/xterm.js/blob/74474da7f32ff7cbfdd120ba6adf04efaed3cb69/src/renderer/BaseRenderLayer.ts#L250

**Comment by Tyriar** [comment]
I'm also seeing the static atlas on the master branch drawing rows around 30% faster which I would largely put up to the string creation.

**Comment by jerch** [comment]
@Tyriar 
Ah yes, few weeks ago during some benchmarking regarding the typed array buffer I figured those interim objects are very expensive.

**Comment by jerch** [comment]
@Tyriar Could the cache key string be replaced by some integer? A template string creation vs. an integer on every char should make some difference.

**Comment by Tyriar** [comment]
Compare that to 3.3.0, note that all characters in the row appear to be getting drawn still:

<img width="472" alt="screen shot 2018-09-12 at 12 28 12 am" src="https://user-images.githubusercontent.com/2193314/45408985-caa8bf00-b622-11e8-918d-fe9ee36cee71.png">

**Comment by Tyriar** [comment]
I think I fixed it, I just removed a bunch of the object/string overhead and the dynamic cache seems to be down to around 3ms on average (from 7). PR probably tomorrow.

**Comment by jerch** [comment]
Wow nice  :+1: 

Also chrome got much much better in drawing things to canvas since version >61, the difference here between electron v2 and the newer browser is really impressive (like 3-5x faster in my tests).
