### ISSUE TITLE
Support for color-coding available/possible?

### ISSUE THREAD

**Issue by dscheste** [xtermjs/xterm.js#1683]
I am experimenting with xterm.js and wonder whether it is possible to return directory listings in a color-coded fashion, like so:
https://content.screencast.com/users/dscheste/folders/Jing/media/d418617b-ef09-4cc6-92f3-3c13cfb4d281/2018-09-12_1201.png

Thank you.

**Comment by Tyriar** [comment]
Well the normal way to do this is to configure `ls` to use colors and define `LS_COLORS` for what to use. If you didn't want to do that, sure it's possible to listen to ls output and decorate it, I wouldn't recommend it though on performance/reliability grounds.
