### ISSUE TITLE
Selection with search and unicode

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1686]
Combining, surrogate or fullwidth chars in the line and/or the search string lead to weird selection offset problems. Steps to repro:

- insert into demo: `echo -en 'combining: ééé\nfullwidth: ￥￥￥\nsurrogate: 𓂀𓂀𓂀\n'`
- search for 'ééé', '￥￥￥' and '𓂀𓂀𓂀'

The selection is kinda off for all 3 types, it gets even worse if the line contains any of these before their occurence. It seems the renderer and the selection manager do not agree on the chars widths and lengths.

Since I had a similar problem with the linkifier, it might be fixable the same way (#1678).

**Comment by jerch** [comment]
@Tyriar Nope its not gone, still the same here. Maybe its a platform issue?

Looks like this atm:
![grafik](https://user-images.githubusercontent.com/6193135/45951100-82b27080-c002-11e8-803a-f2b09a25d11d.png)
![grafik](https://user-images.githubusercontent.com/6193135/45951013-38c98a80-c002-11e8-9714-66d88fe75b88.png)

**Comment by Tyriar** [comment]
@jerch are you on Linux?

**Comment by jerch** [comment]
Yes Ubuntu 16 here.

**Comment by Tyriar** [comment]
I guess we need to have a setting for this stuff like you were suggesting before. Still not sure the best way of querying the platform for these character widths though, I doubt we can rely on all Linux distros being the same and macOS being a different case.

**Comment by Tyriar** [comment]
Same underlying issue to https://github.com/xtermjs/xterm.js/issues/1059?

**Comment by jerch** [comment]
Nope, this time its not wcwidth's fault, changing the argument I mentioned above fixes the problems (tested a few minutes ago)

**Comment by jerch** [comment]
Currently blocked by #1707 and #1709.

**Comment by jerch** [comment]
Some background on this:
The way the start and end pos of the selection is determined still does not work for all surrogates and fullwidth chars combinations - thus if there are any of those in the line before the match or in the match itself start and end offsets can occur.

This can be fixed the same way I had to fix the linkifier underlining in #1769, by mapping a string index back to the buffer index:
https://github.com/xtermjs/xterm.js/blob/c7fa89da8e97e907cdfb72b23eabf5c3a5d1bb9e/src/Linkifier.ts#L223

If done twice (match start and end) the selection will correctly point to the underlying cells.

**Comment by Tyriar** [comment]
This still happens. This is the problem line:

https://github.com/xtermjs/xterm.js/blob/cad9477eef22c0e505337c1f634f9f35a8804edc/addons/xterm-addon-search/src/SearchAddon.ts#L345

`result.term.length` for `ééé` is 6, the fix likely involves returning from `_fineInLine` an end row and col instead of the actual term.

**Comment by Silvyre** [comment]
Hello, I would like to join my peer @miggs125 in contributing to xterm by tackling this issue.

I will first attempt to improve selection of strings that include diacritical marks.

**Comment by jerch** [comment]
@Silvyre Sure thing. Note that the terminal buffer already accounts diacritical characters into one cell, thus the issue comes from the string position to cell back-mapping.

**Comment by Silvyre** [comment]
Thanks!

> Note that the terminal buffer already accounts diacritical characters into one cell with the main character

Are you referring to the [JoinedCellData type](https://github.com/xtermjs/xterm.js/blob/master/src/browser/renderer/CharacterJoinerRegistry.ts#L13)? As far as I can tell, this base type is not currently used within search selection, and that search selection instead generalizes cells as objects of [IBufferCell](https://github.com/xtermjs/xterm.js/blob/5b555bacc069e69535e94c8c80a3c34cfc500c58/typings/xterm.d.ts#L977) type.

**Comment by Silvyre** [comment]
> changing the argument I mentioned above fixes the problems (tested a few minutes ago)

Starting to get on the same page. OK, modifying [_findInLine](https://github.com/xtermjs/xterm.js/blob/d9f58c0dbbd73145779586a9a4caddba3871ffc1/addons/xterm-addon-search/src/SearchAddon.ts#L228) to return `termLength: getStringCellWidth(term)` instead of `term` still appears to improve the selection diacritical characters (at least on Ubuntu; [getStringCellWidth()](https://github.com/xtermjs/xterm.js/blob/2eb77cc4da14c09147fe11a29d85233b6152d692/src/common/CharWidth.ts#L144) calls [wcwidth()](https://github.com/xtermjs/xterm.js/blob/2eb77cc4da14c09147fe11a29d85233b6152d692/src/common/CharWidth.ts#L8), which may perform differently on other platforms?)

I can't imagine this to be a satisfactory solution, considering that, as you mentioned, this does not work for all surrogates and fullwidth chars combinations (e.g. selection of ￥ is still not great).

**Comment by Silvyre** [comment]
>  selection of ￥ is still not great, at least on Ubuntu 18.04

To clarify, it *sometimes* works, as shown in [this GIF](https://i.imgur.com/cxmdgb4.gif).

**Comment by jerch** [comment]
@Silvyre Yes working with wcwidth correction is the right way to go here. Imho needed once for the search term itself (in case it contains weird chars) to get the amount of cells taken ("cell length"), then you'd need to correct every start offset found likewise to find the real cell offset. That cell-offset + term-cell-length % cols should give the real start and end position in the buffer.

**Comment by Silvyre** [comment]
Excellent, I'll work on that. Thanks again!

**Comment by Silvyre** [comment]
I have an [architecture](https://github.com/xtermjs/xterm.js/wiki/Contributing#architecture) question regarding addons and dependencies: how would you recommend that we import the helper functions defined in `src/common/CharWidth.ts` (i.e. getStringCellWidth, wcwidth) into `addons/xterm-addon-search`?

**Comment by jerch** [comment]
@Silvyre They arent yet, the public API gets extended on request. Thus you'd have to go with internal refs for now. Maybe open an issue regarding this so we can decide how nd where to put it.

**Comment by Silvyre** [comment]
>you'd need to correct every start offset found likewise to find the real cell offset

@jerch I'm having a bit of a difficult time determining how and where cell offsetting is implemented. Is it within [BufferLine.ts](https://github.com/xtermjs/xterm.js/blob/7c82f9c7d4f2eecd26197470c2e0c17c2e53a8aa/src/common/buffer/BufferLine.ts)?

**Comment by Silvyre** [comment]
I've also noticed that `selectionEnd` appears to spend most of its time undefined, while `finalSelectionEnd` gets defined. A related bug, maybe?

**Comment by Tyriar** [comment]
Maybe, it's meant to be undefined for various types of selection if I remember right though (word, line, select all).

**Comment by jerch** [comment]
> @jerch I'm having a bit of a difficult time determining how and where cell offsetting should be (or is) implemented. Within BufferLine.ts? 

Ah yepp thats abit hidden in the codebase, the code regarding this is in Buffer.ts and BufferLine.ts, both contain several methods that demostrate how to walk cells, easiest startpoint might be this: https://github.com/xtermjs/xterm.js/blob/e8153d929d6bb4f7012d3f20aa8c74abc335715d/src/common/buffer/Buffer.ts#L480

Not sure if you can directly use this method, you have to take care where your string index origin is (whether col 0 of wrapped or unwrapped lines).

**Comment by JasinYip** [comment]
![image](https://user-images.githubusercontent.com/7105264/96073757-abec1500-0ed9-11eb-9279-edeaa119841b.png)

I'm using VSCode(1.50.0) on macOS Catalina(10.15.6) and this issue still happening.

**Comment by JasinYip** [comment]
@Tyriar   Hi, so the issue has any solutions? I tried to load xterm-addon-unicode11, it can only fix emoji chars viewing but searching for Chinese chars still having the issue.

**Comment by Tyriar** [comment]
Been a while since I looked at this code but I think we could expose the active `IUnicodeVersionProvider`'s `wcwidth` to extensions via `IUnicodeHandling.activeProvider.wcwidth` or similar to solve this.

**Comment by JasinYip** [comment]
@Tyriar How could we fix or adapt this in our production? Seems it was internal code you write above and I have no idea how should I do...

**Comment by Tyriar** [comment]
@JasinYip there's some discussion about the fix inhttps://github.com/xtermjs/xterm.js/pull/3236, been a while since I looked and don't have time atm though.
