### ISSUE TITLE
Wrapping problem with unicode in High Sierra

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1689]
Issue for tracking a wrapping problem in High Sierra:

@Tyriar 
I'm seeing wrapping being broken on macOS/bash when I use 💩:

<img width="854" alt="screen shot 2018-09-09 at 7 03 58 am" src="https://user-images.githubusercontent.com/2193314/45265360-95238c00-b3fe-11e8-87c6-2a82176fa671.png">

URL:
https://github.com/xtermjs/xterm.js/issues/1669#issuecomment-419718223

**Comment by jerch** [comment]
Oh well this is just another wcwidth problem - xterm.js' wcwidth sees 💩 as a halfwidth char and High Sierra as a fullwdith char, therefore the CR is one char to early in the stream. Since the autowrap did not happen yet the cursor jumps back to the start.

**Comment by Tyriar** [comment]
Root cause? https://github.com/xtermjs/xterm.js/issues/1059

**Comment by jerch** [comment]
Yupp :+1:
