### ISSUE TITLE
Support lineHeight in DOM renderer

### ISSUE THREAD

**Issue by pelmers** [xtermjs/xterm.js#1700]
The line height configuration is only supported in the canvas renderer (as of 3.6.0). 
pointer: https://github.com/xtermjs/xterm.js/blob/e736f1223f5c42eb1b0674050ae55184f2215806/src/renderer/dom/DomRenderer.ts#L53

I thought I had seen an issue for this already but wasn't able to find it now.

**Comment by Tyriar** [comment]
I don't think there's an issue but there's a comment calling this out.

https://github.com/xtermjs/xterm.js/blob/e736f1223f5c42eb1b0674050ae55184f2215806/typings/xterm.d.ts#L152

Open to PRs.

**Comment by Tyriar** [comment]
You can see how this used to be handled by looking at the old DOM renderer in https://github.com/xtermjs/xterm.js/pull/938

**Comment by leomoty** [comment]
Hello @Tyriar, I would like to tackle this one, is it just a matter of using lineHeight inside `DomRenderer.ts` and defaulting to normal otherwise?

**Comment by Tyriar** [comment]
@leomoty great!

We want it to act like line height in the canvas renderer, which is used here:

https://github.com/xtermjs/xterm.js/blob/e7ae4be394d67ef0ca1b4f41e5251b42b9630999/src/renderer/Renderer.ts#L222-L230

Also the value is always set so you don't need to worry about using normal:

https://github.com/xtermjs/xterm.js/blob/e7ae4be394d67ef0ca1b4f41e5251b42b9630999/src/Terminal.ts#L94

You can see how we used to do it by looking at src/Renderer.ts in this PR:

https://github.com/xtermjs/xterm.js/pull/938
