### ISSUE TITLE
Resize from the left causes flickering and characters misplaced

### ISSUE THREAD

**Issue by wspl** [xtermjs/xterm.js#1701]
I added a resize feature to my application. It supports resizing the Terminal from both left and right. But I found a weird phenomenon that the resize performance on the left is not the same as the right. Resize from the left will cause the terminal text flickering, and fast resize causes characters misplaced. (Slowly wouldn't)

## Details
- Browser and browser version: Electron 3.0.0 Chromium 66
- OS version: macOS Sierra
- xterm.js version: 3.7.0

### Steps to reproduce

1. Make a resizable container for xterm.js Terminal
2. resize the container from left side

### Video
[https://drive.google.com/open?id=1KU9z5loHpnf1XY8qRyMUwHqbpf9eyB5w](https://drive.google.com/open?id=1KU9z5loHpnf1XY8qRyMUwHqbpf9eyB5w)

**Comment by Tyriar** [comment]
@wspl I cannot reproduce the flickering on the same electron, os and xterm.js version. The only thing that should be different moving from the left is that the actual element is moving. I would guess this is related to Electron/Chrome unless your application is doing something extra?

For the characters misplaced, I've seen this before. I think it's related to the experience of wrapping the prompt, which pushes the above line up. This isn't much better in other terminal so leaving as designed for now:

<img width="1039" alt="screen shot 2018-09-19 at 7 44 06 am" src="https://user-images.githubusercontent.com/2193314/45760836-d62a5600-bbdf-11e8-8275-2ce29001966f.png">

**Comment by mofux** [comment]
Try to log the `rows` and `cols` as you resize the terminal, my guess would be that if you resize from the left, it will log `0` or `NaN` values because the container resize implementation you are using makes the xterm container "jump" between 0-size and the actual size.

**Comment by wspl** [comment]
@mofux Actually, the resize implementation is based on `ResizeObserver` API. I printed the logs and there are no any 0 or NaN:
![image](https://user-images.githubusercontent.com/2133311/45791252-75704b80-bcbb-11e8-9923-9ef2d7102486.png)

**Comment by wspl** [comment]
@Tyriar Resize from the left side is implemented by moving element. I will make a simple demo for that.

**Comment by wspl** [comment]
@Tyriar I reproduced the problem in fiddle: [https://jsfiddle.net/q40m3cox/24/](https://jsfiddle.net/q40m3cox/24/)

**Comment by mofux** [comment]
Thanks for the fiddle, I can reproduce the flickering. I don't think you are doing anything wrong - strange. I'm using a very similar way to resize xterm in my app - and it is not flickering. Was xterm.js hosted inside an iframe in your electron app that you posted the video from?

**Comment by wspl** [comment]
@mofux No. If I move the code from jsfiddle to a pure single .html file without iframe, the flickering can be reproduced too.
```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/xterm@3.7.0/dist/xterm.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xterm@3.7.0/dist/xterm.css">
  <style>
    .box {
      display: flex;
      height: 400px;
    }
    .left-resizable {
      resize: both;
      overflow: auto;
      min-width: 100px;
      background: yellow;
      margin-right: 10px;
    }
    .right {
      flex-grow: 1;
      position: relative;
    }
    #terminal {
      position: absolute;
    }
  </style>
</head>

<body>
  <div class="box">
    <div class="left-resizable"></div>
    <div class="right">
      <div id="terminal"></div>
    </div>
  </div>
  <script>
    const term = new Terminal()
    term.open(document.getElementById('terminal'))
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')

    const observer = new ResizeObserver(entries => {
      console.log(term)
      const cellWidth = term._core.renderer.dimensions.actualCellWidth
      const cellHeight = term._core.renderer.dimensions.actualCellHeight
      const cols = Math.floor(entries[0].contentRect.width / cellWidth)
      const rows = Math.floor(entries[0].contentRect.height / cellHeight)

      term.resize(cols, rows)
    })
    observer.observe(document.querySelector('.right'))
  </script>
</body>
</html>
```

**Comment by mofux** [comment]
Yep, also reproduces for me. I've tested in Chrome on Mac and Linux, it happens in both.

**Comment by Tyriar** [comment]
I can repro on a much more stripped down example https://jsfiddle.net/dasw0gb3/

Not sure why it's happening here and not in my implementation but maybe it's something to do with the canvas texture getting cleared and needing to get redrawn whenever you call resize? Note that the DOM renderer does not show this.

Resize emits resize:

https://github.com/xtermjs/xterm.js/blob/290c95ad71f8b1264139a7ed6f070c4741a8987e/src/Terminal.ts#L1685

Which tells the renderer to resize

https://github.com/xtermjs/xterm.js/blob/290c95ad71f8b1264139a7ed6f070c4741a8987e/src/Terminal.ts#L705

Which resizes the render layers:

https://github.com/xtermjs/xterm.js/blob/290c95ad71f8b1264139a7ed6f070c4741a8987e/src/renderer/Renderer.ts#L123

Then emits its resize event:

https://github.com/xtermjs/xterm.js/blob/290c95ad71f8b1264139a7ed6f070c4741a8987e/src/renderer/Renderer.ts#L136-L139

---

I tried the standalone example in https://github.com/xtermjs/xterm.js/issues/1701#issuecomment-423078424 and I don't see it 😕

**Comment by jerch** [comment]
Repro'ed with all chromium versions I have here on Ubuntu (65, 68, 69, 71, thanks to puppeteer). The timeline shows heavy painting and GPU activity, scripting is < 10%. Firefox shows no perceivable flickering at all. In electron 2 there is flickering as well but less obvious.

Maybe this is just "bad timing" of the browser blitting the actual canvas content into to the screen? At least there are several places, where the canvas has an intermediate "black'd out" state:

https://github.com/xtermjs/xterm.js/blob/a531b4dd9b5341556e64fcc2f8d25ed9f27960f8/src/renderer/BaseRenderLayer.ts#L108
https://github.com/xtermjs/xterm.js/blob/a531b4dd9b5341556e64fcc2f8d25ed9f27960f8/src/renderer/TextRenderLayer.ts#L261

If thats the culprit it could be solved by offscreen prerendering and doing the clear & draw thing coupled together as close as possible. (Maybe just for the resize part, I think general prerendering has a negative impact on runtime).

**Comment by wspl** [comment]
@Tyriar I found that vscode also has a scene that modifies the cols/rows of the terminal when container resizing, but it won't flickering. How does vscode solve this problem?

**Comment by Tyriar** [comment]
Can't repro anymore
