### ISSUE TITLE
TypeError: Cannot read property 'isWrapped' of undefined at Buffer.getWrappedRangeForLine

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1702]
![image](https://user-images.githubusercontent.com/2193314/45791827-2933f580-bc40-11e8-90f7-a9436d0a02a0.png)

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/45791973-b5deb380-bc40-11e8-876d-69e47ad1d253.png)

![image](https://user-images.githubusercontent.com/2193314/45792020-f2aaaa80-bc40-11e8-8860-e94fb09adc14.png)

**Comment by Tyriar** [comment]
It's happening because endIndex is being passed into iterator and it's invalid. In this example:

```
ydisp = 98
ybase = 98
absoluteRowIndexStart = 98
this._rowsToLinkify.start = 0
this._rowsToLinkify.end = 25
_endIndex = 124
_buffer.lines.length = 115
terminal.rows = 17
```

![image](https://user-images.githubusercontent.com/2193314/45792480-b8420d00-bc42-11e8-8695-3010c6a9ae64.png)

I think this is happening after a vertical resize down as I was tweaking font size/family before hitting this. Since the error was thrown once the `this._rowsToLinkify.end` value never gets set to `null` as it's at the end of that function, that's why I keep seeing the error despite the value of `this._rowsToLinkify.end` not making sense any more.

**Comment by Tyriar** [comment]
FYI @jerch

**Comment by jerch** [comment]
Hmm, was not able to repro it. The iterator does not do any sanity checks atm, gonna add them to #1693.
