### ISSUE TITLE
Add a demo to the website

### ISSUE THREAD

**Issue by MartinMuzatko** [xtermjs/xterm.js#1712]
All these products that use xterm are nice to see, but it would be great to see a living and working demo in the browser.

**Comment by Tyriar** [comment]
It's probably a good idea to show a demo on the website http://xtermjs.org, it probably doesn't need a backing process but just some fake commands on the client side to show off some features (links, colors, throughput, etc.).

**Comment by whydoubt** [comment]
Adapting https://busybox.net/live_bbox/live_bbox.html to use xterm.js could be one way to provide a demo.  AFAICT it runs fully in the browser, but does take a moment or two to 'boot'.

**Comment by Tyriar** [comment]
Probably a bit overkill when a handful of canned commands would communicate mostly the same idea. Also the booting maxes out the CPU for 30 seconds on my PC 😛

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xtermjs.org/pull/61
