### ISSUE TITLE
How to set background color on terminal

### ISSUE THREAD

**Issue by zwhitchcox** [xtermjs/xterm.js#1719]
I set the background terminal color with

```js
term._core.renderer.colorManager.colors.background = {
  css: "#fdf6e3",
  rgba: "rgb(253, 246, 227)",
}
```

Just wanted to share my solution and immediately close this is anyone else was having the same problem

**Comment by zwhitchcox** [comment]
Also, I don't think gitter is a viable solution, because other people can't learn from that

**Comment by mofux** [comment]
This is not really the recommended way of defining the colors 😀You can pass a `theme` object with colors in the Terminal constructor options, e.g.:

```javascript
const term = new Terminal({
  theme: {
    background: '#fdf6e3'
  }
});
```

You can also update the theme colors at runtime:
```javascript
term.setOption('theme', {
    background: '#fdf6e3'
});
```

**Note 1**: If you don't define a theme value, we will use the default fallback value for it.
**Note 2**: If you want a transparent background, you also have to specify the [allowTransparency](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#allowtransparency) option.

For a list of available theme colors, check this out:
https://xtermjs.org/docs/api/terminal/interfaces/itheme/

**Comment by mofux** [comment]
I would blame our docs, they are not really helpful in explaining the options available 😅

**Comment by JoeStrout** [comment]
If it makes you feel any better, people-from-six-years-ago, it's now 2024 and the docs are no better.

Isn't there some way to change the colors by simply tweaking xterm.css or style.css?

**Comment by jerch** [comment]
> If it makes you feel any better, people-from-six-years-ago, it's now 2024 and the docs are no better.

Feel free to come up with suggestion or PRs for better online docs here: https://github.com/xtermjs/xtermjs.org

> Isn't there some way to change the colors by simply tweaking xterm.css or style.css?

Nope. Main reason for this - the terminal has 3 different default renderers, where only one is DOM/CSS based. And all must keep working with whatever abstraction you come up with.
