### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by zwhitchcox** [xtermjs/xterm.js#1721]
It would be nice if you could change the background color of the terminal. I can change the color as described in #1719, but it still leaves a small stroke around the letters that I can't figure out how to get rid of.

![screenshot from 2018-10-02 10-20-42](https://user-images.githubusercontent.com/4328800/46354558-df2e1500-c62c-11e8-94cf-8a290b199ee0.png)

**Comment by mofux** [comment]
@zwhitchcox Please see my comment in #1719, it should fix your problem.
