### ISSUE TITLE
Linkifier.prototype._doLinkifyRow throwing 'char is undefined'

### ISSUE THREAD

**Issue by rptl** [xtermjs/xterm.js#1722]
Streaming nginx logs to xtermjs, folowing string is throwing "char is undefined":

`2018/10/02 14:15:02 [error] 8#8: *135 connect() failed (111: Connection refused) while connecting to upstream, client: 10.255.0.2, server: 192.168.0.20, request: "GET /liveness HTTP/1.1", upstream: "http://192.168.0.20:8080/liveness", host: "192.168.0.20:9099"`

Code snippet:
   ```
 var uri = match[typeof matcher.matchIndex !== 'number' ? 0 : matcher.matchIndex];
    var index = text.indexOf(uri);
    var line = this._terminal.buffer.lines.get(this._terminal.buffer.ydisp + rowIndex);
    var char = line.get(index);
```

Looks like some char is leading to wrong 'index' on 'uri'

**Comment by jerch** [comment]
@rptl Which version if xterm.js are you using? Can you try master and see if the problem persists?
