### ISSUE TITLE
Selection can start in the middle of a double-width character

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#1732]
Version: 3.8.0 and below

When starting the selection on the second half of a double-width character, only half of that character gets selected. I would expect that ~~the whole character~~ the character closest to the selection direction gets selected once hovered in that case.

**Actual**
![kapture 2018-10-08 at 20 24 48](https://user-images.githubusercontent.com/2785983/46626774-a0222700-cb38-11e8-943e-040b6e762001.gif)

**Expected**
![kapture 2018-10-09 at 1 50 24](https://user-images.githubusercontent.com/2785983/46639374-daee8400-cb65-11e8-8746-ce8ada4e7bea.gif)

**Comment by Tyriar** [comment]
Code pointer:

https://github.com/xtermjs/xterm.js/blob/8d16bb6ea2e90312b0efb28bee3f39d3995a906f/src/SelectionManager.ts#L502-L507

**Comment by egmontkob** [comment]
> second half [...] expect that the whole character gets selected

I'd expect that the character doesn't get selected in that case :)

The behavior in pretty much all graphical applications (but unfortunately not in many terminal emulators) is that the click or drag location is rounded to the closest boundary between characters. That is, a character gets selected if you click on its first half and move the mouse to the right, or click on its second half and then move the mouse to the left.

(Word selection at double clicking requires a different strategy, though.)

(I happen to be in the finish of rewriting of VTE's selection code, expected to land in a day or two; you might want to see for some long comments inside the patch in [VTE 34](https://gitlab.gnome.org/GNOME/vte/issues/34) about my opinion on the desired behavior :) Of course it's just one opinion, hopefully backed up by some rationale, but feel free to disagree.)

**Comment by Tyriar** [comment]
> That is, a character gets selected if you click on its first half and move the mouse to the right, or click on its second half and then move the mouse to the left.

@egmontkob yeah I think that's how the selection code I wrote works, obviously selecting half the character isn't good though 😄. If the fix can act like this, it should 👍

**Comment by mofux** [comment]
@egmontkob Thanks for your thoughts. I agree, we shouldn't perform a selection in that case and only start selection on a neighbour cell if the cursor drags over it.

**Comment by Tyriar** [comment]
@dubzzz I think that's handled at a different level, if it visually comes out as a single cell in the terminal, selection should work fine.
