### ISSUE TITLE
Issue writing to terminal after parent calls show() after hidden().

### ISSUE THREAD

**Issue by hifall** [xtermjs/xterm.js#1734]
I have found some similar issue in the repo, but the fix did not work for me (see below).

An xtermjs instance is created inside a div. There are 2 tabs, tab 1 and tab 2. When tab 1 is clicked, it calls jQuery's show() for the div containing the xtermjs instance. When tab 2 is clicked, it calls hide() to hide the div and shows something else.

When tab 1 is not active and the div is hidden, I try to call xterm.writeln on the instance to add some new content, then click on tab 1. Now I expect the new content to be available in the terminal, however, it's not there.

I have called `term.resize(term.cols, term.rows)` as suggested in [https://github.com/xtermjs/xterm.js/issues/573](https://github.com/xtermjs/xterm.js/issues/573), but that did not help.

## Details
- Browser and browser version: Google Chrome 69.0.3497.100 (Official Build) (64-bit)
- OS version: macOS Sierra 10.12
- xterm.js version: 3.5.1

### Steps to reproduce

1. create 2 divs and 2 tabs, each tab shows one div, and a terminal inside first div;
2. click on tab 2, write some data to terminal;
3. click on tab 1, terminal gets visible, but new data is not.

**Comment by Tyriar** [comment]
@hifall could you create a small repo so it's easy to repro the problem?

**Comment by jerch** [comment]
Closing the issue due to inactivity. @hifall Feel free to reopen if the issue persists.
