### ISSUE TITLE
Data lost after pumping a few hundred lines.

### ISSUE THREAD

**Issue by hifall** [xtermjs/xterm.js#1746]
When I pump  a few hundred lines of data into the terminal, and scroll to the top, the first lines are missing. I expected there is some option to set the buffer size, but I did not find any from docs.

## Details
- Browser and browser version: Google Chrome 69.0.3497.100 (Official Build) (64-bit)
- OS version: macOS Sierra 10.12
- xterm.js version: 3.5.1

### Steps to reproduce

1. create 1 terminal;
2. call writeln to write a few hundred lines of data;
3. scroll to the top of the terminal, the first lines are not there.

**Comment by mofux** [comment]
This is actually expected if your input lines exceed the size of the scrollback buffer. You can configure how long that scrollback buffer should be as an option:
https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#scrollback

```javascript
const term = new Terminal({ scrollback: 2000 });
```
