### ISSUE TITLE
The search addon searches from where was last clicked, not the top of the viewport when there is no selection

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1749]
Maybe this if is always true?

https://github.com/xtermjs/xterm.js/blob/b650db5b1ae230d4c7adeb39c433be28712dc66f/src/addons/search/SearchHelper.ts#L34-L37

VS Code issue: https://github.com/Microsoft/vscode/issues/59376

**Comment by skprabhanjan** [comment]
@Tyriar , I changed it accordingly but I have one doubt 
` if (this._terminal.getSelection().length !== 0) {
        startRow = this._terminal._core.selectionManager.selectionEnd[1];
      }
      else if (this._terminal.getSelection().length === 0) {
        **startRow = X **
      }`
should this X be this._terminal._core.selectionManager.selectionStart[1] or 0 or something else ? 
Will send a PR to fix this if you confirm this , thanks :)

**Comment by Tyriar** [comment]
@skprabhanjan ydisp contains the absolute row for the top of the viewport, so that would be the one to use when there is no selection 👍
