### ISSUE TITLE
Search addon: Finding no results should clear the selection

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1750]
Repro:

1. Find something that exists
2. Find something that doesn't exist, the selection should go away

VS Code issue: https://github.com/Microsoft/vscode/issues/59372

**Comment by skprabhanjan** [comment]
@Tyriar , Can i work on this ? 
If so can you give some starting pointers ? 
Fixing this will automatically fix the vscode issue ?
Thanks :)

**Comment by Tyriar** [comment]
@skprabhanjan sure!

That's basically what you'll need to do yeah, just use `this._terminal.clearSelection()` instead though as that's part of the public API:

https://github.com/xtermjs/xterm.js/blob/37972aa5dda107da569dded73863815bf25a0cea/typings/xterm.d.ts#L562

**Comment by skprabhanjan** [comment]
@Tyriar  Okay done,  sent a PR.
Will this also fix the corresponding vscode issue or should i change something there also ?
Thanks!

**Comment by Tyriar** [comment]
@skprabhanjan I'll pull the change into vscode 😃
