### ISSUE TITLE
Can't click the scrollbar

### ISSUE THREAD

**Issue by pansila** [xtermjs/xterm.js#1751]
I can't click the the scrollbar, but mouse wheel works.

## Details
- Browser and browser version: electron 2.0.11
- OS version: Windows 7 x64
- xterm.js version: 3.7.0

### Steps to reproduce

1. Import xterm.js in the electron + vue app
2. Apply fit addon to follow resize event
3. Open the terminal on the component's 'mounted' callback
4. fit the terminal on the resize event
5. After terminal shows up, I can't click the scrollbar.

xterm-screen content width including the scrollbar
![image](https://user-images.githubusercontent.com/5125601/46956441-ee4ea180-d0c7-11e8-979c-62a3f84070c0.png)
while xterm-rows has a margin-right to make way for scrollbar
![image](https://user-images.githubusercontent.com/5125601/46956503-176f3200-d0c8-11e8-9aba-30885ee3ea3e.png)
xterm-viewport
![image](https://user-images.githubusercontent.com/5125601/46956673-70d76100-d0c8-11e8-83eb-3b8509509945.png)

CSS styles:
xterm-rows
![image](https://user-images.githubusercontent.com/5125601/46956898-fe1ab580-d0c8-11e8-8a88-aa49a898e49d.png)

xterm-screen
![image](https://user-images.githubusercontent.com/5125601/46956870-efcc9980-d0c8-11e8-8c4e-f60806666900.png)

xterm-viewport
![image](https://user-images.githubusercontent.com/5125601/46956919-0a9f0e00-d0c9-11e8-9821-8d5a060c126e.png)

I searched around and found #512 and #1284, it works if I introduce the following CSS style:
```
.xterm .xterm-screen {
    margin-right: 20px;
}
```

Then I dug further and found it works without the patch CSS above if I change the code in the function _updateDimensions of DomRenderer.js as following:
`xterm\lib\renderer\dom\DomRenderer.js`

```
DomRenderer.prototype._updateDimensions = function () {
...
-        this._rowContainer.style.width = this.dimensions.canvasWidth + "px";
-        this._rowContainer.style.height = this.dimensions.canvasHeight + "px";
+        this._terminal.screenElement.style.width = this.dimensions.canvasWidth + "px";
+        this._terminal.screenElement.style.height = this.dimensions.canvasHeight + "px";
```

It looks that xterm-screen is shading xterm-viewport so that scrollbar can't receive the click event.
Is it a real problem? Or am I using xterm.js the wrong way? Thanks.

**Comment by Tyriar** [comment]
@pansila it's working in the demo for me (on a mac), it could be an error in your CSS?

**Comment by whydoubt** [comment]
When using the demo, after setting rendererType to 'dom', I observe this behavior as well.
It is similar to the referenced issues, but this time it is with the newer DOM renderer.
