### ISSUE TITLE
select text does not work correctly when xterm in a fixed div and scroll the browser at the same time.

### ISSUE THREAD

**Issue by bigfish02** [xtermjs/xterm.js#1761]
## Details
- Browser and browser version:  chrome:69
- OS version: mac os 10.13
- xterm.js version: xterm3.7

### Steps to reproduce

1. I input xterm in a fixed div.
2. scroll the browser page
3. select text does not work 
![image](https://user-images.githubusercontent.com/13795019/47069991-df303680-d222-11e8-8f54-0f357c03333f.png)
Select '/data/apps' ,it will select some text(yellow label) after these content.
If I do not scroll the browser, it will select correctly.

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/1684
