### ISSUE TITLE
Column selection crosshair doesn't go away when you alt+tab

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1767]
## Details
- Browser and browser version: Chrome
- OS version: Windows
- xterm.js version: 3.8.0

### Steps to reproduce

1. Launch demo
2. Put mouse over terminal
3. alt+tab to another program
4. Release alt
5. Mousing over the unfocused browser will incorrectly change to the crosshair cursor

Related: 

https://github.com/xtermjs/xterm.js/pull/1766

**Comment by skprabhanjan** [comment]
@Tyriar ,
Can you tell me how to reproduce this on Mac OS and some pointers to start as I would like to fix this :)

**Comment by Tyriar** [comment]
@skprabhanjan I don't think you can repro it on macOS because the issue is related to the conflict between alt column selection and _alt_+tab on Windows/Linux

**Comment by whydoubt** [comment]
Definitely harder to reliably fix an issue when you can't observe the problem / observe and verify the fix.  Anyway, I have a fix ready that I haven't pushed, but I am not where I can do so at the moment.  FWIW, while my fix does change a couple of lines in the code as well as a CSS change, it could be done purely in CSS.
