### ISSUE TITLE
How do I accept Input/Enable Textarea in xterm?

### ISSUE THREAD

**Issue by CreatorVilius** [xtermjs/xterm.js#1771]
How do I enable user input in xterm?

**Comment by Tyriar** [comment]
The demo provides a basic client/server setup for this https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo

You can also see the example in the node-pty repo for an example Electron app https://github.com/Microsoft/node-pty/tree/master/examples/electron

**Comment by CreatorVilius** [comment]
Problem is, for some reason I keep getting python error shit which doesn't let me install it. It makes impossible to make input for me then.

**Comment by Tyriar** [comment]
@CreatorVilius what's the error and the OS? Did you install node-pty's deps? https://github.com/Microsoft/node-pty#dependencies-on-windows
