### ISSUE TITLE
drawBoldTextInBrightColors is not taken into account with DOM renderer

### ISSUE THREAD

**Issue by astefanutti** [xtermjs/xterm.js#1773]
## Details
- Browser and browser version: Chrome 70
- OS version: Mac OS X
- xterm.js version: 3.8.0

### Steps to reproduce

1. Set `drawBoldTextInBrightColors` to `false` and `rendererType` to `dom`
2. Bold characters are still rendered brighter

It works as expected with the canvas renderer.

**Comment by Tyriar** [comment]
Code pointers:

- DOM renderer bold code https://github.com/xtermjs/xterm.js/blob/160b4a7d669b6c527fec1bc40a18ae79db7d19de/src/renderer/dom/DomRendererRowFactory.ts#L81
- How the canvas renderer handles it https://github.com/xtermjs/xterm.js/blob/a7b051c52f1cb6bc4c02a1786a9d949bd8d46ad7/src/renderer/BaseRenderLayer.ts#L261

**Comment by leomoty** [comment]
I will probably take this one as well, question, how do I get bold characters tho?

**Comment by Tyriar** [comment]
@leomoty for the dom renderer the bold characters are drawn using the bold class. I think for this issue you just need to match the logic around drawBoldTextInBrightColor for this section https://github.com/xtermjs/xterm.js/blob/160b4a7d669b6c527fec1bc40a18ae79db7d19de/src/renderer/dom/DomRendererRowFactory.ts#L82-L85

**Comment by leomoty** [comment]
@Tyriar I think I wasnt clear, how do I repro bold characters? I don't think I saw anything different in Windows. I also have a Linux machine at my disposal.

**Comment by Tyriar** [comment]
Ah, on Windows you can do it by installing WSL (if not already), running that shell by running `bash` then running these:

```
echo -e '\x1b[31mRed normal\x1b[0m'
echo -e '\x1b[31;1mRed bold\x1b[0m'
```

To print the bright colors:

```
echo -e '\x1b[91mBright red normal\x1b[0m'
echo -e '\x1b[91;1mBright red bold\x1b[0m'
```

**Comment by leomoty** [comment]
Hey @Tyriar, this doesn't seem to work properly, I am invoking bash from cmd:

![image](https://user-images.githubusercontent.com/1463740/48318847-5a4ff700-e5ed-11e8-98f0-a2a6da4675d3.png)

According to the code it should append "xterm-bold"  class, so both 2nd and 4th line should have it? But seems like flags is always set to "0", thus that block never runs.

It seems that the decoded `fg` is already offsetted:

![image](https://user-images.githubusercontent.com/1463740/48318932-5cff1c00-e5ee-11e8-9037-4bbe97b9396a.png)

**Comment by leomoty** [comment]
> @leomoty for the dom renderer the bold characters are drawn using the bold class. I think for this issue you just need to match the logic around drawBoldTextInBrightColor for this section
> 
> [xterm.js/src/renderer/dom/DomRendererRowFactory.ts](https://github.com/xtermjs/xterm.js/blob/160b4a7d669b6c527fec1bc40a18ae79db7d19de/src/renderer/dom/DomRendererRowFactory.ts#L82-L85)
> 
> Lines 82 to 85 in [160b4a7](/xtermjs/xterm.js/commit/160b4a7d669b6c527fec1bc40a18ae79db7d19de)
> 
>  // Convert the FG color to the bold variant 
>  if (fg < 8) { 
>    fg += 8; 
>  }

ping @Tyriar, any pointers on why fg is already offsetted by 8? That block doesn't seem to run at all.

**Comment by Tyriar** [comment]
The `fg += 8;` is what needs to happen only if the `drawBoldTextInBrightColor` is true, values 0-7 are the standard colors, 8-15 are the bright colors.

> this doesn't seem to work properly, I am invoking bash from cmd:

Maybe it's to do with the font you're using? 😕

**Comment by leomoty** [comment]
@Tyriar, I understood clearly what you meant, but from my testing it is already 9, before reaching the portion of the code which you outlined.

Regarding the font, it should be the default. I'll try to take another look.
