### ISSUE TITLE
Text vertical alignment is off in Firefox with Canvas renderer

### ISSUE THREAD

**Issue by astefanutti** [xtermjs/xterm.js#1774]
Using the Canvas renderer, text vertical alignement is above the baseline in Firefox, e.g.:

<img width="1058" alt="screenshot 2018-10-31 at 12 47 40" src="https://user-images.githubusercontent.com/366207/47786171-364a0700-dd0b-11e8-995a-a8de116041f7.png">

While it displays correctly with Chrome and Safari:

<img width="1092" alt="screenshot 2018-10-31 at 12 48 47" src="https://user-images.githubusercontent.com/366207/47786205-55489900-dd0b-11e8-81f2-f0806b3ad747.png">

The screenshots are taken with Xterm.js instantiated here: https://github.com/astefanutti/kubebox/blob/0de0294ca0fd5130e50cc636b6972a97b910bdc2/docs/index.html#L162 

## Details
- Browser and browser version: Firefox 52.9.0 (64-bit)
- OS version: Mac OS X
- xterm.js version: 3.8.0

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/1055
