### ISSUE TITLE
Copy large text into xterm.js didn't response in real time

### ISSUE THREAD

**Issue by haosdent** [xtermjs/xterm.js#1776]
## Details
- Browser and browser version: Chrome 70.0.3538.77
- OS version: MacOS 10.11.6 (15G1611)
- xterm.js version: 3.8.0

### Steps to reproduce

1. I open the vim in xterm.js and paste a large text (10000 lines) into the terminal. However, the terminal only response me when all these inputs are pasted.

```
1
2
3
...
10000
```

2. However, if I paste it in the terminal of VSCode, it responses in real time. Is there any configuration used in VSCode? I try to search this in the repo of VSCode, don't find any clues so far.

**Comment by jerch** [comment]
@haosdent Just to make we are talking about the same scenarios - you c&p the same large text in vim running as slave program at the pty either in the demo app or the integrated terminal of vscode - and see this difference?

**Comment by haosdent** [comment]
yep, in demo app. it stucks like my app. in vscode, it show in real time.

**Comment by jerch** [comment]
node-pty has an electron demo app with xterm.js - can you try it there? If this also shows more "real time" behavior it is likely related to the way, the underlying pty stream is integrated into the app. In electron it is coupled directly to the pty stream events, while the xterm.js browser demo has to go over a websocket connection with additional buffers and such.

**Comment by haosdent** [comment]
ohoh, sry. I think you said xterm.js demo in web browser before. Yep node-pty app is real time.

**Comment by haosdent** [comment]
let me close this ticket.
