### ISSUE TITLE
npm install throw error

### ISSUE THREAD

**Issue by ofirrifo** [xtermjs/xterm.js#1777]
I just clone the xterm.js project and run the npm install which  throw error 
`gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/.nvm/versions/node/v9.7.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/.nvm/versions/node/v9.7.1/bin/node" "/.nvm/versions/node/v9.7.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /dev/test/xterm.js/node_modules/node-pty
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN @fimbul/ymir@0.15.0 requires a peer of tsutils@>2.29.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.7.6 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-11-04T18_58_56_997Z-debug.log
`

## Details
- Browser and browser version: 
- OS version: mackOs Mojave
- xterm.js version: 

### Steps to reproduce
git clone git@github.com:xtermjs/xterm.js.git
cd xterm.js
npm install

**Comment by jerch** [comment]
@ofirrifo Do you have Xcode and/or the cmdline build tools installed? If so, this is either an upstream bug of node-pty or node-gyp (xterm.js itself does not need native stuff). Please check if other node-gyp based modules work and make an upstream bug report.

**Comment by ofirrifo** [comment]
I don't have Xcode I have terminal command line
Should I install the Xcode ?
BTW what is the gyp

**Comment by jerch** [comment]
See https://github.com/nodejs/node-gyp for install instructions and further info.

Closing issue since its not xterm.js related.
