### ISSUE TITLE
Better handling of fullwidth chars

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1779]
Currently non of the cell content insert/delete/replace methods handle previously added fullwidth chars at the position where the action takes place. All of those can break "fullwidth char cell pairs" by either cutting the left or the right part or even move the cells apart (insert).

Possible solution: Whenever a cell gets modified by any of the actions, we would have to check whether the cell is part of a fullwidth char and clear the other cell.

Affected by this:
- `InputHandler.eraseInLine`
- `InputHandler.eraseInDisplay`
- `InputHandler.deleteChars`
- `InputHandler.insertChars`
- `InputHandler.eraseChars`
- `InputHandler.print` (only after cursor jumps, normal input flow already handles this)

Might be easier to fix on buffer line level, since all above fall back to 3 methods - `insertCells`, `deleteCells` and `replaceCells`.

To avoid fixing this several times - blocked until we are settled with the buffer line implementation.

**Comment by skprabhanjan** [comment]
@jerch , is this one good for me to work on ?

**Comment by jerch** [comment]
We have a concrete issue with that in #2592. Trying to schedule this for next release.
