### ISSUE TITLE
How to implement in Angular 7

### ISSUE THREAD

**Issue by Nemtecl** [xtermjs/xterm.js#1786]
Hello,
I'm trying to implements xterm.js on my angular app.
I created an xterm component
Here is the xterm.component.ts file : 

```ts
import { Component, OnInit } from '@angular/core';
import { Terminal } from "xterm";

@Component({
  selector: 'app-xterm',
  templateUrl: './xterm.component.html',
  styleUrls: ['./xterm.component.css'],
})
export class XtermComponent implements OnInit {
  public term: Terminal;
  container: HTMLElement;

  constructor() { }

  ngOnInit() {
    this.term = new Terminal();
    this.container = document.getElementById('terminal');
    this.term.open(this.container);
    this.term.writeln('Welcome to xterm.js');
  }
}
```

And the xterm.component.html
`<div id="terminal"></div>`

It display badly, i don't know why.. Can someone help me pls :)?

**Comment by jerch** [comment]
@Nemtecl Please use platforms like stackoverflow for usage/integration related questions. We dont provide integration examples beside a plain browser example (see demo folder) as it would introduce quite high maintenance workload.
