### ISSUE TITLE
Prompt no longer wraps correctly

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#179]
Filling the prompt line no longer wraps like it used to:

![image](https://cloud.githubusercontent.com/assets/2193314/16809562/9fa54100-48d5-11e6-9b5f-c265879a206e.png)

Before:

![image](https://cloud.githubusercontent.com/assets/2193314/16809596/be1b3ffe-48d5-11e6-977e-af2ea1875c23.png)

**Comment by parisk** [comment]
Just checked out 637c2eae434be539a31ce222c1d53ce22a525256 and this is still the behavior. Do you have any clue of where could this got broken?

**Comment by Tyriar** [comment]
Nothing I can think of off the top of my head.

**Comment by githistory** [comment]
I can confirm I'm seeing the same thing. Quite confusing.

**Comment by githistory** [comment]
I tested previous version way back to 0.3 all showing the same problem.

**Comment by githistory** [comment]
Hint: check on \r returned by server.

**Comment by githistory** [comment]
Looks like it's not a problem with xterm but with how \r is handled. I now do

```
stream.on 'data', (data)-> socket.emit 'data', data.toString('utf-8').replace(/\r$/g, '\r\n')
```

on server side which works great.

Notice the `$` in the regex which keeps `\r\n`s intact.

**Comment by githistory** [comment]
Turns out a better approach might be to configure the underlying tty exposed by ssh2. I'm setting it to unlimited number of columns for the moment. Works well until xtermjs itself has to wrap, after which when you backspace, xtermjs won't get back to previous line because ssh2 won't tell it to by sending relevant character. So I think xtermjs shouldn't wrap line by itself until told to.

**Comment by parisk** [comment]
Not sure if this is an xterm.js issue. Works fine at www.sourcelair.com and on the demo using the latest version.

Could be an issue of the underlying tty?

**Comment by githistory** [comment]
Could very much be the case I suppose. I found ssh2's confusing at some points and incomplete.

**Comment by kevinwon1985** [comment]
@parisk start the demo on latest version. and open chrome developer tools. and run  `term.write('aaa\rzzz')` in console. and you will see the problem.

**Comment by adamjimenez** [comment]
I noticed this started happening as well. Seems to be to do with the handling of single `\r`. My fix is to filter them client side before sending to the terminal e.g.
`data = data.replace(/\r(?!\n)/g, '\r\n');`

**Comment by Tyriar** [comment]
I'm going to close this off as I believe we're acting as expected. The problem is the shell is only sending `\r` (move cursor x to start of line) and not `\r\n` (move cursor x to start of line, then move to next line).
