### ISSUE TITLE
Change terminal colors

### ISSUE THREAD

**Issue by CreatorVilius** [xtermjs/xterm.js#1797]
How do I change terminal colors?

For example, I want to change red to x, blue to y, green to z, yellow to w, etc.

How do I do that?

**Comment by jerch** [comment]
See https://xtermjs.org/docs/api/terminal/interfaces/itheme/

**Comment by jerch** [comment]
@CreatorVilius Please use platforms like stackoverflow for usage related question. The github issues are meant for bugs or feature requests.
