### ISSUE TITLE
xterm linebreak doesn't go back to position 0 in new line(linebreak is same as form feed character).

### ISSUE THREAD

**Issue by CreatorVilius** [xtermjs/xterm.js#1798]
## Details
- Browser and browser version:  Electron 3.0.3(I don't know the version of chromium)
- OS version: Windows 10 64-bit
- xterm.js version: 3.8.0

### Steps to reproduce

1. Create terminal
2. Create function like this:
```js
term.write('123\n123')
// or:
term.write('123')
term.write('\n')
term.write('123')
// both work same.
```

### Screenshot

![capture](https://user-images.githubusercontent.com/31628630/48966394-94939e00-efc8-11e8-8a8a-9a71c0eb9593.PNG)

**Comment by jerch** [comment]
You are missing '\r' aka CR or Carriage Return, which moves the cursor to the beginning of a line. '\n' by default just moves the cursor one line down. Question is - why is '\r' missing here? I guess you are not using a pseudoterminal (pty) in between which by default converts '\n' to '\r\n'. For this particular case the terminal has an option `convertEol`, see https://github.com/xtermjs/xterm.js/blob/929d722e0e691d6c7187849d01acbbe95a517475/typings/xterm.d.ts#L44
Note that xterm.js heavily relies on pty functionality, it is possible to run it without a pty but for more complicated stuff you will have to emulate a pty.

**Comment by CreatorVilius** [comment]
Yeah, I noticed that I need `\r` before your answer. Thanks anyways.
