### ISSUE TITLE
search addon doesn't work well with chinese

### ISSUE THREAD

**Issue by zjjEcho** [xtermjs/xterm.js#1801]
I found some related issues, like this [emoji issue](https://github.com/xtermjs/xterm.js/issues/1103)
But it doesn't seem to solve my problem.

## Details
- Browser and browser version:  chrome(52.0.2743.82  64-bit)
- OS version: Ubuntu 16.04 LTS
- xterm.js version:  3.8.0

### Steps to reproduce

1. generate test content with some chinese in it 
2. search some content，like this
![2](https://user-images.githubusercontent.com/5327847/49000178-be4cf080-f193-11e8-89ad-d8c849e331bc.jpg)

if there's no chinese before the search content, search addon works fine, like this
![1](https://user-images.githubusercontent.com/5327847/49000245-eb010800-f193-11e8-902a-173174f48c15.jpg)

**Comment by jerch** [comment]
This is prolly related to #1686.
