### ISSUE TITLE
Releases includes source code but should include compiled xterm.js and xterm.css

### ISSUE THREAD

**Issue by nojvek** [xtermjs/xterm.js#1802]
### Steps to reproduce

https://github.com/xtermjs/xterm.js/releases

It seems this page just bundles up the source code but the compiled assets in lib are not available. The source code is already available in zip format via `Clone or Download` functionality of github so it seems somewhat redundant. 

I would expect the release includes the compiled assets i.e xterm.js and xterm.css that the README.md talks about.

**Comment by Tyriar** [comment]
We don't attach the compiled assets to releases, it's just the default that GitHub gives us for free. Building from source and npm are the only way to get the compiled assets https://github.com/xtermjs/xterm.js#getting-started
