### ISSUE TITLE
Allow hooking or disabling paste events

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#1803]
I'm currently handling paste myself, but it seems that it's impossible to disable xterm's internal paste handlers. The attached event handlers are irremovable, and pasteHandler isn't exported.

Could you please add an option to disable default paste handlers, or an access point to override its behaviour?

**Comment by Tyriar** [comment]
Can you listen for paste using this API and handle it on your end that way?

https://github.com/xtermjs/xterm.js/blob/b5f1c3384ab8af6bd770cefdaa8274ee3d42e397/typings/xterm.d.ts#L473-L482

This is how VS Code does it.

**Comment by Eugeny** [comment]
Haven't considered this! Would `preventDefault()` here prevent the browser's `paste` event which you're listening to for `pasteHandler` though?

**Comment by Tyriar** [comment]
@Eugeny I think so, in vscode I believe only "vscode keybindings" can trigger pastes and they end up firing this to do the actual paste:

https://github.com/Microsoft/vscode/blob/0d375bf5fc3b34144fde240626603c7f0b2cfc55/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L631-L634

**Comment by Eugeny** [comment]
Can confirm this works.
