### ISSUE TITLE
Why does font spacing increase when I set fontFamily?

### ISSUE THREAD

**Issue by Williamlook** [xtermjs/xterm.js#1814]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. 
2.

**Comment by Williamlook** [comment]
![image](https://user-images.githubusercontent.com/24517443/49566854-14295180-f967-11e8-8354-648d1757f7c9.png)

**Comment by Williamlook** [comment]
set fontFamily Arial.
![image](https://user-images.githubusercontent.com/24517443/49566922-39b65b00-f967-11e8-9218-aa497c5a55ce.png)

**Comment by Williamlook** [comment]
this is right!
![image](https://user-images.githubusercontent.com/24517443/49566966-5ce10a80-f967-11e8-9ba6-425bd8270ab9.png)

**Comment by Williamlook** [comment]
I don't lick letterSpacing,
![image](https://user-images.githubusercontent.com/24517443/49567013-75512500-f967-11e8-8f83-c1acc4da9fbe.png)

**Comment by Tyriar** [comment]
Arial won't look good as it's not a monospace font, the maximum width of a char is guessed based on "W" I think, and that is used for each cell.
