### ISSUE TITLE
CompositionHelper bug  ev.keyCode === 229  can not work in IOS (IPAD)

### ISSUE THREAD

**Issue by QylinFly** [xtermjs/xterm.js#1815]
CompositionHelper bug  ev.keyCode === 229  can not work in IOS (IPAD)

**Comment by Tyriar** [comment]
Can you give some more context?

**Comment by QylinFly** [comment]
1. Enter in the iPad, adjust the iPad soft keyboard
2. Switch the input language to non-English, such as Chinese
3. Press nihao and select ‘你好’, this time the terminal shows nihao你好.

thx

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/1101
