### ISSUE TITLE
Make scroll-to-bottom on input behaviour configurable

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#1824]
xterm will unconditionally scroll to bottom on user input: https://github.com/xtermjs/xterm.js/blob/master/src/Terminal.ts#L1518

It'd be handy if this could be programmatically disabled.

**Comment by Tyriar** [comment]
@Eugeny are you sure that's the right fix for https://github.com/Eugeny/terminus/issues/543? This particular case in VS Code is handled by this option which let's you force normal selection (not apply tmux selection) and copy that way:

https://github.com/xtermjs/xterm.js/blob/b5f1c3384ab8af6bd770cefdaa8274ee3d42e397/typings/xterm.d.ts#L150-L157

**Comment by Eugeny** [comment]
Judging by 

>But with Terminus, when you press space, it doesn't let you enter select mode. Instead, it jumps you to the bottom of the tmux window.

I'd say that's the case

**Comment by Tyriar** [comment]
@Eugeny but tmux doesn't have access to the scrollback, it maintains it's own scrollback buffer which is why this is confusing me. If you were using tmux's copy mechanism, you must be at the bottom of the (xterm.js) viewport?

**Comment by Tyriar** [comment]
After more discussion in https://github.com/Eugeny/terminus/issues/1578, it's not to do with tmux apparently, people just want the option to disable it so accidentally hitting a key doesn't scroll.

Proposal for new option:

```ts
scrollOnInput?: boolean; // default true
```

**Comment by jerch** [comment]
@Tyriar Not sure how this is currently coupled to input - is the scrolling triggered by keyboard input or by pty output (thus `term.write` input)? Imho most other emulator couple this only to latter one like xterm with its `Scroll to Bottom on TTY output` setting.

**Comment by Tyriar** [comment]
@jerch :+1: the `Terminal` options should probably override the DECSET modes though?

```
  scrollOnWrite?: boolean;    // default undefined, respect DECSET 1010
  scrollOnKeypress?: boolean; // default true, override DECSET 1011
```

**Comment by jerch** [comment]
@Tyriar xterm seems to allow to change that by apps on the fly. Imho for those things the user should always be in control - I agree with you.

**Comment by Tyriar** [comment]
> Another way to deal with it and have DECSET support would be a 3-state option

This is what I was suggesting, we might be over thinking it though and adding a thing no one would use? It's similar to the cursor style sequence that I added which doesn't have a 3 state thing, instead the sequence updates the option and that's the source of truth.

**Comment by jerch** [comment]
Well I currently lean towards having the options only, no DECSET at all for this. Would be straight forward to implement. Imho application side should be able to alter those settings (thus DECSET 1010/1011 are ignored like now). I really dont get why these settings have DECSET modes at all (maybe I just dont see the valid use cases).

**Comment by killjoy2013** [comment]
I'm using xterm in Reactjs and just upgade to 4.8.1. My app constantly writing long SSH output chunks to terminal. Default behaviour is to scroll to bottom whenewer a new text chunk is written. My app's user is supposed to activate / deactivate this behaviour. i.e, he'll freeze the terminal to prevent this scroll to bottom thing as he wishes.   Couldn't find a way. Is it possible to switch **scrollTtyOutput** behaviour in the app?
Thanx

**Comment by Tyriar** [comment]
Added in https://github.com/xtermjs/xterm.js/pull/4289

**Comment by JasonXJ** [comment]
Hi Tyriar, I wonder whether we want to keep this issue open as the other option "scrollOnWrite" still haven't been implemented?

**Comment by JasonXJ** [comment]
Personally, I don't use it. But in the older version of our app which supports it, I can see that ~1% of users use it.

Another thing is that it is not hard to implement "scroll on write" outside of xterm.js --- we just need to subscrube to `onWriteParsed()` event and then call `scrollToBottom()`. It might still be nicer for xterm.js to support it directly though.

I will leave the decision to you.

**Comment by Tyriar** [comment]
Since the usage should be low and it's trivial to implement by the embedder I think we can leave this out. Key press on the other hand was enabled by default so the embedder didn't have a choice.

**Comment by CaledoniaProject** [comment]
This is still not implemented in xterm? It's quite a common feature in other desktop terminals.
