### ISSUE TITLE
Invalid unicode characters for command 'pstree'

### ISSUE THREAD

**Issue by Displee** [xtermjs/xterm.js#1835]
Invalid unicode characters are being shown when using the 'pstree' command through SSH on a Linux machine:

https://i.imgur.com/3FMFwhO.png

This is how it has to be:
https://i.imgur.com/r3DuKLB.png

The xterm I'm using atm is:
https://cdnjs.cloudflare.com/ajax/libs/xterm/3.8.0/xterm.js
https://cdnjs.cloudflare.com/ajax/libs/xterm/3.8.0/xterm.css

**Comment by jerch** [comment]
This is most likely a problem of your locale settings. Please post the output of `locale` for both machines and try running `LANG=C pstree`.

**Comment by Displee** [comment]
Using LANG=C worked, it looks way better now:
https://i.imgur.com/ppzTaxl.png

The locale of my Linux server:
`LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

My own machine where I'm hosting my webserver is a windows PC.
So I can't really run the locale command on it.

**Comment by jerch** [comment]
@Displee: The native xterm will typically use your system locales.

xterm.js currently does not depend on a particular locale setting, still its important to use some utf8 encoding, as the terminal can only handle unicode. Ancient local 8bit encodings will not work with xterm.js.

**Comment by Displee** [comment]
Is it possible to override the native xterm locale?

Or do you know another solution to this?

**Comment by jerch** [comment]
Well you can spawn the pty with lang being reset, just provide `{LANG: 'C'}` in the env given to `pty.spawn` (if you use node-pty).

**Comment by Tyriar** [comment]
Looks like this is purely an environment issue more related to the pty.
