### ISSUE TITLE
On certain fonts, font sizes, and line heights, xterm cuts off tops of characters

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#1844]
## Details
- Browser and browser version: Chrome latest
- OS version: OSX
- xterm.js version: 3.9.1 

### Steps to reproduce

Seems like you have to use certain font-size and line-height combos, but here's a codepen to illustrate: https://codepen.io/akanet/pen/KbMwaZ. You can see that as the characters are deleted, tiny slivers of them are left:
![screenshot 2018-12-18 18 27 11](https://user-images.githubusercontent.com/613320/50195109-96fcc580-02f2-11e9-921c-dee4d5e7c090.png)

I *think* this just started in 3.9.0.

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/1138
