### ISSUE TITLE
Only reflow to the top of the viewport

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1869]
This is a follow up for reflow https://github.com/xtermjs/xterm.js/pull/1864

The idea is to instead of reflowing the whole buffer every time resize is called, to reflow only up to the top of the viewport and keep track of where the reflow has occurred up to with the `Buffer`'s state.

Something to consider here is what happens with things like the search addon which need to search the whole buffer. Perhaps search should trigger a full reflow before hand or any call to `BufferLine.translateToString` should ensure that up to that line has been reflowed?

**Comment by mofux** [comment]
I'm not a big fan of such an approach as it results in leaving the buffer in an inconsistent state. IMO if we want such an optimization, we should keep the buffer as pure as possible (without reflow) and add a view model on top that does the reflow + optimizations.

**Comment by Tyriar** [comment]
@mofux it's an inconsistent state that the buffer knows about though, just like if we took the view model approach (which I tried initially and struggled to get working).

I can imagine something like this might work whenever a row is accessed:

```ts
private _reflowTop: number;

public get(y: number): ... {
  this._ensureReflowed(y);
  ...
}

private _ensureReflowed(y): void {
  if (y >= this._reflowTop) {
    return;
  }
  this._reflow(y);
  this._reflowTop = y;
}
```

**Comment by Tyriar** [comment]
Doesn't seem worth the effort as reflow is quite fast already
