### ISSUE TITLE
isWrapped does not get lifted for longish bash commands

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1882]
Repro with reflow PR in the demo:

- input some longish multiline command, e.g. `echo "Lorem ipsum....."`, press enter
- use arrow up to see the command again, dont press enter
- use arrow down to get back to clean prompt
- input `ls`, press enter
- shrink/enlarge viewport width

![grafik](https://user-images.githubusercontent.com/6193135/50718885-ad49a600-1094-11e9-9bd4-f28ddd38fde2.png)

Above the first 3 lines of the `ls` output wrongly reflow as they belong to one wrapped line.

Note this is not an issue of the reflow PR, the PR just makes the problem obvious. It seems we currently do not lift the `isWrapped` flag for `eraseChar` which happens to be send by libreadline when navigating through bash comands with arrow keys.

**Comment by egmontkob** [comment]
Sounds similar to (perhaps the same as) former [VTE 780011](https://bugzilla.gnome.org/show_bug.cgi?id=780011) :-)

**Comment by Tyriar** [comment]
Just tested, this still happens.

**Comment by jerch** [comment]
@Tyriar Yeah, the buggy code is still there...
