### ISSUE TITLE
Copying HTML-formatted output

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#1883]
Please consider adding an API to copy terminal contents as a HTML string.

**Comment by Tyriar** [comment]
@Eugeny does switching to the DOM renderer and copying the inner HTML of `Terminal.element` work?

**Comment by Eugeny** [comment]
It should, but with the webgl renderer coming up, it might make sense to have a frontend-independent API for that. What do you think?

**Comment by jerch** [comment]
I stumbled over this myself the other day when I tried to copy over a terminal page into a rich text editor (libreoffice). I kinda expected it to preserve the text attributes and the font (at least as monospaced), but it stripped all for any renderer.

**Comment by Tyriar** [comment]
When we added this to VS Code the feature really annoyed me and many other users, the reason being it replaced ctrl+c and almost always personally I was non-formatted text. While the copy action does copy both text, it will always paste the rich text one into editors that support it.

Upstream issue: https://github.com/Microsoft/vscode/issues/20813

**Comment by PerBothner** [comment]
To be able to detach a terminal session, you need to be able to save (serialize) the terminal state in some fashion, and then restore it later.  DomTerm saves the output as HTML, slightly cleaned up, along with JSON for other state.  On a later attach, it re-creates the DOM (using `innerHtml`), followed by some re-initialization.

It is not sure that that HTML is the best serialization format for xterm.js's output state, but it does have some advantages.

**Comment by Eugeny** [comment]
@perbothner it's not about serialization, it's about getting the content with the formatting included

**Comment by PerBothner** [comment]
@Eugeny: _"it's not about serialization, it's about getting the content with the formatting included"_

Of course. My point is that being able convert part or the whole the output buffer to HTML, could *also* be useful for serialization, and it might be useful to keep use-case in mind.

**Comment by starpit** [comment]
fwiw, copying the innerHTML from the DomRenderer view does not work when the content is taller than the viewport.

**Comment by XiaocongDong** [comment]
Is there any way to get all of the content of the terminal as a plain text?

**Comment by jerch** [comment]
@XiaocongDong Plain text is already possible via API with `term.buffer.getLine(0).translateToString(true)` (grabs first line in buffer right trimmed). For all lines iterate up to `term.buffer.length`.

**Comment by XiaocongDong** [comment]
> @XiaocongDong Plain text is already possible via API with `term.buffer.getLine(0).translateToString(true)` (grabs first line in buffer right trimmed). For all lines iterate up to `term.buffer.length`.

Thanks jerch, another question on this term.buffer. Does this buffer have a limit? What happen if this buffer goes too large. Will some of the lines be removed? Thanks.

**Comment by jerch** [comment]
@XiaocongDong The buffer is a circular buffer with a max size of `scrollback` + `rows`. Writes that require new lines beyond that limit recycle top lines (FIFO) and re-append them at the bottom with the new content.  This circular behavior is important to know, as it leads to a "moving index" once that limit is hit.

**Comment by XiaocongDong** [comment]
Thanks @jerch , that just answers my question.

**Comment by Tyriar** [comment]
Current plan AFAIK is to enable supporting this eventually via an addon and the buffer API https://github.com/xtermjs/xterm.js/issues/2075

**Comment by jerch** [comment]
@starpit Eww, your [sameStyle function](https://github.com/kubernetes-sigs/kui/blob/755f5c4997fa744ec1cf5758755ada64c734aa86/plugins/plugin-bash-like/src/pty/copy.ts#L39) would have been a one-liner, if we would not try so hard to hide the internal buffer layout behind "convenience" (in fact creating inconvenience and a runtime penalty here) :blush:

**Comment by starpit** [comment]
lol, yeah that was painful to write.

**Comment by Tyriar** [comment]
@jerch maybe we should just expose the raw fg/bg numbers and add some things to watch out for in the jsdoc

**Comment by jerch** [comment]
@jerch Yeah that would do. As long as the shape of fg/bg as a bit compound gets explained, ppl can use it. It has a small drawback though - if we ever reshape things internally, we'd have to provide those fields explicitly, prolly as getter. But thats not a biggy either.

**Comment by Tyriar** [comment]
Yeah one of the caveats I had in mind was compatibility across xterm.js versions is not guaranteed.

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/3440
