### ISSUE TITLE
Text vertical alignment is off in Chrome 71 with Canvas renderer

### ISSUE THREAD

**Issue by astefanutti** [xtermjs/xterm.js#1892]
Since Chrome 71, text is not positioned correctly, e.g.:

<img width="1078" alt="screenshot 2019-01-11 at 15 52 44" src="https://user-images.githubusercontent.com/366207/51041501-60952c00-15ba-11e9-8c1b-0afe3128b58f.png">

While the exact same content displays correctly using Chrome 69:

<img width="1067" alt="screenshot 2019-01-11 at 15 52 26" src="https://user-images.githubusercontent.com/366207/51041592-84587200-15ba-11e9-8968-6e22b30cfd32.png">

## Details
- Browser and browser version: Chrome 71
- OS version: Mac OS X
- xterm.js version: 3.9.0

It seems similar to #1055 but for happening for Chrome as well now.

**Comment by Tyriar** [comment]
Update to 3.10 https://github.com/xtermjs/xterm.js/pull/1859

**Comment by astefanutti** [comment]
Thanks.
