### ISSUE TITLE
better DCS handling

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#1894]
Testing DECRQSS DCS commands across several emulators leads to weird results:

- done with `echo` at the shell does not spit out any results across all emulators (pretty sure that worked before)
- testing with dumb terminal state in `cat` provokes results in xterm.js but in no other terminal emulator

Several things are weird here. Im pretty sure that during earlier tests `echo` would provoke results of DCS commands to be shown, thats not the case anymore. Needs investigation, seems those commands get supressed now (either by echo, the shell or both). Same for `cat`, but now xterm.js behaves differently than the installed emulators. Not yet tested with a raw terminal.

Does anyone know if there were some patches regarding DCS commands degrading/limiting their usage?

TODO:
- [x] raw terminal tests
- [x] identify pattern whether to show DCS results
- [ ] write test cases for officially supported DCS commands

Update:
Had an error in my escape sequence, with the correct sequence `echo` and `cat` work the same across all emulators I can test. I still keep this issue open as invalid results still behave slightly different across emulators and test cases are still missing.

**Comment by Tyriar** [comment]
@jerch can this one be closed? If it's just the last item in the todo we could create an item just for tests so it's more focused and can get a help wanted label.
