### ISSUE TITLE
Demo doesnt work in Safari on the iPhone OS 10.3.3 and possibly later

### ISSUE THREAD

**Issue by boorishpea** [xtermjs/xterm.js#1902]
In the demo and my own applications, when ever text is written letters are missing, when more text is written other bits reappear appear but still letters of the text are missing.

## Details
- Browser and browser version: Safari 10
- OS version: iPhone 10.3.3 (14G60)
- xterm.js version: 3.8.0

### Steps to reproduce

1. Go to xtermjs.org
2. Look at the demo

### Other
Is this still a problem in the latest version of Safari iPhone? I have a feeling that this is a problem with xtermjs and not the browser.

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/1101

**Comment by boorishpea** [comment]
Are you sure that this is the same issue as the suggested duplicate? I don't think it is.

**Comment by Tyriar** [comment]
@boorishpea we don't support mobile, you're talking about iOS?
