### ISSUE TITLE
Cut not work as expected

### ISSUE THREAD

**Issue by ofirrifo** [xtermjs/xterm.js#1906]
When I select some text inside the terminal and then right click I have some option like cut copy etc...
When I click on the cut it not remove the text from the terminal.  

## Details
- Browser and browser version: Chrome
- OS version: macOS Mojave
- xterm.js version: 3.9.1

### Steps to reproduce

1. select some text from the terminal 
2. mouse right click 
3. select the cut option

expected to remove the selected text

**Comment by Tyriar** [comment]
There's no way to disable it in the context menu AFAIK.
