### ISSUE TITLE
Search breaks after resizing

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1915]
I believe the search addon's line cache isn't being invalidated when a resize occurs, so search will be broken until the TTL period expires.

Repro in https://github.com/Microsoft/vscode/issues/67468

**Comment by lohxx** [comment]
Can i work on this issue?

**Comment by Tyriar** [comment]
@lohxx yes please 🙁

**Comment by thebradbain** [comment]
Hello,

I believe I've found the source of the error and the fix -- upon a terminal 'resize' event we should invalidate the cache similarly to how its done for a 'cursormove' event. https://github.com/xtermjs/xterm.js/blob/ce1c45fb18af8ba7a88ee148e10a76eed070357f/src/addons/search/SearchHelper.ts#L151 

I'll submit a PR if you like!

**Comment by Tyriar** [comment]
@thebradbain that should do it, yes please submit a PR if you can 👍

**Comment by thebradbain** [comment]
I've submitted the PR -- let me know if there's anything I should change regarding it. I can walk you through how to make the bug manifest within the xterm.js demo pre-changes, too, if necessary. 👍
