### ISSUE TITLE
We probably don't need to set font-family on the terminal anymore

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1935]
Since the renderers own how text is drawn I don't think we need this line anymore:

https://github.com/xtermjs/xterm.js/blob/abf6a9fa58704de6f75184f8003fc233751053ce/src/xterm.css#L39

DOM renderer sets family here:

https://github.com/xtermjs/xterm.js/blob/abf6a9fa58704de6f75184f8003fc233751053ce/src/renderer/dom/DomRenderer.ts#L154

Canvas renderer sets family here:

https://github.com/xtermjs/xterm.js/blob/abf6a9fa58704de6f75184f8003fc233751053ce/src/renderer/BaseRenderLayer.ts#L347

**Comment by mofux** [comment]
Good catch. Do you know if the IME popup takes the font family of the input it's triggered on? I think the text area will inherit the parent font family? We also have to make sure that the `charMeasure` is still working correctly.

**Comment by Tyriar** [comment]
Char measure works, but the IME font is different (which never worked right)
