### ISSUE TITLE
combined single buffer

### ISSUE THREAD

**Issue by PerBothner** [xtermjs/xterm.js#1942]
In xterm.js and many other terminal emulators the normal and alternate buffers are completely separate.  When using the alternate buffer, the scrollbar does nothing.

DomTerm does not treat the Normal and Alternate Screen Buffers as separate: It is one big buffer. When the Alternate buffer is active, it is just the lower section of the buffer, and you can scroll through the entire buffer. (A dividing line is displayed just above the Alternate buffer.) Entering Alternate Buffer Mode means setting the Home position to the bottom of the buffer (at a new line below the last line), and scrolling the new Home to the top. Restoring Normal Buffer mode means deleting any lines below the original last line. (This is normally the Alternate Buffer home position, but not if there has been output scrolling in Alternate Buffer.) Then the cursor, home position, etc are restored.

This screenshot shows it in action.  The `mc` command enters Alternate Buffer, which acts just as you'd expect.  However, if you scroll back using the scrollbar you can view the primary buffer.  A double-green line (which is only visible if you've scrolled back) separates the two bufffers.

![buffers](https://user-images.githubusercontent.com/10293361/52748813-5a6ce380-2f9c-11e9-8079-3882ed428a2b.png)

This works very well, and make the scrollbar natural and useful in Alternate Buffer mode. Beyond that, it is a API simplification: One can get rid of the `BufferSet` class. There are other simplifications: For example, the restriction that Markers can only be used in the primary buffer is no longer needed.

**Comment by Tyriar** [comment]
I don't think we want to go in this direction as we want to behave like most terminals. Also the scroll bar in the alt buffer would be confusing in some cases; it's not what people expect and it would conflict with the program taking scroll events.

**Comment by PerBothner** [comment]
Regardless of whether you want to *expose* to the user that it is a single buffer, I still think it would simplify the internals to get rid of the BufferSet class.  I.e. a single Buffer of lines, but when in the alternate buffer you'd have a non-zero minScrollLineIndex field to get the traditional behavior: Rendering and scrolling would then ignore all lines with indexes less than minScrollLineIndex.  To get the DomTerm behavior, minScrollLineIndex would be 0.

(This feature is not high priority, but I would like to have it if/when xterm.js gets enough functionality to replace the terminal engine of DomTerm.  However, I can always create a  fork.)

**Comment by Tyriar** [comment]
@PerBothner separation of the two concepts is better though, no peppering conditions referencing `minScrollLineIndex` everything, just swap the buffer in and out and it just works -> less code, simpler, around the same memory cost.
