### ISSUE TITLE
Remapping of key to F13-F16

### ISSUE THREAD

**Issue by stevereaver** [xtermjs/xterm.js#1945]
So what I want to do is the opposite of what has been asked before with regard to mapping function keys. I support a rather old Terminal application that requires the user to send F13-F16, in other terminal applications we can steal and remap certain keys to send the correct ESC codes. How do I go about doing that in xterm.js. I've had a dig through Terminal.ts and investigated using customKeyEventHandler without any luck. Any assistance is appreciated.

**Comment by Tyriar** [comment]
@stevereaver you were on the right track, you should be able to intercept the key event with attachCustomKeyEventHandler, and then whatever you want to bind to F13-F16 make sure it doesn't go through (return false) and send what you want manually to your backing pty.
