### ISSUE TITLE
unify trim/delete/insert events

### ISSUE THREAD

**Issue by PerBothner** [xtermjs/xterm.js#1946]
I believe various issues would be simplified if we unified `trim`, `delete`, and `insert` events on a Buffer's lines.  Most obviously, a `trim` is just a `delete` where the event `index` is 0.  Similarly, an `insert` can be treated as a `delete` with a negative `amount`.  I believe any code that needs to handle one of these events needs to handle them all - just look at at the code for `Buffer.addMarker`.

Also notice the ElementInsert.put method (in Buffer.ts) in my sixel pull request #1940.

Not sure whether to call the unified event 'delete' or come up with a more neutral name.

I noticed that the selection is discarded when the window is resized.  That is a symptom of not handling these events in a unified manner: The `SelectionManager` watches for `trim` events, but does not handle `delete` or `insert` events.  That should be fixed.

A related issue is that deleteLines/insertLines/eraseInDisplay should perhaps also signal a delete event.  I need something similar so images (sixel and otherwise) can get disposed when appropriate.

There will some compatibility problems. Addons that have `trim` handlers will have to be updated.  It seems possible to kludge it so that old trim handlers are called when the index is 0.

**Comment by Tyriar** [comment]
> I noticed that the selection is discarded when the window is resized. That is a symptom of not handling these events in a unified manner: The SelectionManager watches for trim events, but does not handle delete or insert events. That should be fixed.

I can't think of a way to actually hit this as an end user, please create another issue if you have a repro.

I did hit this when trying to repro though https://github.com/xtermjs/xterm.js/issues/1963
