### ISSUE TITLE
webLinks plugin issue. Wrong behaviour on selection

### ISSUE THREAD

**Issue by vitaliy-codeocean** [xtermjs/xterm.js#1947]
If i will finish selection in the middle of some link and release mouse button, link will be clicked.
So in general im just trying to copy part of the text but opening link in the end :)

## Details
- Browser and browser version: Google Chrome Version 72.0.3626.109
- OS version: macOS 10.14.3
- xterm.js version: 3.11.0

### Steps to reproduce

1. Start to select text
2. Stop when your cursor will be over some link
3. Link is opened

**Comment by Tyriar** [comment]
I guess to prevent this we could make sure not selection change has occurred (or no selection exists?) when a link is about to be activated.
