### ISSUE TITLE
webLinks not interpreted

### ISSUE THREAD

**Issue by ppot** [xtermjs/xterm.js#1954]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

Referencing issue : https://github.com/zeit/hyper/issues/3503
### Steps to reproduce

1. Write `http://example.io`
2. mouse over and the link is not interpreted as valid link you can't click it.

**Comment by Tyriar** [comment]
Code pointer: https://github.com/xtermjs/xterm.js/blob/8ea254bdc798ffcf72cb1b37385af40c747d3fa4/src/addons/webLinks/webLinks.ts#L12
