### ISSUE TITLE
Selection doesn't always redraw when resizing the window (canvas renderer)

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1963]
Repro:

1. Make a selection
2. Resize the window

Sometimes the selection will show, sometimes not.

**Comment by Tyriar** [comment]
Selection is drawn here for the canvas renderer: https://github.com/xtermjs/xterm.js/blob/master/src/renderer/SelectionRenderLayer.ts

**Comment by khoitd1997** [comment]
I will tackle this one
