### ISSUE TITLE
ANSI colors 0-15 are wrong in 256 color mode.

### ISSUE THREAD

**Issue by NickShaffner** [xtermjs/xterm.js#1964]
Sending xtermjs the command to set a black background '<ESC>[48;5;0m'  instead sets a darkish gray.   Other ansi color codes under 16 (in 256 color mode) also seem to be incorrect.  The same code generates correct colors on iTerm2 and Mac terminal.

Digging around in the code, it seems the source of the issue is the DEFAULT_ANSI_COLORS table from ColorManager.ts, which seems very different from the standard I see quoted many other places elsewhere, eg (scroll down to the bottom) https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg

for example, ansi 0 should be #000000 but per the current table ends up #2e3436.  All of the colors are 'closeish' t the standard, but still off.

Is there a reason for this?  I didn't see anything in the git blame discussing it or issues raised about it.  I'm interested in submitting a fix - if this isn't intentional.

`export const DEFAULT_ANSI_COLORS = (() => {
  const colors = [
    // dark:
    fromHex('#2e3436'),
    fromHex('#cc0000'),
    fromHex('#4e9a06'),
    fromHex('#c4a000'),
    fromHex('#3465a4'),
    fromHex('#75507b'),
    fromHex('#06989a'),
    fromHex('#d3d7cf'),
    // bright:
    fromHex('#555753'),
    fromHex('#ef2929'),
    fromHex('#8ae234'),
    fromHex('#fce94f'),
    fromHex('#729fcf'),
    fromHex('#ad7fa8'),
    fromHex('#34e2e2'),
    fromHex('#eeeeec')
  ];`

**Comment by Tyriar** [comment]
The grey is used to give some contrast against the background color, I think the actual issue is that the first 16 colors in 256 are shared when the 256 colors should be fixed and no change based on the theme. PR welcome, I think we want to keep the first 16 colors as they are though, but separate `ansi` from `ansi256` here:

https://github.com/xtermjs/xterm.js/blob/7e1b5cc7e905634a82a9488a4d733e5c13292fe8/src/renderer/ColorManager.ts#L102

**Comment by egmontkob** [comment]
In all the terminal emulators I've seen, the first 16 out of the 256-color palette (foreground: `38:5:0` .. `38:5:15`, background: `48:5:0` .. `48:5:15`) are always the same colors as the legacy 16 (foreground: `30` .. `37` and `90` .. `97`, background: `40` .. `47` and `100` .. `107`). Even the OSC 4 sequence that redefines the palette affects both kinds of escape sequences (if supported at all).

The linked color chart might easily document xterm's default colors. For the additional colors (indices `16` .. `255`) pretty much every terminal emulator reuses these same colors. For the first sixteen (at the bottom of the chart) each terminal emulator goes with its own preference.

I think it would be a source of confusion if the legacy 16 + the newer 256 colors would be two independent sets. There's a reason these terminal emulators are referred to as supporting 256 colors and not 272 colors. Plus it's unclear how OSC 4 would work then.

There's one tiny differene in the handling of `38:5:0` .. `38:5:7` versus `30` .. `37` in some terminal emulators: when combined with `1` (bright/bold), in some terminal emulators the old-fashioned `30` .. `37` values also switch to the brighter counterpart of the color in addition to making them bold, while with the 256-color syntax they only become bold but remain the darker color.

**Comment by Tyriar** [comment]
@egmontkob so would you advocate for us changing the default colors to the standard color set and keeping everything else as is?

**Comment by egmontkob** [comment]
I'd say do whatever you want with the first 16, and follow the existing practice with indices 16-255.

Note however that the linked color chart is probably incorrect, as someone pointed out in a comment if you click on the hardly readable gist link at the bottom of the chart.
