### ISSUE TITLE
Find previous doesn't work for the wrapped portions of lines

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1967]
VS Code: https://github.com/Microsoft/vscode/issues/69249

PR: https://github.com/xtermjs/xterm.js/pull/1866

**Comment by khoitd1997** [comment]
@Tyriar  I want to try tackling this since it can be a really annoying bug, do you have any pointers?

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/1866
