### ISSUE TITLE
Share character atlas between xterm instances

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#1969]
Generating the character atlas takes a considerable amount of time for each new terminal:
![image](https://user-images.githubusercontent.com/161476/54210945-b87be080-44e0-11e9-914f-192599c11b27.png)

Could there be a way to share one atlas between multiple xterm instances (given that font, size, and character measurements are the same)?

**Comment by jerch** [comment]
@Tyriar Any thoughts on this? In theory a terminal could support getting an atlas from outside (per ctor arg or some `setAtlas` thingy), but I am not sure if the we get lifecycle issues with such an approach. Also Im not sure whether to stick with the static atlas at all.

@Eugeny In the meantime you can switch to the dynamic atlas, which does a more clever caching of values when requested and does not have the big initial penalty.

**Comment by Tyriar** [comment]
That's what this code is meant to do:

https://github.com/xtermjs/xterm.js/blob/bc86a61a0ca8c1d87cb77216ef3e2e4c262f3a0f/src/renderer/atlas/CharAtlasCache.ts#L31-L37

Maybe it's not working under some cases?

**Comment by Tyriar** [comment]
It's meant to share the same atlas if the config is the same:

https://github.com/xtermjs/xterm.js/blob/6e196da59cdb363e0483942b149905744607544e/src/renderer/atlas/CharAtlasUtils.ts#L11-L35

https://github.com/xtermjs/xterm.js/blob/bc86a61a0ca8c1d87cb77216ef3e2e4c262f3a0f/src/renderer/atlas/CharAtlasCache.ts#L64-L72

@Eugeny please debug into these areas if you're seeing the issue to identify the problem.

**Comment by Eugeny** [comment]
Works as expected in master.
