### ISSUE TITLE
Renderer._needsFullRefresh is never reset to false

### ISSUE THREAD

**Issue by akosyakov** [xtermjs/xterm.js#1975]
I am debugging https://github.com/theia-ide/theia/issues/3838 and noticed that on first drag [_isPaused](https://github.com/xtermjs/xterm.js/blob/d8b973b12659ff02b0380409d67bb0e58bb0e671/src/renderer/Renderer.ts#L85) set to true, on second `_needsFullRefresh` is also true, so no refresh happens. Afterwards it does not matter what user is doing values of `_isPaused` and `_needsFullRefresh` don't get changed. Is it on purpose or `_needsFullRefresh` should be reset to false in `onIntersectionChange`? Should we call something else to force refresh after reattaching xterm from one parent to another?

**Comment by Tyriar** [comment]
It looks like _needsFullRefresh does need to get reset after the refresh happens (as a full refresh has occurred).

**Comment by Tyriar** [comment]
PR is out to fix it, I don't think this would fix https://github.com/theia-ide/theia/issues/3838 though? The bug seems to be that once a full refresh occurs, every time an unpause happens a full refresh happens, even if it's not needed.

**Comment by akosyakov** [comment]
We just need to upgrade xterm, in our version not most recent intersection observer entry is used. https://github.com/xtermjs/xterm.js/commit/69d3a4667f6d3ade4a89e71be066de0e69d82d16 fixes the issue

**Comment by Tyriar** [comment]
@akosyakov makes sense, and thanks for finding the bug 😃
