### ISSUE TITLE
Viewport scrolling jumps when xterm textarea is focused

### ISSUE THREAD

**Issue by natomato** [xtermjs/xterm.js#1981]
When xterm text area is scrolled above the window viewport, clicking on the textarea will jump halfway up the viewport.

## Details
- Browser and browser version: Chrome Version 73.0.3683.86 (Official Build) (64-bit), and Safari Version 12.0.3 (14606.4.5)
- OS version: macOS 10.14.3
- xterm.js version: 3.12.0

### Steps to reproduce

1. unfocus xterm
2. scroll past xterm until part of text area offscreen
3. focus xterm

Heres an example
![xtermjs-focus-jump](https://user-images.githubusercontent.com/778135/55100959-41b61a00-5080-11e9-98c0-afdce7d6b902.gif)

For what its worth, you can see the same behavior from a different bug also relating to calling focus on a textarea:
https://github.com/facebook/draft-js/issues/14

**Comment by natomato** [comment]
Something is scrolling the focused element to ~center of screen, maybe the browser?
It seems to happen even before the focus event reaches the target.
One way to fix this is to maybe scroll the element just before calling focus to avoid the extra high jump.
```
  //Terminal.ts
  /**
   * Focus the terminal. Delegates focus handling to the terminal's DOM element.
   */
  public focus(): void {
    if (this.textarea) {
      const {top} = this.textarea.getBoundingClientRect();
      const topEdge = window.scrollY;

      if (top < 0) {
        window.scrollTo(0, topEdge + top)
      }
      this.textarea.focus();
    }
  }
```

**Comment by Tyriar** [comment]
Thanks for the report, this is even better 😄 

![image](https://user-images.githubusercontent.com/2193314/55270379-35d27f80-525b-11e9-8185-8b3721f32c70.png)

❤️ TS

**Comment by natomato** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus
I thought about it, but it has limited browser support.
Also seems like scrolling is the correct thing to do, to notify the user where their input is being received, but the current scrolling behavior is too much.

**Comment by natomato** [comment]
I created [a gist for how I am handling the unexpected jump](https://gist.github.com/natomato/05f28f96c48bc51e639d2d45708fb8ba), maybe it will be helpful in creating a good solution.

**Comment by Tyriar** [comment]
@natomato well for Firefox specifically it seems to focus as I would expect, for just the xterm.js element to go into view (not be centered). After that, I'm not sure it's worth a special workaround for just Safari considering Edge will soon be based on Chromium and preventFocus will work?
