### ISSUE TITLE
Font fallback

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#1983]
It would be nice if xterm would allow setting a fallback font chain for characters not present in the main font.

**Comment by Tyriar** [comment]
Can't you set `fontFamily` to `"font1, font2, 'font3 with space'"` to accomplish this?

**Comment by Eugeny** [comment]
Didn't try this yet. Should it also work with the canvas renderer?

**Comment by Tyriar** [comment]
Yes it should, we just pass that over to the canvas:

https://github.com/xtermjs/xterm.js/blob/b05c66b132b02d5f69b95a5081dcbe497deb0bc4/src/renderer/TextRenderLayer.ts#L295

**Comment by grzs** [comment]
I had to add a single-word dummy item to the beginning of the list to make the fallback work properly. The result looks like this:
`fontFamily="dummy,'Source Code Pro','Courier New',monospace"`
