### ISSUE TITLE
Dramatic performance reduction across browsers when applying a single color to all text

### ISSUE THREAD

**Issue by cubiclesoft** [xtermjs/xterm.js#1988]
Emitting a basic escape sequence to alter the foreground color at the beginning of the terminal output causes noticeable lag across all browsers with just 100 lines of output.  Firefox becomes nearly unusable.  Removing the escape sequence restores the prior snappy performance.

## Details
- Browser and browser version: All browsers exhibit the issue but the problem is most noticeable/obvious in Firefox.  Surprisingly, the least amount of performance degradation is in Edge.
- OS version: N/A
- xterm.js version: 3.12.0

### Steps to reproduce

```js
var terminal = new Terminal();
terminal.open(elem);
terminal.fit();  // <-- Don't know if this is important - my terminal displays at 206x27 chars as a result of calling fit().

// Attempt to set the foreground color to something other than blindingly bright white.
// Unfortunately, this bit of output triggers significant performance degradation.
terminal.write('\x1B[38;5;250m');

// Output a mere 100 lines that wrap.
for (var x = 0; x < 100; x++)  terminal.write('abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789\r\n');
```

**Comment by Tyriar** [comment]
This is one of the limitations of the canvas renderer, the webgl renderer (https://github.com/xtermjs/xterm.js/pull/1790) which is in progress fixes this I believe and switching to the DOM renderer would also likely improve perf for this case (though degrade in the other cases).
