### ISSUE TITLE
Backspace event in the demo does not function properly (missing term.x)

### ISSUE THREAD

**Issue by cubiclesoft** [xtermjs/xterm.js#1989]
The backspace event handler in the demo looks at `term.x` to decide whether or not to emit backspace characters.  Unfortunately, `term.x` does not exist, so the backspace key simply fails to work at all.

## Details
- Browser and browser version: N/A
- OS version: N/A
- xterm.js version: N/A

### Steps to reproduce

1.  Visit https://xtermjs.org/
2.  Type some text into the demo.
3.  Press backspace.

### Additional info

At:

https://xtermjs.org/js/demo.js

The backspace key is being detected but compares a non-existent variable against a positive integer (`term.x > 2`), which always evaluates to false.

**Comment by Syleron** [comment]
I also would like some insight on this. Much appreciated.

**Comment by cubiclesoft** [comment]
The value of interest appears to be stored under `term._core.buffer.x`.  However, since it is a "private" variable, it is subject to change.  That's the only way I see to access the current cursor position.

For the purposes of the demo, it might be a viable solution to just directly access the var and add a comment which says something like, "We're only doing this for the demo - accessing _core directly is not recommended."
