### ISSUE TITLE
Terminal.applyAddon(zmodem) not work?

### ISSUE THREAD

**Issue by Bjkb** [xtermjs/xterm.js#1998]
![image](https://user-images.githubusercontent.com/22948950/55550009-c7356c00-5709-11e9-95a9-d6606df269e9.png)

![image](https://user-images.githubusercontent.com/22948950/55549937-a0773580-5709-11e9-8aa8-a1ffeefb6b72.png)

![image](https://user-images.githubusercontent.com/22948950/55549909-8f2e2900-5709-11e9-936f-230c62a579ca.png)

![image](https://user-images.githubusercontent.com/22948950/55549731-25158400-5709-11e9-99e3-14b3cd7cfe41.png)

**Comment by Tyriar** [comment]
You need to import zmodem such that window.Zmodem exists

https://github.com/xtermjs/xterm.js/blob/master/src/addons/zmodem/zmodem.ts#L87

**Comment by NeroSolomon** [comment]
@Bjkb Have you solved it yet?

**Comment by Tyriar** [comment]
We removed the zmodem addon from the core repo since it was essentially unmaintained. Not sure if it's out there yet but this is a good candidate for the community to pick up.
