### ISSUE TITLE
Feature Request: Allow scrolling down another page

### ISSUE THREAD

**Issue by TChristoph** [xtermjs/xterm.js#2001]
I would like users to be able to scroll one page further down so that they can always position the current input line anywhere, up to the top of the screen. This is common practice in almost every code editor or even Windows' cmd/PowerShell:

![image](https://user-images.githubusercontent.com/38782922/55672460-ac92fc80-589b-11e9-9b8f-7193cbe07484.png)

Please notice there is free space under the last command line but the command history is longer than one screen page.

I would prefer a setting that user maximally can scroll one more page, so the input line cannot disappear but be freely positioned on the screen. This is the standard you might be accustomed to by Visual Studio (Code) or others.

**Comment by Tyriar** [comment]
While this is a common feature on Windows I don't think it is anywhere on non-Windows terminals. To run a Windows shell inside xterm.js it has to go through an emulation layer like conpty such that it behaves like a non-Windows terminal. I'm concerned that something like this would complicate the codebase and potentially cause bugs as it's not a typical feature.
