### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by miguelmota** [xtermjs/xterm.js#2016]
Searched around and couldn't find a way to display line numbers in xtermjs.

**Comment by Tyriar** [comment]
Normally line numbers are handled by the program running inside the terminal, we have no plans to add line numbers numbering the rows in the viewport or the scrollback.

**Comment by miguelmota** [comment]
@Tyriar got it, thanks

For those curious, here's one way to get line numbers:

```js
text = text.replace(/(\r\n|\n\r|\n|\r)/g, (match, p1, offset, string) => {
  return `${p1}${`${(lineNumber++)}`.padEnd(4)} `
})

term.write(text)
```

**Comment by levenleven** [comment]
@Tyriar do you mean program should just print line number? But then there's no way to control their styling, right?
