### ISSUE TITLE
insertMode cannot be enabled/disabled in realtime

### ISSUE THREAD

**Issue by p3nt4** [xtermjs/xterm.js#2021]
## Details
- Chrome: Version 73.0.3683.103
- OS version: Windows 10
- xterm.js version: 3.12.0

### Steps to reproduce

1. Create code such as:
 ```
terminal._core.insertMode = true;
terminal.write("TEST");
terminal._core.insertMode = false;

```
4. Notice insertMode has not been enabled

**Comment by Tyriar** [comment]
Same as https://github.com/xtermjs/xterm.js/issues/2022
