### ISSUE TITLE
Customize the color and the background of the searched text

### ISSUE THREAD

**Issue by wangsen1989** [xtermjs/xterm.js#2024]
Now in our demo (the first picture), when the rendererType is canvas, the terminal can highlight the searched text,

can you provide support, set the color of the text to black and set the background of the text to yellow, like the second picture? 
Thank You!
```
```
![image](https://user-images.githubusercontent.com/24807073/56800735-57b92500-684e-11e9-9650-5a0d09f22f73.png)

```
```
![image](https://user-images.githubusercontent.com/24807073/56796378-00fb1d80-6845-11e9-89c4-67262c7b3ce6.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/1653
