### ISSUE TITLE
Ligatures (possibly character joiners in general) broken in 3.13.x

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#2028]
Since 3.13.0-beta1, `xterm-addon-ligatures` produces weird spacing instead of actual joined chars - often in a different location too:

![image](https://user-images.githubusercontent.com/161476/56863216-f4490780-69b3-11e9-88bb-bd51b341723e.png)

vs

![image](https://user-images.githubusercontent.com/161476/56863219-fe6b0600-69b3-11e9-9662-6e70702c878e.png)

`xterm-addon-ligatures`'s joiner implementation still returns correct indexes, so there must be something going on in xterm itself.

**Comment by jerch** [comment]
@Eugeny This is prolly related to the new `CellData` type that comes with true color support. Can you debug it and give us the raw data sent from the pty?

**Comment by Eugeny** [comment]
Here it is:

```
"\u001b[1m\u001b[7m%\u001b[27m\u001b[1m\u001b[0m                                                                                \r \r\u001b]2;~\u0007\u001b]1;~\u0007\r\u001b[0m\u001b[27m\u001b[24m\u001b[J\u001b[39m\u001b[0m\u001b[49m\u001b[40m\u001b[39m eugene@Eugenes-MBP \u001b[44m\u001b[30m\u001b[30m ~ \u001b[49m\u001b[34m\u001b[39m \u001b[K\u001b[?1h\u001b=\u001b[?2004h"
```

**Comment by Eugeny** [comment]
It starts breaking down in simplest outputs actually:

```
"\u001b[?1034hEugenes-MBP:~ eugene$ ->"
```

**Comment by jerch** [comment]
And which one should join? Only the `->` sequence I guess?

**Comment by Eugeny** [comment]
In this case, only `->`.
The font is [Fira Code Regular](https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-Regular.ttf)

**Comment by Eugeny** [comment]
The text segment given to the joiner is ` ->`, and the range returned is `[1, 3]`

**Comment by jerch** [comment]
Hmm weird, cannot repro it, also the returned range seems good to me (I dont have this font installed thus I can only test the returned range in the renderer phase) Which renderer are you using? Imho only the canvas renderer supports the joiner atm.

**Comment by Eugeny** [comment]
I'm using canvas renderer. I know it's not exactly the minimal reproducible example, but you can grab the latest Terminus build (https://github.com/Eugeny/terminus/releases/tag/v1.0.75)

**Comment by jerch** [comment]
@Eugeny With your latest build v1.0.75 the screen stays black if I enable ligature support. Not sure if I am doing it wrong...

**Comment by jerch** [comment]
@Eugeny Found the bug - joined chars are not handled by the atlas, this line needs an additional check for joined chars to enter the unchached path: https://github.com/xtermjs/xterm.js/blob/f4bbfc30f3caed20d1d1e236f2cfbbc87600a0bc/src/renderer/BaseRenderLayer.ts#L264

Can you check if this works after adding a `|| cell.combinedData` clause? Note that this is not yet the real fix, for a real fix we might have to carry forward a joined flag. @Tyriar How does the cache currently deal with combined chars? Are they always drawn uncached? If so we might get away with this simple check against `cell.combinedData`.

**Comment by jerch** [comment]
Just saw that the old implementation without `CellData` used `Infinity` as value for `code` to tell the atlas that it cannot be cached. With `CellData` thats not possible anymore (as it relies on integer conversions under the hood). Thus I replaced `Infinity` with `0xFFFFFF`, but now the atlas thinks that it has a cache value for it.
I see several ways from here to fix it, either:
- explicit cast `0xFFFFFF` to `Infinity` on `cell.getCode()`
- tell the atlas to skip any value of `0xFFFFFF`
- carry an explicit join flag forward to the cached/uncached code
- stick with the `cell.combinedData` test (only works if the atlas never tries to cache combined things)

@Tyriar Any thoughts on this, which way to go?

**Comment by Tyriar** [comment]
Doesn't it just cache ascii?

https://github.com/xtermjs/xterm.js/blob/f4bbfc30f3caed20d1d1e236f2cfbbc87600a0bc/src/renderer/atlas/DynamicCharAtlas.ts#L157-L166

**Comment by jerch** [comment]
@Tyriar Yeah just rechecked - the problem is caused by a simplification I have done in `CellData.setFromCharData` for easier test writing. In fact the `CharData` to `CellData` conversion was meant to be removed from the active code base and only stay in tests, must have overlooked it for the joiner in `TextRenderLayer._forEachCell`.

**Comment by Eugeny** [comment]
@Tyriar let me know when you'll push the next beta to NPM and I'll add it to Terminus
