### ISSUE TITLE
Input color scheme is wrong after detaching or terminating the `screen`

### ISSUE THREAD

**Issue by Alex4386** [xtermjs/xterm.js#2030]
Forwarded from Eugeny/terminus#779

## Details
- Browser and browser version: electron 5.0.0
- OS version: macOS Mojave 10.14.4
- xterm.js version: 3.13.0-beta2

### Steps to reproduce

1. open screen in terminal, (e.g. `screen -S scr`)
2. Detach from screen or Terminate the screen (e.g. Ctrl-A, D or exiting the shell)
3. color scheme in user input section is going strange.

**Comment by Tyriar** [comment]
Something wrong in renderer or parser, probably related to UTF 32 or true color PRs /cc @jerch

**Comment by jerch** [comment]
@Tyriar Cannot repro it atm, for me the color changes work as expected. If this is still an issue, I suspect some missing `AttributeData` update down the road while switching buffers (both buffers maintain separate color/flag settings).

**Comment by Alex4386** [comment]
@jerch will now try to reproduce with a demo which is provided at [xterm.js/demo](https://github.com/xtermjs/xterm.js/tree/master/demo), Thanks for noticing me out.

**Comment by Tyriar** [comment]
Deferring from next release since it's hard to repro and seems pretty low impact

**Comment by risacher** [comment]
I observe this problem also, and note something particularly wierd:  

My app (https://github.com/risacher/ttyx) allows multiple concurrent xterm.js instances, and if you enter and exit screen in one of them, it messes up the colors not only for that terminal - but for other terminals that are open in the same browser tab.  Somehow screen is generating character codes that are changing a color table shared across terminals, which probably shouldn't be happening.

**Comment by jerch** [comment]
@risacher Eww, this sounds like something is injected into one terminal and reused by a second instance. From my knowledge we dont have any globals in the codebase itself.

@Tyriar Any thoughts on this? Do we have hidden static members somewhere (beside methods)?

**Comment by Tyriar** [comment]
@risacher @jerch sounds a lot like https://github.com/xtermjs/xterm.js/issues/2196

**Comment by Tyriar** [comment]
Yep, looks like it happens in 3.14, I reopened https://github.com/xtermjs/xterm.js/issues/2196 for a patch release
