### ISSUE TITLE
Non-ASCII text is displayed with black color

### ISSUE THREAD

**Issue by NDelt** [xtermjs/xterm.js#2031]
## Details
- Browser and browser version: [Terminus](https://github.com/Eugeny/terminus) (It uses xterm for terminal frontend)
- OS version: Windows 10
- xterm.js version:  3.13.0-beta1

### Steps to reproduce
![nonascii](https://user-images.githubusercontent.com/46282492/56913356-69b7f380-6aec-11e9-8022-c4e53eeaab0c.gif)

1. Type non-ASCII(Korean) text on Terminus terminal
2. It is displayed with black color so it is hard to distinguish

**Comment by Eugeny** [comment]
Can confirm - xterm renders them black independently of the current color palette

**Comment by Tyriar** [comment]
This appears to be related to the canvas renderer

**Comment by Tyriar** [comment]
@jerch might have been the cell data changes?

**Comment by jerch** [comment]
The problematic code is: https://github.com/xtermjs/xterm.js/blob/f4bbfc30f3caed20d1d1e236f2cfbbc87600a0bc/src/renderer/BaseRenderLayer.ts#L317-L333

It misses handling of the default colors.
