### ISSUE TITLE
add a text-shadow equivalent

### ISSUE THREAD

**Issue by vaaski** [xtermjs/xterm.js#2041]
Hello,
I've recently stumbled across a VSCode theme called [Synthwave '84](https://github.com/robb0wen/synthwave-vscode) and a fitting [Hyper theme](https://github.com/diogocezar/hyper-synthwave84).
Since VSCode uses a normal DOM structure for the editor it's fairly easy to add a shiny text-shadow glow effect through a CSS loader extension. [I was hoping I could do the same for Hyper](https://github.com/diogocezar/hyper-synthwave84/issues/1), but it uses this canvas based Xterm.js which is limited to simple colors. Would it be possible to achieve a similar effect in Xterm? It's not the most important thing in the world, but [people](https://twitter.com/TaelurAlexis/status/1122912882461532161) [seem](https://twitter.com/Robb0wen/status/1122889845930635264) [more into the](https://twitter.com/Robb0wen/status/1123010466719121413) [glow effect](https://twitter.com/skyetetra/status/1124307624239886336) [than expected](https://twitter.com/panic/status/1123651547924033538).

Here are some sweet images of the theme to convince you.

![image](https://user-images.githubusercontent.com/17879327/57194113-1a861e80-6f43-11e9-88ff-c30d24148070.png)
![image](https://user-images.githubusercontent.com/17879327/57194433-3db2cd00-6f47-11e9-848e-6fa69bf41005.png)

**Comment by Tyriar** [comment]
You can swap to the DOM renderer and then use CSS, I'm sure they have a setting for that. Also eventually https://github.com/xtermjs/xterm.js/issues/2005 will let you do much more advanced things.
