### ISSUE TITLE
FontFamily not properly loaded in the first place

### ISSUE THREAD

**Issue by Azteker** [xtermjs/xterm.js#2058]
I used Roboto Mono and import it from Google font
```
var term = new Terminal(
        {
            cols: cols,
            rows: rows,
            fontFamily: 'Roboto Mono',
            useStyle: true,
            cursorBlink: true
        } ),
```
When the termianl is opened the font-family is not correct.
![image](https://user-images.githubusercontent.com/13081022/57495320-7a056680-7282-11e9-82fa-81d7254a9d80.png)
It is fixed after I resize the terminal
![image](https://user-images.githubusercontent.com/13081022/57495604-d2893380-7283-11e9-8dec-1498304d531f.png)

The problem is gone if I used this font in some other place on the webpage.
## Details
- Browser and browser version: Chrome 
- OS version: Windows 10
- xterm.js version: 3.12.2

### Steps to reproduce

1. 
2.

**Comment by Tyriar** [comment]
https://www.npmjs.com/package/xterm-webfont is the current workaround for this

See also https://github.com/xtermjs/xterm.js/issues/1164
