### ISSUE TITLE
DomRenderer.dimensions.scaledCharWidth is floored

### ISSUE THREAD

**Issue by starpit** [xtermjs/xterm.js#2063]
## Details
- Browser and browser version: any
- OS version: any
- xterm.js version: 3.13

### Steps to reproduce

1. have a client emit some text to the dom (not using xterm)
2. emit the same text to the dom (using xterm)

Expected result: the width of the two elements should be equal
Actual result: the width of the xterm element is always <= the normal dom element

Cause: in DomRenderer.ts, the `scaledCharWidth` attribute is taken as the floor of the measured character width, as follows:

```
this.dimensions.scaledCharWidth = Math.floor(this._terminal.charMeasure.width * window.devicePixelRatio);
```

For example, on macOS with `fontFamily:"SF Mono"` and `fontSize:14px`, the measured character width is 8.66px (rounded to two decimal places); xterm.js instead uses a character width of 8px, due to the `floor` calculation.

As a consequence, xtermjs elements render as width-compressed compared to the natural character spacing of the chosen font.

I assume that there was a reason for the `floor`? I am reporting it here, as it causes poor font rendering for our use case.

**Comment by Tyriar** [comment]
I *think* the only reason that's there is because I forgot to remove it when I pulled the dimensions code over from the canvas renderer which absolutely needs to fiddle with this stuff. If someone wants to help with this one please verify using mixed colored text, emoji and wide CJK glyphs.

**Comment by starpit** [comment]
not sure quite how much this helps, but... with the floor removed:

![Screen Shot 2019-05-10 at 23 31 25](https://user-images.githubusercontent.com/4741620/57564555-c5e80680-737b-11e9-8e0d-5b35014757ab.png)

![image](https://user-images.githubusercontent.com/4741620/57564537-4d814580-737b-11e9-9093-3b58e9a6765e.png)

**Comment by starpit** [comment]
with the floor in place (3.13):

![image](https://user-images.githubusercontent.com/4741620/57564565-f92a9580-737b-11e9-8c4e-bf979373a491.png)
