### ISSUE TITLE
Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by moltar** [xtermjs/xterm.js#2084]
## Details
- Browser and browser version: Chrome latest
- OS version: macOS latest
- xterm.js version: `3.13.0`

### Steps to reproduce

1. attach to an unreachable websocket
2. see console error messages

---

```
attach.js:84 Uncaught TypeError: Cannot read property 'dispose' of undefined
    at detach (attach.js:84)
    at WebSocket.<anonymous> (attach.js:66)
```

I am guessing need to check for undefined-ness here:

https://github.com/xtermjs/xterm.js/blob/9cb6706e2d3252903501655578e8172fb31440a2/src/addons/attach/attach.ts#L123

**Comment by Tyriar** [comment]
Should be fixed now
