### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by apiel** [xtermjs/xterm.js#2087]
The version in your repo 3.13.0 and in npm 3.13.0 are different. This lead to issue, for example I was not able to use `term.loadAddon(new AttachAddon(socket));`. To solve this I add to pull your repo and copy the lib folder from xterms.js to my node_module. It's a bit a problem if your documentation doesn't correspond with the npm package.

Else that super library ;-) Thank for that.

**Comment by Tyriar** [comment]
@apiel you're not meant to be able to use loadAddon in v3.13 as it's coming in 3.14. It should be in the repo or the npm module, see https://github.com/xtermjs/xterm.js/blob/3.13.0/typings/xterm.d.ts

Which documentation gave you the idea it was ready?

**Comment by apiel** [comment]
https://github.com/xtermjs/xterm.js/blob/master/demo/client.ts#L157

**Comment by Tyriar** [comment]
@apiel ah ok, for any API-related stuff you will want to view the repo against the version tag like so: https://github.com/xtermjs/xterm.js/blob/3.13.0/demo/client.ts#L27

`master` is always the absolute latest, and the documentation may differ from the last stable version. We have a beta build that builds from master if you want to give the new addons a try, we're still polishing them up though. `npm i --save xterm@beta`

**Comment by apiel** [comment]
Shouldn't master be the last released version. You could prepare your release in some release branch, it would not bring confusion. Anyhow thanks for the clarification, now I will know where to look ;-)

**Comment by Tyriar** [comment]
The way we work is master is the latest (and continuously deployed to beta releases), stable releases are tagged on of master when they happen and we branch off if we need to do a point release. This works for us. It's mentioned how to view the actual API in GitHub here https://github.com/xtermjs/xterm.js#api

Note that it's also a pretty rare occurrence that the API and docs change like this.

**Comment by apiel** [comment]
By the way, since you are introducing breaking changes to your API, you should update your sermver to major version. Else `yarn upgrade-interactive` will break project without warnings.

**Comment by Tyriar** [comment]
They aren't breaking changes, it's a new API and `applyAddon` still exists.
