### ISSUE TITLE
Scrolling with scrollback

### ISSUE THREAD

**Issue by bugale** [xtermjs/xterm.js#2089]
I couldn't find any escape sequence that would be equivalent of using the scrollbar.
There are ^[T and ^[S but they ignore the scrollback, creating empty lines.
In ANSIPLUS, there are the sequences ^[!S and ^[!T, which are equivalent to using the scrollbar, and it seems fairly easy to implement in the input handlers of xtermjs.
I think such a feature would be very useful.

**Comment by Tyriar** [comment]
I don't think such an escape sequence exists because everything just works on the viewport. There are APIs in xterm.js to scroll though:

https://github.com/xtermjs/xterm.js/blob/3.13.1/typings/xterm.d.ts#L701-L727
