### ISSUE TITLE
Make word border configurable

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#2091]
Currently `SelectionManager._getWordAt` is hardwired to expand selection until the nearest whitespace. Could we have an option to configure what characters are considered to be a part of word?

**Comment by Tyriar** [comment]
Sure we could have a `wordSeparator` option that replaces this:

https://github.com/xtermjs/xterm.js/blob/610c4c9726402591fa783cdece0f1166fa3437a5/src/SelectionManager.ts#L43
