### ISSUE TITLE
How to get x co-ordinate of current cursor position

### ISSUE THREAD

**Issue by pavan142** [xtermjs/xterm.js#2103]

**Comment by Tyriar** [comment]
In the upcoming v3.14.0 you'll get access to this via `Terminal.buffer.cursorX`, it flagged experiemntal and is subject to change, but that one probably won't.

https://github.com/xtermjs/xterm.js/blob/739723fe92886756a9d759981dca008abfcaf021/typings/xterm.d.ts#L938-L942
