### ISSUE TITLE
Allow renderers to register dynamically

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#2104]
I think we should get rid of the **hard-wired** renderer options and introduce a renderer registry in order to allow renderers to ship as standalone addons. Maybe something like this as a public facing api would be sufficient?
```typescript
Terminal.registerRenderer(
  name: string, 
  createRenderer: (terminal: Terminal) => IRenderer
): IDisposable
```

**Comment by Tyriar** [comment]
Is this covered by https://github.com/xtermjs/xterm.js/issues/2005? Here's an example of what a renderer addon would look like (setRenderer will work eventually before open is called)

https://github.com/Tyriar/xterm.js/blob/webgl2/src/renderer/webgl/WebglRendererAddon.ts

**Comment by mofux** [comment]
I don't really like the api story of it, because it isn't clear if the renderer that is finally used is the one specified by the `rendererType` option, or any other renderer that gets forcefully set from within the addon by calling `terminal.setRenderer`. IMO it would be better to register a renderer once, and then use it based on the `rendererType` option. 

Or thinking of it the other way around - if I call `term.setOption('rendererType', 'dom')`, how would I switch back to the `opengl` renderer with the current approach?

**Comment by Tyriar** [comment]
@mofux I was thinking `rendererType` would be removed (in addition to `experimentalCharAtlas`), and the DOM renderer would be the default. So the DOM renderer would be used if `setRenderer` is not called or `setRenderer(null)` is called after a renderer is registered. So this is how you would enable a renderer:

```ts
const t = new Terminal();
t.loadAddon(new WebglRendererAddon());

// or maybe later
const t = new Terminal();
t.loadAddon(new AccessibilityRendererAddon());
```

To switch back to DOM:

```ts
const t = new Terminal();
const renderer = t.loadAddon(new WebglRendererAddon());
renderer.dispose(); // back to DOM
```

I'm not the biggest fan of the static API approach used by `applyAddon` as it makes it harder to test. Plus if we wanted to use the `registerRenderer` exposes a new `rendererType` approach, I don't think we would be able to strongly type `rendererType` anymore as the list of valid values becomes dynamic at runtime.

**Comment by mofux** [comment]
Oh I see, thanks for the clarification, your approach looks good to me 👍 Please feel free to close this issue if you don't need it for any further reference.
