### ISSUE TITLE
xterm.js Support for versions including IE8 and above

### ISSUE THREAD

**Issue by maixiansheng** [xtermjs/xterm.js#2106]
🛑 The issue tracker is not for questions 🛑

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/xtermjs.
I wonder if xterm supports for versions including IE8 and above

**Comment by mofux** [comment]
We currently only support IE11 and higher, see the Browser section in README for more info:
https://github.com/xtermjs/xterm.js#browser-support

We don't plan to support any older browsers.

**Comment by Tyriar** [comment]
Also IE11 support is planned to drop when we release v4 https://github.com/xtermjs/xterm.js/issues/1889
