### ISSUE TITLE
No response for Report Cursor Position command

### ISSUE THREAD

**Issue by seldomU** [xtermjs/xterm.js#2107]
I'm trying to get the terminal's cursor position like this:
```javascript
   term.on("data", console.log );
   term.write(`\u001B[6n`);
```

The data event does not fire. InputHandler's onData event fires, but has no listeners. Should I subscribe to that event as well?
When I send `\u001B[n` (sendDeviceAttributes) instead, the Terminal's data event does fire.
xterm version is 3.13.0

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/blob/739723fe92886756a9d759981dca008abfcaf021/src/InputHandler.ts#L1765-L1770

I think we might be missing hooking up the data event from InputHandler to Terminal:

https://github.com/xtermjs/xterm.js/blob/739723fe92886756a9d759981dca008abfcaf021/src/Terminal.ts#L353-L356

**Comment by Tyriar** [comment]
I need to test but if that is the problem we should do a patch release.
