### ISSUE TITLE
Clickable multi-line links have regressed

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2115]
Upstream issue: https://github.com/microsoft/vscode/issues/61708
Old PR that solved the issue (things have changed a lot in the area though): https://github.com/xtermjs/xterm.js/pull/1769

We should verify the state of the bug before tackling this.

**Comment by kamalesh0406** [comment]
I would like to look into this

**Comment by Tyriar** [comment]
@kamalesh0406 sounds good 👍

**Comment by kamalesh0406** [comment]
<img width="997" alt="Screen Shot 2019-06-24 at 3 40 55 PM" src="https://user-images.githubusercontent.com/29024165/60011023-8f015200-9696-11e9-8374-0922d5d1a352.png">

I think the bug has been resolved.

**Comment by jerch** [comment]
@kamalesh0406 Multiline support in general works yeah, but there are issues with special conditions of chars:
- combining chars/wide chars in the line prior the URL (or any content to be linkified) might offset the underline (both start and end)
- combing chars/wide chars within the linkified content might offset end of underline

**Comment by lramos15** [comment]
![](http://g.recordit.co/bdd1uO4vlD.gif)
Repro steps:
1. Fill terminal
2. clear
3. Execute a program which prints a link longer than the current size of the terminal.

**Comment by Tyriar** [comment]
Seems to be fixed, probably with https://github.com/xtermjs/xterm.js/pull/2530
