### ISSUE TITLE
Error when using rz command 

### ISSUE THREAD

**Issue by fany208** [xtermjs/xterm.js#2119]
## Details
- Browser and browser version: chrome 74.0.3729.157
- OS version: macOS High Sierra 10.13.1
- xterm.js version: 3.13.0

### Steps to reproduce

1.  npm run start-zmodem
2. choose file to upload
![image](https://user-images.githubusercontent.com/3197725/58165879-3fa4bc00-7cbb-11e9-85de-fd35fa76ade8.png)
![image](https://user-images.githubusercontent.com/3197725/58166061-97432780-7cbb-11e9-9b70-35d1d8c9f974.png)

**Comment by Tyriar** [comment]
@FGasper FYI we're planning on removing the zmodem addon as we can't maintain it (see https://github.com/xtermjs/xterm.js/issues/1128#issuecomment-394142177). With v3.14.0 we have the new experimental addon API ready which makes it a lot easier for people to write external addons to xterm.js. These examples are pretty complete: https://github.com/xtermjs/xterm-addon-web-links, https://github.com/xtermjs/xterm-addon-search, https://github.com/xtermjs/xterm-addon-attach

**Comment by FGasper** [comment]
@Tyriar That sounds reasonable.

**Comment by Tyriar** [comment]
Closing off since https://github.com/xtermjs/xterm.js/pull/2164 removes all the old addons
