### ISSUE TITLE
resize() doesn't call setupStops()

### ISSUE THREAD

**Issue by unixwitch** [xtermjs/xterm.js#212]
When the terminal is resized with resize(), and the new size is wider, setupStops() isn't called, which means any tabs past the old width of the terminal will result in broken output.
## Details
- Browser and browser version: Firefox 47.0
- OS version: Fedora 23
- xterm.js version: d2cef6f
### Steps to reproduce
1. Create an 80x24 terminal.
2. Call resize() to change it to 170x24.
3. `printf 'foo bar baz quux foo bar baz quux foo bar baz quux foo bar baz foo bar baz quux foo bar baz quux quux\tbar\n'`

Expected output:

```
foo bar baz quux foo bar baz quux foo bar baz quux foo bar baz foo bar baz quux foo bar baz quux quux   bar
```

Actual output:

```
foo bar baz quux foo bar baz quux foo bar baz quux foo bar baz foo bar baz quux foo bar baz quux quux                                                                    b
ar
```

**Comment by parisk** [comment]
Hi @ftarnell, thanks for reporting. Investigating this.

**Comment by parisk** [comment]
@ftarnell could you please try this using the patch attached at #213 to see if it solves this issue?

https://github.com/sourcelair/xterm.js/pull/213/commits/abeff89f9a5134b1695a599cd89fa3301d6317a5.

**Comment by ftarnell** [comment]
Unfortunately that doesn't fix the problem, it just makes it break in a different way:

![20160804154114-9nrj5e](https://cloud.githubusercontent.com/assets/185952/17408265/6e324322-5a62-11e6-801b-988e2988c278.png)

**Comment by Arvinzhu** [comment]
how to use  resize()  change the  the  terminal   size ?

**Comment by parisk** [comment]
Hi @Arvinzhu you can take a look in the demo code https://github.com/sourcelair/xterm.js/blob/master/demo/main.js#L16.

If your question does not have to do directly though with tackling this issue (**resize() doesn't call setupStops()**), please open up a new issue to continue the discussion 😊 .

**Comment by Tyriar** [comment]
I think this is fixed.
