### ISSUE TITLE
Screen resize deletes characters, no text reflow

### ISSUE THREAD

**Issue by komali2** [xtermjs/xterm.js#2121]
If I resize the screen past characters, those characters vanish. 

![Screenshot from 2019-05-23 14-19-19](https://user-images.githubusercontent.com/8533113/58287458-ed6ca500-7d65-11e9-85e3-7b6b2a7b8e9c.png)
![Screenshot from 2019-05-23 14-19-06](https://user-images.githubusercontent.com/8533113/58287459-ed6ca500-7d65-11e9-8f3f-b5d37d844285.png)
![Screenshot from 2019-05-23 14-18-45](https://user-images.githubusercontent.com/8533113/58287460-ee053b80-7d65-11e9-9c56-c3d637f863fb.png)

My resize code: 

```
Terminal.applyAddon(fit);
    const term = new Terminal(opts);
    term.open(document.getElementById('terminal'));
    fit.fit(term);
   
    term.write(`${wrapAndColor('$','orange')}`);
    window.addEventListener('resize', () => {
      fit.fit(term);
    });

```

I had to do `fit.fit(term)` instead of `term.fit()` because typescript was throwing errors about there being no `fit()` method on `term`. 

## Details
- Browser and browser version:  Chrome 74.0.3729.147 64bit
- OS version: Ubuntu 18.04
- xterm.js version: 3.13.1

### Steps to reproduce

1. Insert text
2. Resize to smaller than where the text is.

**Comment by Tyriar** [comment]
This is by design, the line that the cursor on will never get reflowed, that's up to the shell or whatever is on the other side to handle.
