### ISSUE TITLE
text that is typed in the command window doesnt show up and nothing is executed

### ISSUE THREAD

**Issue by TheLinuxPro** [xtermjs/xterm.js#2129]
i cannot enter text into the command window the text doesnt show up and what i type in isnt executed only the block cursor shows up when i click on the command window but when anything is typed in nothing happens.
## Details
- Browser and browser version: latest version available in ubuntu 18.04 repositories
- OS version: ubuntu 18.04
- xterm.js version: latest version available via npm i xterm

### Steps to reproduce
npm i xterm
copy index.html file in readme
start a server with vscodes liveserver extention
go to localhost:5500
click command window
type in something and it doesnt show up and nothing is executed

**Comment by Tyriar** [comment]
If nothing is happening it means that you haven't hooked up the server portion correctly.

> start a server with vscodes liveserver extention

It sounds like you're just serving the index.html file, but you need to connect to a server that launches the process. See demo/server.js for how that works and try [cloning and running the demo](https://github.com/xtermjs/xterm.js/wiki/Contributing) for an example.
