### ISSUE TITLE
Font rendering issues with ligatures enabled

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#2135]
![image](https://user-images.githubusercontent.com/161476/58410342-4ee88880-8072-11e9-9206-6b95807087d0.png)

Compare font weight for `a` and `a-`.

The font is Fira Code.

**Comment by Eugeny** [comment]
Strangely enough, this only happens with `-`, but not `=`, although both can form a ligature.

**Comment by Tyriar** [comment]
What version of xterm.js? Is this in Terminus?

**Comment by Tyriar** [comment]
Also what rendererType are you using?

**Comment by Eugeny** [comment]
Sorry - it's xterm 3.13.2, with canvas renderer. You should be able to see it live by grabbing the latest Terminus build.

This behaviour seems to be new in the 3.13.x series.

**Comment by jerch** [comment]
Cant repro this either with your latest terminus build. Font weight is right for me (tested with `echo -e '\x1b[1m a= a- =='` and `echo -e '\x1b[0m a= a- =='`).

**Comment by Eugeny** [comment]
This doesn't happen on Windows for me either - only macOS seems to be affected

**Comment by Tyriar** [comment]
I can't get ligatures to work?

<img width="753" alt="Screen Shot 2019-05-29 at 4 37 26 PM" src="https://user-images.githubusercontent.com/2193314/58598197-20b0a780-8230-11e9-89a4-5f7ee64f45e0.png">

<img width="243" alt="Screen Shot 2019-05-29 at 4 37 37 PM" src="https://user-images.githubusercontent.com/2193314/58598193-1abac680-8230-11e9-8b9f-daeef07a794f.png">

**Comment by Eugeny** [comment]
Not even after restarting the app?

**Comment by Tyriar** [comment]
@Eugeny oh that did it. 

Cannot repro 😕 

<img width="321" alt="Screen Shot 2019-05-30 at 8 32 41 AM" src="https://user-images.githubusercontent.com/2193314/58644137-85621580-82b5-11e9-8520-aa769cceed31.png">

**Comment by Eugeny** [comment]
I'm seeing the difference in brightness of `a` in `a=` and `a-` on the bottom line

**Comment by Tyriar** [comment]
Oh I see

**Comment by Tyriar** [comment]
They both seem to be drawing with the same properties. Below logs ctx.font, ctx.fillStyle, ctx.textBaseline, chars, x, y

<img width="609" alt="Screen Shot 2019-05-30 at 9 58 18 AM" src="https://user-images.githubusercontent.com/2193314/58649644-7b461400-82c1-11e9-8e62-aa4906af5a10.png">

**Comment by Eugeny** [comment]
It somewhat looks like the fatter A is just being rendered twice, and the overdraw results in a wider outline where it's antialiased

**Comment by Tyriar** [comment]
Hmm, maybe we are somehow drawing things wrong normally and the char joiner one is doing it right. I've seem comments that regular text rendering is more heavy than it should be 🤔

**Comment by Eugeny** [comment]
Can confirm that this doesn't happen with the webgl renderer (all characters seem to be drawn extra-bold there)

**Comment by Tyriar** [comment]
Closing as won't fix since we want to phase the canvas renderer out in favor of webgl and dom only
