### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2136]
VS Code is experiencing this issue: https://github.com/microsoft/vscode/issues/74183

I'm not sure yet whether this is a problem in VS Code or xterm.js, but I think reverting https://github.com/xtermjs/xterm.js/pull/2123 didn't fix it so we should pull that back in once the real problem is identified.

**Comment by Tyriar** [comment]
Looks like the PR was good as https://github.com/microsoft/vscode-remote-release/issues/467 should definitely contains Math.floor again so we should reinstate https://github.com/xtermjs/xterm.js/pull/2067 for 3.14.0

**Comment by Tyriar** [comment]
Repros in demo by initializing with dom renderer:

```ts
  term = new Terminal({
    windowsMode: isWindows,
    rendererType: "dom"
  } as ITerminalOptions);
```

**Comment by jerch** [comment]
Eww - missing CSS in the ctor? Wonder how that went silently for so long.
