### ISSUE TITLE
Display density changes lead to corrupted characters

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#2137]
When switching between a built-in Retina display and an external normal-density display, some characters will be drawn with incorrect size by the canvas renderer.

Now, I can't confirm whether it's possibly Electron's fault, but I suspect that Chrome would behave the same.

xterm 3.13.2

![image](https://user-images.githubusercontent.com/161476/58464283-b6b3d780-8135-11e9-8355-ead6398c96c5.png)

**Comment by Tyriar** [comment]
Might be rel;ated to ligature problems in https://github.com/xtermjs/xterm.js/issues/2135?

**Comment by Eugeny** [comment]
Might be, but I don't think so. Looks like some chars might be cached in the renderer atlas with a smaller resolution?

**Comment by Tyriar** [comment]
@Eugeny seems to me like the cached parts are `-r`, `-x` and `--`.

**Comment by Eugeny** [comment]
Good point - these are the ones that are incorrectly rendered in #2135

**Comment by Eugeny** [comment]
Weirdly enough, switching to a higher density makes these characters larger, and switching to a smaller density display makes them smaller.

**Comment by Tyriar** [comment]
The APIs that https://github.com/xtermjs/xterm-addon-ligatures use probably just need some updating for the recent updates to renderers.

**Comment by jerch** [comment]
Cannot repro this and the other issue #2135 (on Ubuntu though, with Fira Mono and ligatures enabled).

**Comment by Eugeny** [comment]
Still reliably reproducible in master: 
![image](https://user-images.githubusercontent.com/161476/60096377-0dbac580-9751-11e9-920c-af5c59710b74.png)

The font doesn't get corrupted immediately after the DPI switch, but rather after font-family and font-size are updated (re-set to the same values) in xterm.

**Comment by yuezk** [comment]
@jerch @Tyriar 
I came from the VS Code issue https://github.com/microsoft/vscode/issues/94656
It can be reliably reproduced reliably on my macOS 10.15.3 with VS Code 1.44.2 and enabled the `experimentalWebgl` renderer type.

![image](https://user-images.githubusercontent.com/3297602/79710051-623dbb80-82f6-11ea-9285-815e5fc90e92.png)


I have two displays show below
![image](https://user-images.githubusercontent.com/3297602/79709339-81d3e480-82f4-11ea-9145-20f01a4867d4.png)

1. Keep the external display connected.
2. Open the `Terminal` if it hasn't been.
2. Move the VS Code to the external display if it hasn't been.
![image](https://user-images.githubusercontent.com/3297602/79709627-47b71280-82f5-11ea-8a73-7952f36898ad.png)
4. Disconnect the external display.
5. The VS Code will be moved to the builtin display automatically.
6. The Terminal font corrupted.
![image](https://user-images.githubusercontent.com/3297602/79709949-1854d580-82f6-11ea-8893-1f830d50ebad.png)

**Comment by Tyriar** [comment]
I've seen this happen a bunch, we're probably just missing a case in https://github.com/xtermjs/xterm.js/blob/master/src/browser/ScreenDprMonitor.ts, or something is not listening to the monitor.

**Comment by Eugeny** [comment]
@Tyriar I can confirm that the listener fires as expected, but the characters are still corrupted. It can be reliably reproduced with the demo page, but only for *unicode characters*. ASCII will get occasionally corrupted, but not always.

Changing font size to something else and back immediately fixes it.

**Comment by jerch** [comment]
@Eugeny Could you test if this can be repro'ed for ASCII as well, if the fg color is set to RGB?

I suspect that `_drawUncachedChars` does not get the DPR changes for some reason.

**Comment by Eugeny** [comment]
@jerch I've just pushed a PR with the fix. The listener wasn't being called at all.
