### ISSUE TITLE
Incomplete display in Chinese

### ISSUE THREAD

**Issue by xiaofeng505** [xtermjs/xterm.js#2138]
🛑 The issue tracker is not for questions 🛑

Incomplete display in Chinese，if i use chrome.
![image](https://user-images.githubusercontent.com/17075294/58468659-8dfd0380-8170-11e9-8ba4-d049310cffee.png)

**Comment by xiaofeng505** [comment]
![image](https://user-images.githubusercontent.com/17075294/58468832-e6340580-8170-11e9-872d-4594d788fd6c.png)

**Comment by Tyriar** [comment]
/duplicate https://github.com/xtermjs/xterm.js/issues/1138

Workaround is to use rendererType: "dom"
