### ISSUE TITLE
String escape can freeze terminal

### ISSUE THREAD

**Issue by spadgett** [xtermjs/xterm.js#2139]
## Details
- Browser and browser version: Chrome (latest)
- OS version: macOS Mojave
- xterm.js version: reproduced in 3.8.1 and image xtermjs/xterm.js:latest

### Steps to reproduce

1. `docker run -p 3000:3000 xtermjs/xterm.js`
2. Open browser to http://0.0.0.0:3000/
3. Paste `echo -e "\x1bP"`

The terminal freezes.

**Comment by Tyriar** [comment]
Can repro on the docker container but not running the demo on mac

**Comment by Tyriar** [comment]
Also can't repro on Ubuntu 😕

**Comment by jerch** [comment]
Can repro this with docker under Ubuntu, no clue yet why this happens.

**Comment by jerch** [comment]
@spadgett 
Actually this works as intended.
The escape sequence you have tested is an introducer for DCS data, thus the terminal enters this state and reads all following data as such until it gets a finalizing sequence. If that finalizer does not occur, it will just "hang" in the DCS state. Same goes for other states like OSC (you try this with '\x1b]123;......').
The terminal is still working as you can test by typing `reset` + <kbd>Enter</kbd>, which sends the needed escape sequences to reset the terminal to its normal operation state.

NB: The finalizer for DCS is '\x1b\\', if you append that to your string it will show the prompt right after the echo. Any data between the introducer and the finalizer will not be shown, as the DCS data is meant for subparsers to do it work.
