### ISSUE TITLE
Uncached canvas draws are offset by 1 pixel

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2144]
Add to top of BaseRenderLayer.drawChars:

```
    (<any>window).t = (<any>window).t || 0;
    if (cell.getChars() === 'a' && (<any>window).t++ % 2 === 0) {
      this._drawUncachedChars(terminal, cell, x, y);
      return;
    }
```

<img width="354" alt="Screen Shot 2019-05-30 at 10 37 30 AM" src="https://user-images.githubusercontent.com/2193314/58651789-0544ab80-82c7-11e9-9bc2-3c7ff2fad325.png">

**Comment by Tyriar** [comment]
I think this is actually a bug in the static char atlas, not uncached draws.

**Comment by jerch** [comment]
Oh I also get 1 px offset in terminus with dynamic atlas. Repro:
- enable ligatures
- font: Fira Code
- type 'a-'
- type another '-'

--> the first '-' moves 1 px upwards.

**Comment by jerch** [comment]
Oh well my problem actually might be with the font itself, office and a textarea in the browsers shows the same "dancing" '-':

![image](https://user-images.githubusercontent.com/6193135/58654821-14544980-8319-11e9-9bf6-7d80c094f4c2.png)

**Comment by Tyriar** [comment]
Since the offset is just related to the static char atlas that's being removed in v4, I'll close this off.
