### ISSUE TITLE
Copying colored text while holding alt no longer works

### ISSUE THREAD

**Issue by npezza93** [xtermjs/xterm.js#2170]
Hey there 👋!

Looks like something may have changed with selecting colored text in zsh from 3.13 to 3.14. 
When copying colored text, pasting is throwing a `bracketed-paste-magic` error. 

## Details
- Browser and browser version: chrome and safari
- OS version: macos mojave
- xterm.js version: 3.14.0

### Steps to reproduce

1. jump into zsh
2. hold alt and select colored text
3. copy highlighted text
4. paste copied text

Videos showing the difference:

https://drive.google.com/file/d/1zMLVeNwrq7GaGuPj-FEMYzg60Oi_x6f_/view?usp=sharing
https://drive.google.com/file/d/1UXv6Hz-NhOmfPer7vhswA-7_DtVOrp0M/view?usp=sharing

**Comment by Tyriar** [comment]
I created an integration test for bracketed paste mode in https://github.com/xtermjs/xterm.js/pull/2172 and it seems to pass, not sure what's going wrong?

**Comment by npezza93** [comment]
Ok looks like my initial assumption was incorrect. This has nothing to do with copying colored text. I think it is due to https://github.com/xtermjs/xterm.js/commit/34ac1bc5029ea7f440acaf904c9c502324d6b1c9#diff-b28ef5ac37b020702c7a4f2e52676735. Currently in my app I automatically copy text when it is finished being selected. And from 3.13 to 3.14 it looks like the selection event gets fired when its cleared so basically a null string is being put on the clipboard which makes zsh unhappy. It totally makes sense to fire that event when the selection is cleared so this isnt an issue here. Sorry for the trouble!

**Comment by Tyriar** [comment]
@npezza93 thanks for letting me know, I didn't think that change would break anyone 🙁
