### ISSUE TITLE
color render issues with htop

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2189]
With Ubuntu 18 LTS `htop` looks broken:
![grafik](https://user-images.githubusercontent.com/6193135/58964519-536a1b00-87af-11e9-938f-f7a5f1dd1f5b.png)

- no recent xterm.js regression, same issues for older xterm.js versions on Ubuntu 18.04
- no issues with `htop` on Ubuntu 16
- no issues with other terminals on Ubuntu 18 (tested xterm, gnome-terminal and konsole)

Since other terminals work I wonder whether this is an old bug that went unnoticed and now gets triggered by recent changes in either `htop` or Ubuntu's terminal settings (changed terminfo?).

Update:
Seems to be related to terminfo, if I change the TERM variable to `xterm-256color` everything is working. The demo default of `xterm-color` is limited to the 8 standard colors, still there seem to be issues with these colors (as black is not black, and some chars lost the bold flag). 
There is another entry `xterm` in Ubuntu's terminfo which has the right color commands but is still at 8 colors. Looks like a bug in the terminfo db to me.

**Comment by theflyingape** [comment]
I can confirm TERM set to xterm-256color, xterm-color, xterm, linux, vt220, vt100 all render properly:

$ rpm -q ncurses
`ncurses-6.1-10.20180923.fc30.x86_64`
$ rpm -q htop
`htop-2.2.0-4.fc30.x86_64`
$ cat /etc/fedora-release
`Fedora release 30 (Thirty)`
$ npm ls xterm
`dankdomain@2.1.1 /home/rhurst/src/node/dankdomain`
`└── xterm@3.14.2`

Using `TERM=pcansi` does cause partial background color issues, but does the same using a regular xterm shell.

**Comment by jerch** [comment]
Ubuntu 18.04 still ships htop v2.1 which is known to have several rendering glitches (https://github.com/hishamhm/htop/issues/840).
