### ISSUE TITLE
Cannot read property 'setTheme' of undefined

### ISSUE THREAD

**Issue by tyrotoxin** [xtermjs/xterm.js#2220]
Hi, we've had such code:
```
this.terminal.setOption('theme', ....);
this.terminal.open(....);
```

However, with the latest changes, the internal `_colorManager` gets initialized on `.open()`, thus the first line fails with:
```
TypeError: Cannot read property 'setTheme' of undefined
    at e._setTheme (Terminal.js.pre-build-optimizer.js:587)
    at e.setOption (Terminal.js.pre-build-optimizer.js:307)
    at t.setOption (Terminal.js.pre-build-optimizer.js:193)
```

It's an easy fix on our side (just swap two lines), however, it makes sense to decouple visual customization from connectivity responsibilities. Was it an unintentional change?

**Comment by Tyriar** [comment]
I think this is already fixed in the latest release https://github.com/xtermjs/xterm.js/releases/tag/3.14.2, https://github.com/xtermjs/xterm.js/pull/2179

**Comment by tyrotoxin** [comment]
@Tyriar, it's a new unresolved issue.
If you look at [line 622 in Terminal.ts in master](https://github.com/xtermjs/xterm.js/blob/master/src/Terminal.ts#L622) - that's the only place where `_colorManager` is initialized - the `open` function.

**Comment by Tyriar** [comment]
Thanks for the follow up, fixing now 😃

**Comment by tyrotoxin** [comment]
Thank you for making it real :)

**Comment by Tyriar** [comment]
We should be able to entirely avoid these issues when this part is moved to TS strict mode, can't wait but it's a bit of a beast of a project https://github.com/xtermjs/xterm.js/issues/1507
