### ISSUE TITLE
3.14.2 typings should not mark applyAddon as deprecated

### ISSUE THREAD

**Issue by tsl0922** [xtermjs/xterm.js#2230]
3.14.2 typings should not mark `applyAddon` as [deprecated](https://github.com/xtermjs/xterm.js/blob/3.14.2/typings/xterm.d.ts#L884), as it's [README](https://github.com/xtermjs/xterm.js/blob/3.14.2/README.md#addons) still uses `applyAddon`.

I'm trying to use the suggested `loadAddon` in 3.14.2 but now all of the the published addons work (https://github.com/xtermjs/xterm.js/issues/2178#issuecomment-502334368).

**Comment by Tyriar** [comment]
For the new addons you need to install the beta tagged releases for them to work

**Comment by tsl0922** [comment]
@Tyriar The latest version of fit addon still not work on 3.14.2.

```
Uncaught TypeError: Cannot read property 'dimensions' of undefined
    at e.proposeDimensions ((index):1)
    at e.fit ((index):1)
    at t.onSocketOpen ((index):1)
```

**Comment by Tyriar** [comment]
@tsl0922 I suggest using the old addons for now. You bring up a good point that as we change the addons their compatibility breaks and we need to manage that a little better, probably by publishing the compatible addon versions in the release notes for v4+
