### ISSUE TITLE
Write twice `\r` after writing twice any content, `onData` will trigger two calls

### ISSUE THREAD

**Issue by mayongze** [xtermjs/xterm.js#2243]
Write twice `\r` after writing twice any content, `onData` will trigger two calls, parameter `19` `17`
![image](https://user-images.githubusercontent.com/22066360/59905487-f5893480-9438-11e9-91df-d6670a7898d3.png)![image](https://user-images.githubusercontent.com/22066360/59905504-ffab3300-9438-11e9-802c-afb95f613c86.png)
**Console:**
![image](https://user-images.githubusercontent.com/22066360/59905529-118cd600-9439-11e9-9d16-67083e511c31.png)

**The following operations will not trigger:**
![image](https://user-images.githubusercontent.com/22066360/59905550-1ce00180-9439-11e9-86ca-25ea5a347b51.png)Or![image](https://user-images.githubusercontent.com/22066360/59905563-279a9680-9439-11e9-83ca-361c02a02c22.png)

## Details
- Browser and browser version:  Chrome 75.0.3770.80
- OS version: Windows 1709
- xterm.js version: 3.14.2

### Steps to reproduce
```
const term = new Terminal()
term.open(this.$refs.render)
term.onData((data) => {console.log(data.charCodeAt(0), data.substr(1))})
term.fit()
term.write('\r')
term.write('\r')
term.writeln(this.intro)
term.writeln(this.intro)
```

**Comment by Tyriar** [comment]
`term.onData` shouldn't be firing at all for this, are you sure `this.intro` or something else isn't causing it? I can't repro on master.

**Comment by mayongze** [comment]
Sorry, I lost a line `term.fit()`

**Comment by Tyriar** [comment]
Fit shouldn't do anything either. I think that's probably happening here is because of the fact you're on Windows which uses winpty. I'm guessing winpty might be sending information requests back that xtermjs emits.
