### ISSUE TITLE
Webgl: Support rendering underline attribute

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2251]
Webgl addon added in https://github.com/xtermjs/xterm.js/pull/1790

**Comment by kamalesh0406** [comment]
Can you elaborate on what feature you need I cannot understand it 😅

**Comment by Tyriar** [comment]
Currently `echo -e '\x1b[4mhello'` will not print hello in underlined like the other renderers:

webgl:

<img width="219" alt="Screen Shot 2019-06-24 at 7 02 01 AM" src="https://user-images.githubusercontent.com/2193314/60025202-ff37b580-964d-11e9-8e1a-820e8b7b9ab5.png">

expected:

<img width="204" alt="Screen Shot 2019-06-24 at 7 02 08 AM" src="https://user-images.githubusercontent.com/2193314/60025209-019a0f80-964e-11e9-8d9e-af1bef5302be.png">

**Comment by ryanwarsaw** [comment]
@Tyriar another issue I've noticed is that font ligatures don't appear to work in the new renderer. Are these two issues similar? I'm new to the project, would love to contribute - not sure where the best place to start would be!

**Comment by Tyriar** [comment]
@ryanwarsaw ligatures are broken with all renderers at the moment, We need to tweak the addon in https://github.com/xtermjs/xterm.js/issues/2318

Once that's done, for WebGL we would need to handle these:

https://github.com/xtermjs/xterm.js/blob/5a9e6fe94b17f8a27938a3c26ece0056cd8f6976/src/renderer/Renderer.ts#L201-L207

In the WebGL renderer:

https://github.com/xtermjs/xterm.js/blob/5a9e6fe94b17f8a27938a3c26ece0056cd8f6976/addons/xterm-addon-webgl/src/WebglRenderer.ts#L225-L231

Right now they do nothing but they need to register/deregister and then be used when drawing the characters together and treat them as a simple glyph. For example if the addon says ">=" is a ligature, it should draw ">=" together in a single glyph and save it to the texture atlas like that, you might be able to leverage [WelglChatAtlas.getRasterizedGlyphCombinedChar](https://github.com/xtermjs/xterm.js/blob/5a9e6fe94b17f8a27938a3c26ece0056cd8f6976/addons/xterm-addon-webgl/src/atlas/WebglCharAtlas.ts#L126) to do that.

You might be able to hack in the ligatures addon to get it to work of bring it into this repo (from https://github.com/xtermjs/xterm-addon-ligatures) to get started on this, it should be relatively easy to do https://github.com/xtermjs/xterm.js/issues/2318 if you want to give that a shot.
