### ISSUE TITLE
Webgl: Support allowTransparency option

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2252]
Webgl addon added in https://github.com/xtermjs/xterm.js/pull/1790

I'm not sure what the state of this is currently.

**Comment by Eugeny** [comment]
Any updates on this one? This and character joiner support are the only things keeping me from using the WebGL renderer as default in Terminus.

**Comment by Tyriar** [comment]
No updates, needs someone to look into it until I get time to invest into bringing it to vscode.

**Comment by Tyriar** [comment]
Transparency seems to mostly work in from https://github.com/xtermjs/xterm.js/pull/2560/commits/ef05a6a05354901eef52177d03858a4e05111697 in https://github.com/xtermjs/xterm.js/pull/2560:

<img width="818" alt="Screen Shot 2019-11-25 at 2 33 26 PM" src="https://user-images.githubusercontent.com/2193314/69583854-a8356400-0f90-11ea-9910-4980411caab1.png">

The scrollbar seems a bit off though and haven't tested very thoroughly.

**Comment by Tyriar** [comment]
I tried to not draw a background rectangle at all as some colors ended up being off. There are two options for whoever wants too look into this in the future:

- Explore not using a background color for the viewport (would be inconsistent with other renderers)
- Explore not using a completely transparent background for webgl renderer (little worried about regressions here)

**Comment by Eugeny** [comment]
Works perfectly for me, including the scrollbar!

**Comment by Tyriar** [comment]
@Eugeny oh? The screenshot above of the demo is showing that the alpha color isn't correct as it's drawn twice (once in `.xterm-viewport`, once in `canvas`).

**Comment by Eugeny** [comment]
@Tyriar my primary concern was being able to have a completely transparent background - even in the current state `transparent` being drawn twice results in a usable transparent webgl xterm :)

**Comment by Tyriar** [comment]
@Eugeny ah ok, good 😃 I'll keep this open until the background color is correct though.

**Comment by Tyriar** [comment]
I believe the background color problem is fixed, notice how the right of the row is the same color:

![image](https://user-images.githubusercontent.com/2193314/181916880-b4c77f30-b1d5-4f44-9054-930364acc3c1.png)

There have also been several fixes that have gone in for v5. Let's close this off and track individual issues as they come up as this one's a little ambiguous what's left to do.
