### ISSUE TITLE
Reset command breaks formating

### ISSUE THREAD

**Issue by marusak** [xtermjs/xterm.js#2263]
Executing `reset` command in xterm.js connected do linux bash breaks colors. This is a new regression, it was not happening with `3.13.1` but is with `3.14.2`.

Steps to reproduce:
1) I use custom PS1
`export PS1='$(if test $HOSTNAME = "HELLO"; then echo -n "🔹[\u@\h \W]\\$ ";fi;)[\[\e[0;37m\]\d\t\[\e[m\] \[\[\e[0;37m\]\u\[\e[m\]\e[m\]@\[\e[0;32m\]MAIN \[\e[1;31m\]\w\[\e[m\]]\n($?$(if git log -1 --oneline > /dev/null 2>&1; then echo -n ")-(\[\e[0;36m\]"; git-branch-name; if cnt=$(git cherry 2>/dev/null | wc -l); then if test $cnt -gt 0; then echo -n " $cnt"; echo -ne "\xdf\xa1"; fi; git update-index -q --refresh >/dev/null 2>&1; test -z "$(git diff-index --name-only HEAD --)" || (echo -ne " \xE2\x99\xA5"); echo "\[\e[m\]"; fi; fi)) \[\e[1;30m\]\\$ \[\e[m\]'`
2) When I write `reset` text becomes bold.

It does *not* happen when using [reset](https://xtermjs.org/docs/api/terminal/classes/terminal/#reset) method.
While on the `reset` method - it does not show prompt the same way `reset` command does. Is this bug or intentional? Or is there some way how to restart terminal and get prompt line back?

## Details
- Browser and browser version: firefox-67.0.4
- OS version: Fedora 30
- xterm.js version: 3.14.2

**Comment by Tyriar** [comment]
Ugh, I thought this was added after master. It's already fixed but we should do a patch release to fix this in 3.14

**Comment by Tyriar** [comment]
I'll reopen https://github.com/xtermjs/xterm.js/issues/2196 and fix it up there
