### ISSUE TITLE
Clear method does not show the full prompt

### ISSUE THREAD

**Issue by marusak** [xtermjs/xterm.js#2264]
My PS1 is two lines long. When calling [clear](https://xtermjs.org/docs/api/terminal/classes/terminal/#clear) method only the  second line is shown.

## Details
- Browser and browser version: firefox-67.0.4
- OS version: Fedora 30
- xterm.js version: 3.142.

### Steps to reproduce

1.  Use the following PS1:
`export PS1='$(if test $HOSTNAME = "HELLO"; then echo -n "🔹[\u@\h \W]\\$ ";fi;)[\[\e[0;37m\]\d\t\[\e[m\] \[\[\e[0;37m\]\u\[\e[m\]\e[m\]@\[\e[0;32m\]MAIN \[\e[1;31m\]\w\[\e[m\]]\n($?$(if git log -1 --oneline > /dev/null 2>&1; then echo -n ")-(\[\e[0;36m\]"; git-branch-name; if cnt=$(git cherry 2>/dev/null | wc -l); then if test $cnt -gt 0; then echo -n " $cnt"; echo -ne "\xdf\xa1"; fi; git update-index -q --refresh >/dev/null 2>&1; test -z "$(git diff-index --name-only HEAD --)" || (echo -ne " \xE2\x99\xA5"); echo "\[\e[m\]"; fi; fi)) \[\e[1;30m\]\\$ \[\e[m\]'`

2. `terminal.clear()`
3. Only the second line is shown but both lines should be shown.

**Comment by Tyriar** [comment]
This is by design as there's no way for xterm.js to know how big your prompt is (mine's 2 lines too).
