### ISSUE TITLE
Implement Client Escape Codes

### ISSUE THREAD

**Issue by BiatuAutMiahn** [xtermjs/xterm.js#2271]
Similar to the web-links addon, can we get a feature that if a certain escape sequence is used (similar to how ANSI colors are used)...a specific callback is triggered, as in open a new tab, windows, navigate, or initiate a download?

Thank you

**Comment by Tyriar** [comment]
Let me know if this wasn't what you were thinking of:

https://github.com/xtermjs/xterm.js/blob/f9eeea59174d4092af919010073f3b13db4f0c08/typings/xterm.d.ts#L491-L513
