### ISSUE TITLE
Missing Types.js

### ISSUE THREAD

**Issue by sscfaith** [xtermjs/xterm.js#2272]
## Details
- Browser and browser version: chrome
- OS version:  mac
- xterm.js version:  3.14.4

### Steps to reproduce

![image](https://user-images.githubusercontent.com/23066241/60311006-ca966780-9987-11e9-933c-b170ecba1965.png)

**Comment by Tyriar** [comment]
Types.js is there for me after installing 3.14.4 fresh from npm? 😕 

<img width="536" alt="Screen Shot 2019-06-28 at 10 30 42 AM" src="https://user-images.githubusercontent.com/2193314/60360132-d423cd80-998f-11e9-8b36-8a248b29f664.png">

**Comment by sscfaith** [comment]
it appears when i reinstall
