### ISSUE TITLE
Option to right trim lines retrieved from selectionManager.selectionText

### ISSUE THREAD

**Issue by MaxRis** [xtermjs/xterm.js#2280]
For the moment terminal emulations apps based on xterm.js should implement right trimming of selected text on their own.

Different terminals behaves not identically:
- Standard MacOS's Terminal.app and Ubuntu's terminal don't do right trimming of copied lines.
- cmd.exe and iTerm2(MacOS) do right trimming.

Xterm.JS might consider to provide new option to enable automatic right trimming of copied lines.
Difference in copied white-spaces with/without turned on option might look as:

![2019-06-30_3-31-29-rtrim-copied-lines-option](https://user-images.githubusercontent.com/1928902/60390810-a6519c80-9ae7-11e9-8d3f-c33958b00384.gif)

Please provide your opinion regarding introduction of new option, thanks

**Comment by Tyriar** [comment]
This should already work, provided they are "null" cells and not "whitespace" cells. Do you have a repro where the trimming is not happening? If it's on cmd it might not be working right because of something weird going on in conpty/winpty.

**Comment by MaxRis** [comment]
1. Sorry, I forgot to mention, but whitespaces are not trimmed, seems, only if ConPTY is used. Since ConPTY is planned to be the primary pty for Windows, it makes sense to give this issue some attention.
2. I've tried to repro with `VS Code` and have found that ConPTY is used by `VS Code` to run terminal by default starting Windows 10 build 18309+ (and seems on all earlier Windows versions `VS Code` runs always WinPTY).
On Windows 10 build 17763 in `VS Code` the whitespaces are trimmed well (WinPTY is used according to their documentation for "Windows Enable Conpty" option in `VS Code` Settings).
On Windows 10 build 18922 `VS Code` doesn't trim whitespaces (ConPTY seems is used). Be default, `VS Code` launches terminal with Powershell. You can enter anything followed by whitespaces and press ENTER. Copy/paste will insert entered previously whitespaces.

**Comment by MaxRis** [comment]
![2019-06-30_22-02-01-VS-Code-ConPTY-not-trimmed-whitespaces](https://user-images.githubusercontent.com/1928902/60400918-1fea9880-9b83-11e9-8084-c2817e878669.gif)

**Comment by jerch** [comment]
Who is responsible for placing spaces there in the first place? Imho this has to be fixed there as we have no way to tell where to trim spaces (we simply dont know whether the space belongs to data or is just a "filling space").
Basically the same reason/issue why we changed to the null/space separation as well.

**Comment by MaxRis** [comment]
@jerch spaces are not trimmed as well if some process prints to std output and inserts spaces.

My request is about final users' desire to have trimming functionality as they have with WinPTY, cmd.exe or iTerm2 (haven't checked others terminals).

If to implement this for ConPTY, I believe that current xterm.js's logic for lines wrapping is not affected, since white space symbol is used as indicator to not wrap the line in current workaround to support wrapped lines on Windows https://github.com/xtermjs/xterm.js/pull/2278/files#diff-b8140f130bfc85e13de07e85f477c9d7R26

Might be really "too much attention" only for ConPTY's different behavior.

**Comment by jerch** [comment]
> @jerch spaces are not trimmed as well if some process prints to std output and inserts spaces.

Yes I am aware of that, we had several discussions about this when we suffered the space problem in the buffer ourselves. We also had several attempts to solve this by "clever trimming", none worked reliably. Once the space is there you cannot tell anymore whether it should stay (intended by incoming data) or should to be cut off (space from aligning/filling up).

About the workaround you referred to - this is a hack to overcome issues with line endings in ConPty, Id say we should to keep it exposed as that and not weave it further in the codebase.

**Comment by Tyriar** [comment]
I can't repro with powershell or pwsh on Windows 10 1903 (18362.175)

**Comment by Tyriar** [comment]
Closing off as it's likely a quirk with pty emulation on Windows
