### ISSUE TITLE
Reflow semi-broken on Windows

### ISSUE THREAD

**Issue by pfitzseb** [xtermjs/xterm.js#2291]
Reflowing long lines seems to only work in the viewport on Windows, and cause loss of data for lines outside of that region:

![reflow](https://user-images.githubusercontent.com/6735977/60795253-a139c080-a16b-11e9-9a02-00606f31982c.gif)

This might very well be a bug with node-pty, but not sure.

## Details
- Browser and browser version: Electron 2
- OS version: Windows 10
- xterm.js version: 3.14.4 (and whatever the latest stable VSCode uses)

### Steps to reproduce

1. Print a lot of output without any linebreaks.
2. Horizontally resize the terminal and scroll around a bit.
3. Observe that only some text is reflown, and data is lost on lines that aren't.

**Comment by Tyriar** [comment]
The reflow feature is disabled completely when windowsMode is turned on, what you're seeing is an issue with conpty or winpty reprinting the viewport.
