### ISSUE TITLE
eval usefulness of compat addon

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2308]
Coming from #2288.

We have some limited support for ancient/legacy sequences in InputHandler, that either do not make much sense these days or even could be harmful by changing terminal settings, that an integrator does not want to change at all.

Simply removing them seems a waste previous effort and would seriously break with older apps that still deal with those. A first idea is to identify the features we dont want to stay in codebase and move them in a second step into a compat addon. They then can be explicitly loaded/activated from there.

**Comment by Tyriar** [comment]
I'm starting to think we shouldn't bother with this as no one would likely use such an addon anyway?

**Comment by jerch** [comment]
Hmm tbh, idk if there are still apps using DECCOLM etc. Ive never seen this getting triggered by an app in the last 10ys. Prior 2000 there were some, but cant remember what it was (I think I've seen this under fvwm2 with some config apps in the 90s).

**Comment by jerch** [comment]
@Tyriar Yeah lets close this, imho DECCOLM could hide behind some setting once we have something working here #2399.

Other ancient stuff should be decided individually anyway.
