### ISSUE TITLE
Restructure mouse handling

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2319]
Coming from #2316, we clearly have to work on the mouse tracking front. Furthermore due to the restructuring of the repo we cannot go with the code we have in `Terminal.ts` which is full of browser refs. Last but not least the code is full of closured state and not easy to fix, thus I propose to rewrite this from scratch.

Rough idea to structure this:
- frontend/browser part:
  - register/deregister mouse tracking in browser engine for different event types
  - proper handling of event propagation (whether to stop or not)
  - catch browser mouse events
  - translate events into row/col based and dispatch it into offscreen part
- offscreen part:
  - handle proper protocol/encoding switches
  - announce changing mouse tracking state to frontend (to register/deregister handlers)
  - provide an event to trigger row/col based mouse events (hooked up by the frontend)
  - dispatch proper encoded reports to pty

The details are not worked out yet, prolly we will end up with mouse services in browser and common talking to each other by custom events. In general #2316 contains a list of needed changes to the current mouse handling.

To not introduce bad regressions we should first build up a proper test base (prolly with puppeteer, it can fake mouse movements and clicks). --> #2321

**Comment by Tyriar** [comment]
> The details are not worked out yet, prolly we will end up with mouse services in browser and common talking to each other by custom events. 

I don't think we need bi-directional communication, just browser depending on common? Also DECSET modes live in `ICoreService`.

**Comment by jerch** [comment]
Well the reports only walk into one direction, but we still might need some way to tell the browser service, to activate the mouse tracking in the browser? Well we just could install a "default on" handler there...

**Comment by Tyriar** [comment]
@jerch isn't mouse tracking determined by whether mouseEvents is set? This could live in CoreService/MouseService and have an event similar to onOptionsChange (or whatever it is)

**Comment by jerch** [comment]
Your prolly right, I am not that used to the new interface yet.

**Comment by jerch** [comment]
Offscreen/common part --> #2323.

**Comment by jerch** [comment]
Discussion related to browser part --> #2336 and #2337.

Closing this issue in favor of those.
