### ISSUE TITLE
Search addon does not search start of wrapped line when ydisp is in the middle of it

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2325]
Repro:

Write one really long wrapped line that spans multiple viewports
Search for a string above the viewport, no results will be found

**Comment by Tyriar** [comment]
cc @lramos15

**Comment by miggs125** [comment]
Mind if I give this issue a shot?

**Comment by Tyriar** [comment]
@miggs125 sure!

**Comment by miggs125** [comment]
@Tyriar I haven't been able to reproduce this bug, perhaps I am doing it wrong? I opened up the demo, ran ls and then filled the terminal with lorem ipsum until the results of ls weren't visible. I then searched for strings in the output of ls and it seems to be working.

**Comment by Tyriar** [comment]
@miggs125 that's the repro yeah, I can still get it to happen:

![image](https://user-images.githubusercontent.com/2193314/67622154-41276280-f7cc-11e9-84a5-c5cbe03c6dd2.png)

(vscode is basically at master of xterm atm)

Maybe tweak the width of the terminal or position of the string you're searching for?

**Comment by Tyriar** [comment]
Seems to work now
