### ISSUE TITLE
xterm 3.14.5 is not compatible with xterm-addon-fit 0.1.0 version

### ISSUE THREAD

**Issue by hemkaran** [xtermjs/xterm.js#2330]
I am using the first xterm-addon-fit version which 0.1.0 in which `renderService` is used instead of `renderCoordinate`. But xterm 3.14.5 (latest release) still contains old code. 
Commit: https://github.com/xtermjs/xterm.js/commit/cbfbe232d00fd3ff6acb622b3b5469d7f882f731

You need to release a minor version of xterm to accommodate these changes.

## Details
- Browser and browser version: NA
- OS version: NA
- xterm.js version: 3.14.5

**Comment by hemkaran** [comment]
@Tyriar Can you check it?

**Comment by Tyriar** [comment]
Yeah we haven't really worked out the versioning story just yet, use the applyAddon version for now. After a similar report I added to the releasing docs to note the compatible addon versions in the release notes https://github.com/xtermjs/xterm.js/wiki/Releasing#release-notes
