### ISSUE TITLE
Consider removing UTF8 and URXVT mouse encodings

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2334]
gnome-terminal never supported UTF8 encoding for mouse reports and will also remove the ambiguous URXVT encoding. See https://github.com/xtermjs/xterm.js/issues/1962#issuecomment-511920261.

Encodings to be removed:
- UTF8
- URXVT

**Comment by Tyriar** [comment]
@jerch come to a decision on this? I don't know much about what apps use what mouse encodings.

**Comment by jerch** [comment]
@Tyriar I'd say we simply remove those encodings with an upcoming PR. @egmontkob has convinced me, that this will do no harm to any app with mouse support, as the common ones already refer to SGR encoding (the only one that should be used for any new app with terminal mouse support).

**Comment by Tyriar** [comment]
@jerch since this should just be removing a bunch of code consider this for v4.2 😃
