### ISSUE TITLE
Performance reduction on Firefox with webrender enabled.

### ISSUE THREAD

**Issue by HeyBanditoz** [xtermjs/xterm.js#2341]
xterm.js is almost unusable in Firefox on Linux with webrender enabled. Also effects proxmox.
## Details
- Browser and browser version: Firefox 70.0a1
- OS version: Arch Linux
- xterm.js version: Unknown, used site demo to test

### Steps to reproduce

1. In `about:config`, toggle `gfx.webrender.all` and `gfx.webrender.enabled` to true.
2. Head to [the main page](https://xtermjs.org/) and play around with the demo, noticing poor performance.

**Comment by Tyriar** [comment]
@HeyBanditoz shouldn't this be reported to webrender/firefox instead?

**Comment by HeyBanditoz** [comment]
Yeah, you're probably right. I'm not sure exactly how or what to report to them, though.

**Comment by Tyriar** [comment]
It's likely having issues with a large number of `drawImage` calls, it could also be driver problems (we've seen issues under chromium too).
