### ISSUE TITLE
VT52 mode?

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2350]
While staring at the parser code I started to wonder whether we should support VT52 mode as well. Tbh I am not much interested in that feature myself, also we had no feature request regarding this as far as I am aware of. Maybe just keep it buried in computing history?
Also note that we have no clear "mode separation" at all, xterm.js is currently a wild mixture of all VT lines and some ECMA specs with many "holes". In general I think we should not try to be an emulator with such a clean emulation mode separation, I like our current cherrypicking more since it gives us a hint of features that are used/demanded. (There are so many ancient VT sequences that make not much sense anymore lol.)

Up for discussion. The changes needed to get this rolling are not much (some tweaks to the transition table and the parse method).

cc: @Tyriar, @mofux, @egmontkob, @textshell

**Comment by theflyingape** [comment]
FWIIW, I supported the mix of VT52/VT100/VT220 back in the PDP and VAX "data processing" days, and it was nice to downgrade VT100/VT220 for testing apps made for the data entry folks.  I think it's too nostalgic to have it baked in Xterm.js.

Would this be a good use-case as an add-on, or allowing for CSI extensions for those in need of custom sequences?  At least VT52 mode could be easily tested against ncurses apps.

**Comment by jerch** [comment]
> Would this be a good use-case as an add-on, or allowing for CSI extensions for those in need of custom sequences?

I second the addon idea, still this wont work without changing a few aspects on the parser. There is that one sequence that breaks with our assumptions about well formed sequences - cursor positioning with `ESC Y x y` cannot be caught, the coord bytes would end up in PRINT state. Also we dont expose enough details of the parser to intercept this (neither PRINT, ERROR or the transition table is public API atm). Furthermore patching it on that level with an addon will be quite cumbersome as 90% is the other states/sequences are invalid and would have to be disabled/ignored.
Thinking about it again it might be easier to switch to a clean VT52 parser and wire it to the needed terminal commands on activation. This could be done in an addon (only with private access atm). Opening this part of xterm.js to the public would allow more emulation modes, even block mode (most IBM terminals). But I am currently not interested in turning xterm.js into a general purpose terminal lib thingy.

> At least VT52 mode could be easily tested against ncurses apps.

Yeah, to my own surprise VT52 is still pretty well supported by most older apps.

**Comment by Tyriar** [comment]
Sounds a little out of scope for the project imo, unless it has real benefits making this separation in terms of simplifying the codebase.

**Comment by jerch** [comment]
@Tyriar Yes I think so too. Although its a low hanging fruit (in terms of needed bits to get it working), it makes not much sense to implement this as no one ever requested this.

Closing the issue.
