### ISSUE TITLE
Eval esctest for compliance testing

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2382]
We should check if we can benefit from a more systematic compliance testing with https://gitlab.freedesktop.org/terminal-wg/esctest. Its a comprehensive test suite for terminal behavior under different circumstances.

The tests were originally created by @gnachman for iTerm2.

**Comment by gnachman** [comment]
I wrote the test suite originally, and Thomas made a bunch of improvements and improved the xterm testing. This was my paternity leave project :)

**Comment by jerch** [comment]
@gnachman Woops, sorry - thought you stated that yourself in some comment, guess I got it wrong (and ofc cannot find it anymore lol). Thx for clarification.
Our sequence tests are currently inconsistent and incomplete, partly tested by a bunch of testfiles against xterm output, others are only tested with our JS test framework as integration tests. I hope to get this more straight forward with your test suite.
