### ISSUE TITLE
Expose buffer cell's color data via API

### ISSUE THREAD

**Issue by MaxRis** [xtermjs/xterm.js#2383]
It's related to https://github.com/xtermjs/xterm.js/issues/595#issuecomment-500233934

Currently plugin can access only "text" data in the Buffer.
To have better support of XTerm.JS serialization it's highly desirable to have possibility to access colors as well.

Is it the right time to extend the API?

**Comment by Tyriar** [comment]
Currently being discussed in https://github.com/xtermjs/xterm.js/pull/2369

**Comment by MaxRis** [comment]
@Tyriar wow, thanks!
