### ISSUE TITLE
xterm add-on fit doesn't fit to container

### ISSUE THREAD

**Issue by saisandeepvaddi** [xtermjs/xterm.js#2394]
## Details
- Browser and browser version:  Google Chrome 76.0.3809.100 (Official Build) (64-bit)
- OS version: Windows 10
- xterm.js version: 3.14.5
- xterm-addon-fit version: 0.1.0

### Steps to reproduce
I've created a sandbox to demonstrate.
[https://codesandbox.io/s/zen-boyd-u529q](https://codesandbox.io/s/zen-boyd-u529q)

terminal is not fitting to their red/green containers

It seems to fit width when I drag container larger than default rendered width. But height never seems to work.

Thank you

**Comment by tsl0922** [comment]
The `0.1.0-beta1` version should works for 3.14.5

**Comment by saisandeepvaddi** [comment]
I updated sandbox [https://codesandbox.io/s/zen-boyd-u529q](https://codesandbox.io/s/zen-boyd-u529q) with addon `0.1.0-beta1`.  Still seems to have issue.

**Comment by tsl0922** [comment]
Did you call `fitAddon.fit()`? I'm using xterm-addon-fit `0.1.0-beta1` and xterm `3.14.5` in t[tyd 1.5.2](https://github.com/tsl0922/ttyd/blob/1.5.2/html/src/components/terminal/index.tsx#L106), it works fine.

**Comment by saisandeepvaddi** [comment]
Yes. Its working with `fit()`. Thanks a lot. 👏

Addons section of README only says to use `loadAddon(new AddonName())`. So I only did that.

**Comment by Tyriar** [comment]
Thanks @tsl0922, and sorry about the addon versioning hassle. It should hopefully be fixed up with the new release soon.

**Comment by Tyriar** [comment]
I made a note about that version in the 3.14.0 release notes https://github.com/xtermjs/xterm.js/releases/tag/3.14.0
