### ISSUE TITLE
xterm-addons do not have a repository url in their package.json

### ISSUE THREAD

**Issue by alexandrudima** [xtermjs/xterm.js#2395]
It would be nice if the addons would contain a repository field in their `package.json` because certain tools benefit from this extra metadata.

For example, in VS Code, we have a tool which analyses all the node modules we ship, by going to their respective repositories and fetching the license text. 

Currently, we have to hard-code the licenses for xterm addons as a workaround for the repository field missing. -- https://github.com/microsoft/vscode/blob/59462eb0b16e8726bf2a3b810014852ddd2b2018/cglicenses.json#L49-L98

fyi @Tyriar

**Comment by Tyriar** [comment]
Something funny might happen with our tooling because the addons are in a sub-directory, but the license is essentially the same for the core project.
