### ISSUE TITLE
Keyboard events on Oculus Quest are not being recognized

### ISSUE THREAD

**Issue by alantrrs** [xtermjs/xterm.js#2396]
Seems like the keyboard events are not being recognized out of the box on the oculus quest. Focusing on the terminal works fine, however nothing happens when you begin to type. I've tried logging the `onData` and `onKey` events and they're not being triggered. 

## Details
- Browser and browser version: OculusBrowser/6.0.13.162924336
- OS version: Oculus Quest OS 8.0
- xterm.js version: 3.14.5

### Steps to reproduce

1. Open https://xtermjs.org/ on an Oculus Quest
2. Use the controller to focus on the Terminal (should work)
3. Try typing (no text appears in the terminal)

**Comment by Tyriar** [comment]
I'm guessing the textarea isn't actually getting focused or something? You could try call `Terminal.focus()` to force it? Check what document.activeElement is when you want to type.

Closing this off as we can't action it without the hardware, and it's pretty niche, but we'd probably accept a PR to fix it.

**Comment by wzli** [comment]
Would like to bump this issue. Also to add that it persists on the Quest2 as well.

**Comment by mofux** [comment]
We'd still accept a PR that fixes the problem, but as we don't have the hardware to test this, there is nothing we can do from our side.
