### ISSUE TITLE
Link matchers do not work with multi-line links

### ISSUE THREAD

**Issue by TDaglis** [xtermjs/xterm.js#24]

**Comment by martellaj** [comment]
Is there anyone looking into this issue? It's a killer for VS Code's integrated terminal.

**Comment by webdeb** [comment]
+1

**Comment by parisk** [comment]
Hi @martellaj, right now this is not assigned to anyone, so no one is looking into this.

We will get on top of this, as soon as we find the required amount of time.

And of course PRs are always welcome 😁.

**Comment by Tyriar** [comment]
I believe all the pre-requisites for this are now done:

- The buffer knows when lines are wrapped (at least on Linux/macOS)
- There is a relatively fast method to grab the entire line as a string
- Links no longer need to juggle the DOM so it will be possible to get multi-line lines with both parts reacting when hovering

I won't be able to pick this up any time soon. Here's what needs to be done for those interested:

- Query [`isWrapped`](https://github.com/sourcelair/xterm.js/blob/313d1e6fecd98a4a5e8dddebb832a6c4c16a828d/src/InputHandler.ts#L68) to identify lines that are wrapped when [linkifying rows](https://github.com/sourcelair/xterm.js/blob/313d1e6fecd98a4a5e8dddebb832a6c4c16a828d/src/Linkifier.ts#L202).
- Modify [`MouseZone`](https://github.com/sourcelair/xterm.js/blob/313d1e6fecd98a4a5e8dddebb832a6c4c16a828d/src/input/MouseZoneManager.ts#L158) and [`MouseZoneManager`](https://github.com/sourcelair/xterm.js/blob/313d1e6fecd98a4a5e8dddebb832a6c4c16a828d/src/input/MouseZoneManager.ts#L20) to support wrapping. This is probably best done by replacing `MouseZone.y` with `y1` and `y2`.

**Comment by Tyriar** [comment]
We also want to make sure links work when the data goes off the screen to the right. This should be tackled at the same time as multi-line links

**Comment by chirgjn** [comment]
I would like to take a stab at this. I have done a fair bit of js for past 2 years and am looking forward to get my first pull request. I can pick this up on the coming weekend if that is fine with everyone 😊

**Comment by Tyriar** [comment]
@chirgjn by all means. As a hint on where to start you will need to have the `MouseZone`'s support ranges that can span multiple lines, and then check if lines are marked with `isWrapped` and if so check for lines on the entire wrapped line and create the appropriate `MouseZone`. This will mostly involve working in Linkifier.ts and MouseZoneManager.ts

**Comment by chirgjn** [comment]
Thanks, picking this up this weekend 😃

**Comment by bastichelaar** [comment]
@chirgjn any progress on this?

**Comment by Tyriar** [comment]
@bastichelaar it's one of the handful of things I want to get to next if a PR doesn't come in.

**Comment by chirgjn** [comment]
Hey, sorry for the late reply. I will get a PR ready today.

**Comment by Tyriar** [comment]
@chirgjn FYI I've started working on it and plan to finish it off in probably the next week or 2 https://github.com/xtermjs/xterm.js/pull/1303

**Comment by webdeb** [comment]
@Tyriar thank you for the work on it, I'll check out your changes, maybe I'll be able to help out next time! 👍
