### ISSUE TITLE
Don't try move cursor on alt click if user has scrolled up

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2401]
See https://github.com/microsoft/vscode/issues/80496

**Comment by dwelle** [comment]
Still can repro on latest insiders, which should already contain the fix.

Version: 1.39.0-insider (user setup)
Commit: 0f1bd7721b793ed8b7805ba621061ce5a1f5c263
Date: 2019-09-09T05:28:53.427Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by Tyriar** [comment]
Thanks for pointing this out, I upgraded to the version 1 commit before this fix. Fixing it up now.

**Comment by dwelle** [comment]
Confirmed fixed in latest insiders. :100:
