### ISSUE TITLE
Accommodate predictive keyboard on mobile

### ISSUE THREAD

**Issue by oclyke** [xtermjs/xterm.js#2403]
### Relation to #1101 
There already exists an issue requesting support for mobile platforms, however that issue is broad and the feature request / issue here only covers a narrow subset of those needs. 

## Expected Behavior

> Xterm.js is a front-end component written in TypeScript that lets applications bring fully-featured terminals to their users in the browser.

Given this usage of xterm.js on any platform should feel transparent - that is to say that whenever an input is made (key pressed, text pasted, etc...) it should be reflected immediately. This is no less true for mobile devices

## Actual Behavior
Of course mobile devices have special optimizations and features. One such feature are 'smart' software keyboards. These cause behavior that is confusing and unexpected for the user. 

When typing in mobile (tested on Chrome for Android) 'predictive' text appears ahead of the cursor until it is entered. Additionally a long history of entered text is maintained in some in-between layer, causing the 'backspace' key to behave counter-intuitively. See a demonstration of the behavior in this gif: (tested on the latest 'master' running in SourceLair.) (Actually also documented by #675)

![xtermjs_predictive_mobile](https://user-images.githubusercontent.com/13486034/64480846-ec347c00-d18c-11e9-8587-dcaa21e99c68.gif)

## Proposed Solution
How do you remove predictive / smart features of mobile keyboards? Passwords! 

Solving this issue is possible by changing the HTML element type of the terminal's ```textarea``` to an input and adding the ```type='password'``` attribute. [Example commit](https://github.com/oclyke/xterm.js-mobile/commit/69cab25e46be41b7272530bc2c896c89a37c5a9c)

To see the changes in action start a new SourceLair project (language Node10) based on this fork:
https://github.com/oclyke/xterm.js-mobile

And switch to the branch ```predictive-keyboard_textarea-to-password-input```

⌛wait for changes to be recompiled ⌛

Check out your demo at the public URL! Try it on desktop and mobile. You will find that now all keyboard inputs are routed immediately to the control of xterm.js -- that means no more unpredictable behavior! This method is lightly tested on:

- Chrome on Mac OSX
- Chrome for Android
- Safari for iOS

This method does cause a warning about a password input not contained in a form... could be suppressed by wrapping the input in a form.

### Implementation / PR
I'd like to see this feature added to xterm.js in the near future for a project I am working on because the whole point is for it to work on mobile (bluetooth control of a micropython board via the web). I'm looking to the xterm.js veterans to guide me toward an acceptable implementation. 

Right now I can think of two possible paths forward:

- Just make the change. One commit, one type change (across 7 files), and the addition of the ```type='password'``` attribute.
- Create a Terminal construction option as to which password to use. Allows existing / desktop use cases to be blissfully unaware of any change, but creates additional complexity. 

The first option is tidy but it might have unintended consequences that a more experienced xterm.js developer could identify. The second option seems to be clunky and likely to add more code than is necessary for this. 

Does anyone else have another idea of how to support mobile in this regard?

### Thanks
I would *love* to see this make it into a new release! So would:
#1902 
#1635 
#675
#945 ?

**Comment by Tyriar** [comment]
Great write up! I don't think we can use password as that would be an accessibility issue, screen readers would announce the terminal input as a password field which is quite confusing. Right now `autocorrect="off"` and `spellcheck="false"` get set, maybe we can achieve what we want via additional attributes?

**Comment by Tyriar** [comment]
Note also that we may need to start listening to the `input` event instead of `keydown` to properly support this (which is buried in [this issue](https://github.com/xtermjs/xterm.js/issues/469#issuecomment-299740272)).

**Comment by oclyke** [comment]
Thanks for checking it out, I hadn't considered operation of a screen reader. I just installed ChromeVox (53.0.2784.6) to try it out. 

Currently the ```aria-label``` attribute (which says ```'Terminal input'```) seems to get used just once (the first time you focus the terminal) after which re-focusing only reads the element type (```'textarea'```). When changing to an ```'input'``` with ```'password'``` type attribute we still hear the ARIA text read on the first focus, but then the reader speaks *password text input* on subsequent focuses. Yes, I agree that is confusing and not ideal.

I don't know much about ARIA yet. How come the screen reader only announces the ```'aria-label'``` text once? Maybe that is implementation-dependent? It would be nice if the ARIA label were read consistently. 

At first glance I was worried that using attributes would not be able to solve the problem. However with a little more research I'm hopeful. Checking out [attributes for the ```textarea```](https://www.w3schools.com/tags/tag_textarea.asp) tag shows three types available:
- Local: I don't see anything promising here for getting transparent keyboard functionality 
- [Global](https://www.w3schools.com/tags/ref_standardattributes.asp): includes ```spellcheck``` but not ```autocorrect``` (why?). Maybe we can add some other unlisted attributes like [```autocomplete = 'off'```](https://davidwalsh.name/disable-autocorrect)
- [Event](https://www.w3schools.com/tags/ref_eventattributes.asp): possibly useful ```oninput``` attribute. 

I'll also try playing around with the ```input``` events to see if that can help. I'm worried though that the ```input``` won't occur until the predictive features of the keyboard have run their course in an inaccessible (to xtermjs) layer. 

(P.s. maybe this is a reason for to add to the HTML standard an input type ```direct``` or something to indicate to mobile devices that they should just try to act as closely to a hardware keyboard as possible - just dreaming!)

**Comment by oclyke** [comment]
Just tried to [disable autocomplete in the textarea](https://github.com/oclyke/xterm.js-mobile/tree/predictive-keyboard_disable-textarea-autocomplete) with no success. I have a feeling that the autocomplete referred to there is geared toward saved form data as opposed to the autocomplete features within a smart keyboard. 

Next up is the ```oninput``` exploration.

**Comment by Tyriar** [comment]
Additionally, since it's a `textarea` not an `input`, I don't think we could do the password option. For the `input` event, you will get the result after auto-complete.

I'm still hoping there's an attribute only fix to tell browsers to not do it, don't know why autocomplete="off" doesn't work 😕 

https://davidwalsh.name/disable-autocorrect
https://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/xtermjs/xterm.js/issues/1101

**Comment by luxi78** [comment]
Hi @oclyke , It seems that https://github.com/oclyke/xterm.js-mobile has been removed, can I find it elsewhere? I really need this, thanks a lot.
