### ISSUE TITLE
Provide toggle buttons on demo for enabling/disabling addons

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2407]
It would be nice to have a standard way to disable and enable all the addons just like with settings. This would be particularly useful for WebGL and [Ligatures](https://github.com/xtermjs/xterm-addon-ligatures) which should probably remain disabled by default.

**Comment by glneto** [comment]
You mean one option to Enable/Disable all or one option for each addon? Also, should they be enabled or disabled by default?

**Comment by Tyriar** [comment]
@glneto individual checkboxes for each addon in a new section. Right now there is a single button for webgl but if all the addons had checkboxes that would be great.

Note that webgl currently doesn't implement dispose properly so it won't work for that https://github.com/xtermjs/xterm.js/issues/2254, but unchecking web links for example should stop linkifying new web links.

For enabled by default, have their initial state being whatever the demo does right now (webgl is disabled, web links are enabled, etc.), for the attach addon have a button but mark it as disabled since I think unchecking would break the demo.
