### ISSUE TITLE
Unable to get value synchronously

### ISSUE THREAD

**Issue by monsterooo** [xtermjs/xterm.js#2408]
Hi @Tyriar 

I wrote some data using `term.writeln`.  At the same time, I can't get the value I just set using `term._core.buffer`.  But when I set a timer, everything works fine `setTimeout(getBuffer, 3000);`

I tested the demo used：
https://codesandbox.io/embed/elated-davinci-mue6q

I am very confused. Do you know why?  🤔

thank you very much!

**Comment by monsterooo** [comment]
https://github.com/xtermjs/xterm.js/blob/bc5e1e601234ac5ac1f129af1b4ceee11763725e/src/Terminal.ts#L157

`term._core.writeBuffer`  Is it a reliable way to use it ？

**Comment by Tyriar** [comment]
We've been discussing a method of knowing when the data was written for a while, I don't think there's an issue for it yet so let's track it in here.

https://github.com/xtermjs/xterm.js/pull/2369 has the callback for write but we might merge it in with a smaller PR before that.

**Comment by jerch** [comment]
@monsterooo 

> I am very confused. Do you know why?

`write` and `writeln` are async methods, they get not immediately processed. The reason for this is the output, we have to process incomming data in chunks to allow the renderer to update the viewport in between.

> `term._core.writeBuffer` Is it a reliable way to use it ？

You should not rely on `term._core.writeBuffer` - its not exposed via API thus may change over time. Furthermore its the buffer for incomming data, the terminal has not yet dealt with that data.

As @Tyriar  wrote the plan is to add a callback to write methods (nodejs style) that gets called once the chunk was processed by the parser. With this you can promisify your code later on:
```js
...
await new Promise(resolve => term.write('some string data', resolve));
doSomething(); // executed after the chunk was processed
...
```
