### ISSUE TITLE
Property 'attach' does not exist on type 'Terminal'. ts(2339)

### ISSUE THREAD

**Issue by glennflanagan** [xtermjs/xterm.js#2413]
I know this is a Typescript thing but I'm a bit stuck. I've tried asking this question over [on StackOverflow](https://stackoverflow.com/questions/57791997/xtermjs-property-attach-does-not-exist-on-type-terminal) but I've had no responses or comments so I'm wondering if anyone else can help. 

I'm trying to use the `attach` addon for xtermjs in Typescript but I'm getting the error:

```
Property 'attach' does not exist on type 'Terminal'.ts(2339)
```

<img width="646" alt="Screenshot 2019-09-11 at 09 27 00" src="https://user-images.githubusercontent.com/5485364/64680860-83901c80-d476-11e9-9065-16aa257ee188.png">

Here is my example code:
```javascript
import { Terminal } from "xterm";
import * as attach from "xterm/lib/addons/attach/attach";


Terminal.applyAddon(attach);
var socket = new WebSocket(
  "wss://docker.example.com/containers/mycontainerid/attach/ws"
);
const term = new Terminal();
term.attach(socket);

```

I can ignore the error but I wanted to know if there is anything I can do to not?

Here is [an example Codesandbox](https://codesandbox.io/embed/happy-surf-l72rl) with the error happening (in a React app)

**Comment by jerch** [comment]
Yeah the docs are wrong in this regard - there is no `attach` / `detach` anymore. With the new addon interface the attach addon work differently. to attach the ctor takes the socket directly:
https://github.com/xtermjs/xterm.js/blob/6211dcd923f0d1f062ede56b79c88593604d7e44/demo/client.ts#L175

To detach, simply call `attachAddon.dispose()`. To re-attach, create another addon instance with your socket.

**Comment by glennflanagan** [comment]
@jerch just to clarify - is `loadAddon` run on the instance of a `Terminal`?

**Comment by jerch** [comment]
@glennflanagan Yes. Its the new addon interface introduced with v4. It always works with addon instances (not with functions as before), thus you have to import the addon class and create an instance. The instance itself can be disposed later on.

**Comment by glennflanagan** [comment]
Got it. I'm running `3.14.5` which is why I'm confused. Time to upgrade!

**Comment by jerch** [comment]
Lol yeah well it just got released :smile:

**Comment by Tyriar** [comment]
Updating website in https://github.com/xtermjs/xtermjs.org/pull/88
