### ISSUE TITLE
WebLinksAddon not compatible with Edge

### ISSUE THREAD

**Issue by felixse** [xtermjs/xterm.js#2417]
Looks like the regex in the weblinks addon has problems with Edge.
`Syntax error in regular expression` is thrown in `Linkifier._doLinkifyRow`

## Details
- Browser and browser version:
Microsoft Edge 44.18362.329.0
Microsoft EdgeHTML 18.18362
- OS version: 
Windows 19 1903
- xterm.js version:
4.0.0.0 
- web-links-addon version:
0.2.0
### Steps to reproduce

1. Open demo in Edge
2. See errors in console

**Comment by Tyriar** [comment]
Error from edge:

![image](https://user-images.githubusercontent.com/2193314/64737111-fadaa600-d4a0-11e9-9879-83dd7d22b9aa.png)
