### ISSUE TITLE
Outdated peer dependency in addon packages

### ISSUE THREAD

**Issue by milleniumfrog** [xtermjs/xterm.js#2428]
Addons have xterm:^3.14.0 as peer dependency, but the documentation says v4+ is required.

## Details
- Browser and browser version: -
- OS version: Mac OS 10.14.6
- xterm.js version: 4.0

### Steps to reproduce

1. yarn add xterm (installs v4.0.1)
2. yarn add xterm-addon-fit

Error message:
```
warning "workspace-aggregator-4c369d15-b7ad-484f-b2d3-9a13af55a7ff > @compilingcodecamp/editor > xterm-addon-attach@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
warning "workspace-aggregator-4c369d15-b7ad-484f-b2d3-9a13af55a7ff > @compilingcodecamp/editor > xterm-addon-fit@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
```

**Comment by jerch** [comment]
@milleniumfrog Thx for pointing out. We are still in the major version transition, thus there still might be rough edges.

@Tyriar Should we also calculate this value from main package version number? Would avoid to patch it by hand with every release.

**Comment by Tyriar** [comment]
@jerch 👍
