### ISSUE TITLE
text area help

### ISSUE THREAD

**Issue by LB-J** [xtermjs/xterm.js#2432]
🛑 The issue tracker is not for questions 🛑

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/xtermjs.
![image](https://user-images.githubusercontent.com/7591120/65038266-2cacaa80-d982-11e9-88cb-b6b090d3679c.png)

who can help . the  terminal input area on the webtermial top  .....

**Comment by Tyriar** [comment]
Looks like you didn't include css/xterm.css on your page

**Comment by LB-J** [comment]
ok ,I'm try again 。because I use  angular and use not well

**Comment by LB-J** [comment]
thanks very much ....   It's work ....
