### ISSUE TITLE
document possible security implications/pitfalls

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2443]
@Tyriar, @mofux 
Since xterm.js gets more and more adopted by people for their terminal stuff - should we write a document about most basic security pitfalls? Imho the big players are more than aware of that and have appropriate counter measures in place, not so sure for the smaller projects.

What comes to my mind beside common XSS rules:
- _identifying application side data as untrusted (possible attack vector from pty-slave --> browser)_ Data from pty-slave should never be inserted in the embedding page lightheartedly as it might contain malicious content to cross the "terminal -> browser page border". We should identify which API methods carry that risk (like `onTitleChange` or a href parser/linkifier) and give some recommendations to circumvent it. This is also true for addon devs that want to deal with terminal data on DOM level. (Note: our DOM renderer is currently not affected as we already use `textContent` to insert terminal data.)
- _problems with websocket transport_ Websockets dont share the typical browser security measures like CORS and such. A malicious websocket client can even fake the Orgin header entry. Thus ppl should never ever try to run their project based on our limited development demo. We had several questions in this regard which makes me think we should emphasize this even more. To get something reliable working with websocket transport ppl **have to use additional security protocols over a secured websocket layer** (wss).

Furthermore we might want to link to the [security cheatsheets](https://cheatsheetseries.owasp.org/) as we cannot name/point out all security pitfalls (imho we should not even try to list concrete pitfalls as this might give ppl the wrong impression to be safe once they hardened their project against this list).

**Comment by Tyriar** [comment]
@jerch good idea, this could be under guides on https://xtermjs.org/docs/

**Comment by jerch** [comment]
Done with 4.3 release.
