### ISSUE TITLE
Search (upwards) is missing words in wrapped lines

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2444]
See https://github.com/microsoft/vscode/issues/81510 for repro

**Comment by dmitryrn** [comment]
I’ll probably check this out

**Comment by Tyriar** [comment]
@dmitryrn you'll want to get the demo up and running, after that the source for the search addon is in addons/xterm-addon-search

**Comment by dmitryrn** [comment]
Yeah, I’ll find out, thanks

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/2532
