### ISSUE TITLE
Caps lock isn't working correcting when using Pinyin IME on MacOS

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2457]
Ah I wasn't reproducing the right thing, this appears to be specific behavior of Chinese IMEs. Repro:

1. Enable PinYin IME
2. Type (Chinese auto completions appear)
3. Caps lock on
4. Type - This should be lowercase in the terminal but it's uppercase

VS Code issue: https://github.com/microsoft/vscode/issues/69367

**Comment by yifanchen** [comment]
Good to know, thanks for the link.

**Comment by gqbre** [comment]
Any solution yet ?

**Comment by ipaddicting** [comment]
Any updates so far? It's quite annoying to be forced to switch the input method between Pinyin and English.

**Comment by Tyriar** [comment]
PRs are welcome, realistically this is probably not going to get any attention from the core team.

**Comment by yume-chan** [comment]
I did some tests: the `keydown` event for pressing <kbd>A</kbd> key when Pinyin IME is active and CapsLock is active are

| | Chrome 98 | Safari 15 | Firefox 94 |
|----|----|----|----|
| `key` | `A` | `A` | `a` |
| `keyCode` | 65 (KeyA) | 229 (IME) | 65 (KeyA) |
| `code` | `KeyA` | `KeyA` | `KeyA` | 
| `shiftKey` | false | false | false|
| `getModifierState('CapsLock)` | true | true | true |

To me the Firefox implementation makes most sense, and Safari even has the `input`/`keydown` order [wrong](https://bugs.webkit.org/show_bug.cgi?id=170369). Maybe we should first file issues to Chromium or even [w3c/uievents](https://github.com/w3c/uievents) to get the behavior sorted.

**Comment by serkodev** [comment]
Any update on this? I have the [same problem on VSCode](https://github.com/microsoft/vscode/issues/69367), but i tried on xterm.js [official web](https://xtermjs.org/) with Firefox, Chrome and does not get any problem.
Seems like it's VSCode's bug.

**Comment by serkodev** [comment]
@Tyriar Few days ago, I made a pull request (#3728) for fixing this problem, please check.

**Comment by serkodev** [comment]
@Tyriar May I know is there any feedback?
