### ISSUE TITLE
Page crashes when `term.write` is called quickly in succession and `screenReaderMode` is enabled.

### ISSUE THREAD

**Issue by AndrewSverdrup** [xtermjs/xterm.js#2466]
Page crashes when `term.write` is called quickly in succession AND terminal has the setting `screenReaderMode: true`.

## Details
- Browser and browser version: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- OS version: Ubuntu 18.04.3 LTS
- xterm.js version: `4.1.0` (also observed in `3.*`)

I have not been able to reproduce this bug in Firefox.

May be related to https://github.com/xtermjs/xterm.js/pull/2120.

This bug was observed when trying to run a pip install command (`sudo pip3 install -U spacy`), but is reproducible by calling `term.write` many times in a `setInterval`.

### Steps to reproduce

1. Go to https://codepen.io/AndrewSverdrup/pen/VwwvXZg.
2. Click the 'Start writes' button in the HTML preview.
3. Observe the preview crashes after a few seconds.

If you comment out line 6 (`screenReaderMode: true`) it works fine. The bug/limitation seems to be in the screen reader mode code.

Thanks for creating/maintaining xterm! It is excellent!

**Comment by Tyriar** [comment]
I can't seem to reproduce? What kind of crash is it? Is it just an exception with a trace?

**Comment by jerch** [comment]
Repro'ed under Ubuntu 18 with Chrome 77 (same as OP). Again no issues with FF.

@Tyriar This is hard crash of the browser tab like a segfault, no exception or anything printed at the JS console. CPU and mem usage looks good in devtools. `top` revealed that the tab process is very memory hungry - it jumps over 8GB in 5s, prolly getting killed by the kernel for that.

**Comment by AndrewSverdrup** [comment]
@jerch @Tyriar I asked some others to try and reproduce it with that CodePen and everyone with the same environment I posted was able to. Interestingly one person couldn't reproduce it with Chrome v76 and they could reproduce it in Chrome v77. So it sounds like the bug may be in Chrome v77.

**Comment by Tyriar** [comment]
Yeah that's what it's sounding like if it's a hard crash, let's close this as we can't action it, feel free to report to Chromium though.
