### ISSUE TITLE
Support link matcher start position

### ISSUE THREAD

**Issue by jmbockhorst** [xtermjs/xterm.js#2468]
The registerLinkMatcher() should support returning the row and column position of the link so it can be used for position the hover message. Related to https://github.com/microsoft/vscode/issues/77964. 

For VSCode, I believe this is needed in order to match the terminal link experience (the popup starts where the link starts) to the rest of the editor. Currently, there is no way to get the position of the link, and the hover position is just the mouse position, which is inconsistent.

**Comment by Tyriar** [comment]
Right now you only get the MouseEvent and uri from the `tooltipCallback`:

```ts
export interface ILinkMatcherOptions {
  tooltipCallback?: (event: MouseEvent, uri: string) => boolean | void;
}
```

How about this?

```ts
// This is just `ISelectionPosition` but we're interested in the viewport only, not whole buffer
export interface ILinkLocation {
    startColumn: number;
    startRow: number;
    endColumn: number;
    endRow: number;
}

export interface ILinkMatcherOptions {
  tooltipCallback?: (event: MouseEvent, uri: string, ILinkLocation) => boolean | void;
}
```

Coupled with the ability to get the dimensions of the cells from https://github.com/xtermjs/xterm.js/issues/702, this would let us expose this information without getting into pixel coordinates (which get complicated as they could be relative to different things).
