### ISSUE TITLE
Replace ISelectionPosition API with IBufferRange

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2480]
This will allow us to have generic interfaces to represent a buffer range vs a viewport range

```ts
interface IBufferRange {
  start: IBufferCellPosition;
  end: IBufferCellPosition;
}
interface IBufferPosition {
  x: number;
  y: number;
}
```

More context: https://github.com/xtermjs/xterm.js/pull/2470

**Comment by Tyriar** [comment]
Thought: this position is only valid immediately after it was generated, `y` would need to be a marker for any longer.

**Comment by jerch** [comment]
> Thought: this position is only valid immediately after it was generated, y would need to be a marker for any longer.

Certainly a problem - could we get this done with markers? Not sure about their maintenance/update penalty, if there are a few held...

**Comment by Tyriar** [comment]
Should be fine if there aren't that many, marker have overhead of initializing an object and having their line updated on every scroll once scrollback is maxed out.
