### ISSUE TITLE
.off() missing from IPublicTerminal intentional?

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#2487]
https://github.com/xtermjs/xterm.js/blob/91cbeecf523b30e03d42e63cd57bab77021fbc3e/src/Types.d.ts#L175

seems to be missing `.off`, but `term.off('data', dataCallback)` still seems to work in 4.x. Is this the accepted usage for deregistering a data callback?

**Comment by Tyriar** [comment]
This is intentional, the new way is to do this:

```
const listener = term.onData(d => ...);

// remove data listener
listener.dispose();
```

**Comment by vincentwoo** [comment]
Thanks!
