### ISSUE TITLE
I can't write any letters on terminal

### ISSUE THREAD

**Issue by sweetienianyu** [xtermjs/xterm.js#2494]
## Details
- Browser and browser version: chrome 77.0.3865.120
- OS version:  macOS catalina
- xterm.js version: 4.1.0

### Steps to reproduce

1. first  i import xterm.js and css
2. according to docs i write some codes
    var term = new Terminal();
    term.open(document.getElementById('terminal'));
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
3. i can see a black terminal  on my web page 
4. but i can't write any letters on my terminal
5. Do I need to do something extra?
6. I create a repositorie to reproduce  https://github.com/sweetienianyu/xterm-test 
7 git clone it and yarn & yarn serve you can see my test page

**Comment by Tyriar** [comment]
Works for me?

![image](https://user-images.githubusercontent.com/2193314/67297978-7ca9f000-f49f-11e9-9024-010a0ca14a3e.png)

Check console for errors, try `git clean -xfd && yarn`

**Comment by Lizard-King101** [comment]
no I think he means he cant type on his keyboard into the terminal. there is no "setup" documentation or how to actually use this repo.

**Comment by Tyriar** [comment]
For basic use case check out:

- Demo: https://github.com/xtermjs/xterm.js/tree/master/demo
- Website js: https://github.com/xtermjs/xtermjs.org/blob/master/js/demo.js
