### ISSUE TITLE
codepoint in TextDecoder.decode

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2495]
From lgtm.com:

<img width="589" alt="Screen Shot 2019-10-21 at 6 49 59 PM" src="https://user-images.githubusercontent.com/2193314/67254760-b218f400-f433-11e9-8629-2d2bff68b95a.png">

Looks like it's always 0 at that point?

https://github.com/xtermjs/xterm.js/blob/d29fc6d5de9e93e549005ed9dc98df5dbec54af4/src/common/input/TextDecoder.ts#L197-L201

**Comment by jerch** [comment]
@Tyriar Woops, thats a typo in the code. Guess its time for more test cases again. The whole section is a code gem *cough* ...

**Comment by Tyriar** [comment]
😉

I fixed some nasty errors from the same site, like 10 lines in a case block that could never be hit 😱
