### ISSUE TITLE
Support "alt+enter" sending `\e\r`

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2498]
Reminder issue coming from #2364.

**Comment by kumaran-14** [comment]
@Tyriar I would like to take this.
Also, Do you have plans to extend support for `Caps + Enter` and `Shift + Enter` ?
Only asking because I generally use them a lot and struggled to set it up in Konsole. But generally, most terminal emulators only support `Alt + Enter`

**Comment by Tyriar** [comment]
@kumaran-14 sure. On caps and shift enter, we want to support what other terminals support, I'm not sure what they are meant to do personally?

**Comment by kumaran-14** [comment]
I use these key combinations for [zsh-autosuggestions  specific commands](https://github.com/zsh-users/zsh-autosuggestions#key-bindings). But it is true that not all terminals implement this. I will implement alt-enter only.

**Comment by kumaran-14** [comment]
@Tyriar I've looked at the #2364 pr thread.
file : `src/common/input/Keyboard.ts`
```
      if (ev.altKey && applicationCursorMode) {
        result.key = C0.ESC + C0.CR; // \e\r
      } else {
        result.key = C0.CR;
      }
```

Is these along the lines of what you had in mind?
I'm sure this is be more involved than this. Could you point me in the right direction?

**Comment by Tyriar** [comment]
@kumaran-14 it needs another decset private mode so it only is enabled when the mode is active, see https://github.com/xtermjs/xterm.js/pull/2364#pullrequestreview-287556720

@jerch is this right? Is it this one? 🤔 

> Ps = 1 0 3 9  ⇒  Don't send ESC when Alt modifies a key,
>           xterm.  This disables the altSendsEscape resource.

**Comment by kumaran-14** [comment]
@Tyriar Could you explain a bit more. How would I go about implementing a new privat mode and handle key signals based on this mode?

**Comment by jerch** [comment]
@Tyriar Hmm not sure about 1039 or 1036. I think we always use Alt, then 1039 should do.

**Comment by kumaran-14** [comment]
@jerch If I add a new DECSET private mode in `IDecPrivateModes` in the file `src/common/Types.d.ts`, in what way would I handle them in `setModePrivate()` and `resetModePrivate()` functions in `src/inputHandlers.ts` ?

**Comment by jerch** [comment]
@kumaran-14 Well, `setMode` always switches something on, `resetMode` switches something off. The DEC private flags are booleans indicating whether some operational mode takes place.

For DECSET 1039 I think we want it to send the leading ESC for any key+Alt combination, while for DECRST 1039 (reset) we should go with sending the key only (kinda ignoring the pressed Alt key, note that xterm sends in reset mode the 8bit variant of the key instead). Furthermore we should make DECSET 1039 being set by default.

About the 8bit key mode: We dont have that anywhere and it was no issue so far. I would not bother with it, as nowadays ppl dont know much about it and would never use it. Also it makes less sense in an unicode env. (I see only one valid use case for it - input of C1 chars. But those are somewhat ancient too, ppl again would not use it.)

**Comment by PerBothner** [comment]
I didn't see this mentioned: The Fish shell interprets Alt+Enter to [enter multi-line mode](https://fishshell.com/docs/current/index.html#multiline-editing).

Of the terminals I've tested, it works on gnome-terminal, Konsole, and DomTerm - but not xterm.
