### ISSUE TITLE
Setting normal buffer scrollback to 0 will send alt buffer mouse wheel sequences

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2500]
We might need a property to indicate the buffer is the alt buffer instead of relying on scrollback?

**Comment by ikmrgrv** [comment]
Can I do anything for this ??
I have little experience working in JS environment. I would need help and mentoring to resolve this.

**Comment by Tyriar** [comment]
@ikmrgrv I was in the middle of a response but I don't think this is what I thought it was but rather a shell is not accepting the sequences that we _want_ to send. Follow along in https://github.com/microsoft/vscode/issues/83154 if you're interested.
