### ISSUE TITLE
Xtermjs 4.1.0, how to accept keys, term.on or term.onKey. And how to load addons, example?

### ISSUE THREAD

**Issue by michaelqiji** [xtermjs/xterm.js#2502]
Hey guy, I move from 3.11.0, when I update xterm to be the latest version, it's broken. Can you give me some tips on what should I do to upgrade and what code need to be changed.

btw, I am building it on React.

Cheers

**Comment by Tyriar** [comment]
There are pretty thorough instructions for this on the release notes for v4, including examples for each breaking change: https://github.com/xtermjs/xterm.js/releases/tag/4.0.0
