### ISSUE TITLE
Support disposing of EventEmitters

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2509]
VS Code disposes Events which frees references to all its listeners, we should do the same:

https://github.com/microsoft/vscode/blob/4d1e08fec954853878c692a4c6629d7f0f884fd0/src/vs/base/common/event.ts#L591-L602

**Comment by revanthmahesh** [comment]
dispose method should be added in EventEmitter.ts, which should clear all the listeners in EventEmitter.ts??
