### ISSUE TITLE
Move away from string-based options

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2522]
How about we expose `options: ITerminalOptions` that replaces `getOption` and `setOption`?

```ts
class Terminal {
  options: ITerminalOptions;
}
```

This would also enable setting single settings (via getters/setters on the internal `ITerminalOptions` implementation) or changing all settings at once (via getter/setter of `Terminal.options`).

```ts
// before
term.setOption('rendererType', 'dom');

// after
term.options.rendererType = 'dom';
// or if it's the only setting
term.options = {
  rendererType: 'dom'
};
```

**Comment by jerch** [comment]
We have several such gems in options - how about enums vs. union types? Though enums are not that useful and cannot be `const` at public API level as long as we still target JS users.

**Comment by Tyriar** [comment]
Union types are typically preferred by JS devs as they're more concise and easier to use (no importing needed), luckily typescript can treat them just as strictly as an enum so doesn't matter from my perspective.
