### ISSUE TITLE
When term.write '\n' or attach to term,data contains '\n' , it is not left aligned.

### ISSUE THREAD

**Issue by zengbin3013** [xtermjs/xterm.js#2524]
When term.write '\n' or attach to a websocket,data contains '\n' , it is not left aligned.
## Details
- Browser and browser version:  chrome and firfox
- OS version: windows and ubuntu
- xterm.js version: 4.2.0

### Steps to reproduce

code as:
![image](https://user-images.githubusercontent.com/3376268/67910419-9513bc00-fbbd-11e9-8c73-d6fd6e6bee5d.png)

browser screenshot：
![image](https://user-images.githubusercontent.com/3376268/67910438-b1aff400-fbbd-11e9-8cf9-76c563a5dc0e.png)

**Comment by Tyriar** [comment]
As designed, use a carriage return `\r` to return the cursor to the start.
