### ISSUE TITLE
Split out puppeteer's install to be acquired separately to the rest of the modules

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2539]
It downloads Chromium which means is busts the GH Actions cache if we try to cache node_modules and also takes a long time to install locally and in CI. We should move it out and only install it when we need the API tests (`cd test/api && yarn`? `"pretest-api": "npm install puppeteer"`?).

**Comment by Tyriar** [comment]
Well this is mainly about just speeding up the compile/unit test job, which already gets run in containers. A perk is that it would also lower the startup time for new people. It makes sense to just avoid installing puppeteer unless you need to actually run the API tests, I don't think we should require someone to have docker to run them though.

**Comment by leomoty** [comment]
I meant more like `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` as an env var would only default for CI. So locally it should still download puppeteer. And could just check the same env var to set explicitly the binary or not.

**Comment by Tyriar** [comment]
👍 seems like the easiest fix: https://github.com/xtermjs/xterm.js/pull/2541

**Comment by leomoty** [comment]
That is what I meant, sorry for "missing the point" first :)
