### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by graue** [xtermjs/xterm.js#2544]
We'd like to be able to scroll a terminal horizontally. It looks like this might be possible by generalizing somewhat the code that was added in #218. This has come up in the context of an accessibility concern where a user uses large fonts due to vision impairment.

**Comment by Tyriar** [comment]
If you want to add a horizontal scroll bar it's possible right now by just sticking the terminal insider a container that is scrollable. We won't be building something like this natively though as it's such a niche scenario and imo should live within an the embedding application.

**Comment by MatthiasGrandl** [comment]
I was trying to implement a log viewer with xterm.js and wanted to add the option to toggle line-wrapping. Rendering the xterm.js over the width of the longest log line (about 10k pixels) absolutely kills performance, so this is sadly not an option.

I understand however that this is outside the scope of xterm.js.

**Comment by briancullinan2** [comment]
i got horizontal scroll working
