### ISSUE TITLE
Unable to detect `ENTER` key event  with => xterm[4.2.0] onKey() method 

### ISSUE THREAD

**Issue by goxr3plus** [xtermjs/xterm.js#2565]
Using the latest version of `xterm.js` **4.2.0** i want to be able to detect key events and pass them on the terminal , i am not able to detect when `ENTER` or `ALT` or `SHIFT` is pressed like i used to with older version `3.x.x`

![chrome_2019-11-13_14-49-21](https://user-images.githubusercontent.com/20374208/68765162-d1ff9a00-0624-11ea-8a4a-56e61719ed47.png)

Why Enter is returning `""` ?

What i have done:

```JS
    term.onKey(key => {
      const char = key;
      console.log(key);
      console.log(char.key === "");
      if (char === "") {
        console.log("Enter pressed");
        prompt();
      } else {
        term.write(char);
      }
    });

  prompt = () => {
    var shellprompt = "$ ";
    term.write("\r\n" + shellprompt);
  };
```

I am a new user of the library :)

**Comment by goxr3plus** [comment]
@jerch @Tyriar @parisk

**Comment by Tyriar** [comment]
It's there you'll find it's actually `\r`:

<img width="141" alt="Screen Shot 2019-11-13 at 6 40 09 AM" src="https://user-images.githubusercontent.com/2193314/68773491-81fee400-05e0-11ea-822c-543fd82f9a2b.png">

That is what a terminal emulator would normally send to a shell. If `key` doesn't have what you're after we also expose the `KeyboardEvent` directly:

https://github.com/xtermjs/xterm.js/blob/414eea2a2c4cde4c8fb72bb98cd48650bb89c927/typings/xterm.d.ts#L439-L445

**Comment by goxr3plus** [comment]
@Tyriar You are amazing you know that :) ? 

I ended up using `KeyboardEvent => keyboardEvent.domEvent.key`
