### ISSUE TITLE
Chalk [ 3.0.0 ] not working with xterm [ 4.2.0 ] 

### ISSUE THREAD

**Issue by goxr3plus** [xtermjs/xterm.js#2567]
I have made the following `React[16.11.0]` + `XTerm[4.2.0]` demo trying to use `Chalk[ 3.0.0 ] `but it doesn't work for some reason .... is this a bug or am i doing something wrongly?

I carefully read https://github.com/xtermjs/xterm.js/issues/895 and found out i have to use :

``` JS
let options = {enabled: true, level: 2};
const forcedChalk = new chalk.constructor(options);
```

But still i am getting errors => [you can see the very simple demo on SandBox](https://codesandbox.io/s/xtermreact-demo-c1h3u) , by the way i am making a full demo oF new xterm.js [ 4.0.0 ] so react developers can benefit from it .

**Comment by goxr3plus** [comment]
@jerch @Tyriar @parisk :) Please let me know in your free time .

**Comment by Tyriar** [comment]
@goxr3plus please don't ping people, Paris doesn't work on the project anymore and me and @jerch watch every notification.

**Comment by goxr3plus** [comment]
Okay i am sorry for that :)

**Comment by jerch** [comment]
> is this a bug or am i doing something wrongly?

Kinda the latter - you're using a lib meant for nodejs with OS env in mind for a pure browser env. That not gonna work unless the package provides other means to escape the nodejs stuff.

Closing since its not an xterm.js issue,

**Comment by goxr3plus** [comment]
Do you know a library i can use as a work around :) ?

**Comment by jerch** [comment]
@goxr3plus Nope sorry, maybe ask chalk devs how to escape the nodejs deps correctly?

**Comment by goxr3plus** [comment]
Thank you :)

**Comment by goxr3plus** [comment]
For future users i finally used another library called [ansi-colors](https://www.npmjs.com/package/ansi-colors)

![image](https://user-images.githubusercontent.com/20374208/69153408-d88b8700-0ae6-11ea-9b6f-bac69945291b.png)
