### ISSUE TITLE
Terminal.on is not a function

### ISSUE THREAD

**Issue by 4424dev** [xtermjs/xterm.js#2571]
Terminal.on is not a function is an error thrown when trying to accept input...
## Details
- Browser and browser version: Chrome
- OS version: 76
- xterm.js version: 4.2.0

### Steps to reproduce

1. Install xterm with npm
2. Run the following code:

Terminal.on('data', (data) => {
    Terminal.write(data);
});

**Comment by jerch** [comment]
@4424dev Its a feature, not a bug. v4 API removed the weakly typed interfaces in favor of strongly typed counterparts: `on('data', ...)` --> `onData(...)`.
Please refer to the API for the changes.

**Comment by 4424dev** [comment]
> @4424dev Its a feature, not a bug. v4 API removed the weakly typed interfaces in favor of strongly typed counterparts: `on('data', ...)` --> `onData(...)`.
> Please refer to the API for the changes.

Hi, I am trying to allow users to type and I am running this code:

term.onData(term.write(data));

It does not work, rather it say (data is not defined).

**Comment by jerch** [comment]
@4424dev `onData` takes a callback to be called with `data` later on, not the return value of some function (as you called it). Did you mean this?
```JS
term.onData(data => term.write(data));
```

**Comment by 4424dev** [comment]
> @4424dev `onData` takes a callback to be called with `data` later on, not the return value of some function (as you called it). Did you mean this?
> 
> ```js
> term.onData(data => term.write(data));
> ```
> 
> Edit: If you are using this for local echoing of input you might run into problems/artefacts. xterm.js is build to be used in conjunction with a real pty in between. A pty does several modifications on the data that you will have fake for local stuff. See https://github.com/wavesoft/local-echo for a solution that tries to circumvent this.

Yes, thank you very much.
