### ISSUE TITLE
Space between lines when drawing block characters

### ISSUE THREAD

**Issue by kolbe** [xtermjs/xterm.js#2572]
## Details
- Browser and browser version: 
Google Chrome 78.0.3904.108
Safari Version 13.0.3
Firefox 70.0.1 (after changing font-family to `"DejaVu Sans Mono", "Everson Mono", FreeMono, Menlo, Terminal, monospace, "Apple Symbols"`... the default font looks totally ridiculous in Firefox)

- OS version: 
macOS Catalina 10.15.1

- xterm.js version: 
Git commit 70babeacb62fe05264d64324ca1f4436997efa1b, build with `docker build .`.

### Steps to reproduce

[tidb.ascii.txt](https://github.com/xtermjs/xterm.js/files/3876032/tidb.ascii.txt)

1. Run TiDB Demo docker container 
2. `curl -L https://github.com/xtermjs/xterm.js/files/3876032/tidb.ascii.txt` in the xterm.js terminal pane.

![image](https://user-images.githubusercontent.com/1221210/69363398-51085a00-0c45-11ea-8fd9-104c29bb079a.png)

In my termimal, the block characters are smooshed together nicely and form a single field of pixels, while in xterm.js there is a small gap between each line.

**Comment by egmontkob** [comment]
See also #2409.

**Comment by theflyingape** [comment]
![vscode-linux](https://user-images.githubusercontent.com/19166945/69449325-a8cbc180-0d28-11ea-9450-0e643cf55112.png)

**Comment by Tyriar** [comment]
I think it depends on the font you're using so in a way it's as designed. #2409 would change this to override the font glyphs to be drawn manually, I'm not sure whether we want to do that or not.
