### ISSUE TITLE
NPM version

### ISSUE THREAD

**Issue by cryptopool-builders** [xtermjs/xterm.js#2573]
🛑 The issue tracker is not for questions 🛑

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/xtermjs.

I couldnt find out what version of npm do i need to be on to run npm install xterm.

**Comment by jerch** [comment]
We do not test again specific npm versions, we test again common LTS nodejs versions (master should work with LTS 8/10/12 and thus with the bundled npm).
