### ISSUE TITLE
Selection doesn't respect the zoom CSS rule

### ISSUE THREAD

**Issue by wl4g** [xtermjs/xterm.js#2584]
## Details
- Browser and browser version: chrome 72.x
- OS version: windows7(1366*768)
- xterm.js version:  latest

### Steps to reproduce

1. 
2.

**Comment by Tyriar** [comment]
What specifically doesn't work?

**Comment by wl4g** [comment]
![image](https://user-images.githubusercontent.com/29530154/69592863-4decdf80-1032-11ea-93c7-ec4b6f45dc44.png)

**Comment by wl4g** [comment]
![image](https://user-images.githubusercontent.com/29530154/69592935-7ffe4180-1032-11ea-979d-63b3ca1bb4e5.png)

**Comment by wl4g** [comment]
![image](https://user-images.githubusercontent.com/29530154/69593006-ca7fbe00-1032-11ea-9b7e-6e123b02643b.png)
Please see my screenshot

**Comment by wl4g** [comment]
As I've developed some browser plug-ins before, in mouse events, the location should be divided by document.body.style.zoom

**Comment by wl4g** [comment]
For example, this is the code I wrote before:

// Get mouse positions
window.onmousemove = function(i) {
	i = i || window.event;
	// To resolve browser scaling
	mouse.x = i.clientX/document.body.style.zoom;
	mouse.y = i.clientY/document.body.style.zoom;
}

**Comment by marvinthepa** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport

> This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

Chrome, Safari and Firefox have dropped support, so I guess the Chromium-based Edge does not have it as well.
So it is probably better not to add code to support this.

**Comment by Tyriar** [comment]
> My personal guess is that adding support for a non-standard Feature is not worth the effort.

Definitely, thanks for pointing this out.

> would transform: scale() work for your usecase, as the MDN docs suggest?

If transform has an issue that would be a bug, I think we've fixed transform related issues in the past though.

**Comment by Tyriar** [comment]
I'd be open to adding a `console.warning` if the `getComputedStyle` of the terminal container has `zoom` set to help debug this issue, we shouldn't support non-standard APIs though.
