### ISSUE TITLE
DOM renderer doesn't support transparency correctly

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2586]
Use this in demo to create terminal:

```ts
  term = new Terminal({
    windowsMode: isWindows,
    allowTransparency: true,
    theme: { background: '#ff000080'}
  } as ITerminalOptions);
```

Notice the background is drawn twice (look at scrollbar for proper color).

<img width="813" alt="Screen Shot 2019-11-25 at 2 49 46 PM" src="https://user-images.githubusercontent.com/2193314/69584749-d74cd500-0f92-11ea-95e4-a904fa544559.png">

**Comment by kumaran-14** [comment]
I'd like to take this on. What should be done further?

**Comment by Tyriar** [comment]
@kumaran-14 notice how the red screenshot above has 2 shades of red, the scrollbar share on the very right is correct. You'd need to investigate why it's happening (the screen and viewport both set the background color?) and resolve it such that both the screen and scroll bar are the same color.

**Comment by kumaran-14** [comment]
@Tyriar I used the demo code above, but could not generate this issue.
![xterm-screen](https://user-images.githubusercontent.com/32682103/72627456-8fcf3d80-3972-11ea-8f5d-baddc734bb62.png)

**Comment by kumaran-14** [comment]
I fiddled around, I was able to hide the scrollbar completey. Is this the required behaviour?
![xterm-2](https://user-images.githubusercontent.com/32682103/72628005-78448480-3973-11ea-953b-709e5361b1cc.png)

**Comment by Tyriar** [comment]
@kumaran-14 it is, but I can reproduce it here on Windows. Remember to switch the rendererType to dom renderer

**Comment by kumaran-14** [comment]
@Tyriar I switched to dom type, and I get dark color. 
I have a doubt, is the hex code above correct. Its of length 8 characters. Shouldn't be 3 or 4?

**Comment by Tyriar** [comment]
@kumaran-14 the last 2 are an alpha channel (transparency), it's a darker red because 2 partially transparent rectangles are drawn on top of each other, that's the bug.

**Comment by kumaran-14** [comment]
@Tyriar I found that when this line gets commented out, there is only one layer of color, i.e not dark anymore.
https://github.com/xtermjs/xterm.js/blob/fbeb45d1da9960cb9ebb0fea56882128696a254b/src/browser/renderer/dom/DomRenderer.ts#L159
But I think this is not the issue.

**Comment by kumaran-14** [comment]
@Tyriar This, along with the above may be the issue
https://github.com/xtermjs/xterm.js/blob/fbeb45d1da9960cb9ebb0fea56882128696a254b/src/browser/Viewport.ts#L57

**Comment by kumaran-14** [comment]
@Tyriar I think this is the issue. Can you confirm?
Removing the styling in `viewport.ts` should be solution

**Comment by kumaran-14** [comment]
@Tyriar I think this is the issue. Can you confirm?
Removing the styling in `viewport.ts` should be solution

**Comment by Tyriar** [comment]
Does anything else weird happen when you do that? My fear is that removing the color from the viewport will break the color of the macOS scroll bar.

**Comment by kumaran-14** [comment]
I dont see anything happening in my linux setup.
Let me know what you want me to do.

**Comment by kumaran-14** [comment]
@Tyriar what would be the fix for this?

**Comment by Tyriar** [comment]
Well removing this one seems to work fine on macOS, if it works fine on Linux we can probably move ahead with that:

https://github.com/xtermjs/xterm.js/blob/fbeb45d1da9960cb9ebb0fea56882128696a254b/src/browser/renderer/dom/DomRenderer.ts#L159

**Comment by kumaran-14** [comment]
Cool. I will send a pr.
