### ISSUE TITLE
How to use vim command in xterm.js?

### ISSUE THREAD

**Issue by ligang626** [xtermjs/xterm.js#2587]
Hello everyone. I use xterm.js in angular, but how to use vim command?

**Comment by jerch** [comment]
To use vim:
- install vim package (e.g. `apt install vim`)
- call `vim` at the shell prompt
- refer to vim docs how to work with it (if that was the question)

**Comment by Tyriar** [comment]
You probably didn't hook up a backend? Look at the demo for an example of how to use node-pty with xterm.js.
