### ISSUE TITLE
Feature request: API to add scrollable DOM elements as overlays

### ISSUE THREAD

**Issue by sdegutis** [xtermjs/xterm.js#2588]
I'd like to e.g. add a DOM element somewhere (like an \<img>) so that whenever the user scrolls the terminal, the element will scroll as if it's also part of the terminal character grid (even though it's just a DOM element). An API to add a DOM element to the scrollable terminal DOM element would allow me to do this. Or if this is already possible, this would then be a request to mention that API in the documentation. Thanks for your time in reading this request :) and great work btw.

**Comment by Tyriar** [comment]
I think this is captured in https://github.com/xtermjs/xterm.js/issues/1852, there is also some image support @jerch was looking into which is tracked in https://github.com/xtermjs/xterm.js/issues/614
