### ISSUE TITLE
DOM renderer on Linux does not apply contrast ratio to truecolors

### ISSUE THREAD

**Issue by connor4312** [xtermjs/xterm.js#2593]
## Details
- Browser and browser version: Code Insiders 2019-12-03
- OS version: Lubuntu 19.10

### Steps to reproduce

https://github.com/microsoft/vscode/issues/85966

Using the DOM renderer on Lubuntu 19.10, the contrast ratio does not apply to the truecolor test:

![image](https://user-images.githubusercontent.com/2230985/70070851-23a69f00-15a9-11ea-97e5-0fa097ef4176.png)

Canvas and webgl work, and dom works with the default palette color

![image](https://user-images.githubusercontent.com/2230985/70070907-42a53100-15a9-11ea-9869-b2f89e3c90a0.png)

**Comment by Tyriar** [comment]
The fix didn't work apparently https://github.com/microsoft/vscode/issues/86142#issuecomment-562287178

**Comment by Tyriar** [comment]
Fixed already
