### ISSUE TITLE
Color contrast cache will have conflicting keys for different color modes

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2601]
The cache key is based on the fg and bg color raw value:

https://github.com/xtermjs/xterm.js/blob/8b5c48fe878f830914248e4c1ed78e621deb16c4/src/browser/renderer/dom/DomRendererRowFactory.ts#L170

This will overlap for different color modes.

**Comment by jerch** [comment]
All JS engines I can test have show 9007199254740991 as `Number.MAX_SAFE_INTEGER`. Not sure if thats the case only for 64bit (cannot test 32bit). There are 52 safe bits to be used (guess its `double` based internally), thus you could simply join  BG and FG into one number as key with all rgb channels (= 48 bit).

**Comment by Tyriar** [comment]
@jerch it's probably easier to leave as is with the 2 separate keys to reduce fiddling with colors in this hot path.

Looking at this again, it's actually not a problem. I thought fg and bg just includes the number from getFgColor/getBgColor but it's not. https://github.com/xtermjs/xterm.js/pull/2602 just happens to work by accident because I only read `0xFFFFFF` and the color mode is stored beyond that in `0x3000000`
