### ISSUE TITLE
Improve naming and documentation around attribute data

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2603]
Current state:

https://github.com/xtermjs/xterm.js/blob/17cb610ef1eeeb96b35c2fea1d4f325d73797434/src/common/Types.d.ts#L71-L100

Problems:

- `fg` and `bg` are very ambiguous
- `getFgColor` and `getBgColor` return a number, not an `IColor`
- Can we improve `getFgColorMode` and `getBgColorMode` to return a `type ColorMode = CM_DEFAULT | CM_P16 | CM_P256 | CM_RGB` instead of `number`?
- This whole interface could do with some detailed docs, especially since it's probably going to get exposed in xterm.d.ts in https://github.com/xtermjs/xterm.js/pull/2369

**Comment by JavaCS3** [comment]
If `getFgColor`, `getBgColor` returns an Object, it will decrease performance a little bit.

**Comment by Tyriar** [comment]
@JavaCS3 it would still be a number, just a more precise one:

```ts
type ColorMode = CM_DEFAULT | CM_P16 | CM_P256 | CM_RGB
// equivalent to this but with names:
type ColorMode = 0 | 0x1000000 | 0x2000000 | 0x3000000
```

**Comment by JavaCS3** [comment]
> @JavaCS3 it would still be a number, just a more precise one:
> 
> ```ts
> type ColorMode = CM_DEFAULT | CM_P16 | CM_P256 | CM_RGB
> // equivalent to this but with names:
> type ColorMode = 0 | 0x1000000 | 0x2000000 | 0x3000000
> ```

Great

**Comment by jerch** [comment]
@JavaCS3 Just drop me a note if you have issue to restyle it (since I have created that convoluted mess).

**Comment by Tyriar** [comment]
@jerch I'm planning on doing this one, but we can carry the changes over to https://github.com/xtermjs/xterm.js/pull/2369 after

**Comment by jerch** [comment]
@Tyriar Ah ok, either way would work (and does not bloat #2369 with too much offtopic stuff).
