### ISSUE TITLE
insecure handling of links due to missing noopener usage

### ISSUE THREAD

**Issue by vapier** [xtermjs/xterm.js#2608]
for background details, check out this page:
https://dev.to/dhilipkmr/why-should-you-use-noopener-beware-of-security-flaws-3i57

this seems to affect [xterm-addon-web-links](https://github.com/xtermjs/xterm.js/blob/4.3.0/addons/xterm-addon-web-links/src/WebLinksAddon.ts#L28-L30) and the [mouse zone manager](https://github.com/xtermjs/xterm.js/blob/4.3.0/src/browser/Linkifier.ts#L296-L301).  it's easy to reproduce with the web-links addon, but i have no idea how to trigger the latter code.

unfortunately, `window.open` is not a friendly API.  when you add `noopener` to the features field, it resets all the other defaults on you.  [MDN has good documentation on this](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#Window_features).

it's also somewhat still a [relatively new feature](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types#noopener) (only available for ~2 years now), so if supporting older browsers is important, more work is required.

so the fix **isn't** as simple as say:
```js
-  window.open(uri, '_blank');
+  window.open(uri, '_blank', 'noopener');
```

fwiw, i added a utility function to hide this ugliness in hterm, and then updated all APIs to use that helper.
https://chromium.googlesource.com/apps/libapps/+/hterm-1.87/libdot/js/lib_f.js#283

**Comment by Tyriar** [comment]
@vapier thanks for the report. Feel free to do a PR for this, otherwise I'll tackle it in the next version.

The mouse zone manager one should fire if you remove `_handler` from the web links addon:

https://github.com/xtermjs/xterm.js/blob/bd0d267d972a1aab4777cddecf9bf8196d7aa44f/addons/xterm-addon-web-links/src/WebLinksAddon.ts#L45

**Comment by vapier** [comment]
i'm sure if i attempted to fix this, i'd do more harm than good :).  i've never fiddled with typescript before.

**Comment by Tyriar** [comment]
@vapier no worries, the fix will likely look exactly the same as JS though 😉
