### ISSUE TITLE
nano mouse support stopped working

### ISSUE THREAD

**Issue by Coding-Kiwi** [xtermjs/xterm.js#2611]
hi,

when I'm using GNU nano inside the terminal and activate mouse support via alt+m it allows me to move the cursor to the position I clicked.

I updated from 4.2.0-vscode1 to 4.3.0-beta.31 and this stopped working. Am I missing something?

## Details
- Browser and browser version: Chrome/78.0.3904.126 Electron/7.1.3
- OS version: win 7 and win 10
- xterm.js version: 4.2.0-vscode1 -> 4.3.0-beta.31

### Steps to reproduce

1. use xterm version: 4.2.0-vscode1
2. open file in nano
3. press alt+m
4. click somewhere to check if its working
5. npm install xterm@beta
6. repeat 2 - 4

**Comment by Coding-Kiwi** [comment]
I narrowed it down, it works in 4.3.0-beta20 but stops working in 4.3.0-beta21

**Comment by jerch** [comment]
Still works for me (under ubuntu).

@Tyriar Does the windows node-pty part support byte writes or only strings? Its the only thing I can think of...

**Comment by Coding-Kiwi** [comment]
@jerch okay, thanks for the info. If you need more information from me or if you want me to test something, feel free to ask.

**Comment by jerch** [comment]
@Coding-Kiwi Well if you are keen to fiddle around, you could test, whether the binary write at node-pty is the problem. For this change line 118 in `demo/server.js` like this:
```js
    ws.on('message', function(msg) {
      if (typeof msg !== 'string') {
        msg = msg.toString();  // does UTF8 string conversion, thus higher coords than 95 are messed up
      }
      term.write(msg);
    });
```
If it works for lower coords again, then thats the root cause.

**Comment by Coding-Kiwi** [comment]
@jerch not sure if the demo setup is of use here, I added the suggested lines to my personal project.

it uses the `ssh2` package, simplified with your suggested fix:

```
const Client = require('ssh2').Client;

var conn = new Client();
conn.on('ready', () => {
            conn.shell(pty_settings, (err, stream) => {

                 stream.on('data', (data) => {
                     if (typeof data !== 'string') {
                         data = data.toString(); // does UTF8 string conversion, thus higher coords than 95 are messed up
                     }
                     term.write(data);
                 }
             }
}
```

sadly this doesnt solve the problem

**Comment by jerch** [comment]
Does the ssh package support binary transport? If not, then it is already to late here. You can check this by testing here if data is always a string type. Just place a `console.log([data])` in front and see whether there are binary chunks at all once you enabled mouse reports in nano.

**Comment by Coding-Kiwi** [comment]
the ssh package has nothing to do with it I think. As I said, I tested the mouse support in my project with 4.3.0-beta20 which works, then ran `npm install xterm@4.3.0-beta21` and it stops working, so the only thing that changed is xterm or its dependencies

**Comment by Coding-Kiwi** [comment]
@jerch I'm so sry xD I wasn't forwarding the onBinary event because I didn't know this existed, thank you
