### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by sdegutis** [xtermjs/xterm.js#2615]
Handler is never unset:

https://github.com/xtermjs/xterm.js/blob/bd0d267d972a1aab4777cddecf9bf8196d7aa44f/src/browser/Lifecycle.ts#L13-L29

**Comment by sdegutis** [comment]
To be clear, the potential bug is that calling dispose() multiple times will probably keep calling removeEventListener. Probably need handler=null in there.

**Comment by jerch** [comment]
I'd call this not a bug, since `removeEventListener` is a NOOP for not attached handlers. Still this roundtrip into browser realms could be avoided, true.
