### ISSUE TITLE
Canvas selection doesn't accept rgba values in >=4.3

### ISSUE THREAD

**Issue by npezza93** [xtermjs/xterm.js#2620]
In the demo run: `term.setOption("theme", { selection: "rgba(255, 255, 255, 0.3)" })`

This should set the selection to the default color but if you try to select something no color shows up.

## Details
- Browser and browser version: Safari and Electron
- OS version: macOS Catalina
- xterm.js version: master

### Steps to reproduce

1. Run the demo 
2. Execute `term.setOption("theme", { selection: "rgba(255, 255, 255, 0.3)" })`
3. Click and drag to highlight

**Comment by Tyriar** [comment]
I might have broken this with the min contrast ratio changes as I only explicitly supported the `#rrggbbaa` format
