### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by ManojkumarV** [xtermjs/xterm.js#2622]
Getting the below errors when building xterm using npm install 

<img width="940" alt="Screen Shot 2019-12-09 at 5 39 37 PM" src="https://user-images.githubusercontent.com/10399151/70434905-87e6c880-1aab-11ea-9292-55f0f3060528.png">
<img width="915" alt="Screen Shot 2019-12-09 at 5 39 55 PM" src="https://user-images.githubusercontent.com/10399151/70434918-8ddca980-1aab-11ea-99ae-a5540158c4da.png">
<img width="876" alt="Screen Shot 2019-12-09 at 5 40 03 PM" src="https://user-images.githubusercontent.com/10399151/70434922-91703080-1aab-11ea-98bc-ea46ce8c9b29.png">

**Comment by Tyriar** [comment]
Try using `yarn`, this might be one of the cases that lock files prevent and we prefer yarn.lock over package-lock.json.
