### ISSUE TITLE
WebGL: Canvas added to body

### ISSUE THREAD

**Issue by pfitzseb** [xtermjs/xterm.js#2623]
With the new WebGL renderer I'm seeing a spurious problem where (what I think is) the char atlas is sometimes being added into `<body>` when the terminal loses focus:
![image](https://user-images.githubusercontent.com/6735977/70522308-2c671a00-1b41-11ea-8c5b-d814d0da3574.png)
Also see https://github.com/JunoLab/atom-ink/pull/242#issuecomment-562863787.

It's entirely possible that we're doing something stupid when initializing the terminal/renderer, but I'm still opening this issue on the off chance that someone has seen this before.

## Details
- Browser and browser version: Electron 4.2.12
- OS version: Manjaro
- xterm.js version: 4.3.0

### Steps to reproduce
Not sure how to reproduce this, sadly.

**Comment by Tyriar** [comment]
Nope, that's a bug and a pretty nasty one. Surprised no one has called it out yet.

**Comment by Tyriar** [comment]
Fixes and published to xterm-addon-webgl@0.4.1

**Comment by pfitzseb** [comment]
Thanks for the quick fix!
