### ISSUE TITLE
Textarea is visible

### ISSUE THREAD

**Issue by BetiDev** [xtermjs/xterm.js#2633]
Whenever I create my terminal with xterm I can see the textarea. Example: 
![image](https://user-images.githubusercontent.com/47372998/70872352-80289780-1f75-11ea-82e7-627b50c71a02.png). I don't know why it is doing this.

## Details
- Browser and browser version: Chrome. Version 78.0.3904.106 (Official Build) (64-bit)
- OS version: Chrome OS 
- xterm.js version: I don't know how to find this

### Steps to reproduce

1. Use nodejs to import the xterm module
2.  Init xterm on the web

Repl: https://repl.it/@PDanielY/TerminalX

**Comment by AndrienkoAleksandr** [comment]
Hello, You need import xterm styles. require('xterm/css/xterm.css'); or for typescript with configured webpack  `css-loader`: `import 'xterm/css/xterm.css'`

**Comment by AndrienkoAleksandr** [comment]
And for parent div, which you are using for xterm, don't forget to apply some styles too.

**Comment by BetiDev** [comment]
oh,ok. Thank you!

**Comment by BetiDev** [comment]
@AndrienkoAleksandr I don't think that's the problem, I have the style imported and it has the same result
