### ISSUE TITLE
Change cursor to hand/click for links

### ISSUE THREAD

**Issue by auchenberg** [xtermjs/xterm.js#2634]
Small nit, but it would be super helpful if the cursor changed to hand/click when hovering over links or "link mode" is activated like here in VS Code.

<img width="429" alt="Screen Shot 2019-12-17 at 10 45 04 AM" src="https://user-images.githubusercontent.com/173559/71024801-8f652d80-20ba-11ea-8bfb-bdc1a69a70e2.png">

No sure if this is core in xterm or code?

**Comment by jerch** [comment]
> No sure if this is core in xterm or code?

xterm core seems right for this atm since the renderers handle things differently. We have currently a PR (#2530) open for better link detection and linkifying service in general, when that gets done it can prolly be handled by the registered callback in a more unified way from integration side.

**Comment by Tyriar** [comment]
@auchenberg this on a mac? Works fine in latest Insiders and xterm master for me on mac.

**Comment by auchenberg** [comment]
Validated in latests insider on MacOS. So it seems it was there already? Funky, works in Insiders 👍

**Comment by Tyriar** [comment]
It was broken a little while ago so i guess you just hit that old bug
