### ISSUE TITLE
Allow custom xterm keybindings to be turned off by consumers (and provide APIs for them)

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#264]
As per https://github.com/sourcelair/xterm.js/issues/239#issuecomment-242633928 I think things like alt+arrow to jump words should be able to be turned off (or be off by default).

It does make sense for this stuff to be integrated into xterm.js so it works as most people would expect out of the box. However, in vscode for example, I would prefer if alt+arrow for example was routed to vscode's keybinding system so that users can define their own keybindings for this. In other words, I would like to turn this off and have vscode call into a public API to send the "Jump over word left/right" key sequence.

**Comment by parisk** [comment]
I am 👍  on this. I think one good thing we could do is create an API which is compatible with the `inputrc` format: http://www.securitronlinux.com/mint_linux/using-the-inputrc-file-to-control-keybindings-in-xterm/.

This could provide great experience with the user's customization's available out-of-the-box, when xterm.js is wrapped in native applications like vscode.

**Comment by Tyriar** [comment]
Yeah I need to check out what's in my `.inputrc` and what if anything is done via `gnome-terminal`.

**Comment by ayapi** [comment]
hmmm...? Xterm reads .inputrc? from my understanding, .inputrc is for Readline, not related to Xterm.
i thought .Xresources ( `XTerm.VT100.translations: #override` ) is suitable for this issue.
like this -> http://unix.stackexchange.com/questions/138501/keybinding-in-xterm-to-shift-one-line-up-using-shiftup

**Comment by parisk** [comment]
It was just a proposal to understand the syntax. X resources seems more suitable though.

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.

**Comment by jerch** [comment]
I dont quite get the idea behind those "// HACK: Make Alt + left-arrow behave like Ctrl + left-arrow:" changes in Keyboard.ts. By what were these hacks justified? Why would anyone want Alt+Arrow to behave exactly like Ctrl+Arrow?

**Comment by Tyriar** [comment]
@jerch it might have been me making things act as I would have expected when I was a noob. If so these should probably be in vscode's keybindings instead

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/issues/4538

**Comment by Tyriar** [comment]
The custom keybindings request in xterm.js was eventually closed as embedders can set it up to do whatever they want. My philosophy since then has been do baseline behavior in xterm.js and anything non-standard in embedders where you can probably configure as a user.

Some built-in examples in vscode that try make the terminal act more like the editor:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/5f9904f4-4232-4b5a-b6a7-82ba36354318)
