### ISSUE TITLE
Check if element is attached to DOM is too specific

### ISSUE THREAD

**Issue by nlundquist** [xtermjs/xterm.js#2642]
The check made here:

https://github.com/xtermjs/xterm.js/blob/71a78cbf0159adab95aaeb6e6a11cfa7485aca9c/src/Terminal.ts#L457

before throwing a warning is too narrow. It fails when xterm is opened inside a parent element inside a WebComponent shadow root. `document.body.contains(parent)` will return false, even thought the parent is fully attached and visible on the page.

## Details
- Browser and browser version: Firefox 71, Chrome 79
- OS version: OS X
- xterm.js version: 4.3.0

### Steps to reproduce
1. Create a simple WebComponent rendering a single div
2. Use Terminal.open to create a new terminal inside that div
3. The warning will be produced even though the elements are fully attached and rendered

**Comment by nlundquist** [comment]
Perhaps `parent.isConnected` is really all the check that is needed?

**Comment by Tyriar** [comment]
@nlundquist sounds like that's what I was after, would you like to do a PR for this?
