### ISSUE TITLE
Fit addon excludes terminals that are the child of a ShadowRoot

### ISSUE THREAD

**Issue by nlundquist** [xtermjs/xterm.js#2643]
The check made here:

https://github.com/xtermjs/xterm.js/blob/f1e01c7166d89679a1c9ec18c8a88f113e080919/addons/xterm-addon-fit/src/FitAddon.ts#L55

prevents the fit addon from working if the xterm element is the child of a ShadowRoot.`_terminal.element.parentElement` will be null, since it's `parentNode`, a ShadowRoot, is not an element.

## Details
- Browser and browser version: Firefox 71, Chrome 79
- OS version: OS X
- xterm.js version: 4.3.0

### Steps to reproduce
1. Create a simple WebComponent
2. Use Terminal.open to create a new terminal inside that tag
3. Call `.fit()`

**Comment by nlundquist** [comment]
i think the check here would be equally well served by `!this._terminal.element.parentNode` which will fix this

**Comment by Tyriar** [comment]
Should we use `isConnected` like the proposal in https://github.com/xtermjs/xterm.js/issues/2642 for this?

**Comment by hantatsang** [comment]
@nlundquist Do you have a simple code to replicate this issue?

The terminal is created inside a given DOM Node (ie. `xterm-container` in screenshot below), so its `parentElement` should be always that DOM Node, not a Shadow Root.

![xterm](https://user-images.githubusercontent.com/11912225/106371916-65ee8a80-63be-11eb-9991-e40ad3fa6aff.jpg)
