### ISSUE TITLE
xterm-addon-attach syntax error in IE

### ISSUE THREAD

**Issue by jestapinski** [xtermjs/xterm.js#2646]
When trying to use the `attach` addon in IE11, it results in a plain "syntax error". This is likely due to a webpack or tsconfig issue since copying the code into my local project works as expected.

Other addons (such as `fit`) use ES5 whereas this uses ES6.

## Details
- Browser and browser version: IE11
- OS version: Windows 7
- xterm.js version: 4.3.0
- attach version: 0.4.0

### Steps to reproduce

1. Open xterm.js with the attach addon loaded
2. Inspect the console

**Comment by Tyriar** [comment]
The tsconfig.json target is likely the problem as you indicated.

**Comment by Tyriar** [comment]
@jestapinski could you please verify with `xterm-addon-attach@0.5.0-beta.1`? I don't have a Windows machine around atm.

**Comment by jestapinski** [comment]
Hi @Tyriar, just gave it a look. Looks great, thanks for the update!
