### ISSUE TITLE
Take isWrapped cell status into account when alt+clicking to navigate the prompt in the normal buffer

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2658]
VS Code: https://github.com/microsoft/vscode/issues/86482

**Comment by kumaran-14** [comment]
What should be done to resolve this error? Can someone help me out? I'd like to solve this.

**Comment by Tyriar** [comment]
@kumaran-14 the alt+click feature code is all inside this file: https://github.com/xtermjs/xterm.js/blob/master/src/browser/input/MoveToCell.ts

[I see isWrapped is referenced in that file](https://github.com/xtermjs/xterm.js/blob/1c06e576aea6b1a63dc71d180ae92cc1c6d68c7c/src/browser/input/MoveToCell.ts#L105-L125), this issue will need to look into whether those usages are correct and why the problems occurs in https://github.com/microsoft/vscode/issues/86482

**Comment by kumaran-14** [comment]
I'm assuming I should switch to windows and setup [this](https://github.com/xtermjs/xterm.js/wiki/Contributing#windows) and try to reproduce the error first?
I'm using Arch Linux for development right now.

**Comment by Tyriar** [comment]
@kumaran-14 this should happen in bash on Linux too.

Actually I thought this was another issue my description was a little off. Moving across lines is disabled outright in the _normal_ buffer (ie. not in an application like vim). The problem is this fallback case where only horizontal movement is happening:

https://github.com/xtermjs/xterm.js/blob/fbeb45d1da9960cb9ebb0fea56882128696a254b/src/browser/input/MoveToCell.ts#L32-L33

Instead of this, if the current line is marked as isWrapped (when clicking above) or if the following line is marked isWrapped (when clicking below), it should take the wrapped line into account and move an additional `colcount * rowdelta` such that the cursor ends up where it was clicked (or as far as it can go in that direction).

**Comment by kumaran-14** [comment]
True. I debugged the functions and it seems like we cannot use vertical arrow sequence to move the cursor up as it brings up the last used command. The only way is to cleverly manipulate the repeated horizontal arrow sequence to get near to the target position.
I think I now understand the way the functions usage. So I will come up with a way to solve this based on your suggestion and if it sounds okay, I will implement it. 
Alright?

**Comment by Tyriar** [comment]
@kumaran-14 yes that's right, we only want to press left/right, the other vertical arrow sequence uses up/down which would navigate history in bash.

**Comment by kumaran-14** [comment]
@Tyriar How can I get the total row width of terminal?
I wrote some basic logic to move cursor to target if cursor is in the same row. To make it work across multiple rows, I need width of a single wrapped row.
Also, inside ```moveToRequestedRow```, something like this,
```
let rowsToMove = 2;
return repeat(rowsToMove, sequence(verticalDirection(startY, targetY), applicationCursor)); 
```
generates up/down keysequences, which navigates bash history for me. Is this the normal behaviour?

**Comment by kumaran-14** [comment]
@Tyriar How can I get the total row width of terminal?
I wrote some basic logic to move cursor to target if cursor is in the same row. To make it work across multiple rows, I need width of a single wrapped row.
Also, inside ```moveToRequestedRow```, something like this,
```
let rowsToMove = 2;
return repeat(rowsToMove, sequence(verticalDirection(startY, targetY), applicationCursor)); 
```
generates up/down keysequences, which navigates bash history for me. Is this the normal behaviour?

**Comment by Tyriar** [comment]
@kumaran-14 row width -> `bufferService.cols`

**Comment by kumaran-14** [comment]
I got it working, mostly.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32682103/72055965-c01f3800-32f1-11ea-9f08-ec112014089a.gif)

```
export function moveToCellSequence() {
  .
  .
  .
  // Only move horizontally for the normal buffer
  let direction;
  if(startY == targetY) {
    direction = startX > targetX ? Direction.LEFT : Direction.RIGHT;
    return repeat(Math.abs(startX - targetX), sequence(direction, applicationCursor));
  } else {
    direction = startY > targetY ? Direction.LEFT : Direction.RIGHT;
    return repeat(colsFromRowEnd(startY > targetY ? targetX : startX, bufferService), sequence(direction, applicationCursor))
    + repeat((Math.abs(wrappedRowsForRow(bufferService, startY) - wrappedRowsForRow(bufferService, targetY))-1)*bufferService.cols, sequence(direction, applicationCursor))
    + repeat(colsFromRowBeginning(startY > targetY ? startX : targetX, bufferService), sequence(direction, applicationCursor));
  }
}

function colsFromRowBeginning(currX: number, bufferService: IBufferService): number {
  return Math.abs(currX);
}

function colsFromRowEnd(currX: number, bufferService: IBufferService): number {
  return Math.abs(bufferService.cols - currX);
}
```
If I could access the last position of buffer, I could manipulate movement when the user click below the text buffer. So this does not work right now (see last few seconds of gif). The flickering seen is because of my screen recorder.

**Comment by kumaran-14** [comment]
@Tyriar I got it working, mostly.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32682103/72055965-c01f3800-32f1-11ea-9f08-ec112014089a.gif)

```
export function moveToCellSequence() {
  .
  .
  .
  // Only move horizontally for the normal buffer
  let direction;
  if(startY == targetY) {
    direction = startX > targetX ? Direction.LEFT : Direction.RIGHT;
    return repeat(Math.abs(startX - targetX), sequence(direction, applicationCursor));
  } else {
    direction = startY > targetY ? Direction.LEFT : Direction.RIGHT;
    return repeat(colsFromRowEnd(startY > targetY ? targetX : startX, bufferService), sequence(direction, applicationCursor))
    + repeat((Math.abs(wrappedRowsForRow(bufferService, startY) - wrappedRowsForRow(bufferService, targetY))-1)*bufferService.cols, sequence(direction, applicationCursor))
    + repeat(colsFromRowBeginning(startY > targetY ? startX : targetX, bufferService), sequence(direction, applicationCursor));
  }
}

function colsFromRowBeginning(currX: number, bufferService: IBufferService): number {
  return Math.abs(currX);
}

function colsFromRowEnd(currX: number, bufferService: IBufferService): number {
  return Math.abs(bufferService.cols - currX);
}
```
If I could access the last position of buffer, I could manipulate movement when the user click below the text buffer. So this does not work right now (see last few seconds of gif). The flickering seen is because of my screen recorder.

**Comment by kumaran-14** [comment]
@Tyriar I got it working, mostly.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32682103/72055965-c01f3800-32f1-11ea-9f08-ec112014089a.gif)

```
export function moveToCellSequence() {
  .
  .
  .
  // Only move horizontally for the normal buffer
  let direction;
  if(startY == targetY) {
    direction = startX > targetX ? Direction.LEFT : Direction.RIGHT;
    return repeat(Math.abs(startX - targetX), sequence(direction, applicationCursor));
  } else {
    direction = startY > targetY ? Direction.LEFT : Direction.RIGHT;
    return repeat(colsFromRowEnd(startY > targetY ? targetX : startX, bufferService), sequence(direction, applicationCursor))
    + repeat((Math.abs(wrappedRowsForRow(bufferService, startY) - wrappedRowsForRow(bufferService, targetY))-1)*bufferService.cols, sequence(direction, applicationCursor))
    + repeat(colsFromRowBeginning(startY > targetY ? startX : targetX, bufferService), sequence(direction, applicationCursor));
  }
}

function colsFromRowBeginning(currX: number, bufferService: IBufferService): number {
  return Math.abs(currX);
}

function colsFromRowEnd(currX: number, bufferService: IBufferService): number {
  return Math.abs(bufferService.cols - currX);
}
```
If I could access the last position of buffer, I could manipulate movement when the user click below the text buffer. So this does not work right now (see last few seconds of gif). The flickering seen is because of my screen recorder.

**Comment by Tyriar** [comment]
@kumaran-14 the clicking below the buffer behavior in the gif is correct, it should be moving it to the end of the prompt which. it's doing. Can you do a PR and we can discuss any further changes it needs before merging?

**Comment by kumaran-14** [comment]
@Tyriar create from my fork's master to upstream master?

**Comment by Tyriar** [comment]
@kumaran-14 ideally you should branch off from your fork's master:

```
git checkout -b myfeature
git push
```

And create a PR from that. Doing it off master can cause problems if you want to do another PR while the other is still in review (also syncing your master branch gets more complicated).

**Comment by kumaran-14** [comment]
@Tyriar I gave a pr.
