### ISSUE TITLE
Mulit code point emoji doesn't render correctly

### ISSUE THREAD

**Issue by thefallentree** [xtermjs/xterm.js#2660]
👩‍👩‍👧‍👧  doesn't render correctly in xtermjs

as you can see, it renders correctly in chrome 
![image](https://user-images.githubusercontent.com/1256464/71640979-53e56a00-2c49-11ea-88d8-2757fa5dfd97.png)

But not on xtermjs

![image](https://user-images.githubusercontent.com/1256464/71640989-62cc1c80-2c49-11ea-8dd6-5e2018f2c899.png)

## Details
- Browser and browser version: 
chrome latest
- OS version: 
windows 10
- xterm.js version: 
last release

**Comment by thefallentree** [comment]
How are these two related? I tested many common font and the emoji is not rendered correctly under any of the common fonts.

**Comment by Tyriar** [comment]
Been having issues with cmd+c recently 😕 It's this one https://github.com/xtermjs/xterm.js/issues/1709
