### ISSUE TITLE
Composition with tilde broken on Firefox on macOS with Finnish keyboard

### ISSUE THREAD

**Issue by ssh-peppe** [xtermjs/xterm.js#2661]
## Details
- Browser and browser version: Firefox 71.0
- OS version: macOS 10.15.2 - Finnish keyboard
- xterm.js version: 4.3.0

### Steps to reproduce

1. Type tilde + space or tilde + n
2. Observe that instead of getting ~ and ñ you get ~~ and ~ññ

### Description

For me on macOS, Fnnish keyboard, with Safari and Chrome a tilde + space results in ~ and tilde + n results in ñ as it should. But on Firefox a tilde + space results in ~~ and tilde + n results in ~ññ.

Interestingly this behavior difference can be seen (but a bit differently for some reason) on the https://xtermjs.org/ home page example terminal. If you enter tilde + space there on Safari you get nothing at all. Same for tilde + n. But with Firefox while tilde + space gets you nothing a tilde + n gets you ñ. Not sure why it's working differently there.

Debug logging shows the following when typing tilde + space on Firefox:

```
xterm.js: sending data "~" Array [ 126 ]
xterm.js: sending data "~" Array [ 126 ]
xterm.js: parsing data ~~
```

For tilde + n it shows:

```
xterm.js: sending data "~" Array [ 126 ]
xterm.js: sending data "ñ" Array [ 241 ]
xterm.js: sending data "ñ" Array [ 241 ]
xterm.js: parsing data ~
xterm.js: parsing data ññ
```

The "sending data" log lines reported by xterm.js also match what I'm seeing being sent to the onData() callback.

Note that there are differences in browsers and platforms with regards to what is reported when entering composed characters from e.g. compositionend vs. input vs. keydown vs. keypress events.

I should add that nothing is being sent until you hit space or n. That is, the initial tilde that starts the character compose does not result in any callbacks firing, whch is correct.

The sequence of keyboard events recording by attaching a custom keyboard handler using the Terminal API, for tilde + n is on Windows Firefox (71) with Finnish keyboard is the following:

```
keydown Control { target: textarea.xterm-helper-textarea, key: "Control", charCode: 0, keyCode: 17 }
keydown { target: textarea.xterm-helper-textarea, key: "AltGraph", charCode: 0, keyCode: 18 }
keydown { target: textarea.xterm-helper-textarea, key: "Dead", charCode: 0, keyCode: 160 }
keyup { target: textarea.xterm-helper-textarea, key: "Dead", charCode: 0, keyCode: 160 }
keyup { target: textarea.xterm-helper-textarea, key: "Control", charCode: 0, keyCode: 17 }
keyup { target: textarea.xterm-helper-textarea, key: "AltGraph", charCode: 0, keyCode: 18 }
keydown { target: textarea.xterm-helper-textarea, key: "ñ", charCode: 0, keyCode: 78 }
keyup { target: textarea.xterm-helper-textarea, key: "n", charCode: 0, keyCode: 78 }

```

On macOS with Firefox (71) with Finnish keyboard the sequence is:

```
keydown Alt { target: textarea.xterm-helper-textarea, key: "Alt", charCode: 0, keyCode: 18 }
keydown Alt { target: textarea.xterm-helper-textarea, key: "Dead", charCode: 0, keyCode: 160 }
keyup Alt { target: textarea.xterm-helper-textarea, key: "~", charCode: 0, keyCode: 160 }
keyup { target: textarea.xterm-helper-textarea, key: "Alt", charCode: 0, keyCode: 18 }
keydown { target: textarea.xterm-helper-textarea, key: "ñ", charCode: 0, keyCode: 78 }
keyup { target: textarea.xterm-helper-textarea, key: "n", charCode: 0, keyCode: 78 }
```

**Comment by ssh-peppe** [comment]
Possibly related: https://bugzilla.mozilla.org/show_bug.cgi?id=1305387

**Comment by ssh-peppe** [comment]
Seems like the same issue also exists on iPad OS 13 Safari with Finnish keyboard. Most likely other keyboards as well that use composition for tilde. Small difference in that tilde plus space results in ~~ but tilde plus n results in ~ñ.

**Comment by mofux** [comment]
@ssh-peppe Can you still reproduce the issue, e.g. in the recent vscode terminal? I've tried to reproduce on macOS Big Sur with finish keyboard layout, but it seems to be working fine. Producing the `~` character brings up the composition overlay (it's a little bit displaced to the right for some reason), then typing either `space` or `n` produces the desired character (and only once). 

![Kapture 2021-04-28 at 10 04 57](https://user-images.githubusercontent.com/2785983/116369052-3c9c9980-a809-11eb-8501-c6f7e84cf05b.gif)

**Comment by ssh-peppe** [comment]
> @ssh-peppe Can you still reproduce the issue, e.g. in the recent vscode terminal? I've tried to reproduce on macOS Big Sur with finish keyboard layout, but it seems to be working fine. Producing the `~` character brings up the composition overlay (it's a little bit displaced to the right for some reason), then typing either `space` or `n` produces the desired character (and only once).
> 
> ![Kapture 2021-04-28 at 10 04 57](https://user-images.githubusercontent.com/2785983/116369052-3c9c9980-a809-11eb-8501-c6f7e84cf05b.gif)

The issue was on Firefox, so I can't replicate it in VS Code. But it reproduces still in Firefox 88.

**Comment by mofux** [comment]
Oh I missed the fact that this only happens in Firefox. I've been able to spot the section in our code that messes up the composition for this particular case in Firefox:

https://github.com/xtermjs/xterm.js/blob/376b29673ba174934b1b6339ef3eed8449fec529/src/browser/input/CompositionHelper.ts#L103-L105

It seems like the composition helper is finishing the composition early, which then allows the actual keydown handler in `Terminal.ts` to print the character straight away instead of waiting for the composition to end. I'll see if this can be fixed easily, but the whole keyboard handling and composition is a hard to debug across different browsers / OS'es.

**Comment by ssh-peppe** [comment]
I made a small tester app that listens to keydown, keypress and compositionend events from a text field and then tried it out by typing a tilde on the Finnish keyboard. Here's the outputs.

Safari:

<img width="1392" alt="Screen Shot 2021-04-28 at 16 37 59" src="https://user-images.githubusercontent.com/51072037/116413379-3c6bc080-a840-11eb-8cce-691b276b40be.png">

Firefox:

<img width="1361" alt="Screen Shot 2021-04-28 at 16 37 52" src="https://user-images.githubusercontent.com/51072037/116413428-47265580-a840-11eb-9bc3-8735b98f74cc.png">

The tester app is simply an HTML document with a single input field and the following event listeners attached to it:

    let x = document.getElementById('x');
    x.addEventListener('keydown', event => console.log('keydown', event));
    x.addEventListener('keypress', event => console.log('keypress', event));
    x.addEventListener('compositionend', event => console.log('compositionend', event));

As you can see from the output, the keydown and compositionend events fire in different order on those two browsers. But Chrome fires them in the same order as Firefox and I can't replicate the original issue with Chrome.

**Comment by ssh-peppe** [comment]
Let me know if you need any help in debugging this.
