### ISSUE TITLE
can the "clear" method support no screen? Just add a new scroll bar, and the content scrolls up to it

### ISSUE THREAD

**Issue by roguexiaohuihui** [xtermjs/xterm.js#2671]
If I do the clear method, it will clear the whole screen, but I think it's just the current screen is empty, but the content doesn't clear. Specific implementation can add a scroll bar, and then scroll down the scroll bar has rendered the number of lines.

I would like to ask if there is any recommended scheme to realize this requirement?

**Comment by Tyriar** [comment]
You can scroll/clear more specifically by writing certain sequences, see Erase in Display on https://invisible-island.net/xterm/ctlseqs/ctlseqs.html for example.

**Comment by roguexiaohuihui** [comment]
> You can scroll/clear more specifically by writing certain sequences, see Erase in Display on https://invisible-island.net/xterm/ctlseqs/ctlseqs.html for example.

I have carefully read the reference address you gave me, but I am still confused. Could you give me a simpler example? Thanks for your reply
