### ISSUE TITLE
Add blank lines at the bottom of the terminal 

### ISSUE THREAD

**Issue by Akarys42** [xtermjs/xterm.js#2672]
Hi, I'm trying to use [TTYD](https://github.com/tsl0922/ttyd/) on my server and connect on my iPad. The problem is that the virtual keyboard is in the way, and I can’t scroll down the terminal. Is it possible to add some blank lines at the end, so I can easily scroll it down and put the text above the keyboard.

Here is what I mean : 
If I run a lot of command (`cat .bash_history` for example), the terminal will look like this : 
![6ECB8568-3640-4C5C-B0B1-6CADCDA102E8](https://user-images.githubusercontent.com/44778521/70797174-3dfc2c00-1da4-11ea-91f3-385c944a02ce.png)

But now if I try to write a new command, the keyboard is in the way : 
![18AA462D-2D58-45E1-82B3-B92EDCA830E3](https://user-images.githubusercontent.com/44778521/70797207-53715600-1da4-11ea-8e11-487b8931c1d9.png)

I have opened an issue on the TTYD project directly (tsl0922/ttyd#254), but they told me to report the problem here, so here I am :D

I’m on a RPI 4B and Ubuntu Server ARM

**Comment by Tyriar** [comment]
Mobile support is tracked in https://github.com/xtermjs/xterm.js/issues/1101
