### ISSUE TITLE
Cursor lags behind when typing very fast

### ISSUE THREAD

**Issue by MohamedElgharbawy** [xtermjs/xterm.js#2673]
## Details
- Browser and browser version: Chrome 79.0.3945.117
- OS version: MacOS Catalina 10.15.1
- xterm.js version: Latest

### Steps to reproduce

1. https://codepen.io/mwelgharb/pen/qBEpLEe
2. Type very very fast, the cursor will lag behind. Happens consistently.

I'm not sure if this is a bug with xterm, or with the way I have implemented it. Any insight would be appreciated!

**Comment by Tyriar** [comment]
This is a problem with how you've implemented it, what you're doing is listening to the key event and acting there. But you should instead be reacting to the onData event which is after the key event has gone through serialization to text. Basically you should use `Terminal.onData` to react to input events in the terminal and `Terminal.write` to write things to it. I'm not.

That's probably not the cause of the cursor "lagging behind" problem though, just a general problem you should fix up. The cursor being always at the start of the line seems to be because you put it there with this line:

```js
term.write('\033['.concat(pos.toString()).concat('D')); //term.write('\033[<N>D');
```

`\033[<N>D` will move the cursor backwards (left) `N` times.

**Comment by Tyriar** [comment]
This is what I'm seeing to be clear:

<img width="745" alt="Screen Shot 2020-01-15 at 3 04 08 PM" src="https://user-images.githubusercontent.com/2193314/72479108-4e8b3200-37a8-11ea-8648-b29469e814c0.png">

**Comment by MohamedElgharbawy** [comment]
How do I use onData? I tried replacing the instances of term.on with term.onData, but that doesn't seem to work.

**Comment by Tyriar** [comment]
> xterm.js version: Latest

@MohamedElgharbawy this is actually wrong, that codepen is on xterm 3.14 which is quite old. Since then, `on` has been removed in favor of onData, onKey, etc. See the API here:

https://github.com/xtermjs/xterm.js/blob/fbeb45d1da9960cb9ebb0fea56882128696a254b/typings/xterm.d.ts#L458-L473

**Comment by MohamedElgharbawy** [comment]
Can you provide a small example of how to use onData? I'm trying to look up examples, but they all use Terminal.on instead.

**Comment by jerch** [comment]
> Can you provide a small example of how to use onData? I'm trying to look up examples, but they all use Terminal.on instead.

Thats indeed an issue with those examples floating around in the internet, most are older and dont show the newer API. If in doubt, I suggest to always refer to our own demo in this repo here, it will reflect any new API stuff as well (we use it for development). For `onData` see the attach addon: https://github.com/xtermjs/xterm.js/blob/fbeb45d1da9960cb9ebb0fea56882128696a254b/addons/xterm-addon-attach/src/AttachAddon.ts#L35

**Comment by Tyriar** [comment]
@MohamedElgharbawy doing this should help you understand it better:

```ts
terminal.onData(data => console.log(data));
```

**Comment by MohamedElgharbawy** [comment]
I converted everything to use onKey, but I still get the cursor lagging bug? Any idea what could be causing this? I have a feeling it's because here:

```js
pos = curr_line.length - term.buffer.cursorX + 4;
curr_line = [curr_line.slice(0, term.buffer.cursorX - 5), input, curr_line.slice(term.buffer.cursorX - 5)].join('');
term.write('\33[2K\r\u001b[32mscm> \u001b[37m' + curr_line);
term.write('\033['.concat(pos.toString()).concat('D')); //term.write('\033[<N>D');
```

I allow the user to write in the middle of their entry, and then adjust the position of the cursor. Could this be causing some issue?

**Comment by Tyriar** [comment]
I mentioned earlier that the reason the cursor is on the left side is because of 

```
term.write('\033['.concat(pos.toString()).concat('D')); //term.write('\033[<N>D');
```

Try remove/tweak lines and see what happens.

**Comment by MohamedElgharbawy** [comment]
That's not what I am referring to. I am aware of the cursor going to the beginning of the line. What I am talking about is if you type very fast, the cursor will lag one position behind.

![Here is an example.](https://user-images.githubusercontent.com/30507689/72569383-316d6680-386f-11ea-9814-33aa7c772271.png)

Give it a try in the codepen. It'll happen well before you loop to the beginning of the line again.

**Comment by jerch** [comment]
@MohamedElgharbawy Cannot repro it in Firefox or Chrome.

**Comment by MohamedElgharbawy** [comment]
Can you try this? https://mohamedelgharbawy.github.io/scheme

**Comment by jerch** [comment]
Nope, the cursor is always behind the last typed char (until the chars hits the line limit, then weird things happen).

**Comment by MohamedElgharbawy** [comment]
It looks to be happening on Mac. I hopped on my Windows machine, and the lag does not occur. Are you on Windows by any chance?

**Comment by jerch** [comment]
Linux.

**Comment by jerch** [comment]
@MohamedElgharbawy Is this meant to run solely in the browser without a pty in between? If so, note that the terminal will behave slightly different w'o a pty.

**Comment by MohamedElgharbawy** [comment]
I have not implemented a backend yet, but I would use something like flask. However, I'm simply trying to finish the front-end at the moment, so I'm very confused as to why this is only happening on MacOS.

**Comment by jerch** [comment]
Maybe try `options.logLevel = 'debug'`, it will show the data sent or received in console.log.

**Comment by jerch** [comment]
Cannot repro it in Mojave either (with Safari).

**Comment by MohamedElgharbawy** [comment]
Upon talking with others, it seems pressing two keys at once repeatedly causes this error. Reproduced on MacOS, Linux, and Windows. Any idea how to prevent this?

**Comment by MohamedElgharbawy** [comment]
In fact, doing this can make it really bad:
![](https://user-images.githubusercontent.com/30507689/72571554-c9ba1a00-3874-11ea-8c70-8969a2ba747e.png)

**Comment by jerch** [comment]
> Upon talking with others, it seems pressing two keys at once repeatedly causes this error. Reproduced on MacOS, Linux, and Windows. Any idea how to prevent this?

I cannot repro that either lol. Can you check if this also happens in our demo? Just run `cat` in the demo terminal and test for the double key thingy. Does this only happen on your machine?

**Comment by MohamedElgharbawy** [comment]
Doesn't happen in your demo, but I have reproduced it on 3 different machines.

**Comment by jerch** [comment]
Can you show the code dealing with the key strokes up to writing stuff back to the terminal?

**Comment by MohamedElgharbawy** [comment]
```js
<!doctype html>
<html>

<head>
	<title>Mohamed Elgharbawy</title>
	<link rel="stylesheet" href="xterm/css/xterm.css" />
	<script src="xterm/lib/xterm.js"></script>
	<script src="xterm-addon-fit/lib/xterm-addon-fit.js"></script>

	<!-- Favicons -->
	<link href="img/m.png" rel="icon">
	<link href="img/m.png" rel="apple-touch-icon">
</head>

<body>
	<div id="terminal"></div>
	<script>
		var term = new Terminal({
			cursorBlink: "block"
		});

		var curr_line = '';
		var entries = [];
		var currPos = 0;
		var pos = 0;

		term.open(document.getElementById('terminal'));
		term.prompt = () => {
			term.write('\n\r' + curr_line + '\r\n\u001b[32mscm> \u001b[37m');
		};
		term.write('Welcome to my Scheme web intepreter!');
		term.prompt();

		term.onKey(function(ev) {
			console.log(ev.domEvent.code);
			console.log(ev);
			const printable = !ev.altKey && !ev.altGraphKey && !ev.ctrlKey && !ev.metaKey &&
				!(ev.domEvent.code === "ArrowLeft" && term.buffer.cursorX < 6);

			if (ev.domEvent.code === "Enter") { // Enter key
				if (curr_line.replace(/^\s+|\s+$/g, '').length != 0) { // Check if string is all whitespace
					entries.push(curr_line);
					currPos = entries.length - 1;
					term.prompt();
				} else {
					term.write('\n\33[2K\r\u001b[32mscm> \u001b[37m');
				}
				curr_line = '';
			} else if (ev.domEvent.code === "Backspace") {
				if (term.buffer.cursorX > 5) {
					curr_line = curr_line.slice(0, term.buffer.cursorX - 6) + curr_line.slice(term.buffer.cursorX - 5);
					pos = curr_line.length - term.buffer.cursorX + 6;
					term.write('\33[2K\r\u001b[32mscm> \u001b[37m' + curr_line);
					term.write('\033['.concat(pos.toString()).concat('D')); //term.write('\033[<N>D');
					if (term.buffer.cursorX == 5 || term.buffer.cursorX == curr_line.length + 6) {
						term.write('\033[1C');
					}
				}
			} else if (ev.domEvent.code === "ArrowUp") {
				if (entries.length > 0) {
					if (currPos > 0) {
						currPos -= 1;
					}
					curr_line = entries[currPos];
					term.write('\33[2K\r\u001b[32mscm> \u001b[37m' + curr_line);
				}
			} else if (ev.domEvent.code === "ArrowDown") {
				currPos += 1;
				if (currPos === entries.length || entries.length === 0) {
					currPos -= 1;
					curr_line = '';
					term.write('\33[2K\r\u001b[32mscm> \u001b[37m');
				} else {
					curr_line = entries[currPos];
					term.write('\33[2K\r\u001b[32mscm> \u001b[37m' + curr_line);

				}
			} else if (printable && !(ev.domEvent.code === "ArrowRight" && term.buffer.cursorX > curr_line.length + 4)) {
				if (ev.domEvent.code != "ArrowLeft" && ev.domEvent.code != "ArrowRight") {
					var input = ev.key;
					if (ev.domEvent.code == "Tab") {
						input = "    ";
					}
					if (term.buffer.cursorX === curr_line.length + 5) { // End of line
						pos = curr_line.length - term.buffer.cursorX + 4;
					} else {
						pos = curr_line.length - term.buffer.cursorX + 5;
					}
					curr_line = [curr_line.slice(0, term.buffer.cursorX - 5), input, curr_line.slice(term.buffer.cursorX - 5)].join('');
					term.write('\33[2K\r\u001b[32mscm> \u001b[37m' + curr_line);
					term.write('\033['.concat(pos.toString()).concat('D')); //term.write('\033[<N>D');
				} else {
					term.write(ev.key);
				}
			}

		});

	</script>
</body>

</html>
```

**Comment by jerch** [comment]
Is there a specific reason why you directly use `onKey` instead of `onData`?

**Comment by MohamedElgharbawy** [comment]
I was having trouble converting my code to use onData, onKey seemed a bit easier. Specifically, I was struggling to find the ev codes using onData. I'll be happy to convert it if you can tell me how to find the ev codes, and I can let you know if it fixed it.

**Comment by jerch** [comment]
If you switch logLevel to 'debug' you'll get the `onData` content in console.log. Just press the keys you want to handle (e.g. pressing 'a' will give you an 'a', pressing ENTER will give you '\r' and so on). In general normal keys will give you the character, F-keys and arrow-keys will send a terminal sequence.

**Comment by MohamedElgharbawy** [comment]
How do I switch the logLevel to debug?

**Comment by jerch** [comment]
Either as ctor option `new Terminal({logLevel: 'debug'})` or with `term.setOption('logLevel', 'debug')`.

**Comment by MohamedElgharbawy** [comment]
When I do `term.setOption('logLevel', 'debug'`, I get a blank line in the console for enter and backspace. Do you know what the backspace character is?

**Comment by jerch** [comment]
Imho the debug log should print the byte values, too. Backspace defaults to DEL, which is 0x7F.

**Comment by MohamedElgharbawy** [comment]
How would I check that though? For example, if I want to check if enter was pressed, I do `ev === "\r"`. What would the equivalent be for backspace?

**Comment by jerch** [comment]
`s === '\x7F'` should work as equality check.

**Comment by MohamedElgharbawy** [comment]
Before, at the end, I was writing ev.key to prevent the arrow keys from printing their values. How would I do that now that I'm using `onData`?

**Comment by MohamedElgharbawy** [comment]
Also, converting everything to `onData` did not fix the cursor lag issue.

**Comment by jerch** [comment]
Now that you are using `onData` - try to repro the terminal output from the data logged in the console (maybe step debug it).

**Comment by Tyriar** [comment]
> That's not what I am referring to. I am aware of the cursor going to the beginning of the line. What I am talking about is if you type very fast, the cursor will lag one position behind.

Here's what is written when it reproduces:

```
[32mscm> [37msadasd[-1D
[32mscm> [37msadassd[0D
```

The second line moves the cursor 1 space to the left. As I suggested earlier, removing this line fixes that:

```
term.write('\033['.concat(pos.toString()).concat('D')); //term.write('\033[<N>D');
```

**Comment by Tyriar** [comment]
If you're wondering why this is happening, it's because write happen asynchronously but you're expecting `term.buffer.cursorX` to be "up to date", so when you do 2 key events before a parse event has happened it will end up using a stable cursorX value.

Recommendation:

- I don't know what it's meant to do, but you should avoid using the buffer API in `onData` (or `onKey`).
- Keep a separate representation of the world like a shell would if it was run in xterm.js, only communicate to xterm.js from your "process" via the `write` and `onData` APIs (ie. you're communicating purely over a 2 directional pipe).
- If you really want to use `cursorX`, the latest version of the API has a callback which lets you know when writes have finished being parsed which means cursorX would be up to date. https://github.com/xtermjs/xterm.js/blob/fbeb45d1da9960cb9ebb0fea56882128696a254b/typings/xterm.d.ts#L702-L710

**Comment by MohamedElgharbawy** [comment]
How would I fix this bug using the third option, as it seems the simplest? What would I pass in for the callback parameter?

**Comment by jerch** [comment]
Option 3 is not simplest one here, as it requires knowledge about internals like async/sync behavior of different API parts, which is not officially documented (and thus not reliable / might change in future versions). I suggest not to use it.

Maintaining your own "view" is the way to go, strictly going through the I/O pipes:
- read data with `onData`, update your view (incl. your own cursor), decide, what to do, e.g. cursor should move to xy for some reason, then
- use `term.write` to update the cursor in xterm.js as well

**Comment by Tyriar** [comment]
@MohamedElgharbawy you shouldn't do option 3, but you would need to learn about async programming in node if you wanted to use callback in write.

**Comment by MohamedElgharbawy** [comment]
@Tyriar Then what would you recommend? The only reason why I'm going through all this trouble is because I want the user to be able to write in the middle of the line, while keeping their cursor there instead of moving it to the end.

**Comment by Tyriar** [comment]
@MohamedElgharbawy by emulating what a shell does by keeping a "local" model and only communicating over the pipes. And then reacting when the terminal is resized.
