### ISSUE TITLE
Multiple DOM rendered instances will lose the cursor theme

### ISSUE THREAD

**Issue by rj0n3s** [xtermjs/xterm.js#2674]
This is a minor issue, but should be relatively easy to correct.
While great care has gone into namespacing style rules for multiple xterm instances, one small detail has been overlooked.
The problem is that all CSS keyframe animation rules share the same `blink_block` name.
Because of this, all instances will share the last defined keyframe rule so that every instance will have the same cursor color regardless of theme.

The following excerpt from an xterm generated style block illustrates the problem.

```
<style>
@keyframes blink_block { 
    0% {  
        background-color: rgba(255, 255, 0, 1);
        color: rgba(0, 94, 0, 1);
    }
    50% {  
        background-color: rgba(0, 94, 0, 1);
        color: rgba(255, 255, 0, 1);
    }
}

...

.xterm-dom-renderer-owner-1 .xterm-rows.xterm-focus .xterm-cursor.xterm-cursor-blink.xterm-cursor-block { 
    animation: blink_block 1s step-end infinite;
}
</style>
```

Instead, you may consider just concatenating the integer used to uniquely identify the render owner to the end of the keyframe rule name as follows.

```
<style>
@keyframes blink_block_1 { 
    0% {  
        background-color: rgba(255, 255, 0, 1);
        color: rgba(0, 94, 0, 1);
    }
    50% {  
        background-color: rgba(0, 94, 0, 1);
        color: rgba(255, 255, 0, 1);
    }
}

...

.xterm-dom-renderer-owner-1 .xterm-rows.xterm-focus .xterm-cursor.xterm-cursor-blink.xterm-cursor-block { 
    animation: blink_block_1 1s step-end infinite;
}
</style>
```

My thanks to all contributors for the excellent work going into this project.

Take care

## Details
- Browser and browser version: Any
- OS version:  Any
- xterm.js version:  4.3.0

### Steps to reproduce

1.  Create multiple DOM rendered xterm.js instances within the same HTML document.
2.  Assign different themes to each instance, specifically cursor and cursorAccent.
3.  Transfer focus between the different instances to see the cursor color remains the same as the last one defined.

**Comment by rj0n3s** [comment]
## Possible Solution:
**/src/browser/renderer/dom/DomRenderer.ts  :  174**

```
    // Blink animation
    styles +=
        `@keyframes blink_box_shadow` + `_` + this._terminalClass + ` {` +
        ` 50% {` +
        `  box-shadow: none;` +
        ` }` +
        `}`;
    styles +=
        `@keyframes blink_block` + `_` + this._terminalClass + ` {` +
        ` 0% {` +
        `  background-color: ${this._colors.cursor.css};` +
        `  color: ${this._colors.cursorAccent.css};` +
        ` }` +
        ` 50% {` +
        `  background-color: ${this._colors.cursorAccent.css};` +
        `  color: ${this._colors.cursor.css};` +
        ` }` +
        `}`;
```

**Comment by Tyriar** [comment]
Good find 😃
