### ISSUE TITLE
Public API -- typings are inconsistent with implementation

### ISSUE THREAD

**Issue by corwin-of-amber** [xtermjs/xterm.js#2675]
The `colors` option is no longer available. Colors are now managed by the `ColorManager`. (Is there a public API for it?)
https://github.com/xtermjs/xterm.js/blob/f7d36a670c7655638d6642dde4573b804e524918/src/public/Terminal.ts#L147

**Comment by kumaran-14** [comment]
@Tyriar Can I work on this? How would you like me to refactor it?

**Comment by Tyriar** [comment]
@kumaran-14 I'll tackle this one as I want to try do a release today or tomorrow. Issues with [help wanted and no milestone ](https://github.com/xtermjs/xterm.js/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Amilestone) are good to pick up as they aren't time critical.
