### ISSUE TITLE
Display corrupted in Tor browser

### ISSUE THREAD

**Issue by wibud** [xtermjs/xterm.js#2686]
It display corrupted in Tor browser

![image](https://user-images.githubusercontent.com/3693897/73709339-c3b0ae00-473b-11ea-96e2-c2683bb540b1.png)

## Details

- Browser and browser version: 

![image](https://user-images.githubusercontent.com/3693897/73709371-d9be6e80-473b-11ea-939a-1834b540eda5.png)

- OS version: 

![image](https://user-images.githubusercontent.com/3693897/73709435-0c686700-473c-11ea-84b0-89ad5bc0e89b.png)

- xterm.js version: 4.3.0

**Comment by Tyriar** [comment]
I guess the Tor browser doesn't support canvas properly? Change rendererType to dom will probably fix, no plans on actioning this.

**Comment by hexagonrecursion** [comment]
Canvas work just fine in tor browser except that one feature (image extraction) is intentionally blocked to prevent fingerprinting https://2019.www.torproject.org/projects/torbrowser/design/#fingerprinting-linkability:

> HTML5 Canvas Image Extraction
>
> After plugins and plugin-provided information, we believe that the HTML5 Canvas is the single largest fingerprinting threat browsers face today. Studies show that the Canvas can provide an easy-access fingerprinting target: The adversary simply renders WebGL, font, and named color data to a Canvas element, extracts the image buffer, and computes a hash of that image data. Subtle differences in the video card, font packs, and even font and graphics library versions allow the adversary to produce a stable, simple, high-entropy fingerprint of a computer. In fact, the hash of the rendered image can be used almost identically to a tracking cookie by the web server.

This leads to many websites that use xterm.js being broken. It would be great if xtem.js worked fine in tor browser by default.

Firefox also has this feature, but it is currently experimental and is off by default:
https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting

**Comment by Tyriar** [comment]
Reading canvas image data is critical to how both the canvas and webgl renderers work. Looks like you'll have to use the DOM renderer or click allow:

```ts
new Terminal({
  rendererType: 'dom'
});
```

This will be the default in v5 https://github.com/xtermjs/xterm.js/issues/3271, allowing embedders to upgrade to the faster implementations and handle falling back.
