### ISSUE TITLE
Clickable links in the terminal no longer work.

### ISSUE THREAD

**Issue by MohamedElgharbawy** [xtermjs/xterm.js#2701]
## Details
- Browser and browser version: All browsers
- OS version: MacOS 10.15.1
- xterm.js version: Latest

### Steps to reproduce

1. term.write("https://google.com");
2. The link will appear in the terminal but will not be clickable or underlined.

**Comment by jerch** [comment]
@MohamedElgharbawy Cannot repro with linux, works here with Chrome (v79) and Firefox (v72).

**Comment by MohamedElgharbawy** [comment]
I'm on version 4.3.0, if that helps.

**Comment by jerch** [comment]
Also works for me with v4.3.0. Plz test with our demo in the master branch and see if the issue remains.

**Comment by Tyriar** [comment]
Links definitely work in both 4.3 and 4.4 as they're working in vscode now and have been. Links don't come out of the box if it wasn't clear, you need to enable the web links addon to get that functionality.
