### ISSUE TITLE
Add debug option to API tests

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2702]
I find it very useful when debugging API tests to log the result of polling:

https://github.com/xtermjs/xterm.js/blob/56990f2a2904f1d8b5f868be9ce14895b2156c8f/test/api/TestUtils.ts#L13

Would be handle to run `yarn test-api --debug` to log this instead of changing it locally.

**Comment by kumaran-14** [comment]
@Tyriar I'd like to take this up. Where would the extra flag `--debug` be handled?
And what would the change in the file you've mentioned?

**Comment by Tyriar** [comment]
@kumaran-14 we probably need a script to wrap mocha, say `./bin/test_api.js` which sets a `DEBUG` environment variable and launches mocha? Follow that line with something like:

```ts
if (process.env.DEBUG) {
  console.log('pollFor result', result);
}
```

**Comment by kumaran-14** [comment]
@Tyriar I have a hard time understanding this. Could you please elaborate more?
Thanks in advance. And sorry for not responding sooner.

**Comment by Tyriar** [comment]
@kumaran-14 there is a `./bin/test.js` which we use to wrap the unit tests, the script would basically just set `process.env.DEBUG` if `--debug` is passed in and then launch mocha. Then if `process.env.DEBUG` is set we should log something like this

```ts
if (process.env.DEBUG) {
  console.log('poll result', result);
}
```

Here:

https://github.com/xtermjs/xterm.js/blob/56990f2a2904f1d8b5f868be9ce14895b2156c8f/test/api/TestUtils.ts#L13
