### ISSUE TITLE
Link Provider end positions are incorrect

### ISSUE THREAD

**Issue by jmbockhorst** [xtermjs/xterm.js#2708]
The current `WebLinksProvider` incorrectly calculates the end position of the link. They are 1 character longer than it should be for both `hover()` and `leave()`. 

I also noticed a situation when implementing VS Code's link provider, that only the `leave()` is being called on that extra character. So there may be bugs in both the `LinkProvder` API and the `WebLinksProvider`, but I am not sure.

**Comment by Tyriar** [comment]
I probably caused this with https://github.com/xtermjs/xterm.js/pull/2530/commits/0103c689f7966c4909f51855b90053bdfe15d4cb (https://github.com/xtermjs/xterm.js/issues/2706)
