### ISSUE TITLE
Merge ligatures addon into core repo

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2726]
The thinking changes from having separate addon repos to just including them all in one to simplify development and releasing. The ligatures addon also keeps having regressions, we should pull https://github.com/xtermjs/xterm-addon-ligatures into `addons/xterm-addon-ligatures`.

It should be relatively easy to pull the code over by following existing patterns established by the other addons.

**Comment by LabhanshAgrawal** [comment]
I want to give it a try, can you mention any pr for some other addon which I can refer.

**Comment by Tyriar** [comment]
@LabhanshAgrawal they would probably be stale at this point. If you want to tackle this you should first move the ligatures folder into `addons/xterm-addon-ligatures/`, adjust config files, get it building and then search other addon names to find where things need to be adjusted. For example:

![image](https://user-images.githubusercontent.com/2193314/79251077-8bf96d00-7e34-11ea-89b9-91e13115ce06.png)

**Comment by LabhanshAgrawal** [comment]
Got it. Will give it a try.
