### ISSUE TITLE
Flaky integration test in CI

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2727]
The new integration test for registering a link provider does not return in time for macOS:

```
  1) API Integration Tests
       registerLinkProvider
         should fire activate events when clicking the link:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/runners/2.165.0/work/1/s/out-test/api/Terminal.api.js)
```

Code: https://github.com/xtermjs/xterm.js/blob/708c6bdeb81d5fa063d5090dac9a47eb531f35d7/test/api/Terminal.api.ts#L616-L661

**Comment by Tyriar** [comment]
I think this is fixed, haven't seen it recently.

**Comment by Tyriar** [comment]
Nevermind, this happened when I tried to release

**Comment by jerch** [comment]
@Tyriar Yeah no clue what going on, its even flakey in failing, happens like once in 5 to 10 runs. Its a little princess ;)

**Comment by Tyriar** [comment]
Happened twice in a row for the release actually, had me worried for a sec.

**Comment by Tyriar** [comment]
Hoping this is fixed now that I bumped the timeout 200ms from 50ms. Not a proper fix but there's a warning in the test that polling for something wasn't good enough 😕

**Comment by Tyriar** [comment]
Haven't seen this in a while.
