### ISSUE TITLE
Link exchange

### ISSUE THREAD

**Issue by jcubic** [xtermjs/xterm.js#2733]
I think that Xterm.js and [jQuery Terminal](https://terminal.jcubic.pl/) are two most popular JS libraries that add terminal feature to web pages. They are overlapping in functionality but are used for different purpose.

So my question is do you want to exchange links (it will be better for SEO and users will easier find exact projected they need). I've already been asked few times, how to do something with my library and in fact what user want was xterm.js, that's why I sent them to your project.

My idea is that you on your site you will put link to my project (main website not github) and write when user would like to use my library instead of xterm.js, like when

* he have JS library of any language or interpreter
* want to add quick interface to REST API
* use GitHub pages or any service without backend (like netlify) or shared hosting that don't allow to run a process in background
* want to create terminal like portfolio (lot of users use my library for that)

if someone have any of those cases, he really want jQuery Terminal instead of xterm.js. My library have limited suport for Unix ANSI codes etc. but this is limited, this is usualy when one can't spawn own server.

I will do the same on my project website, if someone will really want to run vi or emacs or have interactive app written in C and want interface to it, it will be easier to use xterm.js. The same if someone plan to get the server (he can pick VPS) and want real terminal. I can write anything you want on my website with a link to your project home page.

What you think?

**Comment by Tyriar** [comment]
Sorry I'd rather not get involved with link exchanges, we'd be happy to link in the showcase though if you change your frontend to use xterm.js.
