### ISSUE TITLE
Selection color with transparency is black in Legacy Edge

### ISSUE THREAD

**Issue by felixse** [xtermjs/xterm.js#2736]
When using a color with transparency for selection the color is rendered black in Legacy Edge. Chromium based browsers are not affected.

## Details
- Browser and browser version: Microsoft EdgeHTML 18.18363
- OS version: Windows 10 1909
- xterm.js version: 4.4.0

### Steps to reproduce

1. Add `term.setOption("theme", { selection: "rgba(255, 0, 255, 0.5)" });` to the demo
2. Select text in Legacy Edge

**Comment by Tyriar** [comment]
@felixse does this happen in both canvas and dom renderers?

**Comment by felixse** [comment]
This happened in the canvas renderer. Just retried with dom and it's displaying no visible selection instead.
