### ISSUE TITLE
Rendering issue on input events when using RTL

### ISSUE THREAD

**Issue by andersevenrud** [xtermjs/xterm.js#2743]
Hi,

I'm having a really strange issue with xterm when using the `direction: rtl` CSS style (or `dir` HTML attribute) anywhere in my layout.

This is most likely related to https://github.com/xtermjs/xterm.js/issues/1330 that was fixed.

On certain input events the terminal moves outside the viewport in the rightward direction even though the actual Terminal root DOM element is inside another element that is **absolutely** positioned (this also occurs with `static` position).

Changing the elements position to **fixed** seems to fix this behavior. While live debugging this in devtools I noticed that disabling *both* the `-9999<unit>` rules (on `.xterm-helper-textarea` and `.xterm-char-measure-element`), then re-enabling them sort of kicks it back into the original position again.

If this isn't a bug in xterm maybe someone could enlighten me as to what's going on here or maybe point out something I did wrong :slightly_smiling_face: 

## Details

- Browser and browser version: Chrome 80, Firefox 73, Edge 18
- OS version: Arch Linux, Windows 10
- xterm.js version: 4.4.0

### Steps to reproduce

Using https://codesandbox.io/s/confident-poincare-4udf0 this can be reproduced in the following ways:

#### Chrome

Click the terminal with mouse and press space key.

#### Firefox and Edge

Click the terminal with mouse (it might take a few clicks).

**Comment by Tyriar** [comment]
This is https://github.com/xtermjs/xterm.js/issues/2598 as the testing page is super wide due to this css:

https://github.com/xtermjs/xterm.js/blob/ae135ac181b080fce0a13853c19a768c973cc4be/css/xterm.css#L61-L68

Adding this prevents it from happening which proves this:

```css
.xterm .xterm-helper-textarea {
  left:0em !important;
}
```

**Comment by andersevenrud** [comment]
Indeed, that seems to solve the issue. Thanks :)
