### ISSUE TITLE
DECSTR handling corrupts screen

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#2745]
It seems that although the default behaviour for DECSTR is to reset cursor position, other terminals (xterm, macOS terminal, gnome-terminal) don't do this. In particular, GNU screen issues DECSTR before going into alternate screen mode, and after returning from it, the cursor ends up in 0;0, writing over old screen contents. Here's an output dump from an actual GNU screen in-and-out (JS string, can be fed straight into xterm):

```"    root@gpu-box:~# screen -x\r\n\u001b[!p\u001b[?3;4l\u001b[4l\u001b>\u001b[?1049h\u001b[22;0;0t\u001b[4l\u001b[?1h\u001b=\u001b[0m\u001b(B\u001b[1;40r\u001b[H\u001b[2J\u001b[H\u001b[2Jroot@gpu-box:~#\r\nroot@gpu-box:~# l\r\n1.py  \u001b[1m\u001b[35mkitten.jpg\u001b[2C\u001b[34mNVIDIA_CUDA-10.1_Samples\u001b[0m/\r\nroot@gpu-box:~# \r\u001b[36B\u001b[7mReally kill this window [y/n]\u001b[27m\u001b[K\r                                                                                                                                       \u001b[4;20H\u001b[?1l\u001b>\u001b[40;1H\r\n\u001b[?1049l[screen is terminating]\r\nroot@gpu-box:~# "```

Here's a simple repro: 

```
"one \u001b[!p \u001b[?1049h \u001b[?1049l two"
```

**Comment by Eugeny** [comment]
Here's related xterm source where they only reset cursor for RIS, not DECSTR: https://github.com/joejulian/xterm/blob/defc6dd5684a12dc8e56cb6973ef973e7a32caa3/charproc.c#L9885

**Comment by jerch** [comment]
@Eugeny Yes DECSTR (and RIS as well) is still off compared to other emulators (as I found out in the sequence docs PR). The issue at hand though seems to be derived from the official VT docs, which states to reset the cursor to home position (https://vt100.net/docs/vt510-rm/DECSTR.html). I have not yet looked into it, maybe we miss a cursor restore call somewhere along DECSTR / buffer switch?

**Comment by Eugeny** [comment]
It seems that at least GNU Screen doesn't save cursor position until after DECSTR.

**Comment by jerch** [comment]
Oh well, seems the docs were interpreted wrong in this regard. Looking at DEC STD 070 it clearly states:
> DECSTR has no affect on the Active Position.

Regarding the cursor DECOM and DECSC are reset, I guess DECSC got misinterpreted as resetting the active cursor position. But it should only reset the values stored in the cursor save structure to the home position (thus a following DECRC would move the cursor to home).

**Comment by jerch** [comment]
@Eugeny Should be fixed in #2746.
