### ISSUE TITLE
Upgrade to target ES6

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2748]
VS Code just dropped IE11 support so it could target ES6. I suggest we do the same which makes Old Edge v18 the low bar: https://github.com/microsoft/vscode/issues/90676

This would mean cutting IE11 support completely which could cause problems for some clients so we'll target v5 as this will make IE11 incompatible with the lib.

**Comment by TomzBench** [comment]
@Tyriar Is there a workaround to import xterm as an es6 module.

This works ok for building. But my dev environment does not do any bundling. Tools like snowpack, webdevserver and etc serve es6 module directly. But this module cannot import into this environment.

**Comment by TomzBench** [comment]
@Tyriar 

I added a tsconfig.es6.json overlay that builds the codebase as an es6 module and bundles with rollup. It doesn't touch the codebase and only adds extra tsconfig build files. So it's like a parallel build setup...  If interested i can submit a PR and we can figure out way to publish it adjacent to the regular build.

https://github.com/TomzBench/xterm.js

**Comment by jogibear9988** [comment]
@Tyriar @TomzBench 
I've exactly the same problem. I don't do any bundling, so I cannot use this in browser. ES& import does not work, but also loading via script tag does not, cause it checks for existence of "define" and this is here cause of monaco editor.

You could also add an additional es6 build to the package.json

**Comment by jogibear9988** [comment]
https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper

**Comment by Tyriar** [comment]
duplicate of https://github.com/xtermjs/xterm.js/issues/2878
