### ISSUE TITLE
TypeError: Cannot read property 'onLinkHover' of undefined

### ISSUE THREAD

**Issue by UziTech** [xtermjs/xterm.js#2759]
xterm-addon-webgl@latest (v0.5.1) does not work with xterm@latest (v4.4.0)

it throws error `TypeError: Cannot read property 'onLinkHover' of undefined` because xterm v4.4.0 does not have linkifier2 property on the terminal.

I think xterm-addon-webgl@0.5.1 was meant to be released as v0.6.0-beta.4

**Comment by UziTech** [comment]
@Tyriar is webgl supposed to work with xterm v4.4?

**Comment by coderaiser** [comment]
I have the same issue, this is how I use `xterm-addon-webgl`:

```js
const {WebglAddon} = require('xterm-addon-webgl');
const {Terminal} = require('xterm');

const webglAddon = new WebglAddon();
const terminal = new Terminal({
    scrollback: 1000,
    tabStopWidth: 4,
});

terminal.open(document.body);
terminal.loadAddon(webglAddon);
```

On the last line I have:

```js
xterm-addon-webgl.js:1 Uncaught TypeError: Cannot read property 'onLinkHover' of undefined
    at new e (xterm-addon-webgl.js:1)
    at new e (xterm-addon-webgl.js:1)
    at t.activate (xterm-addon-webgl.js:1)
    at e.loadAddon (xterm.js:1)
    at e.loadAddon (xterm.js:1)
```

**Comment by Tyriar** [comment]
I think this happened because of an oversight by bumping the version in https://github.com/xtermjs/xterm.js/commit/db304513b19ebd7ebd08abd020999cb7cea4bafe

xterm-addon-webgl@0.5.1 is _not_ compatible with xterm@0.4.0 so use 0.5.0 for now. I'll make a note on the releases page: https://github.com/xtermjs/xterm.js/releases

**Comment by Tyriar** [comment]
FYI @jerch

**Comment by jerch** [comment]
@Tyriar How could this happen? Only made a small bugfix in private code not touching any API stuff. Pending previous changes? I was not aware, that bugfix version jumps would publish on its own, sorry for that.

**Comment by Tyriar** [comment]
@jerch master moved on from 4.4 and I think webgl may have adopted internal naming changes since? Yep, bumping any addon versions will automatically publish, just like the main package.json.

**Comment by UziTech** [comment]
Looks like this is still an issue in v0.6.0 even though the changelog says they are compatible.

https://github.com/xtermjs/xterm.js/releases/4.5.0

**Comment by Tyriar** [comment]
@UziTech phew, had me worried for a second 😄
