### ISSUE TITLE
All theme colors not supported

### ISSUE THREAD

**Issue by Ph0enixKM** [xtermjs/xterm.js#2763]
I wanted to apply custom theme but it seems that it's not possible for this version. In my opinion it seems to be some kind of bug. What I did in code is:
- set foreground color to `#0FF` (which is the cyan color - **good**)
- set green color to `#F00` (which is supposed to turn into red but it's still green - **bad**)

![Untitled](https://user-images.githubusercontent.com/29208124/76790275-d39dc200-67be-11ea-8bc0-fdfb7e8a42e7.jpg)

## Details
- Browser and browser version: **Electron version 8.1.1**
- OS version: **Ubuntu 19.04**
- xterm.js version: **4.4.0**

### Steps to reproduce

Code:
```js
const xterm = new Terminal({
    cols: 80,
    rows: 30,
    theme: {
        foreground: '#0FF',
        green: '#F00'
    }
})

xterm.open(xtermElem)
```
_( I have tried the same thing on just **electron + xtermjs** but still that didn't work. )_

**Comment by Tyriar** [comment]
That's likely `brightGreen` as it's bold. Or you can set `drawBoldTextInBrightColors` to false.
