### ISSUE TITLE
Demo server: Risk of memory exhaustion.

### ISSUE THREAD

**Issue by hezedu** [xtermjs/xterm.js#2765]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 4.4.0

### Steps to reproduce

https://github.com/xtermjs/xterm.js/blob/9c19043fed27c5666a58aa110620b5488914bc76/demo/server.js#L52-L55
Bind data event when term is created, 
nerver unbind. 
Log will continue to grow when term runing.

**Comment by jerch** [comment]
@hezedu The demo in the repo is not meant to be used as a blueprint for real world integrations, it is only meant for internal development and testing. The code in question helps to level out latency issues during pty spawn and xterm.js bootstrapping during test runs, nothing that should be copied over to a real world application.
Note that the demo has multiple serious issues:
- no flow control, another source of OOM (see https://xtermjs.org/docs/guides/flowcontrol/)
- lack of security measures (see https://xtermjs.org/docs/guides/security/)
- no clever chunk buffering (the buffering is just a quick hack to reduce the websocket callback pressure)

Thus, don't use the demo as a blueprint by simply copying things over to your application. For a real application you should implement all 3 aspects above to your needs.

Nonetheless - thx for reporting.

@Tyriar Should we rename `demo` to something else (e.g. `devel`)?

**Comment by Tyriar** [comment]
Well demo is short for demonstration which I think describes what it's trying to do. There's also this warning at the bottom of the page:

https://github.com/xtermjs/xterm.js/blob/9c19043fed27c5666a58aa110620b5488914bc76/demo/index.html#L47

I'll improve the message and add it to server.js as well such that a developer who wants to use server.js as a blueprint will have to read the warning.
