### ISSUE TITLE
Windows Powershell resize

### ISSUE THREAD

**Issue by trungutt** [xtermjs/xterm.js#2798]
I made an Electron app using xterm.js to integrate a terminal. 

When the default terminal is Powershell, it doesn't resize correctly when maximizing/unmaximazing the windows. The same thing happened on [Hyper](https://github.com/zeit/hyper), or [Electerm](https://github.com/electerm/electerm) which use xterm internally.

When using other things than Powershell, like `cmd.exe`, that works fine.

## Details
- Browser and browser version: Chrome
- OS version: all Windows versions
- xterm.js version: latest version

### Steps to reproduce

1. Default shell to Powershell
2. Download and install Electerm on Windows (for example)
3. type `ls`
4. maximize the window (if it's not already maximized)
5. unmaximize the window
6. maximize the window
7. type `ls` and see that `ls` is not positioned correctly

Screen capture here:

![powershell resize](https://user-images.githubusercontent.com/18528548/77901518-03010400-7280-11ea-9921-2568a54be64f.gif)

**Comment by Tyriar** [comment]
> OS version: all Windows versions

What version of windows are you on? Type `ver` into cmd.

**Comment by mat007** [comment]
@Tyriar I’m on @trungutt’s team, I have the same issue, here is my Windows version
```
Microsoft Windows [Version 10.0.19592.1001]
```
I guess we’re all running Insider Rings versions on the team.

**Comment by Tyriar** [comment]
@mat007 does it happen when you try on [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab)? Also can you share your settings.json file?

**Comment by Tyriar** [comment]
Also how are you creating the pty backend?

**Comment by Tyriar** [comment]
https://github.com/electerm/electerm/blob/1f2d7b3ba83736e4a423567e454eb442d28db986/src/app/server/session.js#L135-L141

Try setting the `useConpty: true`.

**Comment by mat007** [comment]
> does it happen when you try on Windows Terminal?

As a matter of fact, it does! So I guess that means it’s a Powershell bug…

**Comment by Tyriar** [comment]
@mat007 if it repros in windows terminal is means it's a conpty bug. You should report to https://github.com/microsoft/terminal

**Comment by mat007** [comment]
Thanks @Tyriar 👍

**Comment by trungutt** [comment]
A bit late but thanks @Tyriar

**Comment by trungutt** [comment]
So I created another ticket on that https://github.com/microsoft/terminal/issues/5254
