### ISSUE TITLE
Change both text color & background color of selection

### ISSUE THREAD

**Issue by ScarlettKK** [xtermjs/xterm.js#2808]
It seems that I can only change the background color of selection layer, and the color should be translucent, or the text will be covered. 

But the selection effect is implicit:

![image](https://user-images.githubusercontent.com/47051897/78126096-8cf9ca00-7444-11ea-80a5-fb0df883b5df.png)

I want to achieve the following selection effect:

![image](https://user-images.githubusercontent.com/47051897/78126207-bf0b2c00-7444-11ea-979d-55681ae2aaee.png)

Are there any help? Thanks.

**Comment by Tyriar** [comment]
This is possible now but currently only by specifying the `minimumContrastRatio` setting, not by actually giving it a color to use:

https://github.com/xtermjs/xterm.js/blob/8b042caf6009db36a0324bb6c0ea0d40fab80e9a/typings/xterm.d.ts#L156-L166

**Comment by Tyriar** [comment]
Adding help wanted to add an optional `selectionForeground` theme key.

**Comment by ScarlettKK** [comment]
@Tyriar Thanks a lot about this, I tired to set `minimumContrastRatio` but it didn't work.

It seems that the `minimumContrastRatio` setting is for the text layer. When the text foreground color is almost as dark as the background color, increasing its contrast ratio can help make the text more obvious.

But it seems that the selection layer is a layer floating above the text layer, it has no relation with the foreground or background  color of the text layer.  So when a selection layer is added onto the text layer, it can't trigger the change of contrast ratio.

**Comment by ScarlettKK** [comment]
I think to solve this problem, the selection layer should be under the text, or we should copy the selected text onto it.

**Comment by ScarlettKK** [comment]
Sorry for I found my current xterm version is 3.14.5, so the `minimumContrastRatio` couldn't work. Let me do some update and try it again.

**Comment by ScarlettKK** [comment]
I tried the [demo](https://github.com/xtermjs/xterm.js/tree/master/demo) of version 4.4.0, but the selection effect still couldn't work with param `minimumContrastRatio`.

```typescript
term = new Terminal({
  windowsMode: isWindows,
  minimumContrastRatio: 21,
  theme: {
    selection: "#fff"
  }
}
```

The terminal:

![image](https://user-images.githubusercontent.com/47051897/78224165-9e9da900-74fa-11ea-8747-c16f2b35bd6e.png)

After select text "bash":

![image](https://user-images.githubusercontent.com/47051897/78224208-b2e1a600-74fa-11ea-8a99-da7b4531bb07.png)

The text is still covered under the selection layer.

**Comment by Tyriar** [comment]
> I think to solve this problem, the selection layer should be under the text, or we should copy the selected text onto it.

The selection layer is only under the text on the WebGL renderer, it's too hard to do in a performant way for canvas/dom.

> I tried the demo of version 4.4.0, but the selection effect still couldn't work with param minimumContrastRatio.

The minimumContrastRatio setting made some changes such that foreground text can now be dynamic, it might still be tricky to change on canvas/dom as I don't think the text layer knows anything about selection currently.

**Comment by ScarlettKK** [comment]
> The selection layer is only under the text on the WebGL renderer, it's too hard to do in a performant way for canvas/dom.

It means that copying the selected text onto selection layer has a poor performance? 

> I don't think the text layer knows anything about selection currently.

The selection layer might know which text is selected.

**Comment by Tyriar** [comment]
> It means that copying the selected text onto selection layer has a poor performance?

Text rendering is complicated and the way selection works for canvas/dom is it's completely separate, drawing 3 partially transparent rectangles.

> The selection layer might know which text is selected.

Of course it could get the text and the style information but that's a bunch of duplication and complexity being added there. Right now it's not the most straightforward task to do this in a nice way.

**Comment by ScarlettKK** [comment]
OK I see, hope there will be a suitable solution.
