### ISSUE TITLE
Add ability to change hard-coded HOVER_DURATION

### ISSUE THREAD

**Issue by Coding-Kiwi** [xtermjs/xterm.js#2822]
I'm using _xterm-addon-web-links_ and I configure a `tooltipCallback` in the `ILinkMatcherOptions`. I would like the callback to be triggered immediately when I hover, not after the hard coded 500ms defined [here](https://github.com/xtermjs/xterm.js/blob/7f598a36753f4d950ee63dc91bd6a92290f7e037/src/browser/MouseZoneManager.ts#L12)

There has been this pull request https://github.com/xtermjs/xterm.js/pull/1251 but I don't understand what the issue is here.

**Comment by Tyriar** [comment]
@Coding-Kiwi #1251 wasn't needed in the end as you could use the `willLinkActivate` event. It's a reasonable request to add this now though considering position is now passed to tooltip and it makes sense in the future [link provider](https://github.com/xtermjs/xterm.js/blob/e2ac4b45d0747ae3d6ab3eb1e3ba9be7cbdec351/typings/xterm.d.ts#L744-L750) world.

**Comment by Tyriar** [comment]
Well actually it's not forward looking as link providers doesn't even give you this event, just hover and leave and will let the embedder handle any timeout logic. Let's add this setting as we can always remove when link matchers are removed (https://github.com/xtermjs/xterm.js/issues/2703).

**Comment by Coding-Kiwi** [comment]
Oh okay, I suppose when link matchers are removed, the handler function handles all mouse events, not just click?

**Comment by Tyriar** [comment]
@Coding-Kiwi well you get hover and leave events so you should be able to handle the tooltip however you want. A little more code on your end but you get complete control over how it happens and looks, and a simpler API on our side.

**Comment by Coding-Kiwi** [comment]
@Tyriar Yeah I have no problem with that, I just wanted to ask how I'll get the events to implement tooltips on my side :)

**Comment by Tyriar** [comment]
@Coding-Kiwi this is the part of the API:

https://github.com/xtermjs/xterm.js/blob/e2ac4b45d0747ae3d6ab3eb1e3ba9be7cbdec351/typings/xterm.d.ts#L1115-L1134

You'll add functions for hover, leave and activate to the links themselves whenever you provide them, instead of doing it once like with link matchers.
