### ISSUE TITLE
Different behavior when search two same words in only one row

### ISSUE THREAD

**Issue by ScarlettKK** [xtermjs/xterm.js#2840]
## Details
- Browser and browser version: Chrome 81.0.4044.92
- OS version: Mac OS 10.13.6 
- xterm.js version: 4.4.0

### Steps to reproduce
I find `findNext` in `SearchAddon` behaves differently when search two same words in only one row.

1. As the picture below, when I am searching the word `bash` and press the `Enter` button, the highlight mark will start from the first(1) position to the next(2) position, then stop at the position 2 and never go back to position 1.

![image](https://user-images.githubusercontent.com/47051897/79199969-55d5e080-7e68-11ea-86c8-d025dc7e2cfa.png)

2. But when I am searching in multi rows(pressing the `Enter` button), the highlight mark will go 1->2->3->4->5->1->2... as a circle.

![image](https://user-images.githubusercontent.com/47051897/79200549-312e3880-7e69-11ea-9fea-35b27b78c37c.png)

Although users seldom search in only one row but the different behavior makes it a little bit strange.

**Comment by ScarlettKK** [comment]
I find the `startCol` variable never change when search only one row. 

![image](https://user-images.githubusercontent.com/47051897/79201624-f200e700-7e6a-11ea-972f-773331578dda.png)

It's relative with these code in `SearchAddon.ts`:

![image](https://user-images.githubusercontent.com/47051897/79201738-178df080-7e6b-11ea-9d42-ebdba960b37e.png)

**Comment by rishab-pdx** [comment]
@Tyriar I would like to take this. I believe we must wrap back search for starting column just as we do it in other cases.

**Comment by rishab-pdx** [comment]
#2867

**Comment by rishab-pdx** [comment]
#2867

**Comment by rishab-pdx** [comment]
PR https://github.com/xtermjs/xterm.js/pull/2867
