### ISSUE TITLE
Link provider probably needs to change to provide links for entire line

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2848]
Consider the following:

![image](https://user-images.githubusercontent.com/2193314/79397999-66538d00-7f34-11ea-82bb-e75d19c329ca.png)

Currently in VS Code, depending on which cell you focus first gives a different link.

Good (validated local link provider):

![image](https://user-images.githubusercontent.com/2193314/79398041-81be9800-7f34-11ea-86b4-3071da64b0a9.png)

Bad (word link provider):

![image](https://user-images.githubusercontent.com/2193314/79398027-7a978a00-7f34-11ea-8026-229fde62feb0.png)

fyi @jmbockhorst

**Comment by jmbockhorst** [comment]
So it would look something like this?
``` typescript
provideLink(bufferLineNumber: number, callback: (link: ILink | undefined) => void): void;
```

**Comment by Tyriar** [comment]
Yes but multiple returned:

```ts
provideLinks(bufferLineNumber: number, callback: (links: ILink[] | undefined) => void): void;
```

Also when I was looking into https://github.com/xtermjs/xterm.js/issues/2849 I noticed that right now in vscode we're using `leave` like a `dispose`, which is good as xterm drops the link reference when leaving the cell range. But if we did this with the `provideLinks` idea then we would want to differentiate `leave?(event: MouseEvent, text: string): void;` and `dispose?(): void` so xterm owns the decision of when to get rid of it (leave = it may get reused, dispose = embedder should drop the ref).

**Comment by Tyriar** [comment]
I don't really see another way of fixing this problem of competing providers creating different links based on what is hovered, which leads to an inconsistent experience.

**Comment by Tyriar** [comment]
This isn't actually fixed yet, we need to delete links that are "below" higher priority links still.
