### ISSUE TITLE
Link provider hover doesn't go away when mouse leaves xterm element or document

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2849]
Mouse is within editor:

![image](https://user-images.githubusercontent.com/2193314/79465844-b1ab8100-7fb0-11ea-9551-1a58472c2149.png)

Can also happen when mousing out of the document quickly.

**Comment by jmbockhorst** [comment]
This doesn't seem reproducible to me after the latest changes in xterm and vscode.

**Comment by Tyriar** [comment]
I've done a bunch of work around this and there's still a WIP PR out https://github.com/microsoft/vscode/pull/95608

For leaving the xterm element I fixed it in https://github.com/xtermjs/xterm.js/pull/2852, I'm currently still working through an issue where the link in sticky when the mouse leaves the document though which looks like it could get fixed in xterm.js.
