### ISSUE TITLE
Possible bug in isWrapped flagging

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2872]
I think this should be `buffer.y + buffer.ybase`?

https://github.com/xtermjs/xterm.js/blob/dac3037ee45421270bcb84a586d4af2e79e5c60e/src/InputHandler.ts#L558

**Comment by jerch** [comment]
@Tyriar Oh dear, yes I think so, too. What a nasty bug, weird it did not cause more issues yet.
