### ISSUE TITLE
web-links addon 0.3.0 opens new electron window instead of default browser

### ISSUE THREAD

**Issue by LabhanshAgrawal** [xtermjs/xterm.js#2875]
In https://github.com/zeit/hyper since updating to web-links addon 0.3.0 clicking the links is opening new empty electron window instead of opening it in the default browser.
git bisect also pointed to it (https://github.com/zeit/hyper/commit/f730d84021f00545a3305ca7da08e7488b209784) and reverting back to 0.2.1 fixes the issue.

## Details
- Browser and browser version: electron 8.2.3
- OS version: macOs 10.15.4
- xterm.js version: 4.5.0

### Steps to reproduce
(using hyper as an example, you may try with some test electron app if you have it handy)

1. Checkout hyper canary
2. build an run it (`yarn && yarn run dev` and in separate shell `yarn run app`)
3. do `echo "http://google.com"` in then opened hyper window
4. click the link
5. it'll open a new electron window with no content
6. change web-links addon version to 0.2.1
7. steps 2-4
8. it'll open google in your default browser

**Comment by LabhanshAgrawal** [comment]
https://github.com/xtermjs/xterm.js/commit/a980b3d1323661f8d678bfa5c458ec4773712eed might be the reason
As `window.open()` opens a new electron window and `window.open(uri, '_blank')` opens the uri in the default browser. (tested in dev console in hyper, and we haven't modified window.open in any way)

**Comment by Tyriar** [comment]
You can set a custom handler in the ctor:

https://github.com/xtermjs/xterm.js/blob/a8bcfc62d0b10f9a2e455257a82300b70e24d9aa/addons/xterm-addon-web-links/src/WebLinksAddon.ts#L45
