### ISSUE TITLE
ES6 module no export Terminal

### ISSUE THREAD

**Issue by elgs** [xtermjs/xterm.js#2878]
When I follow the doc to import Terminal as an ES6 module.

The recommended way to load xterm.js is via the ES6 module syntax:
```
import { Terminal } from 'xterm';
```

I got the following error. I opened the xterm.js and found it's an minified js file and it indeed didn't export Terminal.

```
The requested module '../../../node_modules/xterm/lib/xterm.js' does not provide an export named 'Terminal'
```

I'm not using any building tools. I just used plain ES6 import syntax.

**Comment by Tyriar** [comment]
I don't know the details here on what TS does but TS works for me. I guess this is requesting a native ESM target which has come up before https://github.com/xtermjs/xterm.js/issues/2486

**Comment by elgs** [comment]
What I am wondering is I've seen a few other libraries claiming they are supporting ES6, but they are in the same situation like this, like this one https://github.com/highlightjs/highlight.js/issues/2473. They use Rollup to build the library. I'm not familiar with Rollup.

My understand of ES6 module is the library has some code syntax like:
```js
export something = someFunction;
```

And the client is like:
```js
import { something } from 'node_modules/someLib/someLib.js';

something();
```

I wonder if I misunderstood what ES6 is.

**Comment by elgs** [comment]
This is a big deal, because with the REAL ES6 support, the client can get rid of the dependency of build tools, though the build tools are awesome, but at least it's not necessary.

**Comment by Tyriar** [comment]
Yeah it would be nice to be on the latest and greatest but then you lose support for other better supported ways of importing. Eventually we'll move there but shipping a library that supports many different import types is tricky.

**Comment by elgs** [comment]
I understand that. That's why if you look at the lodash package, they released a separate package called lodash-es. That is the REAL ES6 support. But unfortunately the export syntax is illegal in the nodejs like module system.

You mentioned:
> but then you lose support for other better supported ways of importing

Actually, no, you don't lose anything in browser. All modern build tools support the REAL ES6 syntax. What you lose is the support to build for nodejs user. But for packages like xterm, and highlightjs, why does it matter at all. Who use them in Nodejs.

**Comment by elgs** [comment]
lodash releases two separate packages for a wise reason, one for Nodejs and the other for browser. Because the natural of lodash is that it is used in both Nodejs and browser. In the old days, Javascript didn't  have any module system in the browser, everything is bound to `window`, so that's why many build tools did many tricking things to translate the Nodejs module system to the browser `window`. That's understandable before REAL ES6 is usable in the browsers. Now ES6 is natively supported by browsers, packages like xterm and highlightjs should have no reasons go around to the Nodejs module system.

**Comment by justinfagnani** [comment]
Is there any chance of moving to native modules in a major release? Every current major browser, and the past 3 major (soon to be 4 next moth) of Node, supports modules natively.

@Tyriar
> then you lose support for other better supported ways of importing. Eventually we'll move there but shipping a library that supports many different import types is tricky.

I don't think there are better ways of importing than native modules. Every other way requires tools or userland loaders, and can be targeted with native modules and a tool anyway.

At this point I really don't think it'd even be worth it to publish two packages. Applications that support older browsers can really easily consume JS module dependencies and compile them to a different format. It's the default behavior for Rollup and Webpack.

One problem with not publishing standard JS modules is that you library is shut off from those that are using native modules. I'm trying to use a terminal widget for a project, but all my libraries are modules only, and there's no good way to import UMD from native modules.

**Comment by TomzBench** [comment]
@justinfagnani Did you find a good way to import Terminal?

**Comment by elgs** [comment]
As I learned more about the whole thing. Now I know this is kind of like a fake ES6 support. Webpack did the trick to allow ES6 like syntax to import Nodejs modules.

**Comment by TomzBench** [comment]
@elgs 

I made an es6 export version with a fork here:

https://github.com/TomzBench/xterm.js

It is a fork with a set of different tsconfig files + rollup to export an es module. Hopefully this works for you.

**Comment by elgs** [comment]
@TomzBench cool, thanks!

Can you some an example assuming I don't have node or npm installed, which file should I `import` in the browser in order to use it?

**Comment by TomzBench** [comment]
I import like this

```typescript
import {Terminal} from "@altronix/xterm"
```

**Comment by elgs** [comment]
Can you please tell me the absolute path of `@altronix/xterm`?

**Comment by elgs** [comment]
I am actually thinking about of getting rid of the dependencies of node. I suddenly realized the source of this project is written in Typescript so it should be natively/immediately ready for Deno. And if we have an for example an Agular project, we should be able to import the source code from this project without going through the rollup at all.

**Comment by TomzBench** [comment]
xtermjs typescript sources uses "paths" and referenced projects and outputs es5. So to have it build es6 output you can look at my fork and copy the tsconfig.es6.json files if you want to build it that way. You can copy the es6 xterm.js file and paste it where ever you need it if you don't want to use node.

**Comment by zjhou** [comment]
> I import like this
> 
> ```ts
> import {Terminal} from "@altronix/xterm"
> ```

Hi, I try to visit the repo of this package but got a 404 page :eyes:

**Comment by jogibear9988** [comment]
@Tyriar any news to real ES6 support?

**Comment by Tyriar** [comment]
Updates would be posted here

**Comment by jodersky** [comment]
I found a workaround for the initial issue: you can change the import to `import * as xterm from '<path to xterm.js>;`.

E.g. the getting started example (using absolute paths since we assume it's served via a webserver):
```html
<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="/node_modules/xterm/css/xterm.css" />
</head>
<body>
    <div id="terminal"></div>
    <script type="module">
        import * as xterm from '/node_modules/xterm/lib/xterm.js';
        const term = new Terminal();

        term.open(document.getElementById('terminal'));
        term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    </script>
</body>
</html>
```

**Comment by walterjj** [comment]
> @elgs
> 
> I made an es6 export version with a fork here:
> 
> https://github.com/TomzBench/xterm.js
> 
> It is a fork with a set of different tsconfig files + rollup to export an es module. Hopefully this works for you.
> 
> you can test it by importing `@altronix/xterm`

Good job! , Thankyou!

**Comment by Aurillium** [comment]
Is there any official progress or recommended solution on this issue?
This is still mentioned as the recommended way of importing the module on the website but it doesn't work.
The fork is also behind and isn't really a sustainable solution to the issue.

**Comment by jerch** [comment]
@Aurillium A proper move to full ESM support is quite involved, this mainly results from the fact, that TS has its own understanding of module resolution, and how far it allows to use ESM resolution beside the old nodejs resolution.

@Tyriar Could we do a lightweight transition during bundling, like creating an explicit ESM target for xterm.js and the addons? I currently do this in `node-sixel` with different tsconfig + webpack build targets, where the result is a proper ESM bundle. Downside - it is not properly reflected by node package exports, as this is more involved with the right entries in package.json, thus it will not work with pure nodejs ESM resolution yet. Still the browser would happily digest that as ESM.
I dont see yet a full move to ESM for xterm.js, as we would have to sort out, which parts should go into native ESM resolution, and which would always need some sort of prebundling. Furthermore cutting off the current nodejs module resolution will create many frictions on most embedding projects...

> This is still mentioned as the recommended way of importing the module on the website but it doesn't work.

Currently the docs snippets are written for TS, not JS. Plus the idea, that your TS project is set up with nodejs module resolution. It just happens, that TS uses a similar syntax to JS-ESM, but in fact translates things to `require(xy)` calls underneath. Imho thats just a misunderstanding from the docs - note that the import syntax in the snippets does not contain '.js' endings on modules. TS uses that syntax way longer than ESM is out in the wild.

> The fork is also behind and isn't really a sustainable solution to the issue.

For long term thats not a viable way to deal with the issue, as forks always tend to show that issue.

**Comment by TomzBench** [comment]
It's not really a "fork" - just a personal attempt to get it working with vite at the time.

I gave a quick try to resync with the master branch but i get some compile errors now. so i probably won't be able to fix them unless i need to use this package with vite again.

**Comment by johtso** [comment]
I just tried to use xtermjs for the first time in a deno project, and immediately bumped into the `The requested module 'npm:xterm@5.1.0' does not provide an export named 'Terminal'` issue..

**Comment by Tyriar** [comment]
We're going to be forced to do this soon as VS Code is in the process of moving from AMD to ES6. I expect some progress on this in the next 2-6 months

**Comment by johtso** [comment]
I managed to get things working by using the old version that @TomzBench .. any tips on how I can import an addon? They have the same issue.

**Comment by thimpat** [comment]
The module doesn't seem to be ES6 compatible. I sent a temporary quick fix while waiting for the native export


```javascript
import {Terminal, SearchAddon, WebLinksAddon, FitAddon} from "@thimpat/xterm";
```

**Comment by wtcross** [comment]
As far as I can tell this issue prevents this library from being used with Vite. Am I wrong about that?

I am trying to use [duckdb-wasm-shell](https://github.com/duckdb/duckdb-wasm/tree/main/packages/duckdb-wasm-shell) in a project and it is not able to import xterm due to this. Any advice would be much appreciated. I spent way too much trying to hack together a way to get it to work with no results.

**Comment by liudonghua123** [comment]
I tried `@altronix/xterm`, but it's version 4.x and a little old, I forked and changed [minimal](https://github.com/liudonghua123/xterm.js/commit/9ee2f08084e392eec698c21fce11844ae8ac8bfd) code to output esm/module builds.

You can use it as `import { Terminal } from "@liudonghua123/xterm";`

OR

```html
    <script type="importmap">
      {
        "imports": {
          "xterm": "https://unpkg.com/@liudonghua123/xterm@5.4.0/lib/xterm.js"
        }
      }
    </script>
```

And some code also need to update, see also https://github.com/xtermjs/xterm.js/issues/4256#issuecomment-1510977408.

**Comment by Tyriar** [comment]
Fixed with https://github.com/xtermjs/xterm.js/pull/5092! Anyone interested please test this out in the latest beta build
