### ISSUE TITLE
Need the function to clear a line in terminal

### ISSUE THREAD

**Issue by ScarlettKK** [xtermjs/xterm.js#2884]
I need to achieve the install loading effect (like `npm install`) in xterm, but I can not find the correct way to clear the current line. 

![image](https://user-images.githubusercontent.com/47051897/80481438-ffe35b80-8984-11ea-8b68-2822a71fb98f.png)

I have tried to add `\x1b[2K` and `\x1bc`  in `xterm.write()`, but they don't work well. `\x1bc` clears the whole screen, while I just want to clear all the words in the current line and write new messages into the same line. `\x1b[2K` behaves weird as the following image:

Code: 

``` typescript
term.write(name + ': ' + percent + '%   \x1b[2K')
```

Show results：

![image](https://user-images.githubusercontent.com/47051897/80482327-9f551e00-8986-11ea-9e96-67c15b7dc761.png)

Can we make a new API like  `term.clearLine()` or `term.writeCover()` to let users write message in the same line?

**Comment by Tyriar** [comment]
You could do this:

```
term.write('\x1b[G\x1b[Kblah')
```

The reason for not adding something like `clearLine` is because it goes against how the lib is meant to be used where the application is meant to talk to the terminal only by the bi-directional text stream (onData and write).
