### ISSUE TITLE
xterm-addon-search@0.6.0 is not compatible with xterm@4.4.0

### ISSUE THREAD

**Issue by haoqi0818** [xtermjs/xterm.js#2885]
xterm-addon-search@0.6.0 is not compatible with xterm@4.4.0
bug
xterm-addon-search@0.6.0 just require xterm@^4.0.0

## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 4.4.0
- xterm-addon-search version 0.6.0

console error: "Uncaught TypeError: Cannot read property 'length' of undefined" when call search

**Comment by Tyriar** [comment]
This will happen until we move the addon versioning to v1. Trust the release page about support, not the package.json for now https://github.com/xtermjs/xterm.js/releases/tag/4.4.0

**Comment by Altamill** [comment]
I have too problem
OS version: 10.15
xterm.js version: 4.1.0
xterm-addon-search version: 0.5.0
