### ISSUE TITLE
Link provider underline draws 1 extra character when after wide characters

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2887]
I'm guessing this is in xterm.js as it appears to be purely a rendering issue, the link works file and excludes the `]`:

![image](https://user-images.githubusercontent.com/2193314/80600852-d73d7f00-89e1-11ea-8a7a-482c2e7b28d9.png)

![image](https://user-images.githubusercontent.com/2193314/80600927-f0463000-89e1-11ea-9e55-24ff33d1420e.png)

**Comment by rishab-pdx** [comment]
@Tyriar 
I did a bunch of work on this issue. Currently, xterm.js fails to detect some links as the regex cannot capture all the cases and the same is true for rendering the underlines. 

https://drive.google.com/open?id=19M6FJwpbNzRuMbjHE3QeC9BN0mPHg7yi

Rendering happens on

https://github.com/xtermjs/xterm.js/blob/f2ed01993dc4074e2ad012593cf230b2aeab600d/src/browser/renderer/LinkRenderLayer.ts#L56-L78

https://github.com/xtermjs/xterm.js/blob/3a5def98e574909ad34385c0bcaa3112a6807e0e/src/browser/renderer/BaseRenderLayer.ts#L160-L165

all of this happens using based on range created using 

https://github.com/xtermjs/xterm.js/blob/9817754f92519322bec076b56644f5ec8c0e597a/addons/xterm-addon-web-links/src/WebLinkProvider.ts#L24-L71

I would like to work on this further. Can you let me know how can I reproduce the issue on xterm.js to test rendering without modifying the regex to handle links like 
```https://www.google.com/[我是学生].txt ```

Also, I feel WebLink addon must detect links with a regex similar to the vscode terminal.

**Comment by Tyriar** [comment]
> Can you let me know how can I reproduce the issue on xterm.js

Maybe the only way right now is to it within VS Code as described in https://github.com/xtermjs/xterm.js/issues/2818#issuecomment-621814056 as it pulls in a bunch of monaco code to do the link detection. I'm pretty sure the bug is in xterm.js though as everything else seems to work, just not to rendering part. Alternatively you could try use a custom link matcher which matches on these characters to see if it can trigger the bug in the renderers.

> Also, I feel WebLink addon must detect links with a regex similar to the vscode terminal.

The link support in VS Code only works because it builds on a lot of code inside the editor, in an effort to keep the web links addon simple and avoid needing to attribute, I thought it best to keep it regex based as it was before.
