### ISSUE TITLE
blink text problem

### ISSUE THREAD

**Issue by ppacory** [xtermjs/xterm.js#2891]
this code print in term doesn't blink :

`text = "\u001b[5mTitle of the Program\u001b[0m"` or
`text = "\x1B[5mTitle of the Program\x1B[0m"`   

the other ansi code like inverted,bold,underline work perfectly ...
Any idea ?

**Comment by Tyriar** [comment]
duplicate of https://github.com/xtermjs/xterm.js/issues/944
