### ISSUE TITLE
DA1/2/3 issues

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#2894]
We are currently sending quite some rubbish on DA requests - we switch output based on `this._is` (were does this come from?) to lure a program into thinking that we are something else. Thats a really bad habit, if I were a cmdline dev I'd hate xterm.js for doing this. DA3 isn't implemented at all.

We should fix that, maybe like this:
- dont shift output on some obscure `this._is` value, we are xterm.js with working and missing stuff
- find appropriate DA1 string that reflects our VT level best (kinda hard as we dont follow that scheme and have mixed support across the levels)
- report some unique number in DA2 so a program can identify us as xterm.js, also put version number there
- no clue if we should implement DA3, if so, maybe put version number into clientID

**Comment by Tyriar** [comment]
> we switch output based on this._is (were does this come from?)

This thing has always confused me, it used to be Terminal.is, I just moved it into `InputHandler` recently as it's the only thing that used it. It's based on `termName` which hasn't been part of the API for years and its default value is `xterm`.

**Comment by jerch** [comment]
While working on the image addon, I again stumbled over this trying to find a suitable DA report with SIXEL enabled. The problem we basically have is a wonky support for any type we report there with best coverage of VT102. We cannot easily go with VT220+ (reporting >=62) as we miss several functionality of these higher devices. But for lower types the additional numbers do not carry any meaning, thus reporting SIXEL support might not be evaluated by applications.

To get something working in this regard, here my proposal for DA1:
- report terminal as VT220 --> 62
- identify missing crucial functionality of VT220, fix ASAP
- report things like SIXEL support, if addon is enabled (could be done from the addon itself)

Additionally we should reshape DA2 reports. xterm reports patch number in Pv, Pc is set to 0. I think we could do likewise, maybe like this:
- Pp should be at least VT220 (1), and maybe VT240 if SIXEL is enabled (2)
- Pv could contain our major release number (4.10 --> 4), or maybe with some xterm.js "namespace" (1200 --> 12004)
- Pc could contain our minor release number (4.10 --> 10)

In any case we should remove the "shape-shifting" of reports, it is really cumbersome for applications to work with that.

Plz note that changes to the DAs will cause frictions with applications, that eval them and are not aware yet about it. But the current stage is a nightmare, so I think we should go through that for a better aftermath. Also there is a discussion about it on the terminal-wg, but it kinda led to nowhere and might get superceded by the planned feature reporting sequence. Also I am still unsure about DA3 and would leave it out of this for now.

Up for discussion, better ideas how to shape the reports are more than welcome.

FYI: @Tyriar, @mofux, @ThomasDickey

**Comment by jerch** [comment]
Somewhat stale, thus closing.
