### ISSUE TITLE
Detect ligatures on browser side

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2897]
Currently the ligatures addon needs a node.js environment to run which essentially means it can only run in Electron and will not run in VS Code like this as we're moving towards a more secure, node-free renderer. This idea is about trying to detect ligatures for a particular font by having a set of common ligatures (==, ===, <=, >=, ->, etc.) and using a canvas to draw them, toggling `font-variant-ligatures` on and off and comparing the output. If they're different, assume they're ligatures and draw them together using the character joiner API.

**Comment by LabhanshAgrawal** [comment]
This may not be needed now?
