### ISSUE TITLE
TypeError: n.buffer.getLine is not a function

### ISSUE THREAD

**Issue by Altamill** [xtermjs/xterm.js#2909]
## Details
- Browser and browser version: chrome / 81.0.4044.129
- OS version: linux centos 7
- xterm.js version: 4.5.0
- xterm-addon-attach: 0.5.0
- xterm-addon-fit: 0.3.0
- xterm-addon-search: 0.6.0

### Steps to reproduce

searchAddon.findNext(e.target.value) 

TypeError: n.buffer.getLine is not a function

**Comment by JavaCS3** [comment]
@Altamill Can you provide a http://jsfiddle.net/ sample?
This issue may be related to #2713
