### ISSUE TITLE
Warnings about non passive events

### ISSUE THREAD

**Issue by DavidSichau** [xtermjs/xterm.js#2910]
There is already a closed issue about that: https://github.com/xtermjs/xterm.js/issues/829

However we do see the following warning popup in chrome again:

```
/node_modules/xterm/lib/xterm.js:9 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
t.addDisposableDomListener @ /node_modules/xterm/lib/xterm.js:9
t.bindMouse @ /node_modules/xterm/lib/xterm.js:9
t.open @ /node_modules/xterm/lib/xterm.js:9
e.open @ /node_modules/xterm/lib/xterm.js:9
eval @ XTerm.jsx:340
(anonymous) @ meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1234
/node_modules/xterm/lib/xterm.js:9 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
t.addDisposableDomListener @ /node_modules/xterm/lib/xterm.js:9
t.bindMouse @ /node_modules/xterm/lib/xterm.js:9
t.open @ /node_modules/xterm/lib/xterm.js:9
e.open @ /node_modules/xterm/lib/xterm.js:9
eval @ XTerm.jsx:340
(anonymous) @ meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1234
/node_modules/xterm/lib/xterm.js:9 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
t.addDisposableDomListener @ /node_modules/xterm/lib/xterm.js:9
t.bindMouse @ /node_modules/xterm/lib/xterm.js:9
t.open @ /node_modules/xterm/lib/xterm.js:9
e.open @ /node_modules/xterm/lib/xterm.js:9
eval @ XTerm.jsx:340
(anonymous) @ meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1234
/node_modules/xterm/lib/xterm.js:9 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

## Details
- Browser and browser version: Chrome  81.0.4044.122
- OS version: Ubuntu 20.04
- xterm.js version: 4.5.0

### Steps to reproduce

1. Open Demo in Chrome

**Comment by jerch** [comment]
@DavidSichau I cannot repro with Ubuntu 18, same chrome version. Did you set some special flag in the chrome settings to get this warning? (Yes its just a warning, dont get misguided by the term "Violation")

**Comment by Tyriar** [comment]
I always had trouble reproducing this warning reliably, The fix should be to set `passive` explicitly though, essentially making it a mandatory option. If we want to intercept scrolls, which we do iff mouse wheel events are being sent to the process so the page doesn't scroll, we want `passive: false` I think.

**Comment by DavidSichau** [comment]
I do not have any special settings. I could follow to the causing function which is:

https://github.com/xtermjs/xterm.js/blob/3a9cdbab0d62706c28233ada339d11d75ddedabb/src/browser/Lifecycle.ts#L19

**Comment by Tyriar** [comment]
@DavidSichau this is probably the line:

https://github.com/xtermjs/xterm.js/blob/64328ee39c64a201bd28dc72fb5c644d8cd880d8/src/browser/Terminal.ts#L677

If you can reproduce this consistently, you could make a PR by running the demo, changing it to this and verifying it goes away:

```ts
el.addEventListener('wheel', eventListeners.wheel, { passive: false });
```

**Comment by DavidSichau** [comment]
@Tyriar Your change did not work.

I added the following change and all issues were gone:


```
export function addDisposableDomListener(
  node: Element | Window | Document,
  type: string,
  handler: (e: any) => void,
  useCapture?: boolean
): IDisposable {
  // add here passive
  node.addEventListener(type, handler, { passive: false });
  let disposed = false;
  return {
    dispose: () => {
      if (disposed) {
        return;
      }
      disposed = true;
      node.removeEventListener(type, handler, useCapture);
    }
  };
}
```

My suggestion would be to instead of passing useCapture and an object or boolean which contains additional options, then the passive event can be passed down. What do you think?

**Comment by jerch** [comment]
@DavidSichau The code line @Tyriar mentioned, will be activated on a program requesting extended mouse reports. You can prolly trigger the same error at that code line with vim and activated mouse support.

**Comment by DavidSichau** [comment]
I get rid of the warnings if I do both changes. The one code line change mentioned by @Tyriar is not enough,

**Comment by Tyriar** [comment]
Maybe a listener is missing then. I'm not sure we can add passive there to the generic listener helper as some events may not be passive? Finding the one tuts needs it and passing in an option instead would be better.

**Comment by DavidSichau** [comment]
I have created a pull request to address these warnings:

https://github.com/xtermjs/xterm.js/pull/2931
