### ISSUE TITLE
Font not properly displayed

### ISSUE THREAD

**Issue by miguelmota** [xtermjs/xterm.js#2918]
What fonts do I need installed on my system for xterm to render the text correctly? The screenshot shows the fonts being rendered weirdly on the demo page

![Screenshot from 2020-05-06 12-54-49](https://user-images.githubusercontent.com/168240/81222388-1008c580-8f99-11ea-9c3d-393e09a4db39.png)

## Details
- Browser and browser version: All
- OS version: Arch linux
- xterm.js version: latest

### Steps to reproduce

1. Visit https://xtermjs.org/
2. Scroll down to demo

**Comment by miguelmota** [comment]
It was a monospace font configuration problem on my computer. Closing.

**Comment by jerch** [comment]
> The same problem is exist on my computer. What's the problem and how to solve it?

You should have installed at least one monospace font in your OS, which the browsers acknowledge as such and would choose.

**Comment by Tyriar** [comment]
Yeah that's a little strange as we fallback to monospace. I would consider this a OS/browser issue also

**Comment by FreeeBird** [comment]
> > The same problem is exist on my computer. What's the problem and how to solve it?
> 
> You should have installed at least one monospace font in your OS, which the browsers acknowledge as such and would choose.

It works for me. Thanks.
