### ISSUE TITLE
Where is xterm.js

### ISSUE THREAD

**Issue by st1nga** [xtermjs/xterm.js#2937]
## Details
- Browser and browser version: FireFox 68.8.0esr
- OS version: Debian 9
- xterm.js version: 4.6.0 (I believe)

### Steps to reproduce
root@shark:/var/www/html# apt install npm
root@shark:/var/www/html# npm install xterm
xterm@4.6.0 node_modules/xterm

1. npm install xterm
2. Can't find xterm.js anywhere

root@shark:/var/www/html# find . -iname "*xterm.js*" -ls
root@shark:/var/www/html# 

Scratch head....

**Comment by st1nga** [comment]
I added this and now I get something...

<script src="https://cdnjs.cloudflare.com/ajax/libs/xterm/3.14.5/xterm.min.js"></script>

But unsure about it really.....

**Comment by st1nga** [comment]
Opps, didn't mean to close it

**Comment by Tyriar** [comment]
Installing npm via apt seems like a bad idea, it's bundled with node. It should be in node_modules/xterm

**Comment by st1nga** [comment]
Well it isn't in node_modules/xterm.

How else would I install npm?

**Comment by Tyriar** [comment]
This is a problem with your node/npm setup, you should read their docs.

**Comment by st1nga** [comment]
OK, thanks for the help.
