### ISSUE TITLE
“opening link blocked as opener could not be cleared“：an exception occurred for xterm-addon-web-links

### ISSUE THREAD

**Issue by roguexiaohuihui** [xtermjs/xterm.js#2943]
## Details
- Browser and browser version: Electron 
- OS version:  Windows 10
- xterm.js version: 4.4.0
xterm-addon-web-links：>=0.4.0

### Steps to reproduce

1. when the xterm version is 4.4.0, if the xterm-addon-web-links version is higher than 0.2.1, an error will occur

**Opening link blocked as opener could not be cleared**

![image](https://user-images.githubusercontent.com/22930711/82645034-d694b300-9c44-11ea-8b7f-c7b364771de6.png)

**Comment by Tyriar** [comment]
This was added to prevent a security issue. I wonder if we should be detecting Electron somehow here, that may not be possible if the sandbox is enabled though 🤔

**Comment by mofux** [comment]
In which case would `window.open()` not return a reference to the opened window? I just tested the above code in electron and it is working correctly. @roguexiaohuihui Can you tell which electron version you are using, and maybe also provide the settings that you are using for opening the electron window?
