### ISSUE TITLE
Disable cursor

### ISSUE THREAD

**Issue by Jesse-Schokker** [xtermjs/xterm.js#2944]
Currently it doesn't seem to be possible to hide the cursor. There's also nothing listed in the supported terminal sequences in regards to removing the cursor (https://xtermjs.org/docs/api/vtfeatures )

**Comment by jerch** [comment]
@Jesse-Schokker 
DECTCEM with `CSI ? 25 h` (show) and `CSI ? 25 l`  (hide) does not work for you?

**Comment by arciisine** [comment]
I've tried using the sequences and they are not working within VSCode's xterm instance.  Running the same code outside of VSCode in a standard bash shell, and everything works as expected.

**Comment by jerch** [comment]
@arciisine The terminal state is global and can be changed by any process with access to that terminal. You prolly have some process in between which negates the effect (e.g. a $PS1 directive messing with the cursor, a shell plugin, ConPty on Windows).

If this happens within the output of a single interactive process we need more context information.

**Comment by Tyriar** [comment]
This works fine:

![recording (19)](https://user-images.githubusercontent.com/2193314/84572784-3ae0f900-ad51-11ea-8b5e-e6a83f5346ac.gif)
