### ISSUE TITLE
Is it possible to get txt content of xterm?

### ISSUE THREAD

**Issue by xiangcong** [xtermjs/xterm.js#2945]
Hi,

I'm planning writing integ tests for xterm used in my application.
Wondering if I can get the txt from canvas and verify the content?

Thanks!

**Comment by jerch** [comment]
> Wondering if I can get the txt from canvas and verify the content?

Nope, thats not possible unless you want to write an OCR. A canvas is just a pixelated drawing surface.

Maybe your looking for https://xtermjs.org/docs/api/terminal/interfaces/ibufferline/#translatetostring?

**Comment by xiangcong** [comment]
Thanks for the info!
