### ISSUE TITLE
Up left corner should not show textarea and character 'W'

### ISSUE THREAD

**Issue by dlanorf** [xtermjs/xterm.js#2957]
## Details
- Browser and browser version: 
Chrome
Version 81.0.4044.138

![xterm](https://user-images.githubusercontent.com/44251003/83500408-4fbbc200-a4f1-11ea-9ca4-98ce41c56d18.png)

- OS version: 
- xterm.js version: 4.6.0

### Steps to reproduce
below is my code:

import React, {Component} from "react";
import {Terminal} from "xterm";
import { FitAddon } from "xterm-addon-fit";
const fitAddon = new FitAddon();
const term = new Terminal({
    cursorBlink: true,
    scrollback: 1000,
    tabStopWidth: 8
});
term.loadAddon(fitAddon);

class Home extends Component {
    constructor(props) {
        super(props);
        this.testXterm = this.testXterm.bind(this);
        this.testXterm();
    }

    testXterm() {
        term.open(document.getElementById('terminal'));
        term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ');
        term.onData((data) => {
            term.write(data);
        });
        fitAddon.fit();
    }

    render() {

        return (
            <div>
            </div>
        );
    }
}

**Comment by Tyriar** [comment]
You're not using the css?

**Comment by dlanorf** [comment]
Should not Terminal in xterm use the css ?
Should user import css manually ?

**Comment by Tyriar** [comment]
Please read https://github.com/xtermjs/xterm.js#getting-started

**Comment by dlanorf** [comment]
after import the css manually. It appears normal. Thanks !
