### ISSUE TITLE
[xterm-addon-fit] Wrong rows/cols calculation

### ISSUE THREAD

**Issue by anatoly-spb** [xtermjs/xterm.js#2958]
Thank you for amazing component! 

Anyway I met a problem and want to share it. 

I have a simple project which show the problem with rows/cols calculation by xterm-addon-fit

![problem](https://user-images.githubusercontent.com/13556403/83548117-e72e0e80-a50b-11ea-87f2-5f59eb358051.PNG)

As you can see on the picture xterm shows only 2.5 rows, but xterm-addon-fit calculates 4 rows.
In this situation I cannot scroll to bottom to see the END line (line with the END word), the END line looks cutted. Also I cannot see scroll bars.

May be I do something wrong and you can show me a way to make it works correctly.

## Details
- Browser and browser version: Google Chrome Версия 83.0.4103.61 (64 bit)
- OS version: Windows 10 Home Edition
- xterm.js version: 4.6.0
- xterm-addon-fit version: 0.4.0

### Steps to reproduce

1. Clone example project

```
git clone https://github.com/anatoly-spb/xtermjs-fit-example.git
cd xtermjs-fit-example
npm install
```
2. Open Browser
3. Open File index.html 
4. Open Development Tool
5. Resize the browser to small size and watching to console output with calculated rows and columns

**Comment by Tyriar** [comment]
@anatoly-spb it seems to be doing the right thing, remove `overflow: hidden` from `body` to show the issue; xterm.js' host element is larger than is visible in your screenshot.
