### ISSUE TITLE
Is there a way to get all the characters before cursor ?

### ISSUE THREAD

**Issue by dlanorf** [xtermjs/xterm.js#2969]
![xterm2](https://user-images.githubusercontent.com/44251003/84342446-26c5bc00-abd8-11ea-8c74-050518e7ac36.PNG)

**Comment by Tyriar** [comment]
Yes using the `buffer` API:

https://github.com/xtermjs/xterm.js/blob/8a3366b1eb5d10e86b3e7a49b9003ae49ff93a44/typings/xterm.d.ts#L587-L592

**Comment by dlanorf** [comment]
I tried to use "select" method to get the characters, but I couldn't get desired result.
One difficulty is that I couldn't get the cursor position. As a result, I don't the correct start and end of selection.
