### ISSUE TITLE
pbcopy/pbpaste style functionality in the browser

### ISSUE THREAD

**Issue by samuelsinayoko** [xtermjs/xterm.js#2972]
Note sure if this is the best place to post this but is there a way to interact with the browser's clipboard from a terminal command, similar to what pbcopy/pbpaste provide on OSX (or xsel/xclip on Linux)? 

At the moment you can select and copy using the mouse, or paste using the mouse or keyboard. It can be tricky to copy large amount of text that way. For example if you've typed a long command and you'd like to copy it to the clipboard 
```
history | tail -n 1 | pbcopy
```

**Comment by Tyriar** [comment]
pbcopy would be running on the remote machine, this sort of thing is pretty hard to do and probably impossible just in a regular browser due to security restrictions around clipboard access (maybe possible with hacks in electron though).
