### ISSUE TITLE
Reconnecting to an existing session does not re-enable the mouse

### ISSUE THREAD

**Issue by skerit** [xtermjs/xterm.js#2975]
I'm upgrading my application to Xterm.js 4.7 from 3.4.1.

My xterm.js instance is connected to my server using websockets.
The application it connects to is always on.

When the first xterm.js instance connects to it, everything works fine, including mouse support,
but when I refresh the page and connect again the mouse events are no longer forwarded.

The `term._core._coreMouseService.areMouseEventsActive` property is also false.
How can I re-enable mouse support on the client side?

## Details
- Browser and browser version:  Firefox 78
- OS version: Manjaro Linux 20.0.3
- xterm.js version: 4.7

### Steps to reproduce

1. Reconnect xterm to existing application session via websockets
2. Mouse events aren't captured

**Comment by Tyriar** [comment]
How are you reconnecting? If it's just a socket drop and reconnect there's no reason mouse events would break as xterm.js doesn't know anything about being connected/disconnected.

**Comment by skerit** [comment]
@Tyriar With "reconnecting" I mean a new xterm.js session (a page refresh if you will) connecting to an existing terminal session. (Well, actually an existing `blessed` backend)

**Comment by Tyriar** [comment]
Yes that will definitely happen, currently there is a WIP serialize addon which serializes and restores terminal state: https://www.npmjs.com/package/xterm-addon-serialize, I'm not 100% sure if it retains mouse modes yet but the intent is that it will eventually. But in general, this is up to consumers to do or the serialize addon.

**Comment by petersutter** [comment]
@skerit I have the same issue. Did the `xterm-addon-serialize` solve it for you or did you find a workaround?
Also, even in case the mouse events are forwarded (e.g. scrolling with the mouse works), the property `term._core._coreMouseService.areMouseEventsActive` is always `false` in my case so I'm not sure if this is a good indicator.

**Comment by skerit** [comment]
@petersutter I haven't been able to test it yet, but I'm not sure if I'm going to use it anyway because I see two ways of implementing this:

1: Create an extra xtermjs Terminal instance (together with the serializer) on the server side & pipe all the output of the real terminal into it, then when a new client-side xtermjs Terminal session wants to connect give it the serialized content first before also piping the newest terminal data into it.
I don't really want to let my server-side process handle that.

2: Periodically send the serialized Terminal instance on the client-side to the server, which the server then can use to initialize other new client-side sessions. But I don't know, seems a bit error-prone.

Maybe it's a lot easier to just inject the command sequence that tells the xtermjs instance to enable mouse events?
