### ISSUE TITLE
Cannot delete from second line to first line.

### ISSUE THREAD

**Issue by zfha** [xtermjs/xterm.js#2978]
I use the demo in official website。

https://xtermjs.org/

If I input too long string to second line. Now, I cannot backspace or delete to first line.

case gif:
![Jun-23-2020 17-16-11](https://user-images.githubusercontent.com/4082233/85385809-5039fc80-b575-11ea-9a1e-ffb40702dce5.gif)

how to solve this problem?

**Comment by Tyriar** [comment]
The demo is very basic https://github.com/xtermjs/xtermjs.org/blob/b4b1a13bf676b51d6111f0dd81185312418f0f19/js/demo.js#L23-L39, you should look up xterm.js to a shell process and study how that works.
