### ISSUE TITLE
Cannot read property 'features' of undefined - while using ligatures addon

### ISSUE THREAD

**Issue by LabhanshAgrawal** [xtermjs/xterm.js#2980]
This bug is caused in https://github.com/princjef/font-ligatures which is a dependency of the ligatures addon.

For some fonts, the `gsub` table may not be present. And that causes the below error.

![](https://user-images.githubusercontent.com/2801156/77810633-d1afea80-706b-11ea-8fd6-910405e38ec3.png)

![](https://user-images.githubusercontent.com/2801156/77810889-4afc0d00-706d-11ea-855a-3a490ce55034.png)

![](https://user-images.githubusercontent.com/2801156/77810888-49cae000-706d-11ea-9a0a-4b612a468ac5.png)

It causes the rendering of the font to stop working.

![](https://user-images.githubusercontent.com/2084821/81014132-867eb980-8e19-11ea-9390-75fd4f081c92.png)

Ref- https://github.com/vercel/hyper/issues/4360#issuecomment-605370067 & https://github.com/vercel/hyper/issues/3391#issuecomment-624081818

I've opened a pull request for it https://github.com/princjef/font-ligatures/pull/18 but that repo seems inactive.

Would it be possible to use some other module or incorporate this (font-ligature) module's code into the the xterm-addon-ligatures?

**Comment by LabhanshAgrawal** [comment]
@Tyriar can you please take a look at this
I was able to replicate this issue in Terminus also, using [Inconsolata Nerd Font](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Inconsolata.zip)

I can send a pull request if we want to incorporate this modules's code into the addon, or if you know about any other module which can be used, I can try and add that.

**Comment by jerch** [comment]
@LabhanshAgrawal 

> I can send a pull request if we want to incorporate this modules's code into the addon ...

To me this looks problematic, as the module code relies on nodejs env (loading system fonts through additional modules), while xterm.js itself is a completely decoupled browser frontend thingy. The addon currently only works in this hybrid mode and is not useable in pure browser builds. At this stage I think incorporating the code into a purely browser targetting repo is not a good idea, imho doing a separate fork would bethe cleaner way.

> ... if you know about any other module which can be used ...

Imho @princjef is the first who implemented this in JS, not sure if there are later impls. Furthermore I am not a big fan of spinoffs, if the original looks well organized and maintained. And I was under the impression that this is the case for @princjef's packages, so maybe give him some time to sort things out?

**Comment by Tyriar** [comment]
> To me this looks problematic, as the module code relies on nodejs env (loading system fonts through additional modules), while xterm.js itself is a completely decoupled browser frontend thingy.

This is an Electron-only addon and soon won't even work in VS Code as we want to disable node in the renderer all together.

> Furthermore I am not a big fan of spinoffs

👍 ideally this would get fixed in the upstream package.

**Comment by princjef** [comment]
Hey folks, sorry for the delay on the upstream fix. It has been merged and published in version 1.3.3, so this issue should be resolved now. Let me know if this is not the case

**Comment by LabhanshAgrawal** [comment]
@princjef thanks for merging and publishing it.
@Tyriar @jerch I've opened a pr #2993 to update to 1.3.3
I've tested it in hyper, I'd be glad if this could make it in 4.8.0 if possible.

**Comment by Tyriar** [comment]
@princjef thanks for the quick fix mate 🙂
