### ISSUE TITLE
when open mutil terminal in one page , use long time .

### ISSUE THREAD

**Issue by herolyle** [xtermjs/xterm.js#2983]
## Details
- Browser and browser version:chrome 版本 83.0.4103.116（正式版本） （64 位）
- OS version:mac os 
- xterm.js version: xterm@3.8.0

### Steps to reproduce

In one page ,have many tabs/terminal ，when I open new tab need long time 。。

execute many times  clearColor
FunctionclearColor @ CharAtlasGenerator.js:73

**Comment by herolyle** [comment]
![image](https://user-images.githubusercontent.com/1737842/86002771-6814f300-ba43-11ea-9e09-b77072693d42.png)

**Comment by herolyle** [comment]
![image](https://user-images.githubusercontent.com/1737842/86002896-95fa3780-ba43-11ea-8ddb-05410a5aaf65.png)

**Comment by herolyle** [comment]
code 
 `
  // Remove the background color from the image so characters may overlap
  clearColor(charAtlasImageData, config.colors.background);
`


I set theme configure like 

`
    let defaultTheme = {
        foreground: "#c2c2c2",
//        background: "#222222",
        cursor: "#ffffff",
        selection: "rgba(255, 255, 255, 0.3)",
        black: "#000000",
        brightBlack: "#808080",
        red: "#ce2f2b",
        brightRed: "#f44a47",
        green: "#00b976",
        brightGreen: "#05d289",
        yellow: "#e0d500",
        brightYellow: "#f4f628",
        magenta: "#bd37bc",
        brightMagenta: "#d86cd8",
        blue: "#1d6fca",
        brightBlue: "#358bed",
        cyan: "#00a8cf",
        brightCyan: "#19b8dd",
        white: "#e5e5e5",
        brightWhite: "#ffffff"
    };
`

**Comment by jerch** [comment]
> xterm.js version: xterm@3.8.0

Plz try to repro the issue with the master version. 3.8 is outdated.

**Comment by Tyriar** [comment]
Additionally that is using the canvas renderer which we want to get rid of eventually, the webgl addon is available for fast hardware acceleration or the dom renderer for slower but best compatibility.
