### ISSUE TITLE
Doesn't support vt resize command

### ISSUE THREAD

**Issue by LabhanshAgrawal** [xtermjs/xterm.js#2994]
## Details
- Browser and browser version: Chrome 83 and electron 9.0.5
- OS version: macOS Catalina
- xterm.js version: 4.7.0

### Steps to reproduce

1. do `printf '\e[8;40;80t'`
2. the onResize event should fire (with rows:40 & cols:80) but there's no event

Works on default terminal.app (it resizes based on the entered rows and cols)
Tested on the xterm demo, hyper and terminus

ref https://github.com/vercel/hyper/issues/1788

**Comment by Tyriar** [comment]
This is left out by design, we provide implementations for some window options but not the one you're referring to. See https://github.com/xtermjs/xterm.js/blob/dc541c2664c3009ad61a088fb14663713cd675da/typings/xterm.d.ts#L403-L429 for how to implement this.

**Comment by LabhanshAgrawal** [comment]
I see
Thanks for clarifying

**Comment by vladdeSV** [comment]
Does this mean there will be no way to an application to change the window size?

**Comment by Tyriar** [comment]
@vladdeSV you can do it, you would just need to implement it on your end as per https://github.com/xtermjs/xterm.js/issues/2994#issuecomment-655603325

**Comment by jerch** [comment]
@vladdeSV There are two problems behind it, why xterm.js cannot offer that feature out of the box:
- xterm.js is typically used as embedded widget within a bigger "website", thus cannot not change its dimension freely (or it would break 90% of those embedding pages). You need to prepare your solution for that, and then fill the missing implementation of `CSI ... t`.
- Some of those features require reporting of host features to the application, but reporting arbitrary host data to the application might be a security risk. Thus features behind `CSI ... t` have to be enabled explicitly in the terminal settings.
