### ISSUE TITLE
Nothing is visible in VS Code in 4.8.0

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3003]
Likely due to https://github.com/xtermjs/xterm.js/pull/2999, cc @andrew-schlackman

![image](https://user-images.githubusercontent.com/2193314/87164725-f7a97580-c27d-11ea-93c4-88d525be45e8.png)

**Comment by andrew-schlackman** [comment]
Ugh, that's an unfortunate unintended consequence. I'll try to take a look when I can, but I haven't built vscode from source yet. Sorry about that.

**Comment by Tyriar** [comment]
I'll revert the change to get a quick fix out as I published this in 4.8.0, still open to a change to fix your issue though.

**Comment by Tyriar** [comment]
But no rush on your end 😃
