### ISSUE TITLE
Keeping the scroll position unchanged after write to terminal

### ISSUE THREAD

**Issue by killjoy2013** [xtermjs/xterm.js#3011]
My reactjs app is listening SSH feed and writes every chunk of text to xtermjs terminal. 

Existing behaviour is to scroll to bottom after each write to terminal;

`refTerminal.current.write(newChunk);`

Desired behaviour is to be able to select the default behaviour. i.e., scroll to bottom after each write,  or  keep the scroll position unchanged. Maybe an optional second parameter does it;

`refTerminal.current.write(newChunk, "no-scroll");`

**Comment by Tyriar** [comment]
> Existing behaviour is to scroll to bottom after each write to terminal;

This does not happen:

![recording (6)](https://user-images.githubusercontent.com/2193314/87352072-4d488100-c50f-11ea-8208-d6c18754ea6e.gif)

Since this is the default for non-user input data, the opposite is possible via `term.scrollToBottom()`
