### ISSUE TITLE
Support event when the bell goes off

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3014]
Electron has an API to play the shell bell https://www.electronjs.org/docs/api/shell#shellbeep

To support this with xterm.js we would need to allow `bellSound` to take a `() => void`:

https://github.com/xtermjs/xterm.js/blob/ab63b5168161d5a3a93708f4dc274fadee176801/typings/xterm.d.ts#L47-L50

**Comment by bolariin** [comment]
I would like to work on this issue

**Comment by Tyriar** [comment]
@bolariin sounds good 👍
