### ISSUE TITLE
I can't enter backspace when Xterm connect to my centos8 server

### ISSUE THREAD

**Issue by xulancelee** [xtermjs/xterm.js#3022]
## Details
- Browser and browser version: Google Chrome | 84.0.4147.89 (x64)
- OS version: MyComputer:macOS 10.15.3; Server:  centos8; Bash: 4.4
- xterm.js version: 4.8.1

### Steps to reproduce

1. When I use WebScoket connect to my centos8 server and I just enter wrong content, I can del content by enter backspace key, it work like I enter an space Key。Is this a bug？How can I fix it;

**Comment by jerch** [comment]
Sounds like ssh sends other control codes than the remote system expects. This can go wrong for several reasons, e.g. an unsupported terminfo profile (inspect `TERM` variable on both systems), improper profile settings or the shell does not understand some settings (can happen with ssh'ing directly into `/bin/sh`, check `/etc/passwd` entry).

This question is better suited for stackoverflow or one of its derived forums (serverfault, unix & linux).
