### ISSUE TITLE
Terminal doesn't respond to keypresses

### ISSUE THREAD

**Issue by yvantitov** [xtermjs/xterm.js#3025]
I can't seem to get input from a `Terminal` when using xterm.js in a html page. I apologize in advance if this is a silly error on my end, but I cannot figure out what I did wrong.
## Details

- Browser and browser version: Google Chrome | 84.0.4147.89 (Official Build) (64-bit)
- OS version: Ubuntu 20.04 LTS x86_64
- xterm.js version: 4.8.1

### Steps to reproduce

1. Put this into a file:
```
<!DOCTYPE html>
<html>
  <head>
   <meta charset="UTF-8">
   <title>Broken :(</title>
   <link rel="stylesheet" href="node_modules/xterm/css/xterm.css" />
   <script src="node_modules/xterm/lib/xterm.js"></script>
  </head>

  <body>
   <div id="terminal"></div>

   <script type = "text/javascript">
      var term = new Terminal();
      term.open(document.getElementById('terminal'));
      term.writeln('Hello World!');
      term.onKey = (key, ev) => {
          console.log(`Key entered: ${key}`);
      }
   </script>
  </body>
</html>
```
2. Open it in browser (same behavior also observed when using a basic HTTP server).
3. There is a properly styled terminal but I cannot type in it. Nothing happens visually. There is also no output in the console.

**Comment by Tyriar** [comment]
> term.onKey = (key, ev) => {

term.onKey is a function:

```
term.onKey((key, ev) => {

});
```

Also you should typically be using `onData` instead.

**Comment by yvantitov** [comment]
Working now. Thanks!

**Comment by anatoly314** [comment]
> > term.onKey = (key, ev) => {
> 
> term.onKey is a function:
> 
> ```
> term.onKey((key, ev) => {
> 
> });
> ```
> 
> Also you should typically be using `onData` instead.

So, what the difference between `onKey` and `onData`? I have a similar experience where `onKey` not fired on Android's Chrome browser (except `enter`, 'backspace`) neither `onData` till I type something like `$#@!}|` then `onData` fired will all the chars been typed till now but `onKey` still keeps silence. Doubt is it a known bug or I should report it?

**Comment by Tyriar** [comment]
`onKey` fires during the keypress/keydown events when `onData` should also fire (unless `disableStdin` is on), it contains the DOM event. `onData` is the keyevent serialized such that it can be passed to a pty.

I can't repro what you're seeing. Backspace, $ and | are pressed below in the demo:

![image](https://user-images.githubusercontent.com/2193314/91559440-f515e480-e8ec-11ea-8f7a-1bdc037cbcd5.png)

**Comment by anatoly314** [comment]
@Tyriar , I will try to test more mobile browsers and let you know. It might be related only to my phone (Lineage OS on Redmi Note 4). I made a video where I recorded its behavior [https://youtu.be/hwv0NPm13oQ](https://youtu.be/hwv0NPm13oQ),  meanwhile, you can see it here [https://anatoly.dev/](https://anatoly.dev/).

**Comment by Tyriar** [comment]
@anatoly314 oh Android, they use an IME for input so key events work very differently.

**Comment by anatoly314** [comment]
@Tyriar , when I use the following code to test key inputs it works:
```
<input id="input">

const inputElement = document.getElementById('input');

inputElement.addEventListener('keyup', (event) => {
    console.log("event", event);
});
```
So, I think it's a bug in xtermjs itself

**Comment by anatoly314** [comment]
I think I know the reason why does it happen. xtermjs uses `texarea` element to capture keys and it doesn't work well with Android: https://stackoverflow.com/a/33162287/947111 there're numerous workarounds which were advised on internet but none of them work right now. 

The only thing I can't understand. When I run the demo from here: https://github.com/xtermjs/xterm.js/tree/master/demo I see that when I type something and press Enter xterm send string which I have typed to the server correctly, where did it store before sending?

**Comment by anatoly314** [comment]
Find a workaround for this issue. I paid attention that when I run on Android `onData` fired only when I press `enter` and it fired with all chars which were typed till `enter`. So I added `onData` listener which invoked only app run on Android:
```
this.terminal.onData(async data => {
            if (data.trim().length > 0) {
                await this.write(data);
                this.currentLine = data;
                await this.write("\r\n");
                await this.processCurrentLine();
                await this.printLineIntro();
            }
        });
```
Once again, the difference between regular browser that `onData` called every time you tap key, on Android it called only when you press `enter` and it contains all the chars which were typed till now.

**Comment by Tyriar** [comment]
@anatoly314 I think it's like this because the keyboard (the IME) is hanging onto the words until they are committed. This is similar to how other language keyboards work, in the below image the Japanese characters are not part of the textarea just yet, but part of the "composition" until committed.

![image](https://user-images.githubusercontent.com/2193314/92005527-75c34f00-ecf8-11ea-88bc-ba4acd3d99f0.png)

Proper mobile support would really need some more thinking on how to make the experience nice, plus you would likely require a bunch of key/modifier buttons to do things like holding ctrl and pressing esc. Right now it's out of scope for the lib until we decide to tackle https://github.com/xtermjs/xterm.js/issues/1101

**Comment by lse123** [comment]
what is the main purpose of:
used/ran the: 
`npm install xterm`
and working appearance after creating the terminal.html:
```
<script>
    var term = new Terminal();
    term.open(document.getElementById('terminal'));
    term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')

    term.onKey((key, ev) => {
        console.log(key); // getting in browser console but Not in the browser itself
    });
</script>
```
getting in browser console but Not in the browser itself, so what usages have this, and how appear text in browser in the cmd black window?

**Comment by Tyriar** [comment]
@lse123 you need to direct the key event (ideally `onData`) to something to handle the input event (like a shell via `node-pty` in the demo).
