### ISSUE TITLE
terminal replace

### ISSUE THREAD

**Issue by perfectwebtech** [xtermjs/xterm.js#3030]
hello

any guidance possible when i run with php then i connect one server sucessfully

but when i connect second third  then    first and second replace third server with credential and ip so on 

last connected connect on my past tab also is there way replace terminal class or something guidance possible ? when click on list of server and click on connect then each tab shold create new session not replace allready connected session is there way customize or something ?

**Comment by Tyriar** [comment]
It's a little difficult to tell what your actual problem is. But it sounds like a problem with whatever process you're running that's using xterm.js as a frontend, not with xterm.js itself.
