### ISSUE TITLE
Mac OSX Eclipse internal browser double input

### ISSUE THREAD

**Issue by BoykoAlex** [xtermjs/xterm.js#3037]
Launch xterm demo app
Download Eclipse for Mac OSX
Launch Eclipse and open the xterm demo app UI in Eclipse internal browser (internal browser seems to be some oldish Safari)

Type in the terminal from the keyboard - note double output:

Type `ls` the result in the terminal is `llss`

Any workarounds are very weclomed :-)

![Screen Shot 2020-08-11 at 16 18 52](https://user-images.githubusercontent.com/6433390/89944804-69af0a80-dbee-11ea-9c10-53d10d7d3504.png)

**Comment by Tyriar** [comment]
If this is just some issue with some old webkit fork it's not even worth the time investigating imo as we only support modern evergreen browsers. You might find some answers in the devtools console?
