### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by wmmihaa** [xtermjs/xterm.js#3038]
Hi,
I'm desperately trying to get my head around xterm.js, but I don't get past the first step of installation. I'm following the steps from the [Clone the Git repository (xtermjs.org)](https://xtermjs.org/docs/guides/download/), navigated to the `/demo` directory and typed:
```bash
node start.js
```
The *client-bundle.js* bundle gets created, but then proceeds to output a ton of "Module not found exceptions". See attached output.
[output.log](https://github.com/xtermjs/xterm.js/files/5059988/output.log)

## Details
- Browser and browser version: N/A
- OS version: Ubuntu 16.4, Windows 10 and WSL2
- xterm.js version: cloned from master branch at 2020-08-12

### Steps to reproduce
```
$ git clone https://github.com/xtermjs/xterm.js
$ cd xterm.js
$ npm install
$ npm run build
$ cd demo
$ node start.js
```

**Comment by Tyriar** [comment]
Instructions to run the demo are here: https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo
