### ISSUE TITLE
use xterm in react project，not compatible，input box at the top

### ISSUE THREAD

**Issue by wangxiang1** [xtermjs/xterm.js#3045]
## Details
- Browser and browser version: 
- OS version:  window10
- xterm.js version: 4.8.1

### Steps to reproduce
![image](https://user-images.githubusercontent.com/21142248/90711201-ab1c7580-e2d2-11ea-9269-de5cacf7bed9.png)

1. react project
2.

**Comment by Tyriar** [comment]
This means you're not including the css file correctly.

**Comment by qf8505** [comment]
encapsulation: ViewEncapsulation.None    angular8 used
