### ISSUE TITLE
Parsing error when press the Backspace key.

### ISSUE THREAD

**Issue by shinhwa520** [xtermjs/xterm.js#3050]
## Details
- Browser and browser version: Chrome Version 84.0.4147.125 (Official Build) (64-bit)
- OS version: Ubuntu 18.04.5 LTS
- xterm.js version: 4.2.0

### Steps to reproduce

1. Just press the Backspace key and it will output a "Parsing error" (check in the developer tools console).

xterm.js: sending data "" [127]
xterm.js: parsing data 
xterm.js: Parsing error:  {position: 0, code: 127, currentState: 0, collect: 0, params: e, …}abort: falsecode: 127collect: 0currentState: 0params: e {maxLength: 32, maxSubParamsLength: 32, params: Int32Array(32), length: 1, _subParams: Int32Array(32), …}length: 1maxLength: 32maxSubParamsLength: 32params: Int32Array(32) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]_digitIsSub: false_rejectDigits: false_rejectSubDigits: false_subParams: Int32Array(32) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]_subParamsIdx: Uint16Array(32) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]_subParamsLength: 0__proto__: Objectposition: 0__proto__: Object

**Comment by Tyriar** [comment]
You're on a pretty old version of xterm.js and whatever is being sent to it to parse depends on what is sending the data to xterm.js. Try updating and if that doesn't work you will need to elaborate on how things are hooked up.

**Comment by tino415** [comment]
Hi, I found that I have same problem on
- electron 12.0.2
- xterm 4.11.0

I also tried to downgrade to 4.10.0 but it did not resolved this problem, in mi case I got in developer tools:
```
Parsing error
abort: false
code: 127
collect: 63
currentState: 0
params: e {maxLength: 32, maxSubParamsLength: 32, params: Int32Array(32), length: 1, _subParams: Int32Array(32), …}
position: 0
```

**Comment by jerch** [comment]
@tino415 And what is the actual problem here? DEL is meaningless for the parser in the default configuration, it should not occur by normal means, and the parsing error warns about that. Question is why you have DEL in your data chunks in the first place.

**Comment by gareth-rees** [comment]
I had exactly this problem. The cause in my case was that I was using Emacs as my development environment, so that when I launched a program, it inherited the environment setting `TERM=dumb`. The problem was fixed in my case by setting `TERM=xterm` when launching the program.

**Comment by jerch** [comment]
Within the same line with `BS SP BS` (backspace space backspace, think of it as a typewriter).

**Comment by KiddoV** [comment]
I am not sure what do you mean 🤔, but I found a solution:
```ts
var curr_line = "";
var entries = [];
xterm.onKey((ev) => {
    if (ev.domEvent.key == "Enter") {
        if (curr_line) {
            entries.push(curr_line);
            xterm.write("\r\n");
            //Send cmd to backend here!
        }
    } else if (ev.domEvent.key == "Backspace") {
        if (curr_line) {
            curr_line = curr_line.slice(0, curr_line.length - 1);
            xterm.write("\b \b");
        }
    } else {
        curr_line += ev.key
        xterm.write(ev.key);
    }
});
```

**Comment by jerch** [comment]
`BS SP BS` is `"\b \b"` as js string.

Not sure what you are trying to achieve, but using `onKey` is most of the time much more cumbersome than using `onData`.

**Comment by KiddoV** [comment]
I was trying to make a simple terminal interface. User input text and terminal echo back the text. Actually trying to migrate my app from [JQueryTerminal](https://github.com/jcubic/jquery.terminal) - but seem like XTerm.JS is more complicated than I thought.

How is ``onData`` can be more "clean" than ``onKey``, since they are passing completely different arguments. ``onKey`` is clearly passing the whole ``KeyboardEvent`` for us to use. On the other hands, ``onData`` only passed the ``keystring``.

Can you throws a sample code using ``onData`` with the same functionality as I used ``onKey``?
