### ISSUE TITLE
Writing sequence `\r\n` and then reset terminal invoked at wrong order

### ISSUE THREAD

**Issue by anatoly314** [xtermjs/xterm.js#3053]
If I write `\r\n` sequence and then immediately reset terminal, the cursor is positioned at the second line. It looks like `terminal.write("\r\n")` invoked after terminal being reset despite called before.

## Details
- Browser and browser version: 
Chrome: Version 84.0.4147.135 (Official Build) (64-bit)

- OS version:  
MacOS Catalina 10.15.6

- xterm.js version:  
v4.8.1
### Steps to reproduce

1.  Invoke the following code: 
```
     this.terminal.write('\r\n');
     this.terminal.reset();
```
2. The cursor should be positioned at the first line, but it's located on the second line.

**Comment by Tyriar** [comment]
Write triggers parsing asynchronously by design, you can wait for the write like this:

```ts
this.terminal.write('\r\n', () => {
  // Parsing of \r\n is done and committed to the buffer
  this.terminal.reset();
});
```
