### ISSUE TITLE
Trouble with xterm-addon-ligatures while building

### ISSUE THREAD

**Issue by rafalsk** [xtermjs/xterm.js#3055]
We've been trying to build XTerm, (after many roadblocks we've overcome) we're currently stuck at this: ideas? yarn in installed.

`Preparing xterm-addon-ligatures
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! xterm-addon-ligatures@0.3.0 package: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the xterm-addon-ligatures@0.3.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rafal\AppData\Roaming\npm-cache\_logs\2020-08-25T15_17_40_075Z-debug.log
error Command failed with exit code 2.
child_process.js:644
    throw err;
    ^

Error: Command failed: yarn
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! xterm-addon-ligatures@0.3.0 package: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the xterm-addon-ligatures@0.3.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rafal\AppData\Roaming\npm-cache\_logs\2020-08-25T15_17_40_075Z-debug.log
error Command failed with exit code 2.

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at files.forEach.folder (D:\xterm\bin\install-addons.js:47:14)
    at Array.forEach (<anonymous>)
    at fs.readdir (D:\xterm\bin\install-addons.js:28:11)
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@4.8.1 presetup: `node ./bin/install-addons.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@4.8.1 presetup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rafal\AppData\Roaming\npm-cache\_logs\2020-08-25T15_17_40_136Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@4.8.1 prepare: `npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@4.8.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rafal\AppData\Roaming\npm-cache\_logs\2020-08-25T15_17_40_167Z-debug.log`

**Additional log info:**
52 silly postinstall xterm@4.8.1
53 info lifecycle xterm@4.8.1~postinstall: xterm@4.8.1
54 silly prepublish xterm@4.8.1
55 info lifecycle xterm@4.8.1~prepublish: xterm@4.8.1
56 info lifecycle xterm@4.8.1~prepare: xterm@4.8.1
57 verbose lifecycle xterm@4.8.1~prepare: unsafe-perm in lifecycle true
58 verbose lifecycle xterm@4.8.1~prepare: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\xterm\node_modules\.bin;C:\Users\rafal\Documents\ffmpeg-20190815-ddd92ba-win64-static\bin;D:\Oculus\Support\oculus-runtime;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\rafal\AppData\Local\Programs\Python\Python36;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\nodejs\;C:\Program Files (x86)\WinSCP\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\Mercurial\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common ;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\rafal\.windows-build-tools\python27\;C:\Users\rafal\.windows-build-tools\python27\;C:\Users\rafal\AppData\Local\Microsoft\WindowsApps;C:\Users\rafal\AppData\Local\atom\bin;C:\Users\rafal\AppData\Local\Microsoft\WindowsApps;C:\Users\rafal\AppData\Roaming\npm;C:\Program Files (x86)\Nmap;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\rafal\Documents\vcpkg-master\;C:\Users\rafal\.dotnet\tools;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin
59 verbose lifecycle xterm@4.8.1~prepare: CWD: D:\xterm
60 silly lifecycle xterm@4.8.1~prepare: Args: [ '/d /s /c', 'npm run setup' ]
61 silly lifecycle xterm@4.8.1~prepare: Returned: code: 1  signal: null
62 info lifecycle xterm@4.8.1~prepare: Failed to exec prepare script
63 verbose stack Error: xterm@4.8.1 prepare: `npm run setup`
63 verbose stack Exit status 1
63 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
63 verbose stack     at emitTwo (events.js:126:13)
63 verbose stack     at EventEmitter.emit (events.js:214:7)
63 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
63 verbose stack     at emitTwo (events.js:126:13)
63 verbose stack     at ChildProcess.emit (events.js:214:7)
63 verbose stack     at maybeClose (internal/child_process.js:925:16)
63 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
64 verbose pkgid xterm@4.8.1
65 verbose cwd D:\xterm
66 verbose Windows_NT 10.0.18363
67 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
68 verbose node v8.9.1
69 verbose npm  v5.5.1
70 error code ELIFECYCLE
71 error errno 1
72 error xterm@4.8.1 prepare: `npm run setup`
72 error Exit status 1
73 error Failed at the xterm@4.8.1 prepare script.
73 error This is probably not a problem with npm. There is likely additional logging output above.
74 verbose exit [ 1, true ]

**Comment by rafalsk** [comment]
After we've removed the 'ligatures' addon from build process it went like what follows. there's no information whether it succeeded or not just that it's up-to-date whatever it means.

`npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> xterm@4.8.1 prepare D:\xterm
> npm run setup


> xterm@4.8.1 presetup D:\xterm
> node ./bin/install-addons.js

pulling addon dependencies...
Skipped xterm-addon-attach
Skipped xterm-addon-fit
Skipped xterm-addon-search
Skipped xterm-addon-serialize
Skipped xterm-addon-unicode11
Skipped xterm-addon-web-links
Skipped xterm-addon-webgl

> xterm@4.8.1 setup D:\xterm
> npm run build


> xterm@4.8.1 build D:\xterm
> tsc -b ./tsconfig.all.json

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN jsdom@16.4.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

up to date in 11.317s`

**Comment by Tyriar** [comment]
I've never had problems with this, I'm guessing you're missing some dependencies of one of the dependencies:

https://github.com/xtermjs/xterm.js/blob/3504e2ebd577e609fd042850c51b52509efafe5a/addons/xterm-addon-ligatures/package.json#L33-L43

You could try install those deps manually and see if they error out and why.
