### ISSUE TITLE
Add hover callback for LinkProviders

### ISSUE THREAD

**Issue by Coding-Kiwi** [xtermjs/xterm.js#3056]
The LinkMatchers are eventually removed, right?
If you pass `_useLinkProvider` to the xterm-web-links-addon, there is currently no way to get a hover callback to show a tooltip.
I would like to switch to the LinkProvider but I also want to show a tooltip when hovering a link

**Comment by Tyriar** [comment]
👍 PR welcome to add the hover callback to the web link provider, it needs to get added to the result `ILink`s:

https://github.com/xtermjs/xterm.js/blob/566fad41084597496326a662446e20234dd3f749/typings/xterm.d.ts#L1146-L1153

**Comment by Coding-Kiwi** [comment]
@Tyriar this would be a quick and dirty way of passing the callbacks through, what do you think

https://github.com/Coding-Kiwi/xterm.js/commit/8d7958c3df3b6a00a3623cf591ae67e186507711

**Comment by Tyriar** [comment]
@Coding-Kiwi something like that is what I was thinking, decorating the result of `computeLinks` in a separate function would be preferable though:

```ts
const links = LinkComputer.computeLink(y, this._regex, this._terminal, this._handler);
callback(addCallbacks(links, this._options.tooltipCallback, this._options.leaveCallback);
```

Want to iterate on it in a PR?
