### ISSUE TITLE
onfocus/onblur regression

### ISSUE THREAD

**Issue by lukevp** [xtermjs/xterm.js#3057]
onfocus / onblur events used to fire from within the "on" event handler callback  `xterm.on('data', ...)` configuration for the xterm object.

Events were moved to named events `xterm.onData(...)`, and the 'focus' and 'blur' events do not fire anymore in xterm or in the TypeScript typings.

I am a maintainer for [react-xterm](https://github.com/farfromrefug/react-xterm) and want to do a new release with the latest xterm, but I'd like to keep backwards compatibility for our end-users wherever possible, and there are currently event handlers for onfocus/onblur in our library, built against an older version of xterm, that are hooked up to the onfocus/onblur events on the xterm object.

If there's a better way to provide this by hooking to DOM events in a way that works with all renderers, please let me know.

## Details
- Browser and browser version: VS Code
- OS version: Windows 10 1909
- xterm.js version: Currently 3.6.0, migrating to 4.6.0

### Steps to reproduce
List the typings with on* for xterm
![image](https://user-images.githubusercontent.com/1251016/91180381-49328600-e6ad-11ea-9a96-8cee94abfb03.png)

Previously (using "on" generic event handler)
![image](https://user-images.githubusercontent.com/1251016/91338295-57120500-e79a-11ea-893c-61a120f706c5.png)

**Comment by Tyriar** [comment]
The reason these were removed is they essentially just did `Terminal.element.addEventListener('focus' | 'blur')` so you should be able to use that to fill the gap. Since I don't think anyone has complained about it until now and you just want to provide backwards compat makes me think we made the right decision to get rid of it, so you might want to do the same 🙂

**Comment by lukevp** [comment]
Thanks for the clarification and the quick response!
