### ISSUE TITLE
A way to turn off the scrollbar

### ISSUE THREAD

**Issue by NorfairKing** [xtermjs/xterm.js#3074]
I'm implementing https://smos.online.
It's essentially a terminal user interface in the browser. (Something like mutt, but in the browser.)
This type of app really needs no scrollbar so I would like to turn it off but I can't seem to figure out how to do that.
After reading through some of the source, I'm thinking there's no option for it.

**Comment by Tyriar** [comment]
If it's just some custom app you can enter the alternate buffer which has no scroll bar `terminal.write('\x1b[?47h')` will do that I believe.

**Comment by NorfairKing** [comment]
@Tyriar I'm using the websockets plugin, I'm doing no 'manual' `terminal.write`-ing. How would I go about this then?

**Comment by Tyriar** [comment]
@NorfairKing you can try setting scrollback to 0, I think this should hide the scroll bar.

**Comment by NorfairKing** [comment]
@Tyriar I tried that but it doesn't, as far as I can tell.

**Comment by Tyriar** [comment]
Since there will never be a scroll bar if you use scrollback: 0, you can adjust styles to hide it by removing:

https://github.com/xtermjs/xterm.js/blob/master/css/xterm.css#L96

**Comment by NorfairKing** [comment]
@Tyriar I managed to remove the scrollbar but the space where the scrollbar was is still empty then (and the terminal doesn't fill it up). There are also white flashes at the border that prevent me from using borders around the terminal. They appear where the scrollbar used to be.

**Comment by magicnat** [comment]
I ran into the same issue when trying to remove the scroll bar; the scroll bar is gone, but the empty space was left behind.

It appears to be caused by the `scrollBarWidth` calculation here: https://github.com/xtermjs/xterm.js/blob/master/src/browser/Viewport.ts#L49

`this._viewportElement.offsetWidth - this._scrollArea.offsetWidth` returns 0 when there's no scrollbar, so the fallback value (15) was used.

I don't see any trivial ways to check if the scrollbar was hidden by the user, or if the user were on mac, so maybe make turning off scrollbar a configurable option?

**Comment by Puneethnaik** [comment]
I would like to work on this issue. Please guide me on the next steps, @Tyriar @jerch

**Comment by Tyriar** [comment]
@Puneethnaik I think the space caused by `scrollBarWidth` should be forced to 0 when the `scrollback` setting is also 0. Code pointer:

https://github.com/xtermjs/xterm.js/blob/33f0105d290653830bce4c48c408e73ce267ed93/src/browser/Viewport.ts#L46-L49

**Comment by Puneethnaik** [comment]
@Tyriar thanks for directing me on the next steps. I will start looking into Viewport.ts.

**Comment by Puneethnaik** [comment]
Greetings, @Tyriar I have been able to achieve the following behaviour:

https://user-images.githubusercontent.com/13706737/127314672-f3b85b61-d4d9-4580-879c-36e9773ddd4e.mp4

Is this correct? Also, in the current changes, i am manually removing overflow-y: hidden property from xterm.css.
Best Regards

**Comment by Tyriar** [comment]
@Puneethnaik looks like that's what we're after

**Comment by Puneethnaik** [comment]
@Tyriar :+1: Thanks for the feedback :slightly_smiling_face: I will create a PR for it.

**Comment by Puneethnaik** [comment]
Thanks, @Tyriar, for accepting the PR. Once again, I love the xterm.js product :+1:
