### ISSUE TITLE
xterm-addon-serialize only serialize the alt screen if the terminal is in alt mode

### ISSUE THREAD

**Issue by mmis1000** [xtermjs/xterm.js#3090]
## Details
- Browser and browser version: any (not a layout issue)
- OS version: windows/linux
- xterm.js version: https://github.com/xtermjs/xterm.js/tree/56bfdb64d47bee71b192566a5c1c2f4e7403a6a3
- xterm-addon-serialize version: https://github.com/xtermjs/xterm.js/tree/56bfdb64d47bee71b192566a5c1c2f4e7403a6a3
### Steps to reproduce

1. create a empty terminal
2. install the xterm-addon-serialize
3. write the following string into it
```js
    const SMCUP = '\u001b[?1049h'; // enable alternative screen
    const CUP = '\u001b[H'; // move  cursor to top left
    terminal.write(`1${SMCUP}${CUP}2`)
```
4. read the result using `serializeAddon.serialize()`

### Expect

You get the normal screen + alt screen in the result.
(Not sure which sequence is used to move the cursor, because there are too many ways to do it)

### Actually

You get `2`
The addon did not realize there is another screen exist.

### Note

I am not sure whether is it designed to not do it or not.
But the normal screen is required to rebuild the terminal from empty (or exit the htop will no longer bring you back to original prompt), so I guess it is missing?

I play with it a bit. [/src/SerializeAddon.ts#L192-L201k](https://github.com/mmis1000/xterm.js/blob/feature/xterm-addon-serialize-alt-screen/addons/xterm-addon-serialize/src/SerializeAddon.ts#L192-L201)

And if it should do it
1. whether it is always enabled or expose as a option?
2. do alt screen affected by the `rows` option?

**Comment by Tyriar** [comment]
Your changes seem like a good idea.

> whether it is always enabled or expose as a option?

Always would probably be fine

> do alt screen affected by the rows option?

The alt screen has no scrollback, so we could always serialize the whole thing.
