### ISSUE TITLE
why terminal wrap to 2 line when the width reached to 80?   you  can try in demo 

### ISSUE THREAD

**Issue by DasyDong** [xtermjs/xterm.js#3092]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. why terminal wrap to 2 line when the width reached to 80?   you  can try in demo 

https://xtermjs.org/
![image](https://user-images.githubusercontent.com/9334289/93089979-b3e44980-f6ce-11ea-98fd-4e510958f716.png)

2. Which params can adjust the width?  col : 160  ,not work

**Comment by Tyriar** [comment]
I don't think we're resizing when the window is resized to keep the demo simple.

**Comment by DasyDong** [comment]
> I don't think we're resizing when the window is resized to keep the demo simple. We would need to send a request to the server to resize whenever fit is run to do this.

Thanks your quick response .  In my production, I has the same issue too.   So I want to know how to resizing to fit? 

There should be a  doc to introduce this , Would you share your codes if you finished resize to fit?

**Comment by DasyDong** [comment]
#1412 same issue here

**Comment by Tyriar** [comment]
Something is broken in the demo, but this endpoint is meant to be called whenever fit is called, which triggers node-pty's resize:

https://github.com/xtermjs/xterm.js/blob/003cf969104229e2b1ffbf92c1b6c018d36f8f3c/demo/server.js#L66-L75

**Comment by DasyDong** [comment]
One import things is that do not define cols and rows with new Terminal(cols: cols, rows: rows), not work for me

Auto fit the term size by windows width , the issue is fixed ,  share the codes 
```
        let height = document.body.clientHeight;
        let width = document.body.clientWidth;
        let rows = parseInt(height/18, 10);//18是字体高度,根据需要自己修改
        let cols = parseInt(width/9, 10);
        let term = new Terminal();
        term.open(document.getElementById("terminal"));
        term.write("connecting to pod " + pod + "...")

        conn = new WebSocket(url);
        term.on('data', function (data) {
            msg = {operation: "stdin", data: data}
            conn.send(JSON.stringify(msg))
        });

        term.on('resize', function (size) {
            msg = {operation: "resize", cols: size.cols, rows: size.rows};
            conn.send(JSON.stringify(msg))
        });

        conn.onopen = function (e) {
            term.write("\r");
            msg = {operation: "stdin", data: "export TERM=xterm && clear \r"}
            conn.send(JSON.stringify(msg))
            term.resize(cols, rows)
            // term.clear()
        };
```

**Comment by Tyriar** [comment]
The demo is way nicer now
