### ISSUE TITLE
Ligatures not working with webgl renderer

### ISSUE THREAD

**Issue by UziTech** [xtermjs/xterm.js#3094]
The Ligatures addon doesn't do anything when using the WebGl addon

## Details
- Browser and browser version: Electron 6
- OS version: Windows
- xterm.js version: 
	- xterm 4.9.0
	- webgl 0.9.0
	- ligatures 0.3.0

**Comment by UziTech** [comment]
@Tyriar did this issue slip through? Can this issue get triaged?

**Comment by Tyriar** [comment]
@UziTech sorry about that, I was on leave for a few weeks and am only just almost caught up now 🙂
