### ISSUE TITLE
benchmark of xterm-addon-serialize didn't run

### ISSUE THREAD

**Issue by mmis1000** [xtermjs/xterm.js#3103]
## Details
- Browser and browser version: Not a browser error
- OS version: ubuntu
- xterm.js version: https://github.com/xtermjs/xterm.js/tree/1a0a56c1f284dd8e552a270e3a130ad2f6caa8d2

### Steps to reproduce

1. follow the instrucution to setup xterm.js repo
2. cd into `addons/xterm-addon-serialize`
3. run commands
    1. `yarn benchmark` 
        - gives nothing
        - It looks don't have test file path included.
    2. `yarn benchmark-basebline` 
        - Error: Cannot find module '/PROJECT_ROOT/addons/xterm-addon-serialize/out-benchmark/addons/xterm-addon-serialize/benchmark/*benchmark.js'
        - The addon path part duped twice for some reason
    3. `yarn benchmark-eval`  
        - Error: Cannot find module '/PROJECT_ROOT/addons/xterm-addon-serialize/out-benchmark/addons/xterm-addon-serialize/benchmark/*benchmark.js'
        - The addon path part duped twice for some reason

BTW, the test seems use `/dev/random` as random source, which is extremely slow in most of case, it is probably better change it to `/dev/urandom` instead.

**Comment by jerch** [comment]
@mmis1000 Getting the benchmark test running is abit tricky still, as it is bad hack on different project compile output settings. `yarn benchmark` currently sets `/out` as NODE_PATH, thus the benchmark suite itself starts looking from there (this is mainly to avoid re-bundling xterm.js for the benchmark tests over and over).

Quick fix to get it running:
- merge the addon out folder with the repo wide one (thus copy `SerializeAddon.js` over)
- run `yarn benchmark addons/xterm-addon-serialize/out-benchmark/benchmark/SerializeAddon.benchmark.js` from main folder

A proper fix would be to set a separate compile target of the main lib for benchmark tests (own target folder, not misusing `out`), and replay there an addon install before doing the real benchmark testing.

And yes, plz change `/dev/random` into the faster `/dev/urandom` version, no need to waste time for high secure bits here. Btw with the manual fixes above the test show this on my computer for current main branch:

```
   Context "addons/xterm-addon-serialize/out-benchmark/benchmark/SerializeAddon.benchmark.js"
      Context "Terminal: sh -c "dd if=/dev/urandom count=40 bs=1k | hexdump | lolcat -f""
         Context "serialize"
            Case "#1" : 5 runs - average throughput: 8.99 MB/s
Done in 6.31s.
```

**Comment by mmis1000** [comment]
I think the `NODE_PATH` works as intended, the current setting `NODE_PATH=../../out:./out:./out-benchmark/` do work when it is run from the package.json of `xterm-addon-serialize`.

But the `out-benchmark/addons/xterm-addon-serialize/benchmark/*benchmark.js` is incorrect.
It should be `out-benchmark/benchmark/*benchmark.js` because you are already at `addons/xterm-addon-serialize`

Run it with

```bash
NODE_PATH=../../out:./out:./out-benchmark/ ../../node_modules/.bin/xterm-benchmark -r 5 -c benchmark/benchmark.json --baseline out-benchmark/benchmark/*benchmark.js
```
from addon directory do work

Yea, but I have no idea what it is designed to run, so I open the issue here
