### ISSUE TITLE
Clarification about markers

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#3108]
Just tried to use markers for the image addon to get informed, when it is safe to free resources again. I am not quite sure how markers are supposed to be used via API. Is there a reason why `onDispose` is not exported? Is it unsafe to rely on it?

Due to this I did a quick hack with a marker collector, which checks for `isDisposed` and `line` and found that the line is still decrementing after the marker is meant to be disposed:

![grafik](https://user-images.githubusercontent.com/6193135/94004972-d4cb2f80-fd9d-11ea-8db8-60f231ee4928.png)

(The 'got disposed!' message is from my type overloading with a `onDispose` callback.)

This somewhat looks like it was not really disposed, as some code from xterm.js internals updates the now illegal line index (thus still holds a ref somehow)? Imho related code would be here: https://github.com/xtermjs/xterm.js/blob/a5e269a3f9ecdbaa240946e8724e1da9661a696d/src/common/buffer/Buffer.ts#L582-L614

@Tyriar Does this work as intended (bear with me, there is a high chance I simply dont get it :smile_cat:)

**Comment by Tyriar** [comment]
I don't think there's any reason why `onDisposed` isn't exposed. The continuing to decrement indeed looks like a leak, not sure why that is happening as `register` should ensure they're getting disposed? 🤔 

You can see where I've used markers in vscode here: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/browser/addons/commandTrackerAddon.ts#L25-L26, after a quick look this might be an issue that I'm not checking if the marker is disposed before using.

**Comment by jerch** [comment]
> I don't think there's any reason why onDisposed isn't exposed.

Imho worth to be added to the API, as getting informed is much easier to deal with than to keep inspecting actively.

> The continuing to decrement indeed looks like a leak, not sure why that is happening as register should ensure they're getting disposed?

Did not yet investigate further, but the line 608 looks somewhat fishy - though `onDispose` returns a `Disposable` itself, it looks like it will hold `this` forever (like a recursive descent)?

Thx for the pointer, will check that out.

**Comment by jerch** [comment]
@Tyriar Guess I found the bug: https://github.com/xtermjs/xterm.js/blob/a5e269a3f9ecdbaa240946e8724e1da9661a696d/src/common/buffer/Marker.ts#L27-L36

This overloads `Dispoable.dispose`, but never calls the super method, thus the registered disposables on the marker never get freed. It works for me, if I add a `super.dispose()` after line 34.

Output is now:
![grafik](https://user-images.githubusercontent.com/6193135/94126829-64351900-fe58-11ea-825f-75277bbd9b13.png)

Also note the `_isDisposed` property, which correctly is now set to `true`.

**Comment by Tyriar** [comment]
That would do it, thanks for checking it out!
