### ISSUE TITLE
Scrolling not working with specified DECSTBM in VT100.

### ISSUE THREAD

**Issue by psigma** [xtermjs/xterm.js#3111]
Scrolling not working with specified DECSTBM in VT100.
Numbers 1 - 5 outside ViewPort area
 
https://codepen.io/psigma/pen/mdPvaQv

## Details
- Browser and browser version: Google Chrome Version 85.0.4183.121
- OS version: Windows 10
- xterm.js version:  3.14.5

### Steps to reproduce

```
var terminal = new Terminal();
terminal.open(document.getElementById("terminal"));
terminal.write('\x1b[11;18r\x1b[2;1H\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[0K\x1b[2;1Ha\r\nb\r\nc\r\nd\r\ne\r\nf\r\ng\r\nh\r\n\x1b[18;1H\x1b[0m1\r\n\x1b[0m2\r\n\x1b[0m3\r\n\x1b[0m4\r\n\x1b[0m5\r\n\x1b[0m6\r\n\x1b[0m7\r\n\x1b[0m8\r\n\x1b[0m9\r\n\x1b[0m10\r\n\x1b[0m11\r\n\x1b[0m12\r\n') ;  
```

**Comment by jerch** [comment]
@psigma Can you give abit more context information, like what did you expect and where the actual output differs from your expectation?
To me this seems to work as intended, the lines with 1-4 are scrolled out, while the lines with the letters above are still in the viewport.

**Comment by psigma** [comment]
@jerch I expect that scollbar appears on the right side and allow me to scroll to these 1-4 lines

**Comment by jerch** [comment]
> I expect that scollbar appears on the right side and allow me to scroll to these 1-4 lines

The scrollbuffer of xterm.js will only kick in, if the top scroll border is the first line. This is not the case here (you have "frozen" lines above). Without it being the first line, the scrolled out lines are lost.
