### ISSUE TITLE
is there a way to customize terminal input style with my own js, css or html element ?

### ISSUE THREAD

**Issue by dlanorf** [xtermjs/xterm.js#3124]
is there a way to customize terminal input style with my own js, css or html element ?
I just want to customize the prompt input part, not the whole terminal.

## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce
![image](https://user-images.githubusercontent.com/44251003/95725778-aa88d580-0caa-11eb-80bc-bdbc803957aa.png)

**Comment by jerch** [comment]
What can be customized:
- font family
- font size
- terminal palette colors through a custom theme

> I just want to customize the prompt input part, not the whole terminal.

No, it is not possible to only style certain parts of the output from terminal side, as the terminal has no knowledge about where the prompt starts/ends. You have to do this on the other end (the program that create the prompt).
