### ISSUE TITLE
AltGr on German keyboard layout does not work with Chrome version 86.0.4240.75 (however Chrome 85 works)

### ISSUE THREAD

**Issue by corneliusludmann** [xtermjs/xterm.js#3129]
Since the Chrome update to version 86, I cannot type `|` (which is `AltGr + <` on German layout) or `~` (`AltGr + +`) anymore. Instead of `|` the char `<` appears, instead of `~` the char `+` appears.

On a second laptop, I still have Chrome 85.x.x.x with Arch Linux and German keyboard layout and there everything works fine. Thus, I suspect it has something to do with the Chrome update. However, I cannot exclude with certainty that another update on my system has caused this.

I noticed it inside [Gitpod](https://gitpod.io) which uses xterm.js in [Theia](https://theia-ide.org/). However, it also happens with the demo at https://xtermjs.org/.

## Details
- Browser and browser version: Chrome Version 86.0.4240.75 (Official Build) (64-bit)
- OS version: latest Arch Linux
- xterm.js version: 4.9.0

### Steps to reproduce

1. Open the demo at https://xtermjs.org/ with Chrome 86.0.4240.75
2. Type `AltGr + <`
3. `|` should appear but `<` appears. With Chrome 85 everything works fine.

## Related issues:
- #33

**Comment by jerch** [comment]
@corneliusludmann Yes I can repro the issue with master under Ubuntu 18 as well. This is a real showstopper, as many programming characters on german keyboard layout are behind 3rd shift, geez.

**Comment by mofux** [comment]
Just tested with Chromium 86.0.4240.111 on Arch Linux with german keyboard layout, `AltGr + <` produces `|` just fine. Weird. Can you reproduce with the most recent Chrome version?

**Comment by corneliusludmann** [comment]
> Can you reproduce with the most recent Chrome version?

I'll be happy to test this with the latest Chrome version. However, I'm not able to do this before Monday since I'm out of office this week.

**Comment by jerch** [comment]
@mofux Good find. Yes it looks they reverted some earlier attempt to get rid of xlib deps: https://chromium.googlesource.com/chromium/src/+/4fb89e020e3e3b1504fca92dbc8ab807202f7e9c%5E%21/#F0.

**Comment by corneliusludmann** [comment]
> Can you reproduce with the most recent Chrome version?

I can confirm that with Chrome version 86.0.4240.111 it works again. Thanks! I'll close this issue.
