### ISSUE TITLE
Is there some examples for xterm fullscreen?

### ISSUE THREAD

**Issue by TreHack** [xtermjs/xterm.js#3130]
Is there some examples for xterm fullscreen?

**Comment by theflyingape** [comment]
Browser (F11 or Chrome key) for fullscreen or click Disconnect and click Install as an app: https://play.ddgame.us
Re-launch using the app icon.

xterm resizing is done off window.onresize() event (line 100): https://github.com/theflyingape/dankdomain/blob/master/src/door/client.ts
