### ISSUE TITLE
How to support gbk encoding?

### ISSUE THREAD

**Issue by leewill1120** [xtermjs/xterm.js#314]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 
### Steps to reproduce
1. 
2.

**Comment by parisk** [comment]
@leewill1120 xterm.js already supports CJK characters. I have no experience with GBK encoding, so I think we need some more information on "where would you like to use it" and most probably a PR 😅  .

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
