### ISSUE TITLE
Update to webpack 5 

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3154]
The dependency needs additional changes https://github.com/xtermjs/xterm.js/pull/3152, up for grabs if anyone's game. I'd expect it to be fairly easy for anyone familiar with webpack.

**Comment by nasrob** [comment]
Hello @Tyriar, I'd like to work on this issue, could you assign it to me?

**Comment by Tyriar** [comment]
@nasrob sure, GitHub lets us do that now 🙂, note there are several webpack configs in various folders, the addons can be build via `npm run package` in the addon folders.
