### ISSUE TITLE
Uncaught RangeError: The value of "offset" is out of range. in ligatures addon

### ISSUE THREAD

**Issue by UziTech** [xtermjs/xterm.js#3174]
When ligatures addon is used this error happens for some users.

```
// x is a number that seems to change depending on the user.

Uncaught RangeError: The value of "offset" is out of range. It must be >= 0 and <= x. Received x+2

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= x. Received x+2
    at boundsError (internal/buffer.js:73:9)
    at Buffer.readInt16BE (internal/buffer.js:493:5)
    at /packages/x-terminal/node_modules/font-finder/dist/tables/os2.js:56:29)
    at /packages/x-terminal/node_modules/font-finder/dist/parse.js:95:65
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

related https://github.com/bus-stop/x-terminal/issues/204
related https://github.com/bus-stop/x-terminal/issues/206
related https://github.com/bus-stop/x-terminal/issues/211

## Details
- Browser and browser version: Atom
- OS version: Windows 10 Pro & Mac OS X 10.13.6
- xterm.js version: xterm v4.9.0; ligatures v0.3.0

### Steps to reproduce

1. load ligatures addon
2. start typing

See [this youtube video](https://www.youtube.com/watch?v=d0gx5FX1064)

I am not able to reproduce it but a few others have been. After lots of debugging it seems to be when certain fonts are installed on the system (although we are not sure which ones).

The issue seems to happen when font-finder loads all of the fonts.

**Comment by Tyriar** [comment]
Looks like an issue in https://github.com/princjef/font-finder
