### ISSUE TITLE
Cursor blink on page load

### ISSUE THREAD

**Issue by oriooctopus** [xtermjs/xterm.js#3176]
We want to make it as clear as possible to the user that the terminal they see is interactable, and one way to do this is to make the teminal start blinking on page load. RIght now I can specify `{cursorBlink: true}` but that won't have it blink by default, it will only blink when focused.

TLDR: Can we add an option to make the cursor always blink, instead of blinking when focused

**Comment by jerch** [comment]
Does `Terminal.focus` not work for you? You can use it as shown in the demo page:

https://github.com/xtermjs/xterm.js/blob/84fa6be370f9a6b6ced5ece234d2ed1046f0229e/demo/client.ts#L183-L185

**Comment by jerch** [comment]
Closing, feel free to reopen if explicit calling `Terminal.focus()` does not help with your issue.

**Comment by oriooctopus** [comment]
Sorry! Thank you for your response... unfortunately I am not using this package anymore
