### ISSUE TITLE
The rave is showing on xterm-cursor-layer

### ISSUE THREAD

**Issue by DouglasXiaoMS** [xtermjs/xterm.js#3177]
When opening a Terminal with xterm as rendering, the strange rave is shown up in xterm-cursor-layer.

## Details
- Browser and browser version:  Chrome 86.0.4240.198
- OS version: Win 10
- xterm.js version: 4.8.1

### Steps to reproduce

1. Open a terminal
2. Do any operations like input commands

![MicrosoftTeams-image (22)](https://user-images.githubusercontent.com/74578557/99339252-ae27f300-283a-11eb-95ec-b8dce29b521f.png)

**Comment by jerch** [comment]
@DouglasXiaoMS Very artistic :smile_cat: 

This prolly happens with canvas renderer due to some browser engine <--> graphic card driver issues. It has been reported by ppl after hibernation and such. There is not much we can do about it. You can try to use the DOM or the webgl renderer instead.

**Comment by mofux** [comment]
I'm closing this issue for now as there's not much we can do about it. Feel free to reopen if you feel otherwise.

**Comment by Tyriar** [comment]
I got a similar report in codespaces for web, I agree that it's a browser/gpu driver problem that we can't do much about. Switching renderer is a workaround, DOM for example while slower will prevent issues like this.

**Comment by DouglasXiao** [comment]
@jerch , thanks for the comments, may I get to know more about the DOM or the webgl renderer? is the renderer one of the options in xTerm?

**Comment by Tyriar** [comment]
@DouglasXiao https://github.com/xtermjs/xterm.js/blob/a73fe62b7aedcd331e01130b92d7e753bb5be55b/typings/xterm.d.ts#L188-L196

The webgl renderer: https://www.npmjs.com/package/xterm-addon-webgl

**Comment by DouglasXiao** [comment]
Thanks @Tyriar , looks like if using DOM renderer type, we don't need to import extra xterm-addon-webgl library

**Comment by Tyriar** [comment]
That's right, it's slower is the main thing because it manipulates the DOM to display the chars..
