### ISSUE TITLE
cursor

### ISSUE THREAD

**Issue by yyy19961027** [xtermjs/xterm.js#3179]
## Details
- Browser and browser version:IE10
- OS version: win10
- xterm.js version: 

### Steps to reproduce

1. After re-adjusting the terminal size, the cursor position cannot adapt to the text height to the bottom end, and the cursor position is in the middle of the text.

**Comment by jerch** [comment]
You prolly forgot to resize the underlying PTY. The size of xterm.js and the PTY should always be in sync, otherwise random output bugs will happen.
