### ISSUE TITLE
Terminal cannot enter commands

### ISSUE THREAD

**Issue by yyy19961027** [xtermjs/xterm.js#3183]
Some computers run demo, enter commands, the commands are not displayed in the terminal, and the console reports an error indicating that the websocket connection is disconnected
## Details
- Browser and browser version: google
- OS version: win10
- xterm.js version: 4.9.0
- node :15=4.15.0
### Steps to reproduce

1. start the demo
2.  enter commands
Display as follows：
![terminal -error](https://user-images.githubusercontent.com/66300848/100299110-ce3f7b00-2fcd-11eb-8763-5edb684f998f.png)

**Comment by yyy19961027** [comment]
node:14.15.0

**Comment by Tyriar** [comment]
I can't reproduce, does the error go away if you move it to a different folder without CJK characters? It's unclear what you've changed from the xterm.js demo as well.

**Comment by yyy19961027** [comment]
&nbsp; I haven't changed the example. The example that I run directly will run normally on my computer, but it will not work on other people's computers.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xtermjs/xterm.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 凌晨3:49
收件人:&nbsp;"xtermjs/xterm.js"<xterm.js@noreply.github.com&gt;;
抄送:&nbsp;"一步一步向前走"<1551817482@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xtermjs/xterm.js] Terminal cannot enter commands (#3183)





 
I can't reproduce, does the error go away if you move it to a different folder without CJK characters? It's unclear what you've changed from the xterm.js demo as well.

**Comment by jerch** [comment]
@yyy19961027 This does not look like an xterm.js issue. The error is thrown in `mws\lib\receiver.js` and the error `EPIPE` indicates, that it comes from OS file/socket interaction. xterm.js does not know/throw that error.
