### ISSUE TITLE
Microsoft Pinyin IME are duplicating some inputs

### ISSUE THREAD

**Issue by ZxBing0066** [xtermjs/xterm.js#3191]
## Details
- Browser and browser version: chrome 80+
- OS version: window 10
- xterm.js version: 4.3.0 - latest

### Steps to reproduce

1. A demo here: https://codesandbox.io/s/crimson-frost-s11ts?file=/src/index.js:0-267
2. Use Microsoft Pinyin number input, and then input numbers or symbols

A simple demo
```jsx
import { Terminal } from 'xterm';
import 'xterm/css/xterm.css';

const term = new Terminal();

term.open(document.getElementById('terminal'));
term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')

term.onData(data => {
  console.log(data);
  term.write(data);
});
```

same to #1527, but it's closed

**Comment by kena0ki** [comment]
I confirmed this issue also occurs with full-width space as pointed in the issue #1548.
The reason why the input characters are duplicated is  that `CompositionHelper._handleAnyTextareaChanges` and `CompositionHelper.compositionend` are called from `keydown` event and `compositionend` event respectively.

FYI:
In VS Code, `compositionend` event is not  fired at the time the characters input (why?), so  `CompositionHelper.compositionend` is not called and thus the issue does not happen.
