### ISSUE TITLE
got wrong text on paste for long characters

### ISSUE THREAD

**Issue by agusmakmun** [xtermjs/xterm.js#3192]
For somehow the xtermjs got wrong text on paste mode. which is I have paste this:

    curl -X GET https://unix.stackexchange.com/questions/225062/how-can-i-copy-text-from-xterm-awesome-debian-virtualbox

Then the xtermjs not rendered well.

[![bug xterm paste][1]][1]

> But, when I paste the short text. it worked well, e.g:
> `curl -X GET https://stackoverflow.com`

  [1]: https://i.stack.imgur.com/pPh0F.gif

## Details
- Browser and browser version: Chrome Version 86.0.4240.111 (Official Build) (64-bit)
- OS version: Linux Ubuntu Ubuntu 20.04.1 LTS (64-bit)
- xterm.js version: 4.3.0

### Steps to reproduce

1. Run with socket, for more details: https://stackoverflow.com/q/65208155/6396981

**Comment by Tyriar** [comment]
That's a really old version of xterm.js, also your pty and terminal may have their dimensions out of sync.
