### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by Michdo93** [xtermjs/xterm.js#3195]
After I run sudo npm start I get:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xterm@2.3.2 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@2.3.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I am working with Ubuntu 16.04 and nodejs v8.17.0

**Comment by jerch** [comment]
xterm@2.3.2 :fearful:, maybe try a newer release?

**Comment by mofux** [comment]
I'm closing this issue as there hasn't been any response. Feel free to re-open.
