### ISSUE TITLE
Chinese special characters are displayed twice

### ISSUE THREAD

**Issue by zhangyu19940118** [xtermjs/xterm.js#3196]
In the Chinese input method environment, input special characters, it will be displayed twice.

## Details
- Browser and browser version: Chrome87
- OS version: Windows10
- xterm.js version: 4.9.0

### Steps to reproduce

1. open Terminal
2. Switch to Chinese input method
3. input special characters，eg：-; %; （）;

**Comment by kena0ki** [comment]
This is a duplicate of #3191.

**Comment by mofux** [comment]
Let's close this issue in favour of #3191.
