### ISSUE TITLE
When there is too much data at a time, the previous data will not be displayed

### ISSUE THREAD

**Issue by HMenen** [xtermjs/xterm.js#3198]
## Details
- Browser and browser version: Chrome  87.0.4280.88
- xterm.js version: 4.9.0

### Steps to reproduce
When there is too much data at a time, the previous data will not be displayed

**Comment by mofux** [comment]
I'm not quite sure what you mean. The terminal has a scrollback buffer that is limited to a certain amount of lines (I believe it's 1000 by default, haven't checked). The size of the scrollback buffer is configurable as a terminal option, see https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#optional-scrollback

You may want to increase the scrollback buffer, so more lines can be shown before the buffer is cycled.

If this doesn't help, then please provide a more detailed description of your problem, or ideally a screen capture that shows the problem.

**Comment by jerch** [comment]
@HMenen xterm.js gives no guarantee whether some data will ever be displayed on the screen for two reasons:
- high data input pressure without any flow control might lead to data drops to avoid OOM - this data is def. lost
- no slow scrolling mode - output is updated by a framerate, if you happen to write more data between screen updates than the terminal buffer can hold, the beginning of that data cannot be shown

**Comment by Tyriar** [comment]
Closing this as designed. Lots of data means it won't display on screen and/or may never reach the user, I think most users would expect this.
