### ISSUE TITLE
Code Climate refactoring

### ISSUE THREAD

**Issue by misogihagi** [xtermjs/xterm.js#3199]
I use part of xtermjs in my app, also code climate.
code climate said below
https://codeclimate.com/github/misogihagi/TeraterMEN/client/src/evaluateKeyboardEvent.ts/source#issue-8fa5e9901acbe9dff684d16b4a2a0102

After finishing, I may send pull request.
I can't say issue though

**Comment by mofux** [comment]
This file has many if / switch statements and variable declarations which might be causing this high complexity, but I don't think it has to be refactored. For me as a human this file is very easy to parse.
