### ISSUE TITLE
[Feature]: add a `forceOpaque` option for themes

### ISSUE THREAD

**Issue by Nokel81** [xtermjs/xterm.js#3208]
Currently xterm will warn when the css colours provided in a theme either do not set the alpha channel or have an alpha channel that is not `0xFF` equivalent.

Namely, I see a lot of the following errors:

```
Color: #eeeeec is using transparency, but allowTransparency is false. Using fallback #eeeeec
```

It would be nice to be able to silence these errors. I could add the `FF` to the end of the colours but I believed that it is generally assumed that if the alpha channel is not set then it is assumed opaque. Maybe this is not the case, but could such an option be added?

**Comment by Tyriar** [comment]
If you're getting the warning just using `#eeeeec` then that's definitely a bug. I don't think I've seen this error though 🤔

**Comment by Nokel81** [comment]
I am using `"xterm": "^4.6.0"`

**Comment by Nokel81** [comment]
I see that there is a new version, let me try that

**Comment by Tyriar** [comment]
Yeah maybe that's it, 4.6 is pretty old if that's the version you're locked to.

**Comment by Nokel81** [comment]
Updating to `4.9.0` did not fix the issue. I am doing roughly the following:

```ts
const xterm = new XTerm(...);

xterm.setOption("theme", {
    "brightBlack": "#eeeeec",
    ...
});
```

**Comment by Tyriar** [comment]
I can't seem to repro in the demo:

![image](https://user-images.githubusercontent.com/2193314/104031536-b426ba00-5181-11eb-934a-b017ebc4b917.png)

At least not just with `brightBlack`, though I believe it shouldn't matter as that color will get parsed.

**Comment by Nokel81** [comment]
After trying out the in-repo demo. It is true that I don't see that. However, I also don't see any `console.log` or `console.warn` that I manually add to the `Terminal.ts`. Such as in `_updateOptions`.

**Comment by kena0ki** [comment]
You may need to build. Changes of the files in `src` directory are not automatically reflected to the demo by `yarn start`.

**Comment by Nokel81** [comment]
Thanks, will try again

**Comment by Nokel81** [comment]
FYI , this seems to mainly happen when I run my test suite (using `jest`). And the following is the stack trace on the `console.warn` call. 

```
  console.warn
    Color: #eeeeec is using transparency, but allowTransparency is false. Using fallback #eeeeec.

      at e._parseColor (node_modules/xterm/lib/webpack:/src/browser/ColorManager.ts:189:17)
      at e.setTheme (node_modules/xterm/lib/webpack:/src/browser/ColorManager.ts:143:33)
      at t._setTheme (node_modules/xterm/lib/webpack:/src/browser/Terminal.ts:539:25)
      at t._updateOptions (node_modules/xterm/lib/webpack:/src/browser/Terminal.ts:243:14)
      at call (node_modules/xterm/lib/webpack:/src/common/CoreTerminal.ts:109:66)
      at e.fire (node_modules/xterm/lib/webpack:/src/common/EventEmitter.ts:55:16)
      at e.setOption (node_modules/xterm/lib/webpack:/src/common/services/OptionsService.ts:107:26)
```

Note: there is no file `node_modules/xterm/lib/webpack` so it is hard for me to dive deep into the actual code being run but I will try again today.

**Comment by Nokel81** [comment]
I have narrowed down the issue to `@testing-library/react` and will file a bug over there instead. If a `Terminal` is rendered under the `@testing-library/react`'s `render` function then the created `canvas`'s function `this._ctx.getImageData(0, 0, 1, 1).data` always returns an `Uint8ClampedArray` of `[0, 0, 0, 0]`. Even though the `fillStyle` is reported correctly as the previously set value of `css`. 

(Note I am talking abou the `_parseColor` method in `src/browser/ColorManager.ts`)

**Comment by Tyriar** [comment]
Oh ok, thanks for following up 👍

**Comment by Nokel81** [comment]
You are welcome. I noticed that it was only warning when I was running the code in unit tests. And I used a symlink in `node_modules` to a local of copy of `xterm.js` for adding `console.log` statements which lead me to the discovery that in testing no matter what value was set to `fillStyle` the function `getImageData` always returned a wrong result. But when I ran in a browser I saw reasonable results I realized that it must be something to do with the `canvas` and that is when I discovered that testing package.

Sorry about raising a non-issue.

**Comment by Fang-** [comment]
> If you're getting the warning just using #eeeeec then that's definitely a bug.

Seeing this now while setting fore/background to values like `'#000000` and `'#ffffff'`... but only in Chrome (89), on Firefox (87) it doesn't complain.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/3829764/111004066-9398fd00-8388-11eb-9313-d45d8366d2ab.png">

A little bit confused about prior discussion here and whether or not this is within xterm.js's control, but my case seems different enough from @Nokel81's to report just in case. I get this for both dev and production bundles, don't use jest or `@testing-library/react`, etc.

**Comment by Tyriar** [comment]
@Fang- it's likely a bug on xterm.js' side, can you create a new issue with details?

**Comment by Fang-** [comment]
Hmm, I tried reproducing again, but I can no longer get this to happen. _Something_ is afoot, but I'm not sure what or where... I'll refrain from filing until I have a consistent repro.
