### ISSUE TITLE
mouse clicks don't work in xterm/vscode terminal

### ISSUE THREAD

**Issue by nojvek** [xtermjs/xterm.js#3224]
used webssh2 to test this https://github.com/billchurch/webssh2

### Steps to reproduce

1. Install https://github.com/billchurch/webssh2
2. Install https://github.com/Yomguithereal/react-blessed
3. Run `yarn demo hooks`

![image](https://user-images.githubusercontent.com/1018196/105251921-41c6ba00-5b31-11eb-8c2d-eec9e453ed99.png)

Clicking on + / - buttons should increment and decrement counter, but nothing happens. Tried in vscode terminal and webssh2 (which both use xterm.js under the hood). I am not sure how to invoke xterm.js directly connected to local machine.

Question behind question (qbq) is that I want to make a terminal interface that supports mouse clicks and drags. However it seems to be broken in vscode (which uses xterm as downstream dependency). It works in built in Mac OS Terminal app.

**Comment by Tyriar** [comment]
This is likely https://github.com/microsoft/vscode/issues/96058; vscode's mouse support has been partially broken for a while as `onBinary` never got hooked up.

**Comment by nojvek** [comment]
I got the demo up after a bunch of trial and error. Confirmed that mouse support does work in demo indeed. 

Would love to land it in vscode. Happy to make a PR if this is relatively straight forward.
