### ISSUE TITLE
file:/// support

### ISSUE THREAD

**Issue by xenoterracide** [xtermjs/xterm.js#3226]
referencing https://github.com/vercel/hyper/issues/5133, and I'm just copying the description from there, a developer said I need to file an issue here.

> so... spotbugs for gradle is lovely... it gives me a file:// link to the report. I'd like this to open in my browser, which I believe is the default configured behavior... at least that's what terminus with the link plugin does. I believe I've seen something else do it too, but I can't remember what/when. Honestly this is reason 1 that I'm seeking a new terminal, reason 2 is that I'm going to be using windows again, and might be nice to use the same terminal everywhere.

**Comment by Tyriar** [comment]
Hyper can now use the link provider API to do this, this is what the web links addon is built on.

**Comment by LabhanshAgrawal** [comment]
@Tyriar will it be possible to export the `WebLinkProvider` [class](https://github.com/xtermjs/xterm.js/blob/4b29b8a9c67053140c9ccf608550cbb4cee959e7/addons/xterm-addon-web-links/src/WebLinkProvider.ts#L8) used in the addon also in the npm package?
Don't want to replicate everything. If it becomes available then, we'd be able to use it providing just the regex and handler.

**Comment by Tyriar** [comment]
@LabhanshAgrawal the best way to implement a link provider is by writing a parser, it's a bit hacky the way `WebLinkProvider` does it by translating the string indexes to/from buffer indexes to support regex. I don't really want to export it because of this, I'd just say replicate the file or write a parser for `file:///`.

**Comment by LabhanshAgrawal** [comment]
Can you elaborate a bit on what you mean when you say parser?
From what (little) I got from the code is we get the line number and then get the buffer using that. Do you mean I should do the checking on buffer directly? Or to write my own code for the
> translating the string indexes to/from buffer indexes

part
What is the intended way of using the api?

**Comment by Tyriar** [comment]
@LabhanshAgrawal the problem with web links is it needs to convert to a string and then back again, the width of characters and differ in a regular string and on the buffer so it's tricky to get them to match up so the link has the right start/length.

The intent is to use the buffer API directly, for example a provider would get `Terminal.buffer.active.getLine`, and then iterate through it calling `getCell()` searching for `file:///`, once found it would keep going until some character that doesn't belong in the path (eg. `" "`). Doing it this way is faster as you don't need to run the regexes on the whole line and don't need to mess with string indexes.

**Comment by LabhanshAgrawal** [comment]
Got it, I'll give it a try and see if I can get it to work. If it's good then maybe I can try to update the addon also.

**Comment by LabhanshAgrawal** [comment]
@Tyriar can you please give any example string for which the width of characters would be different in string and buffer. It will help in testing this out.

**Comment by jerch** [comment]
@LabhanshAgrawal

- string width 1, cell width 1:
  - all narrow/halfwidth codepoints in BMP (western chars, normal digits, basic interpunction)
  - examples: `'abc123,?!'`
- string width 1, cell width 2:
  - many of earlier specced CJKs (inherited from UCS-2, thus within BMP)
  - example: `￥` (official fullwidth version)
- string width 2, cell width 1:
  - all combined characters on halfwidth BMP base char, narrow codepoints > BMP
  - example: `'e\u0301'` (e with accent as in café), `'𝄞'`
  - any narrow codepoint > BMP (not sure if there are any defined that way)
- string width 2, cell width 2:
  - newer CJK > BMP, combined on fullwidth chars, most emojis (warning: some are still narrow, also depends on used unicode version)
- string width >2, cell width >= 2:
  - complicated grapheme rules (not supported by xterm.js currently)
  - examples: national flags 🇦🇩, combining emojis (color attr, multiple stacking persons)

**Comment by LabhanshAgrawal** [comment]
Ended up creating https://github.com/LabhanshAgrawal/xterm-link-provider based on the WebLinkProvider class. Didn't want to copy it into hyper and thought it might be useful for other people too.
I think I've handled most of the string and cell width issues, do give it a look if you can.
