### ISSUE TITLE
How to get input command

### ISSUE THREAD

**Issue by liuzhenxiaoqqq** [xtermjs/xterm.js#3250]
Requirements: Record which commands the current user has executed

I hope that the api can get the input commands to facilitate users to perform other operations.

**Comment by jerch** [comment]
In a terminal there is no command definition per se, terminal input is always an application context dependent stream of characters, e.g. while the input of `['l', 's', '\r']` at an OS shell prompt would execute `ls`, the same input will have a quite different meaning in other apps (like an editor would just add 'ls' to it char buffer and move the cursor to the line beginning). It is simply not possible to get a hold of a "command" without taking application side state into consideration. It is the application that gives the input the concrete meaning and spans its "command space".

Therefore this is not possible in a straight foward way. To still get something similar as you described:
- narrow down apps, where you would scan for commands (note: very hard to achieve in a reliable way as you'd need additional state information from app side of the PTY)
- identify the shape of legit or expected commands, maybe as regexp rules of the command space
- collect data from `Terminal.onData`
- match collected data against command shapes --> list of commands
