### ISSUE TITLE
xterm broken after Chrome/Edge update

### ISSUE THREAD

**Issue by stefacc** [xtermjs/xterm.js#3252]
Hi guys,
we are using xterm.js in our internal website, but for a few days it is not possible to write anything in it.
I see that only the "space bar" works.

We have this behavior in Chrome (89.0.4389.90), Canary (91.0.4449.3), Edge (89.0.774.54) but not in Firefox (86.0.1) and Chrome portable (88.0.4324.104) where it works quietly.

Thanks 

**UPDATE**:
we debugged the code more thoroughly and found it:
- term.textarea.onkeydown (we are using it) is activated when the keys are pressed outside the chars (space, tab, etc.) only
- term.textarea.onkeypress dosn't work
- term.textarea.onkeyup works, but it changes a little the ux

**Comment by jerch** [comment]
@stefacc Cannot repro it with 89.0.4389.90 under Ubuntu with our repo demo. Does this only happen under Windows?

Plz test, if `term.onData` is still sending input correctly with your chrome versions (you can do that by running our demo and see if the input still shows up correctly).
Which leads to the next question - Is there a specific reason why you hook into the plain DOM events on the textarea? There is a high chance that this might collide with some of the default listeners, as those bubble or stop plain events under various conditions to get char composition correctly done (dead keys, IMEs and such).

**Comment by Tyriar** [comment]
I tested the demo on Windows with Chrome 89.0.4389.90 and Edge 91.0.825.0 and it worked fine, so I'm pretty sure the issue would be on your end somewhere.

As @jerch is indicating, If you set `onkeydown`, `onkeypress`, `onkeyup` properties this would very likely break xterm.js, use `addEventListener` instead and be sure to allow event propagation (don't `preventDefault` unless that's really what you want to do).
