### ISSUE TITLE
writeSync error is a bit too loud

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3255]
I think we should use the log service so this doesn't surface in devtools unless logs are enabled:

https://github.com/xtermjs/xterm.js/blob/145b4874cb217d7c23b46c731a2bb9a780b66c3f/src/common/CoreTerminal.ts#L138

This happens in vscode right now and I wasn't planning on removing it yet as it will be a bit of a pain to get rid of it in the reconnect logic:

<img width="549" alt="Screen Shot 2021-03-18 at 5 23 11 AM" src="https://user-images.githubusercontent.com/2193314/111625598-44006a00-87aa-11eb-929f-b344e15acd31.png">

**Comment by jerch** [comment]
Heavy console bombardment :sweat_smile:

Hmm this will still flood the console under DEBUG, if the type ahead triggers it for each input char. Do we need a debounce on this error?

**Comment by Tyriar** [comment]
Can we use `logService.warn`? I think that won't log by default. I'm fine bringing this back when VS Code adopts it to raise awareness but maybe we should just be logging it once per session?
