### ISSUE TITLE
Access to applicationCursorKeys

### ISSUE THREAD

**Issue by drgrussell** [xtermjs/xterm.js#3263]
I am updating SSHy to make use of the latest xterm.js. This application gives you a javascript SSH client. It was running on quite an old xterm.js.
I have everything working, except the cursor keys when the system is in application keys mode. This flag indicates that I would need to send any cursor key codes in a slightly different format to the SSH server. The flag is held deep inside xterm.js, but no longer is accessible.

Is there a way to access applicationCursorKeys?
this._coreService.decPrivateModes.applicationCursorKeys
Perhaps also isMac and macOptionIsMeta? Would make coding easier...

Or am I being silly and is there a better way of knowing if we are in application keys mode or not?

Thanks
Gordon.

**Comment by Tyriar** [comment]
While I'm not opposed to exposing this in the buffer API as we will need it to be able to serialize the buffer for the serialize addon, I'm not sure why you need it though. If you press keys while xterm.js is focused, it handles translating them into text that is sent over. If for some reason you want to add a button or something to trigger the same as an arrow key, I'd recommend creating a synthetic event and dispatching that on the xterm textarea.

**Comment by drgrussell** [comment]
Maybe we have been doing it wrong.  :-(
We are catching the keypresses ourselves via attachCustomKeyEventHandler then translating it ourselves into xterm codes.
Is there a handler which gives us the processed code translations?

**Comment by Tyriar** [comment]
If you just don't cancel the event via `attachCustomKeyEventHandler` it should just work, if you need to do something else when one of these keypresses happen you could still not cancel it and trigger whatever custom logic you need.

**Comment by drgrussell** [comment]
Sorry to ask stupid questions...
Is there a handler which will give us the keys coming from the terminal already translated into xterm codes. So cursor escape codes for instance? Is that onData? So when a user hits up arrow I get different codes via onData to match whatever applicationCursorKeys mode we are in?

**Comment by drgrussell** [comment]
Sorry about that. I just tested it and it does indeed do the hard work for us already.
All makes much more sense now.
Thanks for the help, and thanks for providing the package.
