### ISSUE TITLE
Make the DOM renderer the default and move the canvas renderer into an addon

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3271]
No need to load the code if it's not being used. VS Code has recently transitioned to webgl as the default: https://github.com/microsoft/vscode/issues/106202

Note that I decided we should probably keep the canvas renderer since otherwise Safari/iPad/etc. are stuck with the much slower DOM renderer. The canvas renderer is much better than that and doesn't really need much maintenance at this point.

**Comment by ejose19** [comment]
Commenting here as https://github.com/microsoft/vscode/pull/120131 & https://github.com/microsoft/vscode/issues/106202 are locked.

On latest build, I noticed a lot of lag on the integrated terminal, previously I was using `"terminal.integrated.rendererType": "canvas"` in order for it to work properly, but that setting doesn't exists anymore (as removed by linked PR). I had to manually toggle "Gpu Acceleration" off to get previous performance, maybe the `auto` detection could be improved? I'm using vscode in a VM with no kind 3d/gpu acceleration, yet it somehow deducted to use it.

**Comment by jerch** [comment]
:+1: for that idea. Imho it is ok to have just one default renderer in the base bundle, and the logical choice would be the DOM renderer. It has a much smaller code footprint and works well enough for casual integrations.

Few notes though:
- DOM renderer still misses some features (e.g. hide cursor is currently not working)
- Do we need a renderer API? I know that we discussed that before, and kinda ended up with private imports in the webgl addon. I dont see a proper API as mandatory step (in fact I am quite happy how easy it is to step into privates, have to use it myself in the image addon). Still private imports create a nasty entanglement between core and addons with all downsides in maintainability and code quality/testing. Maybe this is the chance to get a more formal interface at least reducing the "private pressure".

**Comment by Tyriar** [comment]
Hoping to get time for this in the coming weeks.

**Comment by Tyriar** [comment]
Actually this would have to go in a v5, maybe it's time 🤔
