### ISSUE TITLE
Error opening terminal

### ISSUE THREAD

**Issue by rquevedo** [xtermjs/xterm.js#3272]
Hi folks,
Im trying to use xterm.js inside odoo. Im making a new widget. My widget template is:

```
<div id="widget_terminal_ws">
    <div id="terminal"></div>
</div>
```

When i try to open terminal:

`let term = new Terminal({cursorBlink: true});
term.open($('#terminal', this.$el));`

Im receiving this error:

Cannot read property 'defaultView' of undefined

What im doing wrong?

Thanks in advance.

**Comment by Tyriar** [comment]
We don't have instance of the text `defaultView` in the codebase, the error seems to be on your end.

**Comment by rquevedo** [comment]
Hi @Tyriar the raise comes form:
`this.context = this.parent.ownerDocument.defaultView;`

This code is in open method. Im running version 3

Regards

**Comment by rquevedo** [comment]
Thanks @jerch i will try updating the lib.
