### ISSUE TITLE
DECSCUSR() and DECSCUSR(0) should reflect the current user setting of the cursor shape

### ISSUE THREAD

**Issue by akinomyoga** [xtermjs/xterm.js#3293]
This was first reported at https://github.com/akinomyoga/ble.sh/issues/95. In Visual Studio Code (VSCode), when a Bash plugin `ble.sh` is loaded in a Bash session, the cursor shape becomes always `Block` regardless of the user setting of the cursor shape.

<img width="50%" src="https://user-images.githubusercontent.com/8982192/113637080-b7f9a800-96ae-11eb-9f4f-47ee08a98ae7.png" />

This seems to be caused by the behavior of xterm.js for the control function <kbd>DECSCUSR()</kbd> (*empty*) and <kbd>DECSCUSR(0)</kbd> (*0*). I expect these parameters, *empty* and *0*, change the cursor shape to the default one configured by the user, but, in xterm.js, *empty* and *0* are [always treated as *1* (Blinking Block)](https://github.com/xtermjs/xterm.js/blob/233b78d258417e9d6c107eb54fc4c753e1625911/src/common/InputHandler.ts#L2666) which is just the default value for the user setting.

<img width="50%" src="https://user-images.githubusercontent.com/8982192/113639867-17f34d00-96b5-11eb-9546-7e097ff020d8.png" />

## Behavior of other terminals

- In all the other terminals that I tested (including Mintty, Alacritty, RLogin, GNOME Terminal (VTE), and Windows Terminal), when the user changed the default cursor shape from Block to another, <kbd>DECSCUSR()</kbd> and <kbd>DECSCUSR(0)</kbd> change the cursor shape to the user-configured default rather than to Block. The behavior can be checked with the following commands after the user default is changed.
  ```bash
  $ printf '\e[ q'
  $ printf '\e[0 q'
  $ printf '\e[1 q'
  ```

  I couldn't check xterm's behavior because I don't know how to change the default value for the cursor shape in xterm.

- We can also find a related discussion in [a code comment of VTE](https://github.com/GNOME/vte/blob/f728689e89ef4f6b83527c9a0d340ee52b7d0cf0/src/vteinternal.hh#L174-L185):

  > We treat 0 and 1 differently, assuming that the VT510 does so too.
  >
  > See, according to the "VT510 Video Terminal Programmer Information", from vt100.net, paragraph "2.5.7 Cursor Display", there was a menu item in the "Terminal Set-Up" to set the cursor's style. It looks like that defaulted to blinking block. So it makes sense for 0 to mean "set cursor style to default (set by Set-Up)" and 1 to mean "set cursor style to blinking block", since that default need not be blinking block. Access to a VT510 is needed to test this theory, but it seems plausible. And, anyhow, we can even decide we know better than the VT510 designers!

- In the original DEC implementation of [`DECSCUSR`](https://vt100.net/docs/vt510-rm/DECSCUSR.html), the parameters `empty` and `0` meant the block style, but I guess it is just because the default cursor shape of VT series couldn't be configured so was always the block style (but maybe VT allowed some user configuration, see the previous item of the VTE comment). Anyway, *empty* and *0* typically meant the *default* for some other control functions, so I believe it is a natural guess that *empty* and *0* for DECSCUSR are also intended for the default cursor shape.

## Note on ZDM

Here's [a related note](https://github.com/akinomyoga/ble.sh/issues/95#issuecomment-813574245) on the mode `ZDM` from @jerch:

> Hmm good question. Maybe first some background on this on a general note - in the early days there was a so called ZDM* (zero default mode), which would tell the sequence parser that any `functionXY()` is equivalent to `functionXY(0)`, meant as `default value`. This is what xterm.js' parser does atm. It works so far for all implemented DEC related features.
>
> Later on that mode was removed from ECMA-48 with the note, that a parameter of `0` does not not mean `default value` anymore, but should stand for a numercial value `0` instead. Most sequence functions never applied that updated meaning for older models (e.g. cursor movement sequences still follow the default meaning as in `CSI A` == `CSI 0 A` == `CSI 1 A`). But without ZDM a missing parameter should mean `default value`, while `0` get its zero meaning (thus `CSI A` == `CSI 1 A` != `CSI 0 A`).
>
> [...]
>
> [*] As far as I know ZDM was completely removed from VTE.

## Fix

From the same comment by @jerch,
> For the sequence at hand I see a simple fix (since we have a default cursor style in the terminal options I wasnt aware of):
> - DECSCUSR() - switch to default value from settings
> - DECSCUSR(0) - switch to default value from settings
> - DECSCUSR(1) - steady block
>
> This would be still in line with ZDM, but correctly map to the overwritten default in settings instead.

This is what other terminals do and I completely agree with this fix (though I think "steady block" is a typo of "blink block").

**Comment by jerch** [comment]
> This is what other terminals do and I completely agree with this fix (though I think "steady block" is a typo of "blink block").

Woops, this is indeed a typo in the docs :+1:

**Comment by jerch** [comment]
@akinomyoga Just looked at the code - we have indeed no fixed default setting in the options for the cursor style, instead the setting gets used as initial value, but later changes overwrite that setting (with hardcoded 0|1 as BLINKING BLOCK).

@Tyriar  To get rid of the hardcoded default I suggest to add the cursor style to DEC private modes in `CoreService`, this way we can keep the option setting untouched and use it as default on DECSCUSR() or DECSCUSR(0) and reset.

**Comment by kevinc16** [comment]
Hey @jerch, I came from https://github.com/microsoft/vscode/issues/211394 - I've looked into this a bit and would like to work on this issue. 

If I understand correctly, it seems that we want to add `cursorStyle` in `coreService.decPrivateModes` and use that as the terminal cursor, and use `optionsService.options.cursorStyle` as the default value to revert to? What are your thoughts on adding a defaultCursor variable in `optionsService.options` instead? Thanks in advance!

**Comment by akinomyoga** [comment]
I'm unfamiliar with the codebase of `xterm.js`, but I don't think the cursor style should be stored in `decPrivateModes`. By its name and its members, it's obvious that `decPrivateModes` contains (a part of) the states of DEC Modes, which are set by the control functions `DECSET` and `DECRST`. `DECSCUSR` is unrelated to `DECSET`/`DECRST`.

I also think the cursor set by `DECSCUSR` is not just `cursorStyle` in the codebase, but both `cursorStyle` and `cursorBlink` should be considered here.

https://github.com/xtermjs/xterm.js/blob/2edc65baaa50f8b99c67f3df6f8d5d93c70a69e6/src/common/services/CoreService.ts#L26-L33

I think it is natural to manage *the current values* of `cursorStyle` and `cursorBlink` along with `isCursorHidden` above. I guess the `optionsService.options` should contain *the default values* of `cursorStyle` and `cursorBlink`.

**Comment by tisilent** [comment]
https://github.com/xtermjs/xterm.js/blob/2edc65baaa50f8b99c67f3df6f8d5d93c70a69e6/src/common/services/OptionsService.ts#L12-L19

**Comment by jerch** [comment]
@kevinc16  Sorry for the late response.

Yes you are right - we basically lack a separation of initial default state to current state, which makes it impossible to revert to the initial state since it is not preserved.

@akinomyoga Yepp, `decPrivateModes` is meant as a stateholder of the currently active/inactive instance modes. This gets initialized during startup from the option's service, if there is a configurable option, otherwise from a hard-coded value. 

To get things into perspective, we actually would need both for the full deal:
- a setting in options for default cursor shapes and whether shape/hide change are applicable at all (as some integrators like to disable those features fully effectively disabling messing with cursor shapes & visibility)
- a runtime setting reflecting the active shape & hide state, linked to DEC sequences or fully deactivated

**Comment by Arup-Chauhan** [comment]
@Tyriar , am coming here from VSCode issue [#211394](https://github.com/microsoft/vscode/issues/211394)

I am resuming work after a while as I was away.

I am proposing that we can update the InputHandler in Xterm.js to correctly handle DECSCUSR 0 by resetting the cursor to the user's preferred style. This ensures consistency with expected terminal behavior.

Would that be a good step? @Tyriar @jerch  inputs will be appreciated.

**Comment by Tyriar** [comment]
@Arup-Chauhan yep

**Comment by Arup-Chauhan** [comment]
Hi @Tyriar , raised a draft PR to work on this, have some questions, please take a look, thanks!
