### ISSUE TITLE
Change of cursor blinking state by DECSCUSR is not reflected on the screen

### ISSUE THREAD

**Issue by akinomyoga** [xtermjs/xterm.js#3300]
I noticed this in testing the behavior of DECSCUSR for https://github.com/akinomyoga/ble.sh/issues/95. I could reproduce the behavior both in
- Terminal in VSCode 1.55.0 (c185983) on Windows 10 (version 1909 build 18363.1440)
- and [Demo on xtermjs.org](https://xtermjs.org) with Google Chrome 89.0.4389.114 x86_64 on Windows 10 (version 1909 build 18363.1440)

Even if the internal cursor blinking state is changed by `DECSCUSR`, it is not reflected on the screen. For example, this can be checked by the following commands (in Bash session in the VSCode terminal):

```bash
bash$ printf '\e[1 q'
bash$     # <-- We expect Blinking Block
bash$ printf '\e[2 q'
bash$     # <-- We expect Steady Block
```

Or, in the [Demo](https://xtermjs.org) page, one can directly type the escape sequences from the keyboard as <kbd>Escape</kbd><kbd>[</kbd><kbd>1</kbd><kbd>space</kbd><kbd>q</kbd> and <kbd>Escape</kbd><kbd>[</kbd><kbd>2</kbd><kbd>space</kbd><kbd>q</kbd> to see if the cursor display style is correctly changed.

The result is that the blinking state is unchanged: If the state is initially Blinking, it is always Blinking. If the state is initially Steady, it keeps being Steady even though the state is internally changed by DECSCUSR. I expect that the state change is reflected on the screen.

**Comment by Tyriar** [comment]
Seems to be fixed
