### ISSUE TITLE
Cursor shape change by DECSCUSR is not reflected until the cursor moves in VSCode terminal

### ISSUE THREAD

**Issue by akinomyoga** [xtermjs/xterm.js#3301]
This is also from the tests for https://github.com/akinomyoga/ble.sh/issues/95.

## Environment

I'm not sure if xtermjs/xterm.js is the right place to report it since I cannot reproduce this behavior on the [demo](https://xtermjs.org/#demo) page but only in the VSCode terminal:

- Terminal of VSCode 1.55.0 (c185983) on Windows 10 (version 1909 build 18363.1440). I don't know how to check the bundled version of xterm.js in VSCode.

Maybe this is related to the integration of xterm.js in VSCode. Or, maybe this is just caused by the version difference of xterm.js in VSCode and the demo page. If there is another place where I should report this issue, please let me know the place. If this is already fixed in xterm.js, please close the issue and let me know that.

## Steps to reproduce

1. In the VSCode terminal, open a Bash session. Any Bash from WSL2 or Cygwin is OK.
2. Run the following command:

```bash
bash$ for i in 1 3 5 0; do printf '\e[%d q' $i; sleep 1; done
```

I expect that the cursor shape changes every second. However, VSCode terminal doesn't change the cursor shape at all. In all the other terminals I tried (mintty, xterm, mlterm, alacritty, terminology, urxvt, and Windows Terminal), the cursor shape changes as expected.

If I output some character or some escape sequence to change the cursor position after DECSCUSR, the cursor shape change is immediately reflected on the screen in VSCode terminal:

```bash
bash$ for i in 1 3 5 0; do printf '\e[%d qx' $i; sleep 1; done
bash$ for i in 1 3 5 0; do printf '\e[%d q\e[C' $i; sleep 1; done
```

This means that in the VSCode terminal, the cursor shape change isn't reflected on the screen until the cursor moves after the `DECSCUSR`. The expected behavior is that the displayed cursor shape should be immediately changed on receiving `DECSCUSR`.

**Comment by Tyriar** [comment]
Works now in both the xterm.js demo and vscode
