### ISSUE TITLE
Control Sequences emitted when opening vim

### ISSUE THREAD

**Issue by tflpd** [xtermjs/xterm.js#3307]
While studying the available functionality I noticed a weird behavior. When opening vim there are two control sequences emitted `[2;2R` and `[>0;276;0c` by the onData() event listener.

## Details
- Browser and browser version: Chrome 89.0.4389.128
- OS version: macOS Big Sur 11.2.3
- xterm.js version: 4.7.0
- Angular version: 9.1.12

### Steps to reproduce

1. In an Angular app initialize the terminal: `this.terminal = new Terminal();`
2. Create a listener for new data:
  `this.terminal.onData(data => {
      console.log("New data: " + data)
  });`
3. Open vim from the xterm. You will see the two sequences getting printed before any user input.
Is that normal/expected behavior? I feel that those should not be sent by the `onData()` event listener but I might be wrong

**Comment by Tyriar** [comment]
That's a pretty old version of xterm.js, does it happen on latest? Also are you using `writeSync`?

**Comment by Tyriar** [comment]
This is expected because `vim` requested information, you need to send it back. `[2;2R` is the cursor position for example which is emitted after receiving `\x1b[6n`
