### ISSUE TITLE
line not wrap and place space character in the right

### ISSUE THREAD

**Issue by Lee-42** [xtermjs/xterm.js#3308]
## Details
- Browser and browser version: an Brower in Electron
- OS version: window10
- xterm.js version: ^4.11.0
- xterm-addon-fit": "^0.5.0"

### Steps to reproduce

1. I am sure that cols and rows are set when initializing xterm
2. And send a request to set the cols and rows of the pty of SSH
3. But the following phenomenon will appear
![avatar](https://user-images.githubusercontent.com/4323398/33307012-f25b7f34-d44f-11e7-943a-b8d42f70494a.gif)
4.I have encountered other people’s issues, but he did not explain the solution

**Comment by Lee-42** [comment]
It does not wrap, but simply replaces the previous text

**Comment by yangshuaishuai** [comment]
cols  less than 80 ，I don't know why

**Comment by leftstick** [comment]
same issue

**Comment by leftstick** [comment]
i fixed it by setting the `node-pty`'s `cols` and `rows` with `xterm.cols` and `xterm.rows`. 

You can check my repo: https://github.com/leftstick/electron-awesome

**Comment by Lee-42** [comment]
It has been solved. My solution is to pass in the cols and rows parameters in conn.shell(), and then get the cols and rows of the xterm each time the xterm size is modified, and then use the setWindow of the stream object through the http request () method to set cols and rows

**Comment by Lee-42** [comment]
所以这不是xterm的问题，而是我没有使用好ssh2模块，相信node-pty的解决思路也是一样的

**Comment by Lee-42** [comment]
So this is not the problem of xterm, but I did not use the ssh2 module well, I believe that the solution idea of node-pty is the same

**Comment by hou547982300** [comment]
你们不使用node-pty碰到这种问题没呢
