### ISSUE TITLE
remove line from middle creating spaces

### ISSUE THREAD

**Issue by haroonali72** [xtermjs/xterm.js#3309]
I have integerated xterm.js simulation in my react app. It's working fine with backend server using socket.io, but when I remove a line from middle it creates blackspace and not override blacepaces with text next to spaces.
e.g commad to write is 'kubectl get pods' and if I remove 'get' from the command, terminal will show 'kubectl     pod' showing the black spaces
## Details
- Browser and browser version
Chrome 
- OS version:
Ubuntu 18.04 
- xterm.js version: 
4.9.0

Image attached for better understanding, and its is reproduced on xterm.js demo example.

![Screenshot from 2021-04-19 14-40-50](https://user-images.githubusercontent.com/68653870/115216528-05016380-a11e-11eb-9e98-0e3920d8e3fc.png)

**Comment by haroonali72** [comment]
Any help will be appreciated. If it is implementable with the current xterm features then please show me some way.

**Comment by mofux** [comment]
This sounds like your the backend terminal and xterm.js have different rows / cols settings. Please make sure rows and cols are in sync.

**Comment by mofux** [comment]
Oh I see you are playing with the demo only. The demo is not attached to a proper terminal backend and only emulates this very basics.

**Comment by Tyriar** [comment]
What does this look like with your backend server and what is the pty implemented with? The demo is not meant to work here.

**Comment by jerch** [comment]
xterm.js is a dumb terminal, thus has no advanced (line) editing features. To get what you want you need some data/cursor state handling on the "other side". Normally this is done by the TTY device (basic line editor in ICANON mode) or the application directly (RAW mode).

If you are injecting data directly to the terminal (not from a PTY), you can do the following:
- basic EOL editing as in ICANON:
  This is a very reduced editing mode, it can only remove chars from the end of a terminal row by sending `BS SP BS` (`'\x08 \x08'`). Here the cursor is always meant to be at the end of the current data (does not work with cursor jumps). Can be enhanced up to word removal, if you implement a custom data buffer with word border recognition. By default this works only on the same terminal row, by setting _reverse wrap-around_ (`CSI ? 45 h`) it can span multiple lines in the viewport.
- full viewport/display control
  Thats what most more advanced applications do - they keep track of the current line data (possibly spanning multiple terminal rows) and the cursor position. On  insert/delete they update their own buffer and use terminal sequences to update the terminal state accordingly. Some useful sequences here:
  - EL erase in line (full line erase or prior/past the cursor)
  - ED erase in display (full viewport erase or prior/past the cursor)
  - IL insert line (moving later lines downwards)
  - DL delete line (moving later lines upwards)
  - ICH insert blank chars (moving later chars in the row off the right side)
  - DCH delete chars (moving later chars in the line to the left)
  - ECH erase chars (replacing chars with empty cells)

To get a hold of supported sequences, see https://xtermjs.org/docs/api/vtfeatures/.

**Comment by haroonali72** [comment]
> What does this look like with your backend server and what is the pty implemented with? The demo is not meant to work here.

**Comment by haroonali72** [comment]
> What does this look like with your backend server and what is the pty implemented with? The demo is not meant to work here.

pty is implemented in golang,  Let me breakdown this through a code example that I am using in FE side. 
In this given code example, I am creating an input on every keystrok when user enters then I send that complete input to pty server, and I am also handling cursor manipulation. but when i tried to remove command from center it create blackspace not overriding the blackspaces with data next to spaces. Please guide me what I am missing.
`
let input = '';
let cursor = 0;
xTermObj.onData((data: any) => {
          const code = data.charCodeAt(0);
          if (code === 13) {  // code for enter
            if (input === 'clear') {
              xTermObj.clear();
              input = '';
            }
            if (input !== '') {
              input += '\n';
              sendSocketMessage(new TextEncoder().encode(input));  //this function is for sending input to backend pty.
            }
            input = '';
          } else if (code === 127) {   // code for backspace
                cursor -= 1;
                let part1: string = input.substring(0, cursor - 1);
                let part2: string = input.substring(cursor + 1, input.length);
                input = part1 + part2;
                xTermObj.write('\b \b');
          } else if (data === '\x1b[D') {  // code for left arrow
            if (cursor !== 0) {
              cursor -= 1;
              xTermObj.write('\x1b[D');
            }
          } else if (data === '\x1b[C') { // code for right arrow
            if (cursor < input.length) {
              cursor += 1;
              xTermObj.write('\x1b[C');
            }
          } else {
            xTermObj.write(data);
            input = input.substr(0, cursor) + data + input.substr(cursor);
            cursor += 1;
          }
        });`

**Comment by jerch** [comment]
@haroonali72 You make this harder than needed - the code above is the beginning of writing your own shell with prompt line editing capabilities. The question is - why would you do that? Why not using existing shells? Writing your own shell can be fun ofc, but it is nothing you will get working properly soon with good results.

Solution with existing shells:
- remove all the input condition handling above
- feed any input from terminal directly to `sendSocketMessage`
- run a shell on the PTY with access to the needed commands like kubectl
- done

**Comment by haroonali72** [comment]
> @haroonali72 You make this harder than needed - the code above is the beginning of writing your own shell with prompt line editing capabilities. The question is - why would you do that? Why not using existing shells? Writing your own shell can be fun ofc, but it is nothing you will get working properly soon with good results.
> 
> Solution with existing shells:
> 
> * remove all the input condition handling above
> * feed any input from terminal directly to `sendSocketMessage`
> * run a shell on the PTY with access to the needed commands like kubectl
> * done

@jerch thank you so much . You solved my problem. Its working fine. Actually I was recreating the wheel :D
