### ISSUE TITLE
bell handling

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#3316]
(Coming from #3314.)

Consolidate bell handling as follows:
- Strip sound output handling from xterm.js.
- Propagate `onBell` as interface to hook into the bell (make sound output an outer env problem). Here integrators can do whatever they want or suits their purpose.
- Move current direct sound output to a default bell addon, that keeps working in browsers as now, but listens on `onBell`. If demanded, we can later extend the addon by other bell metaphors, like a visual bell and such.

This cannot be done until next major release version (v5), as it involves changes to the terminal options.

**Comment by Tyriar** [comment]
Pushed to v5 branch
