### ISSUE TITLE
Throttle accessibility tree rendering

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3376]
`screenReaderMode` can cause layout thrashing when there is a lot of data. This much data doesn't help screen reader users anyway so we could easily throttle it to something like 500-1000ms to save many frames being rendered.

Context: https://github.com/xtermjs/xterm.js/issues/3374#issuecomment-867957990

**Comment by pattch** [comment]
Just wanted to ping this issue and see if there's any update here - I have an open PR that fixes this and curious if that change is an acceptable fix?
