### ISSUE TITLE
chrome 92 (beta) randomly duplicates quickly typed in characters

### ISSUE THREAD

**Issue by haraldschilly** [xtermjs/xterm.js#3377]
## Details
- Browser and browser version:  Chrome Version 92.0.4515.70 (beta)
- OS version:  Linux, Ubuntu 21.04
- xterm.js version: the one on your website: https://xtermjs.org/

### Steps to reproduce

Characters are repeated if you type them in very quickly. e.g. `asdf` ends up as `asdff` or other variations (`asddf`). It doesn't matter which characters and I found no specific pattern. I tried it on two different Linux computers and well, seems to happen more frequently with the older (sower cpu) computer – smells like a race condition. I can also say that this doesn't happen in the currently stable version of chrome. This is probably Linux specific as well.

So, there is a chance this will be fixed for the final release, but maybe not. I'm still reporting it in case chrome is released and others notice this as well.

**Comment by Tyriar** [comment]
I can't repro in Edge 93, maybe it's a Chrome bug that's already fixed in Canary?

**Comment by haraldschilly** [comment]
Yes, could be, I'm also suspecting Chrome.

**Comment by Tyriar** [comment]
Let's close this then but I'll keep an eye out for similar reports. Thanks

**Comment by 1412049** [comment]
Browser and browser version: Chrome Version 92.0.4515.107 (Official Build) (64-bit)
OS version: Linux, Ubuntu 20.04
xterm.js version: lastest version

If you have more than one input source, this issue wil be back :((((
![image](https://user-images.githubusercontent.com/33229941/126783242-f7763f98-f181-47c0-9f3b-44c47b92dadc.png)

**Comment by haraldschilly** [comment]
Well, I just got an update to the latest stable version `92.0.4515.10792.0.4515.107` … which still has this issue I reported initially. It's Linux, Ubuntu 21.04. I don't really know what/where these input sources are.

**Comment by 1412049** [comment]
> Well, I just got an update to the latest stable version `92.0.4515.107` … which still has this issue I reported initially. It's Linux, Ubuntu 21.04. I don't really know what/where these input sources are.

Check your input source in: Settings -> Region & Language -> Input source
Remove other and keep only one input source [English (US)]

**Comment by haraldschilly** [comment]
> Check your input source in: Settings -> Region & Language -> Input source
> Remove other and keep only one input source [English (US)]

oh, linux desktop, I see. Well, I'm "German/Austria/Österreich" and there is just one. That's the usual setting if you have German keyboard.

(as a test I could try english/us and restart the browser)

![Screenshot from 2021-07-27 09-26-59](https://user-images.githubusercontent.com/207405/127113647-0d938e6a-4efd-4bc5-9939-3161ab10947a.png)

**Comment by haraldschilly** [comment]
> Check your input source in: Settings -> Region & Language -> Input source
> Remove other and keep only one input source [English (US)]

oh, linux desktop settings, I see. Well, I'm German/Austria (Österreich) and "no dead keys" is the usual selection. There is just one for me:

![Screenshot from 2021-07-27 09-26-59](https://user-images.githubusercontent.com/207405/127114415-6884dac6-917b-4237-86d2-a52e55b3fc50.png)


---

here I tried to switch to engish/usa, started chrome 92 (stable release) in incognito mode and well, it did change the keyboard layout and that's how "git status" looks like.

![Screenshot from 2021-07-27 09-30-45](https://user-images.githubusercontent.com/207405/127114490-696803ed-ce9b-41a1-89cf-422a2b2b6838.png)

**Comment by pattch** [comment]
I can also confirm that I see this issue on chrome 92 on linux, but not chrome 92 on macOS. This issue effects even the official xterm demo FYI

**Comment by pattch** [comment]
Also, I've just confirmed I don't see this issue when using Chrome beta (e.g. https://www.google.com/chrome/beta/)
