### ISSUE TITLE
Ability to know total number of lines written on terminal write

### ISSUE THREAD

**Issue by vrunhofen** [xtermjs/xterm.js#3378]
I have lines with control sequences that change the number of lines that are actually output.
That is: say I write two lines to the terminal. But the control sequences make the output in the terminal 4 lines.
I have no way of knowing how many lines to read from the buffer to get the control-seq processed terminal output. (I need this output to add back to a custom ui area.)

What I currently do is I record `term.buffer.lines.length` before I write the data, and after I write the data in the callback.
```
let n_lines_written
let last_buffer_length = term.buffer.lines.length
term.write(cseq_lines, () => {
    n_lines_written =  term.buffer.lines.length - last_buffer_length
})
```

This does the trick. I can then read buffer lines from `last_buffer_length` to `last_buffer_length + n_lines_written`.

But this completely breaks down when the buffer is full. Once the buffer is full, the reported length is always 1030 (1000 buffer lines + 30 rows). And I can no longer know how many lines were written. 

What would be cool is instead of a callback with no params, if the callback could provide some information about what was written. Would something like this be possible:
```
term.write(data, (info) => {
    console.log(info.written_lines.length, 
        info.written_lines.start_buffer_index,
        info.written_lines.end_buffer_index,
   )
})
```

**Comment by jerch** [comment]
We cannot provide such an interface in a uniform way for a simple reason - the buffer is not linear increasing, there are tons of sequences that can move the cursor around, flush the buffer or even swap buffers underneath. What you are asking for is a write logger on a highly mutating buffer, which cannot be provided in a performant way.

What might help you if you can ensure to do only linear write actions - place a marker upfront and save the current cursor position. After your write action, grab the marker offset to current cursor position - with only linear write actions all the cells/lines between is what you have written. But note that the marker will get disposed when it flows off the scrollback at top (e.g. writing `'\n'.repeat(gt_scrollback)`).

If you only want to know the real lines written (not the wrapping ones), maybe hook into `onLineFeed`.

**Comment by vrunhofen** [comment]
Yes. Ok, I understand that this may not be easy/performant, or even possible to provide.

Re scrollback - do you mean that if the input is longer than the terminal height (rows), then the marker will be disposed. Or if the written data fills up the buffer and then the marker goes off the top, and thats when its disposed?

Doesn't onLineFeed fire on writing a newline? I write a string to the terminal that contains say 9 newlines, and thats how many times the onlinefeed fires. Not when the terminal outputs a linefeed to the screen? Isnt that so?

**Comment by Tyriar** [comment]
This is such a niche thing that I don't think we should support it. Some other ideas you could consider:

- Use the Marker API to track the original line against what the new line becomes, this will work around the scrollback problem where we trim lines off the buffer.
- Write lines to a separate headless version of xterm.js and count the lines that way, if you keep scrollback small and don't call `open` this should still be fairly efficient and the instance could be reused by calling `reset`.
