### ISSUE TITLE
Issue with "Paste" from context meanu

### ISSUE THREAD

**Issue by nikhil-mohite** [xtermjs/xterm.js#3379]
## Details
- Browser and browser version: Google Chrome Version 91.0.4472.114
- OS version:  macOS 
- xterm.js version: 4.11.0

### Steps to reproduce
I am facing an issue with "paste" using the context menu. I am able to copy-paste using the shortcut  (Command + C and Command + V), even copy from the context menu is also working fine(Select text from the terminal and select copy from the context menu). 

Steps:
1. Copy text
2. Try paste using the 'Paste' option from the context menu.

**Comment by Tyriar** [comment]
Works fine for me on macOS/Chrome, try updating to 4.13?

**Comment by agusmakmun** [comment]
@Tyriar is happening on me as well:

**Details:**

- Browser and browser version: Google Chrome Version 97.0.4692.71 (Official Build) (x86_64)
- OS version: macOS Big Sur 11.6
- xterm.js version: 4.14.1
- react version: 17.0.2

**Comment by agusmakmun** [comment]
Issue from me solved by removing this custom `.xterm-screen` css:

```
.xterm-screen {
    width: 100% !important;
    pointer-events: none;
  }
```

especially for the `pointer-events: none`
