### ISSUE TITLE
[FR] example with auto resize on window size change

### ISSUE THREAD

**Issue by farfromrefug** [xtermjs/xterm.js#338]
Your example shows a auto resizing term when you change the number of rows and columns.

What most of us need is an example of a term auto-resizing when you resize the window. Or when you resize a resizable panel, like it is done in VSCode.
The issue is that i really dont see how to compute row and columns based on my div width/height.
An example would be awesome!

**Comment by Tyriar** [comment]
The logic for this is meant to be covered by the fit addon (VS Code uses custom logic though). The addons aren't particularly well documented currently.

**Comment by farfromrefug** [comment]
@Tyriar Is that what you use in VSCOde? 
Will look at it, thanks!

**Comment by Tyriar** [comment]
VS Code's logic is captured here https://github.com/Microsoft/vscode/blob/d14ee7613fcead91c5c3c2bddbf288c0462be876/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L363

Sourcelair and the xterm.js demo use the fit addon which is located here https://github.com/sourcelair/xterm.js/blob/master/addons/fit/fit.js

I'll close this in favor of https://github.com/sourcelair/xterm.js/issues/306 as that's an issue where we want to describe the addons in greater detail.

**Comment by ficristo** [comment]
@Tyriar I'm using the fit addon, but, while it resize the terminal, it always resizes the terminal a bit smaller than the parent element.
I tryed to add some styles like the following but it brokes other things.
```css
#terminal-container .terminal.xterm {
    height: 100%;
}
#terminal-container .xterm-viewport {
    height: 100% !important;
}
```
I looked a bit at VSCode but the particolar code you linked doesn't seem to deal with the height of the terminal.
Any idea how I could fix?

**Comment by Tyriar** [comment]
I believe fit tries to accommodate a scroll bar on the right, otherwise there can be issues with characters on top of the scrollbar (which differs by platform).

**Comment by Tyriar** [comment]
This is covered by https://xtermjs.org/docs/api/addons/fit/
