### ISSUE TITLE
Blurry text and no copy-pasting in Firefox

### ISSUE THREAD

**Issue by nikitaindik** [xtermjs/xterm.js#3380]
## Details
- Browser and browser version: Firefox 89
- OS version: MacOS 11.4
- xterm.js version: 4.13.0

### Steps to reproduce

1. Open https://xtermjs.org/ in both Chrome and Firefox, scroll to the Demo section
2. Chrome: terminal text is sharp, selectable and copy-pasteable. Firefox - blurred text, copying and pasting doesn't work

## Chrome 91
<img width="684" alt="Screenshot 2021-07-04 at 23 10 08" src="https://user-images.githubusercontent.com/15949146/124400082-77421700-dd0f-11eb-916e-3a1bf3627735.png">

## Firefox 89
<img width="687" alt="Screenshot 2021-07-04 at 23 09 58" src="https://user-images.githubusercontent.com/15949146/124400076-7315f980-dd0f-11eb-99a0-ffa839381808.png">

**Comment by nikitaindik** [comment]
Looks like the issue was in my Firefox privacy settings, not in Xterm.

These 2 settings in FF about:config are what causes the issue: 
`dom.event.clipboardevents.enabled = false` - this flag prevents copy-pasting
`privacy.resistFingerprinting = true` - switching off this flag makes the text sharp

Closing :)

**Comment by Tyriar** [comment]
@nikitaindik did you opt-in to these settings? Disabling clipboard events seems like it would break a lot of things.

**Comment by nikitaindik** [comment]
Yep, I was messing with FF flags a few days ago and forgot to revert my settings back. So it's entirely my fault. Works fine on default FF installation.
