### ISSUE TITLE
Can I get the content of a certain line or get the input string?

### ISSUE THREAD

**Issue by Tongzp** [xtermjs/xterm.js#3383]
I’m not familiar with it, hope to be reminded?

**Comment by Tyriar** [comment]
You can get the line's context using the `IBufferLine` API:

https://github.com/xtermjs/xterm.js/blob/094bcbd81d1f080d204331088aa99f4d7173d56c/typings/xterm.d.ts#L1275-L1285

**Comment by Tongzp** [comment]
@Tyriar Hello. I tried to use `term.buffer.normal.getLine().translateToString()`  get the lines's context. But I did not find which attribute represents the current input line.

**Comment by Tongzp** [comment]
> @Tyriar Hello. I tried to use `term.buffer.normal.getLine().translateToString()` get the lines's context. But I did not find which attribute represents the current input line.

In other words, it refers to how to get the output of the last line.

**Comment by Tyriar** [comment]
The current input line is where the cursor is, which is `term.buffer.cursorY`, so try `getLine(term.buffer.cursorY)`

**Comment by Tongzp** [comment]
![image](https://user-images.githubusercontent.com/33510725/125076200-34f34e00-e0f2-11eb-8d65-df0589a34a5c.png)

My term options is shown in the picture. `rows=40` and `scrollback=100` , i tried it but the result was not satisfactory.
When the number of scrolling rows is greater than `rows`, the data obtained from `term.buffer.cursorY` is not the latest row.

for example
![image](https://user-images.githubusercontent.com/33510725/125082816-3cb6f080-e0fa-11eb-94db-bf66f83abc28.png)

**Comment by Tyriar** [comment]
Oh sorry, you're actually after `term.buffer.viewportY + term.buffer.cursorY` since `cursorY` is relative to the viewport (0 to rows - 1)

**Comment by Tongzp** [comment]
OK, i will be try again. I would like to ask another question. I hope I can insert `~` or other symbols before `hello` when I input `hello`, which way should I use? Does `xterm` provide corresponding methods?

**Comment by Tyriar** [comment]
Depends what you mean by insert. But you can control the incoming and outgoing data so you can intercept/manipulate if you need to

**Comment by Tyriar** [comment]
You send data to `write` and listen via `onData`, so listen to whatever you're sending and handle it appropriately. There isn't something built in to handle this for you
