### ISSUE TITLE
Need to handle 'cmd + .' on macOS

### ISSUE THREAD

**Issue by jihoon-ernesto** [xtermjs/xterm.js#3400]
It would be better if the shortcut is supported as in the macOS built-in Terminal app.

The key combination(cmd + .) is handled as 'ctrl + C'(break) on macOS. And it is more convenient because the ctrl key of Mac keyboards is not so easy to press.

So, the usability of xterm (and other applications like VS Code) will be improved by supporting this, in my opinion.

**Comment by jihoon-ernesto** [comment]
I'm trying to fix it myself.

**Comment by Tyriar** [comment]
Let's have embedders handle this, see https://github.com/xtermjs/xterm.js/pull/3401#issuecomment-900238232
