### ISSUE TITLE
Response spacing not correct

### ISSUE THREAD

**Issue by sreerajkarippala** [xtermjs/xterm.js#3406]
i have a issue when i try to display 
`$ ls` 
it shows like below
![Screenshot 2021-08-08 at 4 31 06 PM](https://user-images.githubusercontent.com/1067808/128637825-914dcc15-6ef3-4bb8-8674-8b66eedc4edc.png)
Expected output layout is

<img width="992" alt="Screenshot 2021-08-08 at 4 31 33 PM" src="https://user-images.githubusercontent.com/1067808/128637836-57bbaddd-38ac-4878-9d3b-d99c79d073e7.png">
 
which option control spacing?

**Comment by Tyriar** [comment]
`\r` moves the cursor to the start of the line, so it looks like that is missing from the data you're writing to xterm.js.

**Comment by sreerajkarippala** [comment]
This is the code i am using to write shell response in Typescript
`      
this.child.write('\r\n');
`
`
this.child.write(response.result);
`
`
this.child.write('\r\n$ ');
`

**Comment by Tyriar** [comment]
The `\r\n`'s are working there, `response.result` must just contain `\n`.
