### ISSUE TITLE
Compile error: Cannot find module 'xterm-headless'

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3424]
This happens after watch is run I think a couple of times:

![image](https://user-images.githubusercontent.com/2193314/130067630-c15659b7-74c7-43e3-a2e8-05cc9dfabec7.png)

Probably to do with us leaning on import `'xterm'` being the repo root but `'xterm-headless'` lives in `root/headless` and is generated.

**Comment by jerch** [comment]
@Tyriar Is this a circular dep issue, or just a matter of compile order?

I had a somewhat similar issue in node-sixel with emscripten builds, that depend on some TS output symbols, while the whole projects tries to import the wasm builds. Was able to solve it by manually breaking the cycle with creating distinct "subprojects" (not even sure how it is called in TS, they have their own tsconfig), one to provide symbols for emscripten, and the second for the final import.

**Comment by Tyriar** [comment]
Think it's to do with how xterm-headless is in a sub folder so when the .d.ts tries to discover it by moving up the directory structure, it fails.

**Comment by staff0rd** [comment]
I get this by doing the following:
```bash
git clone git@github.com:xtermjs/xterm.js
yarn
yarn build # successful
# <make some edit to src/browser/Terminal.ts>
yarn build # fails
```

Failure message:

```
stafford@DESKTOP-N6KOGQN:~/git/xterm2$ yarn build
yarn run v1.22.11
warning ../package.json: No license field
$ tsc -b ./tsconfig.all.json
out/headless/public/Terminal.d.ts:2:161 - error TS2307: Cannot find module 'xterm-headless' or its corresponding type declarations.

2 import { IBufferNamespace as IBufferNamespaceApi, IMarker, IModes, IParser, ITerminalAddon, ITerminalOptions, IUnicodeHandling, Terminal as ITerminalApi } from 'xterm-headless';

                                                            ~~~~~~~~~~~~~~~~

out/headless/public/Terminal.d.ts:2:161 - error TS2307: Cannot find module 'xterm-headless' or its corresponding type declarations.

2 import { IBufferNamespace as IBufferNamespaceApi, IMarker, IModes, IParser, ITerminalAddon, ITerminalOptions, IUnicodeHandling, Terminal as ITerminalApi } from 'xterm-headless';

                                                            ~~~~~~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 2.
```
