### ISSUE TITLE
node-gyp failed to build pty on win 10

### ISSUE THREAD

**Issue by gtaranas** [xtermjs/xterm.js#343]
## Details
- Browser and browser version: 
- OS version: win 10
- xterm.js version: latest
- node version 5.1.1

### Steps to reproduce

1. npm install

**Comment by Tyriar** [comment]
This is a known issue, the fix is probably to use the [fork that vscode](https://github.com/Tyriar/pty.js) uses:.

**Comment by Tyriar** [comment]
Use node-pty and ensure the deps are installed
