### ISSUE TITLE
Cannot switch active unicode version in demo

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3442]
Right now when the unicode11 addon is activated the version remains at 6. Instead of adding UI it might be better to set `term.unicode.activeVersion = '11'` automatically

**Comment by anirudh1713** [comment]
@Tyriar Can I take this on? if so, this will reuqire changing `activeVersion` in `initAddons` function and in the change listener for checkbox. is that correct?

**Comment by Tyriar** [comment]
@anirudh1713 pretty much yeah, thank would be good 👍
