### ISSUE TITLE
Adopt @playwright/test and use JSHandle

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3446]
I'm using the new @playwright/test package in Luna Paint and it's essentially just doing what we're doing but in a much nicer way so we should adopt it. Additionally we should move away from just evaluating strings in `page.evaluate` to fetching a JSHandle to the xterm API and using that to test which would give us strong typing on the renderer side.

**Comment by Tyriar** [comment]
- Sharing page contexts across tests https://playwright.dev/docs/test-parallel/#reusing-single-page-between-tests
- Having playwright manage the server https://playwright.dev/docs/test-advanced/#launching-a-development-web-server-during-the-tests

**Comment by Tyriar** [comment]
This is done for the most part

**Comment by mxschmitt** [comment]
Great work @Tyriar!
