### ISSUE TITLE
Implement canvas measure strategy

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3449]
I have seen some reports like this:

![image](https://user-images.githubusercontent.com/2193314/131671640-119a3aae-c58e-494b-a940-60059f36cb17.png)

I had a debug session with someone and there were some interesting findings:

- It happened with monospace, Courier New, Consolas, Cascasia Code but not Arial (at least it wasn't obvious)
- Switching fontSize (forcing the char atlas to get refreshed) did not fix the issue
- Increasing the letter spacing mostly worked around the issue

Still not entirely sure why it's happening, but I believe handling this TODO will probably solve the issue and I can get it retested after we've done it:

https://github.com/xtermjs/xterm.js/blob/353a8c5388e3242af4957da5b89fc50a6e8ab663/src/browser/services/CharSizeService.ts#L54-L54

**Comment by anarchodin** [comment]
I get that display (Firefox on Linux, and it's _very_ consistent), but if I use the mouse to get a highlight:

![image](https://user-images.githubusercontent.com/307675/150239504-10a9307e-9869-4c17-9340-afb8018207de.png)

Remove the highlight and it goes right back to the original look. So whatever causes this, it changes when the highlighting is applied.
