### ISSUE TITLE
Key confusion in German layout (" vs @)

### ISSUE THREAD

**Issue by andrewsali** [xtermjs/xterm.js#3459]
On a Linux machine with German keyboard layout, trying to enter " results in @ (tested on xterm.js website, VS Code & JupyterLab).

Other text fields correctly receive the intended character (").

Please see the screenshot below for the keyboard events:

![Screenshot from 2021-09-03 12-00-07](https://user-images.githubusercontent.com/15079591/131990529-fd3d4c25-c856-44ab-96a5-e5775a8d32df.png)

## Details
- Browser and browser version:  Chrome 92
- OS version: Linux
- xterm.js version: Any

### Steps to reproduce

1. Linux machine, with German keyboard layout, try entering " into xterm.js

**Comment by akosyakov** [comment]
It seems to be somehow related to Chrome profiles: https://github.com/gitpod-io/gitpod/issues/5017 if one reset them then it works again. We see similar issues reported in Gitpod.

**Comment by Tyriar** [comment]
> xterm.js version: Any

Can you test using 4.14? We fixed a bunch of keyboard layout issues in that release.

**Comment by jerch** [comment]
FYI - I cannot repro with exact the same browser version under ubuntu 18 and german keyboard layout. Furthermore this reported events above look really strange, like a bug in the browser locale settings.

**Comment by akosyakov** [comment]
> Can you test using 4.14? We fixed a bunch of keyboard layout issues in that release.

Is it deployed on https://xtermjs.org/. We tried it there yesterday and it was still the issue, also with VS Code 1.60.0. Can we help something like collecting some logs or some debug pointers?

**Comment by lucassardois** [comment]
I have the same issue. I'm on a fedora 33 OS. The issue happens in Google Chrome `Version 93.0.4577.63 (Official Build) (64-bit)
` from xterm version 4.10 (at least) to the latest verison. The issue happen also on https://xtermjs.org/. However; in Firefox `92.0 (64-bit)` and Chromium `Version 93.0.4577.63 (Developer Build) Fedora Project (64-bit)` everything works fine.

**Comment by Tyriar** [comment]
4.14 is not yet in the xtermjs.org demo, it's on 4.13 still

**Comment by davidwindell** [comment]
Same on xtermjs.org for me

**Comment by chtisgit** [comment]
I could reproduce this using Google Chrome. It also happens in 4.14.1 but seems to be browser related as there is no problem in Firefox. In Chrome, when typing Shift+2 I get @ (US layout), in Firefox I get " (german layout). This extends to all keys except the letters.
The fix referenced by @akosyakov seems to work, though. After deleting ~/.config/google-chrome and ~/.cache/google-chrome, it works fine including older versions (tested on xtermjs.org).

Still, in addition to the german umlauts (ä ö ü, ß) I also cannot type a pipe symbol "|" in xterm.js on a German keyboard :(
This is neither in Chrome nor in Firefox.

**Comment by jerch** [comment]
Can repro the AltGr-based 3rd-shift issues - some keys are working (like `{[]`), other dont (like `}|`). Note that this is not the same issue as the initially reported one, as the event viewer reports correctly locale'ed chars in `event.key`.

@Tyriar 
This one is prolly a regression on xterm.js side, as it worked before for years, and now fails for every browser under ubuntu 18 (chrome, firefox and webkit).

**Comment by chtisgit** [comment]
I think this bug has been reported here for Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1245196&q=keyboard%20french&can=2
Make sure to star the issue if you are affected. I posted there because the issue seemed inactive. Let's see what happens.

**Comment by jerch** [comment]
@chtisgit Good find, pretty much looks like the OP's issue, where `event.key` does not apply the locale setting to the reported char.

**Comment by n-lim-pyres** [comment]
> I think this bug has been reported here for Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1245196&q=keyboard%20french&can=2

Ah yes, I'm the author of that issue on the Chromium bug tracker.

Funnily enough, I noticed this issue when implementing xterm.js in a website.  
Small world, eh.

Anyway, it's been more than one month, it's getting long.  
I hope they'll fix it soon.

**Comment by sfo** [comment]
With the latest Chrome update (95.0.4638.54), this is fixed for me (Ubuntu 20.04.3). There was no need to delete or switch profiles or else, just update and restart the browser and the keyboard behavior was back to normal.

**Comment by chtisgit** [comment]
I can confirm this with the same configuration.
