### ISSUE TITLE
4.14.0 regression: key inputs get duplicated in screenReader mode

### ISSUE THREAD

**Issue by martinpitt** [xtermjs/xterm.js#3467]
When enabling `screenReaderMode: true`, typing any character into the terminal gets duplicated. This happens in [cockipt-podman](https://github.com/cockpit-project/cockpit-podman/pull/759), but reproduces in xterm's own builtin demo.

## Details
- Browser and browser version: Firefox 91, Chromium 90.0.4430.212
- OS version: Fedora 34
- xterm.js version: happens with yesterday's 4.14.0 version, any earlier version was fine.

### Steps to reproduce

1. Start the demo: `npm run start`, open http://127.0.0.1:3000/
2. Type `cat /etc/os-release` into the terminal; this works
3. Enable "screenReaderMode" in the options. Now typing "cat" ends up as "ccaatt". The terminal really receives two keystrokes, as the shell complains about "ccaatt: command not found".

![image](https://user-images.githubusercontent.com/200109/132804462-8b745d0d-dde8-4c17-a178-a3fdb910c88c.png)

**Comment by Tyriar** [comment]
Might be caused by https://github.com/xtermjs/xterm.js/pull/3429

**Comment by Tyriar** [comment]
`_inputEvent` is triggering the data event a second time but only when screen reader mode is on:

![image](https://user-images.githubusercontent.com/2193314/132886054-121cd609-9461-4e1f-8b39-255ff97af513.png)

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/blob/9c49b3160928ca9c7d286d0bdbe7c27edcca2c93/src/browser/Terminal.ts#L1090-L1096

**Comment by martinpitt** [comment]
Thanks a lot @Tyriar for the super-fast fix! I confirm this [works properly again](https://github.com/cockpit-project/cockpit-podman/pull/760) with 4.14.1.
