### ISSUE TITLE
How to setup keyboard layout / language

### ISSUE THREAD

**Issue by AntonyChiossi** [xtermjs/xterm.js#3468]
The issue here is that I have a keyboard with italian layout (or i guess its the same with languages that have layouts different than English) and when I type, for exaple, shift + 6 it should print & not ^. Is there any way to set up the layout?

[https://i.imgur.com/lMHCrvO.png](https://i.imgur.com/lMHCrvO.png)

Thanks!

**Comment by Tyriar** [comment]
I believe this is fixed in 4.14.0 with the dead key/altgr related changes. /cc @Eugeny

**Comment by AntonyChiossi** [comment]
I investigated a bit and it happens only on Chrome, tried also FF and works just fine.

OS: Ubuntu 16 (IT keyboard)
xterm: version 4.11.0

**Comment by Tyriar** [comment]
4.11 is like 6 months old, always update and try repro before reporting bugs as they could be fixed already.

**Comment by fahmij8** [comment]
@Tyriar I have follow up question, is there a way to force setting up this keyboard language in xterm?
for example I want to force the input to be from US Keyboard Layout, regardless what keyboard they're using it will be automatically converted to US Layout
