### ISSUE TITLE
Resizing terminal can restyle cells

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3471]
Repro:

1. echo -e '\x1b[41mtesting\n\r\x1b[0m'
2. Resize terminal

![recording (81)](https://user-images.githubusercontent.com/2193314/133256627-7ae2314a-30b1-49e5-8385-b30872b93f16.gif)

**Comment by jerch** [comment]
This looks like an unfortunate BCE condition triggered by resizing.

**Comment by Tyriar** [comment]
Cannot reproduce anymore, it does render differently in canvas but I think that's tracked elsewhere
