### ISSUE TITLE
Autocomplete on Tab

### ISSUE THREAD

**Issue by Abhi2019** [xtermjs/xterm.js#3474]
When the autocomplete feature will be implemented? It is a needed feature on terminal.

**Comment by Eugeny** [comment]
Autocompletion is typically provided by the shell / application running _in_ the terminal.

**Comment by Abhi2019** [comment]
I am trying to implement the terminal in a web browser, but how to achieve tab autocomplete there?

**Comment by jerch** [comment]
You need to emulate the shells REPL cycle there with your logic, including writing your completions to the terminal whenever you find a tab in STDIN. For that think of xterm.js like providing STDIN (data from `onData`) and STDOUT (data send with `.write`).

Sidenote: Note that the character semantic is abit different in a naked terminal without a PTY in between, e.g. when you receive a `\r` from the terminal, it means the user pressed <enter>, to progress cursor to next line beginning you have to use CRLF `\r\n`, only `\n` is not enough. (If you wonder why it is that different to normal process STDIN/STDOUT - the PTY/TTY kernel has several replacement rules for those chars.)

**Comment by Abhi2019** [comment]
> You need to emulate the shells REPL cycle there with your logic, including writing your completions to the terminal whenever you find a tab in STDIN. For that think of xterm.js like providing STDIN (data from `onData`) and STDOUT (data sent with `.write`).
> 
> Sidenote: Note that the character semantic is abit different in a naked terminal without a PTY in between, e.g. when you receive a `\r` from the terminal, it means the user pressed enter, to progress cursor to next line beginning you have to use CRLF `\r\n`, only `\n` is not enough. (If you wonder why it is that different to normal process STDIN/STDOUT - the PTY/TTY kernel has several replacement rules for those chars.)

I have tried in many ways to work, could you please help me the thing.

https://codesandbox.io/s/xtermreact-demo-forked-8xshv?file=/src/App.js

**Comment by jerch** [comment]
@Abhi2019 Are you sure have tried that hard? The snippet above looks more like a stackoverflow c&p result.

It is a long way from what you have there (even slightly wrong/subpar), to what you want. I cannot help you with that, it means writing basic editor functionality myself. You might want to have a look at https://github.com/wavesoft/local-echo, which covers most basic editor semantics. Maybe you can extend that to your needs.
