### ISSUE TITLE
Support double-click to select and copy directly

### ISSUE THREAD

**Issue by zhouxlt** [xtermjs/xterm.js#3475]
Like linux shell，double-click can copy selected content

**Comment by Tyriar** [comment]
Is this just automatically copy selection? You can do that by listening to `onSelectionChange`:

https://github.com/xtermjs/xterm.js/blob/a8a24eba515de6a46a4a1d1f7c81b8cfdd518179/typings/xterm.d.ts#L722

**Comment by zhouxlt** [comment]
@Tyriar thank you for your response,  it helps a lot

**Comment by rawbin-** [comment]
@zhouxlt and what't next?
without any extra work, xterm.js can select with double, but not content around cursor, with a distance to cursor, also for pressing mouse select sometimes ok and some times content with a distance selected
<img width="521" alt="image" src="https://user-images.githubusercontent.com/8169783/225362820-a7b4c2a5-dfc6-4e34-8fb2-fa2c5ecb3744.png">
