### ISSUE TITLE
Rendering issue when changing font size 

### ISSUE THREAD

**Issue by ProChirathF** [xtermjs/xterm.js#3486]
When the terminal font size is changed cursor and view port width is not recalculated, a terminal re-render sets the correct cursor position and the width

## Details
- Browser and browser version: Chrome 93
- OS version: 
- xterm.js version: 4.14.1

### Steps to reproduce

1. https://codesandbox.io/s/xtermjs-font-size-wm4o8
2. xterm-helper-textarea styling is overridden with a red border and opacity:1
3. Type few lines 
![image](https://user-images.githubusercontent.com/64767251/134805610-b3db613d-797a-48b8-a9b6-42305e9fe95b.png)
4. Change Font size to 24
![image](https://user-images.githubusercontent.com/64767251/134805622-e0a52b65-2bd8-41c7-8cbd-275b5558e24c.png)
Cursor position is wrong
5. Enter more lines - Cursor is recalculated. Add lines until cursor is not in view port
6. Set font back to 14
![image](https://user-images.githubusercontent.com/64767251/134805690-8c8c435d-d921-4a7e-b3d3-ee9714a195a7.png)
View port width and cursor is wrong
![image](https://user-images.githubusercontent.com/64767251/134805750-271711dd-ee8e-451b-976c-9bb9aa375785.png)
8. Enter text , view port width and cursor recalculated correctly
![image](https://user-images.githubusercontent.com/64767251/134805776-cbaab338-bc85-439a-a769-9e7dabe1f369.png)
![image](https://user-images.githubusercontent.com/64767251/134805801-6c64f19f-345e-427b-a735-8ba6f04d8f6d.png)

I think this issues is related to https://github.com/xtermjs/xterm.js/issues/3065

**Comment by Tyriar** [comment]
This is another case of https://github.com/xtermjs/xterm.js/issues/3390
