### ISSUE TITLE
Text get cut off on terminal.

### ISSUE THREAD

**Issue by AyaanZaveri** [xtermjs/xterm.js#3492]
This is what the Xterm.js website looks like:
**Brave (Chromium):**
<img width="867" alt="Screen Shot 2021-10-01 at 3 59 31 PM" src="https://user-images.githubusercontent.com/63752541/135679519-55aa2af7-a88a-4c63-b938-2f2afb2bf6b4.png">
On Brave some of the text was cut off.

**Safari:**
<img width="812" alt="Screen Shot 2021-10-01 at 3 59 39 PM" src="https://user-images.githubusercontent.com/63752541/135679647-4e4bbbce-6c76-4e72-9c40-856f615288cf.png">
On Safari it was invisible.

**Terminal Font**: Menlo, Monaco, 'Courier New', monospace

Related to https://github.com/cdr/code-server/discussions/4292

**Comment by Tyriar** [comment]
Safari problem: https://github.com/xtermjs/xterm.js/issues/3357

**Comment by Tyriar** [comment]
As mentioned in https://github.com/cdr/code-server/discussions/4292#discussioncomment-1419953, this is Brave's fingerprint protection which I believe is disabling access to measuring fonts which annoyingly can be used as a mechanism for fingerprinting. But obviously this is crucial to knowing how large the characters are. Open for feedback on how to better detect this.

**Comment by Tyriar** [comment]
Created a FAQ page on wiki to capture this https://github.com/xtermjs/xterm.js/wiki/FAQ
