### ISSUE TITLE
Scrolling in interactive terminal UI (FAR Manager)

### ISSUE THREAD

**Issue by jherman** [xtermjs/xterm.js#3514]
When using a console UI tool like FAR Manager, scrolling seems to throw a `Unable to preventDefault inside passive event listener invocation.`. I can scroll without errors when I'm not in this terminal UI.

I've seen a few other cases/fixes surrounding this but none seem to address this in particular:

https://github.com/xtermjs/xterm.js/pull/2931
https://github.com/xtermjs/xterm.js/issues/3004
https://github.com/xtermjs/xterm.js/issues/3110

I've tried altering xterm.js code to remove the `preventDefault` in the wheel scroll, and that does seem to stop it, however it then tosses the error when I'm out of the terminal UI.

The line that errors:
https://github.com/xtermjs/xterm.js/blob/80d4742ded8029ee9e95aec53200f00d6ce2c569/src/browser/Terminal.ts#L702

## Details
- Browser and browser version: `Chrome Version 94.0.4606.81 (Official Build) (64-bit)`
- OS version: `Microsoft Windows 10 Enterprise Release [2009] Version 21H1`
- xterm.js version: `xterm 4.14.1`

### Steps to reproduce

1.  Setup a basic connection to a PTY session
2.  Start a UI that has scrolling like FAR manager

See image:

![output-onlinegiftools](https://user-images.githubusercontent.com/276792/137996486-99de2764-36ca-42ef-af3e-52fc587a3edd.gif)

**Comment by jerch** [comment]
Thx for your detail replay.

What comes to my mind - is angular faking events by any chance? Like they catch and stop them, and later re-enter them from newly created ones? Thats just a wild guess for now, but that fact that your logs clearly show the events as `passive: false` while this still happens does not fit at all. Those events with `passive: true` have to come from somewhere.

**Comment by jherman** [comment]
@jerch Before I take those steps, let me write up a quick plain old index.html with xtermjs that'll talk to my websocket server and see if that corrects it.  That'll at least tell me if it is Angular, and it's not xterm's problem. I'll let you know what I find out.

**Comment by jherman** [comment]
Just to confirm. I also see the 3 handlers attached:

![image](https://user-images.githubusercontent.com/276792/138298090-b5e908d2-d68c-4c4e-bf91-ae70ee5c2c3b.png)

I'm assuming I maybe be able to remove the zone-flag once #3518 is in.

**Comment by jherman** [comment]
Just wanted to circle back. I reverted my workaround regarding angular zone.js and updated to xtermjs 4.15.0. I no longer get the errors presented in the debugger console. Cheers!
