### ISSUE TITLE
WASM for the win

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#3515]
I'd like to discuss, whether using web assembly for certain terminal core tasks is a viable/maintainable goal.

**Prior investigations and results**

I messed around with wasm for certain tasks with kinda impressive results (tested on V8):
- SIXEL decoding: speedup ~3.5 times (from 40 MB/s to 150 MB/s throughput, this one is highly optimized)
- UTF8 decoding: speedup ~3 times (from 180 MB/s to 600 MB/s for mixed content, ASCII only is much higher)
- base64 decoding: speedup ~2.5 times (from 450 MB/s to 1.1 GB/s)

Funny thing regarding these experiments - it is almost the same code in TS and C++ (compiled with emscripten), but still shows that much of an advantage. Now my tested tasks have several things in common - they are all _filter functions_, that take some input chunk, do some sort of transformation on a rather small rule set (low memory profile without the need of reallocations) to generate the output chunk. While this is rather data copying intensive, it is still much faster than their JS counterparts.
In general those isolated _filter functions_ seem to be a good fit for wasm, if the outer env (xterm.js here) sticks to some basic memory handling rules (borrow as much as you can across the board).

**Downsides of wasm**

Now wasm is not an easy pick for a project, as it pulls in quite a lot - a heavy build chain, other languages, bundle and runtime awkwardities. This puts a heavy burden on maintainability and testability of a project.

**Possible project integration solution**

To not pollute a project with the wasm build chain and foreign languages, my idea is to build "microlibs" for those filter functions as separate npm packages, which can replace existing functionality as a drop-in. This way the heavy wasm stuff can be developed/tested separately from the main project using it. Ofc one issue remains - it pulls those microlibs as additional deps and raises the bar during security audits.

**Where could xterm.js benefit?**
Hot candidates in xterm.js, that fit the _filter function_ idea, are the **UTF8 decoder** and the **wcwidth** calculations. They both could be replaced by a wasm drop-in easily. I am not eager to replace the parser or the terminal buffer (yet?), because of their heavy JS-entanglement and the need of re-allocations (quite cumbersome to bridge into wasm).

In the future a better unicode handling with grapheme clustering and base64 decoding would benefit from wasm.

Up for discussion.

@Tyriar, @mofux, @meganrogge, @Eugeny

**Comment by jerch** [comment]
Out of scope, thus closing.

**Comment by JavaCS3** [comment]
@jerch Please check this out https://blog.asciinema.org/post/smaller-faster/. asciinema(a terminal playback player) recently re-write terminal parser with Rust (compiled to WASM) achieved  50x faster. The source code is at https://github.com/asciinema/vt-rs.
https://github.com/asciinema/asciinema-player. I think you can take this as a reference.

**Comment by jerch** [comment]
@JavaCS3 Thx for finding this one. 50x speedup is really huge, on the other hand they started from very low throughput, while xterm.js with only builtin handlers is already at 15-30 MB/s for the full websocket->parsing->output chain.

For xterm.js I'd estimate the possible speedup more in 3-5x (thus ~100MB/s) with the current parser and buffer model. Main reason for not getting much higher is the fact, that full VT state handling as described by the parser on VT100.net is quite complex and thus easier to be dealt with by an FSM, which xterm.js does. But such an FSM creates quite a high mem lookup and branching penalty for state evaluation, and even in C cannot pass the 300-400 MB/s line on current hardware. For xterm.js there are more delays to account (websocket, event loop stalls, JS-wasm copying, wasm execution slower than native), thus my much lower estimate of ~100 MB/s.

(With giving up the current parser and buffer model certain aspects could be made much faster, esp. ASCII char processing, but that would involve tons of refactoring.)
