### ISSUE TITLE
Web Links Provider shouldn't accept "<>" Characters in opening / ending Clauses

### ISSUE THREAD

**Issue by pattch** [xtermjs/xterm.js#3539]
## Details
- Browser and browser version: All
- OS version: All 

### Steps to reproduce

1. Enter `$ echo "\<http://test.com\>"`
2. Hover over the link printed on the next line, which should be `<http://test.com>`
3. Observe that the link that is validated corresponds to `http://test.com>` which doesn't make much sense

Simply adding the `<>` characters to `NEGATED_PATH_CHARACTER_SET` and `NEGATED_DOMAIN_CHARACTER_SET` somewhat resolves this issue, but also has the issue that the test case above won't validate the link inside of the `<>` brackets as well.

**Comment by silamon** [comment]
`>` is being matched as the path of the url and is being matched by `([^:"\'\\s])`. 
https://github.com/xtermjs/xterm.js/blob/6c18b7f2cc91b923e765b03e572f9038e294d368/addons/xterm-addon-web-links/src/WebLinksAddon.ts#L18-L19

**Comment by Tyriar** [comment]
Seems fixed:

![Image](https://user-images.githubusercontent.com/2193314/207911709-295c4638-5942-499c-8acc-6578a845fd0a.png)
