### ISSUE TITLE
Make Web Links Regex Configurable

### ISSUE THREAD

**Issue by pattch** [xtermjs/xterm.js#3540]
Currently, the Web Links Addon has a hard-coded Regex used to match URLs, and this regex isn't always sufficient / comprehensive (related: #3539). It would be helpful to introduce some method to provide an alternative Regex, something along the lines of a `setUrlRegex(regex: RegExp)` that would de-register the existing link provider etc. and add a new one with the provided regex.

**Comment by Tyriar** [comment]
We could make `urlRegex` part of `ILinkProviderOptions`

**Comment by Heysunk** [comment]
Just as @Tyriar suggested I added urlRegex to ILinkProviderOptions. I haven't touched ILinkMatcherOptions since it is deprecated.
