### ISSUE TITLE
Announce deleted characters to screen readers

### ISSUE THREAD

**Issue by pattch** [xtermjs/xterm.js#3541]
## Details
- Browser and browser version: All
- OS version: All

### Steps to reproduce

1. Initialize a Terminal with `screenReaderMode` set to `true`.
2. Using a screen reader, after typing in the Terminal, enter `backspace` to delete a character
3. Observe that although the Terminal contents have changed, the deleted character is not announced
4. Compare to native Terminals, where the deleted characters are announced

Some screen readers announce the new character that's written in its place, `blank`, but that's not really a useful thing to announce. This may require some special-casing when entering e.g. backspace, but regardless this functionality is not working when compared to native Terminals.

**Comment by Tyriar** [comment]
Merging into https://github.com/xtermjs/xterm.js/issues/3542 as it's the same root problem
