### ISSUE TITLE
xTerm.js in WKWebview encounters characters disappeared on iOS 15

### ISSUE THREAD

**Issue by dongyg** [xtermjs/xterm.js#3543]
xTerm.js in WKWebview encounters characters disappeared on iOS 15

The problem just appears on xTerm.js combine WKWebView. The Safari and SFSafariViewController on iOS 15 are fine.

Comparison video ( iOS 13.7 vs iOS 15 ): https://youtu.be/R30yMe5Riao
Demo code: https://github.com/dongyg/Bug-xTerm.js-WKWebView

**Comment by Tyriar** [comment]
duplicate of #3357
