### ISSUE TITLE
A crashing character joiner brings down the whole terminal

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#3547]
In particular, `opentype.js` cannot parse the updated Monaco font file in macOS Monterey (`No valid cmap sub-tables found.`), rendering xterm unusable when the ligature addon is active.

**Comment by Tyriar** [comment]
Easy repro is probably to throw in the registerCharacterJoiner callback

**Comment by jerch** [comment]
On a sidenote - the particular issue might be fixed in `opentype.js` v0.9.0 (see https://github.com/opentypejs/opentype.js/issues/348), while `font-ligatures` still uses [v0.8.0](https://github.com/princjef/font-ligatures/blob/c9ad109fb9d873e67dc81c23a87fe7fb696d5f8b/package.json#L47).

**Comment by Eugeny** [comment]
It's not unfortunately - I've tried forcibly upgrading ot.js to their latest release

**Comment by jerch** [comment]
Ah ok. Well even if it was fixed, the character joiner should not tear down the whole terminal in the first place.

**Comment by LabhanshAgrawal** [comment]
What if we create an anonymous function to try catch the handler (which returns empty array on catch) and use that instead of the actual handler at
https://github.com/xtermjs/xterm.js/blob/master/src/browser/services/CharacterJoinerService.ts#L71-L74

**Comment by Tyriar** [comment]
I think we just need to catch and handle exceptions here:

https://github.com/xtermjs/xterm.js/blob/20141518d995b85a0a39e3e0352cf0a9db3e676c/src/browser/services/CharacterJoinerService.ts#L179-L182

**Comment by LabhanshAgrawal** [comment]
Yeah, that's the only place it's called at right now, so we can update there.
I was suggesting wrapping it, so that we don't have to worry about it later, in case it's called from other places. But that might not be necessary.

Should I go ahead and open a pr for this?

**Comment by Tyriar** [comment]
@LabhanshAgrawal I think that's the only place and probably won't change. That would be great!
