### ISSUE TITLE
canvas renderer CharAtlas life cycling/refreshing issue

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#3548]
OSC 4 should apply color changes immediately. While this works correctly in DOM and webgl renderers, the canvas renderer does not seem to refresh its `CharAtlas`.

Repro:
```bash
$> echo -e '\x1b[41mhello'
$> echo -e '\x1b]4;1;rgb:ff/ff/ff\x07'
```
The snippet outputs 'hello' with BG red. On entering the second command the color for SGR 41 changes to white, but the canvas renderer still applies its red shaped atlas entries.

Note that after changing the renderer forth and back to canvas it shows the correct glyphs.

Edit:
Btw changing the first line to `echo -e '\x1b[31mhello'` reveals, that the glyphs are not cleared/recolored for the canvas renderer.

**Comment by jerch** [comment]
@Tyriar If I add a `this._charAtlas.clear();` behind line 115 (acquireCharAtlas): https://github.com/xtermjs/xterm.js/blob/cb3dd19039732e8a6e2a0ed594cdad1448ff8084/src/browser/renderer/BaseRenderLayer.ts#L111-L117

the glyphs get correclty re-colored. Is it safe to add this here or will there be negative side effects?

**Comment by Tyriar** [comment]
@jerch think that would break the char atlas caching. Can you invalidate a single glyph in the char atlas instead? Might need to make a new `DynamicCharAtlas.deleteFromCache(glyph: IGlyphIdentifier)` which just makes that section of the texture dead space. Alternatively `DynamicCharAtlas.redrawToCache(glyph: IGlyphIdentifier)` which would redraw it in place, I think we can rely on dimensions being the same.

**Comment by jerch** [comment]
@Tyriar 
Well it would need to remove/replace all glyphs rendered from the old FG or BG setting. Is it possible to do such a "range" delete? Alternatively I could create IGlyphIdentifier lists and do it one by one.
Since I have no clue about the atlas mechanics - is it safe to invalidate single glyphs? Will it re-cache a missing one on next access without messing up the texture atlas?

**Comment by jerch** [comment]
@Tyriar Is there a specific reason, why `_refreshCharAtlas` gets called for all layers again (beside it being a method on a super class)? Isnt the text layer the only one contributing chars to the atlas? Either I get the semantics of it completely wrong, or it is not properly isolated against actions on other layers. Can you give some insights? It gets called from these layers:

```javascript
[TextRenderLayer, SelectionRenderLayer, LinkRenderLayer, CursorRenderLayer]
```
in that particular order. As far I have tested, neither a selection or a cursor over a char contributes any glyph entries.

Btw the clear thing above works, and properly refreshes the cache entries, even with the multiple layer calls (imho these multuple calls force the text layer to cache the changes a 2nd time). Starting with `echo -e '\x1b[31mhello'`:

![grafik](https://user-images.githubusercontent.com/6193135/141144079-4ed423b6-9a54-42f6-9e85-0a06b4dade1d.png)


and after entering `echo -e '\x1b]4;1;rgb:ff/ff/00\x07'` the atlas contains:

![grafik](https://user-images.githubusercontent.com/6193135/141144323-3ab53642-e465-47a0-bbb6-036f99f9e0d2.png)

**Comment by jerch** [comment]
Ok this issue goes deeper. While this correctly applies new theme colors in canvas renderer:

```javascript
term.setOption('theme', {red: '#00ff00', foreground: '#0000ff'})
```

this one does not:
```javascript
term.setOption('theme', {red: '#00ff00'})
```

**Comment by jerch** [comment]
Ok found the source of this: https://github.com/xtermjs/xterm.js/blob/0bc02d6838a2a75048001003617bf172efcf622b/src/browser/renderer/atlas/CharAtlasUtils.ts#L13-L20

Fix:
`ansi: colors.ansi` should be a deepcopy, with `ansi: [...colors.ansi]` everything works.

(This is prolly an reference vs. deep clone issue on by some other code skipping the introspection of individual ansi entries, happening somewhere around `acquireCharAtlas`).
