### ISSUE TITLE
Selecting a more than one line using API includes trailing CRLF

### ISSUE THREAD

**Issue by javier-godoy** [xtermjs/xterm.js#3552]
Selecting a whole line using API includes trailing `\r\n`.

## Details
- Browser and browser version: Chrome 95
- OS version: Windows 10
- xterm.js version: 4.14.0

### Steps to reproduce

1. ~~`terminal.resize(30,20)`~~
2. ~~`terminal.write("012345678901234567890123456789")`~~
3. ~~Select the line using the mouse.~~
4. ~~Confirm that `terminal.getSelectionPosition()` is `{startColumn: 0, startRow: 0, endColumn: 31, endRow: 0}`~~
5. ~~`terminal.select(0,0,31)`~~
6. ~~`terminal.getSelectionPosition()` is `{startColumn: 0, startRow: 0, endColumn: 1, endRow: 1}` and `getSelection()` returns `'012345678901234567890123456789\r\n'`~~

See [below](https://github.com/xtermjs/xterm.js/issues/3552#issuecomment-966505096).

**Comment by jerch** [comment]
Imho this works as expected. Note that you did not only select a whole line, but a whole line + 1 cell of the next line. The lines get concatenated with LF or CRLF. So you get:
```javascript
'012345678901234567890123456789'  // selection in first line, cell 0 - 30
+ '\r\n'                          // advance to next line
+ ''                              // selection in second line, cell 0 (which is empty)

**Comment by javier-godoy** [comment]
You are right, that was not a good example. in order to reproduce it I need to select more than one line (it doesn't matter if they are wrapped or not). When I select the first line, I end at `endColumn: 30, endRow: 0`, but when selecting the second line I end at `endColumn: 0, endRow: 2` instead of `endColumn: 30, endRow: 1`, which is an effect of

https://github.com/xtermjs/xterm.js/blob/376b29673ba174934b1b6339ef3eed8449fec529/src/browser/selection/SelectionModel.ts#L82

```
terminal.resize(30,20);

terminal.select(0,0,30); terminal.getSelectionPosition()
//{startColumn: 0, startRow: 0, endColumn: 30, endRow: 0}

terminal.select(0,0,60); terminal.getSelectionPosition()
//{startColumn: 0, startRow: 0, endColumn: 0, endRow: 2}
```
