### ISSUE TITLE
xterm-addon-web-links: Opening URLs in electron after version 0.2.1

### ISSUE THREAD

**Issue by BitStream1** [xtermjs/xterm.js#3557]
This is an awesome JS terminal emulator!

I wanted to notify you of a possible issue I observed while opening xterm.js weblinks in electron. The issue was introduced in the following change after xterm-addon-web-links > 0.2.1:
```
function handleLink(event: MouseEvent, uri: string): void {
  window.open(uri, '_blank');
}
```
Which was changed to:
```
function handleLink(event: MouseEvent, uri: string): void {
const newWindow = window.open();
  if(newWindow) {
    newWindow.opener = null;
    newWindow.location.href = uri;
  } else {
  console.warn('Opening link blocked as opener could not be cleared');
  }
}  
```
In: https://github.com/xtermjs/xterm.js/commit/a980b3d1323661f8d678bfa5c458ec4773712eed#diff-3160b575196132db9a03c3b3f748a1afd5ebc8ca44604bd9c8081f258a66e36c
The reason being in: https://github.com/xtermjs/xterm.js/issues/2608

The problem occurs because an electron app typically opens links in an external web browser, in the main process as follows:
```
win.webContents.setWindowOpenHandler(data => {
  electron.shell.openExternal(data.url);
  return { action: 'deny' };
});
```
(or via the deprecated new-window event)
See: https://stackoverflow.com/questions/32402327/how-can-i-force-external-links-from-browser-window-to-open-in-a-default-browser

The problem is that calling window.open() without the initial url, passes url as undefined to setWindowOpenHandler(), so there is no way to open the external link in electron, at least via this method (which seems to be the only one).

So, the question is whether it's possible to call window.open() with the url and still satisfy the requirements for the change > 0.2.1?

As far as I can see, there seems to be no other way to open xterm.js weblinks in electron (unless there is some other way of doing so). Reverting to 0.2.1 resolves the issue.

Also, would the concern discussed in: https://dev.to/dhilipkmr/why-should-you-use-noopener-beware-of-security-flaws-3i57 not be already handled by cross-origin security measures? Would clicking on a link really expose the source's window.opener to a 3rd party? If I open a 3rd party site from a link in xterm.js, I do see that window.opener is null in the console.

## Details
- Browser and browser version: Electron 13.5.2
- OS version: Windows 10, but not OS specific
- xterm.js version: 4.14.1
- xterm-addon-web-links: >0.2.1

### Steps to reproduce

1. Obtain/modify an existing electron project containing xterm.js that initializes the browser window as follows:
```
var win = new electron.BrowserWindow({
  webPreferences: {
    nativeWindowOpen: false
  }
});

win.webContents.setWindowOpenHandler(data => {
  console.log(data.url);
  electron.shell.openExternal(data.url);
  return { action: 'deny' };
});

```
2. Run the application and enter a URL in xterm.js.
3. Click on the web link.
4. Observe that data.url is logged above as undefined.
5. The expectation would be that data.url should be the url to be opened, in order to open the link externally in electron using the above method. As far as I can see, this seems to be the main/only method for opening browser links externally in electron.

BTW, just so you are aware, I see older versions of xterm-addon-* at: https://github.com/orgs/xtermjs/repositories. I see that these have been relocated to https://github.com/xtermjs/xterm.js/tree/master/addons but the stale, older repositories remain. Should these be removed, or annotated with a deprecation warning? (Actually, I see now that it has a "Public archive" label.).

**Comment by Tyriar** [comment]
For Electron you'll need to provide your own `handler` in the addon constructor: https://github.com/xtermjs/xterm.js/blob/0bc02d6838a2a75048001003617bf172efcf622b/addons/xterm-addon-web-links/typings/xterm-addon-web-links.d.ts#L23

> Would clicking on a link really expose the source's window.opener to a 3rd party?

AFAIK it is still a concern despite other security measures, no opener was actually a relatively recent contribution.

> but the stale, older repositories remain. Should these be removed, or annotated with a deprecation warning?

Some of them have this message:

![image](https://user-images.githubusercontent.com/2193314/142429761-80507816-dc5a-4eed-8781-285f8349b496.png)

I see web links doesn't so I'll fix that up https://github.com/xtermjs/xterm.js/issues/3558

**Comment by Tyriar** [comment]
For Electron you'll need to provide your own `handler` in the addon constructor: https://github.com/xtermjs/xterm.js/blob/0bc02d6838a2a75048001003617bf172efcf622b/addons/xterm-addon-web-links/typings/xterm-addon-web-links.d.ts#L23

> Would clicking on a link really expose the source's window.opener to a 3rd party?

AFAIK it is still a concern despite other security measures, no opener was actually a relatively recent contribution.

> but the stale, older repositories remain. Should these be removed, or annotated with a deprecation warning?

Some of them have this message:

![image](https://user-images.githubusercontent.com/2193314/142430575-25597681-b96e-445e-a887-1b7cde906723.png)

I see web links doesn't so I'll fix that up https://github.com/xtermjs/xterm.js/issues/3558

**Comment by Tyriar** [comment]
For Electron you'll need to provide your own `handler` in the addon constructor: https://github.com/xtermjs/xterm.js/blob/0bc02d6838a2a75048001003617bf172efcf622b/addons/xterm-addon-web-links/typings/xterm-addon-web-links.d.ts#L23

> Would clicking on a link really expose the source's window.opener to a 3rd party?

AFAIK it is still a concern despite other security measures, no opener was actually a relatively recent contribution.

> but the stale, older repositories remain. Should these be removed, or annotated with a deprecation warning?

Some of them have a message but I see web links doesn't so I'll fix that up https://github.com/xtermjs/xterm.js/issues/3558
