### ISSUE TITLE
The Edge browser listens for onkey events and calls back multiple s when typing a single S. Google Chrome does not have this problem

### ISSUE THREAD

**Issue by FFFFFQQQQ** [xtermjs/xterm.js#3561]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. Turn on edge input
2.

**Comment by Tyriar** [comment]
Are you using a really old version of Edge? The onKey event is meant to be fired multiple times with different key events.
