### ISSUE TITLE
CLI Terminal shortcut support

### ISSUE THREAD

**Issue by zlf341** [xtermjs/xterm.js#3567]
Do we have any support or add-ons for keyboard shortcut?

using keyboard shortcut like C-p, Esc-b, Esc-f, etc. (bash shortcut for CLI managment)

Thank you

**Comment by Tyriar** [comment]
See the docs for info on keybindings in the terminal https://code.visualstudio.com/docs/editor/integrated-terminal#_keybindings-and-the-shell

**Comment by Tyriar** [comment]
xterm.js supports these out of the box
