### ISSUE TITLE
text is truncated instead of wrapping 

### ISSUE THREAD

**Issue by LINALINLINA** [xtermjs/xterm.js#3568]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. 
![image](https://user-images.githubusercontent.com/19849988/144173884-26c5d774-5dea-4403-9812-6a326d4b5327.png)

2. expect result: 
![image](https://user-images.githubusercontent.com/19849988/144173999-bff18ff9-6684-4e43-852a-1972b12e7e27.png)

**Comment by romfrolov** [comment]
I experience the same behavior. I'm on Chromium, but the tmux is attached to a remote session on Ubuntu 20.

**Comment by Tyriar** [comment]
We'll need some more information on this to investigate, my suspicious is it's related to your backend.

@romfrolov if you're seeing it with tmux, chances are it's a tmux issue as wrapping is entirely handled by them.
