### ISSUE TITLE
Redundant text after resizing

### ISSUE THREAD

**Issue by dlanorf** [xtermjs/xterm.js#3569]
Redundant text shown after resizing the terminal wider, as show below:

![before](https://user-images.githubusercontent.com/44251003/144783486-88f2cd01-6170-487e-ab01-3dfb258d6cf9.PNG)

## Details
- Browser and browser version:  Chrome Version 96.0.4664.45
- OS version:  Win10
- xterm.js version: 4.15.0

### Steps to reproduce

1.  type a long text
2. resize the terminal wider

**Comment by Tyriar** [comment]
There is likely something going wrong with your backend to cause this

**Comment by dlanorf** [comment]
Hi, I checked my backend, and it seems send the right text, as shown in below screenshot I made in debug mode.

![k1](https://user-images.githubusercontent.com/44251003/145676353-635f42b3-919e-4556-98bb-48572de99628.PNG)

**Comment by Tyriar** [comment]
Not sure what I'm looking at exactly in the above screenshot. We'll need a working example for us to be able to investigate this.
