### ISSUE TITLE
Freeze when ligature addon

### ISSUE THREAD

**Issue by SquitchYT** [xtermjs/xterm.js#3593]
## Details
- Browser and browser version: electron v11.5
- OS version: ArchLinux
- xterm.js version: 4.16

### Steps to reproduce

1. Add ligature addon
2. Set the font to something that accept ligation (`Fira Code` for example)
3. The app freeze indefinitely without error

**Comment by SquitchYT** [comment]
This issue is probably related to https://github.com/princjef/font-ligatures/issues/23.
However, it is impossible to dispose the addon. Nothing happen when I use `.dispose()` and the ligature remains activated

**Comment by Tyriar** [comment]
Maybe related to crash in https://github.com/microsoft/vscode/pull/139537#issuecomment-998261114

**Comment by Eugeny** [comment]
@Tyriar I second @SquitchYT, the hang is inside `font-ligatures` and it happens for specific font files only.

**Comment by LabhanshAgrawal** [comment]
I'd opened https://github.com/princjef/font-ligatures/pull/24 for this, yet to be merged though

**Comment by Tyriar** [comment]
Merged, figuring out how to release now 🙂
