### ISSUE TITLE
How to get the return result of the command executed by the terminal 

### ISSUE THREAD

**Issue by yyy19961027** [xtermjs/xterm.js#3594]
![result](https://user-images.githubusercontent.com/66300848/148190917-dc3fc5e8-45a9-4115-9895-304d7f6d547f.png)
I want to get the string, but the result is garbled, I want to get the result displayed on the terminal after the terminal executes the command

**Comment by Tyriar** [comment]
Looks like escape sequences are being logged, this is probably something wrong on your end as xterm.js will only print escape sequences if the incoming data says to print them.

**Comment by yyy19961027** [comment]
This picture is the display that I printed out. The terminal display is normal. I want to get the normal string result. Like the terminal display, is there such an interface to directly get the display result of the terminal instead of the pty return

**Comment by Tyriar** [comment]
You can extract text from the terminal using the buffer API: 

https://github.com/xtermjs/xterm.js/blob/1fb11707a527836083d0bdd1275075c3ccf71db7/typings/xterm.d.ts#L1299

**Comment by yyy19961027** [comment]
> You can extract text from the terminal using the buffer API:
> 
> https://github.com/xtermjs/xterm.js/blob/1fb11707a527836083d0bdd1275075c3ccf71db7/typings/xterm.d.ts#L1299

First of all, I am very grateful, I get the right string, but can get the converted string after each new output.

**Comment by Tyriar** [comment]
You would need to call that API whenever the event you care about happens to get the new state of the buffer.

**Comment by yyy19961027** [comment]
Can &nbsp; you &nbsp;tell &nbsp; me &nbsp; how &nbsp;to &nbsp;use &nbsp;it.For &nbsp;example.


发自我的iPhone

------------------ Original ------------------
From: Daniel Imms ***@***.***&gt;
Date: 周六,1月 8,2022 01:17
To: xtermjs/xterm.js ***@***.***&gt;
Cc: yyy19961027 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [xtermjs/xterm.js] How to get the return result of the command executed by the terminal  (Issue #3594)





 
You would need to call that API whenever the event you care about happens to get the new state of the buffer.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yyy19961027** [comment]
I want to get the converted content of the newly received message, and I want to get the difference data, that is, every time the terminal outputs a line, I get a line of converted data. Is there such an interface?

**Comment by Tyriar** [comment]
As I said above, you would use the buffer API to get your data as the terminal sees it. Getting the converted data for just what happened (as opposed to the whole line) is not possible, you would need to make your own thing.

**Comment by yyy19961027** [comment]
I now get a certain line of output, I want to convert this line of output into the displayed terminal output (without garbled characters), is there a way to do this, or let me know which line the output returned by pty is written to
