### ISSUE TITLE
Support setting extended ansi colors (16-255)

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3601]
API proposal: `ITheme.extendedAnsi: number[]`, which would encode colors from index 16 (but not necessarily all of them).

VS Code ask: https://github.com/microsoft/vscode/issues/140235

**Comment by goenning** [comment]
@Tyriar @silamon How do I use these colors? If I have `extendedAnsi: [ '#dcdcdc' ]`, what should the space code be?

I thought it would:  ```\x1b[1;255mHello World\x1b[0m``` but it didn't work. Thanks

**Comment by Tyriar** [comment]
@goenning for 256 color you want:

```
\x1b[38;5;<index>m
```

So replacing index with 17 I think is what you want there?

**Comment by goenning** [comment]
That was it, thank you 🙌
