### ISSUE TITLE
windows系统上 运行几个命令后光标位置

### ISSUE THREAD

**Issue by songlujie** [xtermjs/xterm.js#3605]
![image](https://ae01.alicdn.com/kf/H3bc0e1c35f704519ab7fa6ac8f0da508A.png)

**Comment by luxi78** [comment]
你好。
It is polite to describe the problem in English and to write in detail.

**Comment by childrentime** [comment]
what problem? I don't see any wrong.

**Comment by Tyriar** [comment]
Chances are this is an issue with [conpty](https://github.com/microsoft/terminal) and therefore out of scope
