### ISSUE TITLE
Can not set xtermjs white words's color

### ISSUE THREAD

**Issue by NeroSolomon** [xtermjs/xterm.js#3608]
## Details
- Browser and browser version: chrome 97.0.4692.71
- OS version: macOS 11.5.2
- xterm.js version: 4.3.0

### Steps to reproduce

1. set white words's color when new Terminal
```js
this.xterm = new Terminal({      
     theme: {
        red: 'green',
        white: 'green',
      },
})
```

2. can't work
but those words which are red can be setting
![image](https://user-images.githubusercontent.com/28894970/149504750-c3484784-bdb2-452b-989b-4b111eebacf2.png)

**Comment by Tyriar** [comment]
I think you're looking for `foreground`:

https://github.com/xtermjs/xterm.js/blob/e1578813a79e657c81baa4f7632a30d0093cec71/typings/xterm.d.ts#L274-L276

**Comment by NeroSolomon** [comment]
@Tyriar Thx～ Unexpected.
