### ISSUE TITLE
Shift + Insert paste to xterm， but can not show correct

### ISSUE THREAD

**Issue by taoistwar** [xtermjs/xterm.js#3610]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. copy url

https://www.google.com/search?q=xx&oq=xx&aqs=chrome.0.69i59j0j69i60l2j69i65l2j69i60.5579j0j1&sourceid=chrome&ie=UTF-8

2. Shift + Insert paste to xterm.js

3. The xterm  can not show correct
![the not correct image](https://github.com/taoistwar/notes/blob/master/xterm.js/paste-not-correct.jpg?raw=true)

**Comment by Tyriar** [comment]
This seems to be fixed

![Image](https://user-images.githubusercontent.com/2193314/207912662-052eb2ef-50e1-47b3-bb17-73a11c21abd2.png)
