### ISSUE TITLE
output is overwritten

### ISSUE THREAD

**Issue by shaoyouwang** [xtermjs/xterm.js#3614]
## Details
- Browser and browser version: chrome 97.0.4692.71
- OS version: macos 12.1
- xterm.js version:  4.16.0

### Steps to reproduce
1. login to a linux server
2. set PS1 with color, such as:
PS1="\[\e[32;40m\]\[\u@\h \w \T\]$\[\e\[0m\]"

3. input characters more than one line, find that some content will be overwritten
<img width="874" alt="iShot2022-01-24 17 43 46" src="https://user-images.githubusercontent.com/10345126/150759053-14f36f6a-cdb9-4d20-9dec-4eb4187de2ee.png">

**Comment by Tyriar** [comment]
Overwriting like this is normally due to xterm.js having different dimensions to the backing pty

**Comment by rajiff** [comment]
I am having similar issue, I am not using a pty solution, why will it overwrite and cursor goes back to line 1 position 0

**Comment by jerch** [comment]
@rajiff You are most likely missing the CR --> CRNL replacements done by the PTY.
