### ISSUE TITLE
TypeError: e.composedPath is not a function

### ISSUE THREAD

**Issue by BenasPaulikas** [xtermjs/xterm.js#3615]
TypeError: e.composedPath is not a function
stack = "e[6465]/u</t.prototype._onMouseMove@https://domain.com/js/xterm.js?v=499162500:1:26031\n"

## Details
- Browser and browser version: 
mozilla/5.0 (windows nt 5.1; rv:52.0) gecko/20100101 firefox/52.0
- OS version: 
- xterm.js version: 
- newest(npm install xterm) yesterday

### Steps to reproduce

1. none. Everything works okay for thousands of users but this got this error.

**Comment by Tyriar** [comment]
You seem to be on an ancient version of Firefox, we [generally only support up to date browsers](https://github.com/xtermjs/xterm.js#browser-support).
