### ISSUE TITLE
Window contents not cleared properly

### ISSUE THREAD

**Issue by LabhanshAgrawal** [xtermjs/xterm.js#3617]
## Details
- Browser and browser version: Chrome 97
- OS version: macOS 11.6.2
- xterm.js version: 4.16

### Steps to reproduce

Run `ls -G && nvim` with webgl renderer

### With WebGL
<img width="700" alt="Screenshot 2022-01-29 at 11 09 25" src="https://user-images.githubusercontent.com/16598275/151649042-4083d275-28ec-4794-ba5b-973bfbb1cdfc.png">

### With Canvas
<img width="700" alt="Screenshot 2022-01-29 at 11 09 45" src="https://user-images.githubusercontent.com/16598275/151649040-046493d7-c9af-4dec-8c3d-7c5916c8d18c.png">

## Other Examples

![CleanShot 2022-01-16 at 10 12 01](https://user-images.githubusercontent.com/16598275/151650663-4f87d3db-bcf6-49c1-bc18-907d735a363a.gif)

https://github.com/vercel/hyper/issues/6242
https://github.com/vercel/hyper/issues/6239

I'm able to consistently reproduce using the steps above for webgl renderer, the hyper issue I've linked also mentions the same for canvas but I'm not able to get a consistent repro

### Finding
54375713bc2b049648f03540e611f9c3abd58561 is the first bad commit

@Tyriar I'm not familiar enough with xterm core code to fix this, I can try if you can provide some direction as to what might be wrong from the commit I've mentioned.

Till we can get this, we can use 4.15 since this affects usability a lot. But that version suffers from #3547, I've opened #3618 to work around that in ligatures addon itself

**Comment by jerch** [comment]
Seems `model.clear()` is too much here: https://github.com/xtermjs/xterm.js/blob/6c18b7f2cc91b923e765b03e572f9038e294d368/addons/xterm-addon-webgl/src/WebglRenderer.ts#L119-L134

Wild guess (because idk the cache/redraw-on-change logic behind) - the model clear in `setColors` leaves old cell drawings on screen, if it got called along with huge buffer changes, which is the case for neovim due to an altbuffer switch.

Indeed, can repro this "forgotten-onscreen-cells" issue with this line:
```bash
echo -e '\x1b[?1049h\x1b]11;rgb:00/00/ff\x07\x1b[31m\x1b[1;15HH\x1b[BE\x1b[BL\x1b[BL\x1b[BO'
```

With `this._model.clear();` commented out above the issue is gone.

**Comment by LabhanshAgrawal** [comment]
The explicit texture cleaning seems to work only the first time. From my example above, if you open `nvim` or `less` again then it happens at that point.

**Comment by jerch** [comment]
> The explicit texture cleaning seems to work only the first time. From my example above, if you open nvim or less again then it happens at that point.

Hmm, thats unfortunate. Maybe always aquiring a new atlas from `setColors` would help? (Thats done down in `_refreshCharAtlas` somewhere.)

**Comment by LabhanshAgrawal** [comment]
Can we get #3618 merged though? Will allow us to use 4.15 till this is fixed.

**Comment by Tyriar** [comment]
@LabhanshAgrawal I'll be going through the PRs hopefully today, just need to get through a pretty big terminal link refactor in vscode

**Comment by LabhanshAgrawal** [comment]
> > The explicit texture cleaning seems to work only the first time. From my example above, if you open nvim or less again then it happens at that point.
> 
> Hmm, thats unfortunate. Maybe always aquiring a new atlas from `setColors` would help? (Thats done down in `_refreshCharAtlas` somewhere.)

Same thing happening with new atlas also

**Comment by Tyriar** [comment]
Doesn't repro on Windows with wsl.exe as shell.

**Comment by Tyriar** [comment]
Can repro as well on macOS, investigating

**Comment by Tyriar** [comment]
Repro's in VS Code https://github.com/microsoft/vscode/issues/142091

**Comment by Eugeny** [comment]
The PR is working great :+1:

**Comment by Tyriar** [comment]
@Eugeny good to hear 🙂

**Comment by Tyriar** [comment]
@LabhanshAgrawal this fix is in xterm-addon-webgl@0.12.0-beta.24

**Comment by LabhanshAgrawal** [comment]
@Tyriar Awesome, thanks for the fix.
Unfortunately, just wasted multiple hours debugging why it works in xterm demo and not in hyper, just to realize that I also needed to use xterm 4.18.0-beta.2 instead of 4.17 😞

**Comment by Tyriar** [comment]
@LabhanshAgrawal oh sorry about that, you're right the change to [src/browser/services/RenderService.ts](https://github.com/xtermjs/xterm.js/pull/3624/files#diff-2c55cc3213368a05daba3b895bbb127ef81fa0dfa90f658ace9d89f12e963577) is in core

**Comment by LabhanshAgrawal** [comment]
> @LabhanshAgrawal oh sorry about that, you're right the change to [src/browser/services/RenderService.ts](https://github.com/xtermjs/xterm.js/pull/3624/files#diff-2c55cc3213368a05daba3b895bbb127ef81fa0dfa90f658ace9d89f12e963577) is in core

Sorry didn't mean to vent, just lamenting
