### ISSUE TITLE
Regression - Emoji Panel not working

### ISSUE THREAD

**Issue by LabhanshAgrawal** [xtermjs/xterm.js#3629]
## Details
- Browser and browser version: Chrome 97
- OS version: macOS 11.6.2
- xterm.js version: 4.17

### Steps to reproduce

1. Run the demo
2. Input anything using the Emoji panel

This broke in #3535 and works on reverting that (can't just do that and merge, as it's needed to prevent duplicate input)

https://user-images.githubusercontent.com/16598275/152861179-73d93213-baab-4a4a-aa44-dcd3b60bc043.mp4

**Comment by lgarron** [comment]
Can confirm that this is also broken for me in VSCode on macOS — I thought something was wrong with the computer!

**Comment by hello-smile6** [comment]
Can reproduce on Chromium OS, build by @google with API keys.

**Comment by Tyriar** [comment]
This is too stale and AFAICT it works fine with xterm.js in VS Code

**Comment by lgarron** [comment]
> This is too stale and AFAICT it works fine with xterm.js in VS Code

Can confirm as well!

Sometimes the emoji palette appears in the upper left of the screen because it doesn't know where the cursor is, but this usually still allows emoji input and corrects itself.
