### ISSUE TITLE
Allow decorations to show up in the scroll bar

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3632]
Similar to monaco:

![image](https://user-images.githubusercontent.com/2193314/153410953-fc4eb492-1b22-49ee-8c27-164a7a07c9a5.png)

**Comment by meganrogge** [comment]
Just like the editor, should show a decoration for the cursor is when it's outside of the viewport (because you've scrolled)

**Comment by Tyriar** [comment]
Not sure showing the cursor is that useful as it's always in the viewport down the bottom and almost always on the very last line

**Comment by meganrogge** [comment]
Yeah good point
