### ISSUE TITLE
How to listening copy and paste events?

### ISSUE THREAD

**Issue by yoyo-milktea** [xtermjs/xterm.js#3640]
verson: 4.14.1
now, i want to get the content of copy or paste every time and send it to the server, but i don't know how to listen it.
`
term.onPaste()
`
Uncaught TypeError: term.onPaste is not a function

**Comment by yoyo-milktea** [comment]
version 3.0 can use the follow ways to listen the paste event:
`
term.on('paste',e => {}) 
`
but the version 4.0 can't not use it any more,can you tell me how to listen copy and paste events?

**Comment by Tyriar** [comment]
To listen to paste you need to intercept the keypresses you're after with this API:

https://github.com/xtermjs/xterm.js/blob/4da2db8e0b5e0e4b62cabb3b8cbc9d26f0ed21cb/typings/xterm.d.ts#L848-L857

**Comment by yoyo-milktea** [comment]
However, my copy and paste events are not realized through keyboard events. The right mouse button menu also has the function of copy and paste. I want to know how to listen this event.

**Comment by yoyo-milktea** [comment]
wow,it's really work.Thank you!
