### ISSUE TITLE
Refuse to install

### ISSUE THREAD

**Issue by DarkTerrorWolf** [xtermjs/xterm.js#3646]
Neither the project folder or pwd to project has xterm within it.

` code ENOSELF
npm ERR! Refusing to install package with name "xterm" under a package
npm ERR! also called "xterm". Did you name your project the same
npm ERR! as the dependency you're installing?`

a default Xterm is installed in Linux ubuntu by default.
npm is installed and up to date 
Node.js is also current.

with just the package.json file throws this error. as well as having the git clone within the Downloads folder of my computer.

## Details
- Browser and browser version: N/A
- OS version: Ubuntu 20.04 LTS
- xterm.js version: 4.17.0

### Steps to reproduce

1.git clone https://github.com/xtermjs/xterm.js.git
2. cd xterm.js/
3. npm install xterm

**Comment by Tyriar** [comment]
You're trying to install xterm.js inside the xterm.js repo and npm is telling you that's not a good idea, I agree with npm.
