### ISSUE TITLE
Wrong layout if container height=0 width=0

### ISSUE THREAD

**Issue by mustard-mh** [xtermjs/xterm.js#3647]
## Details
Same as title. you can see demo changes here https://github.com/mustard-mh/xterm.js/commit/d62b42a469ad2e9aa1a294702018fa80999efd36#diff-3fd76301be96a42ea090e36d36ec9c97f4b9a5cca5f8bc9040dc4888b4817e5dR11-R15

If you resize the terminal, the layout will be weirder

`FitAddon` fit terminal into cols=2 rows=1, but the text should be rerendered again in some cases

### Steps to reproduce
1. Run demo code of branch https://github.com/mustard-mh/xterm.js/tree/hw/layout-reproduce
    - You can use Gitpod 
    [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#github.com/mustard-mh/xterm.js/tree/hw/layout-reproduce)
2. Change option `cols=80` `rows=24` (example)

|ChangeOptions|BugCapture|
|:-:|:-:|
|![img](https://user-images.githubusercontent.com/20944364/154344365-ffd5c0a2-691c-4353-9567-1b2df3bb885a.png)|![img2](https://user-images.githubusercontent.com/20944364/154344476-39c51629-20ed-4567-8955-fbfe50fd0fc2.png)|

**Comment by Tyriar** [comment]
I believe the issue where the prompt gets wrapped is working as expected because the shell redraws the prompt after resize on a new line and doesn't attempt to clear the old ones.

**Comment by Tyriar** [comment]
I see the actual fix for the fallback dimensions bug in VS Code was identified downstream 👌
