### ISSUE TITLE
`onBufferChange` api not work

### ISSUE THREAD

**Issue by NO-MAP** [xtermjs/xterm.js#3648]
## Details
- Browser and browser version:   chrome 97
- OS version:   windows
- xterm.js version: 4.17.0

### Steps to reproduce

 i am using `onBufferChange` to log `buf`.
```
import Terminal as TerminalJs from 'xterm'

const term = new TerminalJs()
...

term.buffer.onBufferChange((buf) => {
  console.log(buf.type)
})
```
it's not working

**Comment by Tyriar** [comment]
It works, it's probably not working as expected because you're on Windows. I'm not sure if conpty uses the alt buffer at all.
