### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by eljeffeg** [xtermjs/xterm.js#3652]
It seems that there is no option for text-align.  Everything written in the term, per line, is left aligned.  Example `term.write('test')` output in html:
```
<div style="width: 600px; height: 15px ;line-height: 15px; overflow: hidden;">
    <span>t</span>
    <span>e</span>
    <span>s</span>
    <span>t</span>
</div>
```
While this might best replicate a terminal, it would be great to allow the flexibility of alignment by adding the `text-align` style for the line, such that one might be able to do something like `term.write('test', align=center)` to create:
```
<div style="width: 600px; height: 15px ;line-height: 15px; overflow: hidden; text-align: center;">
    <span>t</span>
    <span>e</span>
    <span>s</span>
    <span>t</span>
</div>
```
A broader option might be to allow a class to be defined `term.write('test', class='myclass')` and thus allowing user defined styles per-line, such as underline, shadow, alignment, etc.
```
<div style="width: 600px; height: 15px ;line-height: 15px; overflow: hidden;" class="myclass">
    <span>t</span>
    <span>e</span>
    <span>s</span>
    <span>t</span>
</div>
```

**Comment by eljeffeg** [comment]
A broader option might be allow a class to be defined, which would allow the option of per line styles.

**Comment by Tyriar** [comment]
This isn't really how terminals work, xterm.js won't support doing this natively as in/out is all encoded as a text stream. You would need to position the text on your end based on the width of the terminal, naively something like this:

```ts
function writeCenter(term, text) {
  term.write('\x1b[${Math.floor((term.cols - text.length) / 2)}G${text}');
}
```

**Comment by eljeffeg** [comment]
That doesn't seem to do anything for me except put `'\x1b[${Math.floor((term.cols - text.length) / 2)}G${text}'` in the terminal as text.
