### ISSUE TITLE
Set timeout?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [xtermjs/xterm.js#3665]
Is there currently any way to set the timeout that auto-closes the terminal? I'm using xterm within a container app (Portainer) and if you dont do anything in the terminal window it closes within like 30 seconds. Very frustrating.

**Comment by childrentime** [comment]
If you don't use xterm, will the terminal you manually open close within 30s if you dont do anything?

**Comment by Tyriar** [comment]
If it's auto closing it sounds like it's on the server end.
