### ISSUE TITLE
input parsed during a buffer clear is incorrectly positioned and duplicated 

### ISSUE THREAD

**Issue by meganrogge** [xtermjs/xterm.js#3672]
Reproducible in powershell:
- run some commands
- run terminal: clear (or trigger buffer clear)
- quickly type some input
- 🐛  it's not positioned correctly

reported here https://github.com/microsoft/vscode/issues/144292#event-6174822792

**Comment by Tyriar** [comment]
See https://github.com/microsoft/vscode/issues/144292, nothing we can do about this afaik
