### ISSUE TITLE
How to get ANSI color codes?

### ISSUE THREAD

**Issue by Lee-42** [xtermjs/xterm.js#3681]
I try to render the output of node-pty onto Xterm.
The output of node-pty has ANSI color codes, which are then rendered to Xterm with various colors. Is there any way to get a string containing ANSI colors from Xterm?

![1](https://user-images.githubusercontent.com/95179300/158343960-0b657390-f041-4880-a416-2bb09ed94f41.jpg)

**Comment by Tyriar** [comment]
You can get this via the `Terminal.buffer` API, there is also the serialize addon which lets you serialize parts of the buffer back into a string with ANSI sequences.

**Comment by Lee-42** [comment]
thanks, it worked
