### ISSUE TITLE
Alignment for overview ruler decorations on the same line is off

### ISSUE THREAD

**Issue by meganrogge** [xtermjs/xterm.js#3683]
The alignment seems off with these:

![image](https://user-images.githubusercontent.com/2193314/158492225-caf2d6c1-bcbd-4dbf-9be8-5ed2cbe6d672.png)

Also blue/right is being drawn largest?

_Originally posted by @Tyriar in https://github.com/xtermjs/xterm.js/pull/3676#discussion_r827513493_

**Comment by Tyriar** [comment]
Current:

![image](https://user-images.githubusercontent.com/2193314/158588935-6963d628-2653-41e1-b674-17b78dd939c8.png)

Expected:

![image](https://user-images.githubusercontent.com/2193314/158589022-57b9d806-95ee-4a08-acd2-69c92c2627a8.png)

**Comment by Tyriar** [comment]
Also monaco does 2px tall for full and 6px for others, we're at 3px and 7px currently
