### ISSUE TITLE
Registered decorations onRender can fire event containing the overview-ruler element

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3686]
I added this code to VS Code:

```ts
		const decoration = this._terminal.registerDecoration({
			marker
		});
		if (decoration) {
			decoration.onRender(element => {
				console.log('element', element);
				element.style.backgroundColor = 'yellow';
			});
			timeout(2000).then(() => decoration.dispose());
		}
```

And I see a yellow scroll bar:

![image](https://user-images.githubusercontent.com/2193314/158620279-49fb06f2-ee61-46b3-b6ce-bd9a762e5fff.png)

And these logs:

![image](https://user-images.githubusercontent.com/2193314/158620332-d15e5310-6bd3-44ed-8884-9ef37d56277f.png)

**Comment by meganrogge** [comment]
That was intentional because we should leave it up to embedders to use this element or filter it out as needed.

**Comment by Tyriar** [comment]
Rendering for the overview ruler is totally controlled by xterm.js so the embedder shouldn't ever need to touch it, it also makes the API harder to understand/use imo.
