### ISSUE TITLE
Optimize rendering of decorations in overview ruler

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3703]
VS Code issue: https://github.com/microsoft/vscode/issues/145751

Could repro this slowness by filling the buffer and then searching for a single letter, this is on a 12th gen i7 (fast modern CPU):

![image](https://user-images.githubusercontent.com/2193314/159537006-1d816cc3-e42f-45b1-a3b4-5a6f1f74126d.png)

A similar thing happens when pressing enter in this state since we don't do any diffing, just clear and re-render.

Ideas to explore:

- Move from rendering each decoration to calculating colored zones which merge similar rectangles into the same zone and render them
- If the buffer is full, explore shifting the texture up depending on how much scrolling occurs (might be tricky to get right)

**Comment by meganrogge** [comment]
When the buffer is full, could we just set the top of the canvas and increase its height?

What I mean is let's say buffer length is 50. When line 51 is added, we set top of the canvas to `-decorationHeight`

**Comment by meganrogge** [comment]
For the case when the buffer isn't full, i was wondering if there's some transform (math) we could do to the canvas to shrink it height wise proportional to the amount that gets added instead of having to actually draw the decorations.

**Comment by Tyriar** [comment]
> When the buffer is full, could we just set the top of the canvas?

We could essentially do this by drawing the canvas to itself via `drawImage(canvas, ...)`, but getting it just right might be tricky. Say 1 row gets trimmed off the top, that might not end up being a complete pixel depending on the dimensions of the terminal, it would be a floating point number that needs to be tracked so the remainder can be applied next. It probably won't end up working in the end as a rerender would end inevitably up shifting some of the pixels.

A better approach would probably be to do the color zone idea and explore shift that instead if performance is still poor after that change.

> For the case when the buffer isn't full, i was wondering if there's some transform (math) we could do to the canvas to shrink it height wise proportional to the amount that gets added instead of having to actually draw the decorations.

You could do some transform of the existing image but I think it suffers from the same problems, in addition to blurriness coming in as well.
