### ISSUE TITLE
Search result numbering seems illogical

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#3724]
It seems that the "first" search result as reported by `onDidChangeResults` is arbitrary, e.g. here the result #0 is the 3rd one from the end: 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/161476/161429160-0cee2b67-0e6c-403e-8683-ed19ae612873.png">

**Comment by Tyriar** [comment]
fyi @meganrogge
