### ISSUE TITLE
On change of font size the viewport is changing automatically

### ISSUE THREAD

**Issue by shashank-gowda** [xtermjs/xterm.js#3755]
On change of font size the viewport is changing automatically. The expected behaviour should be, the height and width of the xterm screen should remain same even when the font size is changed.

## Details
- Browser and browser version: All Browser
- OS version: MAC 12.2.1
- xterm.js version: 4.17

### Steps to reproduce

1. Open terminal with some default font size.
2. Change the font size and just refresh the terminal, the viewport expands/shrinks automatically based on the new font size set.

**Comment by Tyriar** [comment]
This isn't how the library works, the size is set to a width/height regardless of the font family/size. You probably want to use the fit addon and call fit whenever you change the font size.
