### ISSUE TITLE
Terminal cannot display text when created in a react portal window.

### ISSUE THREAD

**Issue by JoshuaH-sudo** [xtermjs/xterm.js#3758]
I am working on a react project, where we want to popout a terminal into a separate window. ([Here is the basic premise of how it works](https://medium.com/hackernoon/using-a-react-16-portal-to-do-something-cool-2a2d627b0202))

In my main project, though the terminal in the new window does open and all other functions involved within the component work, for some reason the text does not display in that popout window. 

The cursor will be in correct position and spaces will be created for lines, as if the text is there. I know that the terminal is receiving data but for some reason, it appears as if the canvas part of the terminal is unable to draw the text.

I was able to get the popout terminal to display partial text once or more by chance, when i created a lot of terminals in the popout window (I am unable to provide a consistent way of doing this). Leading me to believe there could be a problem with how other parts of the xterm.js source code handles getting the document element, weather it grabs from the default main browser window, by simply calling `document` or if someway it can get the window/ document object from the container element that is passed to terminal on `terminal.open()`.

As you will see in the test repo I provided, I had to ensure I got the correct document by accessing the new window in the `<Portal/>` component in App.js. But that is my guess as to what is happening. Please let me know if you need any more information.

## Details
- Browser and browser version: FireFox 99.0.1 (64-bit)
- OS version: Windows 21H2
- xterm.js version: ^4.18.0"
![xterm-bug-test](https://user-images.githubusercontent.com/82687433/166408667-50565bbd-88fe-492b-87e0-b6ca72832db1.png)

### Steps to reproduce
1. Clone the test repo i have created ([here](https://github.com/JoshuaH-sudo/window-xterm.js-test))
2. run "npm i"
3. run "npm start"
4. should then see the terminal is created on the main browser window with the text showing, then in the popout window there will be a terminal present but no text displayed.

**Comment by Tyriar** [comment]
This seems like an issue either with react or firefox, closing as we don't plan to look into it. Let me know if you have more information proving otherwise though

**Comment by joshh101** [comment]
Hi @Tyriar, I have tested on both Firefox and Chrome and the error occurs on both. 

Other react components that are not using xterm.js also work fine. Xterm.js seems to be working for the most part, just the characters are not visible.

**Comment by mihaip** [comment]
@joshh101 I've sent a PR that should fix this (#4069) -- I don't believe it's a framework-specific issue.
