### ISSUE TITLE
louder flow control warnings

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#3760]
Should we place louder flow control warnings somewhere? Almost every project I found on github using xterm.js does not care at all (already wrote various issues). Also not sure, where to place it to raise awareness (seems that the guides are not read).

Any ideas?

**Comment by Tyriar** [comment]
I point people at the demo for a reference implementation so maybe a warning/recommendation to use flow control here?

https://github.com/xtermjs/xterm.js/blob/66be7797cf620d23e458b945eff1523ed5dfc9d8/demo/server.js#L117
