### ISSUE TITLE
CSS: Selectors should not be duplicated

### ISSUE THREAD

**Issue by billchurch** [xtermjs/xterm.js#3780]
The `.x-term` selector is defined twice in `/css/xterm.css`

https://github.com/xtermjs/xterm.js/blob/56c7c5c4eda4ef55005b0370d49087b69c8bb2c6/css/xterm.css#L38-L43

and 

https://github.com/xtermjs/xterm.js/blob/56c7c5c4eda4ef55005b0370d49087b69c8bb2c6/css/xterm.css#L127-L129

`cursor: text;` should be able to be collapsed under the first definition of .xterm on L38.

Is there a reason this is being done this way?

**Comment by Tyriar** [comment]
Probably just an oversight, seems safe to combine them since the only `cursor` rule above it is more specific
