### ISSUE TITLE
registerLinkProvider hover's mouseEvent target is previous mouseEvent target

### ISSUE THREAD

**Issue by MOBUMIN** [xtermjs/xterm.js#3797]
## Details
- Browser and browser version: Chrome 101.0.4951.64 (arm64)
- OS version: linux?
- xterm.js version: 4.18.0

### Steps to reproduce

1. xterm.registerLinkProvider({range, text, activate, hover}: ILink) 
2. hover(mouseEvent){ console.log(mouseEvent.target) } ;
3. 
![xterm-hover](https://user-images.githubusercontent.com/57705512/168213231-3807a1e3-6db4-45e5-8ba2-c996d7eae007.gif)

**Comment by Tyriar** [comment]
I can't reproduce on master which shows the span as the hovered characters when using the DOM renderer:

![image](https://user-images.githubusercontent.com/2193314/168291680-5d1f932e-d9eb-4226-b907-286eb94ab328.png)
