### ISSUE TITLE
Xterm.js is not using imported fonts

### ISSUE THREAD

**Issue by Cveinnt** [xtermjs/xterm.js#3817]
Hello! So I am trying to style xterm with imported fonts using styled-components. I've included the imported font-face in GlobalStyle and added it to my Next.js app.

To change fonts, I am using ITerminalOptions to configure fontFamily, however, it does not seem to be working as imported fonts are skipped and only system fonts are loaded.

## Details
- Browser and browser version: Safari, Chrome, Firefox, Brave
- OS version: Mac OS Monterery 12.3.1
- xterm.js version: 4.18.0

### Steps to reproduce
Detailed above.

**Comment by Tyriar** [comment]
I think you're after https://www.npmjs.com/package/xterm-webfont

**Comment by Cveinnt** [comment]
Was not aware that package exists - many thanks!
