### ISSUE TITLE
Minimum contrast ratio isn't working for inverted text in DOM renderer

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3846]
minimumContrastRatio = 4.5:

![image](https://user-images.githubusercontent.com/2193314/171460819-1e3c2c24-5300-42dc-a749-edd774078f32.png)

minimumContrastRatio = 9:

![image](https://user-images.githubusercontent.com/2193314/171460891-01b78caa-2321-48ef-b9c1-77f90ec3f8f7.png)

**Comment by meganrogge** [comment]
the `cr` is wrong here when called from the dom renderer row factory https://github.com/xtermjs/xterm.js/blob/de03391c2d6bc1eb3b66c56e838ec8968b85cad8/src/common/Color.ts#L169
