### ISSUE TITLE
Add helper button to print a wide range of ansi colors

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3850]
Similar to the box drawing and powerlines buttons in the test tab of the demo, a helper for printing out different color modes would be of great help. Something like this to give an idea, but that prints every color (a separate button for each color mode?)

```
echo -e '\x1b[0mDefault'
echo -e '\x1b[7mDefault (inverse)\x1b[0m'
echo -e '\x1b[33mPalette 16 (color #3, yellow)\x1b[0m'
echo -e '\x1b[38;5;50mPalette 256 (color #50)\x1b[0m'
echo -e '\x1b[38;2;255;0;0mRGB/True color (color #FF0000)\x1b[0m'
```

**Comment by deepanshu44** [comment]
Hello @Tyriar , In this particular issue, is it required to print something like [this](https://superuser.com/a/441853)?

**Comment by Tyriar** [comment]
@deepanshu44 basically yeah, but also including true color and both foreground and background styles.

**Comment by deepanshu44** [comment]
Forgive my ignorance, but I am unaware of what _true colors_ are.
And also, what do you mean by both foreground and background styles?

**Comment by Tyriar** [comment]
@deepanshu44 np. FYI these are just the different types of colors, the 38;2 above is true color, foreground uses 3x, background uses 4x

**Comment by deepanshu44** [comment]
@Tyriar Thanks for providing FYI, I understood what's supposed to be done. 

If I am correct than,  the end results should look something like [this](https://robotmoon.com/256-colors/) displaying 256 colors.

**Comment by Tyriar** [comment]
@deepanshu44 yep 👍

**Comment by deepanshu44** [comment]
Hello @Tyriar , I need to ask whether in order to display colours,  are we required to use a script or write `term.write()` multiple times? 

Both ways are fine for me.

**Comment by Tyriar** [comment]
The `term.write` approach is best as a script wouldn't work across all shells/operating systems. For the order, something like how underline colors are show (0-255, then some color ramps?):
<img width="803" alt="Screen Shot 2022-07-31 at 3 24 30 pm" src="https://user-images.githubusercontent.com/2193314/182047679-f7ae8083-4e1e-486b-bfc5-8c2cf0e57271.png">
