### ISSUE TITLE
xterm-addon-search has the wrong result

### ISSUE THREAD

**Issue by liuxi0811** [xtermjs/xterm.js#3858]
![image](https://user-images.githubusercontent.com/75471072/173319361-e793aed5-0b12-4690-8d3b-795a5e02c2ad.png)
![image](https://user-images.githubusercontent.com/75471072/173319429-552abf18-0842-4406-81aa-a7c6909bcb08.png)
![image](https://user-images.githubusercontent.com/75471072/173319501-9c639c9f-72bc-42e6-8923-022a97d6eb6e.png)

**Comment by Tyriar** [comment]
What version are you using? The search addon went through some very significant changes recently that are not yet released as stable.

**Comment by vidhimultiqos** [comment]
> What version are you using? The search addon went through some very significant changes recently that are not yet released as stable.

Hey @Tyriar, We have to face the same issue in our application.

We have used below packages and versions:
xterm: "^5.0.0",
xterm-addon-search:"^.010.0"


While we are searching any words, Function (searchAddon.findNext("ls")) returns false.

**Comment by Tyriar** [comment]
@liuxi0811 the example you gave I think may be expected as you do the initial search and don't capture the value, then log the second search which doesn't succeed?

![image](https://user-images.githubusercontent.com/2193314/204879364-9200e092-b8a1-4dd1-88f0-f028e9bf65f6.png)

**Comment by Tyriar** [comment]
This issue is too old, if it still happens ideally we'd want more solid repro steps so it's easier to investigate.
