### ISSUE TITLE
The terminal is only black and white

### ISSUE THREAD

**Issue by TheBlindM** [xtermjs/xterm.js#3875]
## Details
- Browser and browser version:  last
- OS version:  windows 10
- xterm.js version:  4.18.0

### Steps to reproduce
Frontend
```
 const term: Terminal = new Terminal({
    rendererType: 'canvas', 
    pid: 1,
    name: 'terminal',
    convertEol: true, 
    scrollback: 800,
    disableStdin: false, 
    cursorStyle: 'block', 
    cursorBlink: true, 
    tabStopWidth: 8, 
    screenKeys: true, 
  });
```
----------------------------------------------------------------------------------
Backend

`shellChannel.setPtyType("ansi");`

I see that other people's command output has color, how can I change it, can you help me? Many thanks

**Comment by Tyriar** [comment]
This is normally because you set `TERM` to something other than xterm-256color. You can see the demo in the repository which shows color for an example
