### ISSUE TITLE
CustomKeyEventHandler does not override XTERM's default keybindings

### ISSUE THREAD

**Issue by galefino** [xtermjs/xterm.js#3880]
I'm trying to use CustomKeyEventHandler to make my application behave a certain way, but shortcuts such as Ctrl+7 / Ctrl+Shift+- are not overridden by the new handler.

### Steps to reproduce

1. Attach a new customKeyEventHandler to the term
2. Write data into the term
3. Trigger Ctrl+7

**Comment by Tyriar** [comment]
When I run this in the demo it logs and disables all keys including ctrl+7 so it seems to be working fine?

```
term.attachCustomKeyEventHandler(e => {
    console.log(e);
    return false;
})
```

**Comment by Tyriar** [comment]
It's working for me:

![image](https://user-images.githubusercontent.com/2193314/190173167-a7ce4d84-d45c-4a28-8060-1b1ea1fb914f.png)
