### ISSUE TITLE
Fit should use the full size instead of rounding down

### ISSUE THREAD

**Issue by arcanis** [xtermjs/xterm.js#389]
Let's say that a character height is 18px. If the terminal container has a size of 24px, then the fit algorithm will give the terminal a size of 18px, without instructing it to fill the remaining 6px in any way. It causes a kind of graphical glitch where elements looks unaligned:

![image](https://cloud.githubusercontent.com/assets/1037931/20868521/f4b123cc-ba5d-11e6-8c47-5b7829bb0072.png)

A workaround is possible by setting `height:100%` on the `.terminal` selector, but it doesn't affect the scrollbar and, as such, doesn't resolve entirely the issue (the scrollbar still isn't aligned to the bottom of the container).

I think an acceptable fix would be to add a "pad" option on the terminal, that would instruct the terminal to add N pixels at the top of its elements (both inside the scrollable content and on the scrollbar height itself). The fit algorithm could then use this option to automatically compute the number of missing pixels, in such a way that users wouldn't have to set it themselves.

**Comment by Tyriar** [comment]
Personally I think this should be left up to the consumer to handle, it's as easy as using flex box to align to the bottom or rolling your own js to add the pad if you can't.

**Comment by arcanis** [comment]
I think the main issue is that in order to support extending the scrollbar area, any userland code would have to make assumption about the html elements generated by xterm.js, assumptions that might break at any time (for example I believe you recently reworked the scrollbar). I would feel more confident if the library was handling this instead of me.

**Comment by Tyriar** [comment]
Now that you mention it there is something is a bit off with the scrollbar when the element with the way I'm positioning the terminal as the scrollbar isn't being re-positioned as well. I'll see if I can look at a way to do this nicely for the next release (time permitting).

**Comment by Tyriar** [comment]
The sizing has changed a lot since this was made, not sure it's an issue anymore
