### ISSUE TITLE
Terminal has borders on the bottom and right.

### ISSUE THREAD

**Issue by superlopez-real** [xtermjs/xterm.js#3911]
## Details
- Browser and browser version: electron 18.3.5
- OS version: macOS 13 beta 3
- xterm.js version: 4.18.0

### Steps to reproduce

1. Download my repository (only tested on mac): https://github.com/superlopez-real/kaiium
2. look at the borders.
![Screenshot 2022-07-19 at 12 43 59](https://user-images.githubusercontent.com/90651091/179804194-efd0d1d2-758e-460f-9dcd-e7b4a68444c1.png)

**Comment by Tyriar** [comment]
This is a problem you'll need to polish on your end. xterm.js works on a grid, so that gap is the when there is not enough room for another row/column. Some ideas: center it, align it to the bottom, change the background of `body` to the use the same background as xterm.js.

**Comment by superlopez-real** [comment]
> This is a problem you'll need to polish on your end. xterm.js works on a grid, so that gap is the when there is not enough room for another row/column. Some ideas: center it, align it to the bottom, change the background of `body` to the use the same background as xterm.js.

What css elements should be changed then?

**Comment by Tyriar** [comment]
An ancestor of the element you passed into `Terminal.open` since this is controlled outside of the element xterm.js is hosted within

**Comment by superlopez-real** [comment]
> An ancestor of the element you passed into `Terminal.open` since this is controlled outside of the element xterm.js is hosted within

ooh ok, thanks a lot mate
