### ISSUE TITLE
Overlapping data inside curses applications

### ISSUE THREAD

**Issue by shashank-gowda** [xtermjs/xterm.js#3914]
In Curses-based text interface, few data are overlapping. I'm attaching the screen shots of it.

## Details
- Browser and browser version: 
- OS version: macOS Monterey
- xterm.js version: 4.17.0

### Steps to reproduce

1. This is the initial screen we get and it is perfectly rendered.
<img width="884" alt="1" src="https://user-images.githubusercontent.com/19536318/180018616-f81072ad-fcf4-465a-824e-848001e23ef1.png">

2. Later I will select the first option and press enter key. We end up getting the data on top of the existing data. Which is also fine.
<img width="882" alt="2" src="https://user-images.githubusercontent.com/19536318/180018954-47159b2b-7b3a-49a8-8fd3-bebce1ea154c.png">

3. I will press Esc+3 option to cancel the above screen, which will take me to the first screen, where the control options data is overlapped. The overlapping data is highlighted 
<img width="884" alt="3" src="https://user-images.githubusercontent.com/19536318/180019857-5c1ad65a-936d-4541-a09c-ce8610ac3934.png">

**Comment by Tyriar** [comment]
Possibly related: https://github.com/xtermjs/xterm.js/issues/3878

**Comment by Tyriar** [comment]
Let's track there

**Comment by shashank-gowda** [comment]
I still see this issue in the latest release 5.0
