### ISSUE TITLE
xterm selection conflict with search addon

### ISSUE THREAD

**Issue by alanhg** [xtermjs/xterm.js#3915]
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/9245110/180164089-8307dfec-6f37-4e75-be5b-d3cb7c79eaed.png">

When the keywords are entered to perform the search, gray blocks will directly appear to cover the hit results when searching the text.

I found the it's selection. maybe it's conflict? 

render canvas is ok, but dom has issue.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/9245110/180181494-aa458c55-5a67-439f-8081-8054bbd8e2a4.png">

## Details
- Browser and browser version:  Chrome v103.0.5060.134
- OS version: Big Sur 11.6.7
- xterm.js version:  
  "xterm": "^4.19.0",
   "xterm-addon-search": "^0.9.0",

### Steps to reproduce

https://github.com/alanhg/express-demo/blob/ac0fcb907de30ab0de885cb118355a17c7061d06/static/js/search-addon-bar.js#L25-L25

**Comment by Tyriar** [comment]
This should be fixed in the latest beta, you may also have an outdated xterm.css?

Here's what the demo shows:

![image](https://user-images.githubusercontent.com/2193314/180213484-2efeef8c-aec4-4e9b-984e-6ec3baf85054.png)

**Comment by alanhg** [comment]
> This should be fixed in the latest beta, you may also have an outdated xterm.css?
> 
> Here's what the demo shows:
> 
> ![image](https://user-images.githubusercontent.com/2193314/180213484-2efeef8c-aec4-4e9b-984e-6ec3baf85054.png)

ok ,my fault, my css is not latest...


fixed.... 


thank you.
