### ISSUE TITLE
Search highlights don't work in the alt buffer

### ISSUE THREAD

**Issue by alanhg** [xtermjs/xterm.js#3918]
run vi command
<img width="926" alt="image" src="https://user-images.githubusercontent.com/9245110/180428391-9d6ce078-8af6-44fb-a89e-d50e6efd5583.png">

run cat  command
<img width="926" alt="image" src="https://user-images.githubusercontent.com/9245110/180428436-059294ca-173d-4001-b378-d644cc6dd719.png">

hightlight nor work in vi mode

## Details
- Browser and browser version:  Chrome v103.0.5060.134
- OS version: Big Sur 11.6.7
- xterm.js version:  v4.19.0
   xterm-addon-search v0.10.0-beta.3

**Comment by Tyriar** [comment]
Was an oversight to not do the decorations in the alt buffer as well, thanks for reporting.
