### ISSUE TITLE
Xterm loading blank section in Vue 3 prod build.

### ISSUE THREAD

**Issue by Xinecraft** [xtermjs/xterm.js#3955]
When building Xterm with VueJS 3(Laravel + Vite) getting some weird behavior that I was not getting on Vue 2.

Currently, till I use dev (Vite) all runs fine. 
But when I build the project for prod using vite build (it export with chunking), things break with a blank section as shown in the screenshot.

![image](https://user-images.githubusercontent.com/3089863/181582064-34a2755b-40fb-45b7-80cf-3c4d8a60e0ff.png)

This happens only in prod build and only if I open the xterm page the second time without a full reload. (the first visit works fine).

Code sample:
```js
<template>
<div id='terminal'></div>
</template>

<script>
export default {
	props: {
        server: Object,
        serverAggrData: Object,
        serverConsoleLogs: Array
    },
    mounted() {
        const theme = {
            background: '#111827',
            cursor: 'transparent',
            black: 'rgb(19, 26, 32)',
            red: '#E54B4B',
            green: '#9ECE58',
            yellow: '#ddcf31',
            blue: '#396FE2',
            magenta: '#BB80B3',
            cyan: '#2DDAFD',
            white: '#d0d0d0',
            brightBlack: 'rgba(255, 255, 255, 0.2)',
            brightRed: '#FF5370',
            brightGreen: '#31ab14',
            brightYellow: '#FFCB6B',
            brightBlue: '#82AAFF',
            brightMagenta: '#C792EA',
            brightCyan: '#89DDFF',
            brightWhite: '#ffffff',
            selection: '#FAF089',
        };

        const terminalProps = {
            disableStdin: true,
            cursorStyle: 'underline',
            fontSize: 12,
            fontFamily: 'Menlo, Monaco, Consolas, monospace',
            rows: 30,
            theme: theme
        };

        const term = new Terminal(terminalProps);
        const fitAddon = new FitAddon();
        term.loadAddon(fitAddon);
        term.loadAddon(new WebLinksAddon());

        term.open(document.getElementById('terminal'));

        fitAddon.fit();
        this.refitTerminal = debounce(() => {
            fitAddon.fit();
        }, 100);
        addEventListener('resize', this.refitTerminal);

        for (let line of this.consolelogs) {
            term.writeln(line.data);
        }

        Echo.private('consolelogs.' + this.server.id).listen('ServerConsolelogCreated', data => {
            this.consolelogs.unshift(data.data);
            term.writeln(data.data.data);
        });
    },

    unmounted() {
        Echo.leave(`consolelogs.${this.server.id}`);
        removeEventListener('resize', this.refitTerminal);
    },

}
</script>

<style src="xterm/css/xterm.css"></style>
```

## Details
- Browser and browser version: Chrome Version 103.0.5060.134
- OS version: Windows 11
- xterm.js version: Tried with 4.13 & 4.19

Not able to find anything helpful regarding this, neither does Vue or Xterm throw any error.
Not sure if I am doing something wrong or if it's some bug. 
If anyone aware plz lemme know. Thanks

**Comment by Tyriar** [comment]
I don't know anything about vue/vite but I'm guessing you need to remove the element in unmounted like it gets added in:

```
 term.open(document.getElementById('terminal'));
```

**Comment by Xinecraft** [comment]
Thanks,
Yes seems to call dispose() with a workaround in unmount() fix the issue.

Here is my hacky workaround coz assigning Terminal object directly to reactive data doesn't work.

Eg, below code throws error `Could not dispose an addon that has not been loaded` :
```js
// ...
mounted() {
this.term = new Terminal(terminalProps);
}
unmounted() {
this.term.dispose();
}
```

So instead I used local variable for terminal and at end of mount assigned it to the reactive variable and then used it in unmount which seems to work.
```js
mounted() {
const tmpTerm = new Terminal(terminalProps);

this.term = tmpTerm
}
unmounted() {
this.term.dispose()
}
```
