### ISSUE TITLE
Persistent background peeking through certain text

### ISSUE THREAD

**Issue by npezza93** [xtermjs/xterm.js#3970]
Seems as though on v5 some text has a different background that isn't present in v4 and persists through selection. 

## Details
- Browser and browser version: electron 19
- OS version: macos monterey
- xterm.js version: v5 beta

### Steps to reproduce

I've so far only noticed this when yarning so im not sure if v4 was just displaying text incorrectly all along and a bug got fixed. 
v4:

https://user-images.githubusercontent.com/5059927/181918983-0b267e65-eb18-45d0-9324-735a191372a3.mov

v5:

https://user-images.githubusercontent.com/5059927/181919012-dd382bdc-e951-4c38-b34f-10a6003e81df.mov

**Comment by Tyriar** [comment]
@npezza93 do you know what's causing this background color?

![image](https://user-images.githubusercontent.com/2193314/181919375-04184ccc-d0f5-4299-a415-9535d6903a1d.png)

Turning on logLevel = 'debug' will let you see the sequence.

Also does this happen on all renderers?

**Comment by npezza93** [comment]
> Also does this happen on all renderers?

Looks like just webgl. Canvas is fine

**Comment by npezza93** [comment]
Heres the debug log:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/5059927/181919503-685af53d-ed98-4fb1-a857-5f2c3db1c7bf.png">

**Comment by Tyriar** [comment]
Hmm, I think devtools parsing and hiding the styling sequence I care about. Can you enable the dom renderer and inspect one of the problem cells instead?

**Comment by npezza93** [comment]
@Tyriar I'm gonna guessing something to do with: https://github.com/xtermjs/xterm.js/pull/3932

<img width="642" alt="image" src="https://user-images.githubusercontent.com/5059927/181919734-6067a0e4-4397-4dac-9986-11dae58f6e03.png">

**Comment by Tyriar** [comment]
Thanks, I think I know what's going on

**Comment by npezza93** [comment]
Still seeing the different background on the lastest master:
Canvas(correct):
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5059927/182029806-171cfec5-e812-4252-9cf1-42b8283e6d65.png">
Webgl:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5059927/182029824-4c175963-adf8-4394-a7a5-b70851706222.png">

It does go away on selection now though.

**Comment by Tyriar** [comment]
@npezza93 is this with allow transparency enabled?

**Comment by npezza93** [comment]
@Tyriar Nope, allowTransparency is false

**Comment by Tyriar** [comment]
@npezza93 hm, what theme are you using? I don't think I saw this when I fixed the selection problem yesterday

**Comment by npezza93** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/5059927/182041251-b3cb55fa-feaa-4107-bc6e-32babe6322e0.png">

Copy pastable json string version:
```
'{"fontFamily":"JetBrainsMono Nerd Font Mono","fontSize":15,"fontWeight":"normal","cursorStyle":"block","cursorBlink":true,"scrollback":4000,"macOptionIsMeta":true,"hideContextMenu":true,"rightClickSelectsWord":true,"macOptionClickForcesSelection":true,"theme":{"green":"rgb(171, 233, 179)","brightGreen":"rgb(171, 233, 179)","black":"rgb(110, 108, 126)","brightBlack":"rgb(152, 139, 162)","red":"rgb(242, 143, 173)","brightRed":"rgb(242, 143, 173)","yellow":"rgb(250, 227, 176)","brightYellow":"rgb(250, 227, 176)","blue":"rgb(150, 205, 251)","brightBlue":"rgb(150, 205, 251)","magenta":"rgb(245, 194, 231)","brightMagenta":"rgb(245, 194, 231)","cyan":"rgb(137, 220, 235)","brightCyan":"rgb(137, 220, 235)","white":"rgb(217, 224, 238)","brightWhite":"rgb(217, 224, 238)","cursor":"rgb(248, 189, 150)","cursorAccent":"rgb(30, 29, 47)","foreground":"rgb(217, 224, 238)","background":"rgb(30, 29, 47)","selectionBackground":"rgba(217, 224, 238, 0.2)"},"allowTransparency":false,"cursorWidth":2,"fontWeightBold":"bold","lineHeight":1,"letterSpacing":"0","tabStopWidth":8,"allowProposedApi":true,"logLevel":"debug"}'
```

**Comment by Tyriar** [comment]
Can repro 👍 

```js
term.options.theme = {"green":"rgb(171, 233, 179)","brightGreen":"rgb(171, 233, 179)","black":"rgb(110, 108, 126)","brightBlack":"rgb(152, 139, 162)","red":"rgb(242, 143, 173)","brightRed":"rgb(242, 143, 173)","yellow":"rgb(250, 227, 176)","brightYellow":"rgb(250, 227, 176)","blue":"rgb(150, 205, 251)","brightBlue":"rgb(150, 205, 251)","magenta":"rgb(245, 194, 231)","brightMagenta":"rgb(245, 194, 231)","cyan":"rgb(137, 220, 235)","brightCyan":"rgb(137, 220, 235)","white":"rgb(217, 224, 238)","brightWhite":"rgb(217, 224, 238)","cursor":"rgb(248, 189, 150)","cursorAccent":"rgb(30, 29, 47)","foreground":"rgb(217, 224, 238)","background":"rgb(30, 29, 47)","selectionBackground":"rgba(217, 224, 238, 0.2)"}
```

Then in terminal:

```sh
echo -e '\x1b[2mdim text\x1b[0m'
```
