### ISSUE TITLE
Underline color no longer matches text color

### ISSUE THREAD

**Issue by npezza93** [xtermjs/xterm.js#3971]
If you look at `Brewfile` below, in v4, the underline matches the text color but in v5 it's always white. This is happening in both the canvas and webgl renderer. 

The webgl renderer is also seems to be drawing the underlines at double the thickness as the canvas renderer and thicker than v4. 

v4 is the top part, v5 is the bottom

<img width="643" alt="image" src="https://user-images.githubusercontent.com/5059927/181923547-c7a761eb-4d53-4d09-90d6-f1788b318b50.png">

## Details
- Browser and browser version: electron 19
- OS version: macos monterey
- xterm.js version: v5

### Steps to reproduce

1. Echo underlined text with a different text color

**Comment by Tyriar** [comment]
Minimal repro: `echo -e '\x1b[4;31munderlined\x1b[0m'`

**Comment by Tyriar** [comment]
Minimal repro: `echo -e '\x1b[4;31munderlined\x1b[0m'`
