### ISSUE TITLE
WebGL renders text thicker than the canvas renderer

### ISSUE THREAD

**Issue by npezza93** [xtermjs/xterm.js#3993]
Webgl:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/5059927/182156564-0736e6ca-e784-47f3-ae0d-edfdc7d8371b.png">

Canvas:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/5059927/182156627-e80c042d-a4b6-473a-accc-60da6c87d652.png">

## Details
- Browser and browser version:  electrons 19
- OS version: macOS Monterey
- xterm.js version: v5

### Steps to reproduce

1.  echo text in both renderers and compare

**Comment by npezza93** [comment]
I think this may be specific to electron, I'm not seeing this same behavior in the demo inside chrome and Firefox.

**Comment by npezza93** [comment]
Ah ha, this isn't just in electron. Repro steps:

Add 
```
body {
    -webkit-font-smoothing: antialiased;
}
``` to your style sheet.

**Comment by Tyriar** [comment]
I guess this is just browser behavior, I can't reproduce in VS Code I guess because it doesn't have the CSS rule? I wouldn't expect font-smoothing to do anything after the fix for https://github.com/xtermjs/xterm.js/issues/2662 though
