### ISSUE TITLE
Executing a command doesn't work with zsh

### ISSUE THREAD

**Issue by wuestkamp** [xtermjs/xterm.js#3994]
Executing a command doesn't work with `zsh`.
In `zsh` a new line is added to the command line, but it's not executed. A manual press of Enter is necessary to execute.

## Details
- Browser and browser version: Chrome 103
- OS version: Ubuntu 20.04
- xterm.js version: 4.19.0 (what is shipped with ttyd 1.6.3)

### Steps to reproduce
Executing a command seems to only work with bash, not zsh:

```
window.term.paste('ls\n'); # bash only
window.term.paste('ls\r\n'); # bash only
window.term.paste('ls\r'); # bash only
window.term.write('ls\n'); # neither works
window.term.write('ls\r\n'); # neither works
window.term.write('ls\r'); # neither works
```

Any idea how this can be achieved with any shell?

**Comment by Tyriar** [comment]
Pasting works a little different to a regular write in that it wraps the text in bracketed paste mode sequences so that it treats everything as a single input and does not execute it. To execute it you need to write enter after pasting

**Comment by wuestkamp** [comment]
Write doesn't work either as written above. Not sure if I do something wrong though.
`window.term.write('ls\r');` doesn't work in bash nor zsh which is why I used paste

**Comment by Tyriar** [comment]
@wuestkamp you're writing to the terminal there, you want to write to the pty (whatever you hooked `onData` up to)

**Comment by Jeremy-Boyle** [comment]
@wuestkamp What was the solution for this?

I am also having this issue, bash works for me but not zsh

**Comment by wuestkamp** [comment]
Found no solution yet. Will try this once I find the time:
https://github.com/tsl0922/ttyd/issues/620#issuecomment-789693717

**Comment by jerch** [comment]
@wuestkamp Well thats a very laborious solution (more like an anti pattern).

What you are looking for, is to write to the datasink you are also forwarding `term.onData(write_to_datasink)` too. You just need to do `write_to_datasink('ls\r')`, should work with all shell types.

**Comment by Jeremy-Boyle** [comment]
@wuestkamp https://github.com/tsl0922/ttyd/issues/620#issuecomment-789693717

Works for zsh

**Comment by jerch** [comment]
@Jeremy-Boyle 

> What you are looking for, is to write to the datasink you are also forwarding `term.onData(write_to_datasink)` too. You just need to do `write_to_datasink('ls\r')`, should work with all shell types.

Just call your onData function with the command you want and your done. No need for term.paste or additional keyboard libs on top.
