### ISSUE TITLE
use xterm-addon-attach Problem

### ISSUE THREAD

**Issue by linwenfeng122** [xtermjs/xterm.js#4011]
## Details
- Browser and browser version: 
-  Google
- xterm.js version: 
 "xterm": "^4.19.0",
    "xterm-addon-attach": "^0.6.0",
    "xterm-addon-fit": "^0.5.0"
### Steps to reproduce

When using the English input method, I will enter every character. How to realize that the Enter key will be responded only after I have typed multiple characters

**Comment by jerch** [comment]
`onData` contains what was typed on the keyboard, thus you can easily filter on `\r` positions in its data (`\r` is what <kbd>Enter</kbd> generates). But doing that sounds very wrong to me and is most likely not what you want. Maybe try to rephrase your issue with <kbd>Enter</kbd>.
