### ISSUE TITLE
Give an option for Xterm.js to include a exit command.

### ISSUE THREAD

**Issue by superlopez-real** [xtermjs/xterm.js#4012]
Give an option for Xterm.js to include a exit command that we can process using a event listener, because i have my own terminal application made using Electron, and i want to exit the process when the user types exit.

**Comment by Tyriar** [comment]
It sounds like this is out of the scope of xterm.js, normally it's the process that handles exit

**Comment by superlopez-real** [comment]
> 

Can you give me some sort of example? I can't find a command like term.read.

**Comment by Tyriar** [comment]
All xterm.js does is writes what it's told to (`write`) and sends out serialized keystrokes (`onData`). You might be talking about https://github.com/microsoft/node-pty, but if you run `exit` in most shells it will already exit so I'm not sure what your situation is.

**Comment by superlopez-real** [comment]
my situation is that it doesn't exit, the terminal does nothing, but i will look into it!
