### ISSUE TITLE
How should I get the text of the line where the cursor is?

### ISSUE THREAD

**Issue by TheBlindM** [xtermjs/xterm.js#4013]
![image](https://user-images.githubusercontent.com/48701152/184845078-cf77cef2-09e1-421e-a689-25c116a496b8.png)

**Comment by Tyriar** [comment]
You can use the buffer API for that:

https://github.com/xtermjs/xterm.js/blob/7e6282e9c2a902096c97fcfd1f67f290cfed12c2/typings/xterm.d.ts#L669-L672
