### ISSUE TITLE
xterm.js mirrors itself on other electron windows

### ISSUE THREAD

**Issue by superlopez-real** [xtermjs/xterm.js#4014]
## Details
- Browser and browser version: Electron 18.3.5
- OS version: macOS 13.0
- xterm.js version: 4.18.0

I don't think it is electron's fault, because normally every letter would be double, which i managed to fix by putting every browserWindow in a let variable.

When having multiple windows in Electron, inputting something in xterm.js just mirrors on other windows, what causes the issue?
Check video below, because this is hard to explain

https://user-images.githubusercontent.com/90651091/185099191-03f57f74-6c9c-4d72-821e-54807993b15a.mov

.

**Comment by superlopez-real** [comment]
It might be an issue with pty itself, if it is that, please tell me.

**Comment by Tyriar** [comment]
You're likely connecting both windows to the same pty, so the input gets sent to the pty and the output/instructions get sent to both xterm.js instances. Either that or an issue with your IPC.

**Comment by FormalSnake** [comment]
> You're likely connecting both windows to the same pty, so the input gets sent to the pty and the output/instructions get sent to both xterm.js instances. Either that or an issue with your IPC.

I think i am connecting both windows to the same pty instances, but how would one make a new pty process spawn every time a window opens?

**Comment by Tyriar** [comment]
@FormalSnake this is more of a general electron IPC question than something related to xterm.js
