### ISSUE TITLE
Inserting X selections requires precise mouse positioning

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4052]
VS Code issue: https://github.com/microsoft/vscode/issues/157233

TLDR, we're probably canceling the middle mouse click event when clicking on text such that the selection clipboard only pastes when middle clicking whitespace

**Comment by dmke** [comment]
When running the demo (both master (b68f8207) and v5 (c55075b6)) in the dev container, in VS Code's Simple Browser, I can't reproduce this issue.

Here I'm using only the left and middle mouse button, and the terminal behaves as expected:

https://user-images.githubusercontent.com/327411/186504866-4a94aa2c-95d2-43ca-9237-a0b0857dc1e9.mp4

**Comment by Tyriar** [comment]
Seems to be a vscode-side issue, thanks
