### ISSUE TITLE
Underline with canvas uses less spacing

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4058]
VS Code issue: https://github.com/microsoft/vscode/issues/158874

- set setting `terminal.integrated.gpuAcceleration: canvas`
- in a terminal type
```
echo -e "\x1b[4:3m"  # curly underline
echo -e "\x1b[4:4m"  # dotted underline
echo -e "\x1b[4:5m"  # dashed underline
```

<img width="594" alt="Screenshot 2022-08-23 at 12 18 35" src="https://user-images.githubusercontent.com/6461412/186134108-84eceeb8-2ce3-4bbd-856b-ac958f59adc7.png">

- set setting `terminal.integrated.gpuAcceleration: on`
<img width="549" alt="Screenshot 2022-08-23 at 12 21 56" src="https://user-images.githubusercontent.com/6461412/186134697-06507ccd-7383-4d8a-aa20-ad7a94e48ec7.png">

Note that the spacing of the underline differs: with canvas it is a bit too close to the text

**Comment by Tyriar** [comment]
Here's a reference for how Word renders 12, 24, 36 and 48px Calibri:

![image](https://user-images.githubusercontent.com/2193314/188165090-7d80bfa1-c374-4ecb-812e-800c8292d4a3.png)

**Comment by jerch** [comment]
@Tyriar Is there a middle ground possible? Its just a gut feeling, but kinda both seem slightly off to me - like canvas is too close and webgl too far?

On a sidenote: In typography there are some support lines how far glyphs should run (found with a quick search: https://material.io/design/typography/understanding-typography.html#type-properties) - maybe there is also an official way how to do it for different underline styles (not mentioned in the link)?

**Comment by Tyriar** [comment]
@jerch I had a bit of a WIP this morning for this where I get the alphabetical text baseline and push it down 1-2 css pixels which looked good, I think that's the approach we should take for the upper cap of the underline
