### ISSUE TITLE
Underline is not continuous

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4059]
VS Code issue: https://github.com/microsoft/vscode/issues/158868

- set setting terminal.integrated.gpuAcceleration: on
- in a terminal type: `echo -e "\x1b[4:2m"  # double underline` followed by `echo -e "\x1b[4:3m"  # curly underline` and a new line

![image](https://user-images.githubusercontent.com/6461412/186127623-de5f87fb-9463-49cc-9606-a97e55595c00.png)

Especially under the `w` there's a lot of space so I would say it can't be antialiasing that interferes

---

I wonder if we should reduce the stroke width here, or potentially do something more manual when drawing the lines to ensure only characters that need it get this treatment?

**Comment by TylerLeonhardt-alt** [comment]
`v` has the same issue as `w`

**Comment by TylerLeonhardt-alt** [comment]
![image](https://user-images.githubusercontent.com/98423974/186259441-751b2dcd-3273-4bde-9114-1c67d4e424b7.png)

Wanted to call out the others. Some make sense like `@`, `$`, `{}`, `|`, `;`. The suspicious ones, I think, are: `()`, `_`, `[]`, `/` and `\`.

**Comment by Tyriar** [comment]
I'm thinking of only doing the outline handling if the glyph has any pixels set on the underline's top row of pixels, I think that should fix those cases
