### ISSUE TITLE
Webgl cache warming up can cause GC/slow app start up

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4103]
![image](https://user-images.githubusercontent.com/2193314/188679544-2f981938-6044-442f-a6cf-71780f3ff910.png)

**Comment by jerch** [comment]
Would it be possible to move some of the work to idle times with `requestIdleCallback()`?

**Comment by Tyriar** [comment]
@jerch great idea 👍! This is just warming up to avoid latency when rendering _likely_ glyphs in the future so it can be deferred until after the initial render which would then only draw the minimal amount of glyphs in the viewport.

**Comment by Tyriar** [comment]
This is pretty much fixed in https://github.com/xtermjs/xterm.js/pull/4131
