### ISSUE TITLE
Showing the cursor for headless browser

### ISSUE THREAD

**Issue by faressoft** [xtermjs/xterm.js#4104]
I'm the author of [Terminalizer](https://github.com/faressoft/terminalizer) and [terminalizer-player](https://github.com/faressoft/terminalizer-player) which depends on xterm.js.

I'm using [Electron](https://www.electronjs.org/) to render the recordings and take screenshots of the page to generate animated GIF images later.

I noticed that when the app is running in headless mode there is no cursor but when I run it normally (no headless mode) I see the cursor.

Headless:
![Headless](https://user-images.githubusercontent.com/1908658/188736932-2f2c1cdc-a14e-41d2-91ae-c7671308c2ef.png)

NonHeadless:
![UI](https://user-images.githubusercontent.com/1908658/188736988-174111be-38eb-4c6a-a92c-76ec0e3ac899.png)

Is there a way to fix this for headless?

**Comment by Tyriar** [comment]
The cursor won't display until you focus it, I'm guessing that's what's causing the problem?

**Comment by faressoft** [comment]
Yes I believe so. Is there a way to always show the cursor on it even when it is not focused?

**Comment by Tyriar** [comment]
No way other than focusing, headless browsers should be able to focus though via `Terminal.focus()`

**Comment by faressoft** [comment]
The issue is fixed with

```
await mainWindow.focusOnWebView();
```
