### ISSUE TITLE
xtermjs text overlap problem.

### ISSUE THREAD

**Issue by AlperRehaYAZGAN** [xtermjs/xterm.js#4110]
https://user-images.githubusercontent.com/43668181/189460912-f8febed0-4110-4d33-8991-0c04f4f163ca.mp4 

![xtermload](https://user-images.githubusercontent.com/43668181/189461028-22e9e5bf-7eba-40ec-b556-a4e22e830690.png)

I use xterm.js on my project with play-with-docker sdk. I use both in react application page. But xtermjs could not could not display onData event on the terminal area correctly. The texts overlap each other. I trigger fitAddon.fit() function after xtermjs div onLoad() function but I haven't solved this poblem yet. Is this problem related with xtermjs sizing problem or play-with-docker sdk. I can't understand the difference between each other. 

## Details
- Browser and browser version: Chrome
- OS version:  Mac OS Monterey 12.0.1
- xterm.js version: 4.19.0

**Comment by jerch** [comment]
Most likely you forgot to forward the resizing to the pty. The pty size must be in line with the terminal size, otherwise its line wrap calculations will be wrong (jumping early or late to the beginning of the same line).

**Comment by AlperRehaYAZGAN** [comment]
Thanks Jerch you are right.
I did some research on the issue you mentioned. The resize() and fitAddon.fit() operations performed via xterm is not sent to the shell screen in the background, and therefore the terminal screen remains at its own size. For my specific project build with [play-with-docker](https://github.com/play-with-docker/play-with-docker/blob/master/handlers/www/assets/app.js#L96), the reason is you should send new terminal sizes via websocket like this:  

![socket-resize](https://user-images.githubusercontent.com/43668181/189499996-2bf315b2-c2cd-4f0b-8803-6d26374f9fad.png)

Thank you very much 😇🚀

> Most likely you forgot to forward the resizing to the pty. The pty size must be in line with the terminal size, otherwise its line wrap calculations will be wrong (jumping early or late to the beginning of the same line).
