### ISSUE TITLE
Screen doesn't fit

### ISSUE THREAD

**Issue by UPL123** [xtermjs/xterm.js#4111]
Hi! I am using Hack Nerd Font for my terminal, and the screen doesn't fit until I resize the window. I'm using the fit addon, but it doesn't works.

(Normal)
![image](https://user-images.githubusercontent.com/84473132/189535005-228df9e3-305a-4e44-8654-65c9cbfedae3.png)

(On window resize)
![image](https://user-images.githubusercontent.com/84473132/189535045-f10c998b-30a9-4154-ac61-79d3ff13eb07.png)

**Comment by ssh-peppe** [comment]
Are you sure the font is fully loaded by the time it first gets used?

**Comment by UPL123** [comment]
Yeah, now it works. Thanks!
