### ISSUE TITLE
setter issue of options.theme

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#4124]
Took me some time to find out, why this doesnt work in the console:

```js
t = term.options.theme
t.background = '#000000'
term.options.theme = t  // no change at all
t2 = {...t}
term.options.theme = t2  // works
```

Its kinda the old mutual vs immutable issue, and I wonder if we should fix it. Possible ways to deal with it:
- some doc notes stating that the theme object has to change identity to take effect
- or do the `{...theme}` always in the setter (thus forcing the terminal to re-eval the object), imho most straight forward solution, as this is a rare action not hurting performance

**Comment by silamon** [comment]
Another solution may be to implement a concrete class with get and set functions? (Both ITerminalOptions and ITheme)

**Comment by Tyriar** [comment]
This is by design imo as you can set either `Terminal.options` or `Terminal.options['option']`, anything deeper than that would require re-writing the option given to us with getters and setters
