### ISSUE TITLE
xterm-addon-canvas does not follow the semver specification

### ISSUE THREAD

**Issue by pfdgithub** [xtermjs/xterm.js#4126]
When using `npm install --save xterm-addon-canvas` to install dependency, it uses the wrong higher version.

https://www.npmjs.com/package/xterm-addon-canvas
| Version | Published |
| -- | -- |
| 0.2.0 | 4 days ago |
| 0.12.0 | 2 months ago |

**Comment by Tyriar** [comment]
0.12.0 was accidentally published, and npm wouldn't let us delete it.

**Comment by pfdgithub** [comment]
Normally, you would redistribute version 0.2.0 with 0.13.0. 
At the very least, it should be explicitly stated in the documentation that 0.12.0 is a deprecated version.

**Comment by Tyriar** [comment]
Sounds good, I'll keep this open as a reminder to do 0.13.0 when xterm 5.1 is published

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/4860 as we're moving to `@xterm` scoped packages
