### ISSUE TITLE
DOM renderer triggers content security policy warnings about unsafe-inline styles

### ISSUE THREAD

**Issue by ssh-peppe** [xtermjs/xterm.js#4133]
With xtermjs 5.0, the canvas renderer is no longer built in. Since renderer add-ons cannot be loaded until the terminal open() call is done, it seems the DOM renderer briefly is activated before the canvas or webgl renderer takes over. And it appears that the DOM renderer creates style elements into the DOM, which is blocked by tight content security policies that don't allow unsafe-inline styles. With xtermjs 4.x since the canvas renderer was built in, this did not happen.

Note that despite the errors, things will work just fine once the webgl or canvas renderers take over.

## Details
- Browser and browser version: Chrome 105.0.5195.125 but also happens with other browsers
- OS version: macOS 12.6
- xterm.js version: 5.0.0

### Steps to reproduce

1. Using a web server that has a tight content security policy that doesn't allow unsafe-inline styles, load xtermjs into a web page
2. Observe unsafe inline style warnings in the web console

The style warnings are expected with the DOM renderer since it creates style elements to the DOM. But this is also happening when using the canvas and webgl renderers because you cannot load them before the terminal open() call.

A screenshot of the errors are attached.

<img width="1360" alt="Screen Shot 2022-09-23 at 10 44 45" src="https://user-images.githubusercontent.com/51072037/191913738-d8ac2d24-251f-4fcf-91d3-603183703bf6.png">

**Comment by Tyriar** [comment]
I think you can change the policy to allow the xterm.js script to set inlines, they're pretty critical to how the dom renderer works. If that's not an option we could maybe allow activating the renderer addon before open is called, just not create the `IRenderer` until `open`?

**Comment by Tyriar** [comment]
We should do this so that we can avoid the DOM renderer initializing on open:

<img width="992" alt="Screen Shot 2022-09-24 at 10 39 06 am" src="https://user-images.githubusercontent.com/2193314/192111463-db0c9d79-fa4a-4ba9-8479-a72f902b1179.png">

**Comment by ssh-peppe** [comment]
In our case, because we're talking about a security product (PrivX by SSH), downgrading the content security policies over this isn't really an option. And it would be up to our customers to do that in any case. In theory this is only a cosmetic issue since the warnings have no effect as we use the canvas or webgl renderers anyway. But in practice the way you can't load a renderer add-on until after open() and have the DOM renderer initialize, seems like a generally bad thing for xtermjs. So seeing this fixed in xtermjs for that reason alone sounds like a good thing.
