### ISSUE TITLE
Exception: Cannot read properties of undefined (reading 'loadCell')'

### ISSUE THREAD

**Issue by leogong99** [xtermjs/xterm.js#4136]
We notice our user experience exception of this error message:

StackTrace:
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:155330)
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:155808)
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:157868)
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:148010)
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:199552)
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:197171)
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:37312)
i (webpack://cloudshell/node_modules/xterm/lib/xterm.js:1:37028)'
NotificationMessage: 'TypeError: Cannot read properties of undefined (reading 'loadCell')'
Error: {}

## Details
-  chrome, firefox
- OS version: window
- xterm.js version: 
    "xterm": "^4.19.0",
    "xterm-addon-attach": "^0.6.0",
    "xterm-addon-fit": "^0.5.0",
    "xterm-addon-web-links": "^0.6.0"
### Steps to reproduce
We are not sure how this happened? we can see this errors in our console logs. 
It crashed at here:

![Screen Shot 2022-09-23 at 3 50 21 PM](https://user-images.githubusercontent.com/5078541/192066654-b1790f55-73e7-4f5b-9a35-af614f921c65.png)

**Comment by Tyriar** [comment]
A lot of changes have happened in this area since 4.19, the canvas renderer which that code is from is actually an addon in v5+. Could you let us know if it happens in v5?

**Comment by mqttBridge** [comment]
hi 
am using it as below but still getting undefined cell,pls help

regards


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Web Terminal with Vim Support</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/xterm/3.14.5/xterm.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/xterm@5.0.0/lib/xterm.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/xterm-addon-attach@0.9.0/lib/xterm-addon-attach.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@xterm/addon-fit@0.10.0/lib/addon-fit.min.js"></script>
  </head>
  <body>
    <div id="terminal-container" style="height: 100vh; width: 100%;overflow: hidden;"></div>

    <script>
	
	  let sessionID = ""
      // WebSocket for server communication
      const ws = new WebSocket("wss://kaazing.example.com:7096/terminal");

      // Flag to track if session is created
      let sessionCreated = false;

      // Initialize the terminal with options
      const term = new Terminal({
        cursorBlink: true,
        rows: 25,
        cols: 80,
        screenKeys: true,  // Allow screen keys (useful for keyboard interaction)
        scrollback: 1000,  // Set scrollback to 1000 lines
        viewportMargin: 150,  // Keep a margin of 10 lines at the bottom
	    fontSize: 14,  // Set the font size
        lineHeight: 1.2 // Set the line height to control vertical spacing
      });

      // Fit addon for resizing the terminal based on container size
      const fitAddon = new FitAddon.FitAddon();
      term.loadAddon(fitAddon);
	  fitAddon.activate(term);

      // Attach the terminal to the DOM
      term.open(document.getElementById("terminal-container"));
	  	  
	  function logTerminalSize() {
        const currentRows = term.rows;
        const currentCols = term.cols;
        console.log(`Terminal resized: ${currentRows} rows, ${currentCols} columns`);
      }
	  
	  //console.debug(term.css.cell.width);

      // WebSocket add-on to send/receive data
   //   const attachAddon = new AttachAddon.AttachAddon(ws, { bidirectional: true });
   //   term.loadAddon(attachAddon);

      // Fit the terminal to the container size
      //fitAddon.fit();
	  //logTerminalSize();
      //const { rows = 25, cols = 80 } = fitAddon.proposeDimensions() || {};
      
      // Resize the terminal when the window is resized
      window.addEventListener("resize", () => {
        fitAddon.fit();
		logTerminalSize();
      });
	  
	  term.onResize(() => {
        logTerminalSize();  // Log size when resize event happens inside terminal
      });

      // Call fit() after terminal is fully loaded
      setTimeout(() => {
        fitAddon.fit();
        logTerminalSize();  // Log the initial size
      }, 500);  // Delay to ensure terminal is rendered

      // Focus on the terminal after initialization
      term.focus();

      // Handle incoming WebSocket messages (e.g., from Vim or other commands)
      ws.onmessage = (event) => {
        const data = event.data;

        try {
          const jsonResponse = JSON.parse(data);
          //console.debug("received operation=,${jsonResponse.operation}" );
		  
          // Check if it's a session response
          if (jsonResponse.operation === 'createSessionRsp') {
		    //console.debug("received operation=${jsonResponse.operation} ");
            // If session creation is successful, store session ID and allow further operations
            if (jsonResponse.sessionID) {
              sessionCreated = true;
			  sessionID = jsonResponse.sessionID;
              term.write(`Session created. Session ID: ${jsonResponse.sessionID}\n`);
            } else {
              term.write('Session creation failed.\n');
            }
          } else if (jsonResponse.operation === 'shellCmdRsp') {
		         //console.debug("received operation=${jsonResponse.operation}" );
		        if (jsonResponse.sessionID === sessionID){
				//decode from base64 and write to term
				//let decoder = new TextDecoder();
				//const rawdata = decoder.decode(jsonResponse.data);
				let rawdata = atob(jsonResponse.data);
				console.debug("sending :",rawdata);
				term.write(rawdata);
				}
				else{
				
				}
		  }
		  else {
            // Handle other responses (Vim output or other messages)
            //term.write(data);
          }

        } catch (error) {
          console.error("Error parsing response:", error);
        }
      };

      // Send data to the WebSocket only after session is created
      term.onData((data) => {
        // Block operation if session is not created yet
        if (!sessionCreated) {
          term.write("Session is not created yet. Waiting for server response...\n");
          return;
        }
        //let encoder = new TextEncoder();
		//const base64Data = encoder.encode(data);
        const base64Data = btoa(data);  // Encode the inputData to Base64
        const shellCmdReq = {
          operation: "shellCmdReq",
          deviceID: "xx",  // Replace with actual deviceID
          terminalID: "xx",      // Replace with actual termID
		  sessionID: sessionID,
		  data: base64Data
        };
		console.debug("sending :",JSON.stringify(shellCmdReq));
		ws.send(JSON.stringify(shellCmdReq));
        // Send terminal data if session is valid
        //ws.send(data);
      });

      // Send the initial create session request once WebSocket is open
      ws.onopen = () => {
        const createSessionReq = {
          operation: "createSessionReq",
          deviceID: "xx",  // Replace with actual deviceID
          terminalID: "xx"      // Replace with actual termID
        };

        // Send the create session request as a JSON string
        ws.send(JSON.stringify(createSessionReq));
      };

      // Example of initial text to display in the terminal
      term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ');

      // Optional: Handle WebSocket errors
      ws.onerror = (error) => {
        console.error("WebSocket Error: ", error);
      };

      // Optional: Handle WebSocket close
      ws.onclose = (event) => {
        console.log("WebSocket closed:", event);
        term.write("\nConnection closed.\n");
      };
    </script>
  </body>
</html>
