### ISSUE TITLE
SerializeAsHTML() does not work with xterm-headless - TerminalCore lacks _colorManager

### ISSUE THREAD

**Issue by gpickell** [xtermjs/xterm.js#4148]
I tried to use the Terminal from xterm-headless with the xterm-addon-serialize addon. I managed to get it to work after I hacked in a property. See the following code fragment:
```
import xterm from "xterm-headless";
import { SerializeAddon } from "xterm-addon-serialize";

const term = new xterm.Terminal({
    allowProposedApi: true,
});

const ser = new SerializeAddon();

// HACK: Make it work (omit to demonstrate error)
term._core._colorManager = {
    colors: {
        ansi: {
            1: {
                css: "blue",
            }
        }
    }
};

term.loadAddon(ser);
term.write("Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ");
term.write("", () => {
    // this will throw without the hack
    console.log(ser.serializeAsHTML({
        includeGlobalBackground: true
    }));
});
```

The ColorManager should get moved to common or this addon package should bundle a copy of it and use it only if there is no _colorManager.

**Comment by Tyriar** [comment]
I'm not surprised this doesn't work, the reason `ColorManager` lives in browser is because color doesn't need to be displayed to the user in the headless version. What's your use case for this?

**Comment by gpickell** [comment]
Pre-rendered CLI tool output presentation as simple HTML. There may be other ways to accomplish this, but xtermjs is the best for handling problems in this area it seems?

**Comment by Tyriar** [comment]
I don't think we should move `ColorManager` to common such that it would be included in xterm-headless since nothing in that package uses it. However we could adapt the serialize addon to support not having a color manager. So changing this:

https://github.com/xtermjs/xterm.js/blob/318abe641bcc499d62c2c741cf82fe72ae4dde85/addons/xterm-addon-serialize/src/SerializeAddon.ts#L546-L547

To include a list of colors like this generates:

https://github.com/xtermjs/xterm.js/blob/318abe641bcc499d62c2c741cf82fe72ae4dde85/src/browser/ColorManager.ts#L30-L76

**Comment by silamon** [comment]
If terminal.options.theme is filled in in headless mode, we can use that.

**Comment by Tyriar** [comment]
@silamon I think that's initialized to `{}` by default? 

https://github.com/xtermjs/xterm.js/blob/37c722d556e4b7e15ef55b63da41a93f87ddd43c/src/common/services/OptionsService.ts#L40

But even if it had more of the colors, I don't think it would have `extendedAnsi` which is important for serializing to HTML.

**Comment by jerch** [comment]
Maybe the html output of the serialize addon should emit color slots as css classes? This way a theme can be applied to it from a css file defining those colors (except RGB, which can always be derived from CellData).

Note - I have not looked at the serialize code, thus idk what it needs the color manager for.

**Comment by Tyriar** [comment]
@jerch i think a common use case would be to put the html into the clipboard and allow pasting into a word doc or something that supports rich text (vscode does this). Going class based wouldn't work as then it's not self contained.

**Comment by jerch** [comment]
Well if thats an issue, how about an style argument to `serailizeAsHtml` containing the colors? Then the code can inline them.

**Comment by Tyriar** [comment]
This had to get reverted for v5.1 as we can't package implementation from core in the serialize addon yet.
