### ISSUE TITLE
xterm-addon-ligatures webpack@package.json

### ISSUE THREAD

**Issue by adrenochrome25** [xtermjs/xterm.js#4174]
while trying to build, i had troubles packaging ligatures addon : i had a broken webpack global installation, while trying to fix it, i learnt webpack global installation should not even exists because webpack should be project dependent to avoid locked down incompatible versions (i'm really noob with nodejs).
so i suggest this fix :
xterm-addon-ligatures, package.json, line 20, webpack should point to xtermjs local version (as it's the case with all other addons) instead of a system-wide version 
`    "package": "webpack",`
->
`    "package": "../../node_modules/.bin/webpack",`

**Comment by Tyriar** [comment]
It currently is designed to run from the main folder via the `./bin/publish.js` script. Changing it to your proposal unfortunately causes this to then fail on Windows. I couldn't find a way to get the best of both worlds, without installing webpack in the addon folders as well which makes dependency install slower.
