### ISSUE TITLE
Utf8ToUtf32 decoder full codepoint test can timeout in CI

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4178]
https://dev.azure.com/xtermjs/xterm.js/_build/results?buildId=5879&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5852bf5a-5a02-52f3-bee8-4fdc90cda9d0

```
  1) text encodings
       Utf8ToUtf32 decoder
         full codepoint test
           0..65535 (1/2/3 byte sequences):
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/out/common/input/TextDecoder.test.js)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by jerch** [comment]
Well its actually a full range test for proper utf8-->utf32 conversion. No clue how to make it faster, maybe split in smaller parts? Note that timeout in azure basically means, that the test server are very packed with work (the test is only CPU bound). We can also skip the test unless someone does changes to the unit?

**Comment by Tyriar** [comment]
I'm splitting it into 10000 chunks atm which gets makes none of them warn about time, pr in a sec
