### ISSUE TITLE
context menu does not offer paste in Firefox-on-Windows

### ISSUE THREAD

**Issue by risacher** [xtermjs/xterm.js#418]
The right-click context menu does not offer 'paste' as an option when using Firefox 50.0, FirefoxPortable 50.0.2, and FirefoxPortable 50.1.0 on Windows 8.1.  Pasting works when the paste option is selected from the Firefox menu.

## Details
- Browser and browser version:  Firefox 50.0 and FirefoxPortable 50.0.2 and 50.1.0
- OS version:  Win 8.1
- xterm.js version:  github as of 2016-12-16

### Not affected: 
 - Firefox Nightly, Google Chrome, and Safari on OS X (El Capitan) 
 - Firefox 50.1.0 on Linux
 - Google Chrome on Win 8.1 
 - Internet Explorer 11 on Win 8.1 has a paste option, but it doesn't work. (Different problem)

### Steps to reproduce

1. Open an xterm.js Terminal in Firefox on Windows 
2. Select some text with the mouse
3. Right click and select 'Copy'
4. Right click again to bring up context menu; observe that there is no "Paste" option.

**Comment by parisk** [comment]
Thanks for reporting this @risacher. Will take a look and post updates here.

Does this happen in the demo or in your consumer application? If the case is the latter there are a few chances it happens because one of the terminal's ancestors are using CSS transforms.

**Comment by Oliboy50** [comment]
Same issue on Windows 10.

Any news about this? 

And not only the context menu, I just don't have any clue about how to paste in Firefox on Windows... :(

**Comment by parisk** [comment]
@Oliboy50 I will try to get on top of this as soon as possible.

Are you aware if the host application of xterm.js that you are using, is using CSS transforms on xterm.js or any of it's parent elements?

**Comment by risacher** [comment]
@parisk you can poke at a live version of my app at https://risacher.org/ttyx/ , the code for which is https://github.com/risacher/ttyx.  You shouldn't be able to log in, but you can test the terminal paste function without logging into the server.

In my case the only css that's loaded is xterm.css from xterm.js itself and https://risacher.org/ttyx/style.css, which is derived from chjj's tty.js style.css.  

I dunno about the demo app;  I'll try to check that.

**Comment by risacher** [comment]
I just confirmed that the same thing happens in the demo app.

**Comment by risacher** [comment]
@Oliboy50 I can paste in Firefox-on-Windows by selecting "paste" in the dropdown menu, which opens when I click on a symbol in the upper right of the browser window that looks like three horizontal bars.  

Admittedly, I struggled for many months before I noticed that cut-copy-paste were in that menu, and it still seems strange to me that paste might work from there when it doesn't appear in the context menu.

**Comment by ansiz** [comment]
@parisk Yes, can't show copy or paste context menus if CSS transforms is using on xterm.js or any parent elements. Thx!

**Comment by ansiz** [comment]
@parisk but I still do not understand why CSS transforms will lead to such a problem, could you explain it? Thanks very much!

**Comment by parisk** [comment]
@ansiz CSS transforms are messing with absolute positioning of elements, which is used to provide the clipboard menu.

**Comment by sitzmar** [comment]
I'm running into this in v3.0.2 using Firefox 58 on Windows 10. The same version of Firefox on MacOS is not affected.

I looked into the CSS transform suggestion, but got the same behavior even with everything other than the xterm js/css stripped out. Any other suggestions or troubleshooting I could try?

**Comment by parisk** [comment]
Thanks for the additional information! I have no additional suggestions @sitzmar neither the time to work around this issue.

I added the "Help wanted" tag in order to encourage people take a shot at solving this, if they can. I am happy to review a PR.

**Comment by sitzmar** [comment]
I think I got to the bottom it. In the clipboard handler, the textarea element gets modified to be under the mouse cursor, and and then very quickly reset with a `setTimeout` method.

The current code has that timeout at `4ms`, which appears to be too fast. On my system, the lowest value that worked consistently was `135ms`. But it seems possible that the minimum could vary based on system performance. Not sure if there are other implications to increasing this value, but setting it to 200 or 300ms might be a safe bet.

Happy to submit a PR if that sounds reasonable.

**Comment by parisk** [comment]
@sitzmar please feel free to do so (also please add a code comment there to explain the reasoning behind the timing).

I can test on a few different systems and browsers to see if this will make the cut.

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/1253
