### ISSUE TITLE
_clipImageData is GC expensive

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4197]
Part of https://github.com/microsoft/vscode/issues/161622

During vscode startup:

<img width="262" alt="Screen Shot 2022-10-11 at 9 18 05 am" src="https://user-images.githubusercontent.com/2193314/195145938-f65f7b1d-0194-4160-b8a8-d01b643a8b9c.png">

**Comment by Tyriar** [comment]
Actually this might be an issue with the whole draw to cache call, closing for not until I understand the problem better and whether it's worth fixing.

**Comment by jerch** [comment]
Looking at the code of that function, I think you can spare the new Uint8ClampedArray there by directly creating the ImageDate and writing to its `.data`? Would atleast lower the gc pressure somewhat.

The bytes also could be transferred as uint32, would make the function somewhat faster.

**Comment by Tyriar** [comment]
Great idea, then it's just a new typed array view on the same buffer until we eventually throw it away after it gets drawn to the canvas!
