### ISSUE TITLE
The content disorder when use up or down key of keyboard to switch history commands

### ISSUE THREAD

**Issue by NeroSolomon** [xtermjs/xterm.js#4202]
## Details
- Browser and browser version: 106.0.5249.119
- OS version: macOS Big Sur
- xterm.js version: 4.3.0

### Steps to reproduce

1. Link a machine
2. Resize the window
3. Use up or down key to switch history commands
4. When the command is too long to on the same line, and click the key to switch again，then the previous command will stay，the next command will be disordered
![image](https://user-images.githubusercontent.com/28894970/195798815-ebbadd67-3251-49bd-b868-d2a64812ecb5.png)
The previous command actually is `ssh localhost -p 2222`, the next command actually is `ssh -vvv 'admin:wjw@localhost' -p 2222`

I suspect this is backend problem, but i console the bianry message when reproduce the problem and it looks the same as normal

when reproduce the problem:
```
00000000: 0808 0808 0808 0808 0808 0808 0808 0808  ................
00000001: 081b 5b31 3740 2d76 7676 2027 6164 6d69  ..[17@-vvv 'admi
00000002: 6e3a 776a 7740 6c6f 6361 6c68 6f73 7427  n:wjw@localhost'
00000003: 1b5b 431b 5b43 1b5b 431b 5b43 1b5b 431b  .[C.[C.[C.[C.[C.
00000004: 5b43 1b5b 431b 5b43                      [C.[C.[C
```

the normal bianry message:
```
00000000: 0808 0808 0808 0808 0808 0808 0808 0808  ................
00000001: 081b 5b31 3740 2d76 7676 2027 6164 6d69  ..[17@-vvv 'admi
00000002: 6e3a 776a 7740 6c6f 6361 6c68 6f73 7427  n:wjw@localhost'
00000003: 1b5b 431b 5b43 1b5b 431b 5b43 1b5b 431b  .[C.[C.[C.[C.[C.
00000004: 5b43 1b5b 431b 5b43                      [C.[C.[C
```

Hope to get help

**Comment by Tyriar** [comment]
What shell is this? And does it happen in the default Terminal.app?

**Comment by NeroSolomon** [comment]
> What shell is this? And does it happen in the default Terminal.app?

The shell is bash and it doesn't happen in the default Terminal.app

**Comment by jerch** [comment]
@NeroSolomon Whats the TERM var in both shells?

**Comment by NeroSolomon** [comment]
@jerch Hi. Is that what you mean？
![image](https://user-images.githubusercontent.com/28894970/196164355-614a7e12-4e80-45f3-bd99-35d753164a8f.png)

**Comment by jerch** [comment]
Yes, maybe try setting it to `xterm-256color`.

**Comment by NeroSolomon** [comment]
@jerch Thanks for helping, but i doesn't work.
![image](https://user-images.githubusercontent.com/28894970/196323125-f8af2eeb-5e46-4e9a-a03d-24493da95148.png)

Maybe i can try upgrade xtermjs version?

**Comment by NeroSolomon** [comment]
I upgrade xtermjs version to v5.0.0, but it still has this problem. What's more, when i make the size wider, it gets weirder.

For example:

The initial width is 1200px
![image](https://user-images.githubusercontent.com/28894970/196328752-6c33a4cf-0d79-4a72-aedf-0401e9802b43.png)

Then i change the size to 1600px
![image](https://user-images.githubusercontent.com/28894970/196328864-758fb5eb-830c-418b-b61f-617bbf75c5cf.png)

It seems ok, but when i click up or down key
![image](https://user-images.githubusercontent.com/28894970/196328950-2408269d-0455-4089-bae3-227a0f5ceb93.png)
![image](https://user-images.githubusercontent.com/28894970/196328987-f3a39958-9444-49f3-9fa4-22d474483548.png)
![image](https://user-images.githubusercontent.com/28894970/196329037-e7fa9338-399f-4c2f-8db4-61b1cadc622b.png)

The previous content will be eaten.😖

**Comment by jerch** [comment]
Is the PTY correctly resized from terminal size changes?

**Comment by NeroSolomon** [comment]
> Is the PTY correctly resized from terminal size changes?

Yes, the frontend will send cols and rows to backend when resize the window，and the backend will resize pty

**Comment by jerch** [comment]
Does this always happen, or only after some CJK chars were printed? Whats the system encoding of the app side (I'd guess utf8, otherwise the CJK chars would have be scrambled)? There is a chance, that the unicode versions on app side and xterm.js dont agree on the monospace width for certain chars, which might cause cursor offset and line wrapping issues.

**Comment by NeroSolomon** [comment]
Yes, it always happen  when the window resized and the chars are too long to stay in one line. The chars  just like `dadasdasdsdasdasdtesttesttesttesttesttesttesttesttesttesttesttesttest`

The encoding is GBK or utf8.

> might cause cursor offset and line wrapping issues

Yes, the cursor offset happens sometime. 

> that the unicode versions on app side and xterm.js dont agree on the monospace width for certain chars

I'll check it, thx

**Comment by NeroSolomon** [comment]
@jerch Can you tech me how to confirm the monospace width?

**Comment by NeroSolomon** [comment]
I found the problem: I send the cols to backend before autofix, so the cols is wrong. This issue can be closed. Thanks for your help
