### ISSUE TITLE
support for autocomplete or autosuggestion

### ISSUE THREAD

**Issue by Sparkenstein** [xtermjs/xterm.js#4213]
any modern shell comes with these features. currently I am trying to implement `hints` with chalk, something like

```js
if (a.key === "h") {
      term.write(`${chalk.green("h")}${chalk.dim("elp")}`)
      term.write("\b\b\b")
}
```
it kinda works 
![image](https://user-images.githubusercontent.com/24642451/196423303-93327bbd-5d3c-4efe-85a3-ba7c293691a0.png)

but manually adjusting every character like this will be a huge task.  because this doesn't even handle backspace etc. 
any other way to achieve the same? I would like to have both auto complete and auto suggestion support in my term

**Comment by Tyriar** [comment]
It's a shell's job to do this, if you're trying to do it on the frontend, that's a very complicated topic that VS Code has been slowly working towards over several years. I doubt that stuff will make it to xterm.js as it relies on shell integration.

**Comment by 2211898719** [comment]
<img width="1480" alt="image" src="https://github.com/xtermjs/xterm.js/assets/77563386/5ab3ed27-00b7-47b8-a378-e3b973ee0d0f">
我实现了一个很基础的版本，获取终端最后一行 用正则表达式去掉`root@VM-4-4-ubuntu:~#` 然后基于history进行提示

**Comment by 2211898719** [comment]
在大部分时候是能正常使用的
