### ISSUE TITLE
demo is broken with Epiphany browser

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#4223]
Currently the demo will not start up with the Epiphany browser (webkit based, gnome's default browser), because of the webgl addon being set as default.

Prolly linked to #3357, I think we need to find a more general conditional than `isSafari` for those webkit driven browsers, along with a more fine-grained version inspection (assuming newer webkit versions work already?)

**Comment by Tyriar** [comment]
That sucks, I don't think there was a way to detect this issue with the canvas going blank and Chrome includes `AppleWebKit` 😕
