### ISSUE TITLE
Min contrast ratio affects wrong cells when combined with search highlight

### ISSUE THREAD

**Issue by Eugeny** [xtermjs/xterm.js#4224]
Disclaimer: I couldn't reproduce it on the demo page - so just looking for a hint on what could be causing this.

When:
* canvas renderer is active
* minContrastRatio is enabled 
* search match highlighting is enabled
* search match bg/fg don't have enough contrast
* there's enough content to scroll

wrong cells are affected by contrast adjustment, namely, the same cells remain "adjusted" while content is scrolling by

It's easier demonstrated than explained:

https://user-images.githubusercontent.com/161476/197265926-4eb0bdbc-1528-47af-80e1-ed8748b8337c.mov

**Comment by Tyriar** [comment]
Can reproduce

<img width="773" alt="Screen Shot 2022-10-28 at 1 53 31 pm" src="https://user-images.githubusercontent.com/2193314/198730615-45722692-58e5-4a0d-833a-9ee21a5906b9.png">

Something is not offset from ydisp or base correctly
