### ISSUE TITLE
how to hide textarea helper?

### ISSUE THREAD

**Issue by alanhg** [xtermjs/xterm.js#4227]
## Details
- Browser and browser version: Chrome v106.0.5249.119
- OS version: Big Sur 11.7. 
- xterm.js version: 
"xterm": "^4.19.0"

### Steps to reproduce

when I write some progress-console, it shows a white border around the num. I found it's textarea helper.

how to hide it?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/9245110/197407336-39b9392a-ec1e-4011-bc0f-46ac71e9e3f4.png">

**Comment by Tyriar** [comment]
You probably didn't include xterm.css

**Comment by alanhg** [comment]
> The demo works fine in Chrome 106 for me:
> 
> ![image](https://user-images.githubusercontent.com/2193314/197566703-ceafc692-339e-421f-88eb-5948602bfe11.png)
> 
> So the problem is likely on your end somewhere. I'd also recommend moving to v5 as v4.19 is quite old now.
same issue on v5.

maybe my fault. I wonder, what is this background box, What can cause this problem, or does the cursor default to the first character when you want to line it.
But I have blur.

![image](https://user-images.githubusercontent.com/9245110/197575345-739f1ab2-2cfb-4652-aebc-822de5f5d379.png)

**Comment by Tyriar** [comment]
It isn't the unfocused cursor box is it?
