### ISSUE TITLE
When a large number of characters are entered into term, the interface is disordered.

### ISSUE THREAD

**Issue by bigkrys** [xtermjs/xterm.js#4230]
![image](https://user-images.githubusercontent.com/17899020/198244099-f0bc0036-ddc9-4b44-b956-fe3ffeab63f2.png)
![image](https://user-images.githubusercontent.com/17899020/198244176-a2d31eb3-02e7-4a88-888c-476eb591d16d.png)
![image](https://user-images.githubusercontent.com/17899020/198244218-9f3b6afb-c5cb-4e85-bd13-84d97a580574.png)

**Comment by Tyriar** [comment]
This looks like it would be an issue on your end, can you try reproduce in the demo and get back to us if it happens there? https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo
