### ISSUE TITLE
xterm-addon-web-links IViewportRange in hover callback is offset by 1

### ISSUE THREAD

**Issue by Coding-Kiwi** [xtermjs/xterm.js#4247]
I have a line with a link:

![image](https://user-images.githubusercontent.com/5007641/198996749-efb7b377-8ea4-46b2-b1d0-a0c334f90155.png)

Its the first line (row) of the terminal.

When I select something in the line and call `terminal.getSelectionPosition`, the start and end row is 0, this is what I would expect
When I hover the link and receive the location from the WebLinkProvider hover callback the start and end row is 1

## Details
- Browser and browser version: Electron 21.2.0
- OS version: Windows 11
- xterm.js version: 5.0.0
- xterm-addon-web-links 0.7.0

### Steps to reproduce

1. have a line with text and link
2. have xterm-addon-web-links with hover callback
3. select text, call getSelectionPosition
4. hover link, receive location
5. compare rows of locations

**Comment by Tyriar** [comment]
I'd expect this is 0-based but following IBufferRange says it should be 1-based:

https://github.com/xtermjs/xterm.js/blob/4451369c664b8ba7a94a7902ca6023d6838feb25/typings/xterm.d.ts#L1244-L1272
