### ISSUE TITLE
xterm.setOption is not a function

### ISSUE THREAD

**Issue by sunkuangdong** [xtermjs/xterm.js#4256]
## Details
- Browser and browser version: 
- OS version: Windows 11
- xterm.js version: 5.0.0

### Steps to reproduce

1. ![image](https://user-images.githubusercontent.com/45513363/200745623-e8ea0586-26d1-47a8-a5c6-f1a2bdf664f6.png)
2. It is my code:
3. xterm.setOption("theme", {
          "background": "#FFFCF3",
          "foreground": "#444444",
          "selection": "rgba(188,214,141, 0.4)",
          "cursor": "#41A863",
          "yellow": "#657B83",
          "brightYellow": "#657B83"
   });

**Comment by Tyriar** [comment]
It was removed in v5, see https://github.com/xtermjs/xterm.js/releases/tag/5.0.0

**Comment by jerch** [comment]
@Tyriar Should we update the docs page? It is still on 4.14 containing old API methods and properties.

**Comment by Tyriar** [comment]
@jerch there's been some deployment problems which I can't work around by myself. I emailed Paris about it.

**Comment by daonb** [comment]
Just upgrade to 5.0 and got bitten by this. Here's the excerpt from the changlog:

> - The deprecated getOption and setOption APIs have been removed in favor of options 
> (https://github.com/xtermjs/xterm.js/pull/3947) via @Tyriar
>
> // before 5.0.0
> term.setOption('scrollback', 1000);
> console.log(term.getOption('scrollback'));
> 
> // after 5.0.0
> term.options.scrollback = 1000;
> console.log(term.options.scrollback);
