### ISSUE TITLE
Mouse scroll should move cursor in vim

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#426]
### Steps to reproduce

1. `vim`
2. `i`
3. Fill file beyond number of rows
4. Scroll using mouse wheel, the vim cursor should respond

**Comment by Tyriar** [comment]
Setting `term.mouseEvents` makes the viewport in vim scroll (not the cursor like in `gnome-terminal`). `mouseEvents` doesn't seem to be getting turned on though.

**Comment by Tyriar** [comment]
`mouseEvents` works fine when you set mouse mode in `.vimrc` with:

```
set mouse=a
```

**Comment by parisk** [comment]
👍  works consistently after `set mouse=a`; it scrolls the viewport `x` lines up or down (where x is a multiple of 3).

 I noticed the following scrolling inconsistency though before using `set mouse=a`:

- **Terminal.app on macOS**: Moves the cursor
- **xterm.js in Chrome**: Does nothing

Seems like `set mouse=a` changes the mouse scrolling behavior in general (even in Terminal.app) and this is why it works in xterm.js.

Shouldn't xterm. scroll the cursor before `set mouse=a`?

**Comment by Tyriar** [comment]
Yes it should scroll the cursor without. I'm not sure when we're meant to sent wheel events to the app and/or to the (xterm.js) viewport.
