### ISSUE TITLE
xterm-addon-search return always false

### ISSUE THREAD

**Issue by vidhimultiqos** [xtermjs/xterm.js#4264]
We are facing the same issue in our application.

We have used below packages and versions:
xterm: "^5.0.0",
xterm-addon-search:"^.010.0"

While we are searching any words, Function (searchAddon.findNext("ls")) returns false.

**Comment by vidhimultiqos** [comment]
@Tyriar Can you please help us?

**Comment by Tyriar** [comment]
I can't reproduce this in the demo on master:

![Recording 2022-11-20 at 09 26 45](https://user-images.githubusercontent.com/2193314/202916609-ab7abdd4-ce92-4cd0-9d88-691111fded2b.gif)

It could be an issue in an older version of the search addon or something unexpected? We can't action without more information though.
