### ISSUE TITLE
My scroll bar doesn't work right and I cannot see the history

### ISSUE THREAD

**Issue by Echo-minn** [xtermjs/xterm.js#4266]
when I enter many commands, the lines goes down, however the scroll bar pin on the top , and I cannot scroll back to view my history command ( not cleared ）, It seems that my history disappeared and the scroll areas show up wrongly, which are supposed to be on the top instead of bottom

![image](https://user-images.githubusercontent.com/32877946/202609303-e25db567-e0df-4071-822f-1fdfe2616d84.png)

I am totally confused and holp you can get me some tips to figure out what happened.
## Details
- Browser and browser version: 
Chrome
- OS version: 
Ubuntu 16
- xterm.js version: 
 "xterm": "^5.0.0",

### Steps to reproduce
1. 
2.

**Comment by Tyriar** [comment]
Can you reproduce this in the demo? That scroll bar could be the document's scroll bar?

**Comment by Echo-minn** [comment]
> Can you reproduce this in the demo? That scroll bar could be the document's scroll bar?

hey, i figure this out，the ` overflow-y: scroll; `  was deleted by accident, so the scroll bar act like `overflow-y: revert;`
