### ISSUE TITLE
any method to know, After the xterm.write success, the affected line number range is

### ISSUE THREAD

**Issue by alanhg** [xtermjs/xterm.js#4268]
sometimes, I want to know After the xterm.write success, the affected line number range is.

**Comment by jerch** [comment]
No thats not possible, the terminal buffer is a random access buffer for the active cursor area, and sequences can move the cursor freely around, therefore chars can be added anywhere in that area in any order, depending on incoming sequences.

If you know that your incoming data will never use more complicated sequences (sequences that move the cursor around or change content and cursor pos at once out of the normal sequential cursor progression from printed data), you can try to get a hold of affected rows with the `onLineFeed` event.

**Comment by alanhg** [comment]
> No thats not possible, the terminal buffer is a random access buffer for the active cursor area, and sequences can move the cursor freely around, therefore chars can be added anywhere in that area in any order, depending on incoming sequences.
> 
> If you know that your incoming data will never use more complicated sequences (sequences that move the cursor around or change content and cursor pos at once out of the normal sequential cursor progression from printed data), you can try to get a hold of affected rows with the `onLineFeed` event.

any method to know which line cursor is?

**Comment by jerch** [comment]
Yep. You'll find the current cursor position there under the active buffer and its `cursorX` | `cursorY` properties. But note, that those values reflect the absolute position in the active cursor area, which will shift underneath `onScroll`. So you have to code some more handlers to properly flow with those shifts.
