### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by arcanis** [xtermjs/xterm.js#4281]
The https://xtermjs.org domain name seems to serve the `*.github.com` certificate, which is invalid and cause Chrome to abort:

<img width="1096" alt="Screenshot 2022-12-01 at 10 24 19" src="https://user-images.githubusercontent.com/1037931/205015633-81860eff-32a2-4c02-ad2f-b8820f018ff8.png">

**Comment by jerch** [comment]
Explicit removing + re-adding "xtermjs.org" as fqdn pulled a valid certificate for now. But some thing is still wrong with the DNS setup:
![grafik](https://user-images.githubusercontent.com/6193135/205057083-c5c8e919-bd3e-4316-aed4-80e079f845e3.png)

@Tyriar I am not sure, if the error above will cancel automatic certificate updates later on. Following the gh docs, the DNS entry should be shaped like this to pass the domain validation tests:

```
xtermjs.org.    26728 IN CNAME xtermjs.github.io.
xtermjs.github.io.   1527    IN  A   185.199.108.153
xtermjs.github.io.   1527    IN  A   185.199.111.153
xtermjs.github.io.   1527    IN  A   185.199.110.153
xtermjs.github.io.   1527    IN  A   185.199.109.153
```

Currently the DNS entry contains the github.io servers directly as A/AAAA records:
```
xtermjs.org.            351     IN      A       185.199.108.153
xtermjs.org.            351     IN      A       185.199.109.153
xtermjs.org.            351     IN      A       185.199.110.153
xtermjs.org.            351     IN      A       185.199.111.153
xtermjs.org.            351     IN      AAAA    2606:50c0:8000::153
xtermjs.org.            351     IN      AAAA    2606:50c0:8001::153
xtermjs.org.            351     IN      AAAA    2606:50c0:8002::153
xtermjs.org.            351     IN      AAAA    2606:50c0:8003::153
xtermjs.org.            21158   IN      NS      dns1.papaki.gr.
xtermjs.org.            21158   IN      NS      dns2.papaki.gr.
xtermjs.org.            21158   IN      SOA     dns1.papaki.gr. support.papaki.gr. 2022113008 10800 3600 1209600 3600
```

Still closing the issue, as it is fixed for now.
