### ISSUE TITLE
Looking for react.js implementation of xterm.js

### ISSUE THREAD

**Issue by himanshu-1034** [xtermjs/xterm.js#4283]
HELP!!!!!!!!!     Hii all, Can anyone point me to the correct way of implementing xterm.js.. I need this urgently

Actually I am trying to render a terminal inside a component which works in development but when is deployed to production gives console error and my page breaks because of this. I don't know what am I doing wrong... 

below is my code

`import React, {
    useEffect
} from 'react';
import {
    Terminal
} from 'xterm';
import {
    FitAddon
} from 'xterm-addon-fit';

const UITerminal = () => {
    const term = new Terminal();
    const fitAddon = new FitAddon();
    term.loadAddon(fitAddon);

    useEffect(() => {
        let termDocument = document.getElementById('terminal')
        if (termDocument) {
            resizeObserver.observe(termDocument)
            term.open(termDocument)
            addonfit.fit();
        }
        window.addEventListener('resize', () => {
            addonfit.fit();
        })
    }, [])

    return ( <
        div id = "terminal" > < /div>
    )
}`
below is the error on console
`
react_devtools_backend.js:4012 ReferenceError: Cannot access 'r' before initialization
    at new m (96209.72626fc1cc862aea477a.bundle.js:1:165467)
    at new b (96209.72626fc1cc862aea477a.bundle.js:1:159758)
    at new M (96209.72626fc1cc862aea477a.bundle.js:1:57572)
    at new r.exports.i.Terminal (96209.72626fc1cc862aea477a.bundle.js:1:294972)
    at w (96209.72626fc1cc862aea477a.bundle.js:1:15994)
    at zo (main.71e827eabc798023c129.bundle.js:1:1260000)
    at Ws (main.71e827eabc798023c129.bundle.js:1:1333492)
    at Wi (main.71e827eabc798023c129.bundle.js:1:1294411)
    at Ui (main.71e827eabc798023c129.bundle.js:1:1294336)
    at Pi (main.71e827eabc798023c129.bundle.js:1:1291367)
`

The error is from the production code so These params are not exact..
But I think I am not importing xterm correctly in my code...

**Comment by himanshu-1034** [comment]
CAN SOMEONE HELP ME OUT HERE??

**Comment by jerch** [comment]
@himanshu-1034 Sorry, this is the issue tracker for xterm.js related bugs and feature requests, not a forum to help with basic programming question or how to integrate with toolkit xy. You might have more success on SO or the search engine of your choice.

**Comment by himanshu-1034** [comment]
@jerch I just wanted to know how to correctly import xterm package in reactjs as the way mentioned in xterm.js's documentation is working fine in development but not in prod env. 
https://xtermjs.org/docs/guides/import/

**Comment by Tyriar** [comment]
@himanshu-1034 we don't use react so we don't know

**Comment by Mostafizur-Rahman8391** [comment]
You got to initialize the function first
It's being called before the function is actually implemented
