### ISSUE TITLE
Links get wrong position when they are after wide chars with canvas/webgl renderer

### ISSUE THREAD

**Issue by JasonXJ** [xtermjs/xterm.js#4294]
See the image below. Note that it only happens to the links detected by the weblinks addon but not OSC 8 links. It also only happens to webgl and canvas renderers but the dom one.
![image](https://user-images.githubusercontent.com/6949499/206161640-616e89b1-d0ae-4e05-a9a0-9fcccdbe2879.png)

I looked at the code a bit. It seems that the web link addon uses the character position (i.e. "哈" is counted 1 even though it is a wide character) as the the value for `IBufferCellPosition.x`. [Code here](https://github.com/xtermjs/xterm.js/blob/497df06f3f848ce1ae2b33dd69b2e56a2791ff3e/addons/xterm-addon-web-links/src/WebLinkProvider.ts#L73). Is this the correct way?

BTW, I am not sure whether this is just #2887.

## Details
- Browser and browser version: Chrome 110
- xterm.js version: Tot

**Comment by jerch** [comment]
The weblink addon is broken in several ways, which is basically the reason for #4288. Maybe check if the issue remains with that PR?

**Comment by JasonXJ** [comment]
Hi Jerch, your PR works great! It not only fixes this issue, but also 1) works for special shortlink such as `http:/b/123456`; 2) no longer includes trailing `.` in the url so that urls in documentation et al. are not messed up.

Can I expect this to be merged soon?

**Comment by JasonXJ** [comment]
There is still some rendering issue with the DOM renderer (I care much more about the webgl renderer though). See the screenshot below --- my mouse cursor is on the link in the first row.

![image](https://user-images.githubusercontent.com/6949499/206328289-e2702817-faa1-4ed1-a37f-567e04d95583.png)

**Comment by jerch** [comment]
> Can I expect this to be merged soon?

Well it still needs some more test cases, I kinda turned the whole regexp upside-down to also match unicode chars in paths (nowadays supported by all browsers), but this makes match exclusions a bit more cumbersome.

> There is still some rendering issue with the DOM renderer ...

Had to fix the DOM renderer offset calc (was totally off with correct cell positions), seems there is still a one off issue at the end of underline.

**Comment by jerch** [comment]
@JasonXJ Should work now (plz report in the PR, if something is still totally off :crossed_fingers:)
