### ISSUE TITLE
Links should be re-evaluated immediately on buffer line change if ctrl is held

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4295]
VS Code issue: https://github.com/microsoft/vscode/issues/131114

Demonstration of issue:

![Image](https://user-images.githubusercontent.com/2193314/206313284-90c0dd2c-50ba-4c59-bb6d-e6104be6a588.gif)

ie. it would feel more polished if links were re-evaluated when data was added to the buffer if ctrl is held.

**Comment by Spongman** [comment]
scrolling is not required to repro this issue. just adding new lines to the bottom of the view is sufficient to repro this.
