### ISSUE TITLE
Terminal double click to select word doesn't calculate end properly when CJK is used

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4307]
VS Code issue: https://github.com/microsoft/vscode/issues/147619

Repro:

1. Paste `获取模板 25235168 的预览图失败`
2. Double click the number

**Comment by Tyriar** [comment]
Another repro: https://github.com/microsoft/vscode/issues/156962

**Comment by jerch** [comment]
Cannot repro in master, but in vscode - got this already fixed recently?

**Comment by Tyriar** [comment]
Thanks for the info, this must be an issue with link providers in vscode
