### ISSUE TITLE
Addon packages not updated on npmjs.com

### ISSUE THREAD

**Issue by dstein64** [xtermjs/xterm.js#4336]
The documentation for the recent release, [5.1.0](https://github.com/xtermjs/xterm.js/releases/tag/5.1.0), indicates that the following addons were updated:

- `xterm-addon-attach`
- `xterm-addon-canvas`
- `xterm-addon-serialize`
- `xterm-addon-webgl`
- `xterm-addon-web-links`

Of these, I see on [npmjs.com](https://www.npmjs.com) that only `xterm-addon-attach` and `xterm-addon-serialize` have been updated:

- https://www.npmjs.com/package/xterm-addon-attach
- https://www.npmjs.com/package/xterm-addon-serialize

The others, `xterm-addon-canvas`, `xterm-addon-webgl`, and `xterm-addon-web-links` have not been updated:

- https://www.npmjs.com/package/xterm-addon-canvas
- https://www.npmjs.com/package/xterm-addon-webgl
- https://www.npmjs.com/package/xterm-addon-web-links

**Comment by dstein64** [comment]
I noticed this because the `xterm-addon-canvas` addon was not working properly after I updated `xtermjs`. I also tried updating the addon, but I already had the latest version. Building the addon manually with `npm run package` resolved the issue.

**Comment by Tyriar** [comment]
Probably due to the initial failed build, then the next one not having changes in the respective addon folders https://dev.azure.com/xtermjs/xterm.js/_build/results?buildId=6098&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=e0af9a38-0b43-5e08-a8e3-eaeedcf86686

**Comment by jerch** [comment]
@Tyriar I think this is still not fixed - looking at code change I see at least in the these addons changes, that are not reflected by version bumps:
- fit (also see #4338)
- unicode
- search

**Comment by Tyriar** [comment]
Oh you're right, I looked at the history and saw October 15 but I just realized the v5 was in Sept

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/pull/4343
