### ISSUE TITLE
Fit addon fails to propose correct dimenions

### ISSUE THREAD

**Issue by nebulade** [xtermjs/xterm.js#4338]
This issue came up when I tried to update from xterm 5.0.0 to 5.1.0.
xterm-addon-fit is the same version 0.6.0

First the fit() method as called before does not work and upon some debugging, `proposeDimensions()` always returns `Object { cols: NaN, rows: NaN }`

Unfortunately I have no clue how to debug this further as stepping through the function with the debugger and sourcemaps mostly shows undefined objects and skips lines and I don't know how to build the assets correctly from the .ts files if I'd want to add some console.log()s.

There are some suspicious comments like https://github.com/xtermjs/xterm.js/blob/master/addons/xterm-addon-fit/src/FitAddon.ts#L60 which may hint at the issue?

## Details
- Browser and browser version: both current ff and chrome 
- xterm.js version: 5.1.0

### Steps to reproduce

The code is essentially just the example code from the addon Readme and it used to work.

**Comment by MorningLightMountain713** [comment]
I just hit this, same versions. Rolled back to 5.0.0 and everything works.

**Comment by olivierchatry** [comment]
Yup, this come from this :

**Comment by jerch** [comment]
@Tyriar I think the fit addon misses a version bump for 5.1 release as there were changes to it?

As an interim fix you can use 0.7.0-beta.2, which contains the latest code changes.

**Comment by pomdtr** [comment]
> As an interim fix you can use 0.7.0-beta.2, which contains the latest code changes.

Thanks for the tip, it fixed it on my end

**Comment by Tyriar** [comment]
Should be fixed with https://github.com/xtermjs/xterm.js/pull/4343 getting merged (just needs 10 or so minutes to release)

**Comment by olivierchatry** [comment]
Thank you very much :)

**Comment by nebulade** [comment]
Great and thanks for the super fast reaction on this!

**Comment by vire** [comment]
I can confirm this function https://github.com/xtermjs/xterm.js/blob/99df13b085aecb051f1373c5b7f8e819c4f41442/addons/addon-fit/src/FitAddon.ts#L61

returns different `cols` and `rows` for the same DOM node dimension on two sub-sequent re-renders
