### ISSUE TITLE
Take column into account when rendering cells for perfect patterned underline rendering

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4349]
Forking off from https://github.com/xtermjs/xterm.js/issues/4060

> Thinking about this and the fact that I want xterm.js rendering to be as great as possible, I think we should support multiple glyphs depending on the x-axis when necessary. For the dotted line specifically, say we had a dot of size `window.devicePixelRatio` with the same sized gap in-between, so there would be at most 2 possible variants for every glyph:
> 
> ```
> Even:
> |* * * * |
> 
> Odd:
> |* * * * *|
> | * * * * |
> ```
> 
> To store this as a unique glyph we need to make the glyph key different, this could be done by asking what underline variant it is and then store it as a number, maybe capped at 4 (2 bits) or 8 variants (3 bits)?
> 
> This would allow us make a non-repeated curvy line and not restrict us to a single cell for both the up and down parts of the wave, if that ends up looking better of course.

Current:

![image](https://user-images.githubusercontent.com/2193314/209409348-bc590397-f8bb-4fac-baf2-ebde5e4b2aa8.png)
![image](https://user-images.githubusercontent.com/2193314/209409352-e2bfd77d-bf13-4a68-88cc-2357c32cfdfe.png)

Desired:

![image](https://user-images.githubusercontent.com/2193314/209409468-1c0da170-deff-44b6-b57f-6a978628b878.png)
![image](https://user-images.githubusercontent.com/2193314/209409475-24f75dc0-23ef-40a1-95ac-5d65b2854678.png)

**Comment by tisilent** [comment]
![企业微信截图_16818975586554](https://user-images.githubusercontent.com/48614781/233039591-a45adce4-3f88-47e7-b1bc-3afc5d07629c.png)
I don't know if this effect will be better.

**Comment by tisilent** [comment]
hi @Tyriar ,
![企业微信截图_16922683211768](https://github.com/xtermjs/xterm.js/assets/48614781/12517a91-d6ec-4e83-bb17-b200d011b632)
Is this the effect 😆

**Comment by Tyriar** [comment]
@tisilent yes the circles part is one of the problems this is calling out. Basically we want a perfectly repeating pattern for dotted and dashed. My thinking was to offset the underline based on the column, then make sure that the same underlines are shared between glyphs in the texture atlas.

One of the harder parts of this is to make sure it works across all font sizes and zoom levels.
