### ISSUE TITLE
Text widths do not match between various addons and DOM even when fonts are identical

### ISSUE THREAD

**Issue by davidfiala** [xtermjs/xterm.js#4401]
I noticed that xterm using Canvas or Webgl addons does not render text to the same width as text in the DOM with the same size, spacing, and font family. I would expect that to render the same size. This causes visual alignments issues for my use case when I serialize terminals and render them in HTML above/below a live xterm using these addons.

Please see my attached example.

Some font sizes (in my case, 16px) align perfectly. Whereas others (14px in my case) the canvas and GL are shorter than normal DOM text.

![screenshot](https://user-images.githubusercontent.com/12127027/216863411-34d9b5e4-f4cc-447a-b92a-6c2eb937b392.png)

## Details
- Browser and browser version: 
-- Windows 11  (Chrome 109.0.5414.120, Firefox 109.0.1)
-- Ubuntu 22.04 (Chrome 108.05359124,  Firefox 109.0)
-- Mac M1 13.2 (Safari 16.3)
- xterm.js version: 
-- xterm 5.1.0
-- xterm-addon-canvas 0.3.0
-- xterm-addon-webgl 0.14.0

### Steps to reproduce
1.  Unzip attached example: [xterm-font-bug.zip](https://github.com/xtermjs/xterm.js/files/10636800/xterm-font-bug.zip)
2.  `npm i`
3. `npm run dev`
4. Visit http://localhost:9000 and optionally drag the slider to change font sizes. Observe that at some font sizes there is perfect alignment and that others there is unmatching widths of the same text. (Particularly between row 1 vs rows 3 or 4) Row 2 is buggy for other reasons mentioned above.

_Unrelated and out of scope for this bug: xterm without any addons seems to always align with HTML, however a separate bug seems to not update the font widths of the actual characters; the characters still stay the same size but change reserved width. You'll see that in my demo, but it is NOT the context of this bug. (eg, slide the font larger)_

**Comment by Tyriar** [comment]
This is by design, the canvas-based renderers handle floating point character width their own way which is different to the browser's.

I'm not sure what your use case is, but there is the serialize addon to easily serialize the contents of the terminal, and if you need to display it again you could create it using the same renderer. If one of them must be plain DOM then I'd recommend just going with the DOM renderer.
