### ISSUE TITLE
Scrollback goes missing when resizing a conpty-based terminal on Windows 11

### ISSUE THREAD

**Issue by TimothyZero** [xtermjs/xterm.js#4418]
Here are some useful links
Windows 11 (bug):  [vscode/issues#145368](https://github.com/microsoft/vscode/issues/145368)
Windows 10 (fixed): [xterm.js/issues#2459](https://github.com/xtermjs/xterm.js/issues/2459)

thanks in advance!

**Comment by jerch** [comment]
Plz provide more info on whats going wrong. Pointing to other issues with opposite results is not helpful to understand YOUR issue.

**Comment by jerch** [comment]
Well I cannot really help you with vscode related issues beside stating, that ConPty behaves quite different at certain ends. I think there are circumstances where conpty refreshes the whole viewport screen from its internal buffer state- maybe thats removing the progression (like some race condition between resizing and viewport update)?

To narrow down, whether thats an xtermjs or node-pty/conpty related issue - have you checked against other TEs under windows?

**Comment by TimothyZero** [comment]
Sorry, what is TEs?

**Comment by TimothyZero** [comment]
Actually no, may you provide some suggests about TEs under windows? I'll take a try on my PC.

**Comment by jerch** [comment]
I think WezTerm, alacritty and contour have windows builds. There is also Windows Terminal from MS itself, but it uses a newer conpty implementation internally, so it might not show the issue if its caused by older conpty versions.
