### ISSUE TITLE
Cursor jumping around

### ISSUE THREAD

**Issue by FormalSnake** [xtermjs/xterm.js#4428]
## Details
- Browser and browser version:  Electron 23.1.1
- OS version: macOS 13.2.1
- xterm.js version:  5.1.0

### Steps to reproduce

1. Clone my repository: [Formalterm](https://github.com/FormalSnake/Formalterm/tree/V0.0.4)
2. Open Neovim or tmux and and do things that change mouse positions, like `ctrl+b s` and shuffle through instances
3. Cursor should jump around

If necessary you can ask for footage.

**Comment by jerch** [comment]
> If necessary you can ask for footage.

Yepp, thats necessary. From your current description it is not possible to understand, how the actual behavior deviates from your expectation.

**Comment by FormalSnake** [comment]
the jumping got seemingly fixed by settings pty  name to `xterm-256color`
why does this affect the cursor? what does it actually do and which is the most efficient?

**Comment by jerch** [comment]
This changes the TERM env variable and thus the sequences a terminfo based application gonna use. xterm.js itself does not maintain a custom terminfo entry atm, we use "xterm-256color" in the repo demo as well.

**Comment by FormalSnake** [comment]
> This changes the TERM env variable and thus the sequences a terminfo based application gonna use. xterm.js itself does not maintain a custom terminfo entry atm, we use "xterm-256color" in the repo demo as well.

I'll use it then, altho the terminal isnt as smooth and snappy like kitty, are there any good add-ons for that?

**Comment by FormalSnake** [comment]
I am already using webgl, but it is not that performant

**Comment by jerch** [comment]
Well webgl is the fastest output renderer, thus your integration mostl likely eats up precious CPU cycles elsewhere. You'd have to check your incoming data route to find the culprit, some remarks on that:
- websocket is faster than longpolling
- utf8 byte transport is faster than string transport
- throughput gets better with a tiny buffer at the pty output to collect single byte responses into bigger once (saves some context switches)
- remove costly components the data has to go through adding nonsense CPU or waiting time (latency gets bad)
- for serious data transport you gonna need a flow control mechanism at least in pty --> xterm.js direction

**Comment by FormalSnake** [comment]
Thanks!
