### ISSUE TITLE
In the vue project, I cannot select text with the cursor.

### ISSUE THREAD

**Issue by 18578242152** [xtermjs/xterm.js#4431]
## Details
- Browser and browser version:  Latest version of Google Browser
- OS version: 
- xterm.js version: 

### Steps to reproduce
In the vue project, I cannot use the cursor to select text, but I can select it in the static html file.

**Comment by jerch** [comment]
We cannot give vue specific help, as none of us uses it. Plz ask on SO or in some vue related forum.
