### ISSUE TITLE
scrolltoBottom Err

### ISSUE THREAD

**Issue by TheBlindM** [xtermjs/xterm.js#4433]
Using term.scrolltoBottom() in onActivated in vue3, the view is at the bottom but the scroll bar is not at the bottom
![image](https://user-images.githubusercontent.com/48701152/223889020-703e7803-044b-406f-86f4-891bf322bc65.png)

## Details
- Browser and browser version: Google latest version
- OS version: win10
- xterm.js version: 5.1

### Steps to reproduce

```
onActivated(() => {
	terminalFocus();
	fitAddon.fit();
     term.scrollToBottom();
});
```

**Comment by jerch** [comment]
We cannot give vue specific help, as none of us uses it. Plz ask on SO or in some vue related forum.
