### ISSUE TITLE
Ansi256 on MacOS problem

### ISSUE THREAD

**Issue by dalssoft** [xtermjs/xterm.js#4440]
## Details
- OS version: MacOS Ventura 13.2.1 (22D68)
- VS Code: 
Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No 

### Problem
The terminal in VS Code (xterm) is not able to reproduce all the colors on Ansi256. The evidence is in the image bellow where others terminals are able to do it.

The difference is clear on the ranges [16..21], [52-63] but specially on [232..243]

### Steps to reproduce

1. Run the JS code on different terminals:

```js
const colors = []
for (let i = 16; i < 256; i++) {
    colors.push(`\x1b[38;5;${i}m${i}\x1b[0m`)    
    if ((i -4) % 12 === 11) {
        colors.push('\n')
    }
}
console.log(colors.join(' '))
```

2. This is the result:

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/209287/226454969-112e32ae-fa6f-4f04-b157-94f3c943dead.png">

The code above was generated by ChatGPT, so it might be wrong, but I wanted something with no dependencies here. However I'm using Chalk on my project and the result is the same.

**Comment by jerch** [comment]
xterm.js does a color/luminance adjustment based on the setting `minimumContrastRatio` to ensure a certain distance between foreground and background to keep things readable. Just lower that value to let closer colors through unaltered (1 to switch it off).

**Comment by dalssoft** [comment]
Great, thanks for the quick response. It works perfectly now.

Not sure why the default is 4.5, but this king of prevents some interesting terminal applications from using the full color range. Sometimes the developer wants to use a color that is close to black. I think it would be better to have a default of 1.0, but I guess that would break a lot of existing applications.

Since it is not a bug, I will close this issue.
