### ISSUE TITLE
Ability to hide the cursor

### ISSUE THREAD

**Issue by YesImSevy** [xtermjs/xterm.js#4448]
Is there a way to hide the cursor or am I just stuck with using an addon or being forced to keep it there?

**Comment by Tyriar** [comment]
You can send the `Hide cursor (DECTCEM)` sequence to the terminal, an application may overwrite that though. https://invisible-island.net/xterm/ctlseqs/ctlseqs.html

You could also try setting the color of the cursor to transparent but I wouldn't be surprised if that doesn't work. No plans to add explicit support for this.
