### ISSUE TITLE
please mention DomTerm under "Real-world uses"

### ISSUE THREAD

**Issue by PerBothner** [xtermjs/xterm.js#4455]
This isn't a bug report per se, but a request for a documentation addition.  I'm happy to create a pull request, but I'm unsure how verbose I can be.  I'm also unsure high up in the list it should be - I'm guessing the position in the list is intended to be a combination of importance/visibility and current activity.

The combination DomTerm+xterm.js is interesting to those who want an xterm.js terminal emulator as an application with a number of useful features, as mentioned in the listing:

> [DomTerm](https://domterm.org/xtermjs.html): Tiles and tabs.   Detachable sessions (like tmux).  [Remote connections](https://domterm.org/Remoting-over-ssh.html) using a nice ssh wrapper with predictive echo.  Qt, Electron, Tauri/Wry, or desktop browser front-ends. Choose between xterm.js engine (faster) or native DomTerm (more functionality and graphics) - or both.

**Comment by Tyriar** [comment]
The list is currently in order they were added, created: https://github.com/xtermjs/xterm.js/pull/4456

**Comment by PerBothner** [comment]
Much appreciated.
