### ISSUE TITLE
search style bug when you scroll.

### ISSUE THREAD

**Issue by TommyCat008** [xtermjs/xterm.js#4466]
这个问题应该是稳定复现的，我在vscode的最新版本中也能复现此问题。你可以尝试使用man ipset命令，然后查询一个字符串，滚动整体页面就会看到选中的背景在浮动。

The problem should recur steadily, and I was able to recur it in the latest version of vscode. You can try using the man ipset command, then query a string, scroll through the whole page and see the selected background floating.

## Details
- Browser and browser version: Chrome latest
- OS version: 12.6
- xterm.js version: latest

### Steps to reproduce

1. man ipset 
2. scroll

**Comment by Tyriar** [comment]
I believe this is fixed, I can't repro in vscode
