### ISSUE TITLE
L-shaped artifacts when using xterm instances with Canvas or WebGL addons on Firefox

### ISSUE THREAD

**Issue by sergeichestakov** [xtermjs/xterm.js#4487]
Hey there! Apologies if this has been reported already. I tried searching for similar issues and came across other graphics bugs but couldn't find one that reported this exact issue.

One graphical bug we've been noticing when using xterm has been these strange L-shaped artifacts that are occasionally persisted in the terminal and overlay the output after some time. They seem to be left over from the cursor as they match it in shape/size and appear to only render in places where the cursor was previously rendered. Note that this only happens when either the Canvas or WebGL addons are loaded. Rendering to the DOM, as xterm does by default, does not seem to cause this. We've also only been able to reproduce this on Firefox so it may be a bug in Firefox itself and how it renders graphics to a canvas.

This is a screenshot from our config which was using the Canvas addon (as well as a number of other addons):

<img width="346" alt="xterm-canvas-artifacts" src="https://user-images.githubusercontent.com/24947334/233722877-0cbe550c-8e14-4f8d-a86b-0bd14d488be4.png">

We were also able to reproduce this in the terminal instance on the xterm [landing page](https://xtermjs.org/):

![xterm-canvas-artifacts-official-website](https://user-images.githubusercontent.com/24947334/233722623-4c0629a9-5816-456c-aa41-bfeadd489ea5.png)

## Details

- Browser and browser version: Firefox 112.0.1
- OS version: MacOS Ventura 13.3.1
- xterm.js version: 5.1.0 (`xterm-addon-canvas` version 0.3.0 and `xterm-addon-webgl` version 0.14.0)

### Steps to reproduce

1. Use Firefox
2. Visit an xterm instance with either the Canvas or WebGL addons loaded
3. Enter a bunch of commands that trigger output (e.g. `ls`, `pwd`, etc)
4. After a few, you should start noticing L-shaped artifacts similar to the screenshots above, especially while the cursor moves

**Comment by jerch** [comment]
Can repro this with Firefox - also happens with terminal in focus from the full block cursor glyph, but less often.

It seems, that the full block and the hollow block cursor run into rounding issues during glyph output not matching the erase block done on a new glyph in that position.

**Comment by Tyriar** [comment]
The cursor rectangle must be drawing slightly different pixels on Firefox compared to Chromium, clearing a larger area is a find fix without much impact.

**Comment by Tyriar** [comment]
I can't repro on my mac 🤔

**Comment by sergeichestakov** [comment]
Weird I'm on a Mac as well (M1 Pro running MacOS Ventura 13.3.1) and the latest Firefox (112.0.2) if that helps.

Anyways, thanks so much! hope it works 🤞 will give it a try once the next update is published and report back here!

**Comment by sergeichestakov** [comment]
great, thanks so much! will give it a go

**Comment by sergeichestakov** [comment]
btw how can I see what's changed in a beta release (e.g. which commits are included)? trying to see if we can rely on the beta release in prod and wanted to double check there wouldn't be any intended side effects of pulling it in

**Comment by Tyriar** [comment]
Here's the diff: https://github.com/xtermjs/xterm.js/compare/5.1.0...master, normally it's fine to use beta as that's typically what VS Code Insiders is on. So if there is a regression it's normally fixed pretty quick, we aim for master to be stable at all times.

**Comment by sergeichestakov** [comment]
great, thanks for the quick reply!
