### ISSUE TITLE
terminal mess up after resize frequently

### ISSUE THREAD

**Issue by destinytaoer** [xtermjs/xterm.js#4489]
terminal seems to mess up after resize frequently

## Details
- Browser and browser version: Chrome 112.0.5615.137
- OS version: macOS 12.1 
- xterm.js version: 5.1.0
- node-pty: 0.10.1

i use node-pty in this demo, but other tty like k8s exec api has same problem

https://github.com/destinytaoer/web-terminal

### Steps to reproduce

1. input a long message into terminal
2. resize the window frequently

before：
![image](https://user-images.githubusercontent.com/27852774/233816912-3922f9ff-1075-41fc-8bf1-cfeb5e7ac922.png)

after:
![image](https://user-images.githubusercontent.com/27852774/233817007-c9f59218-93b9-47be-adbe-76f3dc98edda.png)

**Comment by jerch** [comment]
Thats most likely caused by the shell trying to reflow the prompt line on its own, which interferes with xterm.js line reflow. There is nothing we can do about it (beside telling shell devs to stop reflowing on their own).
