### ISSUE TITLE
When I try to enter chinese character in term ,it does not work

### ISSUE THREAD

**Issue by ZhouMM92** [xtermjs/xterm.js#4492]
I use websocket in my project. The server code is:
while ((i = sshOperateEntity.getInputStream().read(buffer)) != -1) {
         resultMessage.setData(Arrays.copyOfRange(buffer, 0, i));
         wsession.sendMessage(new TextMessage(JSONObject.fromObject(resultMessage).toString()));
 }
and the class of resultMessage is:
public class HostMessage {
    private String messageType;
    private byte[] data;
    }
and My vue code is：
    getSocketData(res){
      const that =this
      let message = JSON.parse(res.detail.data)
          that.term.write(message.data)
    }
The problem is when I enter Chinese character in the term,the error is:
![image](https://user-images.githubusercontent.com/101792358/234175803-a373e29b-f7ce-4525-ae0d-fe95bfea0293.png)

so, what should I do to solve this problem, thanks.
## Details
- Browser and browser version: 
- OS version: windows 10 
- xterm.js version: 5.1.0

### Steps to reproduce

1. 
2.

**Comment by ZhouMM92** [comment]
@jerch

**Comment by jerch** [comment]
Whats the result and type of  `JSON.parse(res.detail.data)`? `term.write` understands only utf8 bytes as `UintArray` or a single JS string (must be proper utf-16 unicode).

NB: Plz use markdown source formatting, this way your code is really hard to read.

**Comment by ZhouMM92** [comment]
> Whats the result and type of `JSON.parse(res.detail.data)`? `term.write` understands only utf8 bytes as `Uint8Array` or a single JS string (must be proper utf-16 unicode).
> 
> NB: Plz use markdown source formatting, atm your code is really hard to read.

Thank you very much for replay. And when I set the bytes as utf8 , the problem can be solved. But there's another problem:
I can not enter chinese when I use ** sougou Pinyin**,it looks like the term can not catch the chinese input:
![image](https://user-images.githubusercontent.com/101792358/234750686-01e5f91a-3ef5-4182-998c-891bfdc94573.png)
![image](https://user-images.githubusercontent.com/101792358/234750702-527deaf5-8115-4a70-a008-16693be4a947.png)

but when I use **Microsoft Pinyin**，the term can catch the chinese input：
![image](https://user-images.githubusercontent.com/101792358/234750802-8540f34c-a804-4428-9fe9-6f29b6138b52.png)
![image](https://user-images.githubusercontent.com/101792358/234750826-54f15a89-dd8a-4971-b338-553c8b9ad0c2.png)

**Comment by jerch** [comment]
The "sougou Pinyin" is known for having issues in the past (search the issue list). You may want to open a new issue for that to get more attention from ppl facing the same issue or that have solved it.
