### ISSUE TITLE
VSCode Throws: ``Cannot find module 'xterm-addon-fit' or its corresponding type declarations``

### ISSUE THREAD

**Issue by KiddoV** [xtermjs/xterm.js#4493]
## Details
- Browser and browser version: Webview2
- OS version: Windows 10
- xterm.js version: 5.1.0
- xterm-addon-fit: 0.7.0
<hr>

![fit-addon-error](https://user-images.githubusercontent.com/28552977/234345602-21d9fba0-bebc-430f-a032-389da8bb75e3.png)

I am confused why VSCode throwing this error. 
Next to the import you can clearly see the size of the file provided by the ``Import Cost`` extension, which mean I already installed the package correctly!
When I run the app, everything works fine. It is just annoying to see that error popup in a file.

Anyone know how to fix this issue, or maybe how do I turn that error message off?
Thanks,

**Comment by jerch** [comment]
This has nothing to do with xterm.js itself. Ask in vscode language support forums...
