### ISSUE TITLE
FitAddon  resizes incorrectly in other tabs when there are more than one tab

### ISSUE THREAD

**Issue by ZhouMM92** [xtermjs/xterm.js#4509]
I use el-tabs in my project. But when I open more than one terminal, the fitAddon  only works well in the current active tab(terminal), and the cols and rows of other tabs(terminals)  becomes very small.
The main codes are as follows:
1. html
```
    <el-tabs v-model="activeName">
      <el-tab-pane
        v-for="(item,index) in tabList"
        :key="item.name"
        :label="item.title"
        :index="index"
        :name="item.name"
      >
        <Term  />
      </el-tab-pane>
    </el-tabs>
```
2. js
```
window.addEventListener('resize',this.resizeXterm)
resizeXterm(){
console.log(`before fit , tabIndex=[${this.index}], cols=[${this.term.cols}],rows=[${this.term.rows}]`)
this.fitAddon.fit()
console.log(`after fit , tabIndex=[${this.index}], cols=[${this.term.cols}],rows=[${this.term.rows}]`)
this.websocket.send(ResizeJson)
}
```
and the result are as follows:
as you can see,there are two tabs, when I change the size of window, the cols and rows of current active tab auto changes ,but another‘s become very small.
![image](https://github.com/xtermjs/xterm.js/assets/101792358/735ef051-9238-4e8d-9184-6d3ec7847736)
![image](https://github.com/xtermjs/xterm.js/assets/101792358/a775724f-5b18-460c-b41f-3cbd6e5a66ea)

## Details
- Browser and browser version: Google Chrome  113.0.5672.92
- OS version: Windows 10 professional
- xterm.js version: 5.1.0
- xterm-addon-fit：0.7.0

So, what should I do to deal with this problem, I have puzzled for a very long time.

**Comment by ZhouMM92** [comment]
@jerch

**Comment by jerch** [comment]
Thats prolly an issue with your tab logic and thus not an xterm.js issue. No clue what "el-tabs" and "el-tab-pane" is about, or which framework it is. Maybe ask someone, who knows how to use these.
