### ISSUE TITLE
Measure character show up in the terminal

### ISSUE THREAD

**Issue by ziwangj** [xtermjs/xterm.js#4514]
The measureElement.textContent = 'W' show up in the terminal and override the other messages/characters.

## Details
- Browser and browser version:  chrome/firefox
- OS version: 13.1.1
- xterm.js version: 5.1.0

### Steps to reproduce

1. Render the terminal into a container 
2. The W character will show up and always stay in the place of first character. When mouse move to the place, it will show "W". Please see the attached screenshot for more details.
![Screenshot 2023-05-11 at 4 22 09 PM](https://github.com/xtermjs/xterm.js/assets/127142279/86c889b2-21a2-43e1-8d1b-e5ec3dc2e571)

**Comment by Tyriar** [comment]
I'm guessing you're missing the css file or it's out of date as it should be visibility hidden and also off screen:

https://github.com/Tyriar/xterm.js/blob/8c9e44c2191aa3b18b282eecb1d057b553658cf7/css/xterm.css#L119-L126
