### ISSUE TITLE
Hyperlink dotted underline disappears after hover leave

### ISSUE THREAD

**Issue by diamondburned** [xtermjs/xterm.js#4554]
## Details
- Browser and browser version: Firefox 113.0.2
- OS version: NixOS on https://github.com/NixOS/nixpkgs/tree/7409480d
- xterm.js version: 5.1.0

### Steps to reproduce

1. Write an OSC 8 Hyperlink into a non-WebGL terminal. Notice that there's a dotted underline underneath the link (WebGL terminals don't seem to have dotted underlines at all).
   ![image](https://github.com/xtermjs/xterm.js/assets/8463786/08b96b2e-38d1-4594-92a8-c1919719e7e0)
2. Hover over the link.
   ![image](https://github.com/xtermjs/xterm.js/assets/8463786/6af14138-07d8-4c69-a946-1e1a882787f7)
3. Move the mouse away. Notice that the dotted underline is gone.
   ![image](https://github.com/xtermjs/xterm.js/assets/8463786/9962899d-65d6-4a4b-870d-0167d7b59ccc)

<details>
<summary>Reproducing HTML</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="node_modules/xterm/css/xterm.css" />
    <script src="node_modules/xterm/lib/xterm.js"></script>
  </head>
  <body>
    <div id="terminal"></div>
    <script>
      var term = new Terminal();
      term.open(document.getElementById("terminal"));
      term.write(
        "\033]8;;http://example.com\033\\This is a link\033]8;;\033\\\n"
      );
    </script>
  </body>
</html>
```

</details>

**Comment by diamondburned** [comment]
Applying this diff should fix the issue:

```diff
diff --git a/src/browser/renderer/dom/DomRenderer.ts b/src/browser/renderer/dom/DomRenderer.ts
index 54711ed8..40450e2d 100644
--- a/src/browser/renderer/dom/DomRenderer.ts
+++ b/src/browser/renderer/dom/DomRenderer.ts
@@ -436,7 +436,7 @@ export class DomRenderer extends Disposable implements IRenderer {
       }
       const span = row.children[x] as HTMLElement;
       if (span) {
-        span.style.textDecoration = enabled ? 'underline' : 'none';
+        span.style.textDecoration = enabled ? 'underline' : '';
       }
       if (++x >= cols) {
         x = 0;
```

I haven't confirmed this yet, as I wasn't able to easily apply this fix for my project.

**Comment by jerch** [comment]
Confirmed, can repro in the demo.

It also seems, that your diff can fix it, not sure yet though, if it is the right patch. (Tbh - the logic looks strange to me...)
