### ISSUE TITLE
Possible race in DomRenderer: Cannot read properties of undefined (reading 'replaceChildren')

### ISSUE THREAD

**Issue by connor4312** [xtermjs/xterm.js#4556]
1. In VS Code OSS, check out 59d8f2bd9c6
2. Run a couple of unit tests, with the [selfhost test provider](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-selfhost-test-provider) for example, and open the TestResults view
3. Click on the two top-level test result nodes to switch terminals.
4. Notice you'll eventually get an error in the console. Her
e's the debug state, it looks like there might be an off-by-one error where `y` references a row element that does not yet exist

![image](https://github.com/xtermjs/xterm.js/assets/2230985/56f492af-9eb1-4189-9964-4c88cb8a9709)

**Comment by Tyriar** [comment]
We fixed a similar problem recently, we probably need to clamp start/end to ensure they're valid.
