### ISSUE TITLE
HTMLSerializeHandler does not work: Cannot read properties of undefined (reading 'colors')

### ISSUE THREAD

**Issue by connor4312** [xtermjs/xterm.js#4557]
1. Call serializeAddon.serializeAsHTML()
2. Observe the error `Cannot read properties of undefined (reading 'colors'): TypeError: Cannot read properties of undefined (reading 'colors')`

This seems to come from here, where `_core` appears to be a `CoreTerminal` which doesn't have a theme service.

https://github.com/xtermjs/xterm.js/blob/ac923e55d2f1f99342301d35acb5ae475b07f651/addons/xterm-addon-serialize/src/SerializeAddon.ts#L548-L549

**Comment by connor4312** [comment]
I had to open xterm in an element first for the themeService to be created.

**Comment by Tyriar** [comment]
At the very least we should add an exception with a good error when you call before open

**Comment by silamon** [comment]
I think this is more or less the same as #4148, which can be solved by reviewing #4348.

**Comment by Tyriar** [comment]
@silamon yes it is indeed, thanks
