### ISSUE TITLE
"Cannot read properties of undefined (reading 'getRasterizedGlyph')" when a target element is not displayed

### ISSUE THREAD

**Issue by schoonc** [xtermjs/xterm.js#4560]
After upgrading from `4.18.0` to `5.2.1`, if the mount point is not displayed (e.g. some parent has `display: none`), this causes an error and `xterm` crashes. In `4.18.0` this problem was not present.

## Details
- Browser and browser version: `Vivaldi 6.1.3035.50`
- OS version: `Ubuntu 23.04`
- xterm.js version: `5.2.1`

### Steps to reproduce

Code:

```html
<div style="display: none" id="target"></div>
```

```js
import { Terminal } from 'xterm'
import { CanvasAddon } from 'xterm-addon-canvas'

const terminal = new Terminal()
terminal.loadAddon(new CanvasAddon())
terminal.open(document.getElementById('target'))
```

Console output:
![image](https://github.com/xtermjs/xterm.js/assets/4659633/0ce22830-66df-441d-8fe1-f3ceefe3c013)

**Comment by JounQin** [comment]
Any schedule to fix this issue?

I noticed there are also several `_charAtlas?.` usage, can we just add `if (!this._charAtlas) { return }`? (Sorry I'm not familiar with the source codes)

**Comment by AndreSilva1993** [comment]
Will this be released? This issue is the only thing blocking me to upgrade since it breaks our automated tests.

**Comment by Tyriar** [comment]
@AndreSilva1993 you can use the latest beta build which is released on every commit, VS Code is periodically updated to the latest beta
