### ISSUE TITLE
Scrolling performance - DomRenderer

### ISSUE THREAD

**Issue by robertthemay** [xtermjs/xterm.js#4562]
Any chance of moving "replaceChildren" outside of the loop to reduce DOM reflows?

https://github.com/xtermjs/xterm.js/blob/ac923e55d2f1f99342301d35acb5ae475b07f651/src/browser/renderer/dom/DomRenderer.ts#L366-L381

I'm getting very laggy performance when scrolling 45 rows on my 2017 laptop. I assume it's because each scroll(up/down of mouse wheel) causes 45 DOM reflows.

Laptop specs
-Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz   2.90 GHz
-16GB RAM
-HD620 Graphics

**Comment by Tyriar** [comment]
I wouldn't expect that to make a difference as I don't think we force a reflow between `replaceChildren` calls? I might be missing something.

Scrolling will also be inferior to the GPU powered renders which is why they exist.
