### ISSUE TITLE
Add cursorStyleInactive option

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4566]
Follow up to https://github.com/xtermjs/xterm.js/pull/4443

Since we reverted how it used to be (which I still think is the right default), some embedders/users may want it the old way still. We can solve this for everyone by adding a `cursorInactiveStyle` as suggested by @boettges in https://github.com/xtermjs/xterm.js/pull/4443#issuecomment-1595056304. The name `cursorInactiveStyle` aligns with `selectionInactiveBackground`

To implement this you would need to:

1. Add the new option to xterm.d.ts, options service, etc.
2. Implement it for dom, canvas and webgl renderers

**Comment by tisilent** [comment]
try try

**Comment by tisilent** [comment]
Oh, my! Not implementing selectionInactiveBackground..

**Comment by Tyriar** [comment]
@tisilent no need to touch the selection ones, they are just used as an example to ensure we're following the right naming style:

selection**Inactive**Background and cursor**Inactive**Style
