### ISSUE TITLE
Recent mcedit looks wrong in xtermjs, but OK in gnome-terminal

### ISSUE THREAD

**Issue by socketpair** [xtermjs/xterm.js#4579]
I tried both `TERM=xterm` and `TERM=xterm-color`.

xtermsj 5.0.0

`mcedit` looks like this:

![image](https://github.com/xtermjs/xterm.js/assets/1157412/18b222af-14a6-4e54-b970-e96fa5a9a6a5)

There should not be any black stripes, everything should be filled with blue background. In gnome-terminal it looks fine.

Tell me how to debug. I use websocket in order to connect to PTY.

**Comment by jerch** [comment]
Should be fixed with #4438.

**Comment by socketpair** [comment]
in version 5.2
