### ISSUE TITLE
reset() not finished on sync return

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#4603]
coming from https://github.com/xtermjs/xterm.js/discussions/4319#discussioncomment-6508416 - the `Terminal.reset` call does not finish the re-initialization synchronous.

possible fixes:
Either make it a promise (rather a quickfix and with ugly API change), or revisit the code paths, that are not ready yet when returning synchronously from the method and execute them in sync.

**Comment by Tyriar** [comment]
This is surprising, it was always meant to be sync so hopefully we can fix it.

**Comment by Tyriar** [comment]
clear too? 😕 https://github.com/xtermjs/xterm.js/discussions/4319#discussioncomment-6510734

This isn't just a re-rendering problem is it?

**Comment by jerch** [comment]
> This isn't just a re-rendering problem is it?

Haven't looked into it yet, I'd say yes - its a re-rendering issue with false scrollOffset from viewport.ts (prolly due to using an animation frame there, its just a guess though atm).

**Comment by Tyriar** [comment]
Repro: run this in console `term.reset(); term.write('1\n2\n3\n\r'.repeat(20));`
