### ISSUE TITLE
Flaky test: image lifecycle & eviction evict tiles by in-place overwrites (only full overwrite tested)

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4627]
Flaky on Firefox

https://dev.azure.com/xtermjs/xterm.js/_build/results?buildId=6472&view=logs&j=7e83d574-455f-504f-88a8-4540cd90aeb9&t=c2189d91-6135-52f2-96dd-ee230b3908c0
https://dev.azure.com/xtermjs/xterm.js/_build/results?buildId=6470&view=logs&j=7e83d574-455f-504f-88a8-4540cd90aeb9&t=c2189d91-6135-52f2-96dd-ee230b3908c0

```
  1) ImageAddon
       image lifecycle & eviction
         evict tiles by in-place overwrites (only full overwrite tested):
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\addons\xterm-addon-image\out-test\ImageAddon.api.js)
      at listOnTimeout (node:internal/timers:569:17)
      at processTimers (node:internal/timers:512:7)
```

**Comment by jerch** [comment]
Roughly halved the data load in these tests, which should keep them working longer on low resources.

**Comment by jerch** [comment]
Well both tests cannot be split, as they test the storage usage, which is only valid in one go (terminal + addon instances may not change).
