### ISSUE TITLE
Search matchBackground isn't working in dom renderer

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4642]
Repro:

Set matchBackground in client.ts to `#ff0000` and use the search addon to find something with multiple matches.

Webgl:

<img width="385" alt="Screenshot 2023-08-04 at 8 29 12 am" src="https://github.com/xtermjs/xterm.js/assets/2193314/842f67b6-a03b-4f7f-b63f-6db3753f284c">

DOM:

<img width="237" alt="Screenshot 2023-08-04 at 8 30 00 am" src="https://github.com/xtermjs/xterm.js/assets/2193314/1b7f7c23-202d-48ed-af20-0efd11cc2147">

**Comment by Tyriar** [comment]
@jerch this was due to the fast DOM renderer change, see https://github.com/microsoft/vscode/issues/189600 for more info on the bug.

Pretty sure it's caused by merging cells before the decoration color is resolved as the bg and fg (not border) are rendered as part of the regular grid:

https://github.com/xtermjs/xterm.js/blob/18e578bd09af31ca3ba76467b8c22469e963b36f/src/browser/renderer/dom/DomRendererRowFactory.ts#L214-L234

**Comment by Tyriar** [comment]
Another result of this:

Webgl:

<img width="358" alt="Screenshot 2023-08-04 at 9 04 23 am" src="https://github.com/xtermjs/xterm.js/assets/2193314/5e99e085-f2de-4555-a140-016ea9cbc576">

DOM:

<img width="377" alt="Screenshot 2023-08-04 at 9 05 20 am" src="https://github.com/xtermjs/xterm.js/assets/2193314/1ce8bb05-40b5-44ce-bca1-5a34dd36d713">

**Comment by jerch** [comment]
Yeah, seems this needs an exclusion from the merger.

**Comment by jerch** [comment]
@Tyriar Is there an easy way to test/repro this? Whats the desired behavior here?

**Comment by Tyriar** [comment]
@jerch setting `matchBackground` to something obvious in client.ts and then use the find previous textbox/button. Was pretty easy to repro for me. Only the search term should be highlighted, in this one only the `t` cells should have red backgrounds:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/49888f57-ecb3-46d1-8b46-28aabafca6c0)
