### ISSUE TITLE
API facades leak memory

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4645]
We need to make `BufferNamespaceApi` a disposable and register the events:

https://github.com/xtermjs/xterm.js/blob/c3def09c386f805b9a1127364a587cde8561abea/src/common/public/BufferNamespaceApi.ts#L15-L16

**Comment by jerch** [comment]
Eww, yeah the `BufferNamespaceApi` always felt like being a subject for mem leaks due its permanent re-creating of the api instance. Whats the exact object leaking here, is it the whole api instance or just a particular sub-object bound by an action?

**Comment by Tyriar** [comment]
If the embedder listens to the events they must be disposed by the embedder or xterm can get leaked by them. We just need to make it a disposable and register it
