### ISSUE TITLE
Support emoji IMEs

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#469]
Currently inputting emojis doesn't work on all platforms (via mac: cmd+ctrl+space, windows: win+.).

Context: https://github.com/zeit/hyper/issues/1275#issuecomment-271679999
VS Code: https://github.com/Microsoft/vscode/issues/35266

Related: https://github.com/sourcelair/xterm.js/issues/467

**Comment by parisk** [comment]
👍  I'll give this a try, because I love adding emojis in my squash messages.

**Comment by rauchg** [comment]
@parisk the technique we use in Hyper (might be useful for you) is to place the contenteditable inside the actual caret, so that its position remains relevant.

**Comment by Tyriar** [comment]
Yes we do something similar with our textarea. @parisk let me know if you need help understanding the `CompositionHelper`, there are two issues with it AFAIK: https://github.com/sourcelair/xterm.js/issues/273 https://github.com/Microsoft/vscode/issues/11334

**Comment by rauchg** [comment]
> One way this issue could be fixed is by no longer hiding the textarea offscreen and instead keeping it in sync with the cursor

In our case I believe we always have it _inside_ the caret div, so no reposition is needed. @matheuss can confirm

**Comment by Tyriar** [comment]
Our caret is an actual character on screen which may also contain text and it's reconstructed whenever the prompt line is refreshed.

**Comment by matheuss** [comment]
Yeah @rauchg, we always have our own `contenteditable` inside the `hterm`'s carret (which is a floating `div` that happens to be _above_ the terminal).

**Comment by parisk** [comment]
I think that we the best option for us is moving the hidden textarea to the caret's position on every stroke (similar to CodeMirror's mechanism for the hidden textarea).

What we have to investigate though is why the character is not being inserted in the terminal when click. I guess it's a focus issue, but I will get on top of it within the weekend to tell for sure.

**Comment by Tyriar** [comment]
The reason we're not getting the emoji is because we don't listen to the `input` event. So I guess we need to listen to that to get the changes. We may want to consider reevaluating `keypress`/`keydown` if we're also listening to `input`.

**Comment by parisk** [comment]
You mean ditching keypress/keydown completely for `input` or using it supplementary to the typical keyboard events?

**Comment by Tyriar** [comment]
Not sure yet, maybe we don't need keydown anymore? I've also been told that the input eventis needed to respect repeating chars when holding down a key on macOS.

**Comment by epicfaace** [comment]
The only way I see to do this is to handle the `input` event and grab the `data` attribute of the event object, which then gives you the emoji, such as "😄".

However, Firefox doesn't support the `data` attribute, so I guess we're stuck on that front.

On the other hand, only in Firefox (Mac OS X) I am able to input emojis normally, but only half of the emoji shows up:

![2019-01-06 16 14 01](https://user-images.githubusercontent.com/1689183/50743546-2993d480-11ce-11e9-9426-ea5ecfd48739.gif)



Not sure how this is happening. Any thoughts?

**Comment by Tyriar** [comment]
@juancampa has it working on Hyper's fork, should be an incoming PR soon.

**Comment by minvedacat** [comment]
@Tyriar I believe they are 2 issues:
1. emoji IME input in not handled properly, which #1890 should fix it
2. emoji width is not calculated properly as @epicfaace mentioned, which seems to be unicode related

**Comment by minvedacat** [comment]
#1951

**Comment by ShlomiRex** [comment]
> The only way I see to do this is to handle the `input` event and grab the `data` attribute of the event object, which then gives you the emoji, such as "😄".
> 
> However, Firefox doesn't support the `data` attribute, so I guess we're stuck on that front.
> 
> On the other hand, only in Firefox (Mac OS X) I am able to input emojis normally, but only half of the emoji shows up:
> 
> ![2019-01-06 16 14 01](https://user-images.githubusercontent.com/1689183/50743546-2993d480-11ce-11e9-9426-ea5ecfd48739.gif)
> 
> Not sure how this is happening. Any thoughts?

What project is this? (gif u sent)
Can I view the code please? <3

**Comment by LabhanshAgrawal** [comment]
@Tyriar this got broken in #3535 
Tested on the demo, chrome 97, macOS 11.6.2

**Comment by Tyriar** [comment]
@LabhanshAgrawal could you create a new issue with a gif/screenshot of the new problem?

**Comment by LabhanshAgrawal** [comment]
> @LabhanshAgrawal could you create a new issue with a gif/screenshot of the new problem?

done #3629
