### ISSUE TITLE
Set addon package.json repository to sub-folder containing the addon

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4705]
Context: https://github.com/xtermjs/xterm.js/pull/4519#discussion_r1299174684

eg. this should point at https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-fit

https://github.com/xtermjs/xterm.js/blob/6f0a5c9f0c1ad3e25ae3cf62f758ac99695a7210/addons/xterm-addon-fit/package.json#L10

**Comment by ujjwalpandey922** [comment]
Hi Can I do this ???
Let me know the steps for it as well. I am new to open source
Thanks

**Comment by Tyriar** [comment]
@ujjwalpandey922 this one's just a matter of going through each of the addon's package.json files and changing the repository URL to that location on github (eg. `https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-fit`), instead of the root of the repository (`https://github.com/xtermjs/xterm.js`).
