### ISSUE TITLE
Reuse the empty character structure to save memory and processing time

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#472]
Right now on resize the line is filled with "empty" characters which pad the row, these are then cut from the row if the resize reduces columns.

A better way to handle this would be to have a single "padding" char which is not added to the rows but instead used to fill in the rows if a row's size is less than `Terminal.cols`.

**Comment by parisk** [comment]
What do you propose the "padding" char structure to be? (e.g. a dynamically sized div)

I suspect that flexbox could be useful here.

**Comment by Tyriar** [comment]
I think the structure should stay the same, just not create so many nbsp character arrays.

**Comment by parisk** [comment]
Could this mess with applications running in application mode where the cursor can be in position that looks "empty" (and consequently would be occupied by the padding character)?

**Comment by Tyriar** [comment]
Would have to test it but the idea would be to always assume rows are `this.cols` in length and if it's not found, assume it's the empty character. If you have a good test case for your concern let me know.

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
