### ISSUE TITLE
Inactive selection background is drawn _below_ cell background color

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4736]
Repro:

1. Set inactive selection bg to an opaque color
2. Select text
3. Unfocus terminal

![Image](https://github.com/xtermjs/xterm.js/assets/2193314/c452aa1d-8188-45cf-a27d-b44da84d29ab)

**Comment by tisilent** [comment]
Unable to reproduce, perhaps #4763 has also fixed this issue??

**Comment by Tyriar** [comment]
@tisilent a regression test would be good for this if you want to give it a shot

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/4808
