### ISSUE TITLE
Green artifact with allowTransparency

### ISSUE THREAD

**Issue by SquitchYT** [xtermjs/xterm.js#4749]
## Details
- Webview: WebKit
- OS version: Linux
- xterm.js version: 5.0.0

### Steps to reproduce

1. Enable the `allowTransparency` option.

It's seem that term tries to adjust text color when enabling `allowTransparency`.

This is the current result
![Screenshot_20230906_141458](https://github.com/xtermjs/xterm.js/assets/63391793/150f1072-0a06-468a-ad68-31367af644f0)
and this is the expected result (here, achieved by setting `allowTransparency` to false)
![Screenshot_20230906_141546](https://github.com/xtermjs/xterm.js/assets/63391793/2ac99187-d7cf-49b7-8d14-c751b818b678)

Is there any way to disable this?

**Comment by Tyriar** [comment]
@SquitchYT do you know what renderer this is using (dom, canvas, webgl)? And was the `allowTransparency` change done in the initial options to passed to the constructor or via `Terminal.options`?

Also can you try with the updated version?

**Comment by SquitchYT** [comment]
I'm using the canvas renderer. The option is set in the initial options, without any change after that. 

I've already tried with a newer version, and there is still the same issue.

Also, this doesn't happen on Windows.

**Comment by SquitchYT** [comment]
@Tyriar Hello
Have you any advice to try to resolve this problem?

**Comment by Tyriar** [comment]
@SquitchYT if this doesn't happen with the dom/webgl renderers I'd recommend using them. After the upcoming DOM renderer improvements we're considering removing the canvas rendering completely again.

**Comment by SquitchYT** [comment]
@Tyriar After some investigations. It seems that this is not related to Xterm.JS, but to the webview itself. I'm using Tauri which (with WeKit) that apparently have rendering issues of canvas using alpha value.

**Comment by Tyriar** [comment]
@SquitchYT good to know, thanks. For things like this in VS Code we just recommend turning off gpu acceleration (ie. using the DOM renderer) https://code.visualstudio.com/docs/terminal/appearance#_gpu-acceleration
