### ISSUE TITLE
Webgl/canvas inverse resolves minimum contrast color using the default background, not the inverse

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4752]
Actual

minimumContrastRatio = 12
webgl/canvas

![Image](https://github.com/xtermjs/xterm.js/assets/2193314/e20b3393-1a1c-42b0-b9fe-e9ac68896eb9)

Expected (dom)

![Image](https://github.com/xtermjs/xterm.js/assets/2193314/e4966e44-234b-4e9f-a533-ae277585d5dd)

**Comment by tisilent** [comment]
I tried, but now I can't tell which one is correct.:joy:

**Comment by Tyriar** [comment]
It does get a little confusing doing these types of issues. If minimum contrast ratio is 12 the text should be very visible, understanding these often involves tweaking the background and fg colors a bunch

**Comment by Tyriar** [comment]
Seems fixed 🤷
