### ISSUE TITLE
image addon packaging not working

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#4761]
See https://github.com/xtermjs/xterm.js/pull/4756.

**Comment by Tyriar** [comment]
A way for you to test this in CI is to change this line to `publish.js --dry-run`:

https://github.com/Tyriar/xterm.js/blob/ebd27de4e1a3e617a9e6c7668bed77fb4267d30e/.github/workflows/release.yml#L30

And trigger it in PR by adding this:

```yml
  pull_request:
    branches: [ "master" ]
```

Here:

https://github.com/Tyriar/xterm.js/blob/ebd27de4e1a3e617a9e6c7668bed77fb4267d30e/.github/workflows/release.yml#L7
