### ISSUE TITLE
The content of the DOM renderer is lost or garbled after resizing.

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4765]
![企业微信截图_16941712761829](https://github.com/xtermjs/xterm.js/assets/48614781/310b08b6-a911-4c40-8a7a-4c6002fe7130)

**Comment by Tyriar** [comment]
This might just be a Windows thing, to double check can you run `wsl` and check with output in there? (installing WSL if needed)

**Comment by tisilent** [comment]
I'll check the cause.

**Comment by Tyriar** [comment]
Closing as it's likely windows/conpty
