### ISSUE TITLE
Domrender not using isCursorInitialized

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4790]
on vscode
step:
1. using webgl render
2. create new terminal
3. reload window
terminal do not display cursor

step:
1. using dom render
2. create new terminal
3. reload window
terminal display cursor

**Comment by tisilent** [comment]
I'm not sure that kind of behavior is correct.

**Comment by Tyriar** [comment]
Yep the cursor is not meant to show at all until it's focused. We should be able to craft a regression test that covers this too 👍
