### ISSUE TITLE
Abnormal `load test` for demo

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4791]
![1694522927915](https://github.com/xtermjs/xterm.js/assets/48614781/cd2840f7-9330-4904-814a-fe417440bc98)

**Comment by Tyriar** [comment]
This is expected similar to https://github.com/xtermjs/xterm.js/issues/4765 because conpty which emulates ptys on Windows holds its own view of the viewport and reprints/positions the cursor absolute often. The load test button just writes to the terminal, so conpty doesn't know about it.
