### ISSUE TITLE
DomRenderer Changes when selecting underline content

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4794]
https://github.com/xtermjs/xterm.js/assets/48614781/bbd5ed82-6fba-4f93-a9cc-7207756457d5

**Comment by Tyriar** [comment]
Would have thought this sort of thing would only happen when https://github.com/xtermjs/xterm.js/pull/4703 gets merged 😕

**Comment by tisilent** [comment]
Yes.At the beginning, #4703 occurred.when using the wrong variant. :triumph:

**Comment by Tyriar** [comment]
@jerch ah right, that makes sense. So it's the browser deciding this is how it should render and is actually a bug there if anything. Shall we close?

**Comment by tisilent** [comment]
Chromium wavy lines. 😀
