### ISSUE TITLE
Unable to build xterm-addon-image : Can't resolve 'common/Lifecycle'

### ISSUE THREAD

**Issue by guimard** [xtermjs/xterm.js#4802]
## Details
- OS version: Debian testing
- xterm.js version: 5.3.0

### Steps to reproduce

1. yarn install
2. npm run install-addons
3. npm run build
4. cd addons/xterm-addon-image
5. npm run package

This produces an error:
```
ERROR in ./out/ImageRenderer.js 9:20-47
Module not found: Error: Can't resolve 'common/Lifecycle' in '/home/yadd/dev/debian/src/pkg-js/packages/node-xterm/addons/xterm-addon-image/out'
resolve 'common/Lifecycle' in '/home/yadd/dev/debian/src/pkg-js/packages/node-xterm/addons/xterm-addon-image/out'
```

node_modules/common is installed with the good version (0.2.5) and doesn't export any `common/Lifecycle`

**Comment by Tyriar** [comment]
Looks like it's missing the equivalent of this:

https://github.com/xtermjs/xterm.js/blob/32c616512d428cb392badfcde7d7ee69b37bfb94/addons/xterm-addon-webgl/webpack.config.js#L24-L31

**Comment by Tyriar** [comment]
@jerch the way the build currently works is tsc builds using the aliases but does not modify them:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/6a519b50-cf6c-41c2-b429-89afd30c7c60)

That is then handed off to webpack which also needs to know how to resolve the aliases in order to bundle. You are actually using non-types as I see `Disposable` is being used, this is fine it just needs webpack to know about it.

**Comment by jerch** [comment]
> ... I see Disposable is being used ...

Huch? I took extra rounds not to import any code from base repo (was not really possible in the separate repo), where does that comes from? (Sorry dont have time to look at it atm....)

**Comment by Tyriar** [comment]
Here it is:

https://github.com/xtermjs/xterm.js/blob/1618092b91f561ab860db2770f3cf13fbaabc3df/addons/xterm-addon-image/src/ImageRenderer.ts#L9

I probably added it since I added `MutableDisposable` too since we've been looking into leaked disposables/memory recently in vscode.

**Comment by jerch** [comment]
Yeah seems related to the MutableDisposable change. Sorry, that kinda went unnoticed for me.

**Comment by Tyriar** [comment]
I was very sneaky 😉

**Comment by jerch** [comment]
@Tyriar Sorry I dont quite understand that code change (in particular the control flow behind it). What issue does it solve? Preventing double dispose?

**Comment by Tyriar** [comment]
In https://github.com/xtermjs/xterm.js/pull/4733, `MutableDisposable` helps prevent the pattern you need separately create a disposable and dispose it. It's mainly to catch accidentally not disposing when the disposable may be `undefined`. So instead of this:

```ts
class BaseRenderLayer {
  private _charAtlasDisposable?: IDisposable;

  // ...

  _refreshCharAtlas() {
    // Need to remember to do this or it's leaked
    this._charAtlasDisposable?.dispose();
    this._charAtlasDisposable = ...
  }

  // ! It's also meant to be in dispose but this was a real disposable leak fixed in the PR
}
```

It becomes:

```ts
class BaseRenderLayer {
  // Initialization and dispose in same line
  private _charAtlasDisposable = this._register(new MutableDisposable();

  // ...

  _refreshCharAtlas() {
    // Setting value will automatically dispose the old one
    this._charAtlasDisposable.value = ...
  }

  // ! It's also meant to be in dispose but this was a real disposable leak
}
```

**Comment by jerch** [comment]
@Tyriar Ah ok, thx for the explanation. Will have another look at it.

**Comment by tisilent** [comment]
@Tyriar Previously, I discovered some insignificant memory leaks in vscode terminal.
I'll go see if it's fixed.

**Comment by Tyriar** [comment]
@tisilent thanks, we've been having a big push to plug up memory leaks this month. We have a handy helper now that tracks disposables that don't get disposed in unit tests https://github.com/microsoft/vscode/issues/190503
