### ISSUE TITLE
Webgl  renderer: context lost

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4804]
![image](https://github.com/xtermjs/xterm.js/assets/48614781/3aef6914-8000-46a6-b9a5-f49d07b15c81)
(Toggle Developer Tools)

 after completion yarn run test-api.
 When scrolling through the results in Terminal, the screen is black and Terminal is white But the selected line shows the content. It works normally after standby startup.

**Comment by Tyriar** [comment]
@tisilent doesn't the browser close after `yarn run test-api`? But confused how you get to the console

**Comment by tisilent** [comment]
Running in vs code.

**Comment by tisilent** [comment]
@Tyriar @jerch I have found the reason.
graphics drivers! :worried:
![1694699678633](https://github.com/xtermjs/xterm.js/assets/48614781/56a3672e-66cc-4bd3-90f5-45b406b8c9ef)
`The monitor driver igfx has stopped responding and has successfully recovered.`

**Comment by jerch** [comment]
> graphics drivers! 😟

Oh dear, not again. Not sure if you want to get again into the chromium graphics debugging nightmare, to narrow things down:
- Does this also happen with `yarn test-api-firefox`?
- You can also test with an older playwright version (would ship older chromium version).

**Comment by tisilent** [comment]
I have found the reason this time. The probability of this problem occurring should be very, very low.
And the 'webglcontextrestored' event was successfully executed. It was restored, but it seems that_ RequestRedrawViewport did not effect. Looking back now. 🤔

**Comment by tisilent** [comment]
![image](https://github.com/xtermjs/xterm.js/assets/48614781/7e63efc2-26a7-48a7-b4f7-a7036478a2f2)
It appeared today, and the term was initially a fork icon, then returned to normal. `webglcontextrestored` take effect。

**Comment by tisilent** [comment]
@Tyriar This may not be a problem. 😬 
I think we can close the issue.
