### ISSUE TITLE
WidthCache causing horizontal overflow (scrolling)

### ISSUE THREAD

**Issue by Linux123123** [xtermjs/xterm.js#4805]
WidthCache, which is placed on the body, messes with overflows and makes a horizontal scrollbar for `50000px`. There is no way to make it not overflow and hiding it breaks the spacing entirely.

## Details
- Browser and browser version: Firefox 117.0 and Chrome 116.0.5845.179
- OS version: Linux / Windows
- xterm.js version: 
```
"xterm": "5.3.0",
"xterm-addon-fit": "0.8.0",
"xterm-addon-search": "0.13.0",
"xterm-addon-search-bar": "0.2.0",
"xterm-addon-web-links": "0.9.0",
 ```

### Steps to reproduce

1. Add a new console in a react application
2. (Not sure if changes anything) Add these options
```
const theme: ITheme = {
    background: '#21212C',
    cursor: '#21212C',
    black: '#000000',
    red: '#E54B4B',
    green: '#9ECE58',
    yellow: '#FAED70',
    blue: '#396FE2',
    magenta: '#BB80B3',
    cyan: '#2DDAFD',
    white: '#d0d0d0',
    brightBlack: 'rgba(255, 255, 255, 0.2)',
    brightRed: '#FF5370',
    brightGreen: '#C3E88D',
    brightYellow: '#FFCB6B',
    brightBlue: '#82AAFF',
    brightMagenta: '#C792EA',
    brightCyan: '#89DDFF',
    brightWhite: '#ffffff',
    selectionBackground: '#FAF089',
};

const terminalProps: ITerminalOptions = {
    disableStdin: true,
    cursorStyle: 'underline',
    allowTransparency: true,
    fontSize: 12,
    fontFamily: 'Menlo, Monaco, Consolas, monospace',
    theme: theme,
    allowProposedApi: true,
};
```
3. Observe that you can scroll `50000px` to the right, only when console loads up. Before console loading scrolling behaves normally.

**Comment by Tyriar** [comment]
Can't repro on Windows/Edge

**Comment by Linux123123** [comment]
https://codesandbox.io/p/sandbox/adoring-tdd-7nlnck?file=%2Fsrc%2FApp.tsx%3A91%2C10
Here is a (not so) minimal reproduction

While editing it became apparent that it only happens if body is set to `position: relative`. My believe is that changing `css` for things not related with `xterm` shouldn't make unwanted side effects.

**Comment by Tyriar** [comment]
@Linux123123 thanks, that's helpful!

**Comment by jerch** [comment]
Hmm I took that the measuring setup from monaco. Should we move the elements under the terminal main element? Note that this kinda defeats the idea, to be able to have a single measuring instance later on for multiple terminal instances, as then every terminal would have to repeat the measuring itself.

**Comment by Tyriar** [comment]
We could keep the single element but it's just hosted in _some_ terminal instance? We don't think we touch elements outside `Terminal.element` anywhere else.

**Comment by jerch** [comment]
> We could keep the single element but it's just hosted in _some_ terminal instance? We don't think we touch elements outside `Terminal.element` anywhere else.

Hmm, doesnt that create more fuzz around dispose, e.g. what happens, if the terminal the `WidthCache` is attached to, gets disposed? To me this sounds like creating even more headache, than simply clamping the measuring to a terminal instance individually (well maybe its just me overcomplicating things here).

**Comment by Tyriar** [comment]
@jerch you could just check whether it's detached before using the element? It was a nice thing we were doing not cluttering body with children as opposed to being completely self contained.

**Comment by jerch** [comment]
Well the single instance measuring isnt there yet, what sould work with such an impl is to give it a `registerTerminal` method, where it can deduct the DOM elements to do its measuring under. Then it just needs a disposed check and some ref mapping. Also once all terminals got disposed, it could prolly also empty its caching structures. Something along these lines prolly would work.
