### ISSUE TITLE
WidthCache is added document.body, it should be a child of .xterm-helpers ideally

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4806]
This could cause issues depending on styles differ between the terminal element and `body`

https://github.com/xtermjs/xterm.js/blob/32c616512d428cb392badfcde7d7ee69b37bfb94/src/browser/renderer/dom/WidthCache.ts#L77

**Comment by jerch** [comment]
Also see comment here https://github.com/xtermjs/xterm.js/issues/4805#issuecomment-1720065639
