### ISSUE TITLE
link loss

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4812]
https://github.com/xtermjs/xterm.js/assets/48614781/12297d81-fbfb-4c65-bf34-5ff7245c03f0

In the first and last lines, relative to the viewport.
Loss may occur

**Comment by tisilent** [comment]
DOM renderer and Webgl renderer

**Comment by jerch** [comment]
There are some issues with the linkifier, also see  #4296.

**Comment by tisilent** [comment]
Emmm, just discovered that webgl renderer also uses `ILinkifier2`.

**Comment by Tyriar** [comment]
This might also be a problem in vscode. I know there are some hard to repro issues with link lifecycle

**Comment by Tyriar** [comment]
Closing as stale, I know I fixed a big class of problems like this within the last year
