### ISSUE TITLE
Links get re-evaluated when buffer changes happen outside viewport

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4814]
Repro:

1. Run ls to fill viewport
2. Open vscode repo in terminal
3. Echo a url
4. Run ./scripts/test
5. Scroll up while that's running and hover the url, the underline will flicker

---

The issue is confusion between requesting re-rendering of dirty rows relative to `ybase`:

https://github.com/xtermjs/xterm.js/blob/1618092b91f561ab860db2770f3cf13fbaabc3df/src/common/InputHandler.ts#L498-L499

Then incorrectly firing onRenderedViewportChange incorrectly even when the viewport isn't re-rendered when scrolled up:

https://github.com/xtermjs/xterm.js/blob/1618092b91f561ab860db2770f3cf13fbaabc3df/src/browser/services/RenderService.ts#L169-L171

And assuming that the event is relative to `ydisp`:

https://github.com/xtermjs/xterm.js/blob/1618092b91f561ab860db2770f3cf13fbaabc3df/src/browser/Linkifier2.ts#L323-L331

**Comment by jerch** [comment]
@Tyriar Wow, nice find. Could this also be the reason for the selection events being fired over and over while input flows, even there is no active selection?

**Comment by tisilent** [comment]
Links in tests.....
![无标题123](https://github.com/xtermjs/xterm.js/assets/48614781/90425d03-89bc-4ba7-811b-ee1ba9542ca0)

**Comment by tisilent** [comment]
https://github.com/xtermjs/xterm.js/assets/48614781/c444a5d0-457d-4744-9c73-a900cdf5aa46

Flashing like this.

**Comment by Tyriar** [comment]
There seems to be a bigger problem here where we often render when nothing happens just from input that was written below. `Terminal.refresh` is called for the viewport (relative to ydisp), but often (not always) the intent is to refresh the bottom viewport only.

**Comment by Tyriar** [comment]
@tisilent that's probably some Windows-only wrapping/reflow issue.

**Comment by Tyriar** [comment]
@jerch yeah probably
