### ISSUE TITLE
xterm-addon-search: case sensitive abnormal  behavior

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4822]
https://github.com/xtermjs/xterm.js/assets/48614781/75625457-965a-4812-94d8-81e7e69d52e8

I will fix it next week.

**Comment by Tyriar** [comment]
Not clear if the issue is in the search addon or just the demo from the gif.

**Comment by tisilent** [comment]
There are several related issues.
![123](https://github.com/xtermjs/xterm.js/assets/48614781/b3c8593b-807e-4d31-8e61-b0f7d52e2e49)
1. Enter lowercase s
2. Exec Find previous
3. Enter uppercase s
4. Checked case sensitive
5. Exec Find previous

issues:
1. result count
2. lowercase s is still highlighted
