### ISSUE TITLE
Certain Nerd Font icons cause other UTF-8 codes to render as whitespace

### ISSUE THREAD

**Issue by EyesofBucket** [xtermjs/xterm.js#4834]
The ANSI code for resetting terminal color (1b5b306d) seems to render as a whitespace character when preceded by the Red Hat nerd font icon (f3b1849b) anywhere on the line.  The Windows nerd font icon (ee98aa) does not cause this issue.  This seems to be specific to Windows, as it does not appear in VSCode or GoTTY on NixOS 23.05.

I have written a simple Python script to demonstrate the issue:
```python
def hextest(hex_str):
    byte_seq = bytes.fromhex(hex_str)
    utf8_str = byte_seq.decode('utf-8')
    
    print(hex_str)
    print(utf8_str)

# a<windows>aa
hextest('61ee98aa6161')

# a<redhat>aa
hextest('61f3b1849b6161')

# a<windows>a<reset>a
hextest('61ee98aa611b5b306d61')

# a<redhat>a<reset>a
hextest('61f3b1849b616263640d0a651b5b306d61')

# a<redhat>abcde<reset>a
hextest('61f3b1849b61626364651b5b306d61')

# a<redhat>abcd<cr><lf>e<reset>a
hextest('61f3b1849b616263640d0a651b5b306d61')
```
The expected result would be something like what the Windows Terminal outputs:
![image](https://github.com/xtermjs/xterm.js/assets/48115604/b98d1f5e-e12c-46ea-a1a9-b493533532b4)
(Windows Terminal also had this issue a while ago but has since fixed it, otherwise I would've thought this was just a Microsoft thing as so many things often are 😋)

But xterm.js-based applications such as Hyper or VSCode Integrated Terminal (pictured below) add the whitespaces:
![image](https://github.com/xtermjs/xterm.js/assets/48115604/acf261fc-2e08-4b61-9eeb-d3c34b73ab23)

Running the xterm.js demo from a fresh git clone, ignoring the missing nerd font icons, the whitespace is still rendered:
![image](https://github.com/xtermjs/xterm.js/assets/48115604/bcea70bd-c476-4ed1-a938-8c9f58f46ff9)

Note the result of the last test in the script, and how adding a CLRF causes the whitespace to not be rendered between 'e' and 'a' on the next line.

I went ahead and tested using VSCode and GoTTY on NixOS 23.05 as mentioned earlier, and no whitespaces were rendered just like the Windows Terminal results above. No issues on Linux as far as I can tell.

It should also be noted that the icons overlapping the following text is expected behavior, at least to me, and provides the ability to manually add whitespace when needed while keeping things properly aligned.
## Details
- Browser and browser version: Firefox 118.0.1, VSCode 1.82.2 (Chromium 114.0.5735.289), Hyper 3.4.1
- OS version: Windows 10/11 21H2
- xterm.js version: HEAD (demo)

### Steps to reproduce
1. Run the Python script above in the xterm.js demo on Windows.

**Comment by jerch** [comment]
@EyesofBucket Is this a windows only issue? Or even a powershell only issue? Sorry did not quite get that from your description :sweat_smile:

**Comment by Tyriar** [comment]
This looks a little different on my machine:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/705c2c10-e879-4750-b0ce-8bdf3fe824f2)

And WT:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/d952cd36-67a3-48b2-a8aa-6b9c00142162)

---

Looking at the xterm.js one, this is what conpty is handing off to us:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/7072ec6e-01cb-4718-a03e-ce2ac80183bf)

So it looks like we're doing the right thing and moving the cursor forward 1 position. I'm guessing this is a conpty issue that is different in WT since conpty is bundled and xterm.js/vscode relies on the version built into Windows.

**Comment by microhobby** [comment]
@Tyriar so, we should not use Windows?

**Comment by microhobby** [comment]
@Tyriar is possible to bundle the ConPTY, like WT does, on xterm.js?

**Comment by jerch** [comment]
@microhobby Nope, thats not possible. xterm.js is a JS-frontend lib, which is far far away from OS related things.

You might have better luck to ask the windows terminal maintainers (which btw also maintain ConPty), whether they could release ConPty as a standalone windows service-like thingy with shorter update/upgrade cycles than the official windows releases. But even that might not be possible depending on how deep ConPty has to reach into kernel realms.
