### ISSUE TITLE
Support callback on scrollLines

### ISSUE THREAD

**Issue by unional** [xtermjs/xterm.js#4842]
I tried to implement cursor based navigation.

When trying to handle CursorUp at the top of the buffer when there are scroll (i.e. `buffer.active.viewportY` and `buffer.active.baseY` > 0), I tried to do:

```ts
xterm.scrollLines(-1)
xterm.write('\x1B[A') // cursorUp
```

But that doesn't work probably becuase `buffer.active.Y` is already 0.

Or maybe `scrollLines()` didn't update the `buffer.active.viewportY/baseY` (I saw that they remain unchanged after the scroll happens.

**Comment by Tyriar** [comment]
`scrollLines` should update synchronously:

https://github.com/xtermjs/xterm.js/blob/f6c4aee928ccadaa1a4187003c936895cb4c54f7/src/common/services/BufferService.ts#L128-L150

It will update `viewportY`, not `baseY`. It might be doing something different from what you want, it seems to work as expected for me?

![Recording 2023-10-12 at 13 48 59](https://github.com/xtermjs/xterm.js/assets/2193314/a01105b3-6ce6-4748-b3be-61a998a40cd6)

**Comment by unional** [comment]
My case seems to be an edge case. When the `buffer.active.y` is `0`.

i.e. at the top of the viewport.

I tried doing the same thing when `y` is not `0` and it is working correctly.
