### ISSUE TITLE
[xterm-addon-web-links] Typing with link highlighted causes serious performance impact

### ISSUE THREAD

**Issue by raiden-dev** [xtermjs/xterm.js#4845]
## Details
- Browser and browser version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
- OS version: Windows 11 Pro / 22H2
- xterm.js version: Any version with loaded xterm-addon-web-links. Tested on version bundled with [ttyd](https://github.com/tsl0922/ttyd): `"xterm": "^5.3.0`, `"xterm-addon-web-links": "^0.9.0"`.

### Steps to reproduce

0. Make a terminal with loaded `WebLinksAddon` from `xterm-addon-web-links` package.
1. Move mouse pointer to any link in xterm.js canvas to highlight it.
2. Try to type anything. Overall performance will degrade with every new keypress and may result to tab crash.

Here's the traced performance profile: [Trace-20231014T084401.json](https://github.com/xtermjs/xterm.js/files/12902738/Trace-20231014T084401.json)

<img width="1281" alt="Screenshot 2023-10-14 084530" src="https://github.com/xtermjs/xterm.js/assets/1329477/be134fd8-1f00-4644-9f96-68e1bce4aba0">

**Comment by jerch** [comment]
@raiden-dev Thx for finding this one, can repro it as long as the typed content adds the the link while the link is hovered. This really feels like some exp runtime issue, the perf degrades really fast. Interesting sidenote - the perf resets if I re-hover the link and type again.

From a first glance at devtools it seems the time gets eaten in this method: https://github.com/xtermjs/xterm.js/blob/a5646a58d5df674190c9917702549d23a275a316/src/browser/Linkifier2.ts#L257-L268

but that code look rather innocent to me. Maybe there is something off with `this._linkCacheDisposables`, not sure yet.

**Comment by jerch** [comment]
I cannot repro it on our demo, works with all renderers as expected not showing any quadratic/exp runtime growth. This is somewhat weird, as there were no substantial code changes to the linkifier or the web-links addon almost a year.

@Tyriar My best guess here is, that this was also solved with #4814. Gonna close the issue, as master does not exhibit the toxic growth anymore.

**Comment by Tyriar** [comment]
Yep https://github.com/xtermjs/xterm.js/issues/4814 was a pretty bad bug.
