### ISSUE TITLE
Split terminal view in two-page layout

### ISSUE THREAD

**Issue by bphd** [xtermjs/xterm.js#4848]
**Enhancement Request: Improved Search Functionality**

**Describe the enhancement here.**

I would like to propose an enhancement to the search functionality in our application. Currently, the search feature is quite basic, and users often face limitations in terms of finding specific content efficiently. 

The enhancement I'm suggesting includes the following improvements:

1. **Advanced Search Filters:** Implement advanced search filters that allow users to refine their search results based on criteria such as date, file type, and location.

2. **Search Suggestions:** Integrate a search suggestion feature that provides auto-suggestions as users type their search queries, helping them find content faster.

3. **Full-Text Search:** Enable full-text search capabilities to search for text within documents, not just file names.

4. **Saved Searches:** Allow users to save frequently used search queries for quick access.

5. **Search History:** Provide a search history feature that displays past search queries, making it easier for users to revisit previous searches.

This enhancement would greatly improve the search experience in our application, making it more powerful and user-friendly. Users will be able to find the content they need more quickly and with greater precision.

**Comment by Tyriar** [comment]
This ask doesn't make sense in xterm.js which is just a library, embedders determine how multiple terminals would work.
