### ISSUE TITLE
Demo startup exception

### ISSUE THREAD

**Issue by tisilent** [xtermjs/xterm.js#4852]
- OS version: windows
![123](https://github.com/xtermjs/xterm.js/assets/48614781/082b0a88-5338-4028-bee1-ad233996da61)

Shell not displayed.

Related to the upgrade of node pty. :scream:

**Comment by tisilent** [comment]
@Tyriar  I looked at it and it seems to be related to `ConnectNamedPipe`.
How long is the difference between the two `0.10.1` and `1.1.0-beta5`
node-pty

**Comment by Tyriar** [comment]
@tisilent what version/build of Windows are you on? Did you try clearing all node modules and running yarn again?

**Comment by tisilent** [comment]
@Tyriar 
windows version 19045.3570.
I tried two versions, 0.10.1 and 1.1.0-beta5, and recompiled the latest node pty. I found that I have been waiting in 'ConnectNamedPipe'.

**Comment by Tyriar** [comment]
Closing as stale, we'd need to investigate on node-pty side if there's anything to fix it if it still happens.
