### ISSUE TITLE
Migrate to @xterm org on npm

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4859]
In order to prevent problems like https://github.com/xtermjs/xterm.js/issues/4857 in the future let's move to scoped packages on npm. I don't consider this a breaking change as it needs a manual action to update anyway.

Plan:

- [x] Start publishing beta builds to `@xterm/xterm`, `@xterm/addon-search`, etc.
- [x] Publish 5.4 to new scope
- [x] Deprecate old packages with a message redirecting users to the new package name
- [x] update all docs snippets including paths in `<script>` elements here and on xtermjs.org (added by @jerch)

**Comment by jerch** [comment]
@Tyriar Wow, that already created quite a refactoring noise. Thx for getting it fixed this quickly.

**Comment by Tyriar** [comment]
@jerch np, it was our tech debt week so conveniently timed 🙂 ended up being a pretty chunky VS Code PR too https://github.com/microsoft/vscode/pull/197167

**Comment by octoclonius** [comment]
I tried using `@xterm/addon-attach`, `@xterm/addon-fit`, and `@xterm/addon-webgl`, and I noticed they all had the same issue.

I installed them with npm and I got their beta versions.

"@xterm/addon-attach": "^0.10.0-beta.1"
"@xterm/addon-fit": "^0.9.0-beta.1"
"@xterm/addon-webgl": "^0.17.0-beta.1"

In their respective `lib` folders (`@xterm/addon-[attach/fit/webgl]/lib/addon-[attach/fit/webgl].js`), the `.js` code has a bug. When I replace `self` with `this`, it ceases to cause me issues. I don't really know if that really fixes anything or not, but I just thought I'd share.

**Comment by Tyriar** [comment]
I deprecated xterm and xterm-headless. I don't think I can give it a custom message unfortunately
