### ISSUE TITLE
Support serializing a specific line

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4871]
I'm implementing sticky scroll in VS Code (microsoft/vscode#172742) which needs to serialize a particular line. Right now it's rather inefficient as I need to scroll up to the line, not only the line:

```ts
// TODO: Serializing all content up to the required line is inefficient; support providing single line/range serialize addon
const s = this._serializeAddon?.serialize({
	scrollback: this._xterm.raw.buffer.active.baseY - marker.line
});
if (s) {
	const content = s.substring(0, s.indexOf('\r'));
	...
}
```

**Comment by jerch** [comment]
Already figured, that the high-level serialize interface is a bit unconventional and limited in pulling certain lines or ranges of lines, while doing that first wasm rewrite. Imho providing a range option (default: full range of lines) is the better idea, yeah.
