### ISSUE TITLE
Horizontal scrollbar in Firefox

### ISSUE THREAD

**Issue by Sodik** [xtermjs/xterm.js#4882]
WidthCache element causes horizontal scrollbar appearance.
Workaround is adding `overflow:hidden` to body but this is not applicable if you have `min-width` on body.

![image](https://github.com/xtermjs/xterm.js/assets/4775736/5d95f91e-9bc6-4614-9957-01c0278f4f29)

## Details
- Browser and browser version:  Firefox 119.0.1
- OS version: Ubuntu 20.04.6 LTS
- xterm.js version: 5.3.0

### Steps to reproduce

Create index.html with following content
```<!doctype html>
<html>
  <head>
    <script src="
https://cdn.jsdelivr.net/npm/xterm@5.3.0/lib/xterm.min.js
"></script>
    <link href="
https://cdn.jsdelivr.net/npm/xterm@5.3.0/css/xterm.min.css
" rel="stylesheet">
  </head>
  <body>
    <div id="terminal"></div>
    <script>
      var term = new Terminal();
      term.open(document.getElementById('terminal'));
      term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
    </script>
  </body>
</html>```

**Comment by jerch** [comment]
Plz re-check, if the issue remains with with current master, as there were some changes in that field.

(We are in the middle of a package renaming with a scoped prefix `@xterm/...`, you can pull the latest betas like this from a CDN: https://unpkg.com/@xterm/xterm@5.4.0-beta.14/lib/xterm.js)

**Comment by Sodik** [comment]
Fixed in [https://unpkg.com/@xterm/xterm@5.4.0-beta.14/lib/xterm.js](https://unpkg.com/@xterm/xterm@5.4.0-beta.14/lib/xterm.js)

Thank you.
