### ISSUE TITLE
can you complete your api doc , not only by .ts file?

### ISSUE THREAD

**Issue by birenjack** [xtermjs/xterm.js#4896]

**Comment by jerch** [comment]
> your doc is very clear?

Seems clear enough to give thousands of devs enough clues how to use it. Which does not mean it cannot be improved ofc.

> please send few time to finish your doc like most of website.

This is open source, no one gets paid to please you. If you find something is lacking, try to reach out to the devs, phrase your issue in way devs can understand what you want. Your issue title w'o any issue description is not helpful at all, it is rude spam, therefore I closed it w'o any comment. Its as simple as that - if you dont show dedication, why should I care?

Plz stop that kindergarden spam game, either reach out in a mature way or feel free to use another lib.
