### ISSUE TITLE
Space+Underline is not rendered properly

### ISSUE THREAD

**Issue by ceccopierangiolieugenio** [xtermjs/xterm.js#4901]
## Details
- Browser and browser version: 
  - **Firefox**: 120.0
  - **Vivaldi**: 6.4.3160.47 (Stable channel) stable (64-bit) 
  - **Edge**: 119.0.2151.97 (Official build) (64-bit)
- OS version:
  - **Linux**: Pop!_OS 22.04 LTS 
- xterm.js version: 
  - "xterm": "^5.3.0"

### Steps to reproduce

follow the installation steps on the homepage: https://xtermjs.org
```bash
npm install xterm
```
Use this html testing file:
```html
<!doctype html>
  <html>
    <head>
      <link rel="stylesheet" href="node_modules/xterm/css/xterm.css" />
      <script src="node_modules/xterm/lib/xterm.js"></script>
    </head>
    <body>
      <div id="terminal"></div>
      <script>
        var term = new Terminal();
        term.open(document.getElementById('terminal'));
        term.write('                      # CSI Ps m  Character Attributes (SGR).\n\r')
        term.write('Hello from \x1B[1;0;31mxterm.js   test\x1B[0m Ps=0 -> Normal (default), VT100.\n\r')
        term.write('Hello from \x1B[1;1;31mxterm.js   test\x1B[0m Ps=1 -> Bold, VT100.\n\r')
        term.write('Hello from \x1B[1;2;31mxterm.js   test\x1B[0m Ps=2 -> Faint, decreased intensity, ECMA-48 2nd.\n\r')
        term.write('Hello from \x1B[1;3;31mxterm.js   test\x1B[0m Ps=3 -> Italicized, ECMA-48 2nd.\n\r')
        term.write('Hello from \x1B[1;4;31mxterm.js   test\x1B[0m Ps=4 -> Underlined, VT100.\n\r')
        term.write('Hello from \x1B[1;5;31mxterm.js   test\x1B[0m Ps=5 -> Blink, VT100. - Bold in X11R6 xterm.\n\r')
        term.write('Hello from \x1B[1;7;31mxterm.js   test\x1B[0m Ps=7 -> Inverse, VT100.\n\r')
        term.write('Hello from \x1B[1;8;31mxterm.js   test\x1B[0m Ps=8 -> Invisible, i.e., hidden, ECMA-48 2nd, VT300.\n\r')
        term.write('Hello from \x1B[1;9;31mxterm.js   test\x1B[0m Ps=9 -> Crossed-out characters, ECMA-48 3rd.\n\r')
      </script>
    </body>
  </html>
```

### Issue:
as shown here:
![image](https://github.com/xtermjs/xterm.js/assets/8876552/3d0c7f85-229d-441a-958e-1422bfe98597)
The fifth line should render three underlined spaces but those are not vivible

This issue is noticeable also if I use [pyTermTk](https://github.com/ceccopierangiolieugenio/pyTermTk), where only the different chars of the buffer are sent to the terminal but the entire line is affected:
![Peek 2023-12-06 15-15](https://github.com/xtermjs/xterm.js/assets/8876552/070b753b-f24a-4be0-9172-4151e23bde8a)

### Regression
 * **xterm.js** - **5.0.0** 
  No issues:
  ![image](https://github.com/xtermjs/xterm.js/assets/8876552/05b774c1-4e03-40c4-b6bc-5851f97bf76b)
 * **xterm.js** - **5.1.0**, **5.2.0**
  Some artifacts are displayed:
  ![image](https://github.com/xtermjs/xterm.js/assets/8876552/b8f4d00c-ede7-4b39-91de-99592cb2472a)
 * **xterm.js** - **5.3.0** 
 Underlined Spaces are not rendered:
  ![image](https://github.com/xtermjs/xterm.js/assets/8876552/87e8db62-cabe-4998-8a41-6e9b6db8ddd1)

**Comment by ceccopierangiolieugenio** [comment]
@jerch 
I managed to reproduce the issue just pushing this string to the terminal as reported in the description:
`'\x1B[1;4;31mxterm.js   test\x1B[0m'`
Is it there a way to enable some debug info to check which exact bytes are sent?

**Comment by jerch** [comment]
You can get byte content on console.log, if you enable the debug log in the terminal. I am asking for the byte content, because your screenshot for xterm.js - 5.1.0, 5.2.0 indicates some issues with encoding (looks like mixing latin-1 with utf-8). Once we have ruled that out, we can check if the renderers do crazy things.

**Comment by ceccopierangiolieugenio** [comment]
New test where I used for testing:
```html
      <div id="terminal"></div>
      <script>
        var term = new Terminal({
            logLevel: 'debug',
            allowProposedApi: true});
        term.open(document.getElementById('terminal'));
        term.write('                      # CSI Ps m  Character Attributes (SGR).\n\r')
        term.write('Hello from \x1B[1;0;31mxterm.js   test\x1B[0m Ps=0 -> Normal (default), VT100.\n\r')
        term.write('Hello from \x1B[1;1;31mxterm.js   test\x1B[0m Ps=1 -> Bold, VT100.\n\r')
        term.write('Hello from \x1B[1;3;31mxterm.js   test\x1B[0m Ps=3 -> Italicized, ECMA-48 2nd.\n\r')
        term.write('Hello from \x1B[1;4;31mxterm.js   test\x1B[0m Ps=4 -> Underlined, VT100.\n\r')
        term.write('Hello from \x1B[4;2mxterm.js   test\x1B[0m Ps=4 -> Underlined, VT100.\n\r')
        term.write('Hello from \x1B[4;5mxterm.js   test\x1B[0m Ps=4 -> Underlined, VT100.\n\r')
        term.write('Hello from \x1B[1;9;31mxterm.js   test\x1B[0m Ps=9 -> Crossed-out characters, ECMA-48 3rd.\n\r')
      </script>
```

Here is a comparison between the different versions, the bytes sent are identical;

### xterm.js 5.0.0
![image](https://github.com/xtermjs/xterm.js/assets/8876552/20da1cf5-43a1-4864-9e1f-7d43af6fc464)
```
Sent: "1 �[1;0;31mA B  C�[0mD"
[ 49, 32, 27, 91, 49, 59, 48, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "2 �[1;1;31mA B  C�[0mD"
[ 50, 32, 27, 91, 49, 59, 49, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "3 �[1;3;31mA B  C�[0mD" 
[ 51, 32, 27, 91, 49, 59, 51, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "4 �[1;4;31mA B  C�[0mD" 
[ 52, 32, 27, 91, 49, 59, 52, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "5 �[4;2mA B  C�[0mD" 
[ 53, 32, 27, 91, 52, 59, 50, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "6 �[4;5mA B  C�[0mD" 
[ 54, 32, 27, 91, 52, 59, 53, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "7 �[1;9;31mA B  C�[0mD" 
[ 55, 32, 27, 91, 49, 59, 57, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
```
### xterm.js 5.1.0
| ![image](https://github.com/xtermjs/xterm.js/assets/8876552/eed05934-53f0-4335-9163-b3cf1b173ece) | ![image](https://github.com/xtermjs/xterm.js/assets/8876552/add67387-e0c1-4943-974d-21b55ec4a5b2) | ![image](https://github.com/xtermjs/xterm.js/assets/8876552/0bfeaf47-1357-431b-a1c7-1241e5e575c0) |

```
Sent: "1 �[1;0;31mA B  C�[0mD" 
[ 49, 32, 27, 91, 49, 59, 48, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "2 �[1;1;31mA B  C�[0mD" 
[ 50, 32, 27, 91, 49, 59, 49, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "3 �[1;3;31mA B  C�[0mD" 
[ 51, 32, 27, 91, 49, 59, 51, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "4 �[1;4;31mA B  C�[0mD" 
[ 52, 32, 27, 91, 49, 59, 52, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "5 �[4;2mA B  C�[0mD" 
[ 53, 32, 27, 91, 52, 59, 50, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "6 �[4;5mA B  C�[0mD" 
[ 54, 32, 27, 91, 52, 59, 53, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "7 �[1;9;31mA B  C�[0mD" 
[ 55, 32, 27, 91, 49, 59, 57, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
```

### xterm.js 5.3.0
| ![image](https://github.com/xtermjs/xterm.js/assets/8876552/b48adc02-8a4a-4332-b65d-5faf3614fcd9) | ![image](https://github.com/xtermjs/xterm.js/assets/8876552/e3b6b0d1-992a-4778-a9ba-57caf0757d1c) |
```
Sent: "1 �[1;0;31mA B  C�[0mD" 
[ 49, 32, 27, 91, 49, 59, 48, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "2 �[1;1;31mA B  C�[0mD" 
[ 50, 32, 27, 91, 49, 59, 49, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "3 �[1;3;31mA B  C�[0mD" 
[ 51, 32, 27, 91, 49, 59, 51, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "4 �[1;4;31mA B  C�[0mD" 
[ 52, 32, 27, 91, 49, 59, 52, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "5 �[4;2mA B  C�[0mD" 
[ 53, 32, 27, 91, 52, 59, 50, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "6 �[4;5mA B  C�[0mD" 
[ 54, 32, 27, 91, 52, 59, 53, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
Sent: "7 �[1;9;31mA B  C�[0mD" 
[ 55, 32, 27, 91, 49, 59, 57, 59, 51, 49, 109, 65, 32, 66, 32, 32, 67, 27, 91, 48, 109, 68, 10, 13 ]
```

**Comment by jerch** [comment]
Plz also see https://stackoverflow.com/a/1462039/12548337, might explain that Å char.

**Comment by tisilent** [comment]
![128](https://github.com/xtermjs/xterm.js/assets/48614781/1e15f23d-82ae-486c-96a1-766aa1f3f085)
😟

**Comment by ceccopierangiolieugenio** [comment]
Thanks @jerch  it is exactly the issue reported in:
 https://stackoverflow.com/a/1462039/12548337
I fixed it adding in the header:
```html
   <head>
      <meta charset="utf-8">
   <head>
```
The issue was caused by the encoding of the '\xa0' in:

https://github.com/xtermjs/xterm.js/blob/957e3e0f08606678be8e9346113b0aaefba4e433/src/browser/renderer/dom/DomRendererRowFactory.ts#L272-L274

**Comment by jerch** [comment]
@Tyriar The need for an utf-8 encoded document for the DOM renderer feels like a surprising limitation (in fact it isnt when thinking about it for a few seconds). Should we mention that in some sort of a document setup guide?

**Comment by Tyriar** [comment]
I've never needing to think about HTML document charset before, [mdn says](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#charset) that it's the only valid encoding for HTML5 documents so maybe you're triggering some very old document by declaring it as a xhtml document or something? Also haven't thought about that in a long time.

I don't think this warrants any doc updates as this seems to be the embedder misbehaving unreasonably.
