### ISSUE TITLE
OSC hyperlinks don't work for certain formats

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4916]
VS Code issue: https://github.com/microsoft/vscode/issues/170963

Code pointer: https://github.com/xtermjs/xterm.js/blob/88ba66d00bb848569e867fea894d444defee69b5/src/browser/OscLinkProvider.ts

**Comment by jerch** [comment]
@Tyriar Cant repro from the given examples, not in master and not in vscode 1.82. Maybe it already got fixed? Note that I have some issues to understand the issue description :sweat_smile:

**Comment by Tyriar** [comment]
Think I can repro:

<img width="626" alt="Screenshot 2024-04-12 at 4 38 57 PM" src="https://github.com/xtermjs/xterm.js/assets/2193314/fcb549a2-9e0c-4a32-a0e8-d008145df334">

The link keeps going to `AFTER_LINK` and beyond
