### ISSUE TITLE
Emoji panel and accent menu positioning is broken

### ISSUE THREAD

**Issue by LabhanshAgrawal** [xtermjs/xterm.js#4938]
## Details
- Browser and browser version: Chrome 119
- OS version: macOS 14
- xterm.js version: 5.3.0

### Steps to reproduce

1.  Focus on the terminal and enter any command (e.g. `ls`) so that cursors comes to a new line
2. Now open emoji panel (ctrl+cmd+space)
3. The panel opens at the edge of the screen instead of the cursor position
4. The position is correct if you enter some text in the terminal or click somewhere else and then refocus.

<img width="1243" alt="Screenshot 2024-01-08 at 01 54 43" src="https://github.com/xtermjs/xterm.js/assets/16598275/8bf241c6-6435-4727-8c7b-cd7fe791e9d9">

The accent menu is always positioned incorrectly (also it doesn't work, but that might need a separate bug report I guess)

<img width="1268" alt="Screenshot 2024-01-08 at 02 05 26" src="https://github.com/xtermjs/xterm.js/assets/16598275/e83b7af4-8f9e-443b-8419-431f73733b1d">

**Comment by Tyriar** [comment]
Works for me on latest in VS Code:

![Image](https://github.com/user-attachments/assets/9f59df12-3fbc-4ef0-be09-edcf86e28a47)

I think xtermjs.org's version is out of date
