### ISSUE TITLE
expose API method for writing to application side

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#4948]
Coming from #4220 and this comment https://github.com/xtermjs/xterm.js/pull/4220#issuecomment-1793095087

It would be nice to have a method to write to application side from xterm.js' API. Internally xterm.js uses `this.coreService.triggerDataEvent` for this, which can easily be exposed at the API as well.

_interface suggestion_
```typescript
  export class Terminal implements IDisposable {
    ...
    /**
     * Input data to application side.
     * The data is treated the same way as typed input at the terminal (will appear in the onData event).
     */
    input(data: string): void;
    ...
}
```

Such a method would help to automate data input programmatically, e.g. from the clipboard addon w'o hooking into hidden internals.

**Comment by Tyriar** [comment]
I like it 👍

**Comment by jerch** [comment]
@Tyriar  I'd also need this for my proposal in #4943, but thats still at an very early stage... :sweat_smile:
