### ISSUE TITLE
Only first character is invisible when rendering invisible text via escape code

### ISSUE THREAD

**Issue by sebnozzi** [xtermjs/xterm.js#4962]
Rendering "invisible" text via escape-codes only makes the _first_ character in the sequence invisible. The rest remain visible.

## Details
- Browser and browser version: Chrome - Version 121.0.6167.160 (Official Build) (x86_64)
- OS version: macOS 10.15.7
- xterm.js version: 5.3.0

### Steps to reproduce

1. Create a `Terminal` object
2. Write(ln) the string `Test: \x1B[8mINVISIBLE\x1B[m vs. VISIBLE`
3. Expected: to see "Test:           vs. VISIBLE"
4. Actual: "Test:  NVISIBLE vs. VISIBLE" (note the invisible "I")

To reproduce I offer this HTML file:

```html
<!doctype html>
<html>
<head>
  <link rel="shortcut icon" href="#">
  <title>xterm.js - Invisible Text Bug</title>  
  <link rel="stylesheet" href="node_modules/xterm/css/xterm.css" />
  <script src="node_modules/xterm/lib/xterm.js"></script>
</head>
<body>
  <div id="terminal"></div>
  <script>
    const term = new Terminal();
    term.open(document.getElementById('terminal'));
    term.writeln('Test: \x1B[8mINVISIBLE\x1B[m vs. VISIBLE');
  </script>
</body>
</html>
```

**Comment by jerch** [comment]
Cannot repo in master - could you check with the newer package `@xterm/xterm`?

**Comment by sebnozzi** [comment]
> Cannot repo in master - could you check with the newer package `@xterm/xterm`?

Thanks for the quick reply.

Checked with `@xterm/xterm`. Indeed my issue is not present in that version.

Will this be the next version? Almost all the documentation suggests to install `xterm`, not `@xterm/xterm`.

**Comment by jerch** [comment]
Yes that will be the new official package names for v5.4+. We had to change to prefixed package names due a malicious package name scam.

**Comment by sebnozzi** [comment]
Ok, seeing this will be fixed in a future version, and assuming the documentation will be updated, I will close this issue then.
