### ISSUE TITLE
Not sure second link in monitor not linked

### ISSUE THREAD

**Issue by ldijkman** [xtermjs/xterm.js#4964]
hello

Not sure second link in monitor not linked
ad on weblinks?

playing with your demo
https://ldijkman.github.io/async-esp-fs-webserver/WebSerialMonitor.html

serial monitor demo does not make a second link clickable i think
```
Tuesday, February 20 2024 17:06:33
mDNS at http://garage.local
Browsing for service _http._tcp.local. ... 1 service(s) found
  1: http://kitchen.local - http://10.10.100.100:80
```

http://garage.local/ and http://kitchen.local/ is a clickable link

[http://10.10.100.100:80](http://10.10.100.100/) is not a clickable link

![Screenshot from 2024-02-20 18-02-53](https://github.com/xtermjs/xterm.js/assets/45427770/158617be-283c-4f51-ad06-36a640e94b49)

**Comment by jerch** [comment]
Prolly the same as #4296. (I'll keep this issue open until it is confirmed...)

**Comment by ldijkman** [comment]
hmm
thought it was the second link on line is not clickable 
so changed it
but if the ip is the first link it is also NOT clickable

```
Thursday, February 22 2024 04:08:13
mDNS at http://garage.local
Browsing for service _http._tcp.local. ... 1 service(s) found
  1: http://kitchen.local - http://10.10.100.100:80
  1:  http://10.10.100.100:80
``` 

![Screenshot from 2024-02-22 05-08-40](https://github.com/xtermjs/xterm.js/assets/45427770/1620469b-29c2-4214-a972-ca9020f17dfd)

**Comment by ldijkman** [comment]
looks like 
:port 
 in link is the problem

last ip without port is clickable
```
Thursday, February 22 2024 04:19:04
mDNS at http://garage.local
Browsing for service _http._tcp.local. ... 1 service(s) found
  1: http://kitchen.local - http://10.10.100.100:80
  1:  http://10.10.100.100:80
  1:  http://10.10.100.100
```

![Screenshot from 2024-02-22 05-19-30](https://github.com/xtermjs/xterm.js/assets/45427770/d6281df2-242d-45e4-a445-86f33fa2e1dd)

**Comment by ldijkman** [comment]
second link on monitor line
ip without port is clickable

![Screenshot from 2024-02-22 05-35-57](https://github.com/xtermjs/xterm.js/assets/45427770/219a4e59-b658-4c93-9bc1-4ace412835f4)

**Comment by ldijkman** [comment]
hmm

looks like it also does not make links of text with caps 

http://Living.local 

is not linked

maybe because of L

**Comment by jerch** [comment]
This roughly summarizes, whats going here:
```Javascript
> new URL('hTTpS://Living.local:443/inPathUpperNotLowered')
URL {
  href: 'https://living.local/inPathUpperNotLowered',
  origin: 'https://living.local',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'living.local',
  hostname: 'living.local',
  port: '',
  pathname: '/inPathUpperNotLowered',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```
- protocol and host part are always lowered by `URL`
- `URL` truncates a port notion, if it is the default port of provided protocol

We currently do a sanity check against the `URL` parsing result with `s.startswith`, here we lose the uppercase matching. We should instead do a `s.toLowerCase().startswith` check.

I still cannot repro the port issue, `startswith` should still match even with the port notion being removed. Have you tested with the newer `@xterm` packages?

**Comment by ldijkman** [comment]
Sorry i do not have the knowledge how to change the webadonlinks xterm

I use the chromium terminal example
https://ldijkman.github.io/async-esp-fs-webserver/WebSerialMonitor.html

They at chromium said xterm webaddonlinks maybe the problem for not linking

And the ESP mdns monitor links 
are http not https 
as your test showed

Greet luberth

**Comment by jerch** [comment]
@ldijkman PR #4965 should fix the issues. Thx for alot for finding them.
