### ISSUE TITLE
Add complied project to releases (dist)

### ISSUE THREAD

**Issue by yarona1993** [xtermjs/xterm.js#4985]
Add complied project to releases (dist)

**Comment by Tyriar** [comment]
No plans to do this as you can pull the compiled source easily from npm

**Comment by yarona1993** [comment]
npm doesn't have the latest build
![image](https://github.com/xtermjs/xterm.js/assets/87313761/f7f60335-97c4-483d-8a60-98e6049effa3)

**Comment by Tyriar** [comment]
@yarona1993 see the top of https://github.com/xtermjs/xterm.js/releases/tag/5.4.0
