### ISSUE TITLE
Block style cursor not blinking after upgrade 5.3.0 -> 5.4.0

### ISSUE THREAD

**Issue by RahjIII** [xtermjs/xterm.js#4987]
I've updated from xterm.js 5.3.0 to 5.4.0 and noticed that the cursor is no longer blinking when it is focused and in block mode.

With these options set:
           "cursorBlink": true,
           "cursorStyle": "block",
           "cursorInactiveStyle": "outline"

The cursor goes from outline to block style when the terminal is focused, but the block cursor **does not blink** as expected.  It is supposed to blink, and **does** blink under xterm.js 5.3.0.  

With cursorStyle set to "underline" and cursorBlink to true, the cursor **does** blink as expected.  If I change cursorBlink to false, then the underline cursor **does not** blink as expected.  (showing that the cursorBlink attribute is being honored for the underline cursor)

It only appears that the cursor is fails to blink when cursorBlink is true and cursorStyle is block.

## Details
- Browser and browser version: Version 121.0.6167.139 (Official Build) (64-bit)
- OS version:  Linux
- xterm.js version: 5.4.0

### Steps to reproduce

1. Set cursorStyle to block
2. Set cursorBlink to true
3. set cursorInactiveStyle to outline
4. focus the terminal to activate the cursor
5. If cursor goes active and turns into a block, but does not blink, problem is reproduced.

**Comment by tisilent** [comment]
bar style cursor not blinking 👻 ...

**Comment by RahjIII** [comment]
Enabled webgl addon, cursors work fine.

**Comment by devjiwonchoi** [comment]
Hi, I'm facing the same issue and can confirm that webgl addon does fix this, but if enabled, how can we test the inner contents?

**Comment by Tyriar** [comment]
@devjiwonchoi you can't really if you want to query the actual dom. You could try enabling `screenReaderMode` which adds info for screen readers (though maybe not in the exact format you expect) or using the `buffer` API. I'm guessing you want the DOM renderer though

**Comment by devjiwonchoi** [comment]
Sounds great. Thank you for replying!

**Comment by Tyriar** [comment]
Probably caused by https://github.com/xtermjs/xterm.js/issues/4773
