### ISSUE TITLE
input length character over 80 , screen display override just one line 

### ISSUE THREAD

**Issue by tokenwind** [xtermjs/xterm.js#4990]
When the character length I input on the terminal exceeds 80, it displays an error. When trying to set the terminal cols parameter, it does not take effect, and when the length exceeds 80, it does not automatically wrap.
![image](https://github.com/xtermjs/xterm.js/assets/29992166/23c20de4-c563-4f6d-a7f0-b19fcfac666f)

## Details
- Browser and browser version: firefox\chrom
- OS version: 
- xterm.js version:  latest

### Steps to reproduce
 browse termiral input

**Comment by Tyriar** [comment]
See https://github.com/xtermjs/xterm.js/wiki/FAQ#characters-are-being-overwritten-when-wrapped-to-a-new-line
