### ISSUE TITLE
SearchAddon matches fall out of sync on some multiline inputs when over the scrollback limit.

### ISSUE THREAD

**Issue by tabarra** [xtermjs/xterm.js#4994]
If you have a search and your buffer is already at the scrollback limit (so that older lines are dropped), any multi-line `term.write()`  and any `term.writeln()` ending in `\n` causes the march decorations to fall out of sync with the buffer and mark the wrong lines.  
Video: 

https://github.com/xtermjs/xterm.js/assets/1808295/2eee11b3-6b75-4002-bb67-0ae2b68ae078

## Details
Versions:
```json
"xterm": "5.4.0-beta.20",
"xterm-addon-search": "0.14.0-beta.20"
```

Repro sandbox: https://codesandbox.io/p/sandbox/xtermjs-demo-forked-2jpjsz
It _looks like_ every multi-line `.write()` will cause this bug, and only the `.writeln()` that ends with new lines.  
In the sandbox I provided a bunch of example combinations where it breaks or doesn't.  
This only works when the buffer is already at the scrollback limit, so I changed the options to have 0 scrollback to facilitate testing.

**Comment by Tyriar** [comment]
Simple demo repro:

1. Set scrollback to 1
2. Run ls (fill scrollback)
3. Search for something
4. Press enter in terminal

![image](https://github.com/xtermjs/xterm.js/assets/2193314/cd016527-7d15-4f48-b341-1a7c220a24c0)
