### ISSUE TITLE
invalid identity escape in regular expression

### ISSUE THREAD

**Issue by MooreLxr** [xtermjs/xterm.js#5015]
error: invalid identity escape in regular expression in firefox

## Details
- Browser and browser version: firefox 52.3.0
- OS version: 
- xterm.js version: 5.3.0

**Comment by Tyriar** [comment]
Need a little more info on this:

- Does it happen in v5.4? (use the `@xterm/xterm` package)
- What were you doing at the time?
- Does it come with a stack trace?
