### ISSUE TITLE
Unable to clear terminal using clear method

### ISSUE THREAD

**Issue by destinytaoer** [xtermjs/xterm.js#5019]
## Details
- Browser and browser version: chrome 123.0.6312.59
- OS version: macOS 12.1
- xterm.js version: 5.4.0

Unable to clear terminal using clear()，but reset() can clear the terminal
what is the different between clear() and reset()？
![temrinal](https://github.com/xtermjs/xterm.js/assets/27852774/2f795d90-1dc7-4f71-afdb-04a1f073c7c3)

### Steps to reproduce

1. terminal.write("something\r\n")
2. temrinal.write("last line")
3. setTimeout(() => terminal.clear(), 3000)
![image](https://github.com/xtermjs/xterm.js/assets/27852774/4d86c856-492c-42dd-8a57-f62b27514fa0)

**Comment by destinytaoer** [comment]
The last line can't be cleared. But when i write the last line with CRLF, it can be cleared.

**Comment by Skinbow** [comment]
Hello.
From what I gather, **reset** actually resets the entire terminal (it restarts all the running services dependent on the terminal). However (quoting comment) "reset does bot clear input buffers and does not reset the parser".
**Clear** on the other hand simply clears the buffer, while making the prompt line the first line in the buffer and firing a scroll event, which is why it isn't clearing everything, but rather keeping the last line intact.
I hope this helped.

**Comment by destinytaoer** [comment]
> Hello. From what I gather, **reset** actually resets the entire terminal (it restarts all the running services dependent on the terminal). However (quoting comment) "reset does bot clear input buffers and does not reset the parser". **Clear** on the other hand simply clears the buffer, while making the prompt line the first line in the buffer and firing a scroll event, which is why it isn't clearing everything, but rather keeping the last line intact. I hope this helped.

I got it. The clear method is like entering clear at a terminal, it just clear historical output, and the first line is considered as the user's input. It's that right?

**Comment by destinytaoer** [comment]
so when i want to clear all input, just use reset method? other advise?

**Comment by jerch** [comment]
`.reset()` might not be what you want, it effectively reboots the terminal (its like pressing off/on on a device), which can have unwanted side effects like erasing pending input. Normally it is enough to call the VT function DECSTR (`'\x1b[!p'`) or RIS (`'\x1bc'`).

**Comment by destinytaoer** [comment]
> `.reset()` might not be what you want, it effectively reboots the terminal (its like pressing off/on on a device), which can have unwanted side effects like erasing pending input. Normally it is enough to call the VT function DECSTR (`'\x1b[!p'`) or RIS (`'\x1bc'`).

<img width="356" alt="image" src="https://github.com/xtermjs/xterm.js/assets/27852774/ed1c9282-c312-4a0f-afcc-056355a90193">
it seems that reset and RIS are the same

**Comment by jerch** [comment]
There is a difference - RIS is band-synchronous (postponed until all previous input in the write buffer was handled), while `term.reset()` gets executed immediately in JS, thus might cut into an state of the terminal.
But sure DECSTR is most of the time enough.

**Comment by destinytaoer** [comment]
> There is a difference - RIS is band-synchronous (postponed until all previous input in the write buffer was handled), while `term.reset()` gets executed immediately in JS, thus might cut into any state of the terminal. But sure DECSTR is most of the time enough.
> 
> And if you just want to clear the viewport + scrollback while leaving other terminal states untouched, ED 2 + ED 3 + CUP is your friend (`'\x1b[2J\x1b[3J\x1b[H'`);

Got it, Thank you very much!
