### ISSUE TITLE
Vscode sending "\n" instead of "^J" with "\u000A"?

### ISSUE THREAD

**Issue by tmpm697** [xtermjs/xterm.js#5028]
## Details
- Browser and browser version: 
- OS version:  macos ventura 13.6.6
- xterm.js version: version that used in vscode 1.88.1 on macos

### Steps to reproduce
you can produce this issue via this issue: https://github.com/microsoft/vscode/issues/210121#issuecomment-2053468201

basically when u try to map `cmd+j` to `ctrl+j` in vscode's terminal, vscode or xterm.js seems to send `\n` instead of `ctrl+j`

so how to instruct vscode that user intend to send ^j instead of \n when mapping?

**Comment by Tyriar** [comment]
Discussion in the vscode issue
