### ISSUE TITLE
Support for wider color spaces?

### ISSUE THREAD

**Issue by YousufSSyed** [xtermjs/xterm.js#5045]
Xterm seems to only support srgb. I don't know about canvas elements but CSS has the [`color()` function](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color) to define colors in specific color spaces.

**Comment by jerch** [comment]
A terminal can only reliably do RGB, CMY, CMYK or indexed colors from the SGR function spec. We have implemented RGB and indexed colors, but not the others.

While it would be possible to create color-space translations from those other modes of `color()` maybe to indexed or close RGB matches, I dont think there is not any real value to have that in xterm.js itself. You can always do that in your code as well.
