### ISSUE TITLE
Xterm.onResize cannot receive correct data

### ISSUE THREAD

**Issue by TheBlindM** [xtermjs/xterm.js#5053]
After calling fitAddon. fit(), the cols and rows received by "xterm. onResize" were not accurate. When I modified the window size and triggered fitAddon. fit() again, it worked fine

https://github.com/xtermjs/xterm.js/assets/48701152/c1b67ecf-743d-4ca3-9e18-b29a773e9df6

Before modifying window size：
![image](https://github.com/xtermjs/xterm.js/assets/48701152/28f2d9ea-e459-44b7-a860-4c32599227b1)

After modifying the window size
![image](https://github.com/xtermjs/xterm.js/assets/48701152/c0367fa2-72ae-41b3-a948-9799de0c8718)

## Details
- Browser and browser version:  WebView2: 124.0.2478.80
- OS version:  win10
- xterm.js version: 5.3.0

**Comment by tisilent** [comment]
It doesn't feel like it's a addon-fit issue.
Print xterm.rows xterm.cols

**Comment by TheBlindM** [comment]
> It doesn't feel like it's a addon-fit issue. Print xterm.rows xterm.cols

![image](https://github.com/xtermjs/xterm.js/assets/48701152/f34bd14f-47c3-45b6-a62a-7b391a382549)

**Comment by tisilent** [comment]
When executing fit(), the size of the parent element?
Figure 1, it seems to be forcibly stretched.

**Comment by TheBlindM** [comment]
> When executing fit(), the size of the parent element? Figure 1, it seems to be forcibly stretched.

The parent elements are all saturated, with normal width and height, but the onResize value is incorrect.
