### ISSUE TITLE
Terminals not accessible using nano, vim, etc. in Cloud Shell and likely elsewhere

### ISSUE THREAD

**Issue by pattch** [xtermjs/xterm.js#5065]
## Details
- Browser and browser version: Chrome
- OS version: Windows, MacOS, Linux
- xterm.js version: xterm v5

### Steps to reproduce

1. Open xterm terminal, enabling screenreader mode (e.g. https://shell.cloud.google.com/?show=terminal)
2. Run `vim` or `nano`
3. Enter text, navigate over text using arrow keys

Observed results:
1. No content is announced to screen readers

Expected results:
2. As with normal interaction modes, content should get announced to screen readers

**Comment by Tyriar** [comment]
@pattch do you set `screenReaderMode`? Note that there's only a limited about that can happen here since those apps draw text to the screen instead of streaming text so they're inherently inaccessible.

**Comment by Tyriar** [comment]
Closing as designed, we have a setting you must turn on for basic screen reader support, anything more than that and you need to do something on the embedder side.
