### ISSUE TITLE
Line break bug

### ISSUE THREAD

**Issue by lsy934127847** [xtermjs/xterm.js#5074]
terminal.write("cosfs.sh\ndnspod.sh\ninstall_6.0.sh\ntxcdn.sh")
\n has a bug, 
![image](https://github.com/xtermjs/xterm.js/assets/72968089/2dcd0499-d0fa-459a-94ee-ec43c48d4209)

 terminal.write("cosfs.sh\r\ndnspod.sh\r\ninstall_6.0.sh\r\ntxcdn.sh")

\r\n is normal
![image](https://github.com/xtermjs/xterm.js/assets/72968089/608d3939-ce38-4327-bf62-d31c6d24aafd)

Do you want to manually replace \n with \r\n?

**Comment by Tyriar** [comment]
This is how it's meant to work; \n goes down, \r goes to the left
