### ISSUE TITLE
Incorrect pasting the Greek letter ϕ (U+03D5) and φ (U+03C6) from xterm.js to another text-area

### ISSUE THREAD

**Issue by vladtimss** [xtermjs/xterm.js#5111]
**Description**
When pasting the Greek letter ϕ (U+03D5) copying from xterm.js, it is incorrectly interpreted as φ (U+03C6) on paste to another textarea, and vice versa.

**Steps to Reproduce**

1. Open [xterm.js](https://xtermjs.org/).
2. Copy the character ϕ (U+03D5) into the terminal.
3. Paste it in some textarea it is rendered as φ (U+03C6).

https://github.com/user-attachments/assets/33eb58b5-f63f-4841-917d-997f0ad6db9e

**Comment by jerch** [comment]
Cannot repro - works for me in both chrome and firefox (under ubuntu 22). But I figured something else - the automatic mouse selection does not work anymore in firefox (still good in chrome). Did they change/remove the auxclick event in firefox?

Plz provide more info - how you copy&paste, which browser you see this etc...

**Comment by vladtimss** [comment]
> Cannot repro - works for me in both chrome and firefox (under ubuntu 22). But I figured something else - the automatic mouse selection does not work anymore in firefox (still good in chrome). ~Did they change/remove the auxclick event in firefox?~ (Not related for copy, only used for paste, which still works)
> 
> Plz provide more info - how you copy&paste, which browser you see this etc...

hmm, it seems, that this case relates  with fonts somehow. 

I tried change font-family and it influenced. I attached demo how these characters change places with each other


https://github.com/user-attachments/assets/b5e07681-5b9c-458b-84f1-f6a9edc9d0e7

Seems, we can close this issue and i should fix this problem of my fonts
