### ISSUE TITLE
SyntaxError: Named export 'context' not found.

### ISSUE THREAD

**Issue by PerBothner** [xtermjs/xterm.js#5112]
When I try to do:

     yarn run esbuild-watch

I get: 
````
yarn run v1.22.10
warning ../package.json: No license field
$ node bin/esbuild_all.mjs --watch
[22:07:53] Starting xterm...
[22:07:53] Starting xterm-addon-attach...
[22:07:53] Starting xterm-addon-canvas...
[22:07:53] Starting xterm-addon-clipboard...
[22:07:53] Starting xterm-addon-fit...
[22:07:53] Starting xterm-addon-image...
[22:07:53] Starting xterm-addon-ligatures...
[22:07:53] Starting xterm-addon-search...
[22:07:53] Starting xterm-addon-serialize...
[22:07:53] Starting xterm-addon-unicode-graphemes...
[22:07:53] Starting xterm-addon-unicode11...
[22:07:53] Starting xterm-addon-web-links...
[22:07:53] Starting xterm-addon-webgl...
file:///home/bothner/Software/xterm.js/bin/esbuild.mjs:8
import { build, context, default as esbuild } from 'esbuild';
                ^^^^^^^
SyntaxError: Named export 'context' not found. The requested module 'esbuild' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'esbuild';
const { build, context, default: esbuild } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2
[22:07:53] Finished xterm-addon-clipboard with errors

````

## Details
- Browser and browser version: na
- OS version: Fedora 40
- xterm.js version: master

I'm guessing this isn't a bug per se, but an incompatibility in tool versions

**Comment by Tyriar** [comment]
This works fine for me on Debian/node v20.16.0, did you run `yarn setup`? Not sure what could be causing this only for Fedora?

![image](https://github.com/user-attachments/assets/fbc6afcf-add4-4611-b3be-4d4a8174505b)

**Comment by jerch** [comment]
Also works for me under ubuntu 22. It sounds like your esbuild module is still a CJS one - maybe outdated esbuild version?

**Comment by PerBothner** [comment]
Running `yarn setup`:
````
$ yarn setup
yarn run v1.22.10
warning ../package.json: No license field
$ npm run install-addons

> @xterm/xterm@5.5.0 install-addons
> node ./bin/install-addons.js

pulling addon dependencies...
Skipped addon-attach
Skipped addon-canvas
Preparing addon-clipboard
warning ../../../package.json: No license field
Skipped addon-fit
Preparing addon-image
warning ../../../package.json: No license field
Preparing addon-ligatures
warning ../../../package.json: No license field
Skipped addon-search
Skipped addon-serialize
Skipped addon-unicode-graphemes
Skipped addon-unicode11
Skipped addon-web-links
Skipped addon-webgl
$ npm run build

> @xterm/xterm@5.5.0 build
> npm run tsc


> @xterm/xterm@5.5.0 tsc
> tsc -b ./tsconfig.all.json

error TS2688: Cannot find type definition file for 'trusted-types'.
  The file is in the program because:
    Entry point of type library 'trusted-types' specified in compilerOptions

  src/vs/tsconfig.json:37:4
    37    "trusted-types",
          ~~~~~~~~~~~~~~~
    File is entry point of type library specified here.


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by jerch** [comment]
Whats your node/npm/yarn version? Works with node 20 for me.

**Comment by PerBothner** [comment]
$ node --version
    v20.12.2
    $ yarn --version
    1.22.10
    $ npm --version
    10.5.0

**Comment by Tyriar** [comment]
> error TS2688: Cannot find type definition file for 'trusted-types'.

@PerBothner try deleting node_modules and running yarn again. Those should come through here:

https://github.com/xtermjs/xterm.js/blob/cb3bd463a5aabda47c135481ba4dbf7ccf8680ab/package.json#L80

**Comment by jerch** [comment]
Hmm weird, I have almost the same versions (yarn is at 1.22.22 here). Can you retry with a clean clone? This is what I did:

```
git clone ...
cd xterm.js
yarn
yarn setup
yarn run esbuild-watch
...
```

If you dont want to lose working branches on an older project checkout, `yarn clean` + removing node_modules  - then starting over with `yarn`, ... should get you going. Evtl. you have to repeat the node_modules removal also in addon folders (wasn't needed here).

**Comment by PerBothner** [comment]
Removing `node_modules` fixed things. I should probably just default to that when I get one of these weird error messages ...

I'm not thrilled with the instructions in Contributing to have 4 terminal windows open. That seems inconvenient and easy to lose track of things. It might be helpful to have simple "build from source" instructions (ideally on the home page) separate from "build with automatic rebuild on changes" instructions. The former should probably also mention running `yarn` and `yarn setup` (for those of us who aren't experts on Yarn) unless `yarn esbuild` does that automatically. Note people might want to build from source just to get the current non-released version, even if they're not developing xterm.js.

**Comment by jerch** [comment]
Hmm indeed, the `yarn && yarn setup` went missing on the instructions side?

**Comment by Tyriar** [comment]
Added to the building section

**Comment by PerBothner** [comment]
Thanks for the advise!
