### ISSUE TITLE
Run a command which runs for a long time will awlays make the browser crash

### ISSUE THREAD

**Issue by birenjack** [xtermjs/xterm.js#5114]
## Details
- Browser and browser version: Chrome/126.0.0.0
- OS version: 5.0 (Windows NT 10.0; Win64; x64) 
- xterm.js version: 5.5.0

### Steps to reproduce

1. setup a terminal with websocket
2. run a command which runs for a long time
3. it will make the memory of the browser crash

**Comment by birenjack** [comment]
The memory of browser is used by the xterm terminal, only close other browser pages can help some, how can I make the terminal memory to be smaller.

**Comment by jerch** [comment]
Your issue is the first ever reporting this - therefore my first guess is, that something on your side causes this. Note that xterm.js takes create care in what it hold in memory and recycles data structures.

Can you provide simple repro instructions?

**Comment by birenjack** [comment]
> Your issue is the first ever reporting this - therefore my first guess is, that something on your side causes this. Note that xterm.js takes great care in what to hold in memory and even recycles data structures.
> 
> Can you provide simple repro instructions?
> 
> Edit: I just double checked in the demo - running `ls -lR /` (runs ~1min and produces ~250MB here) multiple times in a row:
> 
> * JS context memory: 6 - 10 MB (mostly xterm.js data structures)
> * chrome tab memory: 40 - 100 MB (whole tab memory consumption as reported when hovering over the tab title)
> * settles pretty early on a number, no further growing tendency
> * same for WebGL or DOM renderer

en~
Some user may open ten or more browser pages, when I run a long time command, it real crash ervery time. Next time, I will provide a picture of this crash event.

**Comment by birenjack** [comment]
This command may excute for about 1 ~ 3 hours

**Comment by birenjack** [comment]
> This command may excute for about 1 ~ 3 hours

and with a lot of logs info~ I guess, these logs make the memory crash ?

**Comment by birenjack** [comment]
Thank you, I just got an idea, I will try to ctrl the amount of logs in a constant time, let me try one more time~

**Comment by birenjack** [comment]
> > Some user may open ten or more browser pages, when I run a long time command, it real crash ervery time. Next time, I will provide a picture of this crash event.
> 
> Thats too late and not very helpful, as the crash already happened. You'd have to dig into system monitor to identify the naughty browser window/tab while it is still running, from there into its page (content) and so on.
> 
> Also opening tons of tabs is not a good idea, if you are under memory constraints. Blame the browser vendors for making things bigger and bigger with every release.
> 
> > This command may excute for about 1 ~ 3 hours
> 
> Which command? Although the command doesn't really matter. What matters is, how your page integrates xterm.js.
> 
> > and with a lot of logs info~ I guess, these logs make the memory crash ?
> 
> Depends again on the integration. A serious integration needs flow control to not stack up websocket messages before xterm.js can digest them. But even that should not create any OOM, as xterm.js will just evict them and warn you about it in the console log. See https://xtermjs.org/docs/guides/flowcontrol/ for details.
> 
> Again - can you provide simple repro instructi

This command is private, I will provide you more pictures when I catch this crash agan.

**Comment by jerch** [comment]
> This command is private, I will provide you more pictures when I catch this crash agan.

No, plz dont. A webpage and its content is not meant to crash a browser, same with a page containing xterm.js. JS is not meant to be able to do that. If it happens to you, report it elsewhere but not to the repo of one page's component, unless you have clear evidence, that it is caused by that. Again I highly doubt that it is caused by xterm.js, the browser is still meant to handle that gracefully by closing a page/tab, not to fully crash.

**Comment by birenjack** [comment]
> > This command is private, I will provide you more pictures when I catch this crash agan.
> 
> No, plz dont. A webpage and its content is not meant to crash a browser, same with a page containing xterm.js. JS is not meant to be able to do that. If it happens to you, report it elsewhere but not to the repo of one page's component, unless you have clear evidence, that it is caused by that. Again I highly doubt that it is caused by xterm.js, the browser is still meant to handle that gracefully by closing a page/tab, not to fully crash.

here is my code, I can not find some where else cause this crash.  
![image](https://github.com/user-attachments/assets/b2dcc1b1-3993-4faf-bbc5-abc4fd3f839f)
Normal, the memory is about 400 MB, When the long command run with long logs, over 1.4 GB, that make the browser crash.
Can you give me some advice for my code ?
Thanks. jerch

`<script lang="ts" setup>
import _ from 'lodash'
import screenfull from 'screenfull'

import { Terminal } from '@xterm/xterm'
import { WebLinksAddon } from '@xterm/addon-web-links'
import { FitAddon } from '@xterm/addon-fit'
import { AttachAddon } from '@xterm/addon-attach'
import { ClipboardAddon } from '@xterm/addon-clipboard'

import '@xterm/xterm/css/xterm.css'

import fullScreenIcon from '@/assets/svg/fullscreen.vue'

import { copyClick } from '@/utils/utils'

/**
 * base module
 */
const props = defineProps({
  webSocketServer: {
    type: String,
    required: false,
    default: ''
  }
})
const emit = defineEmits(['close'])
const socket = new WebSocket(props.webSocketServer)
const attachAddon = new AttachAddon(socket, { bidirectional: true })
const clipboardAddon = new ClipboardAddon()

/**
 * main module
 */
const baseOptions = {
  rendererType: 'canvas',
  windowsMode: true,
  convertEol: true,
  fontSize: 13,
  tabStopWidth: 4,
  fontFamily:
    'Menlo For Powerline, Consolas,Liberation Mono,Menlo,Courier,monospace',
  theme: {
    foreground: '#d2d2d2',
    background: '#2b2b2b',
    cursor: '#adadad',
    black: '#000000',
    red: '#d81e00',
    green: '#5ea702',
    yellow: '#cfae00',
    blue: '#427ab3',
    magenta: '#89658e',
    cyan: '#00a7aa',
    white: '#dbded8',
    brightBlack: '#686a66',
    brightRed: '#f54235',
    brightGreen: '#99e343',
    brightYellow: '#fdeb61',
    brightBlue: '#84b0d8',
    brightMagenta: '#bc94b7',
    brightCyan: '#37e6e8',
    brightWhite: '#f1f1f0'
  }
}
const terminal = new Terminal(baseOptions)

let updateTimer: any

socket.onopen = () => {
  updateTimer = setInterval(() => {
    socket.send('')
  }, 5000)
}

/**
 * enable addon module
 */
terminal.loadAddon(new WebLinksAddon())
terminal.loadAddon(attachAddon)
terminal.loadAddon(clipboardAddon)

const fitAddon = new FitAddon()
terminal.loadAddon(fitAddon)

terminal.attachCustomKeyEventHandler((arg: any) => {
  if (arg.ctrlKey && arg.code === 'KeyC' && arg.type === 'keydown') {
    const selection = terminal.getSelection()
    if (selection) {
      navigator.clipboard.writeText(selection)
      return false
    }
  }

  if (arg.ctrlKey && arg.code === 'KeyV' && arg.type === 'keydown') {
    navigator.clipboard.readText().then(text => {
      socket.send(text)
    })
  }
  return true
})

const terminalRef = ref()

const init = () => {
  if (terminalRef.value) {
    terminal.open(terminalRef.value)
  }
  fitAddon.fit()
  const timer = setTimeout(() => {
    socket.send(
      JSON.stringify({
        cols: terminal.cols,
        rows: terminal.rows
      })
    )
    clearTimeout(timer)
  }, 500)
}

window.addEventListener('resize', () => {
  fitAddon.fit()
  socket.send(
    JSON.stringify({
      cols: terminal.cols,
      rows: terminal.rows
    })
  )
})

onMounted(() => {
  init()
})

onBeforeUnmount(() => {
  socket.close()
  updateTimer && clearInterval(updateTimer)
  updateTimer = null
})

const isFullScreen = ref<boolean>(false)
const fullScreenRef = ref()

const handleFullScreen = async () => {
  const element = fullScreenRef.value

  if (screenfull.isEnabled) {
    await screenfull.toggle(element)
  }
}

screenfull.on('change', () => {
  isFullScreen.value = screenfull?.isFullscreen
})
</script>

<template>
  <div ref="fullScreenRef" class="min-h-[300px] max-h-[800px] h-full">
    <div
      :class="['flex w-full justify-end', isFullScreen ? 'px-6 pt-3' : 'pt-6']"
    >
      <el-button type="primary" link @click="handleFullScreen">
        <fullScreenIcon></fullScreenIcon>
        <span class="full ml-2">{{ isFullScreen ? '退出全屏' : '全屏' }}</span>
      </el-button>
    </div>
    <div ref="terminalRef" class="w-full h-full mt-3"></div>
  </div>
</template>
`

**Comment by birenjack** [comment]
> > This command is private, I will provide you more pictures when I catch this crash agan.
> 
> No, plz dont. A webpage and its content is not meant to crash a browser, same with a page containing xterm.js. JS is not meant to be able to do that. If it happens to you, report it elsewhere but not to the repo of one page's component, unless you have clear evidence, that it is caused by that. Again I highly doubt that it is caused by xterm.js, the browser is still meant to handle that gracefully by closing a page/tab, not to fully crash.

Thanks, jerch.
Today, we run the conmand again, the terminal works well! I just change 'xterm' to '@xterm/xterm'.
