### ISSUE TITLE
When run into alternate, BaseY never get updated and can't scroll the view

### ISSUE THREAD

**Issue by McDaddy** [xtermjs/xterm.js#5120]
everything goes well under active view, but when running into alternate view(like less command), buffer.alternate.baseY is always 3. is there is any thing I can do to enable the scroll?

**Comment by jerch** [comment]
Well the alternate buffer is meant to be a "canvas" for rows * cols characters, and nothing beyond that.

> is there is any thing I can do to enable the scroll?

This is restriction is hard-coded, as it is quite fundamental to terminal emulators. You can try to change the setup of the buffer to also have a scrollback here:

https://github.com/xtermjs/xterm.js/blob/cb3bd463a5aabda47c135481ba4dbf7ccf8680ab/src/common/buffer/BufferSet.ts#L38-L52

But notice, that this might break the terminal or result in weird glitches, as follow-up code in renderers or addons might not expect any scrollbuffer semantics on the alternate buffer at all.

**Comment by Tyriar** [comment]
As designed as @jerch mentioned. Fork/edit at your own risk, I wouldn't though 😅
