### ISSUE TITLE
Follow GTK/Qt color scheme for frame and background and text

### ISSUE THREAD

**Issue by bphd** [xtermjs/xterm.js#5121]

**Comment by Tyriar** [comment]
xterm.js is a lib for the web; it's up to the embedder of the library to create a theme to color it to match gtk/qt if they so wish

**Comment by bphd** [comment]
> to create a theme

It's not about creating a theme here but rather a mechanism

> to color it to match gtk/qt

**Comment by jerch** [comment]
[Terminal.options.theme](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#optional-theme) or OSC 4 / 10 / 11 / 12 (all under https://xtermjs.org/docs/api/vtfeatures/#osc) does not work for you?
