### ISSUE TITLE
xterm-headless connot run in v8

### ISSUE THREAD

**Issue by BinaryRyan** [xtermjs/xterm.js#5134]
### Steps to reproduce

1. read xterm-headless from js file
2. run this script in v8 engine

```log
ReferenceError: navigator is not defined [recovered]
ReferenceError: exports is not defined [recovered]
ReferenceError: window is not defined [recovered]
```

```go
	iso := v8.NewIsolate()

	xtermScript, err := fileutil.ReadFileToString("../js/xterm-headless.js")
	if err != nil {
		panic(err)
	}

	ctx := v8.NewContext(iso)
	_, err = ctx.RunScript(xtermScript, "xterm-headless.js")
	if err != nil {
		panic(err)
	}
```

**Comment by Tyriar** [comment]
Plain v8 isn't a target we compile for, it should work fine in node as VS Code runs it in the pty host node process just fine.

**Comment by jerch** [comment]
Plain v8? Eww thats like Javascript in a box, it misses all typical outer connectivity features / APIs, which make a browser JS engine or nodejs useful.
