### ISSUE TITLE
Make addon peer dependencies friendly with npm

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#5135]
Right now we have stable xterm.js declared as a peer dependency of the beta addons. This ends up causing issue with npm https://github.com/microsoft/vscode/issues/196795#issuecomment-2298982911. To fix this we probably need to update the peer dependency when we update the version of the addons on publish

**Comment by jerch** [comment]
Glad to see a move back to npm - it is not only the official package installer, it also got much better lately, but more importantly we also encountered issues with yarn in other projects, where its package cache might apply the wrong package version (and we had to switch back to npm, mind you - those issues are all around ESM support in various 3rd party packages, grrr).

**Comment by Tyriar** [comment]
npm has been plenty fast for a long time and I think we also switched before package-lock.json was a thing.
