### ISSUE TITLE
font issues in DOM renderer

### ISSUE THREAD

**Issue by jerch** [xtermjs/xterm.js#5164]
Moved from #4881

![image](https://github.com/user-attachments/assets/5f745d6a-99b5-4c45-a88d-6c4b555ec604)

Also this kind of things. Just why? I use Roboto Mono, which is a mono-width font. Just why we need any corrections ?

![image](https://github.com/user-attachments/assets/69e3bdb7-a66b-4d62-bce4-5d2db2b62f33)

_Originally posted by @socketpair in https://github.com/xtermjs/xterm.js/issues/4881#issuecomment-2357512396_

**Comment by jerch** [comment]
@socketpair:

Which browser and which xtermjs version is that? There were some corrections applied to the width measuring in the newer xtermjs versions.

Can you retry with these global patches applied:
```javascript
// width measure container
document.querySelector('.xterm-width-cache-measure-container').style.fontVariantLigatures='none';
// terminal output
document.querySelector('.xterm-rows').style.fontVariantLigatures='none';
```
> Just why we need any corrections ?

Because, other than in the canvas/webgl renderer, we have no control in the DOM renderer how the browser's font renderer gonna output a certain glyph on the screen. It may pick the glyph from a different font or apply different widths for bold/italics. Furthermore some monospace fonts are not perfectly monospaced for all their glyphs. Btw - in your mc output it looks like the bold glyphs cause the misalignment.

_Originally posted by @jerch in https://github.com/xtermjs/xterm.js/issues/4881#issuecomment-2357835623_

**Comment by jerch** [comment]
@jerch are there any tunable to turn off these corrections ? If a font is not perfect we will not use it!

It would also be nice to get your recommendations on which font is the most trouble-free. And possibly well-known bad monospace fonts (like Roboto Mono).

My colleague will write answer to your questions above in few minutes.

_Originally posted by @socketpair in https://github.com/xtermjs/xterm.js/issues/4881#issuecomment-2357994990_

**Comment by jerch** [comment]
> are there any tunable to turn off these corrections ? If a font is not perfect we will not use it!

Nope, thats not configurable from outside, as half of the renderer logic relies on the measurement results.

I just tried to repro it under ubuntu 22 with chrome and firefox and Roboto Mono. Its all fine here with the repo demo, even if I switch to russian locale in mc. So my guess - its either a version issue (which xtermjs version you are using?) or some CSS font settings on the terminal container in your integration not being compatible.

> It would also be nice to get your recommendations on which font is the most trouble-free. And possibly well-known bad monospace fonts (like Roboto Mono).

Roboto Mono behaves correctly for me. Also I dont have any list of bad or good fonts. The letter-spacing trick should level out single glyph metrics issues (thats why even Arial will work there), but it cannot address higher level font features like certain ligatures out of the box. So in general try to avoid monospace fonts using ligature trickery, that are not grid stable (see https://github.com/xtermjs/xterm.js/issues/5156 for some context).

_Originally posted by @jerch in https://github.com/xtermjs/xterm.js/issues/4881#issuecomment-2358998409_

**Comment by jerch** [comment]
@jerch, hello! We use @xterm/xterm 5.5.0, @xterm/addon-attach 0.11.0 and @xterm/addon-fit 0.10.0.
I reproduced the [bug](https://github.com/xtermjs/xterm.js/issues/4881#issuecomment-2357512396) with Roboto Mono on Google Chrome 126.0.6478.182 and Firefox 128.0 on Linux Mint, @socketpair use Fedora.

One more example with `Юж` letters:
![image](https://github.com/user-attachments/assets/b0b1dbbf-c798-4bd7-acca-a1e65dd9c426)

_Originally posted by @ithrforu in https://github.com/xtermjs/xterm.js/issues/4881#issuecomment-2361818228_

**Comment by jerch** [comment]
@ithrforu Can you repro it with the demo of the repo?

Edit: Looks correct to me here with Roboto Mono
![image](https://github.com/user-attachments/assets/cc95e596-9b2d-48d4-8dc6-306b8b82edb3)

_Originally posted by @jerch in https://github.com/xtermjs/xterm.js/issues/4881#issuecomment-2361851763_

**Comment by socketpair** [comment]
@ithrforu please take a look to this issue

**Comment by ithrforu** [comment]
@jerch can you help with the sandbox for reproduction?
Roboto Mono won't load in the [codesandbox](https://codesandbox.io/p/sandbox/zen-kepler-qgw487?file=%2Fsrc%2FTerminalMain.tsx%3A12%2C36&from-embed=&workspaceId=8cdac5a3-7e96-4eb8-8c5c-e7bf35d2ddbc) :(

**Comment by jerch** [comment]
> @jerch can you help with the sandbox for reproduction? Roboto Mono won't load in the [codesandbox](https://codesandbox.io/p/sandbox/zen-kepler-qgw487?file=%2Fsrc%2FTerminalMain.tsx%3A12%2C36&from-embed=&workspaceId=8cdac5a3-7e96-4eb8-8c5c-e7bf35d2ddbc) :(

Nope, I have never done anything with codesandbox, no clue about it.

**Comment by jerch** [comment]
@ithrforu Thats not valid javascript. Whats `import 'some.css';` supposed to mean? Is this some sort of vite magic? Also you put webfonts there. This most likely creates a race condition between the terminal initialization and the fonts being loaded. For the char measuring to work it is _important_, that the font is fully available at the time `terminal.open` is called.

**Comment by ithrforu** [comment]
@jerch, @Tyriar, i tried to load fonts and css from index.html with Roboto Mono from [Google Fonts](https://fonts.google.com/specimen/Roboto+Mono):
https://github.com/ithrforu/xterm-sandbox/blob/another-example-with-preload/index.html

It works correctly without xterm-webfont.

In the first example i used Roboto Mono from fontsource ([1](https://fontsource.org/fonts/roboto-mono), [2](https://www.npmjs.com/package/@fontsource/roboto-mono)). I think problem with `Юж` was here.

I also tried to use [xterm-webfont](https://www.npmjs.com/package/xterm-webfont) and it doesn't work:
https://github.com/ithrforu/xterm-sandbox/blob/preload-with-xterm-webfont/index.js
![image](https://github.com/user-attachments/assets/c7313786-e014-4d8b-a5f7-03ca6e803e43)
```
Uncaught TypeError: this.getOption is not a function
    at terminal.loadWebfontAndOpen (xterm-webfont.js?v=9060b432:172:33)
    at index.js:16:10
```

**Comment by jerch** [comment]
@ithrforu It seems xterm-webfont is quite outdated and still relies on an old API call.

If you want to use a webfont - does `document.fonts.ready` work for you? It returns a promise, so you could place your fonts in early loaded css and then put the whole terminal init code behind that promise.

**Comment by ithrforu** [comment]
@jerch, yes, with `document.fonts.ready` i can use something like this:
```
**
 * @see https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts
 */
const loadApplicationFonts = async (): Promise<void> => {
  try {
    const applicationFontsSet = await document.fonts.ready;
    const fontsLoadingState = [...applicationFontsSet].map((font) => font.load());
    const fontsLoadingResult = await Promise.all(fontsLoadingState);
    const failedFonts = fontsLoadingResult.filter((font) => font.status !== 'loaded');

    if (failedFonts.length > 0) {
      throw new Error(`These fonts failed to load: ${failedFonts.join(', ')}.`);
    }
  } catch (error) {
    throw new Error(`Some fonts can not be loaded:\n${error}.`);
  }
};

....
await loadApplicationFonts()
terminal.open()
```
The peculiarity is that the `await document.fonts.ready` does not mean that all fonts have loaded and return FontFaceSet:
https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet

**Comment by ithrforu** [comment]
@jerch thank you! 
I tried to used combination of your and mines examples and replace Roboto Mono with [Cascadia Mono](https://github.com/microsoft/cascadia-code?tab=readme-ov-file#font-variants).

It works correctly.

**Comment by ithrforu** [comment]
@jerch offtop: where can i find a @xterm/addon-canvas source code?
https://github.com/xtermjs/xterm.js/tree/master/addons

**Comment by jerch** [comment]
@ithrforu The canvas ddon got removed for the next major version and you prolly should not rely on it anymore. v5.5 still contains the source (https://github.com/xtermjs/xterm.js/tree/5.5.0/addons).

Gonna close this issue as resolved, plz open questions not directly related to issues or code bugs under questions.

**Comment by KernelDeimos** [comment]
Does anyone know a powerline-supporting font that works? I'm really struggling, every font I've tried has too much space between letters and setting `letterSpacing` to fix this reprods #4881

**Comment by jerch** [comment]
@ithrforu FYI - created a new addon, which hopefully makes webfonts more easy to deal with, see #5178.

**Comment by devhaozi** [comment]
> @ithrforu Here is a variant of your sandbox example above, which seems to work correctly (also added bold and some test output):
> 
> ```js
> import { Terminal } from '@xterm/xterm';
> import { FitAddon } from '@xterm/addon-fit';
> import '@xterm/xterm/css/xterm.css';
> import "@fontsource/roboto-mono"; 
> import "@fontsource/roboto-mono/400.css"; 
> import "@fontsource/roboto-mono/400-italic.css";
> import "@fontsource/roboto-mono/700.css"; 
> import "@fontsource/roboto-mono/700-italic.css";
> 
> 
> function initTerminal() {
>   const terminal = new Terminal({
>     fontFamily: "Roboto Mono",
>   });
> 
>   const fitAddon = new FitAddon();
> 
>   terminal.loadAddon(fitAddon);
> 
>   const terminalContainer = document.getElementById('xterm-container');
> 
>   terminal.open(terminalContainer);
> 
>   terminal.onKey(({ key }) => {
>     terminal.write(key);
>   });
> 
>   const resizeObserver = new ResizeObserver(() => {
>     requestAnimationFrame(() => fitAddon.fit());
>   });
> 
>   resizeObserver.observe(terminalContainer);
> 
>   // write test after some time...
>   setTimeout(() => {
>     terminal.write('0123456789\r\n');
>     terminal.write('\x1b[1m0123456789\r\n');
>     terminal.write('\x1b[0;3m0123456789\r\n');
>     terminal.write('\x1b[1;3m0123456789\r\n');
>     terminal.write('\x1b[mЮжЮжЮжЮжЮж\r\n');
>     terminal.write('\x1b[1mЮжЮжЮжЮжЮж\r\n');
>     terminal.write('\x1b[0;3mЮжЮжЮжЮжЮж\r\n');
>     terminal.write('\x1b[1;3mЮжЮжЮжЮжЮж\r\n');
>   }, 100);
> }
> 
> document.fonts.ready.then(
>   fontFaceSet => Promise.all(Array.from(fontFaceSet).map(el => el.load())).then(initTerminal)
> );
> ```
> 
> The issue with the fontsource webfont is, that they splitted the font across multiple font files. Each of these font files are not loaded until really needed by the browser, but by then it is already too late for xtermjs. The `Promise.all` instead forces the browser to really load every font file, before it continues with the terminal setup.
> 
> Edit: Tested with chrome && firefox, no clue about safari.
> 
> Would be nice, if xterm-webfont addon would get an upgrade to reflect the newer APIs (@vincentwoo).

It working for me, but seems not support variable fonts.

**Comment by jerch** [comment]
@devhaozi What do you mean by "variable fonts"? Non monospace fonts? Those should also work, but ofc will look quite ugly due their glyphs getting grid positioned. In general it is not a good idea to run a terminal with a variable width font.

Or do you mean variable as of changing the font of an already running terminal? Thats also possible, but there you have to make sure, that all webfont assets are readily loaded before doing the font switch.

**Comment by devhaozi** [comment]
> @devhaozi What do you mean by "variable fonts"? Non monospace fonts? Those should also work, but ofc will look quite ugly due their glyphs getting grid positioned. In general it is not a good idea to run a terminal with a variable width font.
> 
> Or do you mean variable as of changing the font of an already running terminal? Thats also possible, but there you have to make sure, that all webfont assets are readily loaded before doing the font switch.

Like this: https://fontsource.org/fonts/jetbrains-mono/install
It has two types: variable and static.

**Comment by jerch** [comment]
Idk what variable vs. static means in this context. Care to explain?

**Comment by devhaozi** [comment]
> Idk what variable vs. static means in this context. Care to explain?

Variable fonts contain all weights from 100 to 900, which can be adjusted at will.
Static fonts, on the other hand, need to be imported separately for each weight.

**Comment by devhaozi** [comment]
> > Idk what variable vs. static means in this context. Care to explain?
> 
> Variable fonts contain all weights from 100 to 800, which can be adjusted at will without repeated import. Static fonts, on the other hand, need to be imported separately for each weight.

Oh I found the reason, the variable font needs to use the `JetBrains Mono Variable` family name, I was wrong, it is actually suppot.

**Comment by jerch** [comment]
@devhaozi 
I just read it up here: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_fonts/Variable_fonts_guide

This is indeed not fully supported yet, as it needs font variation settings, which are currently not exposed/configurable from terminal API. So yes it will work, if you wait a font-face object to be loaded with those subspecs and only have that one as only font-family in `document.fonts`. It is not possible to actually switch to a variation currently (the browser would pick whatever was the default in that font asset file). This also applies to the new webfont addon in https://github.com/xtermjs/xterm.js/pull/5178.
