### ISSUE TITLE
Cursor canvas render crashed

### ISSUE THREAD

**Issue by lcw0622** [xtermjs/xterm.js#5191]
## Details
- Browser and browser version:Chrome 129.0.6668.90 (Official Build) (arm64)
- OS version: macOS 14.4.1
- xterm.js version: 4.6.0

### Steps to reproduce

1. open xterm, then you can see only this icon, and it's belongs to canvas `xterm-cursor-layer`,if you remove this element it will be OK
![image](https://github.com/user-attachments/assets/132074d9-63b6-4d74-bd97-50dfef058adc)
2. seconds later，this canvas recovered

this bug not appear in Safari

Thank you

**Comment by Tyriar** [comment]
You're on an ancient very much unsupported version, update to this https://www.npmjs.com/package/@xterm/xterm
