### ISSUE TITLE
Not working on Mobile and tablet

### ISSUE THREAD

**Issue by forbesus** [xtermjs/xterm.js#5192]
All key events are not working on mobile and tablet.
When hitting the "Enter" key, all letters that I typed are removed automatically

## Details
- Browser and browser version: Chrome
- OS version: Android 12, 13
- xterm.js version: 5.5.0

### Steps to reproduce

1. Open term on android or tablet
2. Type any letters
3. Hit the "Enter" key

**Comment by Tyriar** [comment]
duplicate of https://github.com/xtermjs/xterm.js/issues/3600
