### ISSUE TITLE
The cols attribute is invalid

### ISSUE THREAD

**Issue by houpengcheng** [xtermjs/xterm.js#5204]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. set {cols:150(>default:80)} in Terminal is invalid
2. It may even bring other problems，such as Not wrapping lines leads to overlap，
3. or when use addon-fit ,When wrapping, the first part will overlap .
4. wish your apply.thank you!

**Comment by jerch** [comment]
@houpengcheng What do you mean by is invalid? Do you get an error?
