### ISSUE TITLE
Rewriting alt-ARROW STDIN to hard-coded 1;5?

### ISSUE THREAD

**Issue by imsnif** [xtermjs/xterm.js#5238]
Hey, I didn't use the issue template because I have a specific question about xterm.js's behavior. I hope it's alright.

I'm working on integrating `xterm.js` with [zellij](https://github.com/zellij-org/zellij) and I'm encountering an issue stemming from these lines: https://github.com/xtermjs/xterm.js/blob/41e8ae395937011d6bf6c7cb618b851791aed395/src/common/input/Keyboard.ts#L162

I'm happy to be corrected on this one, but as far as I know, in both linux and mac the standard ANSI notation for these sequences is `<CSI>1;3B` for alt + down-arrow, `<CSI>1;3A` for up-arrow, etc. I'm a little puzzled by why these are sent as `<CSI>1;5B`, etc.

This is obviously also causing Zellij not to properly interpret these keys. Right now I'm getting around this with `term.AttachCustomKeyEventHandler` - which is alright for my use-case, but I'm wondering if there's an underlying reason here that I'm missing and perhaps should account for.

Thanks!

**Comment by Tyriar** [comment]
It's explained right above that:

https://github.com/xtermjs/xterm.js/blob/41e8ae395937011d6bf6c7cb618b851791aed395/src/common/input/Keyboard.ts#L157-L163

This is one of the non-standard things xterm.js does that's a little risky to change at this point. If you want the standard behavior `attachCustomKeyEventHandler` is indeed the right thing to do
