### ISSUE TITLE
types error in @xterm/addon-xxx 

### ISSUE THREAD

**Issue by destinytaoer** [xtermjs/xterm.js#5259]
when i import CanvasAddon, eslint show some error here
![image](https://github.com/user-attachments/assets/f9995ce3-d6fd-4e59-888d-e5211fd4b792)

## Details
- Browser and browser version: none
- OS version: none
- xterm.js version: 5.4.0

i see that import statement is in the top of xxx.d.ts
```ts
import { Terminal, ITerminalAddon, IEvent } from '@xterm/xterm';

declare module '@xterm/addon-canvas' {
  //...
}
```
i think that it needs to put it into declare module like this
```ts
declare module '@xterm/addon-canvas' {
  import { Terminal, ITerminalAddon, IEvent } from '@xterm/xterm';
  //...
}
```

and in my project, we need to check third_part libs. there are many error in addon modules. why export src dir in npm package? Is that necessary？
![image](https://github.com/user-attachments/assets/4b5288c8-0c44-4dc4-82f8-463d7dfcc43e)

### Steps to reproduce

1. 
2.

**Comment by Tyriar** [comment]
We have removed the canvas addon, next stable release of xterm.js (6.0.0) will no longer ship it

**Comment by destinytaoer** [comment]
> We have removed the canvas addon, next stable release of xterm.js (6.0.0) will no longer ship it

I will learn 6.0.0 soon. But this qustion is not just the canvas addon, also search addon, webgl addon and so on.

can you give me some advise to help me fix it?
