### ISSUE TITLE
Document fit addon and relation with attach

### ISSUE THREAD

**Issue by ficristo** [xtermjs/xterm.js#554]
If I call the `fit` function after calling the `open` function but before the `attach` one, doesn't seems to do anything.
If I call it after `attach` then the terminal is resized.
If this is the expected behaviour would be nice it was documented and the demo changed.

## Details
- Browser and browser version: Firefox 51
- OS version: Windows 10
- xterm.js version: 2.3.2

### Steps to reproduce

1. Add the fit and attach addon
2. Call `term.fit()` before `term.attach()`
3. Try to reverse the calls.

**Comment by Tyriar** [comment]
I think the demo is good enough documentation on this currently, more than happy to accept improvements to the .d.ts files (which the documentation on the site will be derived from soon).
