### ISSUE TITLE
Implement Shell Integration

### ISSUE THREAD

**Issue by ctwise** [xtermjs/xterm.js#576]
iTerm2 has implemented (and documented) proprietary escape code for shell integration. This integration is used to provide command-line markers, jump between command-line entries in the terminal history, track successful commands, provide a terminal-level command history, track the current host and current directory. These escape codes originated with the (now defunct) FinalTerm project.

Please implement these escape codes - https://iterm2.com/documentation-escape-codes.html

Shell Integration/FinalTerm
iTerm2's Shell Integration feature is made possible by proprietary escape sequences pioneered by the FinalTerm emulator. FinalTerm is defunct, but the escape sequences are documented here.

Definitions
OSC stands for Operating System Command. In practice it refers to this sequence of two ASCII characters: 27, 93 (esc ]).
ST stands for String Terminator. It terminates an OSC sequence and consists either of two ASCII characters 27, 92 (esc \) or ASCII 7 (bel).
OSC sequences always begin with OSC, are followed by a sequence of characters, and are terminated with ST.

Most OSC codes begin with a number (one or more decimal digits), which we'll call the "command" in this document. If the command takes parameters it will be followed by a semicolon and the structure of the rest of the body of the OSC sequence is dependent on the command. Well-behaved terminal emulators ignore OSC codes with unrecognized commands.

Concepts
The goal of the FinalTerm escape sequences is to mark up a shell's output with semantic information about where the prompt begins, where the user-entered command begins, and where the command's output begins and ends.

[PROMPT]prompt% [COMMAND_START] ls -l
[COMMAND_EXECUTED]
-rw-r--r-- 1 user group 127 May 1 2016 filename
[COMMAND_FINISHED]

Escape Sequences
FinalTerm originally defined various escape sequences in its original spec that are not supported by iTerm2 and are not described in this document. The best remaining references to these codes are in iTerm2's source code.

FTCS_PROMPT

OSC 1 3 3 ; A ST

Sent just before start of shell prompt.

FTCS_COMMAND_START

OSC 1 3 3 ; B ST

Sent just after end of shell prompt, before the user-entered command.

FTCS_COMMAND_EXECUTED

OSC 1 3 3 ; C ST

Sent just before start of command output. All text between FTCS_COMMAND_START and FTCS_COMMAND_EXECUTED at the time FTCS_COMMAND_EXECUTED is received excluding terminal whitespace is considered the command the user entered. It is expected that user-entered commands will be edited interactively, so the screen contents are captured without regard to how they came to contain their state. If the cursor's location is before (above, or if on the same line, left of) its location when FTCS_COMMAND_START was received, then the command will be treated as the empty string.

FTCS_COMMAND_FINISHED

OSC 1 3 3 ; D ; Ps ST

OSC 1 3 3 ; D ST (for cancellation only)

The interpretation of this command depends on which FTCS was most recently received prior to FTCS_COMMAND_FINISHED.

This command may be sent after FTCS_COMMAND_START to indicate that a command was aborted. All state associated with the preceding prompt and the command until its receipt will be deleted. Either form is accepted for an abort. If the Ps argument is provided to an abort it will be ignored.

If this command is sent after FTCS_COMMAND_EXECUTED, then it indicates the end of command prompt. Ps is the command's exit status, a number in the range 0-255 represented as one or more ASCII decimal digits. A status of 0 is considered "success" and nonzero indicates "failure." The terminal may choose to indicate this visually.

If neither FTCS_COMMAND_START nor FTCS_COMMAND_EXECUTED was sent prior to FTCS_COMMAND_FINISHED it should be ignored.

iTerm2 Extensions
iTerm2 extends FinalTerm's suite of escape sequences.

SetUserVar

OSC 1 3 3 7 ; S e t U s e r V a r = Ps1 = Ps2 ST

Sets the value of a user-defined variable. iTerm2 keeps a dictionary of key-value pairs which may be used within iTerm2 as string substitutions, such as in the Badge.

Ps1 is the key.

Ps2 is the base64-encoded value.

ShellIntegrationVersion

OSC 1 3 3 7 ; S h e l l I n t e g r a t i o n V e r s i o n = Pn ; Ps ST

OSC 1 3 3 7 ; S h e l l I n t e g r a t i o n V e r s i o n = Pn ST (deprecated)

Reports the current version of the shell integration script.

Pn is the version.

Ps is the name of the shell (e.g., bash).

iTerm2 has a baked-in notion of the "current" version and if it sees a lower number the user will be prompted to upgrade. The version number is specific to the shell.

RemoteHost

OSC 1 3 3 7 ; R e m o t e H o s t = Ps1 @ Ps2 ST

Reports the user name and hostname.

Ps1 is username. Ps2 is fully-qualified hostname.

CurrentDir

OSC 1 3 3 7 ; C u r r e n t D i r = Ps1 ST

Reports the current directory.

Ps1 is the current directory.

**Comment by parisk** [comment]
This is a very interesting proposal, despite implementing handling for proprietary escape codes into the core of xterm.js is not likely to happen.

What we could do that sounds a good idea to me is make escape code handling more pluggable, so it can be extended by the user.

This way "advanced" xterm.js users can provide tighter integration between the consumer app and what runs in the terminal. TBH I would really like us to use this in SourceLair as well, it has it's fair set of use cases.

I would like to hear @Tyriar's opinion on this, since he is the one that has dealt with input handling mostly.

**Comment by Tyriar** [comment]
I was actually looking into something similar to this using a pretty different approach in https://github.com/Microsoft/vscode/issues/20676

What I don't like about this shell integration is that it doesn't really work for Windows, but it would probably lead to better and more reliable results than in https://github.com/Microsoft/vscode/issues/20676. We could probably make the Parser pluggable and allow addons to access it to implement this.

**Comment by ctwise** [comment]
In case you're interested, iTerm 2 provides shell integration for Bash, ZSH and Fish. Here's the link for the bash integration - https://iterm2.com/misc/bash_startup.in

iTerm2 will then automatically mark command prompts with a triangle in the left-hand column. Based on the error code of the command it will color failed commands red. You can also hop between prompts in your history which is truly handy when you have a lot of output.

<img width="171" alt="2017-03-02 13-27-19" src="https://cloud.githubusercontent.com/assets/5510/23521264/3f0f5820-ff4c-11e6-85ef-9a5cec380edc.png">

**Comment by ctwise** [comment]
More information on what iTerm 2 does with the integration is here - https://iterm2.com/documentation-shell-integration.html

**Comment by Tyriar** [comment]
Also for tcsh it appears https://iterm2.com/misc/tcsh_startup.in

**Comment by feamsr00** [comment]
Sorry to barge in :) Considering the functional model of the parser, it would seem to be very logical for it to emit parse events. Is it possible to just get the parser to do that for now? That might be a better move while waiting for extension component architecture to evolve. Especially if XT starts to have a more evented arch anyway.

This way implementers (that need ctrl codes) can start planing\testing rough functionality and when (if?) components\observers are developed, implementers can just wrap the new functionality in the freshly prescribed components.

**Comment by PerBothner** [comment]
I wrote a [proposal for a shell integration proptocol](https://gitlab.com/PerBothner/terminal-specifications/blob/master/proposals/semantic-prompts.md).

Comments (unless xterm.js-specific) should preferably be discussed [here](https://gitlab.freedesktop.org/terminal-wg/specifications/issues/4), for now.

Complications (compared to the simple ITerm2/FinalTerm protocol) that I try to address include multi-line inputs (with optional continuation prompt); implicit input-area termination (in case the only customization hook available to the user is a prompt string); and right-prompts.  Another feature I want to make more common is being able to move the input cursor using mouse clicks, implemented (when enabled) by translating to arrow keys. - see the proposal.

I will be implementing and testing the proposed protocol in [DomTerm](http://domterm.org), whiicg already supports most of the funtionality.

**Comment by Tyriar** [comment]
With the addition of the parser hooks added ([`parser.addCsiHandler`](https://github.com/xtermjs/xterm.js/blob/ff790236c1b205469f17a21246141f512d844295/typings/xterm.d.ts#L1001), etc.) this can now be implemented completely in an application embedding xterm.js. I think this makes more sense than trying to put support for shell integration inside xterm.js itself as shell integration is not a standard tech.

**Comment by ZedYeung** [comment]
> With the addition of the parser hooks added ([`parser.addCsiHandler`](https://github.com/xtermjs/xterm.js/blob/ff790236c1b205469f17a21246141f512d844295/typings/xterm.d.ts#L1001), etc.) this can now be implemented completely in an application embedding xterm.js. I think this makes more sense than trying to put support for shell integration inside xterm.js itself as shell integration is not a standard tech.

Any example? How could we utilize this to integrate shell? e.g. capture the input command like ls

**Comment by Tyriar** [comment]
@ZedYeung it's probably a fair bit of work to do this in a solid way, we've already got plenty of other stuff to do.

**Comment by Tyriar** [comment]
If you're after an example of how to use addCsiHandler generally you can see how we use it internally to handle various sequences:

https://github.com/xtermjs/xterm.js/blob/1c72a665679688ea36d88c6796b0d61d754eab86/src/InputHandler.ts#L182-L227

**Comment by jerch** [comment]
Additionally this might need some clarification about the involved things:

Per's proposal is a nice way to get "markup support" in terminals that would help typical terminal programs like shells, pagers etc. with several tasks. But that's one side of the story - the terminal. You can add those features to xterm.js with the commands @Tyriar has shown.

The other side - for real "shell integration" you'd need a shell (or pager or....) supporting those sequences to actually do something with it. Now you have 2 ways to get there - write your own shell supporting it or patch/advertise support in other common shells.

> e.g. capture the input command like ls

This might work with good results for some programs, depending on the quality of your heuristics. Still it is doomed to fail for others.

**Comment by PerBothner** [comment]
My proposal has been [moved to here](https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md).

This [article](http://per.bothner.com/blog/2019/shell-integration-proposal/) shows examples of what you can do with the proposal, with screenshots using [DomTerm](https://domterm.org). (I prefer a styling for "commands" that is relatively minimalistic.)

Not sure what you mean by "capture the input command like ls".  Perhaps you mean capturing the output?  My proposal doesn't directly do that, but does provide a building-block to do that: Specifically explicitly delineating what is the output and what isn't.  DomTerm has a builtin pager, like an automatic `less` filter.

**Comment by SterlingButters** [comment]
> If you're after an example of how to use addCsiHandler generally you can see how we use it internally to handle various sequences:
> 
> https://github.com/xtermjs/xterm.js/blob/1c72a665679688ea36d88c6796b0d61d754eab86/src/InputHandler.ts#L182-L227

@Tyriar @jerch Could you expound on the usage of the parser and how one might achieve correct usage?

**Comment by Tyriar** [comment]
@SterlingButters there's an issue to create a guide on the website on this https://github.com/xtermjs/xtermjs.org/issues/116
