### ISSUE TITLE
Should cmd+left/right be printing escape sequences?

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#597]
I don't think xterm considers the meta key, cmd+left and cmd+right however send 9D and 9C. Regardless we should align with or allow consumers to align with how standard terminal emulators work in this regard on macOS (Terminal.app and iTerm2).

@parisk interested in your input as I don't normally work on a Mac.

Code: https://github.com/sourcelair/xterm.js/blob/ff29fd69a316c59f55dbec1cc86f00c262b73275/src/xterm.js#L1430
VS Code discussion: https://github.com/Microsoft/vscode/pull/22005#issuecomment-286524481

**Comment by parisk** [comment]
From what I can see, when <kbd>Cmd</kbd> is pressed macOS won't send anything to the terminal  (so <kbd>Cmd</kbd> + <kbd>←</kbd>/<kbd>→</kbd> do nothing).

This is quite interesting and actually simplifies things.

Does gnome-terminal utilize the meta key somehow?

**Comment by Tyriar** [comment]
win+left/right in gnome-terminal move the cursor left and right.

**Comment by parisk** [comment]
OK, what about doing the following:

- **macOS**: Send no input when <kbd>Cmd</kbd> is pressed
- **The rest of platforms**: Ignore the <kbd>Meta</kbd> key

**Comment by Tyriar** [comment]
@parisk did you check both Terminal.app and iTerm2's behavior?

**Comment by parisk** [comment]
Yep, it's the same. Both are doing either "system stuff" with <kbd>Cmd</kbd> pressed (e.g. new tabs, windows etc.) or nothing.

**Comment by Tyriar** [comment]
@parisk skipping it on all platforms is probably the best idea then, AFAIK within xterm the meta key is the alt key, so cmd/win can pretty safely be skipped.

**Comment by parisk** [comment]
I am all-in for this 👍

**Comment by Eugeny** [comment]
Latest xterm from the master branch seems to be still sending unrecognized escape seqs for `Cmd-LeftArrow` and `Cmd-RightArrow` on macOS, while simultaneously swallowing the event and preventing the host from handling it.

I'd say a better way would be to ignore Cmd-Arrow combos on macOS completely and pass the event upwards.

**Comment by luxcium** [comment]
I do not experience this problem in [zeit/hyper](https://github.com/zeit/hyper) or [VS Code](https://github.com/microsoft/vscode) is this still an issue ?

**Comment by Tyriar** [comment]
Yes it still happens, it prints D or C for me here. It doesn't in VS Code because there's a keybinding that overrides it.
