### ISSUE TITLE
Could not linkify the URL with super-long TLDs.

### ISSUE THREAD

**Issue by tmyt** [xtermjs/xterm.js#601]
Currently Linkifier implimentation could not linkify the URL with super-long TLDs.

Linkifier assume the TLD lenght in 2 - 6 chars in the here,
https://github.com/sourcelair/xterm.js/blob/master/src/Linkifier.ts#L14

But, some new gTLDs have over 6 chars. (ex: .enterprises, .foundation, and so on).
Needs to update `tldClause` to support these super-long TLD names.

## Details
- xterm.js version: master (ff29fd6)

### Steps to reproduce

1.  echo 'https://example.enterprises'
2.  URL does not linked.

**Comment by Tyriar** [comment]
PRs welcome, should be an easy fix :+1:

**Comment by jens1o** [comment]
@Tyriar Would happy to contribute, for me 256 ought be enough for everybody? ;)

**Comment by Tyriar** [comment]
@jens1o the concern with working more on the web link matcher as is, is that it will eventually be replaced by something much smarter that can understand things like when brackets () are within or outside of a URL, see https://github.com/sourcelair/xterm.js/issues/583

And that one's a bit more work 😛 as it's replacing all the regex logic with a parser that will probably work by finding the start of a link and then move forward until the end is found.

**Comment by jens1o** [comment]
Oh, sorry. I think I won't meet your expectations... Let's hope there will be some nice contributor with some good skills :D

**Comment by Tyriar** [comment]
No worries 😄

**Comment by Tyriar** [comment]
Merging into https://github.com/xtermjs/xterm.js/issues/583
