### ISSUE TITLE
Support 1337 escape sequence to show inline images

### ISSUE THREAD

**Issue by cristynkells** [xtermjs/xterm.js#614]
## Details
- Browser and browser version: all
- OS version: all
- xterm.js version: 2.4.0 

### Feature request
Is there a way to view images from the command line?

by either clicking on the image (much like the linkify addon) or via a command:

$ cat vacation-beach-pic.png

**Comment by Tyriar** [comment]
Clicking on the link to open the image is possible via the an API that's experimental at the moment. It's experimental because it's likely to change but here is the current syntax:

```js
// Add a link for a particular regex and handle when it's clicked.
xterm.registerLinkMatcher(/\w\.png/, function (mouseEvent, imageFile) => {
  // imageFile is the text of the link
});
```

**Comment by cristynkells** [comment]
Hi Daniel, thank you for your speedy reply! Was wondering if there a way to display html on the fly through a set of control characters? Similar to how DomTerm uses “\e]72;<html>\a” sequences ? 

 

https://lwn.net/Articles/670078/

**Comment by Tyriar** [comment]
@cristynkells there isn't right now, standard xterm doesn't support anything like that so if we did want to support it it would certainly need to be in an addon.

**Comment by DonJayamanne** [comment]
@Tyriar 
>it would certainly need to be in an addon

Is this supported today? Right now I don't see how this can be done even with an add on. Basically I'm trying to investigate what it would take to build something with inline plots (something we already have in other IDE, PTVS, RTVS, Spyder, and the like e.g. https://ipython.org/ipython-doc/3/interactive/qtconsole.html).

**Comment by Tyriar** [comment]
@DonJayamanne since this issue I've become aware of a standard some terminals have implemented for displaying terminals. Because of this we could add it to the core library, it's probably a pretty hefty feature though in terms of making sure everything is correct, particularly relating to getting the scroll bar right as right now there's no such thing as variable height rows in the viewport.

**Comment by DonJayamanne** [comment]
> implemented for displaying terminals

Yes, I found iTerm does this.

Thanks for getting back.

**Comment by ebraminio** [comment]
Hi there.I opened [a related issue on VSCode](https://github.com/Microsoft/vscode/issues/44436) and redirected here I wonder supporting iTerm2 image feature a possibility it can be used as easy as this,

    printf "\n\033]1337;File=;inline=1:`cat a.png | base64`\a\n"`

And I already used on [a project](https://github.com/harfbuzz/harfbuzz/commit/6c844ae8e89f52f5f40eace66bb987544fc316e3).

**Comment by ztmr** [comment]
@ebraminio If we are going to draw graphics and possibly some more hypertext, I would really like to be able to specify coordinates where to render it, not just blindly dump it under the current cursor position... check #1176.

**Comment by rs** [comment]
@ztmr: You can use other termcap commands to move the cursor and display the image wherever you want. That is what I do in [jplot](https://github.com/rs/jplot) to redraw the image in place.

**Comment by ztmr** [comment]
@rs: Oh, of course, how could I forget about CUP! :o)

**Comment by jerch** [comment]
+1 for custom escape sequences. Best place to start with those is to implement OSC and DCS subparser interfaces, where custom subparser can hook into the main parser. Also the main parser still has some escape code flaws and the test library still needs to be completed to cover all the basic sequences.

Btw DEC already had some terminal extensions for graphics and image loading (REGIS and SIXEL). No clue if it would make much sense to implement those, since the browser env of xterm.js has much better capabilities to draw such things.

**Comment by jerch** [comment]
SIXEL is supported by some programs (gnuplot) and some terminals (mlterm, xterm), there is even libsixel (https://github.com/saitoha/libsixel) for easy conversion. Seems not to be as dead as I thought...

**Comment by soccermitchy** [comment]
From my point of view, Sixel support would be nice for a monitoring dashboard-style thing. Could easily show gauges and stuff in it - there are even browsers, iirc, that support rendering with it.

**Comment by Tyriar** [comment]
Here are some screenshot of how image placement/selection works in iterm2, not totally sure how the margins work yet.

<img width="332" alt="screen shot 2018-07-24 at 6 48 52 am" src="https://user-images.githubusercontent.com/2193314/43142692-d5653932-8f0d-11e8-9e19-e0803d7c03f5.png">

<img width="321" alt="screen shot 2018-07-24 at 6 53 49 am" src="https://user-images.githubusercontent.com/2193314/43142923-6aaba670-8f0e-11e8-94a6-3b40bf60e0f7.png">

**Comment by jerch** [comment]
I think SIXEL is the way to go for images, also made some progress with an early SIXEL parser (https://github.com/jerch/node-sixel).
Once we are settled with the new buffer layout and marker/decorator rework this should be straight forward to integrate.

**Comment by PerBothner** [comment]
While sixel is a "standard" (and I think it is desirable to support it), it is a rather obsolete standard. It is not well suited to today's hardware, software, or workflow. Very few people have heard of it, and very few programs produce or consume it.  It is extremely inefficient for photographic images (does not support many colors well), and it is constrained to images whose height is a multiple of 6.

The concept (if not necessarily the specifics) of the 1337 escape sequence is a lot easier for most people (and programs) to work with: a base64-encoding of standard current image-file formats: png, gif, jpeg, and optionally svg.  I think that is the way to go. The 1337 syntax is a bit clunky (the `inline` option defaults to 0 - huh?), but it works. Is there some other escape sequence with similar functionality used by other terminals?

(While DomTerm doesn't support the 1337 escape sequence, it supports the same idea, except you have to wrap the data in an `<img>` or `<svg>` html element.   Adding support for the 1337 escape sequence should be trivial.)

**Comment by jerch** [comment]
@PerBothner Imho the ticky part is #1901, as soon as we solved the question how to deal with the grid and layering for "foreign boxes" I see no reason why we should not support image formats that are natively supported by the browser env. But for that I'd love to see a broader discussion (on @egmontkob's platform?) and maybe rethink the sequence. For sixel the sequence is already there for 30ys, still the correct handling of the representation state is wonky (again #1901).

**Comment by PerBothner** [comment]
I fully agree with @jerch's most recent comment.

**Comment by PerBothner** [comment]
I created an [issue](https://gitlab.freedesktop.org/terminal-wg/specifications/issues/12) on the freedesktop.org [terminal-wg](https://gitlab.freedesktop.org/terminal-wg) to try to standardize "simple image display". I hope we can get agreement on a suitable semi-portable escape sequence.  Possibly the 1337 escape sequence (though it has some issues); possibly something else.

**Comment by sdegutis** [comment]
I think this can be broken down into two issues:

1. Handling of arbitrary escape code sequences, either internally or externally (via API). This is a useful feature for more than just images, and is orthogonal to the concept of *what* is shown or even *how* it's shown. It just needs a function callback API.

2. Hosting of foreign DOM content, in this case an image, but other content has the same properties: a DOM element with an x,y,w,h relative to a sub-grid of cells on the terminal's character grid.

Both of them would help me a lot, but in different ways. It might be worth creating two new issues for each.

**Comment by sdegutis** [comment]
> * Currently every single row is a fixed length, are images to be shown fixed to this grid as well or should the size be different? For example with row height=10px and image height=15px, should the image consume 15px or 20px on the terminal). If the latter we may want to tackle #1140 first.

I just assumed the image would still be 15px and the extra 5px would be empty, so that the image would be "overlayed" over the rows. Considering cell width/height is so small, I don't see any drawbacks to the *slight* wasted pixel space of this solution.

**Comment by Tyriar** [comment]
> Handling of arbitrary escape code sequences, either internally or externally (via API). This is a useful feature for more than just images, and is orthogonal to the concept of what is shown or even how it's shown. It just needs a function callback API.

Already done:

https://github.com/xtermjs/xterm.js/blob/bd0d267d972a1aab4777cddecf9bf8196d7aa44f/typings/xterm.d.ts#L1060-L1127

My comment is probably a little out of date, @jerch has been the main one looking at images with this, https://github.com/xtermjs/xterm.js/pull/2503 and https://gitlab.freedesktop.org/terminal-wg/specifications/issues/12

**Comment by sdegutis** [comment]
Ah right, yeah I even use that API. Whoops, should have remembered. Thanks.

**Comment by tracker1** [comment]
I do think it would be cool to support sixel as well as 1337 sequence... I do think that whatever is displayed should be potentially resized if too wide, and the space taken padded to a full line height.

May already be possible with the extension, not sure if custom handlers can hook into a given set of columns/rows and the height-width of either to custom render several rows?

Came into this after discovering sixel formats and noticing that it isn't available in the terminals I use most (one of which is vs code).

**Comment by jerch** [comment]
@tracker1 See #2503 for the current development state.

**Comment by trbot86** [comment]
I really hope this is still in active development. (Seems like a PR is stalled waiting for merge into xterm master?)

As a scientist who writes code to run experiments that produce graphs, the ability to visualize these graphs (in VSCode's xterm) without opening external software would be huge.

**Comment by jerch** [comment]
> I really hope this is still in active development. (Seems like a PR is stalled waiting for merge into xterm master?)

Well, originally I intended to add the SIXEL part as sync code (which is almost feature complete), but the image decoding puts quite some pressure on the main thread, which we cannot simply ignore in bigger embedding apps like vscode as it would lead to bad lag spikes. The addons is basically waiting for #3222 to get finished, with that PR we can offload the hard work to a worker thread.

> As a scientist who writes code to run experiments that produce graphs, the ability to visualize these graphs (in VSCode's xterm) without opening external software would be huge.

Yes scientific REPLs with direct graphics dumping caps will benefit alot from this.

**Comment by trbot86** [comment]
That makes perfect sense, and I'm really glad to hear it. Looks like you're down to just MacOS specific test failures, but if the skillset of a CS concurrency/multicore researcher would be useful, feel free to let me know.

**Comment by jerch** [comment]
Well #3222 will take abit more time, it changes several crucial aspects of the parser handlers which needs proper testing. Once it is there the adoption in #2503 should be small.

> if the skillset of a CS concurrency/multicore researcher would be useful, feel free to let me know.

For #2503 I wonder, how much functionality could/should go to the workers in the end. I really would like to use `OffscreenCanvas`, but thats still unlikely to happen, as the API is far from stable across browser engines. If you have more insights/experience regarding this, fee free to discuss the internal addon shaping over there.

**Comment by CoconutMacaroon** [comment]
Any update on this? Having support for Sixel would be helpful for me.

**Comment by jerch** [comment]
Sixel support can now be tested with the `xterm-addon-image` npm package (see https://github.com/jerch/xterm-addon-image for some docs, how to use it).

**Comment by trbot86** [comment]
So now that we have sixel support in xterm.js, is there any chance we can use this version of xterm.js for the vscode integrated terminal? :) 
(As I recall, @Tyriar said that conversation should continue here.)

**Comment by Tyriar** [comment]
@trbot86 I think we could start experimenting with that yes, it's just a matter of finding the time. I'll bring it up in my planning discussion this week.

@jerch btw I created a png decoder recently which is fast and very well tested which you might prefer over png-ts 😉 https://www.npmjs.com/package/@lunapaint/png-codec, I consume it as a git submodule so it's possible you might hit packaging problems that we'd need to work out.

**Comment by jerch** [comment]
> @jerch btw I created a png decoder recently which is fast and very well tested which you might prefer over png-ts wink https://www.npmjs.com/package/@lunapaint/png-codec, I consume it as a git submodule so it's possible you might hit packaging problems that we'd need to work out.

Thats great news. Well, I am actually looking for a fast PNG decoder to be used for the next protocol extension of the module to directly support png and jpg formats (tbh sixel is a really poor format choice). Would your decoder work in a worker context, or does it need browser mainthread-only APIs? And do you happen to have a fast JPG decoder as well by any chance?

**Comment by Tyriar** [comment]
@jerch I think it will work in a worker, if it doesn't I'd want it to. I currently use it in node and main thread browser without problems.

> And do you happen to have a fast JPG decoder as well by any chance?

I will be making one of these eventually, decode to help understand the format and then encode to give full control over how it's written. Currently doing TGA since basic read/write of jpeg is possible via canvas 🙂

**Comment by jerch** [comment]
@Tyriar Well def. check it out for the next image formats in the addon, which then also should provide proper serialize/deserialize functionality (currently not possible with sixel only). In general the GIP protocol discussion is somewhat stalled, so I might come up with an interim solution addressing most issues we already agreed on.
For jpg decoding in a worker I think I cannot rely on canvas yet, as it is not officially supported by safari? Well, its like waiting for ~Godot~ Safari to close certain implementation gaps... :sweat:

**Comment by dvag-sebastian-goeb** [comment]
Any progress on this? https://github.com/xtermjs/xterm.js/pull/2503 seems to have been parked. I would really love to see inline images in VSCode especially (for Jest + Puppeteer screenshot testing in my case).

**Comment by markusbkk** [comment]
Bump

I'd be interested in this, as well.

**Comment by jerch** [comment]
@dvag-sebastian-goeb @markusbkk 
There is inline graphics support with `xterm-addon-image` addon (sixel only atm).

**Comment by markusbkk** [comment]
> @dvag-sebastian-goeb @markusbkk There is inline graphics support with `xterm-addon-image` addon (sixel only atm).
I saw.

Unfortunately, that's not quite the same as iTerm2. I'm working on something that requires iTerm2 image protocol support.

**Comment by blacktop** [comment]
bump 🙏

**Comment by jerch** [comment]
@markusbkk PR for iterm IIP support: https://github.com/jerch/xterm-addon-image/pull/43.

**Comment by jerch** [comment]
Just merged the IIP support. It passes all my basic tests, but since I have no mac to work with I cannot really compare it with iTerm. So if anyone wants to do some digging - a side by side comparison with iTerm's output from different images and `imgcat` settings would be really helpful.

**Comment by wsshin** [comment]
I landed here from the VS Code issue https://github.com/microsoft/vscode/issues/65283.  Could you describe how to test xterm-addon-image in VS Code?  I am willing to test it on my Mac.

**Comment by jerch** [comment]
@wsshin Idk if vscode allows loading custom xterm.js addons - if not, you prolly have to pull source and add it there yourself.

**Comment by Tyriar** [comment]
@wsshin if you want to try test it out in vscode you can search the vscode codebase for xterm-addon-search which is an example usage of an addon from npm

**Comment by trbot86** [comment]
thanks for the tip @Tyriar and the addon @jerch.
it was my first time even compiling vscode, but i managed to hamfist xterm-addon-image into vscode: https://github.com/microsoft/vscode/compare/main...trbot86:vscode:xterm-addon-image

it seemed like i had to start with an old vscode commit (59faab44cd8287e247cfab8c389b9f0f44174bcf) to satisfy the xterm version dependency in xterm-addon-image. there's probably a better way to do this. i'm just a newbie to the code base, node.js, and typescript.

but man it's awesome to see it work!
![image](https://user-images.githubusercontent.com/11655936/228448513-a570e2fa-f18c-4dbd-b95f-9d331c83568b.png)

**Comment by trbot86** [comment]
thanks for that remark. i haven't previously considered disregarding or updating the version requirement of xterm-addon-image. it turns out vscode:HEAD (specifically 10b2a8e42eddf7504f7b6e6b19d73eb5f888d075) compiles and works with xterm-addon-image, even though it's running xterm 5.2.x. i've updated my repo accordingly.

**Comment by trbot86** [comment]
is there any chance of this making it into insiders? i hadn't previously used vscode OSS, and it's starting to set in how limiting it is... not having access to extensions renders it useless...

**Comment by jerch** [comment]
@trbot86 Plz note that there still some loose ends with the addon - most prominent the ability to serialize image data forth and back. So I am not sure, if it is ready for production rollout yet.
I am currently dealing with the serialization issue in https://github.com/jerch/xterm-addon-image/pull/48. This is still in conceptual phase, as there is no prior art to learn from, so it will take a few more weeks to get things sorted out.

**Comment by jerch** [comment]
@Tyriar Should we close this issue, as the addon is in the base repo now?

**Comment by trbot86** [comment]
I can't find a better issue in vscode (that isn't locked) to ask this in, but now that this is implemented in vscode OSS:main, how do we get this into insiders edition?

**Comment by jerch** [comment]
@trbot86 Isnt the insider edition built regularily from vscode's base repo? Because vscode's repo contains all the needed bits, so it should just work imho. Or do you mean something else with "insiders edition"?

**Comment by Tyriar** [comment]
@trbot86 images are now enabled by default in main, stable and insiders. See https://code.visualstudio.com/docs/terminal/advanced#_image-support

**Comment by trbot86** [comment]
Thanks for the link. I had tested the feature without success, but the image I was testing was extremely large (~8k resolution), and it produced no output. It works when using a smaller image.

Do you happen to know offhand how vscode's sixel support is intended to handle images that are too large to fit in the terminal window? Trying to isolate whether the failure is in the program converting the image to sixels, or in vscode or xterm.js.

**Comment by jerch** [comment]
> ... sixel support is intended to handle images that are too large to fit in the terminal window?

@trbot86
Not sure if you mean in terms of memory usage and/or screen coverage:

_memory_
Since images grow rather big with higher resolutions and JS can only address up to 2GB - there a few limits in place to avoid OOM from exhaustive image usage by the addon:
- `pixelLimit` -  default is 16M (e.g. 4096x4096 squared), a sequence trying to allocate more pixels gets cancelled
- `sixelSizeLimit` - default is 25MB, limits the max. size of a single sixel sequence, bigger sequences are again cancelled
- `iipSizeLimit` - default is 20MB, same as `sixelSizeLimit` but for IIP sequences

_screen coverage_
Sixels are currently capped at 16K pixels in x-direction (truncated), but not actively capped in y-direction, only indirectly by `pixelLimit`. Thus it is possible to create an image with 16K x 1024 pixels up to an image with 1 x 16M (better dont try that, the browser engine prolly wont like such a canvas).
Sixel pixels are mapped 1:1 to CSS pixels, image data beyond the viewport to the right is preserved (can be "un-covered" by resizing), excess to the bottom will normally scroll the terminal window. Sixels dont support a resizing policy as IIP does.
Images from IIP have no additional hard caps, only `pixelLimit`. Furthermore IIP supports a resizing policy during image loading (e.g. `width=50%` to resize an image to 50% of the current viewport).

Also see https://github.com/xtermjs/xterm.js/blob/master/addons/xterm-addon-image/README.md.

**Comment by trbot86** [comment]
Thanks for the detailed answer. It sounds like I'm likely butting up against pixelLimit, as the image in question was something like 8000x5000 pixels. I'm not sure how much the sixel format inflates the PNG size, but the image was something like 2-3MB. I think sixels are perhaps quite wasteful, so I could conceivably also hit the sixelSizeLimit. Well, I can probably just avoid trying to show such large images. It would be nice, from a graceful degradation standpoint, to perhaps render a small image explaining the failure when a limit is hit, rather than the actual image. No big deal though. :)

**Comment by jerch** [comment]
8000x5000 pixels? Thats 160 MB in RGBA for just one image - no, you cannot expect this to work in an env with only 2GB address space. If you have hi-res output needs a terminal is prolly not the right tool for it.

If you want reasonable output & performance, then it is better to grab the terminals viewport size (e.g. by `CSI 14 t`) and zoom & tile into your big image on app side just sending the area of interest. Also sixel is not a good choice for that, as it is very costly to encode (needs quantization & dithering) and has poor output quality - IIP is def. the better choice here (better quality with bigger color space, better compression, much faster to generate).

**Comment by trbot86** [comment]
Yes that's totally fair. It makes sense to slice or shrink large images before viewing them. Easy enough to add an imagemagick convert -resize step in a script.
