### ISSUE TITLE
[Question] Is there a way to use color themes like iterm2 or through Xresources?

### ISSUE THREAD

**Issue by arvenil** [xtermjs/xterm.js#629]
Hi,

I can't find this info. Is there a way to colorize terminal with some premade themes? Like https://github.com/mbadolato/iTerm2-Color-Schemes ?

**Comment by parisk** [comment]
Hi @arvenil, while it is not documented, it is possible.

Please take a look at [`src/xterm.css`](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.css) to see how the default theme works.

I will keep this issue open until we document the "theme" API.

**Comment by Tyriar** [comment]
You can see how VS Code does terminal themes here https://github.com/Microsoft/vscode/blob/da6cbf05e74c171c46e0e5f4d29fab256256ae9f/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L219

**Comment by Ortix92** [comment]
I'm still confused on the theme-ing part. Whenever I set the background colors, for some reason an inline style is set with the background color defaulting to black. What is the proper way to define the background color?

**Comment by Tyriar** [comment]
@Ortix92 this is what I see when I set the theme on the demo:

<img width="1055" alt="screen shot 2018-02-01 at 8 19 47 am" src="https://user-images.githubusercontent.com/2193314/35689589-bedc3e08-0728-11e8-83d8-f95aa0099358.png">

Are you setting like this or via the constructor?

**Comment by Ortix92** [comment]
This is some undocumented magic I've never seen before. I will give it a try and update my response

**Comment by Tyriar** [comment]
@Ortix92 the website is a little out of date, I recommend using the .d.ts file to check the API https://github.com/xtermjs/xterm.js/blob/3.0.2/typings/xterm.d.ts#L95

**Comment by Tyriar** [comment]
Oh also this whole thing has completely changed since this issue was created and I think I can close it off. Before (v2) you would do this using CSS, now (v3) you use the JS API mentioned above.
