### ISSUE TITLE
After exiting a utility command on Terminal the cursor is overlapping previous text

### ISSUE THREAD

**Issue by srusu83** [xtermjs/xterm.js#648]
We use xterm inside the terminal of our application and if I write mc utility to open that utility. then type exit from it, the cursor goes on the top of the page even if I was on the middle of the page before entering mc utility. Anything that I write from that moment, it overlaps the text it was before entering the mc utility

## Details
- Browser and browser version: Firefox and Chrome
- OS version: MacOS El Capitan v. 10.11.6
- xterm.js version: latest

### Steps to reproduce
1. Go to  KICK DevUI and enter in Terminal: mc utility
2. After the Mc details are displayed inside the table, return to the terminal cursor to insert another command
3. Check the cursor's position 

Actual result: The cursor goes on the top of the page even if I was on the middle of the page before entering mc utility. Anything that I write from that moment, it overlaps the text it was before entering the mc utility (See the screenshot attached)

Expected result: The cursor has to be at the last position it was before entering the utility
<img width="800" alt="screen shot 2017-04-04 at 15 56 30" src="https://cloud.githubusercontent.com/assets/28291359/25609691/e864e80c-2f28-11e7-926a-4a9b811dc954.png">

**Comment by Tyriar** [comment]
Some questions:

- Can you repro this in the xterm.js demo?
- Do you use node-pty? If so which version?
- What does it look like in Terminal.app?

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
