### ISSUE TITLE
Could not linkify hostnames without TLDs

### ISSUE THREAD

**Issue by 3rf** [xtermjs/xterm.js#653]
I'm frequently copying and pasting links from the integrated terminal in VSCode that point to internal services and local machines. It would be absolutely killer for me if I could ctrl+click those links to open them in the browser.

The regexes for creating links seem to require a TLD, with the exception of localhost. Is there a reason y'all are specifically restricting things that way? Could we instead allow any string that satisfies the hostname standard?

As an added bonus, this fix would take care of https://github.com/sourcelair/xterm.js/issues/601 as well. Would be happy to work on this if it sounds reasonable.

## Details
- Browser and browser version: VSCode
- OS version: Ubuntu 14.04
- xterm.js version:  "Tyriar/xterm.js#vscode-release/1.12" 

### Steps to reproduce

1.  echo "http://myhostname/blah"
2.  hover over it

**Comment by Tyriar** [comment]
@3rf I think the right direction for the link detection is to add a parser instead of relying on regex so that we can be smart about cases like this for example:

```
(text http://some.com/link)
```

https://github.com/sourcelair/xterm.js/issues/583

**Comment by coreygo** [comment]
`http://localhost:8080.` typing that in with ligatures and the right font enabled in VSCode provided an amusing change in the `:` after regex no longer matches. Had me scratching my head till I checked iTerm and remembered VSCode uses xterm.js :)

**Comment by Tyriar** [comment]
@coreygo I didn't think ligatures would break a regex like that?

**Comment by coreygo** [comment]
@Tyriar it's not the font or ligatures that are breaking regex. The combo (Fira Code with Ligatures) makes it a bit more obvious visually when regex no longer matches the URL pattern…

![regex](https://user-images.githubusercontent.com/649879/29897511-0bdcc6f8-8d96-11e7-87c2-2170fac7e7ee.gif)

**Comment by Tyriar** [comment]
Merging into https://github.com/xtermjs/xterm.js/issues/583
