### ISSUE TITLE
Zooming up on Safari on iOS

### ISSUE THREAD

**Issue by tmyt** [xtermjs/xterm.js#658]
Zooming up the web page when `textarea` or `input` got focus on Safari on iOS if `textarea` or `input` has font-size smaller than 16px.

This behavior can avoid to set `font-size: 16px` to `.xterm-helpers textarea`. But I do not decide to apply this style by xterm.js or application.

## Details
- Browser and browser version: Safari 10.0
- OS version:  iOS 10.3.2
- xterm.js version: master (2221f70)

### Steps to reproduce

1. Open xterm web page
2. Tap terminal
3. Zooming up

**Comment by Tyriar** [comment]
Duplicate https://github.com/xtermjs/xterm.js/issues/1101
