### ISSUE TITLE
Be more defensive to prevent issues when resize and writes overlap 

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#661]
https://github.com/sourcelair/xterm.js/issues/164#issuecomment-300991345

**Comment by tht13** [comment]
Use of the `fit` addon seemed to solve my issue, I couldn't quite figure out why that is able to perform the resize correctly though.

**Comment by mejiaa** [comment]
I updated to xterm 2.9.1 today and now get this error when opening new terminals. I created the terminal and then attach a resize handler to resize the terminal using the 'fit' addon. I noticed this error happens whenever the initial number of rows when the terminal starts is later increased by the resize handler. I worked around this by setting something like 200 rows when creating the terminal.

The specific line that triggered this error for me is at https://github.com/sourcelair/xterm.js/blob/5bc0ad879b7b9cdc3c8617478512ba80affc5d79/src/Renderer.ts#L170

**Comment by infnada** [comment]
`Uncaught TypeError: Cannot read property '0' of undefined
    at Renderer._refresh (xterm.js:2333)
    at Renderer._refreshLoop (xterm.js:2295)`

`var data = line[i][0];`

Same error here. But if at the start of the ssh session I type `ls` on a folder with lots of files (like /etc), then I can make a `.fit() ` at any time without problems.

**Comment by shortwavedave** [comment]
I was also seeing this problem. The height parameter of the class was set to a relative value, like 40%. When I added a min-height with a specific pixel value, the error went away.

```
 .terminal {
              background-color: #111;
              bottom: 10px;
              color: #fafafa;
              width: 100%;
              height: 40%;
              min-height: 400px;
              margin: 0 auto;
              padding: 10px;
          }
```

**Comment by amejia1** [comment]
Hello again. By the way, I'm that ghost above. Just decided to merge my account to the one I'm using now.

Anyway, I've been researching this issue and trying to fix it in my Atom plugin. I've pinpointed it down to a problem involving the less program, at least with my plugin. More on that is here (https://github.com/amejia1/atom-xterm/issues/4). So far, I've just been working around the problem but I think the problem I'm facing could be due to either node-pty or xterm.js.

**Comment by Tyriar** [comment]
@amejia1 have you tried reproducing it on the v3 branch?

**Comment by amejia1** [comment]
I had since made changes to the atom-xterm plugin. This issue now only appears whenever I use the 'less' program when I resize the terminal from larger to smaller. I reported this at https://github.com/sourcelair/xterm.js/issues/977 . I'll try the v3 branch.

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
