### ISSUE TITLE
fit addon and multiple xterm instances

### ISSUE THREAD

**Issue by ficristo** [xtermjs/xterm.js#664]
When I call xterm.fit() when terminal is not visible in the page (display: none) it seems to me it does nothing.
Debugging a little, `window.getComputedStyle(term.element.parentElement).getPropertyValue('width')` return `auto` instead of a number.
Is there a way to make it work?
Maybe it is the expected behaviour, if so it would be nice to add some hints in the docs.

## Details
- Browser and browser version: -
- OS version: -
- xterm.js version: 2.6.0

**Comment by Tyriar** [comment]
@parisk this is probably as designed, how can you fit to an element if it's not visible? If so we should add a note to https://xtermjs.org/docs/api/addons/fit/

**Comment by parisk** [comment]
@Tyriar is right on this. The `fit` add-on depends on the element's container element and visibility, so I will add a documentation note for this.
