### ISSUE TITLE
IME - Extra character was inputed if checked the option "auto input text on the fifth key"

### ISSUE THREAD

**Issue by pangwa** [xtermjs/xterm.js#666]
## Details
- Browser and browser version:  Electron 1.6.x/1.7.1
- OS version: macOS Sierra(10.12.4)
- xterm.js version: 

### Steps to reproduce
I'm using a Chinese Wubi input method(Baidu Wubi, could be downloaded from https://srf.baidu.com/input/mac.html ).
1. In the Options settings, check "Input the first candidate word on the fifth key stroke"
2. input "wqvbk "
3. Notice the actual inputed texts are "你好k中", which the correct text should be: "你好中"
4. The fifth key (k) was put into the input box.

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
