### ISSUE TITLE
Input error on Chrome for Android

### ISSUE THREAD

**Issue by flowergrass** [xtermjs/xterm.js#675]
There is strange input behaviour when using xterm.js in Chrome for Android as seen [here](https://photos.google.com/share/AF1QipNiK_IQM4HrtI5_9uzfJmkC1-8-tYJs4BlilVm-3M2PoRud3YoJ2umWvKE3yQ45Ig?key=YzhoeWg1c1UwZXVyaUQ3QWNiOC1yX1N2YWlSNl9B)
Video courtesy of @ajdlinux in this [issue](https://github.com/jessfraz/contained.af/issues/14) and the bug brought to my attention [here](https://github.com/micropython/micropython-unicorn/issues/2)

It looks like previous input characters are duplicated whenever a "special" character (eg backspace, enter) is pressed. However I cannot replicate the initial bug in the video where characters replace one another.

Currently affects Sourcelair and [MicroPython on Unicorn](http://micropython.org/unicorn/) which uses xterm.js version 2.6.0. The problem does not manifest in Firefox for Android 53.0.2.

- Browser: Chrome for Android 58.0.3029.83
- OS: Android 7.1.2

**Comment by Tyriar** [comment]
Likely related to not using the `input` event (see https://github.com/sourcelair/xterm.js/issues/469, https://github.com/sourcelair/xterm.js/issues/265).

Note that we don't explicitly support mobile yet.

**Comment by pro-src** [comment]
I've observed the same behavior in Android 5.1.1 browsers:

* Google Chrome 65.0.3325.109
* Firefox 59.0.2

Each time I press backspace whatever happens to be in the buffer is printed minus the last char. That output is then appended to the buffer and is repeated if I press it again.

**Comment by Tyriar** [comment]
We don't support mobile OS' currently. Track https://github.com/xtermjs/xterm.js/issues/1101 for progress on this.
