### ISSUE TITLE
Bottom menu line lost with application

### ISSUE THREAD

**Issue by pvouzis** [xtermjs/xterm.js#703]
This is the xtern.js and on the other side is ttyd running a utility called horst. Note the menu line on the bottom (Quite Pause Reset ...) 
![image](https://user-images.githubusercontent.com/3309059/27107495-227d659c-504d-11e7-9dde-7767ff629bb3.png)
This line stays there for a few seconds and then it disappears and it looks like this
![image](https://user-images.githubusercontent.com/3309059/27107508-3243d6f0-504d-11e7-97c3-97bb5803c8b0.png)
If I resize the window, the menu line shows up again for a few seconds, and then it goes away

I also uploaded a video on https://gitter.im/sourcelair/xterm.js (May 19 09:51) (I couldn't upload it here since the format is not supported)

## Details
- Browser and browser version: Chrome Version 58.0.3029.110 (64-bit)
- OS version: Windows 10
- xterm.js version: 2.7

### Steps to reproduce

I came across this problem when using horst (https://github.com/br101/horst). Horst is an application that produces lot's of output and I believe this is the reason this problem comes up. In order to reproduce it you'd have to download horst  on linux machine, compile it and run it. In my case, I use a Rasbperry Pi with a WiFi dongle. Any linux workstation running ttyd would be okay to reproduce.  If you need more information on how to reproduce this problem let me know.

**Comment by Tyriar** [comment]
@pvouzis can you try reproduce on v2.8.0?

**Comment by pvouzis** [comment]
I tried v2.8.1 and the problem is still there. Let me know if I can help with troubleshooting.

**Comment by pvouzis** [comment]
@Tyriar let me know if you need help troubleshooting this. I noticed it on this one specific application (horst -- https://github.com/br101/horst). If you need help to reproduce let me know.

**Comment by Tyriar** [comment]
@pvouzis could you post larger screenshots? I can't make out the problem from them as they're thumbnail sized :stuck_out_tongue:

**Comment by pvouzis** [comment]
Look at https://gitter.im/sourcelair/xterm.js on May 19. 
https://files.gitter.im/sourcelair/xterm.js/fikx/image.png
https://files.gitter.im/sourcelair/xterm.js/EMNB/image.png

And also this video: https://files.gitter.im/sourcelair/xterm.js/Ufe5/bash-_WLAN_PRO_---Google-Chrome-5_19_2017-9_43_43-AM.mp4

**Comment by mofux** [comment]
I have seen a similar problem while running `tmux` from xterm.js, where all of the sudden the green bottom bar disappeared. After a window resize it was back. I believe this happened while I was `tail -f` some log files that produced a large amount of output. Unfortunately this is not easy to reproduce 😔

@pvouzis If you can reproduce it reliably, could you try to change the scrollback setting of xterm to a very high value (or `Infinity`) and see if the glitch occurs later than normal? Also, could you post the options your xterm is initialised with? I'm interested in the `useFlowControl` setting in particular.

**Comment by Tyriar** [comment]
@pvouzis at the 9 second mark in that video, and the second screenshot you posted it looks like the scroll bar is at the top of the buffer, not the bottom where it is meant to be. Can you confirm if you scroll down if it's correct?

@mofux `useFlowControl` will probably be removed in the future as it was a bit of a failed experiment, it was never documenting so I'm hoping no one is using it https://xtermjs.org/docs/api/terminal/#options

**Comment by mofux** [comment]
@Tyriar what a pity! I was so excited when you introduced this feature - and I'm using it in my project and it works pretty well. I know there are problems with certain environments that don't support XON/OFF, but as far as I can tell it is the only way to keep the terminal responsive if huge output is generated. Don't you use it for vscode by default?

**Comment by pvouzis** [comment]
@mofux I am checking on useFlowControl

@Tyriar I see what you are saying, but that doesn't make a difference. By the way, if I run this over ssh everything works fine. It happens all the time, so I can reproduce it. Should I try what @mofux proposed with useFlowControl? 

As @mofux said, if I resize the window the bottom line comes back temporarily.

**Comment by Tyriar** [comment]
@mofux it makes everything less stable though as it's shell specific. launch powershell or a huge host of other shells from bash will totally break them ☹️ . We used it and it needed an emergency patch to revert it because it made many environments unusable. It was only good if you only use bash, but it's too hard to dynamically tell. zsh also had big problems with the very popular oh-my-zsh rebinding the XOFF (I think) key to something else.

**Comment by Tyriar** [comment]
Resizing the window will call `Terminal.resize` which does a full refresh of the scrollbar.

@pvouzis I think I'm going to need some clearly defined repro steps when using the demo (clone this repo and `npm i && npm run dev`).

Also are you sure your backing pty is not being resized somehow?

**Comment by pvouzis** [comment]
@Tyriar I tried it with the ttyd and I have the same problem I have when I use my pty. 

If I give you access to a demo console we have, will that help you reproduce and debug?

**Comment by Tyriar** [comment]
@pvouzis if it's reasonably easy to setup and repro with.

**Comment by pvouzis** [comment]
It is easy. I will set it up for you. And I will let you know about it.

**Comment by pvouzis** [comment]
@Tyriar I need an email to set up your account. Can you email me at panos@netbeez.net ?

**Comment by Tyriar** [comment]
@pvouzis sent

**Comment by Tyriar** [comment]
I think this is fixed.

**Comment by pvouzis** [comment]
Thanks @Tyriar I will test it let you know.

**Comment by pvouzis** [comment]
Hi Tyriar,

I can confirm that this problem is solved.

Works great!

Thanks,
Panos
