### ISSUE TITLE
Support screen readers

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#731]
See https://github.com/Microsoft/vscode/issues/8339

**Comment by jluk** [comment]
+1 to this! Is this on track for the August release?

**Comment by Tyriar** [comment]
@jluk yep, haven't started yet though so not 100% on how long it will take.

**Comment by Tyriar** [comment]
Reading the letter back when it's deleted from the prompt does not seem trivial due as the prompt line gets re-written when typing:

```
[?25l
C:\Users\daimms\Documents\dev\Tyriar\xterm.js>l[0K
[48G[?25h
[?25l
C:\Users\daimms\Documents\dev\Tyriar\xterm.js>ls[0K
[49G[?25h
[?25l
C:\Users\daimms\Documents\dev\Tyriar\xterm.js>l[0K
[48G[?25h
```

**Comment by Tyriar** [comment]
The following work in NVDA:

- Hovering a line to read it out
- Typing reading out the letter that was added

The following does not work:

- Backspace reading out the letter that was deleted
- Moving left/right in the prompt reading the letter on the cursor
- Running a command reading the output (nothing happens)

**Comment by Tyriar** [comment]
Fixed in 1182

**Comment by SiulSalas** [comment]
Mouse hovering on the Visual Studio Code terminal stopped working with NVDA

**Comment by Tyriar** [comment]
@SiulSalas you're better off creating an issue in the vscode repo
