### ISSUE TITLE
crash by vim

### ISSUE THREAD

**Issue by crazystory** [xtermjs/xterm.js#742]
## Details
- Browser and browser version: chrome 58.0.3029.110
- OS version:  macos 10.12.5
- xterm.js version:  2.7.0

### Steps to reproduce

1. Enter: vim
2. Websocket crash log is: Invalid UTF-8 in text frame

Xterm.js sent out a special data to the server, I caught it by wireshark.
But the another server can work and have no special data.

**Comment by Tyriar** [comment]
Looks like it's a problem with your websocket layer not xtermjs as it's vim that's crashing on your server.
