### ISSUE TITLE
[SelectionManager] Select the word underneath the cursor on contextmenu

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#778]
If a user right clicks on a word or url in the terminal, the word should be automatically selected, so it can be copied without having to select it first. This would mimic the default behaviour of Terminal.app, Chrome and most other UIs that allow text selection. I can try to create a PR with this feature if desired.

**Comment by Tyriar** [comment]
I think it would be good to support this for macOS only, a PR would be awesome! One thing to keep in mind is that it generally doesn't seem to select whitespace in the programs I tested, currently [`SelectionManager._selectWordAt`](https://github.com/sourcelair/xterm.js/blob/8fab079ad6cbd8ea8ce3004c4ba4b338ec76aae8/src/SelectionManager.ts#L686) will select whitespace so you'll need to add an extra parameter to that function or something.

**Comment by mofux** [comment]
I was under the assumption that this would be the default behaviour for Windows and Linux too. How about making it platform dependant by default, but configurable through a config flag?

**Comment by Tyriar** [comment]
@mofux sounds good if it's default on macOS only. It would be cool to have opt-in support on other platforms.

**Comment by Tyriar** [comment]
Is it really blocked? I would have thought you'd check MouseEvent for whether it was a right click and/or listen to `contextmenu`?

**Comment by mofux** [comment]
@Tyriar I thought I would just hook into the mousedown handler of the selection manager (the part that is changed by #780), check if options.rightClickSelectsWord is true, selection is currently empty and evt.button is 2 (right mouse button) and basically trigger the same action that is done for double-click (which should select the word underneath the cursor). Then, term.defaults.rightClickSelectsWord would only be true if Browser.isMac

**Comment by Tyriar** [comment]
Right now the right click logic is contained within Clipboard.ts which is called by listening to contextmenu or mousedown depending on the browser. This should probably go inside rightClickHandler which already has the `SelectionManager` passed in.

**Comment by Tyriar** [comment]
Fixed with https://github.com/xtermjs/xterm.js/pull/1114
