### ISSUE TITLE
Background is rendered improperly when specifying standard CSI code \033[40m

### ISSUE THREAD

**Issue by jmwilkinson** [xtermjs/xterm.js#782]
Running the escape sequence `\033[40m` [should set the background to a standard black](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors). However, it results in a more grey background, which can be reset using `\033[0m`.

It looks as though the background color is being interpreted as "bright" rather than normal. 

It appears to be due to https://github.com/sourcelair/xterm.js/blob/master/src/xterm.css#L229

This could be replaced with:

```css
.terminal .xterm-bg-color-0 {
    background-color: #000000;
}
```

and it would behave as expected.

## Details
- Browser and browser version:  All browsers 
- OS version: All
- xterm.js version: 2.7.0, 2.8.1

### Steps to reproduce

[JS Fiddle](https://jsfiddle.net/6zr98d1c/)

```
  <!doctype html>
  <html>
    <head>
      <link rel="stylesheet" href="bower_components/xterm.js/dist/xterm.css" />
      <script src="bower_components/xterm.js/dist/xterm.js"></script>
    </head>
    <body>
      <div id="terminal"></div>
      <script>
      	var term = new Terminal();
        term.open(document.getElementById('#terminal'));
        term.write('I am \033[40mbroken\033[0m $ ')
      </script>
    </body>
  </html>
```
![image](https://user-images.githubusercontent.com/17836030/28087968-2764049c-6639-11e7-9b32-955a24d1bf00.png)

**Comment by parisk** [comment]
Ha! Interesting. I am putting this on the milestone of the 3.0 release.

The best way to solve this is to start using a CSS preprocessor, in order to keep consistent colors across different points of the stylesheet.

**Comment by Tyriar** [comment]
This was actually intentional so that you could see the black color on the background, I'm not opposed to changing it to #000 though. You would also want to change `.terminal .xterm-color-0`

**Comment by Tyriar** [comment]
Deferring to unblock v3

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.

**Comment by jmwilkinson** [comment]
This is still an issue, and there is no longer an obvious workaround using CSS.

**Comment by jmwilkinson** [comment]
Related, it is unclear why the color won't reset when switching between foreground blacks:

![screen shot 2019-01-31 at 3 42 23 pm](https://user-images.githubusercontent.com/17836030/52093255-6f468180-256f-11e9-84c1-7b9370009962.png)

**Comment by Tyriar** [comment]
@jmwilkinson because your `$PS1` doesn't start with `\x1b[0m`

**Comment by jmwilkinson** [comment]
@Tyriar I don't follow.... what does that have to do with changing between black and bright black? Or with the default black background not matching the `\x1b[40m` black background?

**Comment by jmwilkinson** [comment]
So I am almost certain there is a better way to do this, but in `InputHandler.js`, this will make the colors consistent at least:

```js
            } else if(p == 40) {
                bg = DEFAULT_ATTR && 0x1ff
            } else if (p >= 41 && p <= 47) {
                bg = p - 40;
            }
```

I do not know/couldn't find where `curAttr` is actually being converted the colors, so I don't know what the "real" bug is... but this at least fixes the behavior.

**Comment by Tyriar** [comment]
Oh I misunderstood, I think that behavior is as expected, doing another 30m isn't meant to clear the bright flag.

Terminal.app:

<img width="355" alt="screen shot 2019-01-31 at 5 44 46 pm" src="https://user-images.githubusercontent.com/2193314/52097465-fef42c00-257f-11e9-9962-eba7358e2eaa.png">

iTerm:

<img width="345" alt="screen shot 2019-01-31 at 5 45 01 pm" src="https://user-images.githubusercontent.com/2193314/52097468-01568600-2580-11e9-96aa-bef08aa45a25.png">

**Comment by jmwilkinson** [comment]
@Tyriar Ok, that makes sense. What about the behavior of `echo -e '\x1b[40m'`?

**Comment by jmwilkinson** [comment]
@Tyriar The problem is that 40m is not black, it is grey. The default background color is black- I get this can be changed with theming so the default will not longer be black, but *if* black is used for the background it should be the same as the black used for 40m. It should be consistent.

**Comment by Tyriar** [comment]
@jmwilkinson it was an intentional change to make the colors different in the default theme so they could be differentiated, they are different. The reason "default" is treated differently is because it could be black, white, anything, and terminal programs don't know if it's light or dark.

**Comment by jmwilkinson** [comment]
@Tyriar I understand the distinction between "default" and explicitly using black. But if no theming is used, the default background is black. This should not be differentiated from 40m. It is not, as far as I am aware, differentiated in any other vt100 compliant terminal. There should not be a separate color "default black" as opposed to just "black".

**Comment by Tyriar** [comment]
@jmwilkinson [macOS' default terminal behaves the same as xterm.js](https://github.com/xtermjs/xterm.js/issues/782#issuecomment-459801357). This is not some rule in a spec or anything but your personal preference, personally I think it's better to make them distinct because otherwise black background isn't emphasized at all when it is meant to be. Just change the theme in your implementation, easy fix.

**Comment by jmwilkinson** [comment]
@Tyriar Ok, so according to ECMA 48 3rd edition, you are technically correct. The default background is "implementation defined", meaning it does not need to adhere to any of the other available colors, and can have an entirely separate color for the black background.

That being said... Mac os does not behave like that. Nothing behaves like that.

![screen shot 2019-02-01 at 9 52 42 am](https://user-images.githubusercontent.com/17836030/52140315-4b367f00-2607-11e9-870d-19bca63d5931.png)

Still, if there is an easy way to fix it without changing the internals of xtermjs, I am very interested in that.

**Comment by Tyriar** [comment]
> Ok, so according to ECMA 48 3rd edition, you are technically correct. The default background is "implementation defined", meaning it does not need to adhere to any of the other available colors, and can have an entirely separate color for the black background.

There are several reasons I'm resistant to change this:

- Embedders can easily customize this (see below)
- It's provides more information and could catch bugs
- Some programs use black background for emphasis, Powershell is an example of this as the default background color is blue

> Mac os does not behave like that. Nothing behaves like that.

Maybe I changed the background color to be a lighter black 🤔.

> Still, if there is an easy way to change it without changing the internals of xtermjs, I am very interested in that.

```ts
// Change the color of black
terminal.setOption('theme', {
  black: '#000000',
  brightBlack: '#000000'
});
```

I wouldn't be surprised if you didn't find this because our API documentation isn't that great. I normally refer people to the .d.ts file:

https://github.com/xtermjs/xterm.js/blob/73ec8a89a0756614187fb34669b5ea4165a52d7c/typings/xterm.d.ts#L729

**Comment by jmwilkinson** [comment]
@Tyriar Well, no idea what that's doing, but the text remains in the bolded state, which keeps it consistent.

It would be kind of nice to make it the lighter weight, but experimenting with `fontWeight` and `fontWeightBold` hasn't changed anything.

**Comment by jmwilkinson** [comment]
@Tyriar Changing `experimentalCharAtlas` to `none` causes the lighter font weight to be used, although I still don't understand what's actually happening to cause that.

**Comment by Tyriar** [comment]
@jmwilkinson I can't seem to reproduce that?

<img width="311" alt="screen shot 2019-02-01 at 12 30 08 pm" src="https://user-images.githubusercontent.com/2193314/52147950-20572580-261d-11e9-9691-52f6b3656bd9.png">

Can you reproduce it with a single echo -e like above? And does it reproduce if you switch rendererType to dom? If so you can inspect the DOM and see what attributes are being added.

**Comment by jmwilkinson** [comment]
@Tyriar Sure, here you go. Also to be clear this is without a modification to the `experimentalCharAtlas` property being set.

I also don't see this behavior at all when the renderer type is dom.

![screen shot 2019-02-01 at 1 41 36 pm](https://user-images.githubusercontent.com/17836030/52151339-9b253e00-2627-11e9-81b0-d93960b89b17.png)

**Comment by jerch** [comment]
Well there is something off comparing DOM renderer and the canvas renderer - at least the DOM currently does not care for the `drawBoldTextInBrightColors` setting before doing the bright shift.

On code level this determines whether to do the bright shift:
- canvas renderer https://github.com/xtermjs/xterm.js/blob/db9aa5c88be6d6cbe043098f32467db9f45527dd/src/renderer/BaseRenderLayer.ts#L262-L264
- DOM renderer https://github.com/xtermjs/xterm.js/blob/db9aa5c88be6d6cbe043098f32467db9f45527dd/src/renderer/dom/DomRendererRowFactory.ts#L91-L98

They certainly do not the same thing. Question is - whats right or intended behavior here? (Sorry for my ignorance, seems I cannot get it from the comments above.)

**Comment by Tyriar** [comment]
> at least the DOM currently does not care for the drawBoldTextInBrightColors setting before doing the bright shift.

Looks like we have an issue for it: https://github.com/xtermjs/xterm.js/issues/1773
