### ISSUE TITLE
Consider implementing automated vttest tests if possible

### ISSUE THREAD

**Issue by parisk** [xtermjs/xterm.js#80]
## Links
- http://invisible-island.net/vttest/vttest.html

**Comment by jerch** [comment]
This should be possible with a similar approach to the xterm test cases. We can just record in- and output of a single vttest test case and compare the results. Some of the tests need a visual check - those could be done by hand or something like selenium tests in an automated fashion.

**Comment by parisk** [comment]
Instead of Selenium we could go with [jsdom](http://npmjs.org/package/jsdom) to make it more lightweight.

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
