### ISSUE TITLE
Lines of the terminal get rewritten

### ISSUE THREAD

**Issue by LucaT1** [xtermjs/xterm.js#835]
`Yarn` rewrites lines of the terminal, but works fine outside of xterm.
A gif is worth more than a thousand words:
![kapture 2017-08-03 at 22 24 09](https://user-images.githubusercontent.com/29304787/28943298-8cd41fd4-789e-11e7-9615-955bc5df33e7.gif)

## Details
- Browser and browser version: Chrome 59 or electron
- OS version: macOS Sierra
- xterm.js version: 2.9.0 (visible in the gif)

### Steps to reproduce

1. run the demo
2. run yarn installing a dependency or even the simple `yarn` command shows some overwriting errors

**Comment by Tyriar** [comment]
Seems to work just fine for me on the demo and using the [node-pty example](https://github.com/Tyriar/node-pty/tree/master/examples/electron) after upgrading to 2.9.0:

<img width="564" alt="screen shot 2017-08-03 at 2 20 45 pm" src="https://user-images.githubusercontent.com/2193314/28944301-f8b91cce-7856-11e7-9cc3-ae3fefd3fa55.png">

Any more details on your environment?

**Comment by LucaT1** [comment]
Happens also on the node-pty demo, and any other demo/app using xterm, but not in iTerm2 or Terminal.app
![screen shot 2017-08-04 at 00 18 49](https://user-images.githubusercontent.com/29304787/28946336-9411b020-78aa-11e7-8b8c-3fb2ddd05c3f.png)

I don't know what specific info about my environment could help you solve this, but here are some:
```
zsh --version 
zsh 5.2 (x86_64-apple-darwin16.0)
using oh-my-zsh with geometry prompt, but it's reproducible also on bash for me

bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

cat node_modules/xterm/package.json | grep version
  "version": "2.9.0"

yarn --version
0.27.5
```

**Comment by Tyriar** [comment]
I'm quite stumped at to what this could be, it's the only report so far. Does this happen when you install xterm@2.8.1 explicitly?

Also this happens in both bash and zsh for you? Any zsh plugins that could mess with it?

**Comment by LucaT1** [comment]
Yes, it also happens on bash with 2.9.0. Here's a side by side of an electron application using xterm and iTerm2:
<img width="1257" alt="screen shot 2017-08-04 at 11 56 26" src="https://user-images.githubusercontent.com/29304787/28964255-4d8f537a-790c-11e7-854f-35de92a88f62.png">
On the left side, there obviously was the bash prompt with the command `yarn add node-pty` but it was overwritten soon after.

For oh-my-zsh I only have installed [this highlighting plugin](https://github.com/zsh-users/zsh-syntax-highlighting) which shouldn't interfere with the rendering, and seeing that it works fine on iTerm2 makes me think it's a bug, though not reproducible for you.

Tried with `xterm@2.8.1` and it's still reproducible😕

**Comment by Tyriar** [comment]
@LucaT1 hmm weird. Could you try get as small of a repro case as possible (little output) and then open devtools, run `term.debug = true` in the console and then run the command and paste in the console output here?

It should give a bunch of output like this (on 2.9.0 only):

```
data: [?25l
C:\Users\Daniel\Documents\dev\Tyriar\xterm.js>d[0K
[48G[?25h
xterm.js:1901 CSI ? 25  l
xterm.js:1901 CSI  0  K
xterm.js:1901 CSI  48  G
xterm.js:1901 CSI ? 25  h
```

**Comment by LucaT1** [comment]
Yeah I'll try in a few minutes

**Comment by Tyriar** [comment]
I'm hoping this was fixed with xterm 3, let me know if you're still having issues.
