### ISSUE TITLE
Still seeing some errors with the Selection Manager in 2.9.0

### ISSUE THREAD

**Issue by vincentwoo** [xtermjs/xterm.js#838]
Here's a screenshot of a trace. It looks like a bad `line` value is getting fed to `translateBufferLineToString`:

![selection_issue](https://user-images.githubusercontent.com/613320/28988846-c0613e26-7926-11e7-9b06-306f00963855.png)

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
