### ISSUE TITLE
Update importing docs for v3

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#871]
https://xtermjs.org/docs/guides/import/

See changes in https://github.com/sourcelair/xterm.js/pull/868

**Comment by Tyriar** [comment]
This is blocked on https://github.com/xtermjs/xterm.js/issues/1018

**Comment by parisk** [comment]
This should be fixed now:

  - https://xtermjs.org/docs/guides/download/
  - https://xtermjs.org/docs/guides/import/
