### ISSUE TITLE
 Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [xtermjs/xterm.js#885]
## Details
- Browser and browser version:  59.0.3071.104 (Official Build) (64-bit)
- OS version: Ubuntu
- xterm.js version: 3.0 (branch 3.0), seems master too.

### Steps to reproduce
Maybe it's duplicated issue, but it's still stable reproducible inside VsCode and in the patched demo  https://github.com/sourcelair/xterm.js/pull/884.

Steps to reproduce:
1. Open terminal and type ls command few times while will appear scrollbar.
2. Open Midnight Command.
3. Do vertical resize to dicrease amount of the terminal rows.
4. With help Ctrl+O turn back to normal screen.

Actual behavior: Exception
VSCode:
Debugger listening on port 5870.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/095342d0-d8fb-4985-877a-5facf44e7fbe
index.js:41 [uncaught exception]: TypeError: Cannot set property '0' of undefined
onError @ index.js:41
index.js:44 TypeError: Cannot set property '0' of undefined
    at InputHandler.addChar (/home/antey/projects/vscode/node_modules/xterm/lib/InputHandler.js:58:75)
    at Parser.parse (/home/antey/projects/vscode/node_modules/xterm/lib/Parser.js:180:44)
    at Terminal.innerWrite (/home/antey/projects/vscode/node_modules/xterm/lib/xterm.js:825:33)
    at /home/antey/projects/vscode/node_modules/xterm/lib/xterm.js:810:18

Changed demo https://github.com/sourcelair/xterm.js/pull/884:
Uncaught TypeError: Cannot set property '0' of undefined
    at InputHandler.addChar (xterm.js:655)
    at Parser.parse (xterm.js:1974)
    at Terminal.innerWrite (xterm.js:3850)
    at xterm.js:3835

**Comment by Tyriar** [comment]
This might be https://github.com/sourcelair/xterm.js/issues/661
