### ISSUE TITLE
Cursor not visible initially (xterm 3.0) 

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#891]
In the demo with current xterm 3.0 branch the cursor is initially invisible. In fact, there isn't even a dom element for it. Once the terminal gets focused the cursor appears. Maybe this bug has always existed, but since we are not focusing initially anymore, it now becomes visible.

Initial:
<img width="815" alt="screen shot 2017-08-17 at 14 37 19" src="https://user-images.githubusercontent.com/2785983/29412589-bf689fb8-8359-11e7-97d1-8208c467853e.png">

Once focused:
<img width="813" alt="screen shot 2017-08-17 at 14 38 03" src="https://user-images.githubusercontent.com/2785983/29412598-c6ca62be-8359-11e7-8d43-49c2742866b4.png">

**Comment by Tyriar** [comment]
Nice find :smiley:

**Comment by AndrienkoAleksandr** [comment]
Nice find :), but it's a "normal" default behavior for master. @Tyriar Do you plan delete "focusKeys" option from xterm.js 3.0, I see it's commented?

**Comment by Tyriar** [comment]
I think `focusKeys` has been commented for a long time. The regression is most likely caused by https://github.com/sourcelair/xterm.js/issues/646

**Comment by mofux** [comment]
I'll try to create a PR for this, because not seeing the cursor at all seems like a bug to me. The cursor should be drawn in unfocused state imo. Btw. what does the focusKeys option do?

**Comment by Tyriar** [comment]
@mofux looks like it doesn't do anything. It doesn't in term.js either 😄  https://github.com/chjj/term.js/search?utf8=%E2%9C%93&q=focusKeys&type=

Created https://github.com/sourcelair/xterm.js/issues/897 for this

**Comment by Tyriar** [comment]
Fixed
