### ISSUE TITLE
Add tests for events on Terminal

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#900]
We should add some tests the events here https://xtermjs.org/docs/api/terminal/#events

**Comment by Tyriar** [comment]
Related: https://github.com/xtermjs/xterm.js/issues/1505

**Comment by peacefullatom** [comment]
Hello! I'd like to grab this.

Though, need some clarifications, because the link you provided in the first comment leads to nowhere 😃

**Comment by Tyriar** [comment]
@peacefullatom awesome! Here's the proper link now: https://xtermjs.org/docs/api/terminal/classes/terminal/#on, we want to do things that fire the events in `Terminal.test.ts` and make sure they're firing with the right data.

Note that the events will change in https://github.com/xtermjs/xterm.js/issues/1505, but I think we can just change the tests to point at the new events once that's done.
