### ISSUE TITLE
How should we include addons in typings?

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#916]
There are two ways, or we could do both:

1. Give typings for all addons on Terminal before they are loaded such that completions work for this:

   ```js
   term.findNext('foo');
   ```

   We would need to warn in the jsdoc about needing to call loadAddon first for this.
2. Give typings only for the object returned by loadAddon:

   ```js
   const searchAddon = Terminal.loadAddon('search');
   searchAddon.findNext('foo');
   ```

Or both?

**Comment by LucaT1** [comment]
I'd go for the first one.
A warning is more than enough, especially with TS compiler and I really dislike having to create a new variable just to use certain addons APIs. 
Further more the second way wouldn't break things like this?

```js
const term = new XTerm({...})
term.loadAddon('fit')

// Somewhere else in the code, for 
// example in another method of the same class
term.fit()
```

**Comment by Tyriar** [comment]
@LucaT1 the main thing I don't like about that is that then you get everything in completions, like attach, fit if you don't use them. Probably not that much of an issue really.

**Comment by LucaT1** [comment]
That' true. But since types are static i guess there's no other way😢either one or another, it's just a personal flavour. 
That's why allowing both makes sense and is probably the best solution, since it wouldn't cause any breaking change, just act as a small enchantment

**Comment by parisk** [comment]
What if we:

1. Implement typings for each add-on
2. Ditch `loadAddon`, in favor of standard import mechanisms
3. Expose each add-on's API as a component in Terminal (e.g. `term.attach`, `term.search` etc.)

Or is this too "loose" for TypeScript?

**Comment by Tyriar** [comment]
> Ditch loadAddon, in favor of standard import mechanisms

By this do you mean `import ... from 'addons/search';` at the top of the file? We wanted to avoid increasing the file size by excluding non-essential functionality right?

**Comment by parisk** [comment]
Basically, I was thinking something more like the following, in the consumer apps:

```javascript

import Terminal from 'xterm';
import * as search from 'xterm/addons/search';


Terminal.extend(search);  // Or something like that
```

**Comment by Tyriar** [comment]
This is stale
