### ISSUE TITLE
xterm doesn't appear to interact properly with typescript and requirejs

### ISSUE THREAD

**Issue by dgriffen** [xtermjs/xterm.js#917]
When using xterm with typescript set to compile to AMD modules xterm doesn't appear to interact properly with requirejs. A snippet of the typescript code is below

```typescript
import { Terminal } from 'xterm';

var someObject = new Terminal({
    cols: 80,
    rows: 24
});
```

The generated code looks like this:
```javascript
define(["require", "exports", "xterm"], function (require, exports, xterm_1) {
    var someObject = new xterm_1.Terminal({
        cols: 80,
        rows: 24
});
```

The problem is that the `xterm_1` object is actually the terminal object, so the code will fail at runtime. I tried playing with the definition file to get it to work but I did not have any success.

## Details
- Browser and browser version:  Firefox Nightly
- OS version: Windows 10
- xterm.js version: 2.8.1

**Comment by LoganDark** [comment]
Try importing `xterm` as `Terminal`, if that's possible. I believe `Terminal` is the only object that xterm exposes. Correct me if I'm wrong, I have never used TypeScript before and I have no knowledge of the inner workings of this library.

**Comment by Tyriar** [comment]
I'm consolidating all bundling/loadAddon related issues into https://github.com/sourcelair/xterm.js/issues/1018, please comment on that issue if you have thoughts :smiley:

**Comment by dgriffen** [comment]
I think this should be reopened. This still appears as an issue for me with version 3.1. It also seems to happen with SystemJS as well and doesn't matter if I compile to CommonJs modules, AMD or SystemJS modules. In all cases my compiled js code is handed an `xterm_1` object that it expects to have a `.Terminal` property representing the terminal constructor. Instead the `xterm_1` object is the `Terminal` object.

**Comment by Tyriar** [comment]
This is happening because of this file being the entry point for `dist/` https://github.com/xtermjs/xterm.js/blob/master/src/xterm.ts

I think it was necessary to get it working when including the dist file on a web page.

**Comment by dgriffen** [comment]
That's probably the case. I wonder if there is a way to get the best of both worlds. My initial thought would be to make Terminal be a property of itself (i.e. `Terminal.Terminal = Terminal`), but that is incredibly messy and awful looking.

**Comment by dgriffen** [comment]
I can solve it by adding something like the following to my code:

```typescript
import * as xterm from 'xterm';
const TerminalConstructor = xterm as any as (typeof Terminal);
```

from there I can `let terminal = new TerminalConstructor()` and everything works fine.

**Comment by Tyriar** [comment]
I'm not sure we can really do anything about this, it's happening because of the entry point xterm.ts which I think we still need. We're certainly not changing the typings and I wouldn't want to ship 2 copies. TypeScript users should generally be using the copy from `lib/` anyway.

I say let's stick with that workaround for now unless someone knows a better solution that doesn't compromise the current system or cause a bunch of extra maintenance burden.
