### ISSUE TITLE
Paste doesn't work in IE 11

### ISSUE THREAD

**Issue by goflatworld** [xtermjs/xterm.js#925]
## Details
- Browser and browser version: IE 11
- OS version: Windows 7
- xterm.js version: 2.0

### Steps to reproduce

Copy and paste works in Firefox, Chrome, Edge. It doesn't work in IE 11.

Goto: www.pickmyinfo.com

Username: demo@company1.com
Password: demotest1

Once you login, on the left pane, click and expand "Menu->Sydney->Stingray->Testing Router"
On the Right Pane, click "Connect".

After that, a new window popup and states: "Press Enter to Start.". You can test copy and paste in this window.

Thanks

George

**Comment by mofux** [comment]
The version of xterm you are using seems to be quite old. Could you try to update to the latest version of xterm.js and see if the problem still exists?

**Comment by Tyriar** [comment]
I'm closing this off to keep out issue count lower as it hasn't gained any traction, is stale or is not worth tracking.
