### ISSUE TITLE
InvalidStateError when attach addon attempts to send message to not CONNECTED socket

### ISSUE THREAD

**Issue by parisk** [xtermjs/xterm.js#929]
Seems like the [`attach` addon](https://github.com/sourcelair/xterm.js/blob/v3/src/addons/attach/attach.js) attempts to send messages to the socket, even if it is not ready yet.

I guess we could make a check before sending and either queue these messages and send them when the socket connects successfully, or reject them and display an error to the user.

---
## Details
- Sentry Error: https://sentry.io/sourcelair-pc/sourcelair-production/issues/338254774/
- Browser and browser version: Chrome 44
- OS version: Linux
- xterm.js version: 2.9.2

**Comment by Tyriar** [comment]
Fixed by #933?
