### ISSUE TITLE
Add new features to demo

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#939]
We should add new features to the demo:

- fontSize
- fontFamily
- lineHeight
- themes

**Comment by theflyingape** [comment]
FWIIW, I am finding that the client WebSocket does not receive an onclose() event. The demo/app.js might need this event listener added in its **app.ws()**:
```
  term.on('close', function() {
    ws.close();
  });
```

**Comment by Tyriar** [comment]
@theflyingape do you know if this would fix any bugs in the demo? Or is this just a general clean up thing?

**Comment by theflyingape** [comment]
Cleanup mainly.  If you type **exit** in the shell it presents, the running backend app.js does not handle the PID closing, which in turn does not pass on the ws.on('close') event for its cleanup: echoing a 'Closed terminal ' + pid status.  And a netstat confirms that the WebSocket remains ESTABLISHED between client/server without it.
