### ISSUE TITLE
Infinite scrollback

### ISSUE THREAD

**Issue by twifty** [xtermjs/xterm.js#948]
In https://github.com/sourcelair/xterm.js/issues/518 it was mentioned that a large number should be given. In most APIs, if we want to specify such an infinite number, we would either pass `-1` or `0`.

`xterm` causes an error for:
1. `scrollback: -1`, produces:  "Invalid array length"
2. `scrollback: 0`, produces: "cannot read index 0 of undefined"
3. `scrollback: Number.MAX_SAFE_INTEGER`, produces "Invalid array length"

It appears that JS arrays are limited to an unsigned 32 bit value.

A better approach would be to detect `scrollback <= 0 || scrollback > 4294967295` and assign it the max upper value of `4294967295`

**Comment by Tyriar** [comment]
:+1: PRs welcome
