### ISSUE TITLE
Startup and canvas render window resize that updates devicePixelRatio is expensive

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#955]
After https://github.com/sourcelair/xterm.js/pull/938

Repro:

1. Launch xterm.js

---

1. Open demo
2. Start performance timeline 
3. Press cmd/ctrl and + 3 times

<img width="147" alt="screen shot 2017-09-07 at 9 57 09 am" src="https://user-images.githubusercontent.com/2193314/30194318-4a5ded40-9407-11e7-8496-875e203375e5.png">

The reason this happens is because it redraws the char atlas, that's also the reason the time gets greater the more cmd/ctrl + is pressed (more pixels). This could be done using `OffscreenCanvas` and web workers for browsers that support?

**Comment by Tyriar** [comment]
The best solution to these two issues is to pull the CharAtlas generation into a web worker. This is blocked on OffscreenCanvas support so that we can draw on a worker thread.

The great thing about this solution is that the terminal can start drawing immediately just fine, the CharAtlas is just an optimization that can come in whenever and it will be picked up and used from that point on,.

**Comment by parisk** [comment]
Sounds good to me.

Just one question. From what I understand, the CharAtlas needs to be generated every time the zoom factor changes.

If this is true, is the web worker going to be an one-off process or something like a daemon waiting to be requested to generate a new CharAtlas? I think an one-off process would introduce less memory overhead overall.

**Comment by Tyriar** [comment]
One off process is what I'm thinking as it's generally a pretty infrequent thing. If they take a little while to spin up then we could add some time after it's stopped before terminating? (eg. ctrl++ multiple times)

**Comment by Tyriar** [comment]
There's an example of generating the char atlas using a web worker at https://github.com/Tyriar/xterm.js/tree/955_worker. I'll probably leave it there for now and wait for Electron to get a version out that supports `OffscreenCanvas`.

**Comment by mofux** [comment]
Nice! You can use `OffscreenCanvas` in `electron` already by enabling the `experimentalCanvasFeatures `:

```javascript
win = new BrowserWindow({
    width: 1200,
    height: 700,
    webPreferences: { experimentalCanvasFeatures: true }
})
```

https://stackoverflow.com/questions/47271240/can-experimental-features-like-offscreenanvas-be-enabled-in-electron

**Comment by Tyriar** [comment]
Not sure it would be wise to jump in that early though, there would be a lot of these blocked bugs in Chromium v59 https://bugs.chromium.org/p/chromium/issues/detail?id=563816

**Comment by mofux** [comment]
Seeing that list of open issues I agree it would be wise to wait until it becomes official 😅

**Comment by Tyriar** [comment]
I've seen reports of some of the initial frame draws to the terminal taking 3+ seconds, one way to help this could be to move the atlas stuff out to a worker. That way instead of a new uncached draw doing a draw to both the canvas and the atlas, it would just do the canvas and then request to atlas worker to cache the new char.

**Comment by Tyriar** [comment]
No plans to implement this for canvas renderer as we'll move towards the webgl addon that was just moved eventually
