### ISSUE TITLE
Canvas renderer cursor do not hide

### ISSUE THREAD

**Issue by tsl0922** [xtermjs/xterm.js#965]
Cursor may not hided sometimes with the canvas renderer.

## Details
- Browser and browser version: Chrome 60.0.3112.113
- OS version: MacOS Sierra 10.12.6
- xterm.js version: v3 HEAD

### Steps to reproduce

1. run `htop` (`brew install htop`)
2. or run `sl` (`brew install sl`)

### Screenshots

![image](https://user-images.githubusercontent.com/1680515/30250687-735905ec-9685-11e7-80a0-80bc7ac88bb4.png)
![image](https://user-images.githubusercontent.com/1680515/30250700-9f1bd056-9685-11e7-95be-89da58af2aa5.png)

**Comment by Tyriar** [comment]
Thanks for the report, I can reproduce.

**Comment by LoganDark** [comment]
`brew` is a macOS-specific package manager.

**Comment by tsl0922** [comment]
This does not happen on the latest master branch anymore, closing.
