### ISSUE TITLE
Text rendering is a little blurry still

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#985]
Notice "daniel" gets blurry a few rows down when compared to rows above. Changing the canvas height from 500 -> 501 seems to fix it so it's probably a problem with the `IRenderDimensions` generation.

![image](https://user-images.githubusercontent.com/2193314/30394569-451b8c32-9878-11e7-80db-c948ac8dbf59.png)

**Comment by vincentwoo** [comment]
Should this issue be closed now?

**Comment by Tyriar** [comment]
I can still see a little blurriness when zooming in, I think the calculation may be 1-2 pixels off when devicePixelRatio is a decimal.

**Comment by Tyriar** [comment]
I think this is fixed, if not it will come up again 😄

**Comment by Tyriar** [comment]
Just got a report for this: https://github.com/Microsoft/vscode/issues/55701

**Comment by saulcosta** [comment]
We are also experiencing this issue. Is there a fix planned, or are there any workarounds for the time being?

**Comment by Tyriar** [comment]
I can't repro this anymore, if you still see it please create a new issue with repro details.

**Comment by usernamehw** [comment]
In vscode it gets blurry a lot after resizing
```js
"window.zoomLevel": 1, 
"terminal.integrated.fontSize": 16,
```
The app is running with arguments, some of them: `--disable-smooth-scrolling --force-color-profile=srgb`

Workaround that works for me is to use a `dom` renderer:

```js
"terminal.integrated.rendererType": "dom",
```

**Comment by Tyriar** [comment]
@usernamehw created https://github.com/xtermjs/xterm.js/issues/2662 with an idea
