### ISSUE TITLE
Selection in terminal is offset by scrollTop of a parent element

### ISSUE THREAD

**Issue by panickos** [xtermjs/xterm.js#993]
When the terminal is inside a scrollable container which is in turn nested in another container, the selections get messed up when the container is scrolled upwards.

Example here: https://files.gitter.im/sourcelair/xterm.js/Sklp/xterm.js-selection.mov

## Details
- Browser and browser version: Google Chrome 60.0.3112.113
- OS version: Mac OS Sierra
- xterm.js version: 2.9.2

### Steps to reproduce

1. Add a terminal into a scrollable container
2. Scroll the container up.
3. Try to make a selection in the terminal
     You''ll notice that the selection is offset by how much the container is scrolled.

I believe the problem is in this function:

```typescript
export function getCoordsRelativeToElement(event: MouseEvent, element: HTMLElement): [number, number] {
  // Ignore browsers that don't support MouseEvent.pageX
  if (event.pageX == null) {
    return null;
  }
  let x = event.pageX;
  let y = event.pageY;
  // Converts the coordinates from being relative to the document to being
  // relative to the terminal.
  while (element && element !== self.document.documentElement) {
    x -= element.offsetLeft;
    y -= element.offsetTop;
    element = 'offsetParent' in element ? <HTMLElement>element.offsetParent : <HTMLElement>element.parentElement;
  }
  return [x, y];
}
```

The while loop doesn't take into account the fact that some of the parent elements may have a non-zero `scrollTop` or `scrollLeft` which should be subtracted from `y` and `x` respectively.

**Comment by nikonso** [comment]
I believe this was fixed by #910...
